### ISSUE TITLE
Klarere Formulierung der Zahl der aktiven Tage

### ISSUE THREAD

**Issue by Marvodor** [corona-warn-app/cwa-wishlist#101]
## Current Implementation

Die jetzige Darstellung „## von 14 Tagen aktiv“ ist verwirrend, besonders, wenn sich die erste angezeigte Zahl über mehrere Tage nicht ändert.

Es begegnen mir immer wieder Anwenderinnen und Anwender, die klar erkennen lassen, dass sie den Sinn der Aussage in ihrer jetzigen Form nicht verstehen.

## Suggested Enhancement

Die Anzahl der Tage, in denen die App in den letzten zwei Wochen aktiv war, sollte auch so angezeigt werden: „Ihre App war in den letzten 14 Tagen an ## Tagen aktiv.“

## Expected Benefits

Bessere Akzeptanz der App, weniger Misstrauen durch Verringerung unverständlicher Informationen.

---------
Internal Tracking Id: EXPOSUREAPP-2098

**Comment by kangaroocry** [comment]
Auch ich finde, dass die derzeitige Formulierung missverständlich und verwirrend sein kann. Das liegt meiner Ansicht nach an drei Hauptproblemen.

1. "von 14 Tagen" ist weder erklärt, noch selbsterklärend. Dass es sich um die "letzten 14 Tage" handelt,

Allerdings würde auch die vorgeschlagene Formulierung „Ihre App war in den letzten 14 Tagen an ## Tagen aktiv.“ Fragen aufwerfen... War sie an x Tagen rund um die Uhr aktiv, oder war sie an x Tagen mindestens einmal aktiv? Tatsächlich handelt es sich ja um eine Zeitdauer, angegeben in Tagen (als Zeiteinheit 1 Tag = 24 Stunden). Genau hier liegt aber das Problem, dass "Tage" klassischerweise nicht als Zeiteinheit gesehen werden. Ich würde daher vorschlagen, weg von den Tagen zu gehen. Eine andere Zeiteinheit ist aber auch problematisch, wer würde beispielsweise schon auf Anhieb wissen, wie viele Stunden in 14 Tagen eine komplette Aktivität bedeuten würde (336h).
Ich schlage eine relative Angabe in % vor, das ist intuitiv und selbsterklärend, beispielsweise: "Ihre Kontaktverfolgung war in den letzten 14 Tagen zu [x]% aktiviert." Oder etwas prägnanter: "[x]% aktiv in den letzten 14 Tagen"

**Comment by kangaroocry** [comment]
Auch ich finde, dass die derzeitige Formulierung missverständlich und verwirrend sein kann. Das liegt meiner Ansicht nach an drei Hauptproblemen.

1. Der Sinn der Anzeige ist nicht erklärt. Dass es sich um eine reine Information zur Einschätzung der Arbeitsbedingungen/Effektivität der App in den letzten Tagen handelt, wird nicht ganz klar. Es sieht eher danach aus, als würde man "Punkte" sammeln, die irgendetwas bewirken und irgendwann "voll" sind.
1. "von 14 Tagen" ist weder erklärt, noch selbsterklärend. Dass es sich um die "letzten 14 Tage" handelt, muss nicht jedem sofort klar sein und sollte explizit ausgeschrieben werden (so wie vom Ersteller dieses Issues vorgeschlagen).
1. "Tage" als Einheit einer aufaddierten Zeitspanne zu benutzen, wirft Fragen auf. War sie an x Tagen rund um die Uhr aktiv, oder war sie an x Tagen mindestens einmal aktiv? Tatsächlich handelt es sich ja um eine Gesamtzeitdauer, angegeben in Tagen (als Zeiteinheit 1 Tag = 24 Stunden). Genau hier liegt aber das Problem, dass "Tage" klassischerweise nicht als Zeiteinheit gesehen werden. Ich würde daher vorschlagen, weg von den Tagen zu gehen. Eine andere Zeiteinheit ist aber auch problematisch, wer würde beispielsweise schon auf Anhieb wissen, wie viele Stunden in 14 Tagen eine komplette Aktivität bedeuten würde (336h). Ich schlage eine relative Angabe in % vor, das ist intuitiv und selbsterklärend.

Aus meiner Sicht bessere Formulierungen wären daher zum Beispiel

- "Ihre App war in den letzten 14 Tagen zu [x]% aktiv."
- "Ihre App war in den letzten 14 Tagen in [x]% der Zeit aktiv."
- "Aktivitäts-Status: [x]% in den letzten 14 Tagen"
oder ähnlich.

**Comment by SonaliDK** [comment]
Hi @Marvodor,

Thank you for your proposal. All issues in the cwa-wishlist repository will be discussed with our contracting entities. They will decide whether they will be implemented or pursued further. As soon as we have any updates, we will let you know about the details.

Best regards,

SD

Corona-Warn-App Open Source Team

**Comment by GPclips** [comment]
Hello @Marvodor ,

please see https://github.com/corona-warn-app/cwa-wishlist/issues/102.

Thanks,
LMM

Corona-Warn-App Open Source Team
