### ISSUE TITLE
Add Germany

### ISSUE THREAD

**Issue by quaddy-services** [corona-warn-app/cwa-wishlist#107]
Da die Seite 
https://www.coronawarn.app/en/faq/#international
in Englisch ist, könnte man meinen in Germany würde es die corona-warn-app gar nicht geben (insbesondere, wenn der Play-Store mal wieder sagt "Dü gübt es hür leidör nücht": https://github.com/corona-warn-app/cwa-app-android/issues/830 ).

Hier sollten bitte tatsächlich **alle** Länder auftauchen.

Gleiches gilt natürlich für die anderen Übersetzungen: https://www.coronawarn.app/de/faq/#international usw.

**English translation:**
Add "Germany", please.

**Comment by tkowark** [comment]
Closed with https://github.com/corona-warn-app/cwa-website/pull/196
