### ISSUE TITLE
Availability Outside German App Store

### ISSUE THREAD

**Issue by notsostubby** [corona-warn-app/cwa-wishlist#11]
## Feature description

Make app available to global app store users

## Problem and motivation

A large number of expats and military personnel live and work in Germany for short periods of time and typically leave their app store set to their home country.  As changing app stores can occasionally be difficult and cumbersome, making the Corona-Warn app would make it far easier for those individuals to participate in the system while inside of Germany.

## Is this something you're interested in working on

Unable To.

**Comment by lukasziegler** [comment]
The same issue is true for cross-border commuters (e.g. for people living in Austria and working in Germany) and tourists who want to use the German app while spending a week(end) in Germany.

The usage of the app should not be limited to the country which is set in the app store.

**Comment by berdario** [comment]
This unfortunately has already been rejected, see:

https://github.com/corona-warn-app/cwa-app-ios/issues/623

https://github.com/corona-warn-app/cwa-backlog/issues/9

They'll only enable it country-by-country :(

**Comment by SebastianWolf-SAP** [comment]
Dear colleagues,

as we have this new process now, we will close this generic issue. Please create issues and vote on country by country as outlined on https://github.com/corona-warn-app/cwa-backlog/issues/9#issuecomment-648745301

Thanks for your understanding!

Mit freundlichen Grüßen/Best regards,
SW
Corona Warn-App Open Source Team
