### ISSUE TITLE
Test result notification for Devices without EN API

### ISSUE THREAD

**Issue by weather-kr** [corona-warn-app/cwa-wishlist#111]
One advantage of the App is to get fast rest results from COVID-19 tests in a lab. See related article from BR: "Rhöner Labor übermittelt Testergebnisse schnell via Corona-App"

## Current Implementation
Currently it is only possible to install the APP on devices with EN API. App is not supported on IPad or IPhone 5S or old Android devices

## Suggested Enhancement
A fork of the exisiting IOS or Android App might be created or published, that does not rely on the Exposure Notification API.

## Expected Benefits
People with Devices that are not supported yet will also get fast results for Testresults

Reference:
https://www.br.de/nachrichten/bayern/rhoener-labor-uebermittelt-testergebnisse-schnell-via-corona-app,S4D5qxJ

----------------
Internal Tracking Id: EXPOSUREAPP-2063

**Comment by SonaliDK** [comment]
Hi @weather-kr  ,

Thanks for your suggestion. All issues in the cwa-wishlist repository will be discussed with our contracting entities. They will decide whether they will be implemented or pursued further. As soon as we have any updates, we will let you know about the details.

Best regards,
SD
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Maybe this issue could be merged with  #464?

**Comment by larswmh** [comment]
Closing this issue as its related internal ticket was set to obsolete.

> Technically not possible.

**Comment by Ein-Tim** [comment]
@larswmh Mh, why is this technically not possible. For sure, you'd had to change things in the app, but it is not impossible.
