### ISSUE TITLE
Bad UX. "Risiko Begegungen" are not reflected in the "Risiko Status"

### ISSUE THREAD

**Issue by yanosz** [corona-warn-app/cwa-wishlist#113]
## Current Implementation
Presumably harmless encounters (e.g. short distance, short time), are displayed as risky "Risiko-Begungen". Nevertheless, they do do not have a noticeable impact on the risk status (e.g. green).

This is confusing. It is warning people about risky things, but the risk doesn't change.

## Suggested Enhancement

Reconsider the UX, for instance:
* Relable "Risiko Begegnungen" to "~Mögliche Risiko Begegnungen~" "Infizierten Begegnungen"
* ~Show seperate counters "Risiko Begegnungen" and "Nicht Risiko Begegungen"~
* If risk is expressed by one comportment (i.e. counter) it should by reflected by all other components (e.g. total status)

Rule of thumb: If there's a risk solely triggered by presumably harmless encounters, than it has to be reflected in the total risk status, e.g. Relabel the risk status to "Leicht Erhöht", when encountering such contacts.

## Expected Benefits
UI-Consistency:
* Better user acceptance by less confusion

--------
Internal Tracking Id: EXPOSUREAPP-2061

**Comment by daimpi** [comment]
Related: #100

**Comment by akuckartz** [comment]
Maybe change "Risiko Begegnungen" to something like "Begegnungen mit Infizierten", that is: remove "Risiko" from that text.

**Comment by yanosz** [comment]
Now its called "Risiko-Begegnung mit niedrigem Risiko" 

* The text is rather long'ish taking to lines on my screen - "Begegnung mit niedrigem Risiko" would be better, imho
* Still, the general UX problem remains. The user is warned and informed, but the risk assesment remains unchanged. That doesn't male much sense to me. A quick-fix could be to place this information outside the risk assessment field, do not mention "Risiko" in the label. Also outlining that this counter is show solely for information purposes.

**Comment by yanosz** [comment]
The associated confusion hit mainstream media: https://www.tagesschau.de/inland/corona-warn-app-risikoermittlung-101.html

**Comment by daimpi** [comment]
@yanosz are your concerns mitigated by the [new texts](https://github.com/corona-warn-app/cwa-backlog/issues/23#issuecomment-682485410) which are live for a while now?

If so feel free to close this issue 🙂.

**Comment by yanosz** [comment]
@daimpi - I don't see any relevant change: The initial problem remains. The Apo lists risky things "1 Begegnung mit geringem Risiko" but the risk status "green" does not change. 

As I said before: If there is a risk by these encouters, this has to be reflected in the total risk status. But in the new screens, the risk relfected in the text componenent is not reflected in the card component (green). The generated confusion is discussed at various web pages.

* https://www.rundschau-online.de/ratgeber/digital/corona-warn-app-wie-gefaehrlich-sind-viele-begegnungen-mit-niedrigem-risiko--37478326
* https://www.tagesschau.de/inland/corona-warn-app-risikoermittlung-101.html
* https://www.corodok.de/app-risiko-ohne-risiko/

Trying to do some "Think aloud" (https://en.wikipedia.org/wiki/Think_aloud_protocol), I come of this these questions

* Why is it called "Risiko Begungen" and not "Begegnungen mit Infizierten"? Is there a subtential difference? If so, which?
* Is there a "geringes Risiko" originating from presumable low-risk encounters? In case its not: this is not a "Risiko Begegung" - why is it called "Risiko Begegnungen", then?
* Why is the risk still "green"? What is the exatct reason? 
   * How can I estimate my personal risk? 
   * How can I get more Information on the encounter? When was it? Who was infected?
   * How many "Begegnung mit niedrigem Risiko" are fine? 1? 10? 100? 1000? Per day, per week, at all?
* What's the chance, that the App is wrong and a transmission occured anyway?

Some ideas:
* If the counter is not used for estimating the total risk, it should be placed outside the green-red card, cause the card is where people expect information on this. If it is, the actual, statistical impact should be outlined.
* The App could inform tech savvy users about 3rd party possibilites for retrieving more details (e.g. https://github.com/mh-/corona-warn-companion-android)
* Avoid "Risiko" in the label. It is used to name different things:
   * A statistics related counter
   * The risk of a transmission
  There is a clear difference between these two concepts. They should be named differently.

**Comment by Ein-Tim** [comment]
@yanosz 

Just a small remark from me:
Did you see that the App now calls it "Begegnungen mit niedrigem Risiko"?

**Comment by yanosz** [comment]
> @yanosz
> 
> Just a small remark from me:
> Did you see that the App now calls it "Begegnungen mit niedrigem Risiko"?

Yes.

**Comment by rugk** [comment]
Also there is a huge long explanation text if you tap on the card.

> Will the counter decrement again? When does it do so? Why is it decremented after n days?

Yes, if the "Risikobegenung" is longer than 14 days ago.

**Comment by yanosz** [comment]
> Also there is a huge long explanation text if you tap on the card.
> 
> > Will the counter decrement again? When does it do so? Why is it decremented after n days?
> 
> Yes, if the "Risikobegenung" is longer than 14 days ago.

this somehow misses the point of the think aloud protocol. These questions should be answered in the App, not on github...

The question is raised, because the relationship of "für ihre Risikoermittlung wird nur der Zeitraum der letzten 14 Tage betrachtet" and "Dennoach als niedrig eingestuft" is confusing. IMHO it is not comprehensible, to what extent the counter is impacting the estimated risk ... and if the note on "14 days" also applies to the counter.

E.g. having "in der Corona-App wird nur der Zeitraum der letzten 14 Tage betrachtet" is better, imho.

**Comment by yanosz** [comment]
> > Also there is a huge long explanation text if you tap on the card.

Correct - some wall-of-text / tl;dr style of message.

> > > Will the counter decrement again? When does it do so? Why is it decremented after n days?
> > 
> > 
> > Yes, if the "Risikobegenung" is longer than 14 days ago.
> 
> this somehow misses the point of the think aloud protocol. These questions should be answered in the App, not on github...
> 
> The question is raised, because the relationship of "für ihre Risikoermittlung wird nur der Zeitraum der letzten 14 Tage betrachtet" and "Dennoch als niedrig eingestuft" is confusing. IMHO it is not comprehensible, to what extent the counter is impacting the estimated risk ... and if the note on 14 days also applies to the counter.
> 
> E.g. having "in der Corona-App wird nur der Zeitraum der letzten 14 Tage betrachtet" is better, imho.

**Comment by yanosz** [comment]
P.S.  I'd like to make this explicit https://www.corodok.de/app-risiko-ohne-risiko/ boils it down to:

"Es gibt also eine Warnung, bei der man nichts tun muß, ein Risiko ohne Risiko."

IMHO this is also a good way of describing the associated confusion

**Comment by Ein-Tim** [comment]
@yanosz 
So looks like you are against showing low risk exposures at all? 
Maybe take a look at: https://github.com/corona-warn-app/cwa-wishlist/issues/181

**Comment by yanosz** [comment]
Heiho,

> @yanosz
> So looks like you are against showing low risk exposures at all?
> Maybe take a look at: #181

I proposed to relabel it. It's fine to have such a counter. But this value is way too "raw" to express some kind of risk. It's a parameter for calculating the risk. It does not express any risk by itself. ... just give it a proper label.

Take it this way:
Everybody understands, that she or he encounteres infected people if there are a lot. You can explain this and everything is fine.
This basically shows that the App is working fine and that other people are using the app to protect each other. Thats good!

The point is, that the App mistankenly suggest, that this value determinessome total risk to a certain, comprehensible higher degree. It is not.

**Comment by webermike** [comment]
Please show Date and Time of later on announced risk contacts, even if this leads to still having a green status.

As such contacts might occur only at shopping or eating in a restaurant, one can reconstruct with Date and Time where one habe been and if shopping or queuing anywhere is the risk reason.

This would enhance the analyse and discussion and avoiding of behavior in the future much, when it ia shown if the risk contact was at 8:00 in the bus ir at 12:00 in the McDonalds restaurant or at work at 10:00 o'clock at a certain date/day.

so it is not about "10 days ago" but about exact time and day.

Thanks for implementing that local showup fast.

**Comment by yanosz** [comment]
> Please show Date and Time of later on announced risk contacts, even if this leads to still having a green status.

Unfortunatly, this is OT as this issue. Please check other, already existing issues or have a look at https://github.com/mh-/corona-warn-companion-android

**Comment by yanosz** [comment]
Mainstream media still is still discussing the issue, while the bug is still rotting in the tracker:

https://taz.de/Unverstaendliche-Corona-Warn-App/!5735104/

**Comment by heinezen** [comment]
With ENFv2 used in the newest app version, some of the suggestions were addressed: Harmless encounters with distance > 8m (73dB signal strength) and duration of less than 10 minutes are filtered out by the app and are not displayed as risk encounters. See https://www.coronawarn.app/en/faq/#encounter_count_19 for details.

----
Corona-Warn-App Open Source Team

**Comment by yanosz** [comment]
> With ENFv2 used in the newest app version, some of the suggestions were addressed: Harmless encounters with distance > 8m (73dB signal strength) and duration of less than 10 minutes are filtered out by the app and are not displayed as risk encounters. See https://www.coronawarn.app/en/faq/#encounter_count_19 for details.
> 
> Corona-Warn-App Open Source Team

Sure about the ticket? That's not suggested in in this one.

**Comment by heinezen** [comment]
@yanosz Yes, in particular, harmless encounters are now filtered and multiple low risk encounters count towards a total risk score that can lead to an overall high risk.

----
Corona-Warn-App Open Source Team

**Comment by yanosz** [comment]
> @yanosz Yes, in particular, harmless encounters are now filtered and multiple low risk encounters count towards a total risk score that can lead to an overall high risk.

@heinezen : To avoid misunderstandings: Filtering harmless encounters is not part of this ticket. This ticket addresses the UX mismatch between risk expressed in different components. The "risk" expressed by the status "green" is not reflected in the risk expressed by the counter that counts "risk" encouters. The proposal is to rename "risk encounters" to "infectious encouters", because the counter value is raw, i.e. it does not express risk to some determined and comprehesinble degree.

Are status and counter aligned as of now? I.e. does an increasing counter result in risk status red as of now?




> 
> Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
@yanosz You mentioned harmless encounters in your introduction, so I thought this information would be useful here. Sorry if it was confusing.

> Are status and counter aligned as of now? I.e., does an increasing counter result in risk status red as of now?

Yes! This is what I wanted to say. The ENFv2 evaluation considers multiple this now. The normalized exposure time of low risk encounters is summed up for the day. So multiple low risk encounters will lead to a high risk score if the sum of their individual score is higher than the "high risk" threshold.

See here for more information: https://github.com/corona-warn-app/cwa-documentation/blob/master/images/risk_calculation/risk_calculation_enf_v2_overview.pdf

**Comment by ndegendogo** [comment]
> So multiple low risk encounters will lead to a high risk score if the sum of their individual score is higher than the "high risk" threshold.

I think the confusing fact is, that the number shown is **not** the sum of the risk scores.
cwa before version 1.9 showed **number of encounters**. As far as I understand, since v 1.9 it will show **number of days** with encounters. But the *risk score* is still hidden from the user.

**Comment by yanosz** [comment]
closed, fixed
