### ISSUE TITLE
Missing release Info

### ISSUE THREAD

**Issue by FranzBumes** [corona-warn-app/cwa-wishlist#114]
## What is missing
As there was a new release of the android war app for android, I searched for any releaseinformation.
Unfortunately I did not find any. 

Additional there could be a list of planned releases, with timeframe and issues as possible.
I would be interested e.g. when opportunistic scanning will be available, or when there will be others languages avalable.

## Why should it be included
To explain to the public, Information of changes ist essential. This should be easy available.
It helps to know which Bugfixes, new features, changes in existing features are done.

## Where should it be included
As the App is automatically updated, Releaseinfos should be reachable from the App. 
It could be a Link to a Webpage or similar.
Even a short description ( maybe with a link to github issues) would be great.

---
Internal Tracking ID: EXPOSUREAPP-2076

**Comment by FranzBumes** [comment]
Thanks for the link

**Comment by Ein-Tim** [comment]
I think this is solved? 
Release Infos can be found in the respective App Store and here on GitHub in the respective Repo.

**Comment by FranzBumes** [comment]
As there will be  release information within the app, the ticket is solved. 
Will there be information about future releases within corona-warn-app/cwa-app-android#2106?

**Comment by Ein-Tim** [comment]
@FranzBumes 
> Will there be information about future releases within corona-warn-app/cwa-app-android#2106?

Yes, this PR implements that.
