### ISSUE TITLE
Make Corona Warn App available for older Iphones

### ISSUE THREAD

**Issue by dstntsun** [corona-warn-app/cwa-wishlist#116]
The app only works for Iphones 6S and above, because those older i.e. Iphones 6 and below, cannot update to iOS 13, which is a requirement of the Corona Warn App.

I would like to use the app, but I am not able to.

Thanks,

Peter

## Expected Benefits

---------
Internal Tracking Id: EXPOSUREAPP-2064

**Comment by weather-kr** [comment]
I also own only Apple devices which do not support the EN API (IPhone 5s and IPad Mini 2019). Both devices support BLE (Bluetooth Low Energy).

I tried the french StopCovid app, which is supported on both devices. But this shows a big drawback of the french solution: The App only sends the BLE messages if it is actively running. This is visible if you are tracking the BLE messages with python.

As long as Apple does not support the API on old Iphones or IPad, there will be only limited use for the CWA app on these devices. 

One usecase would be the fast notification when doing a Covid19 test at a testcenter with barcode support. See also enhancement request #111.



EN API= Exposure Notification
https://www.macworld.com/article/3545329/apples-covid-19-exposure-notification-api-what-it-is-and-how-it-works.htm

Tool for tracking BLE messages:
https://github.com/mh-/exposure-notification-ble-python

**Comment by SonaliDK** [comment]
Hi @dstntsun,

Thanks for your suggestion. All issues in the cwa-wishlist repository will be discussed with our contracting entities. They will decide whether they will be implemented or pursued further. As soon as we have any updates, we will let you know about the details.

Best regards,
SD
Corona-Warn-App Open Source Team

**Comment by GPclips** [comment]
Hello @dstntsun,

please see the following article https://www.coronawarn.app/de/faq/#ios135.

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@GPclips 
I think it's not right to close this Issue since @dstntsun clearly stated:

> The app only works for Iphones 6S and above, because those older i.e. Iphones 6 and below, cannot update to iOS 13, which is a requirement of the Corona Warn App.

>I would like to use the app, but I am not able to.

And since this is the **Wish**list Repo I think this should stay open until 
a) there is a final decision to **never** support older devices or
b) to support them

Cheers
