### ISSUE TITLE
UX Is the App already tracking?

### ISSUE THREAD

**Issue by mrascher-cosee** [corona-warn-app/cwa-wishlist#122]
## Describe the issue
I opened the App an read all information. After that i came to the main screen. And then there was no information about my tracking. Is the tracking already on? Should i activate something? 

## Suggested change
Probably you need a bigger indicator for an active tracking. Like a radar or some animation. After that the users knows the tracking is active and it will find all persons around me.

**Comment by tkowark** [comment]
Thanks for the proposal. With https://github.com/corona-warn-app/cwa-wishlist/issues/5 we already have a similar proposal that would also fulfil your request. Hence, we'll focus discussion on this one.
