### ISSUE TITLE
Publish number of "positive transmitter" key days on website as metric to show app success

### ISSUE THREAD

**Issue by corneliusroemer** [corona-warn-app/cwa-wishlist#125]
It would be fantastic to have a metric publicly available that shows how successful the app is.

One very relevant metric you must have access to is how many keys of positively tested individuals have been uploaded and shared. This may allow you to approximately infer how many people have reported results through the app. This would very surely interest very many people and be easy to do. It would show that the app is a success and inspire more to download it.

Additional candidate metrics:
- App downloads
- Total number of days for which app was active (across all users)
- more that I can't think of right now (community, please contribute)

---
Internal Tracking ID: EXPOSUREAPP-2059

**Comment by dsarkar** [comment]
FYI - PR https://github.com/corona-warn-app/cwa-app-android/pull/2043

**Comment by heinezen** [comment]
This was integrated into the app as part of CWA release 1.11. A statistics is shown for the number of shared results in the last 7 days. We will close this issue now. Please create a new issue for other statistics-related feature requests.

----
Corona-Warn-App Open Source Team
