### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-wishlist#137]
## Avoid duplicates

* [x] This issue has not already been raised before
* [x] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

I like your error messages, they give technical info (like error code), and are very user friendly (link to explanation and suggestions how to procede).

## Suggested Enhancement

Still they could be enhanced, making it easier to track down rare error scenarios:

- add a timestamp, enabling the user to give more precise information about special context / conditions in his error reports.
- add current cwa version, to avoid misleading / wrong infos. cwa updates automatically in the background, without the user involved, and has other background tasks like risk calculation, so the user cannot be sure in all cases which cwa version encountered an error.
- collect a (small) history of error messages. I have sometimes seen two error messages in very short time, and could only read the second; but maybe the first has useful information that should not be lost.

## Expected Benefits

Easier analysis of errors, more info to track down rare error scenarios.

**Comment by GPclips** [comment]
Hello @ndegendogo ,

thank you very much for your proposal.
To give the community a space for discussing new feature ideas or enhancements that might not be taken up immediately by the development teams, we created the cwa-wishlist repository.

This idea is one of these feature ideas or enhancements. Consequently, we will move this issue to this repository and allow the community and you to further refine it, discuss pros and cons, and evaluate alternatives.

The issue will not be closed in this repository to ensure long-term visibility. All issues in the cwa-wishlist repository will be discussed with our contracting entities. They will decide whether they will be implemented or pursued further. As soon as we have any updates, we will let you know about the details.

Best regards,

LMM
Corona-Warn-App Open Source Team

**Comment by GPclips** [comment]
This message is related to https://github.com/corona-warn-app/cwa-wishlist/issues/112 and will be closed as a duplicate. @ndegendogo please feel free to share your additional thoughts here: https://github.com/corona-warn-app/cwa-wishlist/issues/112
