### ISSUE TITLE
Allow users to switch off warnings when phone logs into foreign mobile phone network provider

### ISSUE THREAD

**Issue by carstenmehring** [corona-warn-app/cwa-wishlist#14]
## Current Implementation

The app seems to send a warning notification if the phone logs into a foreign mobile phone network. For a user living in an area close to the German border this notification is received very often despite the user remaining in Germany.

## Suggested Enhancement

Allow users to switch off the warning in general or for certain foreign mobile phone network providers.

## Expected Benefits

More pleasant use of the app.

**Comment by cfritzsche** [comment]
Can you post a screenshot of the warning? I suspect that it’s a warning from iOS I have also already received about COVID protocol not being active in this country even though I live nowhere close to a border.

**Comment by carstenmehring** [comment]
Maybe it has nothing to do with foreign mobile phone networks but today it happened again when the mobile phone was connected to a foreign network. Here are the screenshots:

![1](https://user-images.githubusercontent.com/48163946/85233550-85284100-b407-11ea-9e96-ed8c1fa578a1.jpg)
![2](https://user-images.githubusercontent.com/48163946/85233551-86f20480-b407-11ea-9edc-a777b59f714d.jpg)
![3](https://user-images.githubusercontent.com/48163946/85233553-89545e80-b407-11ea-9481-230993f630ee.jpg)

**Comment by cfritzsche** [comment]
Yes I have gotten the same warning about twice per week, even with the TestFlight of SwissCovid that I ran before. I think this should be reported to Apple if it wasn't already. Anyway I don't think its a feature request so it's better to move this to the ios repo?

**Comment by carstenmehring** [comment]
Ok, thanks. Maybe best if the app developers report that to Apple. It may confuse users even if it does not affect the app's exposure logging (which I don't know).

**Comment by cfritzsche** [comment]
I found this [issue which already covers it in ios repo](https://github.com/corona-warn-app/cwa-app-ios/issues/645#issuecomment-644876375). It is already known and being worked on at Apple.

@tkowark Suggest to close this issue here.

**Comment by tkowark** [comment]
Yes, good point. This issue is know at Apple and at least we heard from some people that it does not occur with the ios 13.6 beta. So finger's crossed that this will solve itself quite soon.
