### ISSUE TITLE
Registration of restaurant visitors

### ISSUE THREAD

**Issue by DirkReu** [corona-warn-app/cwa-wishlist#140]
When entering a restaurant (or similar place), There should be an easy way to register.
Use the app to scan a qr code of the location, so the app then knows the time entering and later on scan a second time when leaving.

This could speed up the work for the 'Gesundheitsamt' to reach all persons. When the office enters information about a covid 19 case in the restaurant with date and time of the visit of the infected person, all others that have logged in with their app can get the warning directly. This could speed up the warning of visitors.

When now app-warned visitors can give feedback when they received the warning, the Gesundheitsamt can reduce the number of calls for contact tracing.

**Comment by SebastianWolf-SAP** [comment]
We already have a very similar idea in the wishlist with #138. Please check the other idea and consider closing this one in order to avoid duplicates.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by DirkReu** [comment]
This is a different approach to #138, both have the same goal. The better/simpler solution should be implemented to have a quick win in:
- wider usage of the app
- making work for contract tracing easier
- make warnings for app users faster
- increase the acceptance of contact tracing lists
>
