### ISSUE TITLE
Display of planned update should be more precise

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-wishlist#142]
## Avoid duplicates
* [X] This enhancement request has not already been raised before
* [X] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

The risk card shows "Updated daily" at the bottom when a background update process is running.

## Suggested Enhancement

The information about the next planned update should be more precise, such as:
Updated daily: next update planned today / tomorrow at nn:nn or
Updated daily: next update planned today / tomorrow between nn:nn and nn:nn 

## Expected Benefits

The additional timing information about when the next risk update is planned to take place would increase user confidence in the predictability of the app's working.

It seems for instance that the background update timings are unaffected by a risk update triggered by opening the app. Instead of the next background update taking place around 24 hours after the last update (whether automated in the background or run in the foreground) the background update looks like it just happens around 24 hours after the last **background** update.

---
Internal Tracking ID: EXPOSUREAPP-2032

**Comment by MikeMcC399** [comment]
@RoxanaVuc 
Sorry for not posting directly to https://github.com/corona-warn-app/cwa-wishlist/issues and thank you for moving.

I am confused though by:
>The issue will not be closed in this repository to ensure long-term visibility.

and the fact that the enhancement request has been closed. Will it still be considered?

**Comment by SebastianWolf-SAP** [comment]
Hi @MikeMcC399,

sorry that we closed this issue. Of course, we keep this one open. :)

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
According to https://www.coronawarn.app/en/blog/2020-11-25-corona-warn-app-version-1-7/

"With Corona-Warn-App Version 1.7, the exposure check can be run several times a day so that users are informed about possible risk encounters sooner. This repeated daily check is performed automatically. However, it requires a Wi-Fi connection. The standard daily exposure check is still performed once a day, no matter if the smartphone is connected to a Wi-Fi network or not."

The FAQ link on the main screen of the app to https://www.bundesregierung.de/corona-warn-app-faq-englisch also explains under "What has improved with the updates?":

"Version 1.7 means that the risk check can now be performed several times a day, so that users are informed more quickly about potential risk contacts. These multiple daily checks are performed automatically. However, the smartphone does need a WiFi connection to do so. The standard, daily risk check will continue to be performed once a day, regardless of a WiFi connection."

Starting with CWA Android 1.7.0 the risk card no longer displays general text about when updates are being carried out. (In 1.6.1 it still showed "Updated daily".)

I withdraw this wishlist item. If the app does not specify about how often updates are carried out, then it does not need to be more specific about when they occur. The above mentioned FAQ entry explains the update frequency instead.
