### ISSUE TITLE
Add a warning during removing a test result

### ISSUE THREAD

**Issue by MartinEderer** [corona-warn-app/cwa-wishlist#144]
## Current Implementation
The QR code can only be loaded once, which I didn't know.
I deleted my not yet evaluated pcr test as I wanted to load it on my other smart phone.
I can not get (online) access to my test result at all and the telephone hotline can not help as well

## Suggested Enhancement
a) Multiple warnings in a remarkable way (red, bold, ...) in many different places (while loading, while deleting, on the "waiting" screen)
b) Allowing to load the QR code multiple times, X days after the result was provided. At least on the same phone or user
c) Allowing the hotline to reset the lock after some kind of verification

## Expected Benefits
Enhancing the user experience and reducing stress on the user who potentially deleted the result

---
Internal Tracking ID: EXPOSUREAPP-2031

**Comment by GPclips** [comment]
Hello @MartinEderer,

thanks for sharing this idea with us. I personally really like it! Since you already placed it in the correct repository, I will leave it here so that it can be discussed by the community and the RKI can make its decision.

This is a good way to continuously work on new ideas like yours.

Best Regards,
LMM

Corona-Warn-App Open Source Team

**Comment by daimpi** [comment]
Related: https://github.com/corona-warn-app/cwa-app-android/issues/960

Unfortunately, allowing a QR code to be read more than once seems not possible b/c of privacy limitation as @thomasaugsten [stated](https://github.com/corona-warn-app/cwa-app-android/issues/960#issuecomment-667996582):
> Hi unfortunately this is not possible. We have to ensure only one phone can scan the qr code and submit his diagnoses keys. We are not allowed to save an ID of the phone this is the reason why the qr code is only valid for one scan.
Please wait for the normal way (a letter via post mail or Gesundheitsamt calls you) of the test lab to get your result.

What should be possible though, is to get a Tele-TAN once you get a positive result.

**Comment by MartinEderer** [comment]
Thanks for the reference which i did not find.
According to my research - Tele-Tan should be possible after the positive result.

Regarding the one-way code:
If the result is not published and the code is used - flag it as blocked
If the result is not published and the code is not used anymore - flag it as open
If the result is published and the code is used - flag it as blocked
(blocked=code is not loadable; open=code is loadable)

Maybe new idea:
You can always load the code but if it was loaded multiple times, instead of immediately allowing to share the result you have to get the Tele-Tan


Just imaging the situation:
- you are getting just a cold and it starts with similar symptoms while coming back from a "secure" country
- you do the test and delete accidental the code
- you quite freak out everyday a little more with every dry cough and have no chance to get the result earlier
- you are quite pissed and the app is getting disliked

**Comment by Ein-Tim** [comment]
In 1.2.1 there is a warning. 
See [this comment](https://github.com/corona-warn-app/cwa-wishlist/issues/173#issuecomment-683700303) from @thomasaugsten

**Comment by Ein-Tim** [comment]
@heinezen 
I think this can be closed since there is a warning in the App now

**Comment by heinezen** [comment]
@Ein-Tim Yes, I think you'e right.

Implemented in CWA version 1.2.1.

----
Corona-Warn-App Open Source Team
