### ISSUE TITLE
Make app available for users with foreign Google Play account

### ISSUE THREAD

**Issue by tblock79** [corona-warn-app/cwa-wishlist#145]
I temporarily live in Germany but cannot install the app because my Google Play Account is a foreign account. Switching the Google Play account to Germany would prevent me from switching back for a full year. Please change the app settings in Google Play to allow international users to install it as well (as it is the case for the majority of apps in Google Play). The goal should be to make the app available to everyone who is currently located in Germany, not just to users with a German Google account.

**Comment by daimpi** [comment]
See this thread: https://github.com/corona-warn-app/cwa-backlog/issues/9

You can upvote your countries wishlist entry or if it doesn't have one yet, create a new one: https://github.com/corona-warn-app/cwa-backlog/issues/9#issuecomment-648745301
