### ISSUE TITLE
Add QR code support for Centogene Tests

### ISSUE THREAD

**Issue by Lucurus** [corona-warn-app/cwa-wishlist#146]
## Current Implementation

Currently, tests that have QR codes can be scanned in the app and any results are directly displayed in the app once they are made available.

## Suggested Enhancement

The free Centogene Test offered to return travellers from high-risk countries at Frankfurt airport, does not support being added to the app. 
Please contact Centogene and request support for adding the test to the "Have you been tested" section so that results are directly shown in the app.

## Expected Benefits

Since this will be one of the most popular tests administered (Every person returning and passing through Frankfurt Airport should, in theory, get one), adding the test will cover a huge part and, combined with maybe pamphlets at the airport, should hopefully also convince more people to download the app.

---
Internal Tracking ID: EXPOSUREAPP-2030

**Comment by GPclips** [comment]
Hello @Lucurus ,

thanks for sharing your idea. I will leave it in the wishlist repo that it can be discussed by the community and the RKI can make its decision.

Thanks,

LMM

Corona-Warn-App Open Source Team

**Comment by Lucurus** [comment]
Thank you!

**Comment by Marco2907** [comment]
Hi @Lucurus, regarding on your info, the actual situation is that the Centogene Labor is connected to the Corona Warn. The final tests are currently in progress. I will come back to you as soon as possible if there are new results. 

Thank you.

Best,
MP

Corona-Warn-App Open Source Team

**Comment by Lucurus** [comment]
Awesome, thanks for the update!

**Comment by GPclips** [comment]
Hello @Lucurus,

just received an update regarding this topic.
Your Centogene Use-Case has been implemented successfully.
Congratulations and again thank you for sharing your idea!

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by Lucurus** [comment]
Awesome, thank you very much for your help!
