### ISSUE TITLE
Protocol on android devices quite unusable

### ISSUE THREAD

**Issue by sknull** [corona-warn-app/cwa-wishlist#147]
When you open the apps protocol under the device settings/google/covid 19 you see a long list of requsts.

- For each day there are multiple entries which contain data for different hashes.
- When you click on one of them to check the details, then go back the list position is reset to the top and one has to scroll down again. 
- The list seems not to be sorted by date

This approach is not helpful when you want to check when you had a critical contact. It's onky useful to technically check if the app is doing something useful - which will not be of interest for most users.

I suggest the following changes:
- either turn this into a table like view with columns date, hash, hit count - sorted by date
- or at least sort the list by date and colorize the single buttons in a suitable manner i.e. green for zero hit count, yellow up to some hit count, red above that.

Regards,
Stephan

**Comment by GPclips** [comment]
Hello @sknull,

thanks for sharing your idea. I have transferred it o the correct repository to make sure it ends up in the right hands.

Thanks you,
LMM

Corona-Warn-App Open Source Team

**Comment by sknull** [comment]
Ah okay I think what I inteded is the same as discussed in #23 so this one can safely be considered as duplicate and being closed now. I went to the log in the first place to find out more about my "1 Riskio Begegnung" message...

Kind regards,
Stephan

**Comment by SonaliDK** [comment]
Hi @sknull,

Thanks for your comment above. Since it is identified as duplicated, I will go ahead and close this issue.

Best regards,
SD

Corona-Warn-App Open Source Team
