### ISSUE TITLE
Auflistung von Regelungen für spezifische Bundesländer | Add local regulations and restrictions

### ISSUE THREAD

**Issue by KevinH90** [corona-warn-app/cwa-wishlist#151]
## Beschreibung und Motivation
Wir leben aktuell aufgrund von Covid-19 in einer Zeit der Unsicherheit. Mit wie vielen Leuten darf ich mich in der Öffentlichkeit treffen und wie sehen die Regeln im privaten Raum aus? Zu welchen Anlässen und in welchen Lokalitäten muss eine Maske getragen werden? Diese und viele weitere Fragen stellen sich viele in unserem Freundeskreis und sehr wahrscheinlich die meisten Deutschen, vor allem auch, wenn sie das Bundesland wechseln und mit unterschiedlichen Regeln konfrontiert werden.

Wir, vier Studenten der Hochschule Worms sowie der Universität Heidelberg, haben eine kleine Webapplikation für diese Herausforderung als Prototyp erstellt: Wir nennen sie „Coronaregel.de“.

Unsere Idee im Nachgang war es, dieses Feature auch in die offizielle Corona-Warn-App mit einfließen zu lassen. In erster Linie dient die App natürlich der Sicherstellung von Infektionsketten, aber sie kann auch eine Plattform für aktuelle Informationen, vorallem regional, sein.

## Prototyp
[Hier geht's zum Prototypen](http://51.38.99.144:3000/)

![Visualisierung](https://user-images.githubusercontent.com/69519591/89909735-af200780-dbef-11ea-99ff-57217a545334.png)
![Screen 2](https://user-images.githubusercontent.com/69519591/89909739-afb89e00-dbef-11ea-87a6-c3740a3b16e5.png)
![Screen 1](https://user-images.githubusercontent.com/69519591/89909759-b47d5200-dbef-11ea-81cf-afbf382e0dfa.png)

## Einbindung in die Corona-Warn-App
So könnte eine mögliche Integration aussehen, die gezeigte Standortfunktion dient nur der Visualisierung:

![Einbindung in die App](https://user-images.githubusercontent.com/69519591/89909772-b9da9c80-dbef-11ea-81e9-09eabeb6eee5.jpeg)

## Entwicklungsaufwand
Die Screens wurden bereits als eigenständige Applikation umgesetzt, lediglich der Feinschliff und die Integration sind aus unserer Sicht notwendig.

[Github-Repository](https://github.com/juliusmlr/coronaregelswift)

## Sind wir daran interessiert, weiter daran zu arbeiten?
Ja! Gerade als Studenten sind wir daran interessiert, unsere Skills zu verbessern und Erfahrungen zu sammeln.

---
Internal Tracking ID: [EXPOSUREAPP-2161](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-2161)

**Comment by GPclips** [comment]
Hello @KevinH90,

thanks for sharing your idea. I will inform the development team and transfer the issue.

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by FranzBumes** [comment]
Well - this could help to increase the popularity of the app. 
As there are a lot of different rules it would be useful to have such a feature.

Maybe even down to the counties ("Landkreisen") in special circumstances e.g. higher risk with special measures.
  - mandatory mask wearing
  - Test Stations
  - mandatory neg. Test Results for holidays,
  - ... 
GPS ist good enough for this.

**Comment by gusowski1** [comment]
As a agree with you @FranzBumes i fear many people wouldn't use the app if it needs gps
The fear to get tracked is very high in germany

But the feature would make sence without gps too

**Comment by FranzBumes** [comment]
@gusowski1  You are right. 
But if there is an option to activate/deactivate GPS (as shown in the image above) this should not be a problem.
There are lots of apps, who are using GPS. So it depends on assuring that this option is not used for contact tracing. 

an Alternative to GPS:
- Select the state (county) in settings - then there is no GPS necessary.
or
- Show last selected state/county when jumping to "Coronaregeln" view.

**Comment by MarijaJovanov** [comment]
WOW Kevin, would be soooo useful during these hard times. !!
looking forward for the Go Live :)

PS. could you create please and attach small summary in English, so i can share with my colleagues!

**Comment by KevinH90** [comment]
@FranzBumes, we thought about the same regarding rules to wear a mask in specific places or your other examples, but we wanted to put only information in our prototyp we were able to verify at this point, so we kept it simple to demonstrate our idea!

@gusowski1, while creating the mockups we thought about gps aswell and came to the same conclusion as you. The fear of getting tracked by the government is a real issue for many people in germany and we are aware of this, but we thought for a mockup it would be a nice addition to see what would be possible.

@MarijaJovanov, thanks for your feedback Marija! We would also love to see that feature become reality :) I will share an english version in the next two days!

**Comment by FranzBumes** [comment]
@KevinH90:
GPS is not necessary for the benefit of this feature. 
Content could be maintained central ( in all available languages) by one provider and downloaded if there are changes in it;

**Comment by Marco2907** [comment]
Additional information can be found here: https://github.com/corona-warn-app/cwa-wishlist/issues/168

**Comment by daimpi** [comment]
Any news on this project? 🙂

**Comment by Sammeeey** [comment]
Gibt's Neuigkeiten?
Arbeitet Ihr noch an dem Projekt?
Wie läufts?
Habt Ihr schon einen Webauftritt oder Ähnliches?

**Comment by chris-redbeed** [comment]
As I mention in #210 it could be good to add the current incident to the app. 
The RKI has a simple api to get the incident of your current or selected district in germany.

Everyone in germany is currently watching the incident so it would be helpful to have the current number right on your phone.

**Comment by scrobbleme** [comment]
Currently, it is quite hard to find out, where corona risk areas are, what measures are taken, where I can travel ...

As the official app, there also should be information about corona risk areas integrated:

- Overview of current/potential corona risk areas
- Information about personal exposure (is my area a corona risk area? Can I travel to XY?)
- Helpful links to official measures in the corona risk area I'm in

#220

**Comment by heinezen** [comment]
I've added an additional english title description to avoid further duplicates.

----
Corona-Warn-App Open Source Team

**Comment by michaelkrause-SAP** [comment]
Ich finde es extrem wichtig, dass diese Funktionalität IN DIE APP einfließt. Das hilft vor allem dabei, einen noch größeren Mehrwert für diese App zu erzeugen. Aus meiner Sicht müssten die Regeln dann von Behörden gepflegt werden. Sozusagen als offizielle Quelle.

**Comment by MikeMcC399** [comment]
@michaelkrause-SAP 
>Ich finde es extrem wichtig, dass diese Funktionalität IN DIE APP einfließt. Das hilft vor allem dabei, einen noch größeren Mehrwert für diese App zu erzeugen. Aus meiner Sicht müssten die Regeln dann von Behörden gepflegt werden. Sozusagen als offizielle Quelle. Auch die Information z.B. per Push-Message bei Veränderung von Regeln in ausgewählten Orten wäre super.

Bevor man das doppelt macht, warum nicht CWA zu [NINA](https://www.bbk.bund.de/DE/NINA/Warn-App_NINA_node.html) verlinken?
NINA ist die offizielle Notfall-Informations- und Nachrichten-App des Bundes. Falls NINA nicht installiert ist, könnte CWA auch einen Hinweis auf die Links zum Herunterladen der NINA-App für iOS und Android geben (see auch https://github.com/corona-warn-app/cwa-wishlist/issues/151#issuecomment-678622661). NINA besitzt auch Push-Fähigkeiten.

![NINA](https://user-images.githubusercontent.com/66998419/97317863-8fea5b00-186b-11eb-9947-aab3efb81da3.jpg)

Bei NINA unter 
Corona > Corona-Grundwissen > Corona-Warn-App wird auf die Corona-Warn-App hingewiesen. 

Es wäre wohl logisch, wenn auch ein Hinweis in die umgekehrte Richtung erfolgen würde:
CWA => NINA

**Comment by FranzBumes** [comment]
@ MikeMcC399 
Ich bin mir da nicht so sicher. Ich hab NINA installiert.
1. NINA warnt auch vor anderen Dingen ( z.Bsp. Unwetter) Was ja ganz gut ist, aber über den Zweck hinausgeht.
2. NINA muss extra installiert werden.
3. NINA ist (zumindest auf Landes/Landkreisebene) nicht aktuell. 
    In meinem Landkreis ist aktuell die Warnstufe rot ( 50 -100 Falle/100000)
    Ich finde aber weder zu meinem Landkreis noch zum Bundesland Warnungen. Das einzige was angezeigt wird, ist die Warnung  des BMI vom 14.10.2020 ( auch schon wieder fast 2 Wochen alt.)
Um nützlich zu sein müssen die Daten auch aktuell sein. Wenn man hier einen Zugang ( Für jedes Land/ jeden Landkreis)  schafft, der Aktualisierung zulässt, ist das sicher ein Fortschritt.  Alternativ können Landesregierungen /Landkreise dies einer zentralisierten Stelle auch zukommen lassen.

Allerdings sollte es nicht so schwer sein, die eingepflegten Daten, auch aus CWA abzurufen und anzuzeigen., NINA ist ja auch eine deutsche Entwicklung. Dessen Server dahin zu erweitern, Daten abzufragen, sollte deshalb machbar sein. Es muss ja nich gleich ein Push Service sein. Einmal täglich würde auch schon reichen, da wir bei der Corona Lage im allgemeinen nicht von einer stündliche Lageänderung ausgehen sollten.  Um Hackerangriffe zu minimieren könnte das ja von CWA server zwischengelagert werden, die Verbindung von CWA zu NINA gesichert sein . Die Apps könnten die neuen Warnungen parallel zum Abruf der Risikoschlüssel erhalten.

**Comment by FranzBumes** [comment]
@ MikeMcC399 Nachtrag.
Ich hab bei meine Landratsamt nachgefragt. Sie sind noch nicht an NINA angeschlossen. Das stellt die Frage wieviele Landkreise in Deutschland wirklich angeschlossen sind? Ich hab auf der WEB-Seit von NINA dazu nichts gefunden.

Die Anfrage an das Bayrische Ministerium für Gesundheit läuft noch.

**Comment by michaelkrause-SAP** [comment]
> @michaelkrause-SAP
> 
> > Ich finde es extrem wichtig, dass diese Funktionalität IN DIE APP einfließt. Das hilft vor allem dabei, einen noch größeren Mehrwert für diese App zu erzeugen. Aus meiner Sicht müssten die Regeln dann von Behörden gepflegt werden. Sozusagen als offizielle Quelle. Auch die Information z.B. per Push-Message bei Veränderung von Regeln in ausgewählten Orten wäre super.
> 
> Bevor man das doppelt macht, warum nicht CWA zu [NINA](https://www.bbk.bund.de/DE/NINA/Warn-App_NINA_node.html) verlinken?
> NINA ist die offizielle Notfall-Informations- und Nachrichten-App des Bundes. Falls NINA nicht installiert ist, könnte CWA auch einen Hinweis auf die Links zum Herunterladen der NINA-App für iOS und Android geben (see auch [#151 (comment)](https://github.com/corona-warn-app/cwa-wishlist/issues/151#issuecomment-678622661)). NINA besitzt auch Push-Fähigkeiten.
> 
> ![NINA](https://user-images.githubusercontent.com/66998419/97317863-8fea5b00-186b-11eb-9947-aab3efb81da3.jpg)
> 
> Bei NINA unter
> Corona > Corona-Grundwissen > Corona-Warn-App wird auf die Corona-Warn-App hingewiesen.
> 
> Es wäre wohl logisch, wenn auch ein Hinweis in die umgekehrte Richtung erfolgen würde:
> CWA => NINA

Hallo @MikeMcC399 , generell finde ich es immer gut, Dinge nicht doppelt zu machen, an dieser Stelle ging es mir mehr darum, die Bevölkerung zur Corona-App zu bringen und auf noch mehr Endgeräten zu installieren. Meiner Meinung nach, erreicht man das nur über Mehrwerte. Die Frage "What's in for me" stellen sich in meinem Bekanntenkreis leider Mehrere. Wenn wir es erreichen können, dass die App Informationen bereit stelle, warnt, und "nebenbei" auch noch bei der Nachverfolgung hilft, wäre das für mich eine perfekte Kombination. VG Michael

**Comment by achisto** [comment]
> Bevor man das doppelt macht, warum nicht CWA zu [NINA](https://www.bbk.bund.de/DE/NINA/Warn-App_NINA_node.html) verlinken?
> NINA ist die offizielle Notfall-Informations- und Nachrichten-App des Bundes. Falls NINA nicht installiert ist, könnte CWA auch einen Hinweis auf die Links zum Herunterladen der NINA-App für iOS und Android geben (see auch [#151 (comment)](https://github.com/corona-warn-app/cwa-wishlist/issues/151#issuecomment-678622661)). NINA besitzt auch Push-Fähigkeiten.
> 
> Bei NINA unter
> Corona > Corona-Grundwissen > Corona-Warn-App wird auf die Corona-Warn-App hingewiesen.
> 
> Es wäre wohl logisch, wenn auch ein Hinweis in die umgekehrte Richtung erfolgen würde:
> CWA => NINA

(english below)

Ich möchte zum Thema NINA auch noch etwas ergänzen: wenn ich mich in meinem Bekanntenkreis umschaue, nutze ich dort als einziger NINA, KATWARN oder ähnliches. Auch die CWA nutzt nicht jede:r, eben weil - genau wie bei NINA & Co. - kein Nutzen gesehen wird. Was aber wohl jede:r früher oder später nachschauen muss, sind aktuelle lokale Bestimmungen und Handlungsanweisungen. Das wäre ein deutlicher Mehrwert, gäbe es diese Informationen in der CWA.

Zudem finde ich persönlich NINA für den Zweck nicht optimal - die Informationen zu lokalen Bestimmungen gibt es nicht überall, maximal auf Landesebene und sehr unübersichtlich aufbereitet. Das ist in meinen Augen kein Mehrwert und obwohl ich NINA auf dem Smartphone habe, nutze ich bislang immer die Webseiten von Land und Stadt. 

**english**:
I would also like to add something on the subject of NINA: when I look around in my circle of friends and acquaintances, I am the only one there who uses NINA, KATWARN or similar apps. Not everyone uses the CWA either, precisely because - just as with NINA & Co. - no benefit is seen. But sooner or later, everyone has to look up current local regulations so if this information were available in the CWA this would be a huge added value.

In addition, I personally don't think NINA is ideal for the purpose - the information on local regulations is not available on every region, at most on a national level and very confusingly presented. Although I have NINA on my smartphone, I always use the websites of the federal state and city.

**Comment by coronaregel** [comment]
Wie wäre es mit einem Feature, das es ermöglicht zu sehen was ich beachten muss, wenn ich aus Region A nach Region B reise?

english:
What about a feature, which makes it possible to find the regulations specifically for a journey from region A to region B?

**Comment by michaelkrause-SAP** [comment]
> Wie wäre es mit einem Feature, das es ermöglicht zu sehen was ich beachten muss, wenn ich aus Region A nach Region B reise?
> 
> english:
> What about a feature, which makes it possible to find the regulations specifically for a journey from region A to region B?

Ich denke jedes Feature, das dem User ein zusätzlichen Nutzen gibt, ist wertvoll. Ziel soll es ja sein, die Corona app möglichst auf 100% der Mobiltelefone zu installieren. Je mehr Telefone, desto größer der Nutzen.

**Comment by 42ideasnow** [comment]
> > Wie wäre es mit einem Feature, das es ermöglicht zu sehen was ich beachten muss, wenn ich aus Region A nach Region B reise?
> > english:
> > What about a feature, which makes it possible to find the regulations specifically for a journey from region A to region B?
> 
> Ich denke jedes Feature, das dem User ein zusätzlichen Nutzen gibt, ist wertvoll. Ziel soll es ja sein, die Corona app möglichst auf 100% der Mobiltelefone zu installieren. Je mehr Telefone, desto größer der Nutzen.
> 
> English:
> I think every feature that gives the user an additional benefit is valuable. The goal should be to install the Corona app on 100% of cell phones. The more phones, the greater the benefit

Da muss ich vollkommen zustimmen. Vielleicht ist das nochmal ein Thema für ein anderes issue, aber wenn es um features geht, von denen der Endnutzer einen Mehrwert hat, fällt mir noch was ein:
Eine Anzeige der Corona Testzentren und Arztpraxen, die Tests anbieten in der Umgebung. Inklusive Adresse und Telefonnummer.
Das würde die armen Arzthelferinnen der Hausärzte entlasten, die am Telefon Anfragen vom Typ "Wo kann ich mich denn testen lassen" immer wieder bearbeiten müssen.
Wenn man für seine Region nämlich versucht, über eine google Suche Testzentren in der Umgebung zu finden, wird man nicht so wirklich intuitiv fündig.
Die Corona-Warn-App würde immer mehr zu einem Infoportal und Koordinationshilfe zum Thema Corona werden, was auch jeder immer zur Hand hat.

Eine Idee , wie man das Datenschutz Thema bei Ortsauswahl ohne GPS angehen könnt:
Postleitzahl
Für den Heimatort kennt man sie sowieso, ansonsten kann man sie in wenigen Sekunden in einer beliebigen anderen Karten App nachschauen.
Lässt sich auch gut von einer Offline Suchfunktion innerhalb des potenziell täglich erneuerten Datensatz-downloads gut abgleichen.

**Comment by michaelkrause-SAP** [comment]
> > > Wie wäre es mit einem Feature, das es ermöglicht zu sehen was ich beachten muss, wenn ich aus Region A nach Region B reise?
> > > english:
> > > What about a feature, which makes it possible to find the regulations specifically for a journey from region A to region B?
> > 
> > 
> > Ich denke jedes Feature, das dem User ein zusätzlichen Nutzen gibt, ist wertvoll. Ziel soll es ja sein, die Corona app möglichst auf 100% der Mobiltelefone zu installieren. Je mehr Telefone, desto größer der Nutzen.
> > English:
> > I think every feature that gives the user an additional benefit is valuable. The goal should be to install the Corona app on 100% of cell phones. The more phones, the greater the benefit
> 
> Da muss ich vollkommen zustimmen. Vielleicht ist das nochmal ein Thema für ein anderes issue, aber wenn es um features geht, von denen der Endnutzer einen Mehrwert hat, fällt mir noch was ein:
> Eine Anzeige der Corona Testzentren und Arztpraxen, die Tests anbieten in der Umgebung. Inklusive Adresse und Telefonnummer.
> Das würde die armen Arzthelferinnen der Hausärzte entlasten, die am Telefon Anfragen vom Typ "Wo kann ich mich denn testen lassen" immer wieder bearbeiten müssen.
> Wenn man für seine Region nämlich versucht, über eine google Suche Testzentren in der Umgebung zu finden, wird man nicht so wirklich intuitiv fündig.
> Die Corona-Warn-App würde immer mehr zu einem Infoportal und Koordinationshilfe zum Thema Corona werden, was auch jeder immer zur Hand hat.
> 
> Eine weitere Idee, wie man das Datenschutz Thema bei Ortsauswahl ohne GPS angehen könnte:
> Postleitzahl
> Für den Heimatort kennt man sie sowieso, ansonsten kann man sie in wenigen Sekunden in einer beliebigen anderen Karten App nachschauen.
> Lässt sich auch gut von einer Offline Suchfunktion gut abgleichen. (Wenig Potenzial für Tippfehler im Gegensatz zu manueller Eingabe von Städtenamen)

Das genau sehe ich auch als den Richtigen Weg an. Das Zentrale Ziel muss es sein, über Mehrwerte auf alle Telefone zu kommen. Whatsapp und Facebook sind auch auf nahezu jedem Mobiltelefon und es werden Daten an dritte verkauft, eigentlich ein no-go aber die User akzeptieren es ... warum ??? weil die Tools einen Mehrwert bringen.

**Comment by MikeMcC399** [comment]
[Die offizielle Seite des Robert Koch Instituts](https://www.rki.de/DE/Home/homepage_node.html) verweist auf
[Zusammen gegen Corona - vom Bundesministerium der Gesundheit](https://www.zusammengegencorona.de/) das wiederum auf die

**[„Darf ich das?“-App](https://www.darfichdas.info/)** zeigt.

"Was darf man eigentlich, und welche Regeln und Gesetze sind in in deiner Region gerade gültig?"

So wie es aussieht, ich das alles schon realisiert! Ich habe es installiert und überflogen. Es scheint sehr umfangreiche Informationen zu enthalten. Leider bei den sehr dynamischen Veränderungen sind die Infos allerdings etwas widersprüchlich, aber die Daten sind zu den offiziellen Quellen zum Nachlesen verlinkt.
(Ich will hier für die App keine Werbung machen, sondern lediglich die Info hier weitergeben!)

**Comment by AndreasOesterhelt** [comment]
>Leider bei den sehr dynamischen Veränderungen sind die Infos allerdings etwas widersprüchlich, aber die Daten sind zu den offiziellen Quellen zum Nachlesen verlinkt.

Das hat 2 Gründe:

- Wir haben derzeit eine extrem dynamische Situation. Ich hab z.B. heute Regeln aus einer Allgemeinverfügung für Köln eingepflegt, [die auf einer Pressekonferenz](https://www.stadt-koeln.de/politik-und-verwaltung/presse/mitteilungen/22592/index.html) am späten Nachmittag verkündet wurden, die schon ab 0:00h heute Nacht aber nur über das Wochenende 31.10/1.11. gelten werden und am 2.11. von der [neuen Coronaschutz-Verordnung des Landes NRW](https://www.mags.nrw/sites/default/files/asset/document/201030_coronaschutzverordnung_vom_30._oktober_2020.pdf) abgelöst werden werden. Dann aber vermutlich wieder mit lokalen Kölner Ergänzungen. Will nicht jammern, aber gerade ist nicht ganz einfach, das für 400+ Landkreise und kreisfreie Städte immer tagesaktuell korrekt zu halten. 
- Die Regeln auf Landesebene, die im unteren Bereich des Detail View thematisch gegliedert dargestellt werden, sind subsidiär zu den oft schärferen Regeln der Kommunen. In einer perfekten Welt gäbe es eine Legebatterie mit 100 hungrigen Studenten und ein passendes Budget, um das kommunale Delta für jede Kommune in einen integrierten, widerspruchsfreien Gesamttext einfließen zu lassen. So wie die Dinge liegen, sagt die App stattdessen zweierlei: In einem deutlich hervorgehobenen Kasten oben "Das gilt bei Dir vor Ort im besonderen" und weiter unten "Und soweit oben nichts anderes steht, gilt das hier im allgemeinen für Dein ganzes Bundesland". Die Beziehung zwischen den lokalen und den Landesregeln sollte und wird die App noch klarer kommunizieren (Präsentation und Wording). Das war lange recht unproblematisch, als lokale Ausnahmen nur für Orte galten, in denen irgendeine Superspreader-Party stattgefunden hatte oder ein Schlachthof steht und jeder Nutzer aus solchen Gemeinden wusste, dass bei ihm vor Ort gerade die Hütte brennt. Heute haben im Westen nur wenige Gemeinden eine 7-Tage-Inzidenz von <35 und daher fast jeder Ort eigene Regeln, so dass das wichtiger wird. Wir arbeiten daran.

Und wie Du schon sagst, verweisen wir immer auf die jeweils relevanten offiziellen lokalen Informationen.

> (Ich will hier für die App keine Werbung machen, sondern lediglich die Info hier weitergeben!)

Ich schon, und das nicht nur weil sie von uns ist. Ich finde sie ziemlich nützlich und die Datenqualität ziemlich hoch. Auch am Preis (null), der Menge an Werbung (null) und den erhobenen Daten (null) gemessen. Sorry for the plug, musste raus.

**Comment by FranzBumes** [comment]
Ich muss schon sagen ich bin enttäuscht, wie das Corona Warn App Tem diesen Inzident behandelt hat. Wir bemühen uns seit August, warum kann dann es keine Info vom CWA Team geben, da wohl das RKI / BZGA davon wusste?

**Comment by AndreasOesterhelt** [comment]
@FranzBumes Vielen Dank! 

Glaube da hat niemand was verschlafen -- wir sind erst sehr sehr kürzlich auf dem Radar des BMG aufgetaucht. Und weil wir in den Stores von Apple und Google keine Covid-Keywords benutzen dürfen, war die App vorher auch nur sehr schwer zu finden.

**Comment by FranzBumes** [comment]
@AndreasOesterhelt  Danke für die Info.
Mein Frust in der letzten mail war wohl nicht gerechtfertigt - ich seh halt wie die Diskussion bzgl. der Regeln in letzter Zeit gelaufen ist. Es wäre sehr hilfreich gewesen, auf diese App verweisen zu können. 
BTW: Ihr habt ja doch viel Auswand mit der Pflege der Daten. Könnt ihr das lange finanzieren?

**Comment by AndreasOesterhelt** [comment]
@FranzBumes Ja, viel Aufwand. Und ja, ewig können wir diesen Kinderkreuzzug mit Leuten aus allen Ebenen und Funktionen im Laden nicht betreiben, besonders nicht für lau.

Es zeichnen sich am Horizont aber Lösungen ab. Für zusätzliche Datenquellen, sprich weniger Handarbeit, und auch für ein Budget. Bis dahin halten wir erst mal durch. 

Ist aber arg offtopic hier. Wenn Du weiter reden oder vielleicht sogar mithelfen magst, schick mir gern eine mail.

**Comment by Xyz00777** [comment]
Ich fände es auch noch awesome wenn es noch zusätzlich die Möglichkeit gäbe je nach Region hinzuzufügen, wo man sich hin melden muss (eventuell mit direkten Kontakt Daten (auf die Telefon Nummer klicken und man ruft dort direkt an)). Meine mum war vor einem Monat in Österreich und als sie wieder hier war, hätte sie sich testen lassen müsse. Sie hat 2 tage und ca 15 Telefonate gebraucht um herauszufinden an wen sie sich wenden muss um den Test machen zu können. Dies wäre auch noch ein sehr nützlichen Feature welches man hier noch dazu einbauen könnte finde ich. Hierzu müsste man dann vermutlich kontakt mit den Gesundheitsämter aufnehmen schätze ich, um die liste zu bekommen, wo man sich testen lassen kann, dies wird aber in der aktuellen Pandemie vermute ich kein Problem sein, wenn diese anfrage von der richtigen Stelle kommt (CWA Team? bzw regierungs kontakt des Teams?). So könnte man die leute auch noch mehr dazu bewegen die app zu benutzen da man so alles an einer stelle hat.

**Comment by alexanderkeller** [comment]
Kann mich jemand hier vielleicht aufklären? Gibt es hier irgendwie einen Repo Manager oder ein Core Team? Wer genau kümmert sich denn um die issues hier? Bzw. wie ist der aktuelle Stand hier, außer dass es einen recht langen Discussion Thread gibt. Arbeitet schon jemand in einem Feature Branch an dem Feature hier? Wo wäre der Branch zu finden? 

Das enhancement war ja extrem gut und weit schon durch @KevinH90 im August initial erstellt worden. Mehrere Dubletten (auch meine) wurden erstellt. Anscheinend ist der Bedarf nach so einem Feature ja groß. Auch auf die Notwendigkeit, neue Features mal zu implementieren wurde hingewiesen, damit die Akzeptanz der App bzw. des Projektes nicht noch mehr abnimmt. Der Thread lebt ja immer noch durch die immer noch aktuelle Diskussion hier. Seit knapp 3 Monaten in einem Repo was vor 5 Monaten initial erstellt wurde 😉

**Comment by KevinH90** [comment]
Hallo zusammen,

wir freuen uns sehr, dass auch nach so einer langen Zeit, das Interesse an einer Umsetzung unserer Idee innerhalb der Corona-App scheinbar nicht nachgelassen hat! 

Ursprünglich war „CoronaRegel.de“ tatsächlich als Webseite geplant, welche,  durch die Unterstützung der Gesundheitsministerien, verständliche Informationen in einem einheitlichen Format präsentieren sollte. Nachdem diese Ministerien sich jedoch bei uns nicht zurückgemeldet haben, sind wir auf die Idee mit der Implementierung in die Corona-Warn-App gekommen. 

Wir haben die letzten Wochen und Monate die Kommentare aufmerksam verfolgt und finden es selbst schade, dass wir nicht von höherer Stellen erfahren, ob eine Umsetzung geplant ist oder was diese verhindert. Mein Studienkollegen und ebenfalls Werkstudent bei SAP hat bereits intern angeboten, die notwendige Funktionalität vorzuprogrammieren und den Implementierungsprozess zu unterstützen. 

Gibt es in diesem Thread einen Zuständigen der uns über die aktuelle Lage aufklären kann? Über eine Rückmeldung würden wir uns sehr freuen!

**Comment by AndreasOesterhelt** [comment]
> Ich fände es auch noch awesome wenn es noch zusätzlich die Möglichkeit gäbe je nach Region hinzuzufügen, wo man sich hin melden muss (eventuell mit direkten Kontakt Daten (auf die Telefon Nummer klicken und man ruft dort direkt an)). 

116117 ?

**Comment by MikeMcC399** [comment]
@AndreasOesterhelt / @Xyz00777 
>>Ich fände es auch noch awesome wenn es noch zusätzlich die Möglichkeit gäbe je nach Region hinzuzufügen, wo man sich hin melden muss (eventuell mit direkten Kontakt Daten (auf die Telefon Nummer klicken und man ruft dort direkt an)).
>
>116117 ?

Es ist tatsächlich in der App etwas versteckt, aber die App verweist auf die Hausarztpraxis bzw. die Hotline des ärztlichen Bereitschaftsdienstes 116 117.

INFORMIEREN & HELFEN > WEITER > TAN anfragen
runter scrollen
![TAN eingeben](https://user-images.githubusercontent.com/66998419/99565425-e6127000-29cb-11eb-9135-5b5bb64f4333.jpg)

**Comment by DanielHabenicht** [comment]
Seid ihr noch aktiv an der CoronaRegel app dran? Wir könnten euer KnowHow evtl gebrauche. Schreibt mir doch einfach mal ;)
Geht um eine Karte mit Inzidenzvoraussage die an der Charite angesiedelt ist.

**Comment by AndreasOesterhelt** [comment]
Hallo zusammen,

ich will hier nicht rumspammen oder -nerven, nur noch mal kurz daran erinnern, dass es genau diese Funktionalität schon gibt, jedenfalls die Anzeige lokaler 7-Tage-Inzidenz und der lokalen Regeln vor Ort, bundesweit:

[https://www.darfichdas.info/](https://www.darfichdas.info/)

Wir sind grundsätzlich bereit, das in die CWA einfließen zu lassen. Es ist auch ein bisschen schräg, dass von diesem Thread über [populäre Komiker](https://twitter.com/janboehm/status/1319565816157929472?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1319565816157929472%7Ctwgr%5E%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fwww.express.de%2Fkoeln%2F-darf-ich-das---koelner-entwickeln-app-fuer-corona-regelchaos---promi-ist-begeistert-37552216) und [den WDR](https://www1.wdr.de/mediathek/video/sendungen/lokalzeit-koeln/video-koelner-app-erklaert-corona-regeln-100.html) bis zu [Minsterpräsidenten](https://www.sueddeutsche.de/gesundheit/gesundheit-duesseldorf-vorschlaege-fuer-warn-app-lokalinfos-freiwillige-zusatzdaten-dpa.urn-newsml-dpa-com-20090101-201124-99-447793) alle darüber reden, dass so was passieren sollte, aber niemand mit uns.

Als kurzes Update haben wir jetzt 70k+ User, die das gut finden(~5/5* bei Apple und Google) und seit Wochen aktuelle Daten. 

@CWA-Community: Meldet Euch gern!

**Comment by DanielHabenicht** [comment]
@AndreasOesterhelt dann genau die gleich Frage an euch. (ich glaube ich hatte euch auch schon auf Twitter angeschriegen - aber erst heut). 
Kann man eure Datengrundlage auch in andere (Web)Apps integrieren? 
(Wir zeigen momentan Landkreis genau Daten an und verlinken jeweils auf die Seite des zuständigen Landkreises)

**Comment by Ein-Tim** [comment]
@AndreasOesterhelt 
I don't like such OFF Topic Chats normally but one thing I want to add:
I miss from the "Darfichdas"-App that the source code is not public. This is also a bit contradictory to the whole CWA Open Source thing. Is there any reason the Source Code is not public?

**Comment by dsarkar** [comment]
Dear community,

Thank you for your input here. We will approach the developer team with this issue, and hopefully, we can report back here soon.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@AndreasOesterhelt 
https://www.n-tv.de/mediathek/videos/panorama/Diese-Apps-helfen-im-Corona-Regel-Wirrwarr-article22207217.html erwähnt Eure App https://www.darfichdas.info/ 😄

**Comment by jucktnich** [comment]
Maybe we can use the same database like Nina from the bbk (authority) wich can be displayed since 3.3.0. This data is persize to your location.

**Comment by DGrothe-PhD** [comment]
> 
> 
> Hallo zusammen,
> 
> ich will hier nicht rumspammen oder -nerven, nur noch mal kurz daran erinnern, dass es genau diese Funktionalität schon gibt (als iOS/Android-App), jedenfalls die Anzeige lokaler 7-Tage-Inzidenz und der lokalen Regeln vor Ort, bundesweit:
> 
> https://www.darfichdas.info/
> 
> Wir sind grundsätzlich bereit, das in die CWA einfließen zu lassen. Es ist auch ein bisschen schräg, dass von diesem Thread über [populäre Komiker](https://twitter.com/janboehm/status/1319565816157929472?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1319565816157929472%7Ctwgr%5E%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fwww.express.de%2Fkoeln%2F-darf-ich-das---koelner-entwickeln-app-fuer-corona-regelchaos---promi-ist-begeistert-37552216) und [den WDR](https://www1.wdr.de/mediathek/video/sendungen/lokalzeit-koeln/video-koelner-app-erklaert-corona-regeln-100.html) bis zu [Minsterpräsidenten](https://www.sueddeutsche.de/gesundheit/gesundheit-duesseldorf-vorschlaege-fuer-warn-app-lokalinfos-freiwillige-zusatzdaten-dpa.urn-newsml-dpa-com-20090101-201124-99-447793) alle darüber reden, dass so was passieren sollte, aber niemand mit uns.
> 
> Als kurzes Update haben wir jetzt 70k+ User, die das gut finden(~5/5* bei Apple und Google) und seit Wochen aktuelle Daten.
> 
> @CWA-Community: Meldet Euch gern!

Ein solches Feature täte der Corona-Warn-App gut, es gibt ihr einen deutlich wahrnehmbaren Nutzen.

**Comment by jucktnich** [comment]
1. Are there any updates on this topic?
2. What's the reasons for not implementing it?
3. Do you rethink you're opinion, since the local statistics where implemented?

**Comment by larswmh** [comment]
Closing this issue as its related internal ticket was set to obsolete.

> Rejected by stakeholder team with remark about NINA-App.
