### ISSUE TITLE
Prevent app being automatically uninstalled by iOS

### ISSUE THREAD

**Issue by MajorGrooves** [corona-warn-app/cwa-wishlist#155]
iOS has a feature whereby if your phone is running out of storage space, the phone will delete/uninstall apps that are infrequently used. This would likely apply to the Warn App since one does not open it frequently.

It might be worth speaking to Apple to get the app put on a "do not delete" list, so that the app is not deleted without users realising (there is no notification given when an individual app is uninstalled).

**Comment by thomasaugsten** [comment]
Hi MajorGrooves 
the CWA is already excluded from the offloading feature

**Comment by MajorGrooves** [comment]
My gf's app got offloaded yesterday from her iPhone.

**Comment by thomasaugsten** [comment]
Does she use an current iOS 13.6 or better 13.6.1?

**Comment by MajorGrooves** [comment]
13.6

(not 13.6.1 - I suspect her phone is too full to do the update!).

**Comment by thomasaugsten** [comment]
on iOS 13.6 this should not happen. I will check this again. Maybe you can double check she has really installed iOS13.6 while the app was offloaded

**Comment by MajorGrooves** [comment]
Actually it's possible. She probably has not looked at the app since she installed it, which she did on the day it was released. iOS 13.6 was released on 15th July so she must have updated it since then (maybe automatically, since she does not remember doing it). So if this was only an issue with the previous OS and not the current one, then I would guess the app got off-boarded weeks ago, then she updated the OS. So maybe this is a non-issue afterall?

**Comment by MajorGrooves** [comment]
Shall I close the issue?

**Comment by thomasaugsten** [comment]
You can close it at the moment, but have an eye on this with iOS 13.6 installed.
