### ISSUE TITLE
Error message risk evaluation i-phone

### ISSUE THREAD

**Issue by makr3** [corona-warn-app/cwa-wishlist#159]
I had an error message for several days that risk evaluation is not possible (CWA not used for a while). It took very long to find the reason: Obviously a combination of energy saving mode and automatic background updates (in general and for the app) switched off. I think that many users won‘t search for the reason and simply deactivate the app thinking it does not work.
The app should inform the user about the reasons and guide the user exactly what to do.

**Comment by daimpi** [comment]
Are you maybe talking about this issue? https://github.com/corona-warn-app/cwa-app-ios/issues/741

**Comment by makr3** [comment]
yes, this was the error message and issue (obviously known already). Thank you for the fast reaction!

Von meinem Mobiltelefon gesendet

Am 19.08.2020 um 14:55 schrieb Daniel Frey <notifications@github.com>:

﻿
This message is from an EXTERNAL SENDER - be CAUTIOUS, particularly with links and attachments


Are you maybe talking about this issue? corona-warn-app/cwa-app-ios#741<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcorona-warn-app%2Fcwa-app-ios%2Fissues%2F741&data=02%7C01%7Cmarkus.kraus%40eon.com%7C8b75f80c24794dd2430208d8443f1a97%7Cb914a242e718443ba47c6b4c649d8c0a%7C0%7C0%7C637334385108806538&sdata=1L1ETqtrVa0MgC1cSqNTW0KMDoAFcbpmsDPCWA7kmk8%3D&reserved=0>

**Comment by thomasaugsten** [comment]
In the next version we also improved the help text for this issue
