### ISSUE TITLE
Personalized corona check-time

### ISSUE THREAD

**Issue by alanrick** [corona-warn-app/cwa-wishlist#163]
## Current Implementation
Currently, the CWA updates the random IDs and performs a risk assessment at a random time of the day, which does not take the user’s lifestyle into account. This could be improved.

## Suggested Enhancement

It makes sense for those who go to presence-work, such as teachers, for the CWA to have their risk checked _before they go to work_ (e.g. 6:00-8:00am) instead of _at_ work or _after_ work. This would often reduce Covid transmission in practice by one whole day for positives. 
Similarly those regularly working from home might want to be checked at the end of the working day _before they go out to the Kneipe_ in the evening (e.g. 6:00-8:00pm). 

The current algorithm waits at least 24 hours, which according to my observations yields risk calculations every 25-35 hours at a completely random time of the day 

**Suggestion**: Random IDs are updated and evaluated according to a personalised schedule-window, which nevertheless ensures a minimum interval of at least 20 hours between updates. 

**Downside**: A minimum of 24 hour updates is often cited as being necessary for privacy concerns.  This new algorithm would however mean an update will often be performed less than 24 hours after the previous update (e.g. 23 hours when updated at 7am one day and 6am the next). But I fail to understand what is so magic about the number of 24 when it comes to privacy concerns compared with a minimum interval of, say 20 hours between updates.

## Expected Benefits
Updating the data and performing the risk-evaluation at a time of day personalized to match the user's lifestyle and typical interaction with others would in practice often reduce the window of transmission by one working day. This results in a  20% effectivity improvement, assuming the most infectious phase lasts for 5 days.

**Comment by daimpi** [comment]
The issue for "more frequent updates" can be found here btw: https://github.com/corona-warn-app/cwa-backlog/issues/2 🙂.

**Comment by alanrick** [comment]
The refresh time has been reduced to a fraction of a working day ([iOS 1.7.1](https://github.com/corona-warn-app/cwa-app-ios/issues/916) and equivalent android) so this idea is now obsolete and can be closed. 
Many thanks to the developers for making this change.

**Comment by daimpi** [comment]
@alanrick as the author of this issue you can also close it yourself 🙂.
