### ISSUE TITLE
Add an intro at the first start of the app

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#167]
## Feature description

When you first start the App, you see the normal risk card.
I think it would be nice to have like an intro, how other Apps also do it, with an explanation from the different areas of the App:

* Risk Card (how it looks when you had contact to somebody COVID-19 positive)
* Submit Test Result
* Contact Journal
* Event Registration
* etc.

The user should be guided through the App. 

## Problem and motivation
It would be better and easier for the user to understand the App and which possibilities the user have. 
The user must not read all the information text and is prepared f.e. if there is a low risk exposure he/she nows what to do because it was explained in the Intro. 

---

## Related Issue

- https://github.com/corona-warn-app/cwa-documentation/issues/471 (an Intro would make the end of the onboarding clearer)

---
Internal Tracking ID: EXPOSUREAPP-2342

**Comment by svengabr** [comment]
Hello @Ein-Tim 

Thank you very much for your idea! I think this would be a good enhancement to the app.
I will transfer this issue to JIRA so that it gets in the hands of the right people.

Best regards,
SG

Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Version 2.0 will come with an event-registration feature. This feature could also be explained in the intro, as well as the already implemented contact journal.

**Comment by heinezen** [comment]
@Ein-Tim I have updated the list of features that could be explained in your initial post and the Jira ticket.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
I updated the OP of this issue to reflect that you now see the normal risk card when starting the app and not the "Unknown Risk" card.

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
