### ISSUE TITLE
Nützliche Informationen in der App

### ISSUE THREAD

**Issue by gempa-dirk** [corona-warn-app/cwa-wishlist#168]
## Feature description

- Es sollen die vom RKI veröffentlichten Fallzahlen für Bundesländer, Regionen, andere Länder aktuell angezeigt werden.
- Es sollen von der Bundesregierung veröffentlichte Corona-relevante Reisewarnungen und Risikowarnungen aktuell angezeigt werden.
- Es sollen bundesweit und landesweit geltende Corona-bedingte Vorsorgeregelungen angezeigt werden.

## Problem and motivation

- Bislang hat man von der App nur dann einen Nutzen, wenn man tatsächlich eine gemeldete Begegnung mit einer infizierten Person hat, während zum Zeitpunkt der Begebnung die App beiderseitig aktiv veingesetzt wird. Dies ist für die allermeisten Nutzer und Zufälle sicher nicht der Fall. Dadurch verlieren die Nutzer das Interesse an der App und werden diese deinstallieren oder nicht beachten. Funktionen hinzuzufügen, die für den täglichen Bedarf relevant sind, würde den Nutzen und die Anwendbarkeit der App steigern und damit dazu beitragen, dass mehr Menschen die App aktiv verwenden und damit sich selbst und andere schützen.
- Mach die App nützlich und informativ im täglichen Gebrauch
- Zeige an, wo besondere Vorsicht geboten ist.
- Steigere die Akzeptanz der App bei den Anwendern, die Nutzerbewertungen der App sind sehr schlecht. Mehr Funktionalität der App könnte diese und damit den Ruf und die Akzeptanz der App verbessern.

## Is this something you're interested in working on

Nein

**Comment by Ein-Tim** [comment]
Siehe auch #151

**Comment by Marco2907** [comment]
Hello @gempa-dirk, 
thank you for sharing your idea. This is similar to the issue https://github.com/corona-warn-app/cwa-wishlist/issues/151, as @Ein-Tim already has mentioned. What I would like to do, I will refer your proposal as additional information in threat https://github.com/corona-warn-app/cwa-wishlist/issues/151. Also, I will continue and close your issue as a duplicate. Please be invited to share additional ideas in the mentioned threat. 

Thank you,
MP 

Corona-Warn-App Open Source Team

**Comment by gempa-dirk** [comment]
Hi @Marco2907 ,

Es ist prima zu sehen, dass auch andere dieselben Ideen haben. Allerdings ist #151 auch schon ein paar Wochen alt und Corona ist schnelllebig. Hoffentlich werden solche Features bald zur Verfügung gestellt.

gp
