### ISSUE TITLE
QR-Code to App store printed on the Passenger Locator Form

### ISSUE THREAD

**Issue by alanrick** [corona-warn-app/cwa-wishlist#169]
## Current Implementation
The CWA works well technically, but improved propagation would increase the effectivity.

## Suggested Enhancement
The Passenger Locator Form (Aussteigkarte) that visitors and returnees to Germany fill out could include the qr-code to the Google and Apple appstores.

## Expected Benefits
There is space on the form in all languages to include a qr-code to the Appstores. Those filling in the form may motivated to download the app. 
E.g. _Receive test results immediately and confidentially + personalized risk updates_

Maybe this is the wrong place for such a suggestion, but I'm hoping there's some sort of communication between the App development team and the RKI who offer the [form:](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Transport/Aussteigekarten_Covid_Tab.html)

**Comment by mtb77** [comment]
Dear @alanrick.

thank you very much for contacting us.

This project is here for your question regarding the open source process of the Corona-Warn-App. Unfortunately this topic is not directly related to the app, the documentation or its website and so it must be closed. 

However this suggestion is very useful and I will try to inform one of our contacts at the RKI and give them this idea as an improvement.

Thank you very much,

Sascha

Corona-Warn-App Open Source Team
