### ISSUE TITLE
Show date of Low-Risk encounters

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#178]
## NEWS

This will be introduced with version 1.13: https://github.com/corona-warn-app/cwa-app-ios/pull/1882

## Current Implementation
Currently, when you had a Low-Risk encounter you just see that you had one (and that the app says it is Low-Risk) and no more information about the encounter. 

## Suggested Enhancement
Please inlcude the information when the encounter happend ("dd.mm.yy"), how it is done by High-Risk encounters.

## Expected Benefits
The user would know what he/she has done on this day and so know if there is anything special to do. (had I many or just a few contacts on that day/were I on a train this day (where the distance measurement is [not that good](https://www.infranken.de/ratgeber/technik/corona-warn-apps-scheitern-in-bus-und-bahn-studie-zeigt-abstandsalarm-schwaeche-art-5053913)), etc.)

## Additional Inforamtion
I know that the RKI denied to show more information about Low-Risk encounters, but could you please bring up exactly this suggestion and let us know what they are thinking?

---

## Related Issues

- https://github.com/corona-warn-app/cwa-backlog/issues/23
- https://github.com/corona-warn-app/cwa-wishlist/issues/100

----
Internal Tracking ID: EXPOSUREAPP-2836

**Comment by GisoSchroederSAP** [comment]
[color: green] or [color: red]

**Comment by GPclips** [comment]
Hello @Ein-Tim,

thanks for sharing your idea. I have created a JIRA ticket and assigned it to @hermesmar .

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by mweisbach** [comment]
Pls. also note issue >Display of "Tage seit letzter Risiko-Begegnung" is irritating< at https://github.com/corona-warn-app/cwa-documentation/issues/433.

**Comment by ndegendogo** [comment]
Another reason why cwa should show this to the user:
a user that gets such a warning without any details is worried, and trying to find out more details about the time of encounter, he finds the EN log file, and misunderstands these timestamps.

I have seen several such misunderstandings here in the discussions and questions again and again; we may assume that it happens quite often.

**Comment by leuchtetgruen** [comment]
I agree with what @ndegendogo wrote: I was in that very situation of misinterpreting log data, even going so far to write a little app that takes that log-json and puts the dates of what I thought were matches in a calendar view. When I discussed this idea and the prototype with friends and other people many of them wanted to have this app.

It was only later (luckily - being a responsable person - before providing this app to anybody) that I checked my assumptions more thoroughly. I realized that propably identified the date when an infected person uploaded the keys to the CWA server and not the date of encounter - essentially rendering my app useless.

The takeaway from this little story for me is that people also want to know when they had low risk encounters. 

For me personally for example this could be useful to avoid places in which I repeatedly encountered people who later reported an infection even if previous encounters didnt put me at risk (i.e. they were low risk encounters).

**Comment by fabboe** [comment]
This is only worthwhile if you can see days since last encounter for each of the risk categories. 

Currently you might have High Risk 7 days ago, then a day later you have still High Risk but 3 days ago. Was that three days ago now High Risk or Low Risk? Super confusing.

**Comment by Ein-Tim** [comment]
@fabboe 
This Issue is tracked here: https://github.com/corona-warn-app/cwa-documentation/issues/422

**Comment by scentury** [comment]
While waiting for this change to be implemented. Is my logic correct when saying that the day the "low-risk" warning disappears from the app, is 14 days after the "low-risk" exposure happened? 
Since the day the warning disappears is when data from 14 days ago is deleted, hence there is no data there to match the exposure anymore.

**Comment by Ein-Tim** [comment]
Yes your assumption is correct if the Encounter is more than 14 days old the App will not show the Encounter anymore

**Comment by daimpi** [comment]
Regarding OP: a possible extension of this in form of a graph which shows contacts over time has been proposed here: https://github.com/corona-warn-app/cwa-wishlist/issues/205 🙂.

**Comment by ohobby** [comment]
From my own experience, I can report that reporting that you have had one or more low risk encounters, but you don't know when it happened, causes many people to panic and/or brood a lot about when and where it happened. 
My partner and some friends are such candidates.
For this reason it would be very important that the date of the encounter is mentioned very quickly, even in the case of low risk encounters. This would help some users not to panic or brood. And prevent many requests to the health department and/or doctor.

**Comment by daimpi** [comment]
@ohobby 

I agree, that displaying this information would be really helpful.

Btw: if you have an Android device you can get this functionality (+more) already now by using @mh-'s [corona-warn-companion](https://github.com/mh-/corona-warn-companion-android). You don't even need root, you can simply run it in RaMBLE mode (for future encounters) 🙂.

**Comment by ohobby** [comment]
@daimpi 

Iam on iOS.

**Comment by daimpi** [comment]
@ohobby 
> Iam on iOS.

Ok. Under iOS the corona-warn-companion app unfortunately cannot work as iOS is filtering out all the BLE signals containing rolling proximity identifiers (RPIs) already on the OS level. So nothing except for the Exposure Notification Framework (ENF) which is directly integrated into iOS can even see them.

**Comment by stefanbode** [comment]
From a UI perspective, we can keep the main UI untouched but if the user clicks on the low/high risk, then we open a small list with the dates and color each date with yellow or red to give detailed information. Maybe if there where more than one low risk a day we can also add a counter similar to this:
2020-11-02 - low risk   - 1 contact
2020-10-30 - high risk  - 2 contacts
2020-10-25 - low risk    - 2 contacts

**Comment by daimpi** [comment]
@stefanbode see those two proposals: 
- [Encounter/Exposure logbook](https://github.com/corona-warn-app/cwa-wishlist/issues/205)
- [Different information about count and last contact for high and low risk matches](https://github.com/corona-warn-app/cwa-wishlist/issues/233)

Feel free to upvote 🙂.

**Comment by coder66** [comment]
This is very important to add, as it will allow the user to "estimate" when to look to symptoms. Eg when I have a low risk encounter and I know the test result date was 1 week ago, I can monitor my health better.

**Comment by ehambuch** [comment]
I tried to write an app that analyzes the ENF logfile which you can access in your settings. Unfortunately Google has blocked it :-(.
Nevertheless: this functionality must be provided in the original tracking app.

**Comment by Ein-Tim** [comment]
@ehambuch 
Maybe take a look at this: https://felixlen.github.io/ena_log/

**Comment by ndegendogo** [comment]
@ehambuch please be aware that the timestamps in ENF log file are **not** the timestamps of the contact, but only the timestamps of check.
Also the ENF log file shows only number of matches, but no risk assessment (like red / green).

**Comment by ehambuch** [comment]
> 
> 
> @ehambuch
> Maybe take a look at this: https://felixlen.github.io/ena_log/, is this like what you wanted to build or what did you wanted to analyze with the EN Log? Because more than which is done by @felixlen isn't possible...

Yes, the app covers more or less the same functionality, but with some charts etc.

**Comment by webermike** [comment]
Please show Date and Time of later on announced risk contacts, even if this leads to still having a green status.

As such contacts might occur only at shopping or eating in a restaurant, one can reconstruct with Date and Time where one habe been and if shopping or queuing anywhere is the risk reason.

This would enhance the analyse and discussion and avoiding of behavior in the future much, when it ia shown if the risk contact was at 8:00 in the bus ir at 12:00 in the McDonalds restaurant or at work at 10:00 o'clock at a certain date/day.

so it is not about "10 days ago" but about exact time and day.

Thanks for implementing that local showup fast.

**Comment by webermike** [comment]
Please show Date and Time of later on announced risk contacts, even if this leads to still having a green status.

As such contacts might occur only at shopping or eating in a restaurant, one can reconstruct with Date and Time where one habe been and if shopping or queuing anywhere is the risk reason.

This would enhance the analyse and discussion and avoiding of behavior in the future much, when it ia shown if the risk contact was at 8:00 in the bus ir at 12:00 in the McDonalds restaurant or at work at 10:00 o'clock at a certain date/day.

so it is not about "10 days ago" but about exact time and day.

Thanks for implementing that local showup fast.

**Comment by skyerjoe** [comment]
Im also for publish the Date and the Time only for the User. 

This is imho not an Dataprivvacy Problem thus u only know what u have done at this time and no one else.

So than u can react if u want or avoid things if u know okay at this time i was here and here so may i prevent theses locations as good as i can. 

best regards

**Comment by Ein-Tim** [comment]
@skyerjoe 

And exactly this is the problem, you know what you've done, where you were, who you met and so can identify the person.
Also the exact time is not revealed by the API, see [this](https://github.com/corona-warn-app/cwa-backlog/issues/23#issuecomment-678692630) comment from @kbobrowski. 

The exact date would be possible, see #188

**Comment by webermike** [comment]
We need to know if - at the exact time -  I met with Anke or was at the birthday party or McDonalds. Otherwise i cannot refine my behavior to avoid clusters like Lidl or the bus. Also teachers can warn class 5a instead of 6b.
There is no data protection problem nor a technical reason. Every computer has at any time a time stamp.

**Comment by mh-** [comment]
Different people come to different conclusions regarding this privacy concern, that's why I wrote this app which does show time (and, when used with the RaMBLE recording app, even position) of the risk encounters:
https://play.google.com/store/apps/details?id=org.tosl.warnappcompanion

My reasoning: It is extremely unlikely that your device only scanned RPIs from one other phone at that time, so you cannot identify the other person. But I understand and accept that other people have different opinions.

**Comment by webermike** [comment]
The identification of the personbis good and intended. When I met with Anke and she announces tonbe ppsotive via app, she has to tell me anyway. That is what Gesundheitsdienst tries to reseaech via a phone call. Tell me all contacts you remmeber. CWA has them recorded and can give you hints if I was at that time with Anke or at Mcdonalds.

**Comment by Ein-Tim** [comment]
@webermike But if you get the phone call from the Gesundheitsamt they don't tell you like:
"Yeah Anke Beispielname was tested positive and you met with her at xx:xxh in McDonalds" but they only tell that you met somebody who later tested positive, or? 

And no, I don't think that the App would have that high of an adoption rate if everybody could identify his contacts...

So or so this is your opinion and what I wrote is mine.
But I can tell you from a technicall aspect that this is not possible with the current implementation.

**Comment by webermike** [comment]
Have your opinion. Technical allnisbppssiblenor cam be made. When Anke tells Gesundheitsamt my phone number, so that they call me, is she allowed to give my phone number away? Law needs to be adusted that in case of pandemic infection people need =MUST not only to Quarantine, but because of incubation time of 7-14 days all known contacts within that time out of privacy. Otherwise the system is not working..person in private by state order, known contacts of last 14 days in information over public Partner by state order, while the public partner keeps this private and informs only the private person. I am Thankful if any contact or Anke of last 14 days is forced to give me a hint. Only that way I can protect my grandma. And for low risks, i can change my behaviour if I see that tables at mcdonalds are too close to each other screwed at the ground.

**Comment by Ein-Tim** [comment]
@GPclips 
Is there any update about this? Did the Team speak with the RKI about it?

**Comment by Blackjacx** [comment]
I also want to bring in the suggestion to **not** show `x days ago` but to show the **exact day including the weekday** so we all know immediately which day an encounter happened and we don't have to calculate back in mind. 

It makes lives way easier.

**Comment by Ein-Tim** [comment]
@Blackjacx 
See #188

**Comment by vaggelisdouros** [comment]
Trying to balance privacy vs. revealing some meaningful information, may I suggest/re-iterate that, as a minimum, the app should display whether a low-risk was "old" or it is a "new" one?

Motivation: imagine that today the app shows 1 low-risk encounter, meaning that, during the last 14 days, I had a contact with someone who tested positive. 

If the next day the app shows again 1 exposure with low risk, can we at least know whether it corresponds to the previous case (the "old" encounter) or whether that encounter disappeared but a new encounter appeared?

**Comment by daimpi** [comment]
@vaggelisdouros currently as a workaround you can check the EN log to find out whether this is a new encounter (as log as you're under iOS). 
But the situation will improve significantly once the [exposure history](https://github.com/corona-warn-app/cwa-wishlist/issues/205) gets implemented 🙂.

**Comment by Ein-Tim** [comment]
Starting with v 1.12.0 there will be the exposure history shown in the App (https://github.com/corona-warn-app/cwa-app-ios/pull/1801). This will be shown for "High"- and "Low-Risk" encounters. 
This would indirect introduce this too - maybe @dsarkar could update us about this Issue. 
Why won't you show the date of "Low-Risk" encounters directly, but only in the exposure history?

**Comment by GisoSchroederSAP** [comment]
Let me quickly give an answer on-first-shot: When the concept of "red and green only" was established in the very beginning of the CWA, is was quite obvious: Once a warning with "red" risk appears, the user has to take action. A dedicated function was implemented to support this "red" state. 
In contrast to the red card, the "green" status doe not require special attention - therefore (with respect to the limited time and resources), there the function to grab the date of the last green encounter was not implemented yet.
Yes, it seems to be inconsistent. Yes the the exposure history will show both types, still it will require two different methods to gather the respective information for red versus green encounters.

I hope, this explains the "Why?" at the current stage.

**Comment by Ein-Tim** [comment]
Thank you so much for answering @GisoSchroederSAP.❤️

Just btw:
You could get the membership of the Corona-Warn-App Organization here on GitHub (or make it public) so that it is clearer that you are a member (yes your Name is kinda telling this, but I also saw other users with SAP in their names here and it seemed like they have nothing to do with the CWA project at all). 🙂

**Comment by Ein-Tim** [comment]
This will be introduced with version 1.13: https://github.com/corona-warn-app/cwa-app-ios/pull/1882.

**Comment by Ein-Tim** [comment]
Version 1.13 which introduced this has been released to GitHub and is available to all users in the next 48h. 

See blog post: 

DE: https://www.coronawarn.app/de/blog/2021-03-04-corona-warn-app-version-1-13/
EN: https://www.coronawarn.app/en/blog/2021-03-04-corona-warn-app-version-1-13/

See GitHub release:

iOS: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.13.0
Android: https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.13.2

This issue will now be closed.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks!
