### ISSUE TITLE
Suggestions for Risk Details / Period logged UI section in app

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-wishlist#180]
## Current Implementation
The **Period logged** section in the Risk Details UI of the app is confusing.

1. In the sentence "This period is included in the calculation." it is not clear what "This" is referring to.
2. The suggestion regarding having logging permanently active delays the reader getting to the actual information about the period logged.

I have only looked at the Android implementation. This may also apply to the iOS implementation as well.

![20200910_114656](https://user-images.githubusercontent.com/66998419/92715739-2915ee80-f35e-11ea-98a8-f3c9832ad075.jpg)

## Suggested Enhancement
1. Remove  `risk_details_subtitle_period_logged` <string name="risk_details_subtitle_period_logged">"This period is included in the calculation."</string> from [include_risk_details_period_logged_card.xml](https://github.com/corona-warn-app/cwa-app-android/blob/dev/Corona-Warn-App/src/main/res/layout/include_risk_details_period_logged_card.xml). This subtitle is redundant and confusing.
2. Move the `risk_details_period_logged_progress` to before `risk_details_period_logged_body_notice`. The headline "Period logged" is then immediately followed by information about the period logged.

The result would be for example:

**Period logged**

Exposure logging covers the past 14 days. During this time, the logging feature on your device was active for 14 days. The app automatically deletes older logs, as these are no longer relevant for infection prevention.

Your risk of infection can be calculated only for periods during which exposure logging was active. The logging feature should therefore remain permanently active.

## Expected Benefits
The changed layout increases readability. The immediately important information is presented first, followed by additional information.

---
Internal Tracking ID: EXPOSUREAPP-2618

**Comment by svengabr** [comment]
Hey @MikeMcC399 

Thank you for your suggestion. I created a Jira Ticket and assigned it to @MarisaWollner to take a look.

Best regards,
SG

Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
This enhancement request is obsolete because in version 1.15 the text has been changed. The app no longer shows how long exposure logging was active. 

This is what is shown when the app was installed more than 14 days previously:

![Period logged full](https://user-images.githubusercontent.com/66998419/113578182-b08cbd00-9622-11eb-9647-74bbfcae4dbf.jpg)

Some of the suggestions made in this enhancement request concerning the ordering of information have already been implemented in the new text, so there is no need to keep this enhancement request open any more.
