### ISSUE TITLE
Poll for multiple test results (esp. for parents with small children)

### ISSUE THREAD

**Issue by fkoehne** [corona-warn-app/cwa-wishlist#182]
## Feature description
As a **parent** of a child in childcare (with confirmed COVID cases and in quarantine) I would like to scan more than one QR-Code, in order to receive test results for both me and my child asap.

## Problem and motivation
This is a stressful situation for small children, since we tried to maintain physical distancing within our family, as far as possible. Returning to normality a bit earlier would be really helpful, but small children do not own CWA-capable devices.

Since childcare facilities are usually quarantined completely, generating a large number of tests and child-separation struggles, this feature could be relevant for a considerable number of users.

## Is this something you're interested in working on
Yes, but I can only provide feedback, documentation or test support.

**Comment by Ein-Tim** [comment]
Please see #109

**Comment by fkoehne** [comment]
Thanks - voted for it.
