### ISSUE TITLE
Test-Pipeline

### ISSUE THREAD

**Issue by FHellmann** [corona-warn-app/cwa-wishlist#184]
In my opinion, the app should be a passive supporting system that notifies the user in case of viral contact.

1. Corona-Test
The users go to a Corona testing station and register themself with a unique QR-Code provided by this app. This could be manually or automatically by a machine - scanning the QR-code and printing it on a sampling vial.
(Benefits: speeding up the testing queue; particularly interesting for a large number of people to process like airports and such)

2. Corona-Test Result Notification
The QR-code label on the sampling vial also helps the labs to "identify" the user by sending the test result to the Corona-App backend with the unique identifier, which then forwards the notification of the result to the user's app. In addition, notify the user of what they are supposed to do now (e.g. "stay at home for 10 days", "get yourself tested now").

3. Corona-Test Result Contact Notification
Without the users' doing, the app should automatically notify all relevant contacts when receiving a positive lab result.

---

Internal Tracking ID: EXPOSUREAPP-2866

**Comment by heinezen** [comment]
Hey @FHellmann,

Thanks for your submission. I've forwarded your feature request to the internal Jira with ticket ID EXPOSUREAPP-2866. You should get updates on the staus of your request here when they are available.

CH

----
Corona-Warn-App Open Source Team

**Comment by larswmh** [comment]
Closing this issue as its related internal ticket was set to obsolete.

> This would need a change of the whole process for the local health authorities and the technical process inside the app, which is no longer realistic
