### ISSUE TITLE
Show date when the Risk Encounter happend instead of „xx Day(s) ago“

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#188]
## Feature description
I think it would be good to show the Date of an Risk Encounter (f.e. the App would show: "Letzte Risiko Begegnung am: 20.09.2020"), and not only the Number of how many days have past since the Encounter ("9 Tage seit letzter Risiko Begegnung").  

## Problem and motivation

It would be clearer to the user when the Risk Encounter happens and additionally, the confusing how the counting happens would be solved (https://github.com/corona-warn-app/cwa-app-ios/issues/1032)

---
If there's already an open Issue requesting this, please point me to this Issue, I didn't find one.

**Comment by daimpi** [comment]
The issue you linked kinda requests this as well (under "Expected Behavior"):

> Instead of a relative expression of time ("vor n Tagen"), you could as well switch to expressing time in absolute terms ("Am 27. May"). Stating a precise date would probably be less prone to programming errors, and it would be less ambiguous and potentially more helpful for the user.

**Comment by Ein-Tim** [comment]
Thx @daimpi, will close this Issue in favor of https://github.com/corona-warn-app/cwa-app-ios/issues/1032. 👍

**Comment by Ein-Tim** [comment]
This will be introduced with 1.8.0: https://github.com/corona-warn-app/cwa-app-ios/pull/1550

**Comment by skyerjoe** [comment]
Only for ios ?

**Comment by Ein-Tim** [comment]
@skyerjoe 

No, also for Android (I think with: https://github.com/corona-warn-app/cwa-app-android/pull/1677)
