### ISSUE TITLE
Provide ENF version number at bottom of App-Information screen

### ISSUE THREAD

**Issue by vaubaehn** [corona-warn-app/cwa-wishlist#190]
## Avoid duplicates
* [X] This enhancement request has not already been raised before
**I'm reading _everything_ inside the Android repo - and didn't find anything similar.**

* [X] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
**As far as I know/remember, iOS is already showing a second version number below CWA's one. I guess it's the Apple ENF version number.**

* [X] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
**It's not really a new feature, but a neat enhancement.**

## Current Implementation
On the information screen (CWA > menu > app-information), at the bottom, CWA version number is displayed.

## Suggested Enhancement
Below that version number, additionally Google's ENF version number could be displayed.
For version >= 1.6 => show exact number
For version <1.6 => show "1.0/1.5"
(If devices without Google Play Services are able to reach that information screen => "not supported")

## Expected Benefits
This would facilitate support, and save time for me (and most likely others), instead of navigating through all the necessary screens up to the Google COVID19-Exposure-Notification-screen, where to find the version number at the very bottom after a long scroll.

## Some more context
Some birds are tweeting from the roof tops, that not immediately, but soon a new class is introduced to CWA, that checks ENF version number. I guess (and hope) it's not too much of effort, to make use of that class, to get the version number and provide it as additional information to the user.

However, this is not a top priority enhancement.
:heart: 

---
Internal Tracking ID: EXPOSUREAPP-2794

**Comment by vaubaehn** [comment]
Another idea for an enhancement of above enhancement:

If the functionality of the `ACTION_EXPOSURE_NOTIFICATION_SETTINGS` [action ](https://developers.google.com/android/reference/com/google/android/gms/nearby/exposurenotification/ExposureNotificationClient#constant-summary) is still available, and the text of the ENF version number would be clickable for `ENF_version >= 1.6` then a short cut to Exposure Notification settings page could be provided, like Luka already prepared back in June:

https://github.com/corona-warn-app/cwa-app-android/pull/291/files#diff-6cbad94172691ea7c8aeb53479cfbad0bd124eaf277df5b1ac6c05cde7dbecc6

L49+

Maybe it's something you'd like to try out for relaxation in your coffee break, @d4rken ? ;)
I hope, you're doing well, btw.
Cheers, v.

**Comment by harambasicluka** [comment]
> [...] like Luka already prepared back in June:
>
> https://github.com/corona-warn-app/cwa-app-android/pull/291/files#diff-6cbad94172691ea7c8aeb53479cfbad0bd124eaf277df5b1ac6c05cde7dbecc6

@vaubaehn Just out of curiosity how much time did you spend to find this? 😄 

Shouldn't be a problem to include the ENF version and could also help our testers. What do you think @d4rken 

& thank's for your ongoing support in our repo!! Really appreciate it :)

**Comment by vaubaehn** [comment]
@harambasicluka 
 
> 
> > [...] like Luka already prepared back in June:
> > https://github.com/corona-warn-app/cwa-app-android/pull/291/files#diff-6cbad94172691ea7c8aeb53479cfbad0bd124eaf277df5b1ac6c05cde7dbecc6
> 
> @vaubaehn Just out of curiosity how much time did you spend to find this? smile

Haha... Actually, it took just a few minutes:
Yesterday, scrolled through my ENF log, and thought, how nice it would be to have a short cut to the COVID-19-notification page from inside CWA. Remembered, that there was an action used by the EN Api, finally found it in the API reference. Out of curiosity I googled https://www.google.com/search?q=ACTION_EXPOSURE_NOTIFICATION_SETTINGS to find out, if some app has implemented it yet. And as there are just a handful of resuts, I quickly found your old PR :) (you will probably need to enable 'show skipped results')

> 
> Shouldn't be a problem to include the ENF version and could also help our testers. What do you think @d4rken ?

That would be nice :) and together with the short cut absolutely perfect.

> 
> & thank's for your ongoing support in our repo!! Really appreciate it :)

You're so welcome. Like @d4rken wrote in some other place: 'we're all together in this pandemic'. So, why not trying to save some lives together? (even we can't measure any outcome directly, preventing only one severe case of illness it's already worth it, imho)

However, I need to step back a little in these weeks due to my own (working) responsibilities.

Anyway, I hope you're all fine, and the team's mood is good. You all did a huge job in the past weeks. Thanks for your engagement!

Hope to see you soon again!

**Comment by d4rken** [comment]
More :beer: than :coffee: but I support any efforts to empower the community :muscle:.

**Comment by vaubaehn** [comment]
That's nice, thank you and enjoy your :beer:  ;)

**Comment by Ein-Tim** [comment]
This is now included in version 1.9.1 of CWA-Android. 
https://github.com/corona-warn-app/cwa-app-android/pull/1592
@dsarkar I think this can be closed (or is there a way to implement something like this on iOS too? I don't even know if there is a ENF version number like this under iOS 😅 Maybe you could clarifying this?)

**Comment by dsarkar** [comment]
Hi @vaubaehn, once you could update to CWA 1.9.1., please, give us some feedback. Thanks, DS

@Ein-Tim, 

> is there a way to implement something like this on iOS too? I don't even know if there is a ENF version number like this under iOS 😅 Maybe you could clarify this?

I will forward this question to the developers, thanks, DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@Ein-Tim Feedback from the developers:
Quote: 

> Im iOS gibt es keine ENV "version", ENF ist inhärent im iOS, die iOS-Version bestimmt daher die ENF-Version

**Comment by Ein-Tim** [comment]
Okay thanks @dsarkar, than you can close this Issue

**Comment by vaubaehn** [comment]
@d4rken @harambasicluka 

This is probably going to be the most sad wishlist comment that has ever been written...

Matthias just confirmed to me in person, that his contract has ended. And Luka, because I haven't seen any activity from you for quite a long time, I'm suspecting very much the same is true for you.

I'm incredibly sad (and I guess, all your colleagues, too).
Not only that you two helped to push this project onto an uncomparable level of quality by a lot with your ideas, coding, and so on.
Also your communication with the community enhanced the whole project, imho.
You will be missed very much.

But I'm also a bit happy for you, that you now have some more time for yourselves again, and that you are able to follow your own projects that needed to step back due to work for CWA.

Guys, what I wrote here: https://github.com/corona-warn-app/cwa-app-android/pull/1592#pullrequestreview-531911284
is still true: anytime you come to HH, feel free to ping me and get your free 🍺 .

Thanks for all your contributions! All the best to you!

**Comment by vaubaehn** [comment]
Ha... @dsarkar , I still owe you a feedback:

> Hi @vaubaehn, once you could update to CWA 1.9.1., please, give us some feedback. Thanks, DS

Yes, it's working fine, and I'm using it often! 🎉
