### ISSUE TITLE
Late warning about increased risk

### ISSUE THREAD

**Issue by weso0013** [corona-warn-app/cwa-wishlist#191]
A friend of mine was Corona positive and reported - conscientiously as he is - the whole thing via the Corona-Warn-App (on a Samsung S10 with Android 10) and after the hotline had given him a TAN, the test was also shown as positive.
His wife (Corona negative) was told 2.5 days later about an increased risk via the app (although she checked several times).
I would have expected her to get a warning within 24 hours after he reported positive.

What is the reason for this late warning? And can this be improved?

---
Internal Tracking ID: EXPOSUREAPP-1883

**Comment by daimpi** [comment]
I just received report of a [similar case](https://twitter.com/Rabax/status/1317880040907018240). 
The situation is the following Person A & B are living in a household together i.e. have continuous contact. 

The timeline looked like this:
- 17.10. person A got their positive test result and submitted their DKs in CWA. This submission happened around midnight (CEST), but before 02:00 CEST.
- 18.10. checks performed on B's phone on the 18th at 02:33 didn't yield any matches.
- 19.10. checks performed at 08:26 find matches and yield an increased risk (last contact 3 days ago): 
<img src="https://user-images.githubusercontent.com/22129968/96666213-f7c61080-1356-11eb-98fe-d158792f4af4.png" width="300">

Why wasn't Person B already warned on the 18th? Shouldn't DKs uploads before 02:00 CEST (00:00 UTC) still go into the package for the upcoming day?

- Log: [PersonB-log.txt](https://github.com/corona-warn-app/cwa-wishlist/files/5412956/PersonB-log.txt)

**Comment by daimpi** [comment]
Does someone know what the latest point in time is for when DKs uploaded on day 1 will still be added to the daily package which becomes available on the following day?
@christian-kirschnick @Tho-Mat @EvgeniiSkrebtcov maybe? 🙂

**Comment by cfritzsche** [comment]
I guess with 1.7.1 out we can close this issue?

**Comment by dsarkar** [comment]
HI @weso0013, as @cfritzsche suggests, with the new updating schedule of CWA version 1.7.1 this issue becomes obsolete. Do you agree to close this issue? Thanks for the feedback.  Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by weso0013** [comment]
@dsarkar Yes, for sure!

Thanks!

**Comment by dsarkar** [comment]
@weso0013, thanks for contributing! Best wishes, DS

---
Corona-Warn-App Open Source Team
