### ISSUE TITLE
Anzeige der Zeit von Risikobegegnungen

### ISSUE THREAD

**Issue by bjacke** [corona-warn-app/cwa-wishlist#193]
## Current Implementation

Momentan wird nur angezeigt, vor wie vielen Tagen die letzte Risikobegegnung war. Es wird keine Zeit angezeigt und es wird nicht angezeigt, wann ältere Risikobegegnungen gewesen sind.

## Suggested Enhancement and extected Benefits

Schön wäre, wenn man eine Liste der Zeiten oder ggf. einen 14-Tage-Zeit-Grafen sehen könnte, um abschätzen zu können, wann und wo die Risikobegnungen stattgefunden haben. Das ist wichtig, weil man dann selbst sein persönliches Risiko dazu abschätzen kann. Wenn man z.B. tagsüber alleine zu Hause war und zu solchen Zeiten Risikobegegnungen haben soll, weil man z.B. unmittelbar neben einer Schule wohnt, wo die Corona-App Begegnungen loggt, die aber gar keine wirklichen Begegnungen waren, kann man solche false-positive Risikobegegnungen dann ausschließen. Wenn man die Begegnungs-Zeiten nicht  genauer nachvollziehen kann, ist die Information über Risikobegegnungen generell wenig wert, wenn man sich häufiger in "Bluetooth-Reichweite" mit anderen befindet, obwohl man sich nur in seinen eigenen 4 Wänden aufhält.

**Comment by heinezen** [comment]
Hey @bjacke,

Thanks for your submission. Your suggestion is looks very similar to what was discussed in https://github.com/corona-warn-app/cwa-wishlist/issues/100. The RKI also published a general statement regarding this (available here: https://github.com/corona-warn-app/cwa-wishlist/issues/100#issuecomment-690279530). I hope this answers your question.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
Duplicate of #100

**Comment by bjacke** [comment]
(Ich erlaube mir mal auf Deutsch zu antworten, da da die Entwickler und User ja alle von hier sind)

> Thanks for your submission. Your suggestion is looks very similar to what was discussed in #100. The RKI also published a general statement regarding this (available here: [#100 (comment)](https://github.com/corona-warn-app/cwa-wishlist/issues/100#issuecomment-690279530)). I hope this answers your question.

Der issue 100 ist zwar ähnlich, aber dort geht es um theoretische Anfragen nach dem Feature zu "mehr Details sehen", während ich hier einen realen Use-Case beschreibe, der hier tatsächlich aufgetreten ist und der mit steigenden Fallzahlen bei anderen auch noch häufiger auftreten wird: Wenn man Eine Risiko-Warnung bekommt, obwohl man vorbildlich überwiegend die Zeit in der eigenen Wohnung verbringt, muss man grob sehen können aus welchem Zeitfenster die gemeldeten Exposures-Warnungen kommen. Ich bekomme ganz konkret von der CWA ein "Hohes Risiko" angezeigt, obwohl ich in den letzten Tagen die Wohnung nicht verlassen hatte. Wenn der Zeitpunkt der Exposure-Begegnungen nicht ansatzweise nachvollziehbar ist, führt das, den Sinn und Zweck der CWA komplett ad absurdum, denn dann bekommen auch (oder vor allem) diejenigen, die kaum vor die Tür gehen, ein hohes Risiko angezeigt, wenn die Nachbarschaft im Haus ein Exposure hat.

Ich hoffe, dass diese zusätzliche Erklärung jetzt das Problem nochmal etwas deutlicher gemacht hat. Ich bitte daher auch, dass dieser Request nicht von einem Entwickler einfach geschlossen wird, sondern möglichst vom RKI kommentiert wird. Der von Ihnen verlinkte Kommentar vom RKI nimmt auf die hier beschriebene Problematik keinen Bezug und die Aussage, dass die App "möglichst einfach und allgemeinverständlich" sein muss, widerspricht nicht dem angefragten Feature, der ungefähren Anzeige der Zeit der Exposure-Begegnungen. Das Gegenteil ist der Fall, zeitlich unverifizierbare Exposure-Warnungen führen dazu, dass man als User den Warnungen der App kein Vertrauen mehr schenken kann und die CWA zwar "einfacher" aber de facto unbrauchbar wird.

Zum technischen Machbarkeit: Das Feature sollte mir dem ExposureWindow mode der Google API umsetzbar sein, die CWA nutzt aktuell offenbar nur den legacy v1 mode.

**Comment by heinezen** [comment]
@bjacke 

My intention when closing the issue was not to imply that your request is ignored. Sorry, if you understood it that way. The reason I refer to #100 is that it should cover your specific use case, since the data you want to have shown is also extracted from the Apple/Google Exposure API information. The features you describe and their implications were discussed in #100's comments, too. Therefore, it makes sense to continue the discussion there to keep it focused and better to track for the developers.

Btw, the statement does address your request here:

> Zudem wird geprüft, ob mit einem späteren Update eine Risikobegegnungshistorie in der App dargestellt werden kann.
----
> In addition, we will check whether a later update will allow a risk encounter history to be displayed in the app.

The risk encounter histry should be in line with what you described in your previous post. The details about the extent of the feature or when it will be integrated are currently discussed with the developers and the RKI. Once we have updates on this, we will publish them in this repository.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by tangomanni** [comment]
Ich unterstütze den Request von bjacke in vollem Umfang und gehe sogar noch einen Schritt weiter. Auch bei einem Kontakt der mich auf "niedrigem Risiko" lässt möchte ich wissen wann dieser Kontakt war. Ich habe heute die Mitteilung einer Begegnung mit niedrigem Risiko bekommen. Jetzt kann ich der App trauen oder nicht, und ich möchte wissen aufgrund welcher Parameter der risk calculation (Entfernung, Zeitdauer, Infektiosität) das Risiko niedrig eingestuft wurde. Wenn ich den Tag und ungefähr die Zeit weiß dann weiß ich auch (durch meine Buchhaltung) wo ich da war (Einkaufen, beim Arzt, Spazieren) und kann das Risiko auch noch aus meiner Sicht einschätzen.
Das ganze ist natürlich noch wichtiger wenn ein "erhöhtes Risiko" vorliegt.
Ich bin für die CWA und würde ihre Anwendung propagieren, aber dieser Fall jetzt läßt mich doch etwas verunsichert zurück.

Beste Grüße
tangomanni

**Comment by Ein-Tim** [comment]
@bjacke 
Schau mal #178 an, in diesem Issue wird gefragt ob man nicht zumindest die Tage seit der Begegnung in die App implementieren könnte. Die genaue Zeit ist leider nicht möglich da das ENF (die API (von Apple/Google auf die CWA zurückgreift) keine genaue Zeit nicht an die CWA weitergibt.

>P.S. Wie lange habe ich jetzt diese Anzeige jetzt in der App ?

Die Begegnung bleibt so lange in der App bis die Begegnung älter als 14 Tage ist.

**Comment by tangomanni** [comment]
Ok..danke
