### ISSUE TITLE
DP3T iOS SDK: why not use it to take care about background updates. (Spanish Radar Covid)

### ISSUE THREAD

**Issue by ouboub** [corona-warn-app/cwa-wishlist#194]
hi

I have been for 14 days in Spain, using Corono Radar, after some quirks it did the log exposure (key download) in a much more coherent fashion  than the Corona Warn App. The developers pointed out to me that they use 

> DP3T iOS SDK takes care about background updates.
> As far as I know CoronaWarn does not use this dependency

So could't the corona Warn up use this as well.
regards
Uwe Brauer

**Comment by svengabr** [comment]
Dear @ouboub,

thank you very much for your proposal.

To give the community a space for discussing new feature ideas or enhancements that might not be taken up immediately by the development teams, we created the cwa-wishlist repository.

This idea is one of these feature ideas or enhancements. Consequently, we will move this issue to this repository and allow the community and you to further refine it, discuss pros and cons, and evaluate alternatives.

The issue will not be closed in this repository to ensure long-term visibility. All issues in the cwa-wishlist repository will be discussed with our contracting entities. They will decide whether they will be implemented or pursued further. As soon as we have any updates, we will let you know about the details.

Best regards,
SG

Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Just for keeping track:
@thomasaugsten stated [here](https://github.com/corona-warn-app/cwa-app-ios/issues/916#issuecomment-718941101):
>Background task for CWA and DP3T is almost identical because the whole work is done by iOS.

**Comment by ouboub** [comment]
> Just for keeping track:
> @thomasaugsten stated [here](https://github.com/corona-warn-app/cwa-app-ios/issues/916#issuecomment-718941101):
> 
> > Background task for CWA and DP3T is almost identical because the whole work is done by iOS.

be it as it may, but  as a end user (iPhone SE) io13 or ios14 I can tell you this:

I had **no** issues with the spanish app concerning actualization
but I **do** have them with the corona warn.

**Comment by thomasaugsten** [comment]
Which issue exactly can you post your exposure log?

**Comment by Ein-Tim** [comment]
@ouboub Can this be closed since background updates seem to work reliable since version 1.7? Or do you still want to switch to the DP3T SDK?

**Comment by ouboub** [comment]
the background updates work now reliably

**Comment by ouboub** [comment]
>>> "ET" == Ein Tim <notifications@github.com> writes:

> @ouboub Can this be closed since background updates seem to work
> reliable since version 1.7? Or do you still want to switch to the DP3T
> SDK?

No, I will close it, thanks for reminding me.
