### ISSUE TITLE
Personal contact diary

### ISSUE THREAD

**Issue by ouboub** [corona-warn-app/cwa-wishlist#196]
THIS ISSUE IS CLOSED - 
PLEASE MONITOR/CONTRIBUTE IN ONE OF THE LISTED ISSUES HERE: https://github.com/corona-warn-app/cwa-wishlist/issues/310
---

ORIGINAL POST
---

## Feature description

I best refer to the app (only available for Android) https://www.coronika.app/) Could such features be included in the 
App. 

1. Import contacts from the iOs or Android native contact app

    2. Add contacts manually

    3. Add a meeting (encounter) with someone (if it occurred longer than 15 min) with the following features

       a. Name

       b. Localization (via GPS)

       c. Date+Time

    4. Show all the meetings in a list that covers the last 14 Days (optionally delete all meetings older than 14 day to keep it tidy).

       1) Show how many meetings you had every day

       2) show how many locations these meetings occur each day

    5. When tested positive: allow to send the meeting as a attachment, containing, the names, localization date+time, either

       a. As an email

       b. Or whatsapp or other messengers
       

![corona-app](https://user-images.githubusercontent.com/5957203/94833562-8f4ada00-040f-11eb-80ed-29593b47ffb0.png)

That was also a proposal by Karl Lauterbach 
https://www.zeit.de/digital/2020-08/corona-warn-app-coronavirus-eindaemmung-karl-lauterbach-henning-tillmann

regards

Uwe Brauer 

---
Internal Tracking ID: EXPOSUREAPP-3034

**Comment by heinezen** [comment]
Hey @ouboub,

Can you also list the features from Coronika that you want in the Corona-Warn-App here on Github? This will make it easier for us to track them.

Thanks.

----
Corona-Warn-App Open Source Team

**Comment by ouboub** [comment]
ok, here it goes
    1. Import contacts from the iOs or Android native contact app

    2. Add contacts manually

    3. Add a meeting (encounter) with someone (if it occurred longer than 15 min) with the following features

       a. Name

       b. Localization (via GPS)

       c. Date+Time

    4. Show all the meetings in a list that covers the last 14 Days (optionally delete all meetings older than 14 day to keep it tidy).

       1) Show how many meetings you had every day

       2) show how many locations these meetings occur each day

    5. When tested positive: allow to send the meeting as a attachment, containing, the names, localization date+time, either

       a. As an email

       b. Or whatsapp or other messengers
       

![corona-app](https://user-images.githubusercontent.com/5957203/94833562-8f4ada00-040f-11eb-80ed-29593b47ffb0.png)

**Comment by heinezen** [comment]
@ouboub Thank you!

Now I can create a Jira ticket with the info 👍 

----
Corona-Warn-App Open Source Team

**Comment by ouboub** [comment]
thanks! Is there a way to watch the progress made on this issue?

**Comment by heinezen** [comment]
@ouboub It will be discussed internally with the developers and the RKI first. They will decide if and how the feature is implemented. Once there is any concrete update information we can give out on the progress, it will be posted here. So if you are subscribed to this issue, you should be notified if there are any news.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by ouboub** [comment]
> @ouboub It will be discussed internally with the developers and the RKI first. They will decide if and how the feature is implemented. Once there is any concrete update information we can give out on the progress, it will be posted here. So if you are subscribed to this issue, you should be notified if there are any news.
> 
> Regards,
> CH
> 
> Corona-Warn-App Open Source Team

fair enough, thanks

**Comment by GisoSchroederSAP** [comment]
Beside the manual maintenance/entries for this diary, other users also request logging thoses times and places, where the app retrieved significant contacts (according to time and duration). Even better if the location could be stores (as coordinates) or the interface offers again the chance to manually update the location with a human-readable string , like "super market".
Ideally, those meta information could be used on the server side to calclate "risk clusters" where many persons romp around (super market, street demonstration, Football or Soccer Game...)

**Comment by fwilhe** [comment]
I had a similar idea when listening to the recent corona virus update podcast. I think even being able to write down a short text description each day as part of the app like "went to restaurant" or "took the bus" might be helpful in case of infection.

**Comment by kyklos** [comment]
Any update with the Personal contact diary feature available?

**Comment by pkreissel** [comment]
I would like to add a further idea on this: 

The app should alert me, even if I only had a "low risk" encounter during a timeframe, that was manually tagged as "possible cluster situation" in the cluster diary. 

For example: Sitting in a poorly ventilated restaurant for hours could be a high risk encounter due to aerosol transmission even if there is enough distance to everyone else in the room. In this case CWA should alert anyone who was in the same room, even if the signal was weak. 

This would also nudge people further to use the diary and the app and to understand what cluster situations are and how risky they can be.

However this would require the ENF to give us the exact point in time the risk was detected (see [here](https://github.com/corona-warn-app/cwa-wishlist/issues/213#issuecomment-712499976)).

**Comment by rvbaer** [comment]
Good day,

The app is currently unusable for people who are in frequent professional contact with potentially infected people.
These people are well protected during professional activities and have a low risk.

On the other hand, you may have critical contacts in your private sphere without appropriate protection.

The user can assign the notifications of the app to currently unprotected or unprotected periods. Accordingly, they will ignore indications of increased risk.

As a suggestion for improvement, the app should therefore display the time slots of the contact not just by days but preferably by hours. Alternatively, for reasons of data protection, longer periods, such as 3-hour periods, would be better than the current solution.

**Comment by rugk** [comment]
Good point, @rvbaer and actually interesting use case IMHO.

> The user can currently not differentiate the notifications of the app to unprotected or protected periods.

For now, I see one good workaround: Don't have your phone next to you (or disable location services on Android or Bluetooth during these situations.

However, regardless of all of it, I would personally suggest you, @rvbaer to open a new issue describing this as a feature request. Because I actually don't immediately see how a personal contact diary would solve this use case. Maybe there are better ideas for solutions for this use case. (Please fill out the issue template, that would help IMHO.)

**Comment by daimpi** [comment]
There is this proposal for an encounter/exposure logbook which would probably at least help a little: https://github.com/corona-warn-app/cwa-wishlist/issues/205 but encounters there would probably still be to coarse to distinguish b/c CWA cannot get any information on the time-point of the encounter that is finer than one day. 

@rvbaer as a workaround: if you have an Android device I would recommend using the [corona-warn-companion](https://github.com/mh-/corona-warn-companion-android) app in RaMBLE mode (where you don't even need a rooted device). You can simply download it from the play store together with RaMBLE for free. You then can turn on RaMBLE whenever you actually want to record encounters and you will get an exact date and timestamp for each of them 🙂.

**Comment by rvbaer** [comment]
Thanks @daimpi for the workaround - Have installed corona-warn-companion and await first results. 
This looks like a nice workaround for me.
But it will unfortunatley not be of any help for the several hundredthousands of health care workers who experience the same problem daily.


@rugk 

Thanks for your suggestion and support by regarding "The user can currently not differentiate the notifications of the app to unprotected or protected periods" as intersting use case.

Will follow the advice and open a new issue describing this as a feature request.

**Comment by rvbaer** [comment]
@rugk thanks 

Opened #251 just a second ago

**Comment by FHellmann** [comment]
A beneficial feature indeed.

I want to add a suggestion:
When the GPS location of each meeting with another person is tracked, this information could be anonymized and send to a public server (e.g., health ministerium) to create a map of high infection spots. This could help investigate the spreading and the places where it takes place the most.
To bring even more dynamic to the App the users could be notified of high-risk locations when entering or getting close to one to avoid these and stay clear of the risk.

**Comment by rugk** [comment]
GPS is never tracked in the CWA app and as per Google/Apple's policies they are also not allowed to do this. Besides that, 
If you have a restaurant hotspot or so where #162 would be implemented (or there is the existing paper trail solution with leaving contact information), you can get the same information anyway.
So IMHO no, it's not a good idea, as this defeats the way the app is built in a private way and could let users worry about their privacy (if the app were collecting GPS signals). Also, this is quite unrelated to this issue/feature request of a contact diary.

**Comment by daimpi** [comment]
Looks like the diary feature is being targeted for CWA 1.10 (h/t @Ein-Tim): https://github.com/corona-warn-app/cwa-app-ios/pull/1651 🙂.

**Comment by MikeMcC399** [comment]
The contact journal has been pre-announced for CWA version 1.10 on the [Corona-Warn-App Blog](https://www.coronawarn.app/en/blog/2020-12-24-corona-warn-app-version-1-10-announcement/) today.

**Comment by alanrick** [comment]
Excellent! I’ve been doing this (Google Keep) since  September and found it’s very easy to maintain but when I looked back I’d forgotten many meetings  (but I’d found then in the log)

**Comment by ouboub** [comment]
>>> "MM" == Mike McCready <notifications@github.com> writes:

> The contact journal has been pre-announced for CWA version 1.10 on the
> [Corona-Warn-App
> Blog](https://www.coronawarn.app/en/blog/2020-12-24-corona-warn-app-version-1-10-announcement/)
> today.

Does anybody know when this release is supposed to published?

**Comment by ouboub** [comment]
> Excellent! I’ve been doing this (Google Keep) since September and
> found it’s very easy to maintain but when I looked back I’d forgotten
> many meetings (but I’d found then in the log)

As of today there are at least three contact diary apps in the App Store

    1. Coronika (also for android)

    2. Cluster diary

    3. Kontakt Tagebuch

Before I used diaro which allows you to inform your contact individually
(and also allows your to add via GPS the address) but does not posses
any specific Covid19 tools such as 

    1. masks

    2. distance

    3. Ventilation

**Comment by Ein-Tim** [comment]
@ouboub 

> Does anybody know when this release is supposed to published?

Should be released in early January 2021

**Comment by dsarkar** [comment]
See https://www.coronawarn.app/en/blog/2020-12-24-corona-warn-app-version-1-10-announcement/

**Comment by Ein-Tim** [comment]
@ouboub 
Version 1.10.1 has just been released!

**Comment by ouboub** [comment]
>>> "ET" == Ein Tim <notifications@github.com> writes:

> @ouboub 
> Version 1.10.1 has just been released! 

Hello

I checked 10 minutes ago and it wasn't there, now it is. Thanks for
letting me know. Meanwhile digging in the github repository I think I
know who did most of the that particular code. I tried to write him
directly but did not receive any reply.

I checked the journal. I have to say it is very very rudimentary (also
better than nothing). Things that are missing 

    1. No import from the iOS contact list possible.

    2. No entries for: mask has been used.

    3. Distance kept.

    4. Outside/inside

    5. Cluster?

    6. No import of single meetings possible.

Right now, the iOS apps:

    1. coronika

    2. Cluster diary

    3. Kontakttagebuch

Have these features save the last one.

Regards

**Comment by jucktnich** [comment]
When you add a person wich is a double of a person entered sooner, there should be a dialog wich askes, if you want to
- use the existing
- edit the entry
- use both

**Comment by ouboub** [comment]
>>> "j" == jucktnich  <notifications@github.com> writes:

> When you add a person wich is a double of a person entered sooner, there should be a dialog wich askes, if you want to
> - use the existing
> - edit the entry
> - use both

I disagree. I think the better and cleaner solution would be to access
the iOS contact list directly as all the other contact diary apps in iOS do.

**Comment by Ein-Tim** [comment]
Please note that the contact diary included in version 1.10.1 is "MVP Scope" ([Source](https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.10.1).
This means that this version only includes the most basic features of a contact diary.

**Comment by alanrick** [comment]
> Excellent! I’ve been doing this (Google Keep) since September and found it’s very easy to maintain but when I looked back I’d forgotten many meetings (but I’d found then in the log)

Just to say I really like the way it's been implemented. Much better than using Keep for this purpose 👏👏👏 (although I've now grown addicted to keeping a short diary for other reasons)

**Comment by ouboub** [comment]
@alanrick 
did you try one of these
<table border="2" cellspacing="0" cellpadding="6" frame="border" rules="all">


<colgroup>
<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">Nombre</th>
<th scope="col" class="org-left">Language</th>
<th scope="col" class="org-left">Access</th>
<th scope="col" class="org-left">individual</th>
<th scope="col" class="org-left">14 days</th>
<th scope="col" class="org-left">mask</th>
<th scope="col" class="org-left">out/in</th>
<th scope="col" class="org-left">location</th>
<th scope="col" class="org-left">Link</th>
<th scope="col" class="org-left">Price</th>
</tr>


<tr>
<th scope="col" class="org-left">&#xa0;</th>
<th scope="col" class="org-left">&#xa0;</th>
<th scope="col" class="org-left">Apple contact</th>
<th scope="col" class="org-left">reports</th>
<th scope="col" class="org-left">report</th>
<th scope="col" class="org-left">&#xa0;</th>
<th scope="col" class="org-left">&#xa0;</th>
<th scope="col" class="org-left">via GPS</th>
<th scope="col" class="org-left">&#xa0;</th>
<th scope="col" class="org-left">&#xa0;</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-left">Contact journal</td>
<td class="org-left">English</td>
<td class="org-left">yes</td>
<td class="org-left">yes</td>
<td class="org-left">no</td>
<td class="org-left">no</td>
<td class="org-left">no</td>
<td class="org-left">yes</td>
<td class="org-left"><a href="https://apps.apple.com/de/app/contacts-journal-crm/id327685977?l=en">contact journal</a></td>
<td class="org-left">28 Euros</td>
</tr>


<tr>
<td class="org-left">Diaro</td>
<td class="org-left">English</td>
<td class="org-left">yes</td>
<td class="org-left">yes</td>
<td class="org-left">no</td>
<td class="org-left">no</td>
<td class="org-left">no</td>
<td class="org-left">yes</td>
<td class="org-left"><a href="https://apps.apple.com/de/app/diaro-diary-journal-notes/id882519460?l=en">Diaro</a></td>
<td class="org-left">free</td>
</tr>


<tr>
<td class="org-left">Cluster diary</td>
<td class="org-left">English</td>
<td class="org-left">yes</td>
<td class="org-left">no</td>
<td class="org-left">yes</td>
<td class="org-left">yes</td>
<td class="org-left">yes</td>
<td class="org-left">no</td>
<td class="org-left"><a href="https://apps.apple.com/de/app/cluster-diary/id1535388491?l=en">Cluster Diary</a></td>
<td class="org-left">free</td>
</tr>


<tr>
<td class="org-left">Kontakttagebuch</td>
<td class="org-left">German</td>
<td class="org-left">Yes</td>
<td class="org-left">no</td>
<td class="org-left">yes</td>
<td class="org-left">yes</td>
<td class="org-left">yes</td>
<td class="org-left">no</td>
<td class="org-left"><a href="https://apps.apple.com/de/app/kontakt-tagebuch/id1535797892?l=en">kontakt-tagebuch</a></td>
<td class="org-left">free</td>
</tr>


<tr>
<td class="org-left">Coronika</td>
<td class="org-left">English</td>
<td class="org-left">Yes</td>
<td class="org-left">no</td>
<td class="org-left">yes</td>
<td class="org-left">yes</td>
<td class="org-left">yes</td>
<td class="org-left">no</td>
<td class="org-left"><a href="https://apps.apple.com/de/app/coronika/id1538427759?l=en">Coronika</a></td>
<td class="org-left">&#xa0;</td>
</tr>
</tbody>
</table>

**Comment by alanrick** [comment]
Sorry. No. Keep was good enough. CWA is better.

**Comment by Ein-Tim** [comment]
This could be closed since the contact diary was introduced with version 1.10.1. 
For additional feature requests, I would say, it makes sense to create new Issues. 
An overview over them can be found in #310.

**Comment by Ein-Tim** [comment]
@dsarkar Can you close this?

**Comment by dsarkar** [comment]
@ouboub, and community. Thanks for all the contributions here. We close this issue now and please monitor/contribute to one of the listed issues here: #310, Many thanks. Best, DS


---
Corona-Warn-App Open Source Team

**Comment by JensF4711** [comment]
So, before all these functionality (might) be implemented: Which kinds of contacts should be entered in the contact diary?

What are the criteria? 
distance, kind of masks, tightness of masks, activity (speaking, sport, shouting, singing, breathing), altitude difference (of faces), orientation (face to face, back to back, ...), relative velocity, indoor / outdoor, ventilation / air filtering, age of persons, duration, using lipstick, wiping the nose before, gargling before (with ...), wind (direction, velocity), temperature, humidity, kind of glasses / face shield

[Or maybe simple the RKI contact person category 1 and 2 ](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Kontaktperson/Management.html;#doc13516162bodyText8)?

Maybe as a fast solution the contact definition could be put in the app as a helping text. 

P.S.: 
[The effect of aerosols can be computed by a tool from the Max-Planck-Institut für Dynamik und Selbstorganisation Göttingen    ](https://aerosol.ds.mpg.de)

**Comment by JensF4711** [comment]
As notice in the documentation a export of the diary is already possible. For me it seems that transfer them via Threema is possible - but this is not mention in the documentation. I am sorry - as I am not an App developer I not succeeded to find the corresponding part in the source code. 

By the way: Transferring the diary via Signal, Telegram, Threema, Matrix PGP encrypted mail (to the public health department) would be good - but I think this is already on the wish list.

**Comment by heinezen** [comment]
> So, before all these functionality (might) be implemented: Which kinds of contacts should be entered in the contact diary?

> What are the criteria?
> distance, kind of masks, tightness of masks, activity (speaking, sport, shouting, singing, breathing), altitude difference (of faces), orientation (face to face, back to back, ...), relative velocity, indoor / outdoor, ventilation / air filtering, age of persons, duration, using lipstick, wiping the nose before, gargling before (with ...), wind (direction, velocity), temperature, humidity, kind of glasses / face shield

There are no explicit criteria defined except for "places where you were/people who you met". Generally, every user can decide for themselves which contacts or places they enter. However, we could include a more general guidelines. If you think this is a good idea, please make a separate issue for this. 

The criteria you name are often very difficult to assess, e.g. wind velocity. But we have feature requests for free text fields (#314) and indicators for the eneral envorinment (#308).

----
Corona-Warn-App Open Source Team

**Comment by JensF4711** [comment]
> There are no explicit criteria defined except for "places where you were/people who you met". Generally, every user can decide for themselves which contacts or places they enter. However, we could include a more general guidelines. If you think this is a good idea, please make a separate issue for this.
> 
> The criteria you name are often very difficult to assess, e.g. wind velocity. But we have feature requests for free text fields (#314) and indicators for the eneral envorinment (#308).
> 
> Corona-Warn-App Open Source Team

I think the RKI has to define the needed criteria. I guess the public health departments will ask questions about the kind of the contacts after they have received lists / names. Thus, the issue has to be created by somebody else.
