### ISSUE TITLE
Show absolute date instead of relative date („X days ago“)

### ISSUE THREAD

**Issue by tibor** [corona-warn-app/cwa-wishlist#197]
## Current Implementation
Encountered risks are currently displayed to the user using relative dates.

## Suggested Enhancement
Instead or additional there should be an absolute date.

## Expected Benefits
At the moment it is unclear to the user if today is counted as 1 day ago or 0 days ago. Also, it is not clear if the counter steps up at midnight or at the time when the risk encountered. Also, different hotlines gave different information to an user asking for more information (https://twitter.com/anked/status/1309386934259781638). An absolute date would make those information much clearer.

**Comment by Ein-Tim** [comment]
Please see #188

**Comment by tibor** [comment]
Thanks, @Ein-Tim. Will close this issue. [The main issue can be followed here](https://github.com/corona-warn-app/cwa-documentation/issues/433)

**Comment by Ein-Tim** [comment]
This will be introduced with 1.8.0: corona-warn-app/cwa-app-ios#1550
