### ISSUE TITLE
[Discussion] Information of positiv Contacts

### ISSUE THREAD

**Issue by QuadStingray** [corona-warn-app/cwa-wishlist#198]
## Feature description
If you had contact with any positiv testet person it would be Great to see informations about the contact. 

Ideas for informations (not sure that this are available):

* datetime of contact 
* distance 
* geoposition 
* duration

**Comment by daimpi** [comment]
Similar to #100, #178 (@svengabr could you reopen #100 until we get more info from the RKI? This would help ppl to avoid duplicates)

Regarding geoposition: This is not possible within the Google/Apple Exposure Notification Framework (ENF) as access to- and protocolling of geolocation is explicitly forbidden for privacy reasons.

Regarding datetime I'll quote my reply from [here](https://github.com/corona-warn-app/cwa-documentation/issues/433#issuecomment-698978622):
> The exact timestamp of an encounter is not exposed by the Exposure Notification Framework (ENF) for privacy reasons afaik. Therefore CWA cannot show an exact time but only the day when the exposure occurred (see [here](https://github.com/corona-warn-app/cwa-backlog/issues/23#issuecomment-678692630) for more details on the response CWA gets from ENF). If you have a rooted android device you can bypass this restriction e.g. with the [corona-warn-companion-android](https://github.com/mh-/corona-warn-companion-android) though.

Regarding the display of the day of the encounter (for green encounters): This is tracked in this [issue](https://github.com/corona-warn-app/cwa-wishlist/issues/178) and hopefully we will soon see some movement on this issue 🤞.
