### ISSUE TITLE
Testing TAN for testing the report flow

### ISSUE THREAD

**Issue by corneliusroemer** [corona-warn-app/cwa-wishlist#2]
A lot of valuable issues have been created since the general public has been able to use the app.

One part that is not reachable for the interested public to test is the "when positively diagnosed report" flow. It's something that we can only get to once positively tested. It is thus particularly badly tested and error prone.

Question: Is there a test/mock TAN like "0000-0000-0000" that can be entered to test the flow for crashes/UI/bugs? Of course, it should be visible that this is a "mock" report, but it would allow a much wider audience with a bigger assortment of devices to check whether the app functions correctly in this so very crucial use case.

---
Internal Tracking ID: EXPOSUREAPP-2133

**Comment by larswmh** [comment]
Closing this issue as the related internal ticket is set to `completed`.

Developer comment:
> Testing TANs is possible for our testers since a long time already.
