### ISSUE TITLE
Add test result of my children

### ISSUE THREAD

**Issue by dlemm** [corona-warn-app/cwa-wishlist#200]
## Feature description
As a parent I would like to add the test result of my children. If my child had a positive result I would became a person with a higher risk and I would like to warn people I have met.

Test if children so not have a qr cose, there it it not possible to add it to the app. It is most likely that if my children have a positive test result that I will have it , too. But that might be just minimum two days later.

## Problem and motivation

So in order to break the chain this could help to inform people a lot faster. And reduce the spreading.

## Is this something you're interested in working on

No, I have not the skill to add it to the app, unfortunately.

Related issues:
---
#109

---
Internal Tracking ID: [EXPOSUREAPP-2068](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-2068)

**Comment by Ein-Tim** [comment]
Similar to #109.
Please look at this Issue and think if this Issue is really needed. Thanks 👍

**Comment by dlemm** [comment]
Yes I agree it is kind of similar. Only problem is, that there is no test qr-code on tests for younger children. I am not sure about older children though. So a manually added test result might be needed. So not sure if #109 would also solve this ticket.

**Comment by Ein-Tim** [comment]
Okay, understand your point 👍
We'll wait for the devs and see (cc @mtb77)

**Comment by Xyz00777** [comment]
here is one problem. if you add a test to your app then you (your test, your child test or what ever) than it get connected to the IDs from your CWA (Corona Warn App). but your child have propably other persons connection like you. and when you add the test to yur app the persons who have conntact with you got informed (wrong information spread) (my understanding how the app is working).
Also there need to be a option where you could add something like a personalized ID from a other person, so you should be able to add that the test is associated with the IDs of the other person and not with your IDs.

**Comment by dlemm** [comment]
There are two warning messages, so the one with "slightly risky" could be used for the case that one member of the family is tested positively. 
Adding test results from other IDs seems like double warning because I would get a message if I had contact to that person in my app. But perhaps I didn't get your point.

What I think is, adding tests for like toddler old children who have no mobile phones and are most of the time around parents.

**Comment by Xyz00777** [comment]
oh i think i slightly misunderstood your request.

**Comment by dsarkar** [comment]
Updated Internal Tracking ID [EXPOSUREAPP-2068](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-2068) with this issue.

**Comment by Ein-Tim** [comment]
FYI: https://github.com/corona-warn-app/cwa-wishlist/issues/109#issuecomment-823308830 says: 

> I'm sorry to say that the feature request [#109] has been declined by the development team and will not be pursued further. The reason for this is that the main reason for receiving a test is sharing the result and warning others. Entering a test result of another family member and sharing the result should not be the focus of the app, because then the random IDs collected by the device do not correspond to the persons the familiy member met.

**Comment by heinezen** [comment]
@Ein-Tim 

Yes, sorry, this issue here is declined for the same reason. We will also close it.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
FYI: It seems like there is something planned for 2.21: https://github.com/corona-warn-app/cwa-app-android/pull/4947

@dsarkar Could you reopen this issue & apply the `Fix 2.21` label?

**Comment by Ein-Tim** [comment]
FYI: This has been implemented with version 2.21: [Corona-Warn-App Version 2.21 now allows test management for family members](https://www.coronawarn.app/en/blog/2022-04-19-cwa-2-21/).

**Comment by dlemm** [comment]
Awesome. Thank you for your update

**Comment by Ein-Tim** [comment]
You're very welcome @dlemm! Would you like to close this issue now?

**Comment by larswmh** [comment]
Closing this issue as suggested, no response from issue author in time.
