### ISSUE TITLE
Additional, stationary receivers (for cafe's e.g.)

### ISSUE THREAD

**Issue by sdillenburg** [corona-warn-app/cwa-wishlist#201]
I am unsure whether this was brought up before or not. The efficienty of the app could be increased by designing and distributing stationary receivers that can be set-up in cafe's, restaurants, etc.
If one of the devices recognizes a postive contact, coresponding date and time of the contact can be made available to the owner (of the cafe, etc.) who then shares this data and the list of guests present at the time in question to the authorities.

Just an idea...

**Comment by sdillenburg** [comment]
Dublicate of: https://github.com/corona-warn-app/cwa-wishlist/issues/162

**Comment by heinezen** [comment]
https://github.com/corona-warn-app/cwa-wishlist/issues/138 is the main issue for this feature, since most of the discussion takes place there.

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
Duplicate of #138
