### ISSUE TITLE
Kilroy token (presence token/attendence list token)

### ISSUE THREAD

**Issue by speters** [corona-warn-app/cwa-wishlist#204]
## Feature description

Possibility to generate a presence token on request/user interaction.
Generated token is visualized as a human-readable sentence/dissimilar characters and in a machine-readable way (barcode, qrcode).

Additionally, token generation can be done by photographing a qrcode containing an official url which contains a registered identifier for the locality (callback url, id of an official , etc.) in the request data.

## Problem and motivation

Last weeks showed that contact tracing by public health offices often was very problematic, as people left incorrect, faked or unreadable data on the attendance lists in restaurants, bars, etc.
Part of the problem is that in normal business, personal data along with addresses, phone numbers, etc. is not exchanged with the location's operators and people naturally hesitate to hand over sensitive data.

By enabling the Corona Warn App to generate a "_Kilroy token_" ("I was here token"), the personal data in attendence lists could be substituted by this token.

In its simplest form, the token is a human-readable sequence of words, icons or dissimilar characters which can easily hand-written in a list.
Token should provide at least means of a simple human plausibility check.

A more elaborate development would be to show a barcode/qrcode along with the human-readable token to enable better plausibility checks or data processing.
A  "_Kilroy token_" generation could also be initiated by following a QRcoded URL (to an official website with location operator identifier in request data).

Similar to the Bluetooth tokens, these tokens get transmitted to the Corona Warn App servers by the Corona Warn App which generated it.

## Is this something you're interested in working on

No, sorry. My Java/Kotlin/Swift proficiency does not suffice.

**Comment by achisto** [comment]
As I see it your suggestion is quite similar to #138, maybe take a look at the already ongoing discussion over there.

**Comment by speters** [comment]
Thx, for pointing this out.

Duplicate of #138 

Closing to minimize further confusion.
