### ISSUE TITLE
Add inzidenz

### ISSUE THREAD

**Issue by chris-redbeed** [corona-warn-app/cwa-wishlist#210]
## Suggested Enhancement
Adding the current incident of your current location to App.

## Expected Benefits
RKI has a simple API to get the current incident for each german district. Maybe you can set/select the location without a geolocation service to prevent data protection or the app use your current location.

This simple number will help each person in Germany because everyone is currently watching the number.

**Comment by Ein-Tim** [comment]
Similar to #151. Could you maybe comment there and close this Issue, so we can focus the Discussion on one ticket.
