### ISSUE TITLE
Add Share-Option to Onboarding Menu

### ISSUE THREAD

**Issue by sbernhard** [corona-warn-app/cwa-wishlist#212]
There should be a option to share that "I'm" using the Corona-Warn-App to protect us from Lockdown 2 and stop corona.

There is already a button to select on which channel (like twitter, facebook, instagram, Whats App Status) you want to tell others, that you are using the app and the others should follow to install the corona-warn-app. 

When installing the app, this window should appear automatically.

The reason for this feature is, that we need more users of the Corona-Warn-App and we need to let everyone know, that it's no risk to use this app.

**Comment by Ein-Tim** [comment]
![image](https://user-images.githubusercontent.com/67682506/96448202-53878100-1213-11eb-81ef-22ac13e1f8de.jpeg)
There is already this Share Option in the App. Do you still think the Share  Option has to be included in the "Installing Part"?

**Comment by sbernhard** [comment]
Oh. Missed that part. 

Well, adding this to the installing part would be nice, too.

**Comment by Ein-Tim** [comment]
@sbernhard 
Okay, maybe you could change the title of this Issue to:
"Add Share-Option to Onboarding Menu", than its clearer what this Issue is requesting 👍
Thanks

**Comment by sbernhard** [comment]
@Ein-Tim I can not find the option in Android. Are you sure this option exist? Does it only works once / is it hidden afterwards?

**Comment by Ein-Tim** [comment]
@sbernhard 
No it should always work, I'm not very familiar with android, but maybe @daimpi can help here

**Comment by daimpi** [comment]
@sbernhard @Ein-Tim 
> I'm not very familiar with android, but maybe @daimpi can help here and clarify this

sure 🙂 

Step 1:
<img src="https://user-images.githubusercontent.com/22129968/96453935-73bb3e00-121b-11eb-832c-06853c9ae6a5.png" width="300">

Step 2:
<img src="https://user-images.githubusercontent.com/22129968/96453659-132c0100-121b-11eb-8279-176a120188bf.png" width="300">

**Comment by sbernhard** [comment]
Thanks @daimpi

**Comment by heinezen** [comment]
Hey @sbernhard 

Since your request seems to be solved already, I will close this issue now.

Regards,
CH

----
Corona-Warn-App Open Source Team
