### ISSUE TITLE
Semi-Automated Source-Cluster Detection

### ISSUE THREAD

**Issue by fstandhartinger** [corona-warn-app/cwa-wishlist#213]
Whenever several people with Corona-Warn-App are close to each other, the app should log such moments. 
A timestamp is sufficient. 
No storage of personal or GPS data necessary.

In case of a positive test or risk warning: Time stamp goes to the health authority. 

This would help to help affected persons to find out source clusters.
It allows the health department to ask the following question during the follow-up: 
"Where were you last Monday afternoon? The app has recorded that you were among a lot of other people back then."

Details and discussion about this idea here (in german):

https://twitter.com/Florian83616025/status/1316734257059037185

![image](https://user-images.githubusercontent.com/1905188/96448139-4074b100-1213-11eb-9489-0f50928ac2f3.png)

     

---
Internal Tracking ID: EXPOSUREAPP-3331

**Comment by Ein-Tim** [comment]
@fstandhartinger 
The exact timestamp of an Encounter is not given to CWA by the ENF at the moment, so this isn't really possible to introduce with the currently used way the App is programmed.

**Comment by fstandhartinger** [comment]
Thats sad, but thanks for the quick answer. 
If the CWA would query the latest state from ENF lets say 4 times a day, would it then be capable of storing an information like this:
User has been in high exposure situation with multiple people on Monday afternoon?
That might be sufficient to help the health authorities with backward contract tracing (which is arguable worth more than forward contact tracing when it comes to lower infection spread).

**Comment by daimpi** [comment]
@fstandhartinger 
> If the CWA would query the latest state from ENF lets say 4 times a day, would it then be capable of storing an information like this: 
User has been in high exposure situation with multiple people on Monday afternoon?

Unfortunately no: all of this is handled within the Google/Apple Exposure Notification Framework (ENF) and not exposed to CWA: 
- If an encounter is found (by ENF) only the day of the encounter will be exposed, not the exact time (see [here](https://github.com/corona-warn-app/cwa-backlog/issues/23#issuecomment-678692630) for more details on the response CWA gets from ENF)
- The number of non-positive contacts is not exposed to CWA by ENF: https://github.com/corona-warn-app/cwa-wishlist/issues/124#issuecomment-660121125

**Comment by heinezen** [comment]
Hello everyone,

I've mirrored the feature request to Jira. Even if it is not possible to implement right now, the cluster detection mechanism can be discussed in this thread. Official responses on the issue will also be posted here.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by kyklos** [comment]
Hello everyone,

What is the current status of the important request? 
I see a lot of open points in cwa-wishlist here, but I think the cluster detection should be a great help from a medical point of view. The clusters appear to be the biggest driver of the pandemic. If it is technically possible, why is this not simply implemented?

**Comment by daimpi** [comment]
@kyklos as stated above: the implementation proposed in OP is unfortunately **not** technically possible within the current ENF system. One thing which could actually be implement though is a type of "venue registration" which would allow users to register if they visit high risk / high density events. See e.g. #138 for such a proposal.

**Comment by kyklos** [comment]
@daimpi Thank you for your comments. What is not technically possible within the current ENF system? A venue registration is a other implementation feature and If cluster detection is an idea, why not use even if it means adjustments to the ENF system.

**Comment by daimpi** [comment]
@kyklos 
> What is not technically possible within the current ENF system? 

1. Querying information on non-positive encounters
2. Even for positive encounters querying exact timestamps is not possible, the info exposed by ENF is coarsened to a one day time frame.

> I know CWA currently only queries ExposureSummary but why not using ExposureInformation?

This wouldn't help. Same points (1) and (2) apply there. Even [ENF v.1.5+ with `ExposureWindow` mode](https://github.com/corona-warn-app/cwa-documentation/issues/373) is still restricted by those.

> […] why not use even if it means adjustments to the ENF system.

This is something Google/Apple would have to implement as they're in control of the ENF but maybe the CWA-Team could forward this request to them 🙂.

**Comment by kyklos** [comment]
> @kyklos
> 
> > What is not technically possible within the current ENF system?
> 
> 1. Querying information on non-positive encounters
> 2. Even for positive encounters querying exact timestamps is not possible, the info exposed by ENF is coarsened to a one day time frame.
> 
> > I know CWA currently only queries ExposureSummary but why not using ExposureInformation?
> 
> This wouldn't help. Same points (1) and (2) apply there. Even [ENF v.1.5+ with `ExposureWindow` mode](https://github.com/corona-warn-app/cwa-documentation/issues/373) is still restricted by those.
> 
> > […] why not use even if it means adjustments to the ENF system.
> 
> This is something Google/Apple would have to implement as they're in control of the ENF but maybe the CWA-Team could forward this request to them 🙂.

@daimpi Thank you pointing out.  It seems to me that ENF is restricted. When ENF is coarsened to a one day time frame why not create an additional database on the devices, insert needed data und use them to build such or other feature? A control of the ENF would be also great so forward a request Google/Apple.

**Comment by daimpi** [comment]
@kyklos 
> When ENF is coarsened to a one day time frame why not create an additional database on the devices, insert needed data und use them to build such or other features?

You mean in the sense that CWA itself would record BLE tokens aka RPIs? CWA cannot do this because this is not allowed for ENF apps by Google/Apple. See [this thread](https://github.com/corona-warn-app/cwa-wishlist/issues/100) for further discussion on this topic.

**Comment by fstandhartinger** [comment]
Yet another idea:

CWA could just record how many other bluetooth devices are in range. 
Lets say once every 5 minutes. 
Then store that together with a timestamp. 
Completely without using ENF, just using the normal bluetooth features of the smartphone.

Using this information it should still be possible to detect and show moments in the past weeks, where the user was obviously exposed to more devices (i.e. very likely more human contacts) than usual.

Would that be possible?

______________________ some additional info here ________________________

Why is it so important?

We have to be aware:
*Backward* contact tracing (source cluster detection) is be far more efficient in containing virus spread than *forward* contact tracing. This is because of the high dispersion of the virus. 

Explanation: 
We statistically know that 4 in 5 infected people are not infectious. They can not pass on the virus, because their virus load is not high enough in their upper respiratoral tract. 
The whole virus spread happens, because 1 in 5 infected people *can* pass on the virus to others, these are the (super-)spreaders we need to detect.
In forward tracing a lot of energy is spent to identify the people the current case could have infected. But knowing that 4 of 5 don't pass on the virus means that in 80% of the cases this work is actually useless.
In backward tracing (source cluster detection) we try to find the event in which our current case caught the virus. It is pretty sure that in this event we find the 1 in 5 person that actually was infectious. 
And quite possibly this event may have led to a couple of other infections that developed in parallel to our case, which all are very likely in the same stage themselfes now, 1 in 5 on them likely currently infectious.
Thus source cluster detection is far more efficient, because we are not spending our energy on situations that are only 20% relevant for the virus spead, but instead focus on situations where we can expect close to 100% relevance.

**Comment by Ein-Tim** [comment]
@fstandhartinger 

> Would that be possible?

No I don't think so:
1. Apple and Google (mainly Apple) have strict guidelines how Bluetooth can be used in the background if it's scanning for other devices (see the France Corona App which doesn't use the ENF, it has to be opened in the foreground to be active...)
2. The RPIs (Bluetooth Beacons your Handy records and sends) change every 15-20 minutes, so after this time there are only "new" Devices and you can not know if this is really a new device or just a device which changed it RPI...

**Comment by daimpi** [comment]
@fstandhartinger unfortunately @Ein-Tim is correct afaik: CWA itself is not allowed to record BT signals see [this thread](https://github.com/corona-warn-app/cwa-wishlist/issues/100) for further discussion on this topic.

@Ein-Tim 
> The RPIs (Bluetooth Beacons your Handy records and sends) change every 15-20 minutes, so after this time there are only "new" Devices and you can not know if this is really a new device or just a device which changed it's RPI...

This is correct but probably wouldn't pose a problem if you just want to find out how many ENF devices are approximately near you at a given point in time. If you have a short recording window (say a few sec) the number of unique RPIs recorded in a given window will (in expectation) be very close to the number of ppl with ENF around.

@fstandhartinger 
Regarding backward contact tracing / automated cluster detection: I agree that this is a very good and important idea from an epidemiological perspective (see also [this paper](https://arxiv.org/abs/2005.02362) via @pdehaye who has probably much more to say on this topic) but I think Google/Apple would have to implement such a functionality directly into ENF for it to work properly.

**Comment by fstandhartinger** [comment]
Thanks for the feedback! Is there any way you (or myself) can create a feature request for the Exposure Notification API? 
I searched, but didn't find the forum where I could do that - maybe it's access is restricted to developers of the local warn apps?
Best regards Florian

**Comment by fstandhartinger** [comment]
As I didn't find a better way to contact google/apple on this I create a generic support ticket here:
https://support.google.com/android/thread/80101430?hl=en
Anyhow, if you know the correct place to post this feature request, please give me a hint. Thank you

**Comment by daimpi** [comment]
@fstandhartinger 
> As I didn't find a better way to contact google/apple on this I create a generic support ticket here:
support.google.com/android/thread/80101430?hl=en

Upvoted 👍 

Other than that there is the Google exposure-notifications-internals repo: https://github.com/google/exposure-notifications-internals/issues but the devs there [suggested](https://github.com/google/exposure-notifications-internals/issues/3#issuecomment-665158988) (in a different context) to address requests via the respective national ENF app teams who have a dedicated channel: 
> Hi,
>
> Thanks for your question. Unfortunately this is not a great place to report or discuss such issues. The best advice I can provide is that these issues should be shared with the Public Health Authority/App developer in your region. Those partners. can then share that feedback with Google via their DevRel contacts.

**Comment by fstandhartinger** [comment]
Dear CWA devs, please use your DevRel channel to directly push this topic with Apple/Google.

Please be aware this may be a key change to the effectiveness of pandamic containment strategy.
Its cruical.

This is imporrtant. I can't stress this enough!
It's having huge potential to save lives!

Thank you

**Comment by MikeMcC399** [comment]
@fstandhartinger 
There is also an e-mail address for Google 
exposure-notifications-feedback@google.com
however I wouldn't expect too much from that e-mail address. I did once get a reply from them after I reported a bug that they had fixed but not yet released.

The app is published by the [Robert Koch Institut](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Warn_App.html) however I haven't seen any direct involvement here from them, so I suspect you would need to get into direct contact with RKI for any major strategic addition to the CWA functionality. I may of course be wrong about this; I'm just a voluntary community member.

**Comment by alanrick** [comment]
> The app is published by the Robert Koch Institut however I haven't seen any direct involvement here from them

Me neither. They don’t even report usage statistics in their daily situation reports.
 
Very disappointing.

**Comment by MikeMcC399** [comment]
@alanrick 
> They don’t even report usage statistics in their daily situation reports.

The CWA app statistics are handled separately and they are reported on the RKI website weekly under [Übersicht zu aktuellen und früherer Zahlen und Fakten zur Corona-Warn-App (ab 12.10.2020)](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Archiv_Kennzahlen/WarnApp_KennzahlenTab.html). 

RKI could certainly do a better job about integrating the app reports into their other reports and site pages. The English language documents and German documents are inconsistent in the way they link into the app reports, so if you don't know your way around, you may not even find them on the RKI site.

These reports are however also manually copied into the [App Blog](https://www.coronawarn.app/en/blog/).

The usage statistics from yesterday Nov 13, 2020 are [on the RKI site here](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Archiv_Kennzahlen/Kennzahlen_13112020.pdf?__blob=publicationFile).

**Comment by alanrick** [comment]
I know the statistics are available. It just appears that while the RKI is happy to remain the owner of this prestigious project it does not have an interest in its success and doesn't regard it as operationally significant.

**Comment by Ein-Tim** [comment]
Could we please have a clarification about this wishlist item and #240 & #355. 

Is a cluster detection in any form possible with the currently used GAEN-Framework?

**Comment by dsarkar** [comment]
"Cluster Event" functionality will be implemented in Release 1.16.

**Comment by alanrick** [comment]
@dsarkar Is it the exact method that @fstandhartinger proposed at the start of this thread? If not, is there a user-story that we can read that describes the "Cluster Event" capability.

**Comment by dsarkar** [comment]
@alanrick Not that method described in the OP, which is actually with the current ENF impossible to implement as discussed by the community above. It is a QR code based check-in functionality. You will find PR in the iOS and Android repository named "Event Registration"

**Comment by alanrick** [comment]
Thanks @dsarkar. 
I guess I'd have to interpret the code in the Pull Request to figure it out for sure.  But would it be fair to say this is not semi-automated, but a _manual_ cluster detection similar to the [CrowdNotifier](https://github.com/CrowdNotifier/documents)?

And unlike the Luca App, darfichrein... there is no additional connection to the local health center and only anonymous data is exchanged so it is not used for tracing.

I ask to avoid confusion about whether this complements Luca App/darfichrein, or whether it replaces them.

**Comment by alanrick** [comment]
Just to add, the App mentions the site www.coronawarn.app/en/Screenshots as a means to discover what's coming in future releases, but, sadly, the "cluster event" isn't described.

**Comment by Ein-Tim** [comment]
@alanrick 

Please see https://github.com/corona-warn-app/cwa-documentation/issues/547

**Comment by larswmh** [comment]
Closing this issue as the related internal ticket is set to obsolete
