### ISSUE TITLE
Share corona-warn-app usage by Twitter, Instagram, Facebook WhatsApp Status

### ISSUE THREAD

**Issue by sbernhard** [corona-warn-app/cwa-wishlist#214]
There should be a option to share that "I'm" using the Corona-Warn-App to protect us from Lockdown 2 and stop corona. 

In case the button is pressed, you can select on which channel (like twitter, facebook, instagram, Whats App Status) you want to tell others, that you are using the app and the others should follow. 

When installing the app, this window should appear automatically.

The reason for this feature is, that we need more users of the Corona-Warn-App and we need  to let everyone know, that it's no risk to use this app.

**Comment by svengabr** [comment]
Hi @sbernhard ,

Thank you for your proposal. All issues in the cwa-wishlist repository will be discussed with our contracting entities. They will decide whether they will be implemented or pursued further. As soon as we have any updates, we will let you know about the details.

Best regards,
SG

Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@svengabr There is already an Issue (also from @sbernhard) #212, so maybe this could be closed?

**Comment by sbernhard** [comment]
Sure, close this one.
