### ISSUE TITLE
Add text to Settings to guide user to Transnational Exposure Logging details

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-wishlist#216]
## Current Implementation

In CWA Android ~~1.5.0.~~ 2.2.1
It is not obvious how to access the list of countries participating in Transnational Exposure Logging when the Settings menu is opened. Text in the Settings menu does not mention this aspect.

---

### Settings menu
![CWA Settings](https://user-images.githubusercontent.com/66998419/96458369-2346df00-1221-11eb-86df-2f02e0f7865a.jpg)

---

### Exposure logging
![Exposure logging](https://user-images.githubusercontent.com/66998419/96458390-2a6ded00-1221-11eb-8be2-8426d33a436d.jpg)

---

### List of countries
![Countries](https://user-images.githubusercontent.com/66998419/96458400-2e017400-1221-11eb-87ed-5992d81a23df.jpg)

---

## Suggested Enhancement
In the Settings menu, section Exposure Logging, add text after "Allow creation and sharing of COVID-19 random IDs." to indicate that selecting the Exposure Logging item will show a sub-item "Transnational Exposure Logging / Participating Countries". For instance add the text: "Show details and participating countries for Transnational Exposure Logging."

## Expected Benefits
Increases user satisfaction concerning finding information about the EU and Swiss federated sharing of exposure information. Without this enhancement users may have trouble finding it.

---
Internal Tracking ID: EXPOSUREAPP-3409

**Comment by heinezen** [comment]
Good catch @MikeMcC399 as always!

I've created a Jira ticket for this. The devs will pick it up now and decide how to handle it.

Thanks for the feedback
CH

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
I'm going to withdraw this enhancement request. Most major EU countries and all neighboring countries to Germany, except France, are participating in transnational exposure logging. The list of countries is also quite stable now.

The need to find out which countries have only just joined has therefore been reduced and in general I believe there is less interest in the exact list of countries. 

A user who taps of "EXPOSURE LOGGING ACTIVE" on the Start Screen in CWA Android, then on "Transnational Exposure Logging / Participating Countries" will be shown the list of countries. I now think that is easy enough for an interested user.

**Comment by dsarkar** [comment]
@MikeMcC399 forwarded internally.
