### ISSUE TITLE
Make onboarding scrollable text obvious

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-wishlist#217]
## Current Implementation
During the onboarding sequence large amounts of scrollable text are offered to the user in the CWA Android app,  however, depending on the display dimensions it may not be obvious to the user that text is hidden and needs to be scrolled to be viewed.

### First onboarding screen
Here is an example from the first screen from onboarding on a Samsung Galaxy A5 (2017). Viewing this screen, there is no indication that there is hidden scrollable text under the paragraph "More protection for you and for us all. By using the Corona-Warn-App we can break infection chains much quicker."

![Screenshot_20201020-094010_Corona-Warn](https://user-images.githubusercontent.com/66998419/96556539-618fdd00-12b9-11eb-81f9-2f55a4ff0def.jpg)

---
### Scrolled first onboarding screen
![Screenshot_20201020-094328_Corona-Warn](https://user-images.githubusercontent.com/66998419/96556646-8ab06d80-12b9-11eb-9533-8a8fcd05c7cb.jpg)

## Suggested Enhancement

1. Show to the user in some way that there is hidden scrollable text available.
2. Alternatively, in a more radical re-design: dispense with displaying large amounts of text as part of the onboarding process and make this information available elsewhere as reference information. Other country's apps (Ireland, Italy, etc.) don't attempt to show so much text during the onboarding sequence, and keep their display information short and fitted to the screen.

## Expected Benefits
Make sure that the user knows that there is information available therefore ensuring all necessary instructions and background information are passed to the user and not lost.

Edit: I checked on the same device, with CWA 1.12.0 and now the second paragraph in English is cut off, so it is more clear that there is missing text because the sentence does not finish. That should tempt the user to scroll down to read the rest of the sentence. HOWEVER, in German the second paragraph is completely displayed, so again it is not obvious that there is missing text, requiring scrolling to read.

---
Internal Tracking ID: EXPOSUREAPP-3329

**Comment by heinezen** [comment]
Hey @MikeMcC399 

Thanks for the hint. I've mirrored the request to Jira with ticket ID EXPOSUREAPP-3329. It will now be discussed by the development team and the RKI.

Regards,
CH

----
Corona-Warn-App Open Source Team
