### ISSUE TITLE
Display total infections & shared diagnostic keys on first page

### ISSUE THREAD

**Issue by MichaelAnders** [corona-warn-app/cwa-wishlist#218]
## Feature description
On the initial screen of the app, show publically available information:
- Total infections (in Germany) in last 24 hours (source: RKI)
- maybe: Total infections in state last 24 hours (current "Bundesland" based on GPS)
- Total shared diagnostic keys in last 24 hours (source: https://micb25.github.io/dka/) & that it's anonymous / not known who the people are
- Show percentage of shared keys vs total infections (also as text, e.g. "10.4% (10 out of 100)", as actually not everyone can interpret percentages correctly)

## Problem and motivation
Active users of the app:
- have no feedback about the effect of using it ("is it worth using?!")
- are required to use 3rd party websites to get information about the daily statistics (usually only the news papers which only publish statistics by the RKI, the micb25 statistics are basically unknown)
- cannot help in motivating others to use the app ("why should I, I don't see any and have not read about any impact, not even from the RKI?")
- can help responding to "I just see the numbers are increasing even though 19 million are using it, so it's a waste!"

## Expected Benefits
Especially the total shared diagnostic keys is imo important and critical:

- Users see an effect (shared keys) even if they never see any notification --> answers the question "is the app actually working and does it have an impact?"
- Users can show the effect of the app (shared keys) with others --> answers the question "is it worth it?" --> can increase acceptance and usage by others
- Psychologically, app users seeing other positive tested people are uploading their diagnosis may increase the likelihood that they will do the same ("be part of it") --> increased amount of notifications of users --> may increase testing/being more careful --> may lower infection increase

## Is this something you're interested in working on
No as this is something that SAP/RKI have to decide & work on

**Comment by Ein-Tim** [comment]
Similar to #151. Could you, @MichaelAnders, maybe comment there and close this Issue, so we can focus the Discussion on one ticket.
Thanks!

**Comment by daimpi** [comment]
Related (but more focused on showing such stats on the website):
- https://github.com/corona-warn-app/cwa-website/issues/391
- https://github.com/corona-warn-app/cwa-wishlist/issues/125

**Comment by dsarkar** [comment]
FYI - PR https://github.com/corona-warn-app/cwa-app-android/pull/2043

**Comment by Ein-Tim** [comment]
And iOS: https://github.com/corona-warn-app/cwa-app-ios/pull/1807.
Planned for version 1.12.

**Comment by Ein-Tim** [comment]
Some statistics are now (with the release of version 1.11) available in the App:

https://www.coronawarn.app/en/blog/2021-01-28-corona-warn-app-version-1-11

**Comment by heinezen** [comment]
The CWA now has a statistics overview in the main app view. It uses a 7 day peroid instead of the 24 hour period suggested here, but the functionality is the same. We will therefore close this issue as solved.

If there are any new feature requests regarding the statistics overview, please open a new issue.

----
Corona-Warn-App Open Source Team
