### ISSUE TITLE
Add information about corona risk areas

### ISSUE THREAD

**Issue by scrobbleme** [corona-warn-app/cwa-wishlist#220]
Currently, it is quite hard to find out, where corona risk areas are, what measures are taken ...

As the official app, there also should be information about corona risk areas integretad:

- Overview of current/potential corona risk areas
- Information about personal exposure (is my area a corona risk area? can I travel to XY?)
- Helpful links to official measures in the corona risk area I'm in

**Comment by tobiashage** [comment]
There actually is an application (darfichdas.info) that promises to do what you're requesting - I haven't been able to test it though as there's currently only the Android version available, but the concept looks promising. I just see the problem that none of the information provided there isn't "official" as the developer is a private company. Having something similar (especially in such a comprehensive and clear way) in Corona Warn App would be amazing imo.

**Comment by scrobbleme** [comment]
Thanks, looks good at first.

Yeah, "official" is the problem... should be part of the app.

**Comment by Ein-Tim** [comment]
Also very similar to #151. Could you, @scrobbleme, maybe comment there and close this Issue, so we can focus the Discussion on one ticket? 
Thanks!

**Comment by scrobbleme** [comment]
Duplicate ;)
