### ISSUE TITLE
Implement warnings for indirect contacts of positive tested persons

### ISSUE THREAD

**Issue by bullipirat** [corona-warn-app/cwa-wishlist#221]
## Feature description

The app should issue a "yellow" warning message to people that had a direct close contact to a person who him/herself had a close contact to a positive tested person, maybe: "You have been in close contact to a possibly infected person. We would recommend a test." 
## Problem and motivation

Currently, test results take more than 36 hours. If person A is infected and gets into close contact with person B, now B with some probability might be infected too. Later, B comes into close contact with C, and C might get infected. This will mostly occur at the same time A gets a positive test result, if tested at all. But by now, only B will receive a warning from the app, if A shares the result, C will not be warned. However, it might be very useful for C to know about the possible risk and take precautions to avoid further spreading. This feature could even be enhanced for bars and restaurants, which could act as person B in the example before, so that C, who has visited the restaurant (B) at the same time as A, gets a warning if - and as soon as -  A has a positive result. 
## Is this something you're interested in working on

No

**Comment by daimpi** [comment]
@bullipirat There is already an issue for this: https://github.com/corona-warn-app/cwa-wishlist/issues/24

I would suggest closing this one and continuing the discussion over there 🙂.

**Comment by bullipirat** [comment]
Ok, thanks for the hint, daimpi.
