### ISSUE TITLE
3-dots button should be in the corner of the screen 

### ISSUE THREAD

**Issue by orangebutblue** [corona-warn-app/cwa-wishlist#228]
## Current Implementation
This is obviously one of the most pressing issues with the app right now: the 3-dots menu button isn't in the corner of the screen - there is a slight narrow gap in between the button and the corner of the screen 

![Screenshot_20201010-100422_Corona-Warn~2](https://user-images.githubusercontent.com/4688096/95649872-33074a80-0ae0-11eb-81f1-0b7e95fbbc2a.png)

## Suggested Enhancement
put the menu button in the corner - as it is with literally every other Android app 

this is a screenshot of the Gmail app:
![Screenshot_20201010-095743_Gmail~2](https://user-images.githubusercontent.com/4688096/95649895-5af6ae00-0ae0-11eb-9258-01871341fa87.png)

## Expected Benefits
people being able to open the menu without having sniper-like accuracy

---
Internal Tracking ID: EXPOSUREAPP-3173

**Comment by Ein-Tim** [comment]
This should be moved (back) to the Android repo as there are no 3-dot buttons under iOS.

**Comment by d4rken** [comment]
This is fixed already by one of the last updates where we moved from a custom layout to the MD toolbar widget.

**Comment by dsarkar** [comment]
@orangebutblue see comment https://github.com/corona-warn-app/cwa-wishlist/issues/228#issuecomment-884861249.

Thanks for contributing.

---
Corona-Warn-App Open Source Team
