### ISSUE TITLE
QR-Code als Adresszettel-Ersatz

### ISSUE THREAD

**Issue by MarkoPeperkorn** [corona-warn-app/cwa-wishlist#238]
Die Corona-Warn-App ist in meinen Augen ein wichtiger Teil in der Coronazeit.. 
Wäre es nicht möglich in die App einen QR Code zu installieren, mit dem man sich in Restaurants, Kinos und weiteren Teilen des öffentlichen Lebens beim betreten und verlassen an- und abmelden kann und somit den Adresszettel ersetze? 
Dadurch sollte doch ein schnellerer Datenvergleich machbar sein, Fake-Daten werden verhindert und Mitmenschen die sich scheuen ihre Daten auf einen zT ellenlangen Zettel zu schreiben, werden beruhigt. 
Klar, Datenschutz ist wichtig aber meine Gesundheit und die meines Kreises ist mir wichtiger! Da scanne ich mich doch lieber mit einem Code wo ein, als meine Daten auf einem Zettel zu notieren.

**Comment by Ein-Tim** [comment]
Hey @MarkoPeperkorn 

Please see #151 and close this Issue so we can focus the discussion on one Issue. Thanks.

**Comment by heinezen** [comment]
Hey @MarkoPeperkorn 

As @Ein-Tim pointed out, your request is already discussed in https://github.com/corona-warn-app/cwa-wishlist/issues/138 . Please continue the discussion there and give the thread a thumbs up, so we can see how popular the feature is. Any updates and news regarding the implementation of said feature will also be posted in the linked thread. I'll close your issue as a duplicate.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
Duplicate of #138

**Comment by MarkoPeperkorn** [comment]
Na, mein Ansatz als normaler Bürger und User der App mit einem QR-Code ist
zwar ein etwas anderer als der in den genannten Post, aber wenn das nicht
interessant ist, dann halt nicht.
Dann macht mal euer Ding!



Am Dienstag, 27. Oktober 2020 schrieb Christoph Heine <
notifications@github.com>:

**Comment by Ein-Tim** [comment]
@MarkoPeperkorn 
Tut mir leid das du enttäuscht bist, aber bitte guck dir mal noch diesen Issue an: https://github.com/corona-warn-app/cwa-wishlist/issues/70
Dieser ist praktisch dein Vorschlag, oder? #70 bleibt geöffnet und deiner hier wird nur geschlossen damit wir die Diskussion auf einen Thread konzentrieren können.

**Comment by heinezen** [comment]
Hey @MarkoPeperkorn 

Sorry, it was not my intention to make you feel like your feedback is ignored here. When we close issues as duplicates it is not because they are not interesting to us, but rather to centralize the discussion about a feature in one place. That way, we and the community can track ongoing discussions much better. You feedback is also not lost when we close your issue. By marking it as a duplicate, it is linked in the discussion timeline in the other thread and can be accessed from there.

Regards,
CH

----
Corona-Warn-App Open Source Team
