### ISSUE TITLE
Gamification to enhance community thrive and acceptance 

### ISSUE THREAD

**Issue by DanAmt** [corona-warn-app/cwa-wishlist#248]
## Feature description
I would like to see the app display general anonymous statistics that prove how we are all contributing to the drive to battle virus:
- Total number of active apps (downloading on a given day)
- Total number of results transmitted
- Numeber of negative/postive results
- last not least , number of positive results transmitted and number of people warned (if poss) 

## Problem and motivation
The App is too silent. I immedeately shared on twitter when I had my first low risk.
Implementing features as above  would create a community. people would discuss in social media and contribute to perception and acceptance of the otherwise a bit  silent app. 

## Is this something you're interested in working on

Yes

---
Internal Tracking ID: EXPOSUREAPP-4679

**Comment by Ein-Tim** [comment]
SAP/Telekom are already working on this. See @svengabr's comment here: https://github.com/corona-warn-app/cwa-wishlist/issues/236#issuecomment-716587086

---

I still think this Issue can be left open, maybe @svengabr could clarify here what exactly feautres will come to the App. Thanks!

**Comment by Blackjacx** [comment]
Cool feature. I think the same as @DanAmt regarding the app going more "viral".

**Comment by Ein-Tim** [comment]
Seems like we will see statistics in the App starting at version 1.12: https://github.com/corona-warn-app/cwa-app-android/pull/2043

**Comment by Ein-Tim** [comment]
Statistics are now (with the release of version 1.11) available in the App:

https://www.coronawarn.app/en/blog/2021-01-28-corona-warn-app-version-1-11

**Comment by ndegendogo** [comment]
> as well as the number of users tested positive who have warned their fellow citizens via the app

Well, this one will indeed be a **very** interesting KPI

*Should have been published from the beginning - but better late than never*

**Comment by ndegendogo** [comment]
> as well as the number of users tested positive who have warned their fellow citizens via the app

... and not only a KPI. It makes us cwa users feel more like a community.

**Comment by DanAmt** [comment]
Great job.

**Comment by di-sc** [comment]
I absolutely agree. A successful application has to be responsive to the user. The CWA is already successful but I think it can make  much more to make a difference in fighting the pandamic.
I think it is worth to check, if the ENF could be extended to provide anonymous statistical data of a persons contacts with respect to the rules of the ENF.
This issue seems to be related to this one: [#280 Yellow Notification](https://github.com/corona-warn-app/cwa-wishlist/issues/280#issuecomment-817262141)

**Comment by dsarkar** [comment]
see https://www.coronawarn.app/de/science/

**Comment by larswmh** [comment]
Closing this issue as the related internal ticket is set to `complete`.

Developer comment:

> Statistics are added with 1.11 Which contains the number of people who warned others. Other KPIs are currently not requested by the customer
