### ISSUE TITLE
multiple device support

### ISSUE THREAD

**Issue by Xyz00777** [corona-warn-app/cwa-wishlist#249]
## Current Implementation
actually i cant use the app on multiple devices

## Suggested Enhancement
there should be a option that you could use the app on multiple devices

## Expected Benefits
when you change the phone you should be able to import the old IDs from the old phone to the new, so you get information if you had contact with a other person when you dont have access to your old phone anymore

**Comment by Xyz00777** [comment]
Because:
my normal phone had a technical problem and now i have to send it to the manufacture -> i dont know if i had contact with a person in the last 2 weaks who got ill
and when i switch back to my other handy i don't know if i had any contact with infected people on my other handy

**Comment by Ein-Tim** [comment]
@Xyz00777 
I think you are requesting this: #8, or? If so please close this Issue.
Thanks!

**Comment by Xyz00777** [comment]
i dind found something with search multiple device or so. thanks
