### ISSUE TITLE
Improve test CTA to make the app more effective

### ISSUE THREAD

**Issue by j9t** [corona-warn-app/cwa-wishlist#260]
At the moment, it’s not clear how to report an infection (heuristic evaluation). At the same time, the app doesn’t seem to be used as often as it could or should be to report an infection (picked up in news, no source at hand). From a usability/UX standpoint, there seems to be a relationship.

## Current Implementation

In order to report an infection in the app, there seems to be only one way: Click “Learn more and help” or “Informieren & mitmachen” on the app’s main screen.

<img src=https://user-images.githubusercontent.com/1700772/98468800-62db6800-21dc-11eb-8380-d721d5ecff1e.png alt="" width=250>

There are three interconnected issues with this:

* The button text is easily dismissed as being for informational purposes only, or to go to some sort of help center.
* The button text does not use any word a user might be primed for when looking for a way to report a case.
* The button text does not carry enough [information scent](https://www.nngroup.com/articles/information-scent/).

Heuristically, the main and *only* way to report an infection is therefore very likely *not usable* (from a usability point of view)—it’s likely easily overlooked.

## Suggested Enhancement

I’d suggest three improvements:

1. For an immediate fix, relabel the button: “Report an infection” (or something else that is *clear*).—If need be and there’s other functionality hidden behind the button, make a _separate_ section for that not to dilute the messaging. “Report an infection or read up on Covid-19” is likely to be similarly ineffective.

2. For a complementary improvement, add something in the menu (“three dots”) that also leads to where a user could report an infection. (This could also be a useful first improvement, just to cover one section of the app a user is likely to look at.)

3. *Test* the app with actual users. This may have been done, or may be in doing, but just in case, please test the app with users. This is a heuristic issue report here but the best way to be sure an app works is to test it.

## Expected Benefits

1. Less confusion and fewer searches and messages around where and how to report an infection (it seems to be there, just surprisingly hard to discover).

2. More reports and therefore a more effective app.

Thank you for considering this feedback.

---
Internal Tracking ID: EXPOSUREAPP-3645

**Comment by heinezen** [comment]
Hello @j9t ,

Thank you for the detailed suggestion. We have created an internal Jira ticket (EXPOSUREAPP-3645) for your request hich will now be discussed by the RKI and the developers. We will update everyone here oon Github on the status of the request if we got any news.

Best Regards,
CH

----
 Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
This will be improved in v1.9.0, see here: https://github.com/corona-warn-app/cwa-app-ios/pull/1559

**Comment by j9t** [comment]
Thanks for sharing, @Ein-Tim!

Has this change been tested with users? It may otherwise face a similar usability risk in that users would scan the buttons and may not immediately get it, either—“Nächste Schritte” is not clear without context (and unnecessarily unclear if you consider alternatives), and you may not want to peg the success of this element on users also reading the headline.

**Comment by larswmh** [comment]
Closing this issue as the related internal ticket is set to `completed`.
