### ISSUE TITLE
After negative antigen rapid test: Show status: "Cannot spread virus" for some hours

### ISSUE THREAD

**Issue by Wallgauer** [corona-warn-app/cwa-wishlist#263]
## Feature description

In addition to the PCR tests there are antigen rapid tests available. They cannot for sure say that you are not infected, but are quite effective to tell you that you cannot spread the virus for the next hours.

It would be great to reflect this in the corona-warn-app. So that the status shows: "Tested, cannot spread the virus for ... hours"

So it could be made very easy to e.g. visit a residential home for the elderly. 
You can do the rapid test somewhere. 15 min later (when the test result is there) you get the status message on your phone and can show this at the entrance of e.g. the residential home. 
There should be a countdown from the test-time to the moment when you cannot say for sure anymore that you cannot spread the virus. So if this time is e.g. 7 hours, then a 7 hours countdown from the testing. 

---
Internal Tracking ID: EXPOSUREAPP-3672

**Comment by Ein-Tim** [comment]
@Wallgauer 
Please see #239

**Comment by jucktnich** [comment]
I don't think it's a duplicate, because in the other issue it's about changing from red to green, when there's a negative test result and in this issue about showing others, that you can't spread the virus in the next few hours.

**Comment by Ein-Tim** [comment]
Okay I understand.
So you mean to stop sending Bluetooth Beacons but still reviving them. 

Or what do you mean with:
> showing others, that you can't spread the virus in the next few hours.

**Comment by Wallgauer** [comment]
Hi, yes, this is totally different topic.

The quick tests (antigen-tests) are different to the traditional tests. They don't show if you have or have not the virus. But they say that you don't have enough virus in your nose/mouth so that you won't infect someone else in the next few hours. 

The test result is very fast (takes about 15 min from test to result) and cheaper. But for sure after a day or so it can be that you develop the illness so that you can e.g. spread the virus on the day after the next.

**Comment by Ein-Tim** [comment]
@Wallgauer 
I understand, but what should the App do with this Information? 
Stop sending Bluetooth Beacons to others because you can't spread the virus?

**Comment by Wallgauer** [comment]
No, for sure the app should work as normal.
But it should show it on the start screen with a counter.
So that you just can show your mobile at the entrance to e.g. the residence of elderly people and get access. 
So you have your "proof point" ready at hand.

**Comment by Wallgauer** [comment]
And for sure, if you are positive tested, then for sure you have Corona and this can count like a normal PCR test.

**Comment by MikeMcC399** [comment]
@Wallgauer 
> So that you just can show your mobile at the entrance to e.g. the residence of elderly people and get access.

I think you will meet resistance for this suggestion, because it goes against the principle that the use of the app is completely voluntary. Any use where it would be mandatory (to gain admission to somewhere) becomes difficult.

**Comment by Wallgauer** [comment]
I don't think so. It is only additional and making it easier. E.g. you might get a "test confirmation letter" or something like this at the testing station. Or you even can again do an new quick-test at the entrance of the residence you want to enter. 
Most important is the "reuse" of one test if you first enter e.g. first a hospital (do the antigen test there) and then a residence. Instead of being tested within the "OK" period twice you can just show your proof point. And additionally you have some sort of self-control with the counter until when you are for sure "safe for others".

**Comment by heinezen** [comment]
Hello everyone,

Thank you for the suggestion and the oongoing discussion. I have created a Jira ticket for this request (ticket ID: EXPOSUREAPP-3672), so that it will now be discussed internally by the developers and the RKI. They will decide if and how the feature is implemented. We will inform you here on Github if we get any news regarding the issue that we can communicate.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by carstenmueller** [comment]
+1 Having the test result in the app also for an antigen-test would be nice, also to avoid that you have to do tests twice. By this is would be possible to show the negative test also to others to proof your current status. This could be useful for different things. It can also show you when you should do the next antigen- or PCR-test. And it can also be used for the calculation of the current risk status.

Also having the positive antigen-result in the app could also help in the same way as a positive PCR-test result works.

**Comment by kevin-kraus** [comment]
In itself a good idea, but here I see the problem of verification / authenticity of the test result. Who gives the assurance that I have entered my test result correctly and not, just to gain access, stated to be negative? Here, a confidential verification is clearly missing compared to PCR tests, which are verified and transmitted by a trustworthy laboratory.

**Comment by Wallgauer** [comment]
You are right, it would not work if you buy such a test-kit and do the test at home. But if you do the test in a hospital or some residence for elderly etc. there are trustworthy persons that could verify the test result similar to the way it is done for laboratories today.

**Comment by carstenmueller** [comment]
As far as I got it there is currentl yonly the permission to do the antigen test by authorized medical persons, there is no permission to do the test by yourself at home yet. If medical personal can enter the test result, like now the laboratory does, it is nearly the same process.

**Comment by kevin-kraus** [comment]
Okay, if the test and the transmission of the result is done by authorized medical personnel it would be possible. But giving the end-user the ability to enter unverified test results must not be in consideration. That's the whole point what I wanted to say.

**Comment by ndegendogo** [comment]
> If medical personal can enter the test result, like now the laboratory does, it is nearly the same process.

Except that it is not sufficient to authorize a trustworthy **person**. The labs transmit their test results via **software** to cwa server, and this infrastructure is still in ramp-up. Many, but still not all labs are currently connected. So also this testing facilities will need this infrastructure ramp-up.
I don't say this is impossible or a bad idea; I just want to point out that this feature will need more than just an extension of the app.

**Comment by jucktnich** [comment]
Are there any updates there? Since rapid test now should play a role in every-days live, I would appreciate, that the team considers to implement it.

**Comment by MasterEmit** [comment]
Starting on Wednesday (tomorrow) customers should present a "certificate" to show that they got a negative test result from a test not older than 24 hours. No one until now could answer my question, how I can verify that certificate. In my eyes this could be really easy with a simple signature of some data backed with these data together in a QRCode. I could use the CWA to scann the QRCode, the public keys for creating these signatures could be stored centralized and the verification of the certificate can be done locally inside the CWA. 
Now  I have to "trust" or scan a QRCode with my mobile browser - very safe! :-(

**Comment by Ein-Tim** [comment]
@MasterEmit 

It seems like SAP is working on an integration for quick tests, see: https://github.com/corona-warn-app/cwa-quick-test-frontend & https://github.com/corona-warn-app/cwa-quick-test-backend.

**Comment by MikeMcC399** [comment]
Also there is a European solution proposed, but that is not supposed to be ready until the summer. See https://github.com/corona-warn-app/cwa-wishlist/issues/424 and [Digital Green Certificate](https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/safe-covid-19-vaccines-europeans/covid-19-digital-green-certificates_en).

**Comment by MasterEmit** [comment]
Ah great! Did not saw this yesterday. Brand new :-). Good news!

**Comment by jucktnich** [comment]
@MikeMcC399 is it possible to integrate the green pass in the CWA? (I'm not sure if it was discussed elsewhere before, Giu I couldn't find it.)

**Comment by Ein-Tim** [comment]
@jucktnich 

#424 is the issue reg. this. @MikeMcC399 mentioned it above.

**Comment by jucktnich** [comment]
Oh thanks sorry, don't know how I could have overlooked it 🤦‍♂️

**Comment by kevin-kraus** [comment]
Probably this could be closed now as rapid tests / antigen tests are supported since release of version 2.1. 

[Blog article (DE)](https://www.coronawarn.app/de/blog/2021-05-02-corona-warn-app-version-2-1/)

[Blog article (EN)](https://www.coronawarn.app/en/blog/2021-05-02-corona-warn-app-version-2-1/)

**Comment by Ein-Tim** [comment]
And, in addition, the app shows the date when the swap was taken so that one can show it on an entrance, etc.

See: 

<img src="https://user-images.githubusercontent.com/10122052/116780654-57c40f00-aa7e-11eb-9c12-add15bfba7bd.png" width="300">

**Comment by ndegendogo** [comment]
@Ein-Tim uh - a typo on your screen 😱
*her => here*
Is this a screenshot from your current cwa, or an early screenshot during development? 🤪

**Comment by Ein-Tim** [comment]
@ndegendogo 

This is currently live and will be fixed in version 2.2.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> This is currently live and will be fixed in version 2.2.

I don't think that is correct, although I don't personally have a negative test result that I can check it with.

The typo was handled through issue https://github.com/corona-warn-app/cwa-documentation/issues/597 and the fix is live in 2.1. There seems to be an issue though with some missing iOS screenshots on https://www.coronawarn.app/en/screenshots/ though. I will follow up this point separately.

**Comment by dsarkar** [comment]
Hi @Wallgauer @ndegendogo @Ein-Tim @jucktnich @kevin-kraus @MasterEmit @carstenmueller, an dear cimmunit,

Thank you all for contributing here. As stated out above by the community this can be considered implemented technically and practical usage of this feature now depends on local regulations. 

@Wallgauer We suggest closing this issue. 

Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by Wallgauer** [comment]
Thanks a lot for implementing this!
I close this issue.
Greetings

**Comment by MikeMcC399** [comment]
I reported the problem with the missing screenshots in https://github.com/corona-warn-app/cwa-website/issues/1217 and this is already fixed.

The official screenshot for iOS is now on https://www.coronawarn.app/assets/img/screenshots/en/ios/rat_7.png and it does not include the text which had the typo in it. I guess you would need to scroll down to see the text.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thanks, i messed this up because they've fixed this in one of the hotfix releases (see also code: https://github.com/corona-warn-app/cwa-app-ios/blob/f376a728b51eeb77544dac1bb0860f92ccfdf713/src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings#L685)

Back [here](https://github.com/corona-warn-app/cwa-app-ios/pull/2595#issuecomment-830143896) it was planned to be fixed in version 2.2.

Sorry for the confusion everyone!

**Comment by MikeMcC399** [comment]
@Ein-Tim 
No problem! We help each other here!
