### ISSUE TITLE
Add short name of day to risk report notification

### ISSUE THREAD

**Issue by lordgurke** [corona-warn-app/cwa-wishlist#265]
## Current Implementation
If you get a notification about high risk encounters, the number of days since last encounter is shown - i.e. "8 days since last encounter". This is somewhat confusing, if the last update happened yesterday.

## Suggested Enhancement
Could we add the short form of the day of week "8 days since last encounter" refers to?
So, that it's shown as "Wed, 8 days ago since last encounter"?

## Expected Benefits
This would help destroy confusion about what day is meant.
If you were around with people on one specific day day that don't have a smartphone (i.e. kids), you could more or less safely determine, if they were at the same risk as you or not.

**Comment by Ein-Tim** [comment]
See also #188

**Comment by dsarkar** [comment]
Hi @lordgurke, 
Thanks for contributing, see also https://github.com/corona-warn-app/cwa-documentation/issues/433. 

Best wishes,
DS

Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Hey @lordgurke 
With 1.8.0 the exact date of High-Risk Encounters will be shown, not the name of the day but I think this would solve this request, or? (see: corona-warn-app/cwa-app-ios#1550)

**Comment by lordgurke** [comment]
Perfect - Thanks!
