### ISSUE TITLE
Include App Data in iOS/ICloud Backups

### ISSUE THREAD

**Issue by jhueppauff** [corona-warn-app/cwa-wishlist#268]
## Suggested Enhancement
I just restored my iPhone Data to a new one. Thanks to iCloud a lot of app data is copied over. 
The Corona-Warn App unfortunately starts with a fresh set of data. 

Would be amazing to have the app data included in the iCloud backups.

## Expected Benefits
Whenever you need to change your mobile phone you would not start from 0 days. Meaning the app will still know what contacts you had.

**Comment by achisto** [comment]
I believe with #8 there is already a long and ongoing discussion about a similar topic.

**Comment by jhueppauff** [comment]
Sorry, haven't noticed
