### ISSUE TITLE
Show information about received key in the app

### ISSUE THREAD

**Issue by Clauswgh** [corona-warn-app/cwa-wishlist#27]
## Feature description
Show a counter or any else in the app about received keys

## Problem and motivation
The user can only see all is OK by the green display, but the user can't see all it is OK and I have receive any key from other people. Because if I receive no other key - because of a problem - it is seems all is OK too .-(

**So it could be useful to show something like:**
1. X key receives in the last Y hours
2. last key receive W minutes ago

## Is this something you're interested in working on
yes, but no coding - because coding is not my greatest talent :-)

**Comment by Andy58BS** [comment]
I consider this function extension to be urgently necessary to make the work of the APP transparent to the user!

**Comment by BugBuster1701** [comment]
similar to [corona-warn-app/cwa-wishlist/issues/5](https://github.com/corona-warn-app/cwa-wishlist/issues/5)

**Comment by Clauswgh** [comment]
@BugBuster1701 you are right!
Should we link my issue to #5 or should we close my issue my ticket directly?

**Comment by tkowark** [comment]
It is automatically linked in #5 after the first mention, so we can close it here. But nevertheless, thanks for your submission!
