### ISSUE TITLE
Using QR codes for infection cluster detection

### ISSUE THREAD

**Issue by jniediek** [corona-warn-app/cwa-wishlist#272]
## Feature description

As repeatedly discussed by Prof. Drosten and others, it's crucial to identify infection clusters. Here is an idea towards this goal.

1. Create a website to print specific QR codes. These printed codes are used to identify rooms or closed spaces in general, such as class rooms in schools, offices, workplaces, restaurants, maybe even train compartments. Anybody can print a code and display it inside the room. Each QR code contains two pieces of information: a **unique ID** (generated by the backend behind the website) and some **nickname for the room** (not necessarily unique, such as "McDonald's at Berlin Hbf" or "Commerzbank München Office 210"; provided by the user who prints the QR code). For privacy concerns see below.

2. Use CWA to scan the QR code when you enter a room. The unique ID is stored **only locally on the device**, and the nickname of the room is stored **only locally on the device** in the form of some "my closed rooms diary" together with a time stamp, visible to the user of CWA. 

3. If a user is tested positive, three things happen:

- The user can send his/her list of room nicknames to the health authorities/Gesundheitsamt. This will improve the contact tracing interviews a lot: they will be **more precise, more complete, and faster**, because the list of visited rooms will help the patient to recall what happened during the last 14 days. For privacy, of course the user will be able to delete items from the list before sending, and of course sending the list will be voluntary at any time. This is the main benefit of the suggested feature. Additionally:

 - The scanned room IDs + timestamps will be used in the same way that CWA is working right now: The patient can (voluntarily) upload the list of scanned unique room IDs, CWA can download the list, and CWA can then display a warning to anybody who scanned the same ID at around the same time: "a covid patient was in the same room with you". This could be more precise than the current BLE for example in restaurants or offices with bad ventilation, where people can sit 20 m apart and still catch the virus through aerosols.

- The server side of CWA can compute statistics on room IDs scanned by people tested positive to find infection clusters. These highly relevant room IDs can be downloaded by CWA, which can then display a warning such as "you were in a room where several people got infected. Please inform the health authorities". This could help the health authorities to prioritize some investigations above others. For example, they could call contacts of somebody who was found to be in a cluster situation earlier  than contacts of somebody who was not found to be in such a situation.

## Problem and motivation

Current problem: contact tracing interviews are slow, and results are imprecise and incomplete. Imagine people had the option to quickly scan a QR code every time they go into a closed room. This would greatly improve the outcome of contact tracing interviews. Furthermore, it would have positive side effects as described above. 

## Is this something you're interested in working on

Yes

**Comment by Ein-Tim** [comment]
@jniediek 
Thanks for your proposal! 
Something very similar was already proposed here: #70, so maybe you could consider to close this Issue and comment your (very detailed) proposal there? 
Thanks!

**Comment by jniediek** [comment]
became part of #70
