### ISSUE TITLE
UX Terms of use why are chapters not linked?

### ISSUE THREAD

**Issue by mrascher-cosee** [corona-warn-app/cwa-wishlist#273]
## Where to find the issue
Terms of use (Android App)

## Describe the issue
The terms of use have a lot of text. So if a user wants to read a special chapter he needs to scroll all the way down.

## Suggested change
The easiest way was that you link all chapters. The content will scroll down automatically. Maybe you can also implement an "back to top" button, so that the user must not scroll all the way up.

---
Internal Tracking ID: EXPOSUREAPP-2889

**Comment by Ein-Tim** [comment]
Can we close this issue if it won't get implemented @mrascher-cosee?

**Comment by Ein-Tim** [comment]
@heinezen Could you close this issue? 🙂

**Comment by heinezen** [comment]
Hello everyone,

Ths feature request has been **declined** and will not be pursued further.

----
Corona-Warn-App Open Source Team
