### ISSUE TITLE
Forced update by deinstall/reinstall deleted all my contact history

### ISSUE THREAD

**Issue by andreasRu** [corona-warn-app/cwa-wishlist#278]
I've heard from the press there is a new version 1.7. available. Because I couldn't update, I removed the app 1.6.0 from my Android 7.0 and reinstalled it. To my surprise, I got the 1.6.1 Version, but now all my history is lost. If the app would have warned me, I wouldn't did the deinstallation/reinstallation. Now my history is gone, and also my registred contacts of other peoples devices are now deprecated.

**Comment by Ein-Tim** [comment]
@dsarkar 
Could you move this to the Android Repo?

**Comment by MikeMcC399** [comment]
Hi @andreasRu 

I'm sorry about your bad experience losing data! I agree there should at least be some warning if data is going to be lost. Several months ago I opened a request in https://github.com/corona-warn-app/cwa-wishlist/issues/164 "Google Exposure Notification System should optionally preserve exposure data on app uninstall" which is related to your problem. If Google gave the user the choice to keep or delete the data, that would also be a warning.

The database and keys are deleted when the last COVID-19 app is uninstalled, and this deletion is done by Google not by the Corona-Warn-App (CWA). There is an [FAQ article about deleting random IDs](https://www.coronawarn.app/en/faq/#delete_random_ids) and it's a problem only on Google Android, not on Apple iOS.

If you absolutely need to uninstall the app and want to preserve the keys, you can temporarily install one of the other Google Exposure Notification System (ENS) compatible apps from another country, for instance from the list [Mobile contact tracing apps in EU Member States](https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/travel-during-coronavirus-pandemic/mobile-contact-tracing-apps-eu-member-states_en), whilst you uninstall CWA. So long there is at least one ENS compatible app installed on the device, Google will not delete the key data. It does however delete the history of exposure checks for any app which you uninstall. So if you go to Settings > Google > COVID-19 exposure notifications > Exposure checks you only see the history for the COVID-19 apps which are currently installed.

To get version 1.7.0 of the app, you may need to be a little patient. We are told that it is a staged rollout over the next 2 days. I haven't got it yet either.

**Comment by dsarkar** [comment]
Hi @andreasRu,  you are basically suggesting to implement a warning before de-installing or re-installing the application or alternatively that the  RPIs keys (contact) are kept by the operating system.


If so, we would suggest to close this issue and continue to contribute to these related issues:
- "Exposure data will be deleted notification": https://github.com/corona-warn-app/cwa-wishlist/issues/285
- Preserve exposure data by OS: https://github.com/corona-warn-app/cwa-wishlist/issues/164

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by andreasRu** [comment]
Should have closed this issue much earlier. My bad. By the way, thank you for the quick reply and assistance. Love the app, it's the most important app on my mobile since the pandemic. Maybe that is the cause I've felt so upset about this issue at first. Thank you to all the dev team.
