### ISSUE TITLE
Additional features for the contact diary see pull request 1651 and wishlist issue 196

### ISSUE THREAD

**Issue by ouboub** [corona-warn-app/cwa-wishlist#286]
Hi

It is great to see that there is already a [pull request](https://github.com/corona-warn-app/cwa-app-ios/pull/1651) for
implementing a contact diary. 

I have been using the contact diaries that are meanwhile available in
the App Store quite extensively in the last weeks: 

These are 

1.  [Kontakt Tagebuch](https://apps.apple.com/de/app/kontakt-tagebuch/id1535797892?l=en) and

2.  [Cluster Diary](https://apps.apple.com/de/app/kontakt-tagebuch/id1535797892?l=en)

3.  [Coronika](https://apps.apple.com/de/app/coronika/id1538427759?l=en)

I'd like to add some feature proposal about the screenshot presented.

1.  It would be great to have icons, indicating if masks were used
    and to which extend, also whether distance was kept (say in a
    lecture). Moreover an icon for a cluster event would be helpful.

2.  Optionally using GPS for finding out addresses of the event/meeting.

3.  Export: besides send a csv file of all contact in the last 14
    days to the  relevant institution (Gesundheitsamt), it would
    very useful to allow the export of single encounters, in case I
    also want to inform my contacts individually if I am positive.
    And for reasons of privacy I don't want to send the whole list.

Uwe Brauer 

---
Internal Tracking ID: [EXPOSUREAPP-3034](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3034)

**Comment by Ein-Tim** [comment]
@ouboub 

Export: https://github.com/corona-warn-app/cwa-app-ios/pull/1695

**Comment by jucktnich** [comment]
What's about a machine readable format for exporting (e.g. XML-File), so the Gesundheitsamt can use it automatically?

**Comment by ouboub** [comment]
> What's about a machine readable format for exporting (e.g. XML-File), so the Gesundheitsamt can use it automatically?

Hi

I think **CSV** is fine, but and I cannot emphasise this enough, this functionality should also allow to export individual meetings/contact to the persons involved. The «Gesundheitsamt» seems to be overloaded with word and also hampered by incompatible software issues etc.

**Comment by ouboub** [comment]
> @ouboub
> 
> Export: [corona-warn-app/cwa-app-ios#1695](https://github.com/corona-warn-app/cwa-app-ios/pull/1695) (only all entries)
> 
> GPS: Not possible because of Apple/Google restrictions

even not optionally?

**Comment by ouboub** [comment]
> @ouboub
> 
> Export: [corona-warn-app/cwa-app-ios#1695](https://github.com/corona-warn-app/cwa-app-ios/pull/1695) (only all entries)


the video only shows how to export **all** entries, which is fine for the Gesundheitsamt, but since they are overwhelmed with work, it would be **very important** to inform my contacts myself, but because of privacy reasons, I don't want to inform all my contacts about **all** my meetings. I don't understand that the APP is so picky with respect to data protection in certain aspects but in this aspect seems not to care at all.
Did I explain my point?

**Comment by Ein-Tim** [comment]
@ouboub 

> even not optionally?

No, Apps using the ENF are not allowed to use the location...

**Comment by MikeMcC399** [comment]
Related to #196 but not currently linked.

**Comment by MikeMcC399** [comment]
@ouboub 
> the video only shows how to export all entries, which is fine for the Gesundheitsamt, but since they are overwhelmed with work, it would be very important to inform my contacts myself, but because of privacy reasons, I don't want to inform all my contacts about all my meetings. I don't understand that the APP is so picky with respect to data protection in certain aspects but in this aspect seems not to care at all.

I tried out the current branch release/1.10.x in Android which of course is still a "work-in-progress". The Contact Journal offers the option "Export Entries" which provides simple text. On Android you could for instance save this to Google Drive and from there edit any entries. 

This is a fictive example of what export currently produces:
```
Kontakte der letzten 14 Tage (11.12.2020 - 24.12.2020)
Die nachfolgende Liste dient dem zuständigen Gesundheitsamt zur Kontaktnachverfolgung gem. § 25 IfSG.

21.12.2020 Office
20.12.2020 Supermarket Hauptstr.
20.12.2020 Alfons
18.12.2020 Anja

```

Exactly what you share is your decision. Picking out single encounters is very easy with an editor.

**Comment by ouboub** [comment]
> @ouboub 
>> the video only shows how to export all entries, which is fine for
> the Gesundheitsamt, but since they are overwhelmed with work, it would
> be very important to inform my contacts myself, but because of privacy
> reasons, I don't want to inform all my contacts about all my meetings.
> I don't understand that the APP is so picky with respect to data
> protection in certain aspects but in this aspect seems not to care at
> all.

> I tried out the current branch release/1.10.x in Android which of
> course is still a "work-in-progress". The Contact Journal offers the
> option "Export Entries" which provides simple text. On Android you
> could for instance save this to Google Drive and from there edit any
> entries.

> This is a fictive example of what export currently produces:
> ```
> Kontakte der letzten 14 Tage (11.12.2020 - 24.12.2020)
> Die nachfolgende Liste dient dem zuständigen Gesundheitsamt zur Kontaktnachverfolgung gem. § 25 IfSG.

> 21.12.2020 Office
> 20.12.2020 Supermarket Hauptstr.
> 20.12.2020 Alfons
> 18.12.2020 Anja

I am a die hard user of GNU emacs (which I also use for email) and for
me this is indeed simple but still a hassle because as you say I have to
save the list first (or send it to myself) and then to extract the
information.

But that is not the point. I think experience has shown the easier it is
for the average user to do something the more likely it is that he/she
will use it. I don't know the actual numbers, but some weeks ago, only
50% of the users entered their positive test results in the app, now at
least they are reminded.

So let's say the average user is keeping a diary, receives a positive test
result and then send it to the Gesundheitsamt. He/she thinks, shall I
inform my friends. He thinks about the step to perform and concludes 
B.H. And does not do anything.

If on other hand, either after entering the positive test result, he is offered:

    1. Shall I send the list to the Gesundheitsamt

    2. Do you want to warn your contact yourself

Opens his current meetings, see a button share which in turn would open

    1. email

    2. Whatsapp or something like that

I think it would be brilliant.

**Comment by Ein-Tim** [comment]
@ouboub do you agree with me that we could close this Issue since you opened #308 & #309?

**Comment by ouboub** [comment]
>>> "ET" == Ein Tim <notifications@github.com> writes:

> @ouboub do you agree with me that we could close this Issue since you opened #308 & #309? 

It was my understanding from comments that this it would be best to have
a wishlist for each feature. That is why I opened several, but yes this
issue should be closed. 

But may be you can tell me that is best, one issue for feature proposals
or for each proposal an issue?

**Comment by Ein-Tim** [comment]
@ouboub 
Yes I think a separate issues for each request is the best way since its easier to keep track what already was requested and what the status of the issues is. 

You, as the author of this issue, can close it. 👍

**Comment by ouboub** [comment]
ok, done
