### ISSUE TITLE
Datenschutz in App Store 17+ an Google playstore 0+ anpassen

### ISSUE THREAD

**Issue by fpientka** [corona-warn-app/cwa-wishlist#29]
Bitte schnell Datenschutz in App Store 17+ am Google Playstore  USK ab 0 Jahren 
![apps apple corona-warn-app](https://user-images.githubusercontent.com/6198113/84748869-7d0c7380-afb9-11ea-93db-a2e6dac3cad5.PNG)
![play google store de rki coronawarnapp](https://user-images.githubusercontent.com/6198113/84748871-7ed63700-afb9-11ea-8416-5d3ec9523b65.PNG)

anpassen

--------
Internal Tracking ID: EXPOSUREAPP-2159

**Comment by Ein-Tim** [comment]
The App is now rated as 12+ in the App Store, so I think this Issue can be closed, or @fpientka?

**Comment by fpientka** [comment]
Of course could be closed. Now more pupils can use it!

**Comment by Ein-Tim** [comment]
So, now we're back to 17+, see https://github.com/corona-warn-app/cwa-app-ios/issues/2984. 
Would you like to reopen this @fpientka?
