### ISSUE TITLE
Make CWA in-app-reset preserve the tracing duration display

### ISSUE THREAD

**Issue by Diapolo** [corona-warn-app/cwa-wishlist#290]
## Feature description

It would be really nice to keep/preserve or regenerate the tracing duration ("Riskoermittlung war die ganze Zeit aktiv") after doing an in-app-reset.

## Problem and motivation

As far as I know and observed the exposure database is keept after doing an in-app-reset and thus all data is available to display or regenerate the tracing duration for CWA. Please add this, it would make app-resets to recover from problems much more low-level from my point of view.

It feels like beeing at higher risk now, even if thisis not the case.

## Is this something you're interested in working on

No
---
Internal Tracking ID: [EXPOSUREAPP-4442](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4442)

**Comment by MikeMcC399** [comment]
@Diapolo 
You are absolutely right about this need!
It probably needs an enhancement to the [Google Exposure Notifications API](https://developers.google.com/android/exposure-notifications/exposure-notifications-api) to pass back the data. 

Google should provide data which says for each of the past 14 days how many hours exposure logging was activated for logged data available. CWA could then display correct information about duration. It gets it wrong after in-app reset, and if the phone has been switched off. Also if there are multiple COVID-19 apps installed (from different countries) and the apps are alternatively enabled it becomes problematic for CWA to know about the exposure logging enabled by other apps when CWA is (re-)activated.

**Comment by heinezen** [comment]
related: https://github.com/corona-warn-app/cwa-wishlist/issues/164

**Comment by heinezen** [comment]
Hello @Diapolo ,

Thank you for your suggestion. We have added your request to our internal Jira system (ticket ID: EXPOSUREAPP-4442) and it will now be discussed by the development team and the RKI. They will have to decide how and if the feature can be realized. We will notify you here, when we get news on the status of the request.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
This has been implemented with the change to show since when the app is installed (version 1.15).

I therefore suggest to close this issue.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
>This has been implemented with the change to show since when the app is installed (version 1.15).
>
>I therefore suggest to close this issue.

The installation date does not guarantee that exposure logging was enabled, nor does it say that any exposure logs which were collected were not deleted since installation.

Probably the current implementation is the closest that the app is going to get to fulfilling this wishlist item, because anything else would require a Google enhancement.

It would be pragmatic to close it, even though it hasn't been exactly implemented.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Under iOS, the RPIs and downloaded DKs are not deleted when performing an in-app reset. This is different under Android, right?

In this case, this request has been fully implemented under iOS but not under Android. But as you say, everything else needs to be done by Google, so I also suggest to close this.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
According to https://www.coronawarn.app/en/faq/#in_app_reset the in-app reset does not delete the exposure data.

Under Android when a Reset App is carried out, the user is warned 
** Delete Exposure Log **
The exposure log must be deleted separately in your device settings.

If the user then goes ahead with separately deleting the exposure log in the device settings then the installation date of the app does not say anything about the time interval for which exposure data is stored.

**Comment by Ein-Tim** [comment]
Okay nice, then this has been fully implemented under both, iOS and Android (with the restriction @MikeMcC399 mentioned in https://github.com/corona-warn-app/cwa-wishlist/issues/290#issuecomment-881621286).

**Comment by heinezen** [comment]
I've set the ticket to obselete. We'll close here because the duration display was removed.

----
Corona-Warn-App Open Source Team
