### ISSUE TITLE
Add Home Screen Quick Actions/App shortcuts (Contact diary)

### ISSUE THREAD

**Issue by jajoho** [corona-warn-app/cwa-wishlist#295]
## Current Implementation
Currently I do not have any quick actions, when I touch and hold the app icon (see screenshot)
![IMG_63E7D35D980E-1](https://user-images.githubusercontent.com/15175599/103222774-13d0ca00-4925-11eb-9922-5e341bf475ca.jpeg)

## Suggested Enhancement
It would be nice, if I could get directly to the most important functions of the app if I touch and hold the app icon (e.g. Kontakt-Tagebuch).
iOS: https://developer.apple.com/design/human-interface-guidelines/ios/system-capabilities/home-screen-actions/
Android: https://developer.android.com/guide/topics/ui/shortcuts

## Expected Benefits
More usability of the app -> It is more likely, that the functions are frequently used

---
Internal Tracking ID: EXPOSUREAPP-3034
Internal Tracking ID: [EXPOSUREAPP-4659](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4659) Android
Internal Tracking ID: [EXPOSUREAPP-5081](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5081) iOS

**Comment by heinezen** [comment]
Thank you @jajoho 

We have forwarded your suggestions to the dev team.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Related Internal Tracking-ID: EXPOSUREAPP-4659

**Comment by Ein-Tim** [comment]
This will be added in version 1.14 ([Source](https://github.com/corona-warn-app/cwa-app-ios/pull/1988/files#diff-130eb13421036eb3058649fa7623c37dcdf42a3ed0069060bfe0f81a95403f6fR1359))!

**Comment by Ein-Tim** [comment]
PR introducing this for iOS: https://github.com/corona-warn-app/cwa-app-ios/pull/2031

**Comment by dsarkar** [comment]
@jajoho   and dear community. Thanks for your contributions. This feature has been implemented. We suggest closing this issue now.  Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
Here is a screenshot from CWA Android 1.14.3 showing the implementation

![Add Entry](https://user-images.githubusercontent.com/66998419/110842077-f1551880-82a6-11eb-85f7-37d922bf6338.jpg)
