### ISSUE TITLE
Add information about rapid test results to app

### ISSUE THREAD

**Issue by achisto** [corona-warn-app/cwa-wishlist#298]
## Current Implementation
Currently there is not a single [FAQ](https://www.coronawarn.app/de/faq/) entry regarding rapid tests (Schnelltest). Also the CWA does not contain information about how rapid test results are handled inside CWA.

## Suggested Enhancement
At the moment and for various reasons it is not possible to warn others if the user's test result origins from a rapid-test, only PCR-test results qualify. As long as this does not change two improvements  should be made:

- add a note to the "request TAN"-screen informing the user that calling the TAN-hotline after a rapid-test is not needed as they cannot issue a TAN

## Expected Benefits
There have already been media reports (e.g. [this ARD-show](https://www.daserste.de/information/nachrichten-wetter/ard-extra/videosextern/ard-extra-die-corona-lage-420.html), timecode 13:00) voicing concerns about this issue. Personally, I already had friends contact me asking about "how do I register a positive rapid-test". People should at least find reliable information online and inside the CWA.

---
Internal Tracking ID: EXPOSUREAPP-4714

**Comment by MikeJayDee** [comment]
Agreed. I think an item should be added to the "were you tested?" workflow. Essentially add an option to let users indicate that they carried out a rapid test (self-test or tested by professional). When they tap on this, they should be told that if the rapid test is positive they should contact their general practitioner or 116117 to arrange for a PCR test, and come back to the app to register the PCR test after they were tested.

**Comment by MikeMcC399** [comment]
@achisto

I believe that this wishlist item is now fulfilled. Maybe you'd like to check through if you are satisfied and close if appropriate?

"Project team integrates rapid COVID-19 tests into Corona-Warn-App version 2.1" https://www.coronawarn.app/en/blog/2021-05-02-corona-warn-app-version-2-1/ announced the new version on May 2, 2021.

There is a complete new FAQ section [Rapid antigen test](https://www.coronawarn.app/en/faq/#rapid_antigen_test) covering this aspect of the app enhancement.

The app now labels the sections "Enter TAN for PCR Test" and "Request TAN for PCR Test?" by adding the reference to "PCR". This does not explicitly state that TANs are not issued for Rapid Antigen Tests, however the fact that only PCR tests are specifically mentioned should suggest this. The FAQ article [Can I share my positive rapid antigen test result via the TAN hotline?](https://www.coronawarn.app/en/faq/#rat_tan_hotline) explains this explicitly. This is related to the part of the wishlist item suggesting that the "request TAN"-screen. The request has not been implemented exactly though.

**Comment by achisto** [comment]
> 
> 
> @achisto
> 
> I believe that this wishlist item is now fulfilled. Maybe you'd like to check through if you are satisfied and close if appropriate?
> 
> "Project team integrates rapid COVID-19 tests into Corona-Warn-App version 2.1" https://www.coronawarn.app/en/blog/2021-05-02-corona-warn-app-version-2-1/ announced the new version on May 2, 2021.
> 
> There is a complete new FAQ section [Rapid antigen test](https://www.coronawarn.app/en/faq/#rapid_antigen_test) covering this aspect of the app enhancement.
> 
> The app now labels the sections "Enter TAN for PCR Test" and "Request TAN for PCR Test?" by adding the reference to "PCR". This does not explicitly state that TANs are not issued for Rapid Antigen Tests, however the fact that only PCR tests are specifically mentioned should suggest this. The FAQ article [Can I share my positive rapid antigen test result via the TAN hotline?](https://www.coronawarn.app/en/faq/#rat_tan_hotline) explains this explicitly. This is related to the part of the wishlist item suggesting that the "request TAN"-screen. The request has not been implemented exactly though.

Thanks for your comment, you are right, the item ist fulfilled in some way and I think it is sufficient. I will close the issue with my comment!

**Comment by dsarkar** [comment]
@achisto @MikeMcC399 Thanks.
