### ISSUE TITLE
Make app available for iPads

### ISSUE THREAD

**Issue by tkowark** [corona-warn-app/cwa-wishlist#30]
## Current Implementation
The app is only available for iPhones.

## Suggested Enhancement
Make the app also available for iPads

## Expected Benefits
Reach even more users that only have a tablet but no compatible cellphone

--------
Internal Tracking ID: EXPOSUREAPP-2155

**Comment by nitramwin** [comment]
Agreed.

**Comment by larswmh** [comment]
Closing this issue. Internal feedback:

> This is currently not intended, therefore this issue will be set to „Obsolete“
