### ISSUE TITLE
Contact diary: Entering period of time in which a given place was visited

### ISSUE THREAD

**Issue by Selduro** [corona-warn-app/cwa-wishlist#301]
## Current Implementation

Right now it is only possible to enter a place one visited on a given day.

## Suggested Enhancement

I'd like to be able to (optionally!) enter the period of time I spent at the place in question.
For example if I visit my doctor I might sit in her waiting room from 9:30 to 10:00. While she probably knows when I checked into her practice she probably isn't tracking the time at which I left. To determine who spent time with me in that waiting room it would make sense to being able to input the period of time I stayed there.

This is especially true for places that don't even track the exact beginning of my visit.

## Expected Benefits

In my opinion this could make contact tracing a lot easier.

---
Internal Tracking ID: [EXPOSUREAPP-3034](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3034)

**Comment by Ein-Tim** [comment]
This will be added with version 1.14 ([Source](https://github.com/corona-warn-app/cwa-app-ios/pull/1988/files#diff-130eb13421036eb3058649fa7623c37dcdf42a3ed0069060bfe0f81a95403f6fR1357)):

>Sie können zu jedem Eintrag angeben, unter welchen Umständen die Begegnung stattfand. Sie können aus vorgegebenen Optionen auswählen (z.B. Dauer der Begegnung, mit oder ohne Maske) sowie zusätzlich in einer kurzen Notiz weitere Umstände erfassen, die zu einem erhöhten Risiko führen könnten. Sollten Sie sich tatsächlich anstecken, können diese Angaben dem Gesundheitsamt bei der Nachverfolgung möglicher Infektionsketten helfen.

**Comment by dsarkar** [comment]
@Selduro  and dear community. Thanks for your contributions. This feature has been implemented. We suggest closing this issue now.  Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
This is a screenshot from CWA Android 1.14.3 showing one hour (01:00) spent at a place. (The yellow highlight was added by me.)

![Places with time](https://user-images.githubusercontent.com/66998419/110842913-febed280-82a7-11eb-9366-bd4e18453081.jpg)

**Comment by heinezen** [comment]
Dear community,

Thiis feature is now implemented in CWA v1.14. Thank you for your contributions to the discussion.

We will close this issue now. If you have further suggestions regarding this particular feature, please open a new issue.

----
Corona-Warn-App Open Source Team
