### ISSUE TITLE
Kontaktdaten von Kontaktpersonen 

### ISSUE THREAD

**Issue by Saarox** [corona-warn-app/cwa-wishlist#304]
Es wäre sehr praktisch, wenn man auch separate Felder für Kontaktdaten (Tel. und Adresse) von Kontaktpersonen im neuen Tagebuch eintragen könnte. 

Aktuell muss das alles in einer Zeile eingetragen werden, was es etwas unübersichtlich macht und weshalb man eigentlich lieber drauf verzichtet. Dabei sind ja genau diese Angaben im Falle einer Infektion besonders relevant. 

---
Internal Tracking ID: [EXPOSUREAPP-3034](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3034)

**Comment by Ein-Tim** [comment]
Something like this will be added with version 1.14 ([Source](https://github.com/corona-warn-app/cwa-app-ios/pull/1988/files#diff-130eb13421036eb3058649fa7623c37dcdf42a3ed0069060bfe0f81a95403f6fR1357)):

>Sie können zu jedem Eintrag angeben, unter welchen Umständen die Begegnung stattfand. Sie können aus vorgegebenen Optionen auswählen (z.B. Dauer der Begegnung, mit oder ohne Maske) sowie zusätzlich in einer kurzen Notiz weitere Umstände erfassen, die zu einem erhöhten Risiko führen könnten. Sollten Sie sich tatsächlich anstecken, können diese Angaben dem Gesundheitsamt bei der Nachverfolgung möglicher Infektionsketten helfen.

**Comment by Ein-Tim** [comment]
Version 1.14 which introduced this has been released to GitHub and is available to all users in the next 48h. 

See blog post: 

DE: https://www.coronawarn.app/de/blog/2021-03-09-corona-warn-app-version-1-14/
EN: https://www.coronawarn.app/en/blog/2021-03-09-corona-warn-app-version-1-14/

See GitHub release:

iOS: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.14.3
Android: https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.14.3

**Comment by dsarkar** [comment]
@Saarox  and dear community. Thanks for your contributions. This feature has been implemented. We suggest closing this issue now.  Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@Saarox 

This was a very good suggestion!

Here is the edit Person screen from CWA Android 1.14.3 showing the additional fields for Phone and e-mail:

![Person with details](https://user-images.githubusercontent.com/66998419/110844739-126b3880-82aa-11eb-9865-422bac56f4d2.jpg)

**Comment by heinezen** [comment]
Dear community,

Thiis feature is now implemented in CWA v1.14 (as part of a general feature to write notes). Thank you for your contributions to the discussion.

We will close this issue now. If you have further suggestions regarding this particular feature, please open a new issue.

----
Corona-Warn-App Open Source Team
