### ISSUE TITLE
Contact Diary: Option to document the environment in which a contact was met

### ISSUE THREAD

**Issue by le-jou** [corona-warn-app/cwa-wishlist#305]
## Suggested Enhancement

While the Contact Diary is a great enhancement, I miss an option to specify the environment in which a Person was met. Was it a large ventilated room, a small room or outdoors? Were contacts wearing masks?
As per [2.1 "Risikobewertung"](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Kontaktperson/Management.html) there is a difference in contact person ranking depending on the environment.
Another critical information is the duration of exposure, so this would also be helpful to add.

To keep things simple for users which only want to keep track of contacts, providing this kind of information should be optional.

---
Internal Tracking ID: [EXPOSUREAPP-3034](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3034)

**Comment by Ein-Tim** [comment]
This will be added with version 1.14 ([Source](https://github.com/corona-warn-app/cwa-app-ios/pull/1988/files#diff-130eb13421036eb3058649fa7623c37dcdf42a3ed0069060bfe0f81a95403f6fR1357)):

>Sie können zu jedem Eintrag angeben, unter welchen Umständen die Begegnung stattfand. Sie können aus vorgegebenen Optionen auswählen (z.B. Dauer der Begegnung, mit oder ohne Maske) sowie zusätzlich in einer kurzen Notiz weitere Umstände erfassen, die zu einem erhöhten Risiko führen könnten. Sollten Sie sich tatsächlich anstecken, können diese Angaben dem Gesundheitsamt bei der Nachverfolgung möglicher Infektionsketten helfen.

**Comment by Ein-Tim** [comment]
Version 1.14 which introduced this has been released to GitHub and is available to all users in the next 48h. 

See blog post: 

DE: https://www.coronawarn.app/de/blog/2021-03-09-corona-warn-app-version-1-14/
EN: https://www.coronawarn.app/en/blog/2021-03-09-corona-warn-app-version-1-14/

See GitHub release:

iOS: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.14.3
Android: https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.14.3

**Comment by dsarkar** [comment]
@le-jou  and dear community. Thanks for your contributions. This feature has been implemented. We suggest closing this issue now.  Best wishes, DS

---
Corona-Warn-App Open Source Team
