### ISSUE TITLE
[Overview] Issues reg. contact journal

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#310]
**This is an overview over all open Issues regarding the contact journal** (to keep track and avoid duplicates).

| Issue | Title | Status | JIRA |
| --- | --- | --- | --- |
| #294 | Allow users to enable a daily reminder via push notification | **OPEN** | [EXPOSUREAPP-3034](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3034) |
| #297 | Export entries in SORMAS-compatible format | **OPEN** | [EXPOSUREAPP-3034](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3034) |
| #306 | Allow the import from the iOS contact list | **OPEN** | [EXPOSUREAPP-3034](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3034) |
| #307 | Allow to change the date of a contact-meeting | **OPEN** | [EXPOSUREAPP-3034](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3034) |
| #308 | Add icons of the kind of meeting | **OPEN** | [EXPOSUREAPP-3034](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3034) |
| #309 | Export single events | **OPEN** | [EXPOSUREAPP-3034](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3034) |
| #311 | Store actual position using a button in "Kontakt-Tagebuch" | **OPEN** | [EXPOSUREAPP-3034](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3034) |
| #317 | Add new Entries from Edit View | **OPEN** | [EXPOSUREAPP-3034](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3034) |
| #318 | Process if entry already exists | **OPEN** | [EXPOSUREAPP-4949](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4949) |
| #322 | Grouping of contacts and one-time contacts | **OPEN** | [EXPOSUREAPP-3034](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3034) |
| #324 | CSV import | **OPEN** | [EXPOSUREAPP-3034](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3034) |
| #325 | Make it possible to change contact people sort order | **OPEN** | [EXPOSUREAPP-3034](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3034) |
| #339 | Use already existing code on github | **OPEN** | [EXPOSUREAPP-3034](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3034) |
| #369 | Change names of persons and places when exporting | **OPEN** | [EXPOSUREAPP-3034](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3034) |
| #480 | Add a button to the contact journal to add a self test | **OPEN** |  [EXPOSUREAPP-6747](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6747) |
| #712 | Suggest Entries from Calendar and Contacts | **OPEN** | [EXPOSUREAPP-11436](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11436) | |
| #752 | Contact Journal - Update places from Photos I took with my device | **OPEN** | [EXPOSUREAPP-11429](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11429) |
| #775 | Upon entering new contact or place immediately request exposure details entry | **OPEN** | [EXPOSUREAPP-12076](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12076) |
| #789 | Personen Orten zuteilen  | **OPEN** |  [EXPOSUREAPP-12005](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12005) |
| #800 | Display also scanned test result in "Contact Journal" also if registration for the test was not scanned | **OPEN** | [EXPOSUREAPP-12004](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12004) |
| #801 | Extension of the time range in the CWA diary to make it more flexible... | **OPEN** | [EXPOSUREAPP-6160](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6160) |

This overview was last updated on 21.02.2023 (dd.mm.yyyy).

---

Internal Tracking ID: [EXPOSUREAPP-3034](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3034) (Overview)
Internal Tracking ID: [EXPOSUREAPP-5080](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5080) (iOS)
Internal Tracking ID: [EXPOSUREAPP-4741](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4741) (Android)

**Comment by Ein-Tim** [comment]
@dsarkar Do you want me to close this issue (since we have the labels now) or do you want it to stay open?

**Comment by dsarkar** [comment]
@Ein-Tim This thread is brilliant. Keep it open, please. We should do this also with other bigger and related topics (e.g. vaccination / side-effects tracking, QR code related threads ...)  Let's also put the bugs in there, easier to track all of them.

**Comment by Ein-Tim** [comment]
@dsarkar 
I could create threats about the QR-Code and vaccination theme if this would be ok for you 👍

**Comment by dsarkar** [comment]
I wonder if we should move this to the documentation repo if we include also bugs or current ongoing work?

**Comment by Ein-Tim** [comment]
@dsarkar I'm not sure, are there any current known Issues/bugs regarding the contact diary? Or do you mean in general?

**Comment by ndegendogo** [comment]
> this thread is brilliant

@Ein-Tim **definitely!**
One suggestion: is it possible to 'mark' the resolved tickets somehow in this overview? So we can better keep track what is still open?

A strike-through markup would be perfect (but not sure if this is available here.
Alternatively, a textual 'done' or something similar.

**Comment by ndegendogo** [comment]
**Forget my previous suggestion - it is already in place!**

**Comment by dsarkar** [comment]
@Ein-Tim, @ndegendogo,  @MikeMcC399, Community

Question:
What is your opinion: Which are the most important/ hot topic/most desired wishlist items regarding contact diary?
Thanks for feedback.

**Comment by Ein-Tim** [comment]
@dsarkar 
I would say: 
corona-warn-app/cwa-app-android#294, corona-warn-app/cwa-app-android#301 and maybe also corona-warn-app/cwa-app-android#314.

**Comment by ndegendogo** [comment]
@dsarkar thanks for asking.

My top is corona-warn-app/cwa-app-android#314 (free-text notes). It covers several others in functionality (not in comfort!), like corona-warn-app/cwa-app-android#301, corona-warn-app/cwa-app-android#305, corona-warn-app/cwa-app-android#350.
My second would be corona-warn-app/cwa-documentation#213 / corona-warn-app/cwa-app-android#330 (easy and fast access).

**Comment by ndegendogo** [comment]
@dsarkar thanks for asking.

My top is: #314 (free-text notes). It covers several others in functionality (not in comfort!), like #301, #305
My second is #285 / #330 (easy and fast access).

**Comment by dsarkar** [comment]
@Ein-Tim FYI PR Comment function https://github.com/corona-warn-app/cwa-app-android/pull/2357

**Comment by Ein-Tim** [comment]
@dsarkar Thank you!

**Comment by Ein-Tim** [comment]
Version 1.14 which introduced many of the features proposed, has been released to GitHub and is available to all users in the next 48h. 

See blog post: 

DE: https://www.coronawarn.app/de/blog/2021-03-09-corona-warn-app-version-1-14/
EN: https://www.coronawarn.app/en/blog/2021-03-09-corona-warn-app-version-1-14/

See GitHub release:

iOS: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.14.3
Android: https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.14.3

**Comment by gleichda** [comment]
@Ein-Tim Just wanted to use the label like described in the initial description: https://github.com/corona-warn-app/cwa-wishlist/labels/contact-diary

But it seems to be empty :/ So my suggestion either use it or remove it 🙈 

Edit: The URL is just wrong the label is contact-journal not contact-diary

**Comment by Ein-Tim** [comment]
@gleichda 
Thanks for the hint (:

**Comment by MikeMcC399** [comment]
In the code it is called "ContactDiary", however the user interface, documentation, FAQs, etc. use the name "Contact Journal".

**Comment by Ein-Tim** [comment]
FYI: All overviews have been updated and superfluous fields have been removed.

**Comment by Hdfgg** [comment]
Hd

**Comment by Ein-Tim** [comment]
As [CWA development is ending](https://www.coronawarn.app/en/faq/results/#ramp_down), I'm discontinuing this overview.
