### ISSUE TITLE
Contact diary - add comment field (free text) for each day

### ISSUE THREAD

**Issue by tangomanni** [corona-warn-app/cwa-wishlist#314]
This issue generalizes possible issues #301, #305 and #308

## Current Implementation
Currently I can only enter contacts I had and locations I visited at one day.

##  Suggested Enhancement
Allow to add some more information to the contacts or locations which were visited on a day (periods of meeting others, environment, meet several people at one time, etc.. see issues mentioned)
To allow an easy and non restrictive implementation the adding of an optional comment field per day (for free text) is requested

## Expected Benefits
Obviously this gives more details about my infection risks for me, the doctor and health authorities in case of a warning message by CWA.
Having one gneric comment field only might avoid discussions about what can be an environment, how to enter periods, etc.
See also issues #301, #305 and #308

---
Internal Tracking ID: EXPOSUREAPP-3034

**Comment by heinezen** [comment]
Thank you @tangomanni 

We have forwarded your suggestions to the dev team.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by Art4** [comment]
Currently I maintain a separate text file as contact diary on my phone. There I can write down some medical data, contacts of other family members or times/durations of contacts. This is not possible with the current implementation but would be possible with this suggestion.

**Comment by Ein-Tim** [comment]
This will be added with version 1.14 ([Source](https://github.com/corona-warn-app/cwa-app-ios/pull/1988/files#diff-130eb13421036eb3058649fa7623c37dcdf42a3ed0069060bfe0f81a95403f6fR1357)):

>Sie können zu jedem Eintrag angeben, unter welchen Umständen die Begegnung stattfand. Sie können aus vorgegebenen Optionen auswählen (z.B. Dauer der Begegnung, mit oder ohne Maske) sowie zusätzlich in einer kurzen Notiz weitere Umstände erfassen, die zu einem erhöhten Risiko führen könnten. Sollten Sie sich tatsächlich anstecken, können diese Angaben dem Gesundheitsamt bei der Nachverfolgung möglicher Infektionsketten helfen.

**Comment by Ein-Tim** [comment]
Version 1.14 which introduced this has been released to GitHub and is available to all users in the next 48h. 

See blog post: 

DE: https://www.coronawarn.app/de/blog/2021-03-09-corona-warn-app-version-1-14/
EN: https://www.coronawarn.app/en/blog/2021-03-09-corona-warn-app-version-1-14/

See GitHub release:

iOS: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.14.3
Android: https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.14.3

**Comment by dsarkar** [comment]
Dear @tangomanni  and dear community. Thanks for your contributions. This feature has been implemented. We suggest closing this issue now.  

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@tangomanni 

This is what it looks like in CWA Android 1.14.3. You can add a note for a Person or a Place.

In your title you have "for each day", so the implementation is finer than putting a note just on the day itself. You put a note on a Person or a Place for a day.

![People note](https://user-images.githubusercontent.com/66998419/110845216-a50bd780-82aa-11eb-8d18-dd9b7dc273ff.jpg)

There are other screenshots on https://www.coronawarn.app/en/screenshots/ to look at.

**Comment by tangomanni** [comment]
Hello Mike,

Looks good so far. When will this Version be available for Android ? Looking Forward to use the new Features. These days I would have used that for diverse Events.

Kind regards
Manfred

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Mike ***@***.***>
Gesendet: Donnerstag, 11. März 2021 20:49
An: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Betreff: Re: [corona-warn-app/cwa-wishlist] Contact diary - add comment field (free text) for each day (#314)


@tangomanni<https://github.com/tangomanni>

This is what it looks like in CWA Android 1.14.3. You can add a note for a Person or a Place.

In your title you have "for each day", so the implementation is finer than putting a note just on the day itself. You put a note on a Person or a Place for a day.

[People note]<https://user-images.githubusercontent.com/66998419/110845216-a50bd780-82aa-11eb-8d18-dd9b7dc273ff.jpg>

There are other screenshots on https://www.coronawarn.app/en/screenshots/ to look at.

**Comment by MikeMcC399** [comment]
@tangomanni 
> When will this Version be available for Android ? 

CWA Android Version 1.14.3 is being rolled out. As with previous versions, it's a staged rollout, so people receive it during a 48 hour window which was announced two days ago - see https://www.coronawarn.app/en/blog/2021-03-09-corona-warn-app-version-1-14/.

You can check on [Google Play Store](https://play.google.com/store/apps/details?id=de.rki.coronawarnapp) to see if it is already available to your Google account. If you just wait and let the app update automatically it can take another additional 24 hours.

**Comment by heinezen** [comment]
Dear community,

Thiis feature is now implemented in CWA v1.14. Thank you for your contributions to the discussion.

We will close this issue now. If you have further suggestions regarding this particular feature, please open a new issue.

----
Corona-Warn-App Open Source Team
