### ISSUE TITLE
Contact diary - Export to a text file or PDF

### ISSUE THREAD

**Issue by tangomanni** [corona-warn-app/cwa-wishlist#315]
## Current Implementation
Clicking the export contact diary button I have the choice to select an App which is on my smartphone to do the next steps.

## Suggested Enhancement
Allow to export the contact diary to a simple text file or PDF file I can store somewhere on my phone.

## Expected Benefits
User not familiar with all these different apps and what would they mean for my contact diary export can create a simple file on their phone processed later.

---
Internal Tracking ID: EXPOSUREAPP-3034

**Comment by heinezen** [comment]
Thank you @tangomanni 

We have forwarded your suggestions to the dev team.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Related Issue:

#297

**Comment by dsarkar** [comment]
@tangomanni 

- It is actually possible to export to a text file. 
- PDF is not an option, because the user must be able to modify the content.

**Comment by MikeMcC399** [comment]
@tangomanni 

On a reference Google Pixel 3a, Android 11 emulator, the following targets are shown to export the contact journal. (See screenshot below.) Android Save to Drive saves to a text file. 

Android device vendors typically bundle additional apps which accept text input such as Samsung Notes. In the case of Samsung Notes, the app also offers the option to Save as file > PDF file. As @dsarkar wrote, PDF is less flexible for editing, so text would be the preferred format for sharing with the Gesundheitsamt.

**Do you still want to keep this wishlist item open?**

![image](https://user-images.githubusercontent.com/66998419/107634051-3f0b4080-6c69-11eb-88c4-4f4eefdf0a54.png)

**Comment by heinezen** [comment]
@tangomanni

The developers have decided to not pursue this request for the reasons @dsarkar gave in comment https://github.com/corona-warn-app/cwa-wishlist/issues/315#issuecomment-777360289

> * It is actually possible to export to a text file.
> * PDF is not an option, because the user must be able to modify the content.

(The content being modifiable is an external requirement)

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by tangomanni** [comment]
OK, I accept this decision. Also with the current version I have found a way how to store the diary as a text file (via MPE Notizen). Indepent from the goal to inform "Gesundheitsamt" I store the diary regularly to have a complete overview of the contacts in the past.

**Comment by dsarkar** [comment]
@tangomanni Thanks for the feedback. Best wishes, DS

---
Corona-Warn-App Open Source Team
