### ISSUE TITLE
Contact diary: Add ability to delete misspelled locations

### ISSUE THREAD

**Issue by smares** [corona-warn-app/cwa-wishlist#316]
## Current Implementation

Currently, any location once saved will be available as suggestion for other days. If I misspelled a location and later correct that mistake by adding a location with the proper name, the misspelled location cannot be deleted.

## Suggested Enhancement

Add the ability to delete unused locations or individual locations.

## Expected Benefits

Improved overview when adding a location for a given date as misspelled locations no longer appear in the list

**Comment by Ein-Tim** [comment]
@smares 
You should be able to rename locations (used or unused). 

(German instruction, English will follow later): 

Open the App ➡️ `Tagebuch führen` ➡️ click on the 3 dots in the right corner ➡️ `Orte bearbeiten` ➡️ click on the location ➡️ change the name/delete the location by tapping on the red minus. 
(This is a instruction for iOS, could be that Android differs a bit from this)

**Comment by smares** [comment]
You are absolutely right, sorry for missing that.
