### ISSUE TITLE
Integrate 116117.app in CWA for Corona Test

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-wishlist#320]
## Current Implementation
The app seems to only refer to the telephone number 116117, without mentioning the Apple and Google 116117.app or the website www.116117.de

<string name="risk_details_behavior_increased_body_2">"General medical emergency service on telephone number 116117"</string>

## Suggested Enhancement
If the CWA app determines that the user is recommended to get tested for Corona, due to an increased risk assessment, then it should:
- open the 116117.app if installed, so that the user can start the process to get a test appointment
- if the 116117.app is not installed, advise the user that the app is available in addition to the phone number 116117

[116117.app on App Store](https://apps.apple.com/de/app/116117-app/id1465237675) for Apple iOS
[116117.app on Google Play Store](https://play.google.com/store/apps/details?id=de.kvdigital.nfa) for Android

The above store download links are advertised on the website [www.116117.de](https://www.116117.de/de/index.php) website 

The 116117.app has a special button for Corona Test.
![116117app_Main](https://user-images.githubusercontent.com/66998419/103515577-4885d980-4e6f-11eb-9326-7ebc2da02095.jpg)

---
![116117app_Terminbuchung](https://user-images.githubusercontent.com/66998419/103515588-4c196080-4e6f-11eb-903c-0f49008dea4b.jpg)

## Expected Benefits
Telephone Hotlines routed to human operators suffer the problem of scalability. Increased call volumes lead to increased waiting times. Offering the alternative to a telephone conversation through a semi-automated IT process started via app should speed up arranging a test appointment and offload busy call-centers. This should be an important aspect with high case numbers.

## Related discussions
- "Missing mention of 116117 app and website for Corona Test" https://github.com/corona-warn-app/cwa-website/issues/751

Edit: Links to 
o www.116117.de
o [116117.app on App Store](https://apps.apple.com/de/app/116117-app/id1465237675) 
o [116117.app on Google Play Store](https://play.google.com/store/apps/details?id=de.kvdigital.nfa)
have now been added to the FAQ entry https://www.coronawarn.app/en/faq/#encounter_criteria

---
Internal Tracking ID: EXPOSUREAPP-4501

**Comment by heinezen** [comment]
Hello @MikeMcC399 

We have added you feature request to our internal Jira with ticket ID EXPOSUREAPP-4501. It will now be reviewed and discussed by the development team and the RKI. Thank you for the suggestions.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@heinezen 
Changing the title from "Integration" to "Mention" changes the meaning of the suggestion.

I expect there is a higher likelihood of getting "mention" implemented compared to a full integration with the 116117.app, but I still think that integration is a good suggestion.

Thank you once again for the open PR https://github.com/corona-warn-app/cwa-website/pull/752 on the website to get the information posted there!

**Comment by heinezen** [comment]
@MikeMcC399 Ah my apologies, I misread your initial post. I changed it back to the initial meaning and updated the ticket.

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
See also https://github.com/corona-warn-app/cwa-documentation/issues/569.

**Comment by MikeMcC399** [comment]
Withdrawing this enhancement request. It seems that there is no good single place to find out where to get tested independently of the requester's location in Germany. The organization of tests is fragmented by federal state and the http://www.116117.de/ site is only providing a partial answer to this.

The FAQ link https://www.coronawarn.app/en/faq/#where_can_i_get_tested attempts to solve the issue.

This links to 

- https://map.schnelltestportal.de/ and
- https://www.zusammengegencorona.de/testen/?articlefilter=alleartikel

Unfortunately the databases are not well populated. Apparently people have found other ways to locate testing centers in the meantime.
