### ISSUE TITLE
Include local political corona regulations in a retrievable way.

### ISSUE THREAD

**Issue by silviograu** [corona-warn-app/cwa-wishlist#323]
## Feature description

It is somewhat complicated to keep track of the existing corona regulations in different regions and national borders. Even more so if you are not at home in the region, for whatever reason.

## Problem and motivation

It would be good if there was the possibility to deposit texts of regulations or links to the texts of regulations of a certain government, country or other district.

## Is this something you're interested in working on

no

**Comment by Ein-Tim** [comment]
Hey @silviograu 👋🏻

This seems like a duplicate of #151. 
Please monitor this Issue and if necessary follow up there.
Please close this Issue. 

Thank you 👍

**Comment by silviograu** [comment]
Hi @Ein-Tim, thanks!

That's pretty much what I wrote. I am #closing 323 . thanks!

**Comment by MikeMcC399** [comment]
The official app is NINA (Notfall-Informations- und Nachrichten-App) from the Bundesamt für Bevölkerungsschutz und Katastrophenhilfe:
- [NINA English links](https://www.bbk.bund.de/EN/Topics/Crisis_management/Warning/International_Visitors/International_Visitors_start.html)
- [NINA German site](https://www.bbk.bund.de/DE/NINA/Warn-App_NINA_node.html)

There is also https://www.darfichdas.info/ which links into German information sources.
