### ISSUE TITLE
Add links to research surveys

### ISSUE THREAD

**Issue by ChristophGeske** [corona-warn-app/cwa-wishlist#327]
I think the corona warn app would also be the perfect place to give users the ability to participate directly in research projects that help advance research in Covid-19 detection. 

Just one example is the "COVID-19 Detection by Cough and Voice Analysis" where data is collected simply with the smartphone microphone to develop software that can detect early COVID infections using only the phone in your pocket.

One could simply add a new site in the app with links that redirect the users interested to relevant surveys and gives a short explaination what the survey is about.

For example this is the direct link to the "COVID-19 Detection by Cough and Voice Analysis":
https://cdcva.list.lu/

Idealy you would work together with the researchers so the survey gets even better when participants later find out that they tested positive but that is also much more work compared to simply provide users with links to the researchers websites.

----
Internal Tracking ID: EXPOSUREAPP-4527

**Comment by heinezen** [comment]
Hello @ChristophGeske 

Thank you for your suggestion. We have added your feature request to our internal Jira ticketing system (ticket ID: EXPOSUREAPP-4527) where it will now be reviewed by the dvelopers and the RKI. They will decide if and how this  feature would be implemented in the app. We will update you here if we get news about the pogress on the issue.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
related  ticket (EXPOSUREAPP-4637)[https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4637]

**Comment by Ein-Tim** [comment]
Version 1.13 introduced a survey which will be shown to users with high-risk encounters.

More information: 
DE: https://www.coronawarn.app/de/blog/2021-03-04-corona-warn-app-version-1-13/
EN: https://www.coronawarn.app/en/blog/2021-03-04-corona-warn-app-version-1-13/

This isn't exactly what has been proposed by @ChristophGeske, so should be up to you whether you want to close this or not.

**Comment by dsarkar** [comment]
@ChristophGeske Thanks for proposing here. We suggest closing this issue. However, we are very happy to hear and forward new (if possible detailed) suggestions on how to enhance the newly introduced features (as there are event registration (future), data donation, RKI survey). Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
As this was implemented in CWA v1.13, please open new issues regarding enhancements of the feature. We will close this issue.

----
Corona-Warn-App Open Source Team
