### ISSUE TITLE
CoronaWarnApp für iOS 14

### ISSUE THREAD

**Issue by blockiyt** [corona-warn-app/cwa-wishlist#33]
Moin, gestern kam ja das neue iOS raus (habe es mir natürlich direkt geholt also die Beta) nur das Problem ist das iOS 14 auf Xcode 12 arbeitet und die CoronaWarnApp ja in Xcode 11 geschrieben ist (denke ich) und dann schmeißt es mir nur Fehler raus! Es währ ziemlich nice wenn iOS 14 Support bekommen würde. Vielen Dank!

-----
Internal Tracking ID: EXPOSUREAPP-2146

**Comment by tkowark** [comment]
Das eigentliche Problem ist leider, dass das Exposure Notification Framework noch nicht in iOS 14 eingebaut ist:
https://www.coronawarn.app/de/faq/#ios_14_beta

**Comment by blockiyt** [comment]
Mist... Was soll ich dann tun? Soll ich wieder per IPSW downgraden? Was bleiben mir denn für möglichkeiten?

**Comment by blockiyt** [comment]
![image](https://user-images.githubusercontent.com/65811753/85501679-24a32a80-b5e6-11ea-85c4-bc651f4d8939.jpeg)

Habe das gerade gefunden bei den DevDocs  aber warum funktioniert das nicht wenn dort iOS 14 Beta steht ?

**Comment by bastigw** [comment]
Link zu den DevDocs: https://developer.apple.com/documentation/exposurenotification

**Comment by thomasaugsten** [comment]
Die Release Notes zu iOS 14 Beta 1 sind eindeutig:
![image](https://user-images.githubusercontent.com/6367738/85517035-275e4980-b5ff-11ea-8167-bfbd7bf6022c.png)

**Comment by blockiyt** [comment]
Wieso schreibt Apple das dann hin? Also manchmal verstehe ich Apple nicht...

**Comment by jannisg4g** [comment]
Moinsen, ich vermute, dass das daran liegt, dass das Exposure Notification Kit in Absprache mit Behörden läuft und die Freigabe für ein neues iOS noch nicht bestätigt ist. Oder es liegt ein Fehler mit BLE in der iOS 14-DevBeta vor. Es kann alternativ auch daran liegen, dass Dev-Betas allgemein aus Datenschutz-Gründen nicht mit solchen Gesundheitsdaten funktionieren... Mal abwarten, was Public-Beta und weitere Versionen noch so bringen :D

**Comment by tens0rfl0w** [comment]
There shouldn’t be much to change when adopting to iOS 14. But support for Beta software in a production release is really bad practice. I don't think there will be any official support for iOS 14 before GM. (But testing the mock up version, I don't see any problems left when the EN framework will be functional on iOS 14.)

**Comment by blockiyt** [comment]
@tens0rfl0w When do you think the Beta2 is coming?

**Comment by tens0rfl0w** [comment]
@blockiyt Developer Beta 2 is typically released 2-3 weeks after Beta 1.

**Comment by blockiyt** [comment]
Ich hab jetzt die Beta 2 aber leider nicht. Die startet und es kommt ein weißer Bildschirm.

**Comment by tens0rfl0w** [comment]
@blockiyt Sadly there is still no new information about when the ENF will get activated in iOS 14.

**Comment by blockiyt** [comment]
Endlich hat Apple das ENF wieder Aktiviert!
Ich glaube der Thread kann geschlossen werden, oder?

**Comment by Ein-Tim** [comment]
@sonaliDK Da iOS 14 nun released wurde kann dieser Issue geschlossen werden (@mtb77 @svengabr)
