### ISSUE TITLE
Quick access to contact diary

### ISSUE THREAD

**Issue by sebastianries** [corona-warn-app/cwa-wishlist#330]
## Feature description

I would like to see something like the settings widget in android to get directly to the contacts diary.
There it is possible to create a link on the home screen that directs directly to the setting defined.

## Problem and motivation
This would be nice to make it more easy and faster to add a contact you had to the diary without opening the app, scrolling to the diary and selecting the date.
I guess that many people will use this feature more frequent when it is easier to access it.

**Comment by Ein-Tim** [comment]
Hey @sebastianries 👋

Thanks for your proposal, it seems like this is already covered in #295.
Please monitor this Issue and contribute there if necessary.

Thanks and stay healthy!

**Comment by sebastianries** [comment]
Duplicate of #295
