### ISSUE TITLE
Allow pasting of TeleTAN

### ISSUE THREAD

**Issue by moburkhardt** [corona-warn-app/cwa-wishlist#331]
## Current implementation

When entering a Tele Tan it is not possible to past a TAN copied from somewhere.

## Suggested Enhancement

Use prompt to paste copied TeleTAN into entry field.

## Expected Benefits

This will reduce human error and increase convenience.

---
Internal Tracking ID: EXPOSUREAPP-4684

**Comment by Ein-Tim** [comment]
Confirm this. I don't think this is a bug, it is not expected that you can paste it (or @thomasaugsten).

Then this would be something for the CWA-Wishlist.

**Comment by MikeMcC399** [comment]
@moburkhardt 
If you receive a TeleTAN by phone, and this is valid for one hour, why would you want to paste this instead of typing in the TAN by hand?

Could you explain the benefit?

**Comment by Ein-Tim** [comment]
@MikeMcC399 

There is also the "normal" TAN field, the TAN for this you'll get from the laboratory if you are tested positive. If they send you this via Mail/SMS you could paste it into the field. 
But I agree, the title of this issue makes little sense, maybe someone can delete the "Tele" from the title?

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> There is also the "normal" TAN field, the TAN for this you'll get from the laboratory if you are tested positive. If they send you this via Mail/SMS you could paste it into the field.

Could you explain a bit more about TANs for CWA being sent by Mail/SMS? That is new to me. 

I can't see any description of this in the [Solution Architecture](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md) where TANs are described as short-lived (https://www.coronawarn.app/en/faq/#test_multiple_devices mentions one hour life).

**Comment by Ein-Tim** [comment]
@MikeMcC399 sure thing.

Inside of the [test result box](https://user-images.githubusercontent.com/67682506/104705068-bd7fcb80-5719-11eb-9be4-9c97f1a48ec8.jpg) you can find the option "[Enter TAN](https://user-images.githubusercontent.com/67682506/104705179-e0aa7b00-5719-11eb-8a7d-d3fc7701facf.jpg)". If you click on this, you can enter a
a) TAN, which you got from the lab (only if you are tested positive)
b) Tele-TAN, which you got from the TAN hotline.

I don't know how long such a TAN, which is given to you by a Lab valid, maybe @thomasaugsten could answer this.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
The Android app only uses the term TAN. It doesn't use the term TeleTAN at all. I don't believe there is such a thing as a lab TAN which can be used in the Corona-Warn-App. Labs may perhaps issue their own TANs or PINs to retrieve test results on their web sites. This would be a different process however.

Perhaps the original author @moburkhardt could explain how and where he received a TAN that he wanted to paste into the Corona-Warn-App? We could then focus on the actual use-case.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Just to clarify, the iOS App also only talks about TAN's. 
Yeah let's wait what he says, but maybe @dsarkar could also ask the responisble people internally?

**Comment by moburkhardt** [comment]
I am referring to the TAN, that you can receive when calling the hotline. This TAN then needs to be entered into the app. It is very feasible that users will write the TAN down and then try to enter it in the app, allowing for copy paste will reduce human error and increase convenience.
![IMG_851E380CE997-1](https://user-images.githubusercontent.com/169051/104879074-7550eb00-595d-11eb-8eff-e286d83ad7d8.jpeg)

**Comment by Ein-Tim** [comment]
Okay, if there is nothing like a laboratory TAN (than I am very sorry for the false information I told you 😕), the only use case for this really is when the user writes the TAN down on his phone, but not directly into CWA but some other app...

**Comment by MikeMcC399** [comment]
@moburkhardt 
Thank you very much for confirming about the background for your request!

If you have a headset attached, so you can see your phone screen when you call the TAN hotline it would be really nice to be able to type in the TAN in real time into the CWA app whilst it is being dictated to you on the phone. I tried to simulate that on my Android Samsung Galaxy phone using split-screen mode (which I think is vendor specific) so I had half the phone showing the dialer and the other half showing the input screen to type in the TAN, but I couldn't get it to work in any useful way.

If there could be some enhancement which works on iOS and Android to allow dialing the TAN hotline and recording the TAN on the same screen, avoiding typing the TAN temporarily into some other app, that would be good. Maybe this should be a separate wishlist item?

**Comment by heinezen** [comment]
Hey @moburkhardt ,

Thanks for the report. I have reformulated your issue to a feature request and added it to our internal Jira ticketing system (ticket ID: EXPOSUREAPP-4684). The devs will discuss your request and we'll notify you once we know more about implementation date or other specifics here on Github.

Best Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@moburkhardt 

With the release [Version 3.0: CWA warnings now possible after positive self-test](https://www.coronawarn.app/en/blog/2023-01-18-cwa-3-0/) TANs are no longer required.

Instead if a user has a positive test they can warn others directly in the app without needing to request a TAN. This means there should no longer be an issue about typing in a TAN because this is not necessary or possible in CWA 3.0.

**Comment by MikeMcC399** [comment]
This wishlist item should be closed now since TANs are no longer used. The TAN hotline closed down today.

**Comment by larswmh** [comment]
Thanks for your wishlist item @moburkhardt, and thanks to all others who participated. 

Due to the aforementioned information provided by @MikeMcC399, I will now close this issue.
