### ISSUE TITLE
Improve Contact Journal usability for editing and deleting entries

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-wishlist#334]
## Current Implementation

In the Contact Journal, in order to edit or delete entries, it is necessary to use the three-dot icon at the top right. (See explanation in https://www.coronawarn.app/en/blog/2020-12-28-corona-warn-app-version-1-10/).

## Suggested Enhancement

The app should be enhanced to use common ways of editing a person or place entry **directly**. For instance:
- tap and hold on an entry to open a selection to edit or delete
- swipe to delete
- add a pencil icon to edit
- add a bin icon to delete

## Expected Benefits

It should be more obvious how to make changes to existing person or place entries in the app's Contact Journal. As shown by the comments in the issue 
- https://github.com/corona-warn-app/cwa-wishlist/issues/856, the implementation in 1.10.1 of the app is not found to be intuitive.

(Note the FAQ https://www.coronawarn.app/en/faq/#contact_diary entry confirming the intention to improve the Contact Journal based on user feedback,)

---
- https://github.com/corona-warn-app/cwa-wishlist/issues/856 is covered with the above proposal.

Please consider also 
- corona-warn-app/cwa-app-android#405 in relation to this wishlist item.

Internal Tracking ID: [EXPOSUREAPP-3034](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3034)
Internal Tracking ID: [EXPOSUREAPP-5495](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5495)

**Comment by ndegendogo** [comment]
@MikeMcC399 Thanks. Your suggestion is even better than [mine](#317).
My main point was, I would like to have all editing (add, modify, delete entries) in one place; which is well fulfilled with your suggestion.

**Comment by fynngodau** [comment]
We at CCTG have also had some people ask us how to edit people / places who did not find the according setting, and our typical user tends to be rather “technophile” ;)

Because of this and also because of my personal feeling how these screens should work, I support this request and would advocate for the edit / delete workflow to be reworked soon.

**Comment by dsarkar** [comment]
@fynngodau @MikeMcC399 On the wishlist pipeline currently considered high priority. 


---
Internal Tracking ID: [EXPOSUREAPP-5495](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5495)

**Comment by MikeMcC399** [comment]
@dsarkar 
> On the wishlist pipeline currently considered high priority.

Thank you for the feedback.

Here a cross-link to Android Edit Person issues, where the keyboard does not always display for editing: https://github.com/corona-warn-app/cwa-app-android/issues/2658

**Comment by MikeMcC399** [comment]
Please consider also https://github.com/corona-warn-app/cwa-wishlist/issues/405 is relation to this wishlist item.

**Comment by MikeMcC399** [comment]
Comments from @WiseWomanVP 

> ... the problem of correcting or deleting an entry is still non-intuitive. Normally you would press long on an entry and shove it left to delete, or just a long press to correct. 

The above suggestions are covered in the original entry https://github.com/corona-warn-app/cwa-wishlist/issues/334

> It is also problematic that the additional data always opens, instead of there being a little plus to open it.

This is a separate item, about hiding data and expanding it when needed. This could be considered for any other usability improvements to the Contact Journal.

**Comment by ElenaA411** [comment]
![Kontakt-Tagebuch](https://user-images.githubusercontent.com/83277372/116520277-d0866800-a8d2-11eb-82d7-2ec5d34859b6.png)

Here you can see my design idea for the contact journal. The funcion to delete or change persons and places is easier to use.
Example and description:
At first you click at the person. In the right up corner ist the button (...). When you click on the button it opens a separate window with the option (bearbeiten) and (löschen).
When you click on (bearbeiten) you can change the (Beschreibung/ Telefon/E-Mail).
When you click on (löschen) it opens a new window (Wollen Sie diese Person wirklich entfernen?) and you can choose if you delete the person (Ja) or not (nein).

What do you think about this?

**Comment by jucktnich** [comment]
I would add an edit menu to the top and if you click it, these little arrows appear, cause I think it's the standard iOS behaviour.

**Comment by MikeMcC399** [comment]
@ElenaA411 
Something like you propose would be good.

@dsarkar 
Do you have any update, since you wrote in https://github.com/corona-warn-app/cwa-wishlist/issues/334#issuecomment-803985209 about one month ago:

> On the wishlist pipeline currently considered high priority.
> 
> Internal Tracking ID: [EXPOSUREAPP-5495](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5495)

**Comment by WiseWomanVP** [comment]
Okay, that would be better for editing.

There is still the problem with the default being the menu for duration being opened. It should be closed unless requested, I find it highy annoying. I don't want to spend time trying to decide the exact time. I also meet people BOTH indoors and outdoors and with and without a mask. I would have one bubble with "..." or a pencil for editing, another bubble with a clock for adding the time.

**Comment by dsarkar** [comment]
@MikeMcC399 No change. In the pipeline as high priority. I understand that new features implementation has still higher priority (e.g. Rapid antigen test integration, error logging).

**Comment by ElenaA411** [comment]
>No change. In the pipeline as high priority. I understand that new features implementation has still higher priority (e.g. Rapid antigen test integration, error logging).

@dsarkar What do you think about my mockup https://github.com/corona-warn-app/cwa-wishlist/issues/334#issuecomment-829048211? And what do you mean with "no change"? Isn't it possible to change?

**Comment by dsarkar** [comment]
Hi @ElenaA411 see https://github.com/corona-warn-app/cwa-wishlist/issues/334#issuecomment-829104633, I explain better hopefully. 

I will forward you mockup into the internal ticket, so management / developers can have a look at it. Many thanks. 


---
Corona-Warn-App Open Source Team

**Comment by ndegendogo** [comment]
@dsarkar @heinezen what is the status of the discussion for an improved user interface for the contact diary?
I am talking of this ticket, with its really great ideas, as well as of [this proposal](https://github.com/corona-warn-app/cwa-app-ios/issues/2196) over in the iOS repo.

I understand that the very first version of the contact diary was implemented as a "minimum viable product". Especially to get feedback from the users and the community. But unfortunately, since then there was not much progress....

What are the reasons? Are such improvements really "undesired", or is it rather a question of priorities?
Assuming the latter: would it be an option to involve the community here?

*I am sure that we community are able to cover both platforms (iOS and Android)*

**Comment by MikeMcC399** [comment]
@dsarkar 

This request has been open for almost one year and at one point you said it was a high priority item to improve the usability of the Contact Journal for editing and deleting entries.

Could you please enquire about whether it can be addressed soon?

Thank you for working together in the meantime to get an FAQ article published:

- [How can I edit or delete entries from the Contact Journal?](https://www.coronawarn.app/en/faq/#contact_diary_edit)
- [Wie kann ich Einträge im Kontakt-Tagebuch bearbeiten oder löschen?](https://www.coronawarn.app/de/faq/#contact_diary_edit)
