### ISSUE TITLE
[Overview] Statistics

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-wishlist#335]
- [Discussion about the app's efficiency | Diskussion über die Effizienz der App #150](https://github.com/corona-warn-app/cwa-wishlist/issues/150)
- [Informative logging results to be available in app #5](https://github.com/corona-warn-app/cwa-wishlist/issues/5) - EXPOSUREAPP-2136
- [Provide an official interactive CWA dashboard with daily data (incl. data download) #236](https://github.com/corona-warn-app/cwa-wishlist/issues/236)  - [EXPOSUREAPP-3674](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3674)
- [Publish package download counts #117](https://github.com/corona-warn-app/cwa-wishlist/issues/117) - EXPOSUREAPP-2060
- [success statistics for CWA and bluetooth calibration #139](https://github.com/corona-warn-app/cwa-wishlist/issues/139) - EXPOSUREAPP-2033
- PR https://github.com/corona-warn-app/cwa-app-ios/pull/1807 
- PR https://github.com/corona-warn-app/cwa-app-android/pull/2043

**Comment by dsarkar** [comment]
@Ein-Tim If you would like to participate in maintaining this overview, open a new issue and I will past into your issue the current overview. If so done I will close this issue. ;-)

**Comment by Ein-Tim** [comment]
Will do. Thx 👍
