### ISSUE TITLE
[Overview] Issues reg. Statistics & Gamification

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#336]
**This is an overview over all open Issues regarding statistics & gamification** (to keep track and avoid duplicates).

## Statistics

| Issue | Title | Status | JIRA |
| --- | --- | --- | --- |
| #5 | Informative logging results to be available in app | **OPEN** | [EXPOSUREAPP-2136](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-2136) |
| #117 | Publish package download counts | **OPEN** | [EXPOSUREAPP-2060](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-2060) |
| #139 | Success statistics for CWA and bluetooth calibration | **OPEN** | [EXPOSUREAPP-2033](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-2033) |
| #152 | Discovery Metrics | **OPEN** | [EXPOSUREAPP-2158](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-2158) |  |
| #205 | Personal risk monitor graph | **OPEN** | [EXPOSUREAPP-5018](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5018) |
| #358 | Move statistics page to a submenu | **OPEN** | [EXPOSUREAPP-5018](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5018) |
| #359 | Inzidenz widget | **OPEN** | [EXPOSUREAPP-5018](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5018) |
| #579 | add graphs for incidence/R-Value | **OPEN** | [EXPOSUREAPP-8289](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8289) |
| #605 | Function to make local incidences sortable | **OPEN** | [EXPOSUREAPP-8998](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8998) |
| #620 | Explain adding of local incidence card | **OPEN** | [EXPOSUREAPP-8999](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8999) | 
| #630 | Visuelle Darstellung von Inzidenzen pro Altersgruppe | **OPEN** | [EXPOSUREAPP-11566](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11566) |
| #673 | "Hospitalisation" infocard should use adjusted values | **OPEN** | [EXPOSUREAPP-13340](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13340) | 
| #729 | overview of vaccinated and recovered counts - what is the 2G state in percent | **OPEN** | [EXPOSUREAPP-11568](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11568) |

## Gamification

| Issue | Title | Status | JIRA |
| --- | --- | --- | --- |
| #409 | "Success" Badges and other motivational issues | **OPEN** | [EXPOSUREAPP-6161](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6161) |

This overview was last updated on 21.02.2023 (dd.mm.yyyy).

---

Internal Tracking ID: [EXPOSUREAPP-5018](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5018)

**Comment by dsarkar** [comment]
https://github.com/corona-warn-app/cwa-wishlist/issues/152

**Comment by dsarkar** [comment]
https://github.com/corona-warn-app/cwa-wishlist/issues/248

**Comment by Ein-Tim** [comment]
Will add

**Comment by dsarkar** [comment]
ok, i will delete later all these comments after being added. nice to add for example https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Archiv_Kennzahlen/Kennzahlen_11122020.pdf?__blob=publicationFile

**Comment by dsarkar** [comment]
https://github.com/corona-warn-app/cwa-wishlist/issues/303

**Comment by Ein-Tim** [comment]
Not really about statistics

**Comment by Ein-Tim** [comment]
>nice to add for example rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Archiv_Kennzahlen/Kennzahlen_11122020.pdf?__blob=publicationFile

Added Link to blog: https://www.coronawarn.app/en/blog/2020-12-18-facts-and-figures/

**Comment by Ein-Tim** [comment]
You can delete the comments now. Thanks again! ❤

**Comment by dsarkar** [comment]
@Ein-Tim 
EN BLOG 25 Jan 2010 https://www.coronawarn.app/en/blog/2021-01-25-corona-warn-app-version-1-11-teaser/
DE BLOG 25 Jan 2010 https://www.coronawarn.app/de/blog/2021-01-25-corona-warn-app-version-1-11-teaser/

**Comment by Ein-Tim** [comment]
@dsarkar 

Added to the Issue. Will delete this comment as soon as you delete yours. Thanks 👍

**Comment by ndegendogo** [comment]
> Some statistics can already be found [here], on the official Website of the Corona-Warn-App.

@Ein-Tim your link to the cwa website in your last sentence of your description seems broken - I got a 404

**Comment by Ein-Tim** [comment]
@ndegendogo 

Thanks, fixed

**Comment by MikeMcC399** [comment]
There is not a persistent link to the latest statistics on  https://www.coronawarn.app. The link is changed every time a new report is published. The next higher level link is https://www.coronawarn.app/en/blog/.

RKI does however maintain a persistent link at
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Archiv_Kennzahlen/WarnApp_KennzahlenTab.html
and this is the original source of data. I don't know why https://www.coronawarn.app/en/blog/ copies the data from RKI and republishes it instead of just linking to the RKI source. It causes a lag and invalidates the previous link every time it is done.

(Perhaps it could be the subject of an enhancement request on the https://www.coronawarn.app site to make it more maintainable?)

**Comment by Ein-Tim** [comment]
I know that the link changes with every update of the blog post, however I will leave the link to the CWA website until the statistics are published in the app. After the statistics are in the App we would have to decide which above mentioned Issues can be closed and if this overview should stay open.

**Comment by Ein-Tim** [comment]
@dsarkar (or @heinezen) I propose that you add a `statistics` label to issues here in the Wishlist which are proposing to add more statistics (i.e.: #351 & #353).

**Comment by Ein-Tim** [comment]
As [CWA development is ending](https://www.coronawarn.app/en/faq/results/#ramp_down), I'm discontinuing this overview.
