### ISSUE TITLE
[Overview] Issues reg. Event Registration

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#338]
**This is an overview over all open issues regarding the event registration** (to keep track and avoid duplicates).

| Issue | Title | Status | JIRA
| --- | --- | --- | --- |
| #406 | Check in with NFC | **OPEN** | [EXPOSUREAPP-5922](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5922) |
| #413 | Auto-Switching QR-Code Display | **OPEN** | [EXPOSUREAPP-6087](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6087) |
| #443 | CWA-QR-Code-Checkin feature should also work on older devices | **OPEN** | [EXPOSUREAPP-6359](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6359) |
| #444 | Individual QR-Codes for check in | **OPEN** | [EXPOSUREAPP-6383](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6383) |
| #447 | Expiring check in qr codes | **OPEN** | [EXPOSUREAPP-6087](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6087) |
| #458 | Full-screen QR code view | **OPEN** | [EXPOSUREAPP-6542](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6542) |
| #461 | Display date of QR code generation | **OPEN** | [EXPOSUREAPP-6546](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6546) |
| #462 | Increase size of event metadata on print template | **OPEN** | [EXPOSUREAPP-6548](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6548) |
| #469 | Remove event tile on main screen | **OPEN** | [EXPOSUREAPP-6617](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6617) |
| #473 | [2.0] Event Registration - User Guide | **OPEN** | [EXPOSUREAPP-5881](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5881) |
| #481 | Warn when trying to create an event with a start date after the end date | **OPEN** | [EXPOSUREAPP-6760](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6760) | |
| #482 | Better warning when deleting an event registration QR code | **OPEN** | [EXPOSUREAPP-6752](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6752) |
| #484 | Create an asset for a button to check in via an app (probably an App Clip) | **OPEN** | not mirrored |
| #485 | Generating QR code Payload in C/C++ | **OPEN** | [EXPOSUREAPP-6746](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6746) |
| #496 | Add location type(s) for public transportation to the event tracking functionality | **OPEN** | [EXPOSUREAPP-7020](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7020) | |
| #497 | Provide both timestamps for risk calculation by EnsExposureDetection and by PtExposureDetection | **OPEN** | [EXPOSUREAPP-7218](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7218) |
| #519 | Flyer for motivating the use of the CWA for check-ins. | **OPEN** | [EXPOSUREAPP-7275](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7275) |
| #640 | Add possibility to add subgroups for checkin codes | **OPEN** | not mirrored |
| #653 | Usability while being checked in | **OPEN** | not mirrored |
| #679 | Luca QR:  Replace undefined parameters from Check In  with useful Defaults  | **OPEN** | [EXPOSUREAPP-10669](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10669) |
| #680 | Dedicated Message when Scanning Luca QR-Code which has no CWA Data Extension | **OPEN** | [EXPOSUREAPP-10564](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10564) |
| #689 | Creating automatic generic server users that connects Luca App and CWA events | **OPEN** | not mirrored |
| #690 | [CWA vs. Luca]: Promotion of the CWAs "Check-in" functionality ... | **OPEN** | not mirrored |
| #713 | Check-In / -Scan: Suggestion for functional expansion and flexibility ... | **OPEN** | [EXPOSUREAPP-11342](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11342) |
| #719 | Allow to share URL when creating QR code | **OPEN** | not mirrored |
| #744 | Increase maximum value of "Aufenthaltsdauer" (length of stay) from currently 24 hours to the lenght of the event (may be several days)  | **OPEN** | [EXPOSUREAPP-11161](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11161) |

This overview was last updated on 21.02.2023 (dd.mm.yyyy).

---

Internal tracking ID: [EXPOSUREAPP-5117](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5117)

**Comment by Ein-Tim** [comment]
Please delete this comment afterwards:
@dsarkar I am thinking about pasting all Overviews into one (which could be pinned then). 
This would help so that we don't need a overview over the overviews.😅
What do you think?

**Comment by dsarkar** [comment]
Hm, yeah, also had this thought. Both approaches have their advantages. One cleaner, the other one, all in one place. Lets use the overview of overview as index and pin it for the moment. Maybe this works for everybody. 

One good reason is:
For the developers it is probably more convenient to see only one topic.

**Comment by Ein-Tim** [comment]
Okay, will delete my comments now

**Comment by dsarkar** [comment]
@Ein-Tim ok, i will delete mine, you delete yours, looks cleaner. Thanks !

**Comment by Ein-Tim** [comment]
@dsarkar 

Will we see a venue registration in any form in version 1.16?

**Comment by dsarkar** [comment]
@Ein-Tim It is being discussed internally. This label is just an indicator that we might expect seeing something like that, but should not create false expectations, since here we are talking on that larger time-frame.

**Comment by dsarkar** [comment]
FYI https://github.com/corona-warn-app/cwa-app-android/pull/2456

**Comment by MikeMcC399** [comment]
There have been multiple articles published in the press (see https://www.google.com/search?q=corona-warn-app+check-in) regarding the planned new feature of Check-In in version 2.0 of CWA.

**Comment by ChrisLoes** [comment]
is there any overview, which of this features will be implemented and when it will be released?

**Comment by Ein-Tim** [comment]
@ChrisLoes 

There is an overview over the planned features of version 2 here: 
https://github.com/corona-warn-app/cwa-documentation/issues/544

In this issue the last column says for which version the function is planned / in which version the function has been released. 

SAP (who developes the CWA) doesn't share any release dates at all with the community.

**Comment by ChrisLoes** [comment]
Tanks @Ein-Tim

**Comment by ChrisLoes** [comment]
Thanks @Ein-Tim !

**Comment by MasterEmit** [comment]
Is it possible to get a bit speed on it? Version 2.0 is needed! Now! Berlin is enforcing owners of stores to use LucaApp starting from Wednesday, 31st of March 2021. Of course they do not say that LucaApp has to be used but there is no alternative matching the upcoming regulation. So version 2.0 is needed starting tomorrow :-(

**Comment by MikeMcC399** [comment]
@MasterEmit 
> Is it possible to get a bit speed on it? Version 2.0 is needed! Now! Berlin is enforcing owners of stores to use LucaApp starting from Wednesday, 31st of March 2021. Of course they do not say that LucaApp has to be used but there is no alternative matching the upcoming regulation. So version 2.0 is needed starting tomorrow :-(

Do you have a link describing the new regulations in Berlin?

The [Luca App](https://www.luca-app.de/) and the planned [Event Registration](https://github.com/corona-warn-app/cwa-documentation/blob/master/event_registration.md) in the CWA app are not the same. Luca asks for your contact data before you can use it. The planned functionality for CWA on the other hand does not ask for any contact data.

There is an article in https://www.tagesschau.de/inland/corona-warn-app-check-in-101.html today describing the differences. It also says that CWA 2.0 will be released on April 16, 2021.

**Comment by Ein-Tim** [comment]
You can view the work of the devs in the Release 2.0.x branch:

https://github.com/corona-warn-app/cwa-app-ios/tree/release/2.0.x
https://github.com/corona-warn-app/cwa-app-android/tree/release/2.0.x

**Comment by MasterEmit** [comment]
@MikeMcC399 

> Do you have a link describing the new regulations in Berlin?

Sure:

https://www.berlin.de/rbmskzl/aktuelles/pressemitteilungen/2021/pressemitteilung.1069916.php

> Um eine bessere Kontaktnachverfolgung zu ermöglichen und so Infektionsketten zu durchbrechen, appelliert der Senat an Dienstleister*innen und Gewerbetreibende sowie weitere Einrichtungen mit Publikumsverkehr verfügbare digitale Angebote wie die sogenannte Luca-App nutzen. Für den Einzelhandel mit Ausnahme der Grundversorgung wird dies verbindlich vorgeschrieben. 

https://www.gesundheitsstadt-berlin.de/ab-mittwoch-gelten-in-berlin-neue-corona-regeln-15058/
https://www.hwk-berlin.de/corona

So from my understanding any store has to offer a digital solution. I created my own simple form at my own server with an automatic deletion process and present a QRCode with the URL to this form. Not perfect, but better than anything else until the CWA update can be used. After the CWA update is public I will delete this "solution" again. What I will not use is a centralized solution for all locations in Germany.

**Comment by MasterEmit** [comment]
@Ein-Tim 

> You can view the work of the devs in the release/2.0.x branch:

I Know :-) . I check these entries almost every second day ;-)

**Comment by Ein-Tim** [comment]
As [CWA development is ending](https://www.coronawarn.app/en/faq/results/#ramp_down), I'm discontinuing this overview.
