### ISSUE TITLE
Check network status before scanning QR code or asking for TAN

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-wishlist#342]
## Avoid duplicates
* [X] This enhancement request has not already been raised before
Related to https://github.com/corona-warn-app/cwa-app-android/issues/2062#issuecomment-757548295
* [ ] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

First reported on Android app version: 1.10.1
Reviewed for accuracy on Android app version: release/2.12.x

If there is no Internet connection after scanning a test QR code from a test or after inputting a TAN the error message:

"**Error**
Your Internet connection may have been lost. Please ensure that you are connected to the Internet" 

is displayed. The connection is however not checked **before** the scan is started or the TAN is input.

## Suggested Enhancement

A check for an active network connection should be made **before** requesting the user to scan a test QR code or **before** requesting the input of a TAN. If there is no network connection, then the user should be informed that a network connection is necessary to register a QR code or TAN. There is no store-and-forward mechanism which allows either a QR code or TAN to be input and later transferred to a server for registration. (See also documentation issue "Privacy notice incorrect description scanning QR code with no internet" https://github.com/corona-warn-app/cwa-documentation/issues/510.)

A network check should be done:
- after tapping on "Scan QR Code", followed by ACCEPT and before "Position the QR code in the frame" and 
- immediately after tapping on "Enter TAN".

~~In PR "Improved popup text for state "non internet" (EXPOSUREAPP-4569)" https://github.com/corona-warn-app/cwa-app-android/pull/2177 related to https://github.com/corona-warn-app/cwa-app-android/issues/2062 there is a proposal to change the error message to "Möglicherweise wurde Ihre Internet-Verbindung unterbrochen. Bitte stellen Sie sicher, dass Sie mit dem Internet verbunden sind." in the [release/1.12.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/1.12.x) branch. (Presumably also pending translation to other languages).~~ https://github.com/corona-warn-app/cwa-app-android/pull/2177 was merged and the change released in 1.12.0.

## Expected Benefits

If the action of scanning a QR code or forwarding a TAN to a server is not going to be possible because there is no active Internet connection, the user should be told this as soon as possible in the sequence. Warning early saves the disappointment of going through a scan sequence or inputting 10 digits into the UI only to be told that the action was not possible due to something that could have been foreseen earlier.

---
Internal Tracking ID: [EXPOSUREAPP-4719](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4719) obsolete
Internal Tracking ID: [EXPOSUREAPP-4406](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4406)

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-4674](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4719)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for the suggestion. JIRA ticket is created. As usual, feedback will be given here. Best, DS

**Comment by dsarkar** [comment]
The issue will addressed in EXPOSUREAPP-4406.

**Comment by MikeMcC399** [comment]
If Universal QR Code Scanning is implemented in 2.11.x then it will be difficult to know before scanning whether an Internet connection is necessary or not, because that depends on the type of QR code being scanned.

Getting a TAN accepted on the other hand always requires an Internet connection, so the presence of an active Internet connection should be checked before asking the user to enter a TAN manually.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks, I will forward your comment.

**Comment by MikeMcC399** [comment]
Closing this request because the Universal QR Code Scanning can be used to scan QR codes which do not need an internet connection.

In the case of TAN input, if there is no Internet connection, the user may be able to activate a connection without leaving the TAN dialog, and then it is not necessary to input the TAN again.
