### ISSUE TITLE
Explain steps to use interoperability service [for selected countries] (EFGS) to user

### ISSUE THREAD

**Issue by 86x** [corona-warn-app/cwa-wishlist#344]
## Current Implementation
In [cwa-documentation/blob/master/solution_architecture.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#cross-border-interoperability) the last line reads "_In order for the EFGS to function correctly, **all users must specify their visited countries correctly** (either manually or automatically)._"

The only option I've been able to find for this is activating the so called "_travel status sharing_" through the **OS settings**, not the app directly. However, as you can see in the screenshot, it says that this feature is currently not used in the Corona-Warn-App. 

(See screenshots below, or: On iOS open "Settings" app, choose "Corona-Warn", then "Exposure Notifications", scroll all the way to the bottom and you'll find an option to share your travel status, which seems to be disabled by default.)
![IMG_8526](https://user-images.githubusercontent.com/75100597/105492670-90529080-5cb8-11eb-99a6-1f99621c6f4c.PNG)

## Suggested Enhancement
1. Provide an **explaination** to user on how to enable interoperability for _certain countries._
2. Also provide an option for the user to specify visited countries **manually**, as stated in the cwa-documentation.
3. Show a list of "active" countries the user's app is _**really**_ sharing diagnosis keys with.

## Expected Benefits
More clarity to user.
People will no longer think that their diagnosis keys are shared with all participating EU-countries, but rather know which countries' diagnosis keys they are actually downloading or uploading their own diagnosis keys to.

**Comment by Ein-Tim** [comment]
Hey @86x 👋

>The only option I've been able to find for this is activating the so called "travel status sharing" through the OS settings, not the app directly. However, as you can see in the screenshot, it says that this feature is currently not used in the Corona-Warn-App.

I see that you already found out that this switch is currently not used. I will still link to [this](https://github.com/corona-warn-app/cwa-app-ios/issues/1136) Issue, I opened back when this switch was introduced with iOS 13.7.

> 1. Provide an explaination to user on how to enable interoperability for certain countries.
> 2. Also provide an option for the user to specify visited countries manually, as stated in the cwa-documentation.

The EFGS can be operated in 3 modes, you can find them [here](https://news.sap.com/2020/10/eu-corona-gateway-live/):

1. **One Europe**: All diagnostic keys from all participating countries are distributed via the national and European gateway to all app users from all participating countries.
2. **Traveler**: On the devices of travelers, travelers download the diagnostic keys of all participating countries. On the devices of non-travelers, domestic users download not only the domestic diagnostic keys but also the keys of all people traveling.
3. **Country of Interest**: Diagnostic keys of travelers are shared, in addition to the country of residence, only with selected and relevant countries.

CWA is currently using the "One Europe"-mode. As you can see, for this mode, it is not necessary that the user specifies any countries. All countries are shown inside off the Corona-Warn-App, please see [this](https://www.coronawarn.app/de/faq/#interoperability_countries) FAQ entry for an explanation how to see them.


> 3. Show a list of "active" countries the user's app is really sharing diagnosis keys with.

As stated above, there is [this](https://www.coronawarn.app/de/faq/#interoperability_countries) FAQ article showing a list of all countries the app is sharing diagnosis keys with. As said above (too) you can also view a list in the App itself.

**Comment by 86x** [comment]
Thank you @Ein-Tim for your answer and a **huge** thanks for providing sources!

> CWA is currently using the "One Europe"-mode ([Source](https://www.coronawarn.app/en/blog/2020-10-19-version-1-5/)). 

That's also the behaviour I've expected from reading the whole chapter "Cross-border interoperability", _except_ from the mentioned _last_ sentence. 

- Maybe this line should be **removed** from the _cwa-documentation_ 
- and/or the three modes and the fact that the german app uses the "One Europe" mode should be **included** in the documentation to make this more clear. 

Again, thank you for your answer.

**Comment by Ein-Tim** [comment]
@86x I opened https://github.com/corona-warn-app/cwa-documentation/issues/514.

If you are happy with the answer here, please close this Issue. Thanks.

Stay safe and healthy!

**Comment by MikeMcC399** [comment]
@86x / @Ein-Tim 
The disabled option "Reisestatus teilen" in iOS is not even shown in Android Google Exposure Notification System.

Does Apple document this user interface on any website?

Unfortunately Google has not documented their UI publicly, so we only have reverse engineering available to us.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

> The disabled option "Reisestatus teilen" in iOS is not even shown in Android Google Exposure Notification System.

According to @thomasaugsten this is can be used after a EN-App asked you to share the traveler status, you agreed, and then afterwards want to change the setting. 

>Does Apple document this user interface on any website?

AFAIK no. 
The only (official) documentation from Apple can be found here: https://developer.apple.com/documentation/exposurenotification
