### ISSUE TITLE
Connect the Corona test center in Munich (Theresienwiese) to the Corona-Warn-App System

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#346]
## Current Implementation
Currently the COVID-19 test center in Munich, located on the Theresienwiese, seems to be not connected to the CWA infrastructure. If you are tested there, you get a sheet of paper and the number of your test to find out your test result on https://www.doctorbox.de/covid19.jsp.
A QR-Code for CWA is never issued. 

## Suggested Enhancement
Connect the lab/test center to the CWA infrastructure so that users of the Corona-Warn-App can get the test result in the App. 

## Expected Benefits
More people who got tested there and their test came back positive will be (more easily) able to share the test result.

## Additional Information

I thought about sending an e-mail to corona-warn-app.opensource@sap.com but decided against it since this is not about i.e. that one test result wasn't delivered to the app or similar, it's a more general problem.

The website of the test center is: https://www.corona-testung.de/ (German only).
I will ping @GisoSchroederSAP here since it seems like he is responsible for such things.

**Comment by dsarkar** [comment]
@Ein-Tim 

Thanks, I forwarded the info internally.

**Comment by dsarkar** [comment]
@Ein-Tim Update: They are aware of that specific case and working on it.

**Comment by achisto** [comment]
@dsarkar is there a centralized place to report cases like this? I know of two test centres which are also not connected to the CWA infrastructure.

**Comment by MikeMcC399** [comment]
@achisto 
There is a dedicated issue for this on "Connectivity to laboratories / Transfer of QR code / QR code not working" https://github.com/corona-warn-app/cwa-documentation/issues/400

The e-mail address corona-warn-app.opensource@sap.com has also been published for feedback on QR code issues.

**Comment by dsarkar** [comment]
@achisto 

This is the text the user will get in the AppStores regarding lab connectivity issues:


> Vielen Dank für Ihr Feedback. Die automatische Benachrichtigung für das Testergebnis nach Registrierung des QR-Codes funktioniert noch nicht reibungslos. Sofern Sie nach einem Corona-Test Ihren QR-Code in die App eingescannt haben und innerhalb von wenigen Tagen kein Testergebnis über die App mitgeteilt bekommen, rufen Sie bitte beim zuständigen ärztlichen Fachpersonal bzw. Testcenter/Gesundheitsamt an, um Ihr Testergebnis zu erhalten. Mit einem positiven Testergebnis erhalten Sie über die Hotline (0800 7540002) eine teleTAN (gültig für 1 Stunde), mit deren Hilfe Sie das positive Testergebnis dennoch in die App eintragen können. Um die Labore lückenlos anzubinden und die Benachrichtigung des Testergebnisses durch die Warn-App sicherzustellen, möchten wir Sie bitten, folgende Informationen an corona-warn-app.opensource@sap.com zu senden: Datum, Arzt, Labor (falls bekannt), Mobilfunkanbieter, Schwierigkeiten beim Scan des QR-Codes etc. und die Information, ob Sie eine Einverständniserklärung zur Übertragung des Ergebnisses an die App gegeben haben. Je mehr Informationen wir erhalten, desto besser können wir diesen Prozess korrigieren und die Qualität der Corona-Warn-App weiter verbessern.

So, yes, corona-warn-app.opensource@sap.com is the best option I think. It might take a while, but my understanding is that they will look into every single case and answer you. 

Thank you for reporting!

**Comment by ndegendogo** [comment]
> So, yes, corona-warn-app.opensource@sap.com is the best option I think. It might take a while, but my understanding is that they will look into every single case and answer you.

@achisto I can confirm that this is a good email. I recently used it for a similar issue. I got immediate reply from a robot, but shortly after this (I think even the same day) I got a nice reply and feedback. And I am sure they collect and apppreciate all kind of informations that helps them to address this issues and to improve integration of labs and test centers with cwa.

**Comment by Ein-Tim** [comment]
@dsarkar 

> They are aware of that specific case and working on it.

Please keep us (me) in the loop, since I don't get tested every day I can not confirm when they are connected 😉
Thanks! 🙂

**Comment by GisoSchroederSAP** [comment]
All,
please note, we follow up on every single case of known process disruption during the Corona testing. This includes delayed and even missing test results in the app. Meanwhile, based on multiple hundreds of investigated issues we found more than 20 reasons that lead to disappointment of users (and of our team as well). The missing technical connection of a lab to the CWA infrastructure is only one of those 20+ root causes.
However, following up each and every single case allows us to "cluster" the issues and to work on strategies to resolve the one or the other cluster. Additionally, we are currently enhance the process monitoring capabilities to get informed as early as possible if the process chain between test registration (scan) and delivery of result (into the app) gets stuck.

For the initial case: Munich Theresienwiese is a big player performing the Corona tests with at least two labs. Unfortunately, it seems the rich southern German federal states have high medial visibility and but low impact to make the lab facilities supporting the CWA. A big facility chain, with locations in Konstanz, Erlangen, Gelsenkirchen, Ebersberg and Munich still ha no major interest in extra effort to support the CWA test result process. Instead, users get redirected to other websites (like doktorbox.de or mein-laborergebnis.de). 

We are still trying to continue to evaluate the recurring cases and to fix them.

**Comment by ndegendogo** [comment]
> Unfortunately, it seems the rich southern German federal states have high medial visibility and but low impact to make the lab facilities supporting the CWA. 

@GisoSchroederSAP I suggest that you discuss these topics with our Bavarian minister of health, and convince him of the strategic importance of cwa and of the seamless integration of cwa with test center and labs infrastructure *(and maybe you are already in this discussion)* 😀

Here in the rich South, we have setup very good and low-threshold testing services for everybody, **and we are proud of this**. I remember a comment of a not-so-lucky cwa user living in the North, who was eagerly waiting for his red cwa warning so that he could get a test. Here in my county I don't need to wait; I just show up at the test center, self-registrate, and get the test. The process is fully digitized and fast; I got my result after only 15 hours via password-protected email. This is the fastest possible, **cwa just cannot speed this up**.

But the part which is indeed disrupted is **not** the delivery of test result to the user, but feeding a positive result back into cwa infrastructure and warning others.
This is what you need to use as arguments. Instead of just pressing a few buttons, the user must call an overloaded hotline to get the TeleTAN (and maybe not everybody knows this, or they don't take the time, or ... - *you are better aware than me of the shortcomings of this TeleTAN path*).

**Comment by GisoSchroederSAP** [comment]
Yes, we are aware, that there are various spots where we need to pay extra attention. 
Together with RKI we also created this [picture](https://www.coronawarn.app/assets/documents/BPA_Corona-Warn-App_RKI-Plakat_Testcenter_A1_ICv2_RZ04_x3b.pdf) that explains the behavior quite user-friendly (and has sufficient resolution to get printed as a banner or poster).
However, our observation also is, that there are some cases where the test result *is* delivered at a certain day, but it appears in the app up to 5 days later. Strange, so we need to investigate there as well.  Those delays are unacceptable, from the user perspective and as well from our perspective.

**Comment by ndegendogo** [comment]
@GisoSchroederSAP actually, I saw your poster at my local test center when I showed up last week for a test 😀 and I wanted even to take a photo 😀 but I saw it too late and the waiting line was very short and there was no time 😀

So my local test center is meanwhile integrated with cwa (and it is **not** Theresienwiese).

Still I would like to give feedback on the part of the process / data flow that was most diruptive in my case.

The process at my local test center is **fully digitized**, even the cwa QR code I got via email as link to a website where it was shown as png.

**But cwa wants to *scan* it; so I need either a printer or a second device**.

See also suggestions for improvements #227, #302, and #389

**Comment by Ein-Tim** [comment]
A Twitter user [told me](https://twitter.com/golemiker/status/1399121458266259457?s=21) that he had a PCR test done at the test center on the Theresienwiese and he got his test result via the Corona-Warn-App. 
So it seems like that the test center is now connected to the CWA infrastructure. 
@GisoSchroederSAP Could you maybe cross check this, please?

**Comment by GisoSchroederSAP** [comment]
Unfortunately, I am not able to cross-check. However, Theresienwiese will be served by one of the labs of the Eurofins group. As far as we are informed, all labs of this group in Germany deliver their PCR test results into one central location (Konstanz), that finally consolidates the data and is connected since February to the CWA infrastructure. After initial difficulties with the technical setup and reliable data exchange it should work now continuously.

**Comment by Ein-Tim** [comment]
@GisoSchroederSAP Thank you, so I am closing this issue now because it seems like they are connected to the CWA System now. I'll cross check the next time I do a PCR test there. 

Closing as implemented.

**Comment by GisoSchroederSAP** [comment]
I'm totally aware of the difficulties that come with the **fulli-digitalized** process, where you don't even get something to scan, but just a link to a QR code or an email carrying a QR code.
We addressed this topic already multiple times. There is a slight chance, it becomes added _**if**_ (and only if) we are permitted to go for a face-lifting of the app. Main objective is to optimize the user experience, to streamline navigation and to make the UI more consistent on the way it works.

**Comment by Ein-Tim** [comment]
@GisoSchroederSAP I assume you wanted to comment in #389 or was this comment intended to be in this thread?

**Comment by GisoSchroederSAP** [comment]
Unfortunately, I am old and was too slow when you closed this ticket. 
As @ndegendogo mentioned this issue here above, this response should stay here, but certainly also matches #389. Shall I copy/paste it there as well - or will you just link my comment into the other ticket?

**Comment by Ein-Tim** [comment]
@GisoSchroederSAP 

I'll link to your comment. Thanks for the update!
