### ISSUE TITLE
Mark an infected person as recovered

### ISSUE THREAD

**Issue by bigbug** [corona-warn-app/cwa-wishlist#347]
## Feature description

There should be a button on the front screen to mark one as recovered/healthy again - or make it automatically 14 days after the positive test.

## Problem and motivation
Once you have been infected (and testes positive) the app stays in a state, where it says the Gesundheitsamt will contact you. This is still the case after weeks when you are already healthy again. Burried deep in the FAQs there is an instruction on how to reset the app. This is not a good user experience for people using the app.
[https://www.coronawarn.app/de/faq/#recovered](https://www.coronawarn.app/de/faq/#recovered)
At the moment it seems that the app gets useless for people which have been positively tested. Since it is possible to get infected twice we have to make sure, that the app still works after the first infection - especially for people who usually don't crawl through FAQs.

## Is this something you're interested in working on
No

---
Related Issue: #115 Adding a 'virus-free again' feature  
Internal Tracking ID: EXPOSUREAPP-2074 Story request
EXPOSUREAPP-4641 Android
PR Android corona-warn-app/cwa-app-android#2230 and
PR Android corona-warn-app/cwa-app-android#2253
EXPOSUREAPP-4781 iOS
PR iOS https://github.com/corona-warn-app/cwa-app-ios/pull/1960

**Comment by Ein-Tim** [comment]
Hey @bigbug 👋🏻

First of all you have to know that you [don't lose](https://www.coronawarn.app/en/faq/?search=Deinstallieren#delete_random_ids) your contacts of the last 14 days if you reset the app. 
Only the entries in the contact diary are lost and the main screen will show "Unknown Risk" for some time (ca. 24h).

I agree that there should be a button to mark yourself as cured.

---

Related Issues: #115 & #239

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> if you reset the app via the in-app option ... 
... the main screen will show "Unknown Risk" for some time (ca. 24h).

Starting from CWA 1.8 Android if the app is reset, the status immediately shows "Low Risk" not "Unknown Risk". There is no 24 hour wait any more. What happens on iOS, is that the same? (See also new issue https://github.com/corona-warn-app/cwa-app-android/issues/2196. Please comment on the Android issue if iOS has also been changed the same way.)

**Comment by Ein-Tim** [comment]
Thanks for the hint @MikeMcC399.
Did not notice that (since I don't reset the app often 😅). 
I commented in  https://github.com/corona-warn-app/cwa-app-android/issues/2196.

**Comment by dsarkar** [comment]
@bigbug and community,

Thanks for reporting and the discussion here. We add this issue to Internal Tracking ID: EXPOSUREAPP-2074. 

Best, DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@bigbug @MikeMcC399 @Ein-Tim 
FYI PR https://github.com/corona-warn-app/cwa-app-ios/pull/1960 (Fix 1.13 planned)
seems to solve this issue in a more elegant way?
What do you think?

**Comment by MikeMcC399** [comment]
@dsarkar 
> FYI PR corona-warn-app/cwa-app-ios#1960 (Fix 1.13 planned)
seems to solve this issue in a more elegant way?
What do you think?

[iOS Feature/4781 end of life behaviour](https://github.com/corona-warn-app/cwa-app-ios/pull/1960) seems to resolve the request.

I found EXPOSUREAPP-4641 for Android:
https://github.com/corona-warn-app/cwa-app-android/pull/2230 and
https://github.com/corona-warn-app/cwa-app-android/pull/2253

**Comment by dsarkar** [comment]
@MikeMcC399  thanks for the feedback.

**Comment by bigbug** [comment]
Looks good (y)
Very appreciate it.

**Comment by dsarkar** [comment]
@bigbug and all the community! Thanks for contributing! Best wishes, DS

**Comment by achisto** [comment]
I am sorry to reopen an already closed topic but there is something important I want to add. First I really appreciate the changes made so that users can now continue using the app after having tested positive. However I miss an in-app explanation about why a user should do this. Many of the people I know believe that they are 100% immune after having had an infection and would therefore delete the app so to not be bothered anymore by notifications. However even the RKI outlines that at the moment they cannot tell for sure that people will be permanently immune and safe against a reinfection. In my opinion that reasoning should also be shown to the CWA-user so they actually understand why it is still important to keep the CWA on their phones after an infection.

**Comment by heinezen** [comment]
We will leave this issue open for discussion until the implementation is pushed to the public in CWA release 1.13.

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Hey @bigbug 

Version 1.13 which introduced this has been released to GitHub and is available to all users in the next 48h.

See blog post:

DE: https://www.coronawarn.app/de/blog/2021-03-04-corona-warn-app-version-1-13/
EN: https://www.coronawarn.app/en/blog/2021-03-04-corona-warn-app-version-1-13/

See GitHub release:

iOS: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.13.0
Android: https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.13.2

Please close this issue.

**Comment by heinezen** [comment]
Dear community,

Thiis feature is now implemented in CWA v1.13. Thank you for your contributions to the discussion.

We will close this issue now. If you have further suggestions regarding this particular feature, please open a new issue.

----
Corona-Warn-App Open Source Team
