### ISSUE TITLE
Collecting place & time of infections for RKI & respecting data privacy

### ISSUE THREAD

**Issue by HoddleHH** [corona-warn-app/cwa-wishlist#349]
**Motivation**
Provide to RKI an anonymized data set of likely infection points to get better insight in actual infection sources by at the same time respecting privacy rules in a proper way. This way, the government could more precisely decide about suitable measures against the virus.

**Idea**
App users tested positive and at the same time having a red alarming status in their app could provide place and time corresponding to their infection source with a high probability.

**Solution**
1. For every critical contact which is relevant for a red app alarm status, log internally time stamp and GPS coordinates.
2. Following steps apply only to positive tested users with a recent red alarm occurrence in their app:
  After agreeing to warn other users about their infection, in a following second step users get an option to inform RKI about data samples consisting of time and place without any relation to their own person, i.e. in a completely anonymized way. 
3. This additional option should be presented as an independet absolutely voluntary additional step including a good explanation of data privacy mechanisms (encrypted data connection to RKI without any personal data etc.).

**Background**
From statistical point of view, a quite low percentage of infections reported this way would be sufficient to better understand infection events also in public live, i.e. schools, supermarket, public transport etc. by applying typical methods for data anlysis as available at RKI.
Requires access to GPS function by the app.

**Comment by Ein-Tim** [comment]
Hey @HoddleHH 👋🏻

Thank you for sharing your proposal here.
I think this is very closely related/(nearly) the same proposal as #288. 
If you think so too, please consider monitoring #288 and follow up there if necessary. 

Thanks

**Comment by HoddleHH** [comment]
I agree though there some differences in detail, lets close this one and follow the one at #288 instead.

**Comment by MikeMcC399** [comment]
@HoddleHH 
> Requires access to GPS function by the app.

This is not possible.

a) It is against the Corona-Warn-Apps's [Privacy Notice](https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf)

"5. What data is processed?

The app’s entire system has been programmed to process as little personal data as possible. This means that, when you use exposure logging, warn other users, or retrieve a test result, the system does not collect any data that would allow the RKI or other users to infer your identity, your name, **your location** or other personal details. The app does not therefore use any analysis tools to evaluate the way you use it."

b) The app stores do not allow COVID-19 apps to access location information. 

For Google, see https://developers.google.com/android/exposure-notifications/exposure-notifications-api#architecture

Google Play services

Bluetooth functionality happens within on-device Google Play services. Bluetooth functionality includes all broadcasts and scans for BLE beacons, along with local database storage. Your app must have the BLUETOOTH and INTERNET permission in its manifest, but your app doesn't require and can't include **ACCESS_COARSE_LOCATION, ACCESS_FINE_LOCATION**, nor BLUETOOTH_ADMIN. For more information about restrictions on your app, see the API’s [Terms of Service](https://blog.google/documents/72/Exposure_Notifications_Service_Additional_Terms.pdf).

**Comment by Ein-Tim** [comment]
The same restrictions are in place for iOS/ Apple:

https://developer.apple.com/contact/request/download/Exposure_Notification_Addendum.pdf says:

3.3 A Contact Tracing App **may not use location-based APIs**, may not use Bluetooth functionality (excluding Bluetooth functionality included in the Exposure Notification APIs) and **may not collect any device information to identify the precise location of users.** In addition, Contact Tracing Apps are prohibited from using frameworks or APIs in the Apple Software that enable access to personally identifiable information (e.g., Photos, Contacts), unless otherwise agreed by Apple.
