### ISSUE TITLE
Notes on contact diary entries (locations)

### ISSUE THREAD

**Issue by hereisonejens** [corona-warn-app/cwa-wishlist#350]
## Suggested Enhancement
Save notes on contact dairy entries (locations only). Notes such as how many people you met that day at a saved location.

## Expected Benefits
Example: You've visited a butcher shop and the only person you've met there was the seller. You don't know the name of the seller. So you save a note like "Met the seller". In case of infection, the health office can request the butcher shop which seller worked on the day and track that contact.

---
Internal Tracking ID: [EXPOSUREAPP-3034](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3034)

**Comment by Ein-Tim** [comment]
Closely related #314

**Comment by Ein-Tim** [comment]
This will be added with version 1.14 ([Source](https://github.com/corona-warn-app/cwa-app-ios/pull/1988/files#diff-130eb13421036eb3058649fa7623c37dcdf42a3ed0069060bfe0f81a95403f6fR1357)):

>Sie können zu jedem Eintrag angeben, unter welchen Umständen die Begegnung stattfand. Sie können aus vorgegebenen Optionen auswählen (z.B. Dauer der Begegnung, mit oder ohne Maske) sowie zusätzlich in einer kurzen Notiz weitere Umstände erfassen, die zu einem erhöhten Risiko führen könnten. Sollten Sie sich tatsächlich anstecken, können diese Angaben dem Gesundheitsamt bei der Nachverfolgung möglicher Infektionsketten helfen.

**Comment by Ein-Tim** [comment]
Version 1.14 which introduced this has been released to GitHub and is available to all users in the next 48h. 

See blog post: 

DE: https://www.coronawarn.app/de/blog/2021-03-09-corona-warn-app-version-1-14/
EN: https://www.coronawarn.app/en/blog/2021-03-09-corona-warn-app-version-1-14/

See GitHub release:

iOS: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v1.14.3
Android: https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.14.3

**Comment by dsarkar** [comment]
@hereisonejens and dear community. Thanks for your contributions. This feature has been implemented. We suggest closing this issue now.  

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@hereisonejens 

Here is a screenshot from CWA Android 1.14.3 showing the note field for a place

![Place note](https://user-images.githubusercontent.com/66998419/110846012-91ad3c00-82ab-11eb-98ef-7f572d34e077.jpg)

A note field is also available for People. There are screenshots on https://www.coronawarn.app/en/screenshots/ to show this.

**Comment by heinezen** [comment]
Dear community,

Thiis feature is now implemented in CWA v1.14. Thank you for your contributions to the discussion.

We will close this issue now. If you have further suggestions regarding this particular feature, please open a new issue.

----
Corona-Warn-App Open Source Team
