### ISSUE TITLE
Display current Vaccination progress

### ISSUE THREAD

**Issue by Tremoneck** [corona-warn-app/cwa-wishlist#351]
## Feature description

Add an additional Card informing about the current number of vacination doses administered. Also show the number of vacinated people.

The current progress can be found at https://impfdashboard.de/static/data/germany_vaccinations_timeseries_v2.tsv 
Maybe this information should be cached at one central place. There is also only a need to update this information if the last update happened in the same timeframe, starting from 12 o'clock midday.

## Problem and motivation
Make the app the one stop place to find information about corona. It also makes the number easily accessible and shows that progress is happening.

## Is this something you're interested in working on

No

---
Internal Tracking ID: [EXPOSUREAPP-5018](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5018) overview

Internal Tracking ID: [EXPOSUREAPP-7086](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7086) iOS
Internal Tracking ID: [EXPOSUREAPP-7430](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7430) Android

**Comment by Ein-Tim** [comment]
Hey @Tremoneck 

Just that we get you right, you want to add a new statistics card which shows the current vaccination progress, right?

**Comment by Tremoneck** [comment]
Yes, that is right.

**Comment by heinezen** [comment]
Hello community,

we have added this request to the general Jira ticket regarding improvements to the statistics (ticket ID: EXPOSUREAPP-5018). The developers are monitoring the feature request and decide which of them will be implemented or prioritized. We will notify you on Github in the specific issues, once we hear anything new.

Regards, 
CH

----
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-7086](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7086) user story

**Comment by Ein-Tim** [comment]
This has been implemented with version 2.5! 🎉

See the blog post: https://www.coronawarn.app/en/blog/2021-07-12-cwa-version-2-5/

**Comment by dsarkar** [comment]
Dear @Tremoneck and community. Thanks for contributing here. As @Ein-Tim just mentioned, this feature request has been implemented and we therefore suggest to close this issue. Thanks again, best wishes, DS

---
Corona-Warn-App Open Source Team
