### ISSUE TITLE
[Solved]: [Display “Local 7-Days-Inzidenz”]: Additional Information in CWA, based on v1.11.0,…

### ISSUE THREAD

**Issue by Jo-Achim** [corona-warn-app/cwa-wishlist#353]
Hello everybody,

Based on the CWA version 1.11.0, in which incidences are now also displayed, I would like to make a supplementary proposal - which is a bit tricky in terms of data protection law, but can be solved.

Recently, at incidences above a certain value, we have had e.g. movement restrictions within a 15 km radius from home. Due to the corona mutants, it can be assumed that such restrictions will continue to exist in the future.

This means that the current value of the local (home) incidence also belongs as info inside CWA, as does the other new data / information.
Problem: How can CWA display local incidences if it does not have access to the user-location?

Due to data protection, I see the following _voluntary_ option (here reference to Germany)...
With the comparison of the data for the “7-day incidence”, all “7-day incidence” data sets of **all** rural districts, urban districts, etc. (Landkreise, kreisfreien Städte) should also be transmitted to the CWA (approx. 401 data sets for germay?).

For example, if the CWA user _voluntarily_ selects a preferred location from this list of data records to be displayed in a new CWA setting (counties, urban districts), the incidence of this preferred location could be displayed **internally** the CWA. CWA-internal means here that the CWA only processes locally from the overall data set (counties, urban districts) and additionally displays a 'local (location-related) 7-day incidence' value.
A luxury version of this function would display the value of the preselection by default, but also make the other data records temporarily selectable with the help of a list selection.

Example:
![Screenshot_20210131-114933_2](https://user-images.githubusercontent.com/21124877/106384776-e4522900-63cc-11eb-9588-d925fcd6d6f1.png)

In this example I assume that the two arrows to the left and right side of "Hamburg-Stadt" are used to scroll through several predefined data sets (districts / urban districts).
Perhaps an alternative solution would be to make the display field "Hamburg-Stadt" itself input-capable and to specify all possible alternatives in a context-related manner according to the respective input; So after "H" all districts / urban districts with "H", after "Ha" all with "Ha" etc.

If there is no default in the CWA settings, it will not be displayed at all; i.e. at least one specification must have been made under "CWA settings" to show this 'local' display / information.

When displaying the 'local 7-day incidence', the corresponding displays should be sorted in such a way that the display of the "7-day incidence" may be displayed on the right-hand side; currently as 4 and 5 tiles ("7-day incidence" and "7-day incidence (local)").

The background color (here red) of the - in the example above - arrow that shows the trend could serve as an indicator for the incidence value; according to the RKI specifications.

Important: The procedure described should on the one hand continue to **guarantee data protection without restriction**. For this purpose, only the local processing of the selection / input of the desired districts / urban districts must be ensured. And on the other hand, this functionality provides a base number ('local' incidence), which makes it easy to read the applicable provisions (elsewhere (Internet, NINA, etc.)) for this incidence without having to search for further apps / information, etc. .

Since I do not assume that I have found the Philosopher's Stone, the above is only a suggestion.

Sincerely, Joachim.

----
Internal Tracking ID: [EXPOSUREAPP-5018](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5018)
Internal Tracking ID: [EXPOSUREAPP-7087](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7087)

Internal Tracking ID: [EXPOSUREAPP-7431](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7431) Android
Internal Tracking ID: [EXPOSUREAPP-7276](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7276) iOS

**Comment by Ein-Tim** [comment]
Related: #151 & #210

**Comment by Jo-Achim** [comment]
Thank you, @Ein-Tim,

it is increasingly difficult to really post new topics that have not been directly or indirectly mentioned somewhere here.

**Comment by MikeMcC399** [comment]
@Jo-Achim 

[NINA](https://www.bbk.bund.de/DE/NINA/Warn-App_NINA_node.html) already delivers the local incidence value for your actual position or for a list of stored locations. It's not an exact value though, just a range category.

![NINA Infektionsgefahr Stufe 4](https://user-images.githubusercontent.com/66998419/106387826-da83f200-63db-11eb-8ae3-9a821ccecac2.jpg)

---
![NINA Corona-Regeln](https://user-images.githubusercontent.com/66998419/106387832-e1ab0000-63db-11eb-8a23-d624bc3741bc.jpg)

---

Links to download for iOS and Android are on the [NINA website](https://www.bbk.bund.de/DE/NINA/Warn-App_NINA_node.html). Although it is possible to change the language in NINA a lot of the content is untranslated German.

**Comment by Jo-Achim** [comment]
@MikeMcC399, 

I know, but it was about additional information under the roof of the CWA.

No question, the extensions mentioned in #151 make perfect sense - but the question is how long CWA with all the additional information will remain usable in terms of programming.
In this respect, links within the CWA could be a solution, as long as its data / information is current and official. 

Joachim.

**Comment by heinezen** [comment]
Hello community,

we have added this request to the general Jira ticket regarding improvements to the statistics (ticket ID: EXPOSUREAPP-5018). The developers are monitoring the feature request and decide which of them will be implemented or prioritized. We will notify you on Github in the specific issues, once we hear anything new.

Regards, 
CH

----
Corona-Warn-App Open Source Team

**Comment by Jo-Achim** [comment]
Hello everybody,

Since we had already mentioned the "**<a href="https://www.bbk.bund.de/DE/NINA/Warn-App_NINA_node.html" rel=”nofollow”>NINA</a>**" app here and I don't want to open up a new topic, I am adding a reference to the “**<a href="https://luca-app.de/" rel=”nofollow”>luca</a>**” contact tracking app.

Maybe there will be synergies.

In this sense, Joachim.

**Comment by Jo-Achim** [comment]
**[Information only]**
NINA was mentioned above ...
... that's why I would like to draw your attention to a change in NINA: the 7-day incidence has recently been displayed based on location.
Unfortunately, the limits of the respective warning levels are no longer applicable and a desirable trend arrow is still missing.

**Comment by Ein-Tim** [comment]
@Jo-Achim For sure there should be another option for the user but how cool would it be if the user turns on the "data donation" feature and besides of just donating unknown technical data he/she could also see the local Inzidenz. This would be a win win situation, IMHO.
But as said, it's important that there's another way too.

I wrote this comment after I saw someone on Twitter asking why the app doesn't shown the inzidenz for his location although he entered it into the the data donation feature...

**Comment by MikeMcC399** [comment]
The https://www.darfichdas.info/ app mentioned in https://github.com/corona-warn-app/cwa-wishlist/issues/151#issuecomment-733903361 @AndreasOesterhelt shows the local 7-day incidence for a list of selected locations. It also includes a trend graph of  7-day incidence for the last 14 days in an overview of the selected locations, for each location, and in larger size display when a certain location's detailed entry is shown. I have it installed as well as the NINA app (see https://github.com/corona-warn-app/cwa-wishlist/issues/353#issuecomment-770394490 in this thread).

![image](https://user-images.githubusercontent.com/66998419/119166981-93d80780-ba5f-11eb-8d4a-259025bbf869.png)

![image](https://user-images.githubusercontent.com/66998419/119167063-ac482200-ba5f-11eb-9c17-ee5d5e2a1ab9.png)

I can't imagine that CWA is ever going to match the functionality of the above, but I would be happy to be proved wrong.

**Comment by Jo-Achim** [comment]
@MikeMcC399,

thanks for the information. 

In the meantime, NINA has also followed the suggestion to report local incidences; for example: 
![Screenshot_20210520-111239_2](https://user-images.githubusercontent.com/21124877/119221137-26bf8300-baee-11eb-9c25-8297f4055178.jpg)

Best regards, Joachim.

**Comment by Ein-Tim** [comment]
If I interpret the files in the PR https://github.com/corona-warn-app/cwa-app-ios/pull/2767/ right, we will see something like this in version 2.4.

The `fix 2.4` label also suggests this!

**Comment by dsarkar** [comment]
FYI PR Android https://github.com/corona-warn-app/cwa-app-android/pull/3596
FYI PR iOS https://github.com/corona-warn-app/cwa-app-ios/pull/3003 (Check out the video)

**Comment by Ein-Tim** [comment]
@Jo-Achim Did you check if what has been released in CWA version 2.6 fulfills your proposal?

**Comment by Jo-Achim** [comment]
Thanks for the reminder, @Ein-Tim.

Yes, my wish was solved differently, but something like this was in mind as a result.

With that I conclude this wish.

**Comment by dsarkar** [comment]
@Jo-Achim Thanks for contributing here. @Ein-Tim Thanks for "cleaning up".
