### ISSUE TITLE
UX: Inconsistent FAQ lists and hard-to-find answers

### ISSUE THREAD

**Issue by sventuerpe** [corona-warn-app/cwa-wishlist#354]
## Where to find the issue

FAQ lists at:
1. https://www.coronawarn.app/de/faq/ 
2. https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-faq-1758392 
3. https://www.bundesregierung.de/resource/blob/1753814/1760022/0c64afa282398b1b6255d43c7c3c4950/2020-06-12-faq-langfassung-de-data.pdf?download=1 

(Linking to the German versions here.)

## Describe the issue
Three different lists of frequently asked questions exist and differ in content. The CWA website contains [one](https://www.coronawarn.app/de/faq/), the app (Android) links to [a different one](https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-faq-1758392) with fewer questions at bundesregierung.de, and a link points from there to [a longer third one](https://www.bundesregierung.de/resource/blob/1753814/1760022/0c64afa282398b1b6255d43c7c3c4950/2020-06-12-faq-langfassung-de-data.pdf?download=1) in a PDF document at bundesregierung.de. While there is some overlap between the three, they do not seem to constitute different representations or subsets of the same main document. 

This makes it difficult to find answers contained in some of the FAQs but not others, to remember where to find certain information, or to find from the app all information a user may need. 

Example: A new user asking themselves whether they may close the app after activation would most likely turn to the FAQ prominently advertised by the app ([no. 2](https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-faq-1758392)) but not find their question answered. They may or may not find from there the longer PDF document ([no. 3](https://www.bundesregierung.de/resource/blob/1753814/1760022/0c64afa282398b1b6255d43c7c3c4950/2020-06-12-faq-langfassung-de-data.pdf?download=1)), which also fails to answer their question. Only if they happen to check the FAQ at coronawarn.app (no. 1) they will [find the answer](https://www.coronawarn.app/de/faq/#close_app) to their question.

## Suggested change

Maintain a single, consistent FAQ or include all questions of immediate relevance for using the app in whichever FAQ version the app links to. 
 
---
Internal Tracking ID: EXPOSUREAPP-1877

**Comment by heinezen** [comment]
Hello everyone,

we have some updates on the matter. First of all, the decision was made that there will not be a merged FAQ. This was also answered in https://github.com/corona-warn-app/cwa-website/issues/769#issuecomment-770253203

> There will not be one combined FAQ somewhere, the hierarchy is clear and fix: The federal FAQ comes first. From there, they will link to other sites like the technical FAQ or to the RKI.
I hope you all can accept this hierarchy, even if this may lead to misplaced FAQ items or overlaps.

----
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@sventuerpe @Ein-Tim @MikeMcC399 Community - FYI from R 2.13 on, the app will link to the FAQ of coronawarn.app not bundesregierung.de, see https://github.com/corona-warn-app/cwa-app-android/pull/4179/files

**Comment by MikeMcC399** [comment]
@dsarkar 
> from R 2.13 on, the app will link to the FAQ of coronawarn.app not bundesregierung.de,

I'm very happy to hear about that!

It has been very difficult to get fixes implemented on 
- https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-faq-1758392 (German)
- https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch/corona-warn-app-faq-1758636 (English)

See for instance https://github.com/corona-warn-app/cwa-hotline/issues/13 just to get the hotline phone numbers corrected. An issue that has been open for many months.

**Comment by Ein-Tim** [comment]
@dsarkar 

Great news! 

Maybe it would make sense to reopen this issue, apply the `Fix 2.13` label and close it once implemented?

**Comment by dsarkar** [comment]
@Ein-Tim Sure!

**Comment by MikeMcC399** [comment]
@dsarkar 
What will happen to the websites after 2.13?

- https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-faq-1758392 (German)
- https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch/corona-warn-app-faq-1758636 (English)

Will the contents be:
- frozen?
- removed?
- removed and a link left to https://www.coronawarn.app?
- maintained through RKI contacts to Bundespresseamt as before?

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Version 2.13 has been released today. Would it be okay for you to close the issue or would you like to get an answer to https://github.com/corona-warn-app/cwa-wishlist/issues/354#issuecomment-937659903 first?

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Perhaps @sventuerpe would like to respond, since it is his issue, even though it is more than a year old?

Otherwise the questions from https://github.com/corona-warn-app/cwa-wishlist/issues/354#issuecomment-937659903 are implicitly covered by https://github.com/corona-warn-app/cwa-website/issues/1929, so the issue here (#354) does not need to stay open waiting for an answer to that comment.

I notice that there is no mention in the change of FAQ location in today's [2.13 blog announcement](https://www.coronawarn.app/en/blog/2021-11-03-cwa-version-2-13/).

(I've just closed a related issue https://github.com/corona-warn-app/cwa-hotline/issues/13 due to the change of primary FAQ location.)

**Comment by Ein-Tim** [comment]
@sventuerpe 

Do you have any feedback on this? Are you happy on how it was implemented in version 2.13?
