### ISSUE TITLE
Potential super-spreader identification and notification

### ISSUE THREAD

**Issue by rolfwilms** [corona-warn-app/cwa-wishlist#355]
### Summary
It has been [estimated](https://science.sciencemag.org/content/370/6515/406) that only 10% of the cases cause 80% of the infections. Individuals with a high amount of contacts are most likely to a) be infected and b) transmit their infection, i.e. the relative probability to transmit Sars-CoV-2 is proportional to the amount of contacts squared.

Here I suggest adding a new feature to the CWA, which notifies individuals of a high amount of contacts, so that they can take extra precaution, in particular to frequently apply the [forthcoming Lateral Flow Tests approved for self-testing](http://dipbt.bundestag.de/dip21.web/bt?rp=http://dipbt.bundestag.de/dip21.web/searchProcedures/simple_search.do?nummer=19/25705%26method=Suchen%26wahlperiode=%26herausgeber=BT) for COVID-19, or simply change their behavior.

### App User Experience
The CWA displays the individual potential exposure risk relative to the average across CWA app users. If a particular threshold is exceeded, recommended extra precautions, such as frequent self-testing, are displayed.

Users are asked if they agree to donate their potential exposure risk. This agreement is optional, the proposed feature can also be used when not agreeing to a donation.

### RKI User Experience
The UI allows to set the average and threshold of potential exposure risk, which are to be transmitted to the app.
The UI allows to download the donated individual potential exposure risks, e.g. as CSV. From this data, the average and a suitable threshold for potential exposure risk can be computed. By identifying which of the donated individual potential exposure risks came from those tested positive, the hypothesis that a high potential exposure risk correlates with being tested positive can be quantified and the threshold can be fine-tuned.

### Implementation
The potential exposure risk is computed within the app the same way as the exposure risk, but assuming that all contacts were exposures to a positive individual.

If the user has agreed to donate their individual potential exposure risk, it is transmitted to the server when connecting to the server for downloading the keys of positively tested users.

The server transmits the average and threshold of potential exposure risk to the app when downloading the keys of positively tested users.

### Benefits

- Users with a high potential exposure risk are made aware of that fact and are encouraged them to take extra precautions, such as frequent COVID-19 testing. This allows for a more economic use of available testing resources by focusing on those with the highest risk to be exposed to and transmit Sars-CoV-2. 
- Users made aware of a high potential exposure risk may change their behavior, such as trying to have fewer close contacts.
- The data collected by the individual potential exposure risk donations allows to verify the usefulness of of the provided feature and gives additional insight into the way Sars-CoV-2 is transmitted.
- The display of a high potential exposure risk in the app may serve as a qualification to receive free testing or test kits for self-administration.
- The continuous update of the potential exposure risk in the app may improve the acceptance of the app, as it is more interesting when something individual is happening more frequently than the regular exposure risk.
- 
---
Internal Tracking ID: EXPOSUREAPP-5021

**Comment by Ein-Tim** [comment]
Related Issues:

#213
#240
#246

**Comment by heinezen** [comment]
Hello community,

We have added this feature request to our internal Jira ticketing system. The developers are informed and will decide if and how the feature will be implemented together with the RKI. We will notify you about updates on the status of the feature requuest here on Gthub.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by amplexity** [comment]
Great Issue/Feature. I am new here, so pardon if this is not the right format or place for my addl. ideas relating to cluster situations. 
--
In cluster situations, when the user is warned, they should also be invited to make logs in their Diary. 
--
In cluster situations, users should be prompted if they would voluntarily 'donate' their location data, (transmitted to RKI and/or Local Health Authority) so that the local health authority can be made aware of Where and When a cluster occured (without knowing WHO was part of it). Not sure if this is Privacy conform, but maybe it can be adjusted in a way to protect the individual right to privacy. 
--
After a cluster situation the user is notified where or how he/she may obtain a test. 
--
After a cluster situation the user is notified daily of what symptoms to look out for.
--
The user can opt out of notifications.

**Comment by larswmh** [comment]
Closing this issue as the related internal ticket is set to `obsolete`.

Developer comment:

> The people who have a much higher risk to get infected, because they have constantly more contacts to other people, will statistically automatically get more "Low Risk" and "High Risk" states with normal todays usage of the CWA. So they get the warning and related info how to behave already today.
> 
> The technical limitations of the ENF do not allow to get more information about other smartphones, which are not using the CWA.
> 
> So, the additional information from donated "potential exposure risk" could not lead to a better warning behaviour.
