### ISSUE TITLE
User preferences to fine-tune behaviour of risk calculation

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-wishlist#357]
## Current Implementation

Several aspects of the risk calculation are a tradeoff. 
Examples:
* frequency of risk calculation. Performing this several times per day gives a faster warning, but has a very negative impact on battery drain.
* downloading keys if no WLAN available. This may result in additional costs; but some users have an unlimited plan, or they have many contacts with vulnerable people and just need their warning asap.

It is hard, if not impossible, to find a good single value that satisfies the needs and expectations of all users ("no size fits all").

## Suggested Enhancement

The solution is to make such behaviour configurable by the user via user preferences. Of course still providing a reasonable default value.

Add user-configurable preferences for the following:
* frequency of risk check. Values could be: 4 hours / 6 hours / 8 hours / 12 hours / daily.
* download keys in WLAN only vs mobile data

Notes: related to #81. See also [this discussion](https://github.com/corona-warn-app/cwa-app-ios/issues/1664#issuecomment-743353906) and [discussions on battery drain like this](https://github.com/corona-warn-app/cwa-app-ios/issues/1823#)

## Expected Benefits

Configurability by the user can mitigate the battery drain issue that comes with more frequent checks, without sacrificing the faster warning for those who want and need it. Addressing battery drain will increase acceptance of the app. 
As a nice side effect, such a feature will allow the more active users to fine-tune cwa behaviour towards their needs, it engages them, gives them more control, and makes them happy.

---
Internal Tracking ID: EXPOSUREAPP-5022

**Comment by harambasicluka** [comment]
@ndegendogo mobile data for CWA don't cost you anything:

> Important: Mobile/cellular data that are transmitted during the usage of Corona-Warn-App is free of charge and will not be deducted from your data plan!

https://www.coronawarn.app/en/faq/

**Comment by ndegendogo** [comment]
@harambasicluka yes. There is an agreement with the mobile providers that this download of keys for rhe risk check is free of charge.
However, this agreement covers only one check per day. For this reason, the current implementation downloads new keys once per day, plus additional downloads only while WLAN is available.

**Comment by heinezen** [comment]
Hello community,

We have added this feature request to our internal Jira ticketing system. The developers are informed and will decide if and how the feature will be implemented together with the RKI. We will notify you about updates on the status of the feature requuest here on Gthub.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by stweil** [comment]
What about offering risk calculation on demand (with rate limiting)? One automated check per day plus an additional check each time when the user opens the CWA and the last check is older than for example 4 hours? That would keep the user interface very simple while giving everyone the chance to get new status information in critical situations, for example before leaving the house.

**Comment by ndegendogo** [comment]
> One automated check per day 

@stweil even in this case I would prefer a user option to configure the time of day where it happens.
Personally I am very happy with the current 4-hourly schedule. **I don't spend my day in isolation; but of course, as soon as I receive the red warning, I would go home at once.** And I don't want to be forced to remember every 4 hours to check manually; I want this done automatically.

**Comment by larswmh** [comment]
Closing this issue as its related internal ticket was set to obsolete.

> - Frequency of risk calculation has no relevant impact on battery drain.
> - See https://www.coronawarn.app/en/faq/#risk_update_24 for an explanation on why the check is only performed once every 24 hours when using mobile data
> 
> Not realistic to get this implemented.
