### ISSUE TITLE
30% battery usage by COVID-19-Kontaktprotokoll on IOS 13.5.1

### ISSUE THREAD

**Issue by jlang027** [corona-warn-app/cwa-wishlist#36]
Even the app itself seem very economical in using the battery, the also needed Health app from Apple uses 30% for the COVID-19-Kontakprotokoll. Please check, as the overall time to the next recharge is dramatically reduced.

Screenshot: [https://app.box.com/s/ekpxsxwxdlvy16pob99i15q6c5unwwpm](url)

**Comment by thomasaugsten** [comment]
duplicate 
https://github.com/corona-warn-app/cwa-app-ios/issues/671

**Comment by jlang027** [comment]
Moved to corona-warn-app/cwa-app-ios#67
