### ISSUE TITLE
Show the risk status after bringing the App in the foreground

### ISSUE THREAD

**Issue by christianbrb** [corona-warn-app/cwa-wishlist#361]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 11
- iOS Version: 14.2
- App Version: 1.11.0

## Describe the bug

Risk status not shown after scrolling and reopening the App

## Steps to reproduce the issue

1. Kill the App
2. Open the App
3. Risk status is shown 
4. Scroll down to statistics
5. Open a different app
6. Wait a day
7. Open the App
8. It still shows the statistics
9. I have to scroll up to see my risk status

![7857AA9A-A790-47BF-8C8D-42CAD02F6660](https://user-images.githubusercontent.com/35398162/106916794-e1767180-6707-11eb-8f4c-b7d06e1f84e7.jpeg)

## Expected behaviour

Show the risk status after bringing the App in the foreground 

## Additional context

I still assume that it is more important to see an updated risk status instead of the updated Corona stats

---
Internal Tracking ID: EXPOSUREAPP-5023

**Comment by Ein-Tim** [comment]
Can confirm this @christianbrb 

But as stated before (and also said by @dsarkar) this seems more like a feature than a bug.

So the wishlist repo is definitely the right place for this 👍

**Comment by christianbrb** [comment]
Thanks for quickly looking at it 😊👍🏻

I think it is very important, that this is getting changed as the app is called Corona WARN App.

It is a habit for me to look at my risk status every day. This is why I have installed the App.

If this habit is getting changed to look at the Corona Stats, the main purpose is not fulfilled any more in my opinion. The stats I could also look up at a lot of different places. Within the last days I have not looked at the App as frequently as before because I always the stats first.

**Comment by heinezen** [comment]
Hello community,

We have added this feature request to our internal Jira ticketing system. The developers are informed and will decide if and how the feature will be implemented together with the RKI. We will notify you about updates on the status of the feature requuest here on Gthub.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by ndegendogo** [comment]
> I think it is very important, that this is getting changed as the app is called Corona WARN App.

@christianbrb I fully agree, thanks for bringing this up.
cwa is meanwhile showing a lot of additional information screens; I like and appreciate them very much. But on the other side, the audience of cwa covers also persons who are maybe not so much used to smartphones; and such a person can easily be lost.

**Comment by MikeMcC399** [comment]
If you leave the app open on the statistics cards, what happens if there is a change to the risk status, especially a change to red? Is there a pop-up or notification? (I don't know how to test this.)

If the app continues to show Low Risk / No exposures, then it doesn't matter if the app still shows the statistics, because there is no special action to take.

**Comment by dsarkar** [comment]
@MikeMcC399 @ndegendogo @christianbrb 

> If you leave the app open on the statistics cards, what happens if there is a change to the risk status, especially a change to red? Is there a pop-up or notification? (I don't know how to test this.)

We will bring this question to the developers. Thanks.

**Comment by larswmh** [comment]
Closing this issue as the related internal ticket is set to `obsolete`.

> Other users would like to look every day at the statistics and are happy to be automatically there.
> This is also the way apps are handled nowerdays to automatically get to the same part of the app as seen before.

Response to @MikeMcC399's question:

> The notification is (and must be) always independend of the screen.-status you left the app.

(Note that this response is not for certain, as it later asks for confirmation by another person in the comment it was left in. There has not been an update ever since, which can but does not need to mean that this can be considered true)
