### ISSUE TITLE
Contact Journal Export Entries shows German with English locale

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-wishlist#362]
## Technical details

- Device name: Android Pixel 3a emulator
- Android version: 11
- First reported on App version: 1.10.1
- Reviewed as unchanged in App version: 2.17.2

## Describe the bug

The filename and contents of the Contact Journal Export Entries function displays in German when the device is set to English.

## Steps to reproduce the issue

1. Settings > System > Languages and input > Languages
2. Set or add English (United Kingdom) as first language in list.
3. Open CWA
4. Select "Journal" at the bottom of the screen.
5. Tap three-dot icon
6. Tap "Export Entries"
7. Share shows "Kontakte der letzten 15 Tage (dd.mm.yyyy - dd.mm.yyyy)
8. Select (Google) Drive
9. Note that Document title is "Mein Kontakt-Tagebuch"
10. Tap Save
11. View document in Google Drive
12. Note text which says:
"Kontakte der letzten 15 Tage (dd.mm.yyyy - dd.mm.yyyy)
Die nachfolgende Liste dient dem zuständigen Gesundheitsamt zur Kontaktnachverfolgung gem. § 25 IfSG.

Note that screenshot is from version 1.10 where 14, not 15 days were exported.
![image](https://user-images.githubusercontent.com/66998419/103346138-7e077d00-4a93-11eb-8200-4be11034c5f4.png)

![image](https://user-images.githubusercontent.com/66998419/103346244-bf982800-4a93-11eb-83ec-edb5de26f0bf.png)

## Expected behavior

If the UI is set to one of the non-German supported languages, then add translated text in the UI language to the export of the Contact Journal. (According to https://www.coronawarn.app/en/faq/#available_languages: English, Turkish, Bulgarian, Polish & Romanian).

Below the text

"Kontakte der letzten 15 Tage (dd.mm.yyyy - dd.mm.yyyy)
Die nachfolgende Liste dient dem zuständigen Gesundheitsamt zur Kontaktnachverfolgung gem. § 25 IfSG."

add a translation of this text for non-German locales.

Edit: Change expected behavior based on discussion.

---
Internal Tracking ID: [EXPOSUREAPP-4486](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4486) Bug - obsolete
Internal Tracking ID: [EXPOSUREAPP-4741](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4741) Story

**Comment by dsarkar** [comment]
@MikeMcC399 forwarded your comment https://github.com/corona-warn-app/cwa-wishlist/issues/362#issuecomment-773563880 to [EXPOSUREAPP-4741](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4741)

**Comment by larswmh** [comment]
FYI @MikeMcC399 

> The current behaviour is defined by the customer. We may add an option for a localized export later, but for now only german is exported

Closing this ticket, as its related internal ticket is set to obsolete
