### ISSUE TITLE
Possibility to correct or remove an entry in the contact diary for persons or places

### ISSUE THREAD

**Issue by BFallert** [corona-warn-app/cwa-wishlist#366]
## Feature description
Possibility to correct or remove an entry in the contact diary for persons or places if the entry was not assigned

## Problem and motivation

If you make a mistake while entering it or if an entry is no longer required, it cannot be removed

## Is this something you're interested in working on
Yes

**Comment by Ein-Tim** [comment]
Hey @BFallert 

It is possible to remove entries from the contact diary! 


Please see https://www.coronawarn.app/en/blog/2020-12-28-corona-warn-app-version-1-10/ for a How-To. 

If you're happy with this answer, please close this issue.

**Comment by BFallert** [comment]
Thanks for this advice! That solves my problem. The menu would of course also be helpful for the people or places.

**Comment by dsarkar** [comment]
@BFallert Thanks for contributing here!
@Ein-Tim Many thanks for answering.

Best wishes, DS

---
Corona-Warn-App Open Source Team
