### ISSUE TITLE
@heinezen

### ISSUE THREAD

**Issue by cyberpencake** [corona-warn-app/cwa-wishlist#370]
edit: maybe I am not based on the last build, may be my fault.
####################
@heinezen 
I think this can be closed since there is a warning in the App now

_Originally posted by @Ein-Tim in https://github.com/corona-warn-app/cwa-wishlist/issues/144#issuecomment-734884467_

I created this, because it seams to be a really bad warning! At least I did not recognize.
I would suggest you add a feature you need to confirm the deletion of the test registration.

I was mislead by the App because it says, if I get my results earlier on another way (health office, doctor) and the app still shows no results I should rescan my QR code ?!?! That is really annoying.

As well I do not understand why the app can not recognize/save the scanned test and allow to add it again on the same device. So if you "delete" a test you do not completely delete it without the possibility to readd it to the same device again. That way the server with the test results does not need to save the ID of the authorized test device but it would be possible to readd a test to the same device.

Why this silly misleading communication/behaviour of the app? Users are stupid, so am I.

**Comment by Ein-Tim** [comment]
>I created this, because it seams to be a really bad warning! At least I did not recognize.
I would suggest you add a feature you need to confirm the deletion of the test registration.

The warning in the App is this:

![IMG_B3E0E63A9A0F-1](https://user-images.githubusercontent.com/67682506/108605555-03811c80-73b5-11eb-8af1-022166e7883e.jpeg)

There, the App clearly states that the test can only be scanned once. 

> I was mislead by the App because it says, if I get my results earlier on another way (health office, doctor) and the app still shows no results I should rescan my QR code ?!?! That is really annoying.

Could you please provide a screenshot where the app says this?

**Comment by cyberpencake** [comment]
> The warning in the App is this:
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/67682506/108605555-03811c80-73b5-11eb-8af1-022166e7883e.jpeg">
> 
> There, the App clearly states that the test can only be scanned once. What exactly would you do to improve this?
That clearly indicates not to remove tests, yes.

As I mentioned before, I am not sure if I refer to the right place because I had to use https://codeberg.org/corona-contact-tracing-germany/cwa-android/issues on a non google based android device...
I will open an issue there as well. Maybe they have not implemented your warning yet or I am simply stupid.


> I think you refer to the last paragraph on the test result pending screen:
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/67682506/108605612-85714580-73b5-11eb-9948-a6e3d64753f0.jpeg">
> 
> If you read this, you can see that this
> a) only say that you should remove the test result if you are tested positive
> b) that you should call the hotline to get a TAN
> 
> The app nowhere states that you should delete the test and scan the QR-Code again, since this is not possible (for privacy reasons).
Thank you for your fast reply. That was the text.

Despite that, I do not understand why there is no fallback if one deletes its test and want to readd. Should be very little code. But maybe you have reasons not to do so.

I think this can be closed. Thank you again.

**Comment by Ein-Tim** [comment]
I think the best way is to open an issue there, yes.

You, as the author of this issue, can close this.

**Comment by cyberpencake** [comment]
Thank you, it must be my first issue here.

**Comment by heinezen** [comment]
@cyberpencake In the future, please make comments like this inthe original issue (https://github.com/corona-warn-app/cwa-wishlist/issues/144#issuecomment-734884467). You can still comment there, even if the issue is set to closed :)

----
Corona-Warn-App Open Source Team
