### ISSUE TITLE
Try to scan 'non-functional' QR code - improve UI

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-wishlist#372]
Possibly related to [#469](https://github.com/corona-warn-app/cwa-documentation/issues/469) ?

## Current Implementation

Today I got tested at Fürstenfeldbruck. A very lightweight, fully digitized procedure for self-registration. **They have meanwhile added a checkbox to their registration form for a request for a cwa-compatible QR code!** 🚀 
I got a card with the phone number of their hotline, and the QR code of my sample ID (the lab is Eurofins).
*I know that this QR code is not compatible to cwa, but I pretended to be the average user, and tried to scan it with cwa, in the expectation to see the error message.*
So I went through all these dialogs of cwa; but finally it did **no scan and no error message**. 
Note: the QR code is very small. Maybe the scanner didn't even detect / focus it correctly. But as an "average user" I would now go away and tell all my friends that cwa QR code scanning just does not work.

## Suggested Enhancement

Additionally to the "autoscan" that was never triggered in my case, a button to force a scan. You can then give error messages with possible reasons (bad lighting / incompatible QR code system / ...) and/or direct the user to a FAQ page which explains more details (e.g. how a correct / cwa-compatible QR code should look like).

## Expected Benefits

Less confusion on user side. Give them the opportunity to do the first steps of trouble-shooting.

**Comment by MikeMcC399** [comment]
@ndegendogo 
Just as a sanity test I tried scanning a QR code using CWA for something completely unrelated and CWA gave me an error message. In other words, it recognized that it was a QR code, but not one which could be used by CWA.

Did you try scanning your non-CWA code with a generic QR scanner? Was it accepted and scanned by your mobile device? Are you using iOS or Android?

**Comment by MikeMcC399** [comment]
This suggestion overlaps the existing request:
"Improve response to scanning non-CWA lab QR code" #343

**Comment by ndegendogo** [comment]
@MikeMcC399 

> Did you try scanning your non-CWA code with a generic QR scanner? Was it accepted and scanned by your mobile device? 

Good point, I'll try this. And I agree that this also will be one of the first steps of trouble-shooting that the user should try.

> Are you using iOS or Android?

cwa 1.12.1 / iOS 14.2 / iPhone 8.

I remember that end of October I tried to scan a similar QR code with cwa, and got an error message like "bad lighting". Same device, but I don't remember the cwa version nor the iOS version.

**Comment by MikeMcC399** [comment]
@ndegendogo 

You could also try scanning a dummy (non-CWA) QR code that I posted in https://github.com/corona-warn-app/cwa-wishlist/issues/343

![QR Code DE12345678](https://user-images.githubusercontent.com/66998419/105467552-25905d80-5c96-11eb-8408-b4835ee6d61f.png)

**Comment by ndegendogo** [comment]
@MikeMcC399 Bingo!
It seems that my 'wrong' code is not even a QR code (is this possible? Are there maybe other types of codes?)
I tried to read it with a QR code scanning app, and did not succeed (tried forever).
Whereas the code you posted above was read immediately by the QR code app, and produced an error message in cwa.

By the way, I noticed that a similar "code" appears sometimes on my letters; not sure if that is the replacement for a stamp, or an encoding of the address for automatted processing.

**Comment by MikeMcC399** [comment]
@ndegendogo 
> It seems that my 'wrong' code is not even a QR code (is this possible? Are there maybe other types of codes?)

There are many types of 2-D barcodes (see https://en.wikipedia.org/wiki/Barcode#Matrix_(2D)_barcodes) and QR is just one type.

> I tried to read it with a QR code scanning app, and did not succeed (tried forever).
Whereas the code you posted above was read immediately by the QR code app, and produced an error message in cwa.

So your experiment suggests that the code you thought was a QR code, was not in fact coded in QR format. In that case I don't think that there is any reasonable enhancement which could be done to the CWA app to cover this case.

> By the way, I noticed that a similar "code" appears sometimes on my letters; not sure if that is the replacement for a stamp, or an encoding of the address for automatted processing.

According to https://www.deutschepost.de/de/f/frankierung/matrixcode.html the Deutsche Post uses Matrixcode, but I think this is a little off topic 🙂 !

**Comment by ndegendogo** [comment]
@MikeMcC399 it looks like this
![code](https://user-images.githubusercontent.com/6118267/109037272-d5f4e580-76ca-11eb-9cf5-81673d52b8aa.jpg)

And, yes, I agree that this is not any issue for cwa. 
Any trouble-shooting user would find out fast that this code does not even scan with a 'generic' QR code scanner.

**Comment by ndegendogo** [comment]
Closing
