### ISSUE TITLE
Infectiousness profile eventualy needs an update for B117 mutation

### ISSUE THREAD

**Issue by Andiadm** [corona-warn-app/cwa-wishlist#373]
The Infectiousness profile was based on He et al and later updated.
Recently a [Harvard publication](https://dash.harvard.edu/handle/1/37366884) suggest that the mean duration of the proliferation phase was 5.3 days in the B117 variant group vs. 2.0 days for non-B.1.1.7 virus.
I wanted to raise this issue because with the B117 becoming more and more widely spread, this finding obviously calls for a change in the profile.
Ideally, the CWA would use a differnt profile depending if the positively tested person was infected by B117. This might be a too big change. But I would prefer to produce more warning messages than too little.

**Comment by heinezen** [comment]
@Andiadm We cannot move threads, but I've mirrored your initial post to the other issue (https://github.com/corona-warn-app/cwa-wishlist/issues/328). Thanks again for providing the input.

I willl close this issue in favour of #328, as the discussion should not be spread out over several issues. 

----
Corona-Warn-App Open Source Team
