### ISSUE TITLE
Publish technical specification repository

### ISSUE THREAD

**Issue by fynngodau** [corona-warn-app/cwa-wishlist#376]
At various occasions, PRs and issues link to the private `cwa-app-tech-spec` repo. It sounds like this repository contains lots of useful information for people who are trying to find out how exactly the application is working. Therefore, we at CCTG would be very happy if the repository could be published.

If this is not possible, it would also be great if you could publish technical documentation *before* the related feature is released; for example I think that there is still no public documentation for the PPA feature (https://github.com/corona-warn-app/cwa-wishlist/issues/356#issuecomment-770761136). This means that I need to collect information about details for upcoming features from PR source code and strings as well as PR descriptions and comments, which frequently link to private resources instead of detailing what is being done publicly, which is very tedious and seems unnecessary when I know that technical documentation for a feature is being written.

This would aid everyone who wants to contribute to the code or otherwise work with it.

---
Internal Tracking ID: EXPOSUREAPP-3428

**Comment by Ein-Tim** [comment]
Related Issue: https://github.com/corona-warn-app/cwa-app-ios/issues/1393

PPA-Server docs: https://github.com/corona-warn-app/cwa-ppa-server/tree/main/docs (there isn't yet anything helpful)

**Comment by dsarkar** [comment]
@fynngodau ok, thanks, forwarded to the team! Internal Tracking ID: EXPOSUREAPP-3428

**Comment by dsarkar** [comment]
Hi @fynngodau. Feedback: Probably there will be something published on PPA next week, but there are no plans to publish the cwa-app-tech-spec repo currently since it is a repo containing lots of information that is constantly changing.

**Comment by fynngodau** [comment]
> it is a repo containing lots of information that is constantly changing

Logically, this is the case, since the app is also constantly being developed. Hence, it is the purpose of this inquery that having access to this information as soon as it changes would be very helpful.

**Comment by dsarkar** [comment]
@fynngodau FYI https://github.com/corona-warn-app/cwa-documentation/pull/540/files 
solution_architecture.md  has been updated

**Comment by fynngodau** [comment]
Once again, it would be nice if documentation on the "event registration" feature that is being developed for 1.16 would be available soon.

**Comment by dsarkar** [comment]
@fynngodau We will forward you request. Thanks!

**Comment by dsarkar** [comment]
@fynngodau see  see https://github.com/corona-warn-app/cwa-documentation/blob/master/event_registration.md

**Comment by fynngodau** [comment]
@dsarkar Thanks, that’s really awesome!

**Comment by mlenkeit** [comment]
@fynngodau as dsarkar explained in a previous post there are currently no plans to make cwa-app-tech-spec public. Instead, we intend to update cwa-documentation more frequently with technical descriptions, such as we did for Event Registration.

I'm closing the issue for now. Feel free to re-open if there's something specific you're looking for.
