### ISSUE TITLE
[Overview] Rapid-test

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-wishlist#378]
#239 - EXPOSUREAPP-3496 Entering negative test result should influence displayed risk status
#263 - EXPOSUREAPP-3672 After negative antigen rapid test: Show status: "Cannot spread virus" for some hours
#298 - EXPOSUREAPP-4714 Add information about rapid test results to app
#365 - EXPOSUREAPP-5140 Rapid test feature using cough detection
https://github.com/corona-warn-app/cwa-wishlist/issues/371 - // -Rapid Ag-Test infrastructur
https://github.com/corona-warn-app/cwa-wishlist/issues/374 - [EXPOSUREAPP-5391](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5391) Warn contacts on positive home-use rapid test 

---
Internal Tracking ID: [EXPOSUREAPP-5469](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5469)

**Comment by Ein-Tim** [comment]
@dsarkar If you want I can open a new issue and copy the text in there (so I can help keep the overview up to date) 🙂

**Comment by dsarkar** [comment]
@Ein-Tim Great! Go ahead! Thanks!

**Comment by Ein-Tim** [comment]
@dsarkar See #379
