### ISSUE TITLE
Showing items planned for implementation

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-wishlist#380]
## Document location

[README.md](https://github.com/corona-warn-app/cwa-wishlist/blob/master/README.md)

## Description of issue

[README.md](https://github.com/corona-warn-app/cwa-wishlist/blob/master/README.md) says:

"_If an issues (sic) is selected to be implemented in a future release of the Corona-Warn-App, it will be moved to the CWA Backlog Repository._"

Issues are not being moved to the CWA Backlog Repository, instead labels are being applied to the issues, such as:

- [Fix 1.13](https://github.com/corona-warn-app/cwa-wishlist/labels/Fix%201.13)
- [Fix 1.14](https://github.com/corona-warn-app/cwa-wishlist/labels/Fix%201.14)
- [Fix 1.15](https://github.com/corona-warn-app/cwa-wishlist/labels/Fix%201.15)
- [Fix 1.16](https://github.com/corona-warn-app/cwa-wishlist/labels/Fix%201.16)

## Suggested change

Update [README.md](https://github.com/corona-warn-app/cwa-wishlist/blob/master/README.md) to describe the current process used when it has been decided to implement an item from the [wishlist](https://github.com/corona-warn-app/cwa-wishlist/issues)

---
Internal Tracking ID: [EXPOSUREAPP-4024](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4024)

**Comment by dsarkar** [comment]
related https://github.com/corona-warn-app/cwa-backlog/issues/35

**Comment by dsarkar** [comment]
The issue be dealt with in Internal Tracking ID: [EXPOSUREAPP-4024](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4024)

**Comment by MikeMcC399** [comment]
The [README in cwa-backlog](https://github.com/corona-warn-app/cwa-backlog#readme) has been updated with the following text:

"This backlog repository was archived on March 30th, 2021. All issues from the backlog repository, including the closed ones, have been transferred to active repositories, i.e. no issue has been lost. For reasons of transparency we have archived this repository in preference to deleting it. This allows previous links to issues in the backlog to continue to work, due to GitHub's automatic re-direction to the transferred issue in its new repository location.

Why has this repository been archived? For some time the backlog repository had not been used for its original purpose and instead issues are usually taken care of in the repository where they were created. Keeping issues in the original repository has the advantage of not mixing up Android, iOS, documentation, website and wish-list items together with other issues.

Archived repositories are read-only. Closed issues in an archived repository can be read, but not re-opened or commented on. Therefore, by transferring issues from the backlog repository to other active repositories we allow the community to comment and re-open closed issues if necessary.

Originally the backlog repository was intended to show issues in the pipeline of being solved. Instead, we now mark issues in the active repositories with labels "Fix" + release number to show that there is a plan to fix the issue. This means that the issue has a corresponding internal development status which is one of OPEN, ANALYZING, IN PROGRESS, COMPLETED or CONFIRMED (i.e. tested). The Fix label stays with the issue even after the fix has been released and the issue has been closed."

https://github.com/corona-warn-app/cwa-backlog/issues/35 was closed on March 9, 2021.

----

Now the [README in cwa-wishlist](https://github.com/corona-warn-app/cwa-wishlist/blob/master/README.md) needs to be updated correspondingly to document how wishlist items, which are planned for implementation, are handled.

**Comment by Ein-Tim** [comment]
Suggested text:

"If an issue is selected to be implemented in a future release of the Corona-Warn-App, the community managers will apply a label which says `Fix` and the number of the version in which the feature will get implemented" 

How does this sound to you @MikeMcC39 (I won't provide a PR instantly, no worries 😇😉)?

**Comment by MikeMcC399** [comment]
@Ein-Tim 

The existing text from the [cwa-wishlist README.md](https://github.com/corona-warn-app/cwa-wishlist/blob/master/README.md) starting at [**Structure**](https://github.com/corona-warn-app/cwa-wishlist/blob/master/README.md#structure), which needs modifying, says:

---
## Structure

The repository does not contain any code. The [issue tracker](https://github.com/corona-warn-app/cwa-wishlist/issues) contains ideas for new features or enhancements of existing ones.

Issues will be scanned regularly by members of the CWA Github organization and discussed with the product management and the RKI. If an issues is selected to be implemented in a future release of the Corona-Warn-App, it will be moved to the [CWA Backlog Repository](https://github.com/corona-warn-app/cwa-backlog).

---

I defer to @dsarkar about your text suggestion.

**Comment by dsarkar** [comment]
Suggestion:

"
Structure
---
The repository does not contain any code. The issue tracker contains ideas for new features or enhancements of existing ones.

Issues will be scanned regularly by members of the CWA Github organization and discussed with the product management and the RKI. If an **issue** (**TYPO!**) is selected to be implemented in a future release of the Corona-Warn-App, it will be moved to the CWA Backlog Repository. Note that the backlog repository was archived on March 30th, 2021. The procedure had been changed already before: We now mark issues in the active repositories, including this one,  with labels "Fix" + release number to show that there is a plan to fix or implement the issue. This means that the issue has a corresponding internal development status which is one of OPEN, ANALYZING, IN PROGRESS, COMPLETED, or CONFIRMED (i.e. tested). The Fix label stays with the issue even after the fix has been released and the issue has been closed. 

...
"

**Comment by ndegendogo** [comment]
> If an issue (TYPO!) is selected to be implemented in a future release of the Corona-Warn-App, it will be moved to the CWA Backlog Repository. 

@dsarkar I am confused - my understanding was that the selected issues are tagged but **not** moved to the backlog repo?

**Comment by MikeMcC399** [comment]
@dsarkar 

New suggestion based on your text:

"The repository does not contain any code. The issue tracker contains ideas for new features or enhancements of existing ones.

Issues will be scanned regularly by members of the CWA GitHub organization and discussed with the product management and the RKI.  If it is decided to fix an issue or to implement a suggestion from an issue then the issue will be marked up in the originating repository (including in this one) using a label "Fix" + release number. This means that the issue will have a corresponding internal development status which is one of OPEN, ANALYZING, IN PROGRESS, COMPLETED, or CONFIRMED (i.e. tested). The Fix label stays with the issue even after the fix or enhancement has been released and the issue has been closed.

(Note: Originally the [CWA Backlog Repository](https://github.com/corona-warn-app/cwa-backlog) was used to track planned fixes and enhancements. All items from that repository have been redistributed and the now empty [CWA Backlog Repository](https://github.com/corona-warn-app/cwa-backlog) was put into archive status on March 30th, 2021.)"

**Comment by dsarkar** [comment]
@Ein-Tim @MikeMcC399 @ndegendogo @Ein-Tim 

Thanks to everybody. The last suggestion is very nice. Best wishes, and a nice Sunday afternoon.

**Comment by MikeMcC399** [comment]
@dsarkar 
> I would consider it as final version.

Would you like me to put the text change into a PR?

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Your last suggestion sounds good, but I would say "was archived on March 30th, 2021".

**Comment by MikeMcC399** [comment]
@Ein-Tim 

I used the wording I posted because there was nothing of significance archived in the sense of "to store electronic information that you no longer need to use regularly" because actually all the information was moved to other active (not archived) repositories. So the only things which were archived was the issue about the archiving and the README. The rest of the repository was not archived.

Your wording suggestion is simpler, I admit. I think it is just a matter of preference.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

You got me (; Yes, there actually wasn't anything achieved, so I think your wording is good too!

Have a nice evening!

**Comment by MikeMcC399** [comment]
I have created a PR #448 for the change to [cwa-wishlist README.md](https://github.com/corona-warn-app/cwa-wishlist/blob/master/README.md) regarding using Fix labels instead of using the [CWA Backlog Repository](https://github.com/corona-warn-app/cwa-backlog).
