### ISSUE TITLE
[Contact Diary] Notification to add Contacts of today

### ISSUE THREAD

**Issue by jucktnich** [corona-warn-app/cwa-wishlist#381]
## Current Implementation
Today you have to remember to add your contacts of today.

## Suggested Enhancement
Add setting to activate a notification at a certain time.

## Expected Benefits
Don't forget to add your contacts of the day.

**Comment by Ein-Tim** [comment]
Hey @jucktnich 


This has already been proposed in #294. 

All issues regarding the contact diary can be found in #310.

Please monitor this issue and follow up there if necessary.

Thanks and stay safe!

**Comment by dsarkar** [comment]
@jucktnich Anyway thanks for contributing!
@Ein-Tim Thanks for pointing out duplicate!
