### ISSUE TITLE
Add illustration to „Data Donation“ Settings

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#382]
## Current Implementation
All setting menus (exposure logging, etc.) have a illustration but the data donation one.

## Suggested Enhancement & Expected Benefits
Add a illustration to the data donation settings to be consistent with the other menus.
Also, users will feel it more pleasant to activate data donation if there isn't only text which they have to read but also a small illustration.

## Steps to reproduce (iOS)

1. Open CWA 
2. Scroll to the bottom 
3. Click on "Settings"
4. Click on "Data Donation"
5. See no illustration 

<details>
<summary>Screenshots</summary>

Exposure Logging Settings:

<img src="https://user-images.githubusercontent.com/67682506/110125011-1fc48680-7dc3-11eb-808e-15ef58427556.png" width="300">

Data Donation Settings:

<img src="https://user-images.githubusercontent.com/67682506/110125090-38cd3780-7dc3-11eb-9fca-be39cc1268b5.png" width="300">

</details>

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Could you add steps-to-reproduce and a screenshot?

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Added to OP.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
That's interesting because on Android there is a picture. I haven't got the final version of CWA Android 1.13.x yet. When Google Play Store gives me access to it, I will post a screenshot for you to compare.

**Comment by dsarkar** [comment]
@Ein-Tim @MikeMcC399 ok, thanks. We will wait for @MikeMcC399's screenshot.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Here are the screenshots from CWA Android 1.13.2 installed from Google Play Store. You can compare to how it looks on iOS and if it is only iOS which should be changed, then this issue should probably be moved to the iOS repository.

In your steps to reproduce, you wrote:

> 1. Open CWA
> 2. Scroll to the bottom
> 3. Click on "Settings"
> 4. Click on "Data Donation"
> 5. See no illustration

- On Android there is no access to "Settings" from the bottom of the screen. The access is via the three-dot icon on the top right.

- There is nothing in the Android "Settings" menu called "Data Donation". There is only "Share Data". Could you post a screen shot of your iOS "Settings" menu please?

---
This screen is shown after installing, updating or after resetting the app. It contains no illustration.

Steps to reproduce:
1. In CWA tap three-dot icon > Settings > Reset App 
2. RESET APP and confirm
3. Tap LET'S GET STARTED, tap NEXT
4. Tap ACTIVATE EXPOSURE LOGGING & Turn on
5. Tap NEXT, tap NEXT
6. Note the "Share Data" screen which has no picture.

![Share Data in Onboarding](https://user-images.githubusercontent.com/66998419/110217022-2a117e00-7eb2-11eb-8136-28ba2aeec315.png)

---

This screen is shown when accessing Share Data from Settings.

Steps to reproduce:
1. In CWA tap three-dot icon > Settings > Share Data
2. Note the "Share Data" screen with a picture.

![Share Data in Settings](https://user-images.githubusercontent.com/66998419/110217116-ab691080-7eb2-11eb-889f-20f4ccfa64bb.png)

**Comment by Ein-Tim** [comment]
> Here are the screenshots from CWA Android 1.13.2 installed from Google Play Store. You can compare to how it looks on iOS and if it is only iOS which should be changed, then this issue should probably be moved to the iOS repository.

Thank you for the screenshot Mike! 
I will open a new issue in the iOS Repo soon and close this issue, since this seems like a bug (Android Showing an illustration, iOS not).

>There is nothing in the Android "Settings" menu called "Data Donation". There is only "Share Data". Could you post a screen shot of your iOS "Settings" menu please?

Sorry, my bad, it's called "Share Data" too. 
Here a screenshot from the settings:

>This screen is shown after installing, updating or after resetting the app. It contains no illustration.

I think it's intended that there isn't an illustration during the onboarding, but there should be an illustration in the settings.

**Comment by Ein-Tim** [comment]
Moved to https://github.com/corona-warn-app/cwa-app-ios/issues/2160.
 Thaks @MikeMcC399 for your help here!

**Comment by dsarkar** [comment]
@Ein-Tim @MikeMcC399 Thanks a for for analysing. Will create JIRA for iOS.
