### ISSUE TITLE
Widgets for showing risk level and test results

### ISSUE THREAD

**Issue by walamana** [corona-warn-app/cwa-wishlist#383]
There is a similar issue #26 only for IOS, but I think this is a feature, both plattforms could benefit from.

## Feature description

Adding a widget could keep people informed about their current risk level and even test results. This could also help keeping users aware, that the app is still functioning, maybe even encourage them to use it more often.

Possible views could show information about:
- Their current risk level
- The status of test results
- people / places they added into their diary (maybe even the ability to quickly add other people/places)
- quick figures about the current Covid-19 situation

though, I think the first two would be the most important. 

## Problem and motivation
I head from some people around me, that they uninstalled the app, because they thought it's not working (or just thought it would be useless, because it didn't show them anything). A widget on the home screen could resolve this issue and keep people informed about the current status of their exposure service. 

## Is this something you're interested in working on

Yes

**Comment by Ein-Tim** [comment]
@walamana 

There is another one for Android too: #13.

Maybe we should focus on #13 & #26 to not let the discussion get multithreaded.

**Comment by walamana** [comment]
Ou, How could I oversee that one 🙈. I'll delete it and add something on issue#13

**Comment by walamana** [comment]
Duplicate of #13
