### ISSUE TITLE
Location-IDs for anonymously checking possible exposure

### ISSUE THREAD

**Issue by klindt** [corona-warn-app/cwa-wishlist#384]
## Feature description

Provide locations (retail store, restaurants, venues etc.) with an identifier to enable tracing based on _time/location_ in addition to ephemeral Bluetooth identifiers received from people in the vicinity. This (time/location) identifier should be added to the list of ephemeral Bluetooth identifiers on the local device and be used as an aggregate/cluster identifier after notification of a possible exposure during a visit. 

## Problem and motivation

In Germany there is currently a limit of people allowed to enter a retail location at the same time to prevent crowding. At some locations one have to register your contact information in order to trace contacts after notification of a positive case during that time and location. If a retail location could provide a "location id" via QR-Code to its patrons, which is included into the list of ephemeral Bluetooth identifiers saved locally on the device. This enables the app to warn all persons present at a location during a certain timeframe by using the same matching algorithms used for intra-person exposure. It is also possible to include and match persons not having "checked in" at the location via code scanning in the app but by providing contact information to the location by other means instead (e.g. register contact information manually  which is mandatory during times of contact restriction).

If location ids could be generated by anyone, this could also enable check-in at private gatherings not unlike https://www.luca-app.de/ .

This approach respects the privacy of the individual as location ids are locally stored and compared. Location ids also don't have to be ephemeral if the id is used in conjunction with the time of check-in (scanning location id code) and possibly checking out (scaning code a second time?) or  using change in location by the mobile device... 

Just an idea to make gatherings (private/public/retail) a little more traceable using existing infrastructure...

## Is this something you're interested in working on

Only conceptionally.
---

Internal Tracking ID: [EXPOSUREAPP-3034](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3034) (Overview)
Internal Tracking ID: [EXPOSUREAPP-5080](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5080) (iOS)
Internal Tracking ID: [EXPOSUREAPP-4741](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4741) (Android)

**Comment by Ein-Tim** [comment]
Related Issues:

#59
#70
#77
#138
#140
#162

Overview: #338

**Comment by dsarkar** [comment]
@klindt Thanks for the suggestion. There are several similar proposals as pointed out by @Ein-Tim. Actually there is work in progress related to this new feature, see for example corona-warn-app/cwa-app-android#2456

**Comment by heinezen** [comment]
Hello everyone,

This feature has been implemented in CWA 2.0 as part of the event registration feature.

This issue will be closed. If you have new ideas for the current implementation of the feature, please consider opening a new issue.

----
Corona-Warn-App Open Source Team
