### ISSUE TITLE
Contact diary: Provide additional info to locations 

### ISSUE THREAD

**Issue by stefan-schoene** [corona-warn-app/cwa-wishlist#385]
## Current Implementation
Since 1.14 the contact diary provides means to store extended information for contacts and locations, which is great. The options for contacts are more advanced than those for locations though (masks, inside/outside)

## Suggested Enhancement
Those options should be available for locations as well (masks, inside/outside).

## Expected Benefits
This would probably be helpful in the coming months when more locations are reopened to quickly store additional information,
 e.g. getting a coffee at the outdoor area of a Café, so a user could quickly specify that he didn't wear a mask at his table, but also that he stayed outdoors. This would be way easier than entering all those details into the notes field and the user could see those details on first glance like he can with contact meetings.

---
Internal Tracking ID: [EXPOSUREAPP-3034](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3034) (Overview)

**Comment by dsarkar** [comment]
@stefan-schoene Thanks for the suggestion. We will forward this to the developers.
