### ISSUE TITLE
[Overview] Issues reg. the UI/UX & Text

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#386]
**This is an overview over all open issues regarding the UI/UX & text** (to keep track and avoid duplicates). 

## UX/UI

| Issue | Title | Status | JIRA |
| --- | --- | --- | --- |
| #1 | More varieties of skin tones in the illustrations | **OPEN** | [EXPOSUREAPP-2132](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-2132) |
| #15 | Color blind accessibility | **OPEN** | [EXPOSUREAPP-2179](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-2179) |
| #47 | Give the logo more room to breathe | **OPEN** | [EXPOSUREAPP-2117](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-2117) |
| #78 | Improve logo / app icon design | **OPEN** | [EXPOSUREAPP-2117](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-2117) |
| #121 | App risk status screen: misleading wording | **OPEN** | [EXPOSUREAPP-2067](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-2067) |
| #454 | Replace "%1$d" with "einem" for quantity "one" in strings.xml | **OPEN** | not mirrored |
| #511 | (Darkmode) QR-Code should have a black background | **OPEN** | [EXPOSUREAPP-7301](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7301) |
| #512 | Use the same style for showing qr codes | **OPEN** | [EXPOSUREAPP-7272](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7272) |
| #593 | DCC-CWA-Icon | **OPEN** | not mirrored |
| #687 | Better text for when the red warning goes away | **OPEN** | [EXPOSUREAPP-11348](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11348)
| #698 | The scan purpose should be transparent | **OPEN** | [EXPOSUREAPP-10770](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10770) |
| #764 | Button to delete test inconveniently placed when test added | **OPEN** | [EXPOSUREAPP-11446](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11446) |
| #771 | Use monospaced font to display certificate metadata | **OPEN** | [EXPOSUREAPP-11562](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11562) |
| #818 | Bestätigung für Geburtsdatum bei Testregistrierung | **OPEN** | [EXPOSUREAPP-12596](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12596) |
| #825 | Less generic notification | **OPEN** | [EXPOSUREAPP-12909](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12909) |
| #854 | Theme switcher | **OPEN** | [EXPOSUREAPP-1900](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-1900) |
| #860 | Implement implied risk banner if PCR positive | **OPEN** | not mirrored |

## Text-Issues

| Issue | Title | Status | JIRA |
| --- | --- | --- | --- |
| #387 | AHA + L + A - rules instead of AHA | **OPEN** | [EXPOSUREAPP-5671](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5671) |
| #492 | Rename Event to Veranstaltung in German translated apps and website | **OPEN** | [EXPOSUREAPP-7154](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7154) |

This overview was last updated on 21.02.2023 (dd.mm.yyyy).

---
Internal Tracking ID: [EXPOSUREAPP-5666](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5666)

**Comment by dsarkar** [comment]
@Ein-Tim Many thanks again for taking care of this and other overviews.  We mirror the overviews  back to internal tickets and we could optimise the process if we can find new entries or changes int these tables faster:

We will mark entries mirrored already to the internal overview with "m" in STATUS.

Can you mark new rows (and changes in rows) with "X" in STATUS.
If you have a nicer idea, let me know please.  Thanks.

**Comment by Ein-Tim** [comment]
@dsarkar 

For sure I can do this! Should we still leave the internal tracking ID  in the overviews?

**Comment by dsarkar** [comment]
@Ein-Tim 

> Should we still leave the internal tracking ID in the overviews?

Yes, please.

**Comment by ndegendogo** [comment]
> > Should we still leave the internal tracking ID in the overviews?

> Yes, please.

@dsarkar @Ein-Tim 'internal' means the ticket number of Jira, yes?
Thanks, I appreciate this a lot!

**Comment by dsarkar** [comment]
@ndegendogo At least when I say "Internal" I mean the Tracking IDs EXPOSUREAPP-nnnn in the JIRA system, which we use internally.

**Comment by Ein-Tim** [comment]
@dsarkar 

Just FYI, I'm quite busy this week so probably I'll update the overviews on the week-end.

**Comment by dsarkar** [comment]
@Ein-Tim Not sure if I explained well before, just to make sure: The "m" we will use once the row is mirrored to the JIRA overview ticket  EXPOSUREAPP-5666, i.e. me or another member will set it, once mirrored. It is not related to the JIRA ticket shown it the same row, but the ticket for this overview. So, when you add a new row do not put an "m" but "X". If you modify/update a row also put an "X", and if there is already a "m" don't delete the  "m". Thanks!  All this, so we can find easier new entries or modified entries, and then mirror it back to JIRA. Thanks!

**Comment by Ein-Tim** [comment]
Okay thanks @dsarkar.

I added the last row (https://github.com/corona-warn-app/cwa-documentation/issues/566) and wrote:
"**OPEN** X", this is correct, or? 😁

**Comment by crlosmen** [comment]
Ok

**Comment by Ein-Tim** [comment]
@dsarkar As wished, I've updated all overviews.

Have a nice week-end (:

**Comment by vaubaehn** [comment]
Just stumbled in to say
@Ein-Tim : awesome.

**Comment by Ein-Tim** [comment]
@dsarkar Are you going to mirror the overviews back to JIRA? I see very many Xs in all the overviews (;

**Comment by Ein-Tim** [comment]
As [CWA development is ending](https://www.coronawarn.app/en/faq/results/#ramp_down), I'm discontinuing this overview.
