### ISSUE TITLE
[iOS] Remove EnError 13 notification

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-wishlist#388]
## Current Implementation

ENError 13 notification pops up for some users after CWA updates and creates confusion.
There is a link to the FAQ in the notification: https://www.coronawarn.app/en/faq/#ENError13 

## Suggested Enhancement

- suppress error notification 
- Instead show  on risk card:
"Next update in 24 h" or similar instead of the usual 
"Updated: Today hh:mm"
- Maintain risk card green (or red, if it was red already), instead of showing card "Exposure Check failed"  

## Expected Benefits

- Avoid confusion: Users interpret this as a critical error.

---
Internal Tracking ID: [EXPOSUREAPP-5745](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5745)

**Comment by Ein-Tim** [comment]
@dsarkar 

I guess I'm not telling news but this will be implemented in version 2.18: https://github.com/corona-warn-app/cwa-app-ios/issues/4163#issuecomment-1031818212

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for pinging.

**Comment by Ein-Tim** [comment]
This issue should be closed now.
