### ISSUE TITLE
Missing reference to contact journal on Increased Risk

### ISSUE THREAD

**Issue by gleichda** [corona-warn-app/cwa-wishlist#392]
## Current Implementation

Currently when getting an increased risk there is only written `Exposures on x days with increased risk` and on the details part the date of the last exposure is listed, but there is no reference to to the contact journal where the other risk encounters are listed.

## Suggested Enhancement

Add some text reference and maybe a `Jump to contact journal button` would be good.

## Expected Benefits

The contact journal is a quite new and not by everybody used feature. Also if you don't follow the development you might not know that the high risks are shown there. 

Reasons why this might be important: 

- Probably you have workn protective equipement (e.g. as a healthcare worker)
- You want to calculate the day when it makes sence to get tested

---
Internal Tracking ID: [EXPOSUREAPP-3034](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3034) (Overview)
Internal Tracking ID: [EXPOSUREAPP-5829](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5829)
Internal Tracking ID: [EXPOSUREAPP-5883](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5883)

**Comment by dsarkar** [comment]
@gleichda Thanks for contributing. Internally tracked. Best wishes, DS

---
Corona-Warn-App Open Source Team
Internal Tracking ID: [EXPOSUREAPP-3034](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3034) (Overview)

**Comment by Ein-Tim** [comment]
This will be included in version 2.4: https://github.com/corona-warn-app/cwa-app-ios/pull/2748:

<img src="https://user-images.githubusercontent.com/10122052/119137342-02f23380-ba41-11eb-8390-1746fc9f3b3d.png" width="300">
<img src="https://user-images.githubusercontent.com/10122052/119137334-008fd980-ba41-11eb-975c-81847506e0d1.png" width="300">

**Comment by heinezen** [comment]
Hello everyone,

This has been integrated into the current CWA release 2.4.

----
Corona-Warn-App Open Source Team
