### ISSUE TITLE
Display statistics trend values (percentages) in addition to symbols

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-wishlist#395]
## Current Implementation

The statistics tiles use an arrow and color to indicate the trend for values shown in the app

For instance, today, Tuesday, March 16, 2021 the Trend for the 7-Day Average of Confirmed New Infections is shown as upwards.

The fact that the trend actually represents an increase of 23.0% compared to the previous week is not explicitly displayed. The red color just says that the increase was more than 5%.

![Confirmed New Infections 2021_03_16](https://user-images.githubusercontent.com/66998419/111299614-71d19b80-8650-11eb-998a-c720e81b0735.jpg)

Comparison<br>Value \ Steady band % | Daily<br>1% | Weekly<br>5%
--- | --- | ---
Confirmed New Infections<br>7-Day Average | | ✔️ 
Warnings by App Users<br>7-Day Average | | ✔️ 
7-Day Incidence | ✔️  |
7-Day R Value | ✔️  |

## Suggested Enhancement

The app should show the numerical value of the trend in % terms, in addition to the trend symbol.

If the % change is shown then the UI also needs to display whether it is a weekly comparison or a daily comparison. A daily 1% change is approximately equivalent to a 7% weekly change.

## Expected Benefits

The magnitude of the trend should be clearer to users so they can better judge the overall national pandemic situation.

----
Internal Tracking ID: [EXPOSUREAPP-5840](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5840)

**Comment by heinezen** [comment]
Thank you for the submission. We've added this to the wishlist in Jira as [EXPOSUREAPP-5840](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5840).


----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
Extensive trend information is available through
https://www.coronawarn.app/en/analysis/ > https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/COVID-19-Trends/COVID-19-Trends.html?__blob=publicationFile#/home

I withdraw this request, since the % comparison with the previous day is not so helpful. The graphs available through the above link give a much better picture.
