### ISSUE TITLE
Add screenshots for planned versions/features to website

### ISSUE THREAD

**Issue by heinezen** [corona-warn-app/cwa-wishlist#397]
## Feature description

The [CWA website's screenshot section](https://www.coronawarn.app/de/screenshots/) already contains screenshots for the *current* version of the app. It would be nice to see a preview of future versions, especially new features, on that page or on Github too.

Related: https://github.com/corona-warn-app/cwa-wishlist/issues/258

---
Internal Tracking ID: [EXPOSUREAPP-5837](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5837)

**Comment by Ein-Tim** [comment]
The screenshot delivery in the website usually takes place during the RC period of the releases, so technically it would not be a problem to show screenshots of the upcoming versions.

**Comment by larswmh** [comment]
Closing this issue as the related internal ticket is set to `obsolete`.

Developer comment:
> Nice to have and huge effort / not possible. So sorry, but rejected.
