### ISSUE TITLE
Release on UK App Store

### ISSUE THREAD

**Issue by jonjardine** [corona-warn-app/cwa-wishlist#40]
Please release the iOS and Android apps in the UK store.

**Comment by schuhmi2** [comment]
Guess this is worth the upvote since there are over 110k British expats in Germany who may be affected, plus British service personnel based in Paderborn, Monchengladbach and Wulfen.

**Comment by vollmersj** [comment]
Second that - noticed it when it came out [https://github.com/corona-warn-app/cwa-documentation/issues/260](https://github.com/corona-warn-app/cwa-documentation/issues/260)

**Comment by DaGaMs** [comment]
Plus the fact that the UK is probably the single biggest risk country, so you _really_ want people with links to the UK to use the app while in Germany

**Comment by PivotNeilTarrant** [comment]
There has also been significant immigration of young, 'digital natives' (to use that horrible term) in recent years from the UK due to Brexit (for example myself). Being such recent immigrants our accounts are still tied though subscriptions and years of digital content.

**Comment by janek26** [comment]
https://www.youtube.com/watch?v=2LZYuzgArVQ

**Comment by tkowark** [comment]
As noted in https://github.com/corona-warn-app/cwa-backlog/issues/9#issuecomment-652980998 , the Corona-Warn-App is now also available in App stores for the UK!

**Comment by jonjardine** [comment]
Many thanks for all your efforts!

**Comment by tjbassindale** [comment]
Wonderful, thanks for releasing on UK store!
