### ISSUE TITLE
Porting existing data to a new phone

### ISSUE THREAD

**Issue by KST1810** [corona-warn-app/cwa-wishlist#400]
## Current Implementation

As of right now, data is only stored locally (as it should be).
Yet, when switching to a new phone, all of the data is lost.

## Suggested Enhancement

Upon request of the user, all of the data could be uploaded to a server and downloaded to the new device. This could happen when scanning a QR code. 
After the data has been downloaded it should be deleted.

## Expected Benefits

This enhancement is a rather "niche" addon. Yet, it can help those setting up a new phone to keep their data to remain informed about their exposure risk. It further encourages downloading the CWA onto the new device.

**Comment by thomasaugsten** [comment]
Google and Apple is not allowing the ENF data on more than one phone. This is the reason why this data is not included in phone backup

**Comment by KST1810** [comment]
Hi, thanks for the clarification!

What I was thinking was something along these lines:

1) The user requests to port the data
2) The data is securely uploaded
3) The user scans a QR Code which starts the download of said data
4) The data is deleted from the server

Would something like this work or is it too complicated for too little gain in usability?

**Comment by thomasaugsten** [comment]
Only Apple and google has access to this data. I dont think they will introduce such a process

**Comment by KST1810** [comment]
Too bad :(
Should I close this thread then?

**Comment by Ein-Tim** [comment]
I think this can be closed, since there is also already a open issue reg. this: #8.
You could comment your proposal there.
