### ISSUE TITLE
Contact Journal: Select and delete unused entries

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-wishlist#405]
## Current Implementation

Edit People / Places allows individual selection and deletion or Remove All.

Some entries will not be needed again as the history of contacts is aged out day-by-day until 14 days have expired. There is no convenient way to purge these entries in any grouped way.

## Suggested Enhancement

In Edit People / Places add a button
"Select Unused"
mark those entries as selected and allow any entry to be selected or de-selected.

Add a button
"Delete Selected".

Consider implementing this in some way as part of the existing wishlist item
"Improve Contact Journal usability for editing and deleting entries"
https://github.com/corona-warn-app/cwa-wishlist/issues/334

## Expected Benefits

Ease of use for Contact Journal.
Only relevant People or Place entries will be presented for selection to add to a particular day.

Otherwise as time goes on the list of entries will tend to get longer and become more difficult to use.

---
Internal Tracking ID: [EXPOSUREAPP-3034](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3034)
Internal Tracking ID: [EXPOSUREAPP-6158](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6158)

**Comment by achisto** [comment]
Related: #322 (one time contacts)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks.

**Comment by dsarkar** [comment]
Internal Tracking ID: EXPOSUREAPP-3034
Internal Tracking ID: EXPOSUREAPP-6158
