### ISSUE TITLE
Contact Journal: Make it possible to search locations and people

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#410]
## Current Implementation
Currently it is not possible to split locations or people in any form. It is really annoying and takes long (if you have many people/locations stored) to search for the person/location you want to add.
 
## Suggested Enhancement
Add a search field to the top of the edit screen and to the top of the screen where you add the entries. 

## Expected Benefits
Better usability (=better UX) and less time spend on searching for people/locations.

---
Internal Tracking ID: [EXPOSUREAPP-3034](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3034)
Internal Tracking ID: [EXPOSUREAPP-6159](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6159)

**Comment by dsarkar** [comment]
@Ein-Tim Thanks!

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-3034](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3034)
Internal Tracking ID: [EXPOSUREAPP-6159](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6159)

**Comment by Guenni1975** [comment]
DE:
Gibt es schon was neues ob eine Suchfunktion demnächst geplant ist? Bei vielen Personen und Orten wird die Liste schnell unübersichtlich! 

EN:
Is there anything new whether a search function is planned soon?  If there are many people and places, the list can quickly become confusing!

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
