### ISSUE TITLE
Anonymuous enter tokens for venues at certain time windows (i.e. retail shops, hardware stores) 

### ISSUE THREAD

**Issue by mfs12** [corona-warn-app/cwa-wishlist#411]
## Feature description

- request a token to enter a venue at a certain time window
- book an enter token for a venue
- cancel a booked enter-token for a venue  

## Problem and motivation

Since many shops are only allowed to provide shopping for customers with a date in time windows, there is a need to offer such enter tokens. When offering such a service a user should be allowed to keep as much information private as possible. This way  customers can stay anonymous while entering tokens providing same safety as other solution but keeping the user*s data private.

So far most of those solution are proprietary solutions and as such concept sounds simple it is likely that there are a lot of solutions fail user*s data private.  The cluttering of private date over commercial services would be avoided as well.

This feature would also help retailers to offer such a service with little cost and a low technical barrier. Probably small retailers with little technical experience would profit most.

This feature could even allow short-term/ad-hoc  access.
 
---
Internal Tracking ID: [EXPOSUREAPP-6172](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6172)

**Comment by vaubaehn** [comment]
For me this sounds interesting in general. One could even think to connect the check-in of the token with an automatic check-in of CWA's upcoming event registration feature.
But I think it's not as trivial to implement as it looks at first glance.

@mfs12 , would you volunteer to go a bit more into detail in form of a written draft, how this could be implemented and how could be the workflows, e.g., which platforms to use (registration portal? CWA-client's needs, backend server needs. Where would back-channels for communication between these parts needed?), how to keep efforts for hosts and guests as little as possible, etc.

We could then go and discuss here. In the end there could be a rough but implementable concept.

As there are some "big things" moving and being implemented currently, I think it's not unrealistic that such a service might go "under consideration" for future implementations.

For me, currently it looks like we will need CWA for an undetermined long time into the future...

**Comment by mfs12** [comment]
@vaubaehn I am not much involved into this project. Therefore I would wait for some feedback from the developers before trying to specify something.

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-6172](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6172)

**Comment by larswmh** [comment]
Closing this issue as the related internal ticket is set to `completed`.

Fixed in Version 2.0 by adding the functionality to print a QR Code, so that attendees of an event can scan the printed QR-Code for check-in.
