### ISSUE TITLE
Feature Requests & Voting directly within the APP

### ISSUE THREAD

**Issue by Velligis128** [corona-warn-app/cwa-wishlist#415]
## Feature description

* Users should be able to propose new features / enhancements directly within the app (like here, but with better UX)
  * This needs of course a automatic duplicate check
* User should be able to vote on proposed new features / enhancements within the app

## Problem and motivation

If we are looking on the enhancements and development of the app it is quite obvious, that since the release in june 2020 not many new features were released. We are missing out on ideas of million of users, which are not aware of the possibility of proposing new features or are not firm with github. In my opinion it is not accepable, to exclude all non-it-related users from proposing new ideas.

## Is this something you're interested in working on

As always - happy to help with design. Coding is not my strong suite anymore.

**Comment by Ein-Tim** [comment]
Closely related to #299.

**Comment by Velligis128** [comment]
More or less a duplicate to 299
