### ISSUE TITLE
Integrate with EU Digital COVID Certificate for vaccination, recovery and test (previously called EU Digital Green Certificate)

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-wishlist#424]
## Problem description

The EU's proposed [Digital Green Certificate](https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/safe-covid-19-vaccines-europeans/covid-19-digital-green-certificates_en) (now called [EU Digital COVID Certificate](https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/safe-covid-19-vaccines-europeans/eu-digital-covid-certificate_en)) is a personalized proof of COVID-19 health status. In terms of test status it concerns itself with non-infectious individuals.

CWA on the other hand uses pseudoanonymous data exchange regarding test results and shares positive tests pseudoanonymously back to the community of CWA users.

Users are sometimes forced to deal with different systems resulting out of one test because pseudoanonymous and personified data are handled completely separately.

## Feature Description

Integration of CWA into the [European Union's eHealth : Digital health and care](https://ec.europa.eu/health/ehealth/covid-19_en) proposed [Digital Green Certificate](https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/safe-covid-19-vaccines-europeans/covid-19-digital-green-certificates_en):

"A [Digital Green Certificate](https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/safe-covid-19-vaccines-europeans/covid-19-digital-green-certificates_en) is a digital proof that a person has been vaccinated against COVID-19, has recovered from COVID-19 or has a negative test result. The Digital Green Certificate is therefore a name used to collectively refer to 3 types of certificates: vaccination, recovery, test."

The feature proposal for CWA and for related processes, such as the [10C testing form](https://www.kbv.de/media/sp/Ansichtsexemplar_Muster10C.pdf), is to revise the test reporting mechanism so that there is one standardized way of reporting the results of a COVID-19 test back to the person being tested, so it can be automatically integrated into CWA and in parallel into a [Digital Green Certificate](https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/safe-covid-19-vaccines-europeans/covid-19-digital-green-certificates_en) in the case of a negative test.

"On 17 March 2021, the European Commission presented a proposal to create a Digital Green Certificate to facilitate the safe free movement of citizens within the EU during the COVID-19 pandemic. 

Digital Green Certificates will be valid in all EU Member State" 

## Timeline (according to [EU documents](https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/safe-covid-19-vaccines-europeans/eu-digital-covid-certificate_en#timeline))

- [x] **1 June** - EU Gateway (interconnection of national systems) goes live.
- [X] **1 - 30 June** - Warm-up phase: Member States can launch the certificate on a voluntary basis provided they are ready to issue and verify certificates, and have the necessary legal base in place.
- [X] **1 July** - The EU Digital COVID Certificate enters into application throughout the EU.
- [X] **1 July - 12 August** - Phase-in period: if a Member State is not yet ready to issue the new certificate to its citizens, other formats can still be used and should be accepted in other Member States.

## Integrated Features

- [X] Vaccination certificates (CWA 2.3)
- [X] PCR-Test certificates (CWA 2.4)
- [X] Rapid-test certificates (CWA 2.4)
- [ ] Add multiple certificates (CWA 2.5)
- [ ] Recovery certificates (CWA 2.5)

## Related Apps

- [CovPass-App](https://digitaler-impfnachweis-app.de/) (German language information only)
- [CovPassCheck-App](https://digitaler-impfnachweis-app.de/impfschutz-pruefen/) (German language information only)

### Recovery

[How do I tell the app that I recovered from COVID-19?](https://www.coronawarn.app/en/faq/#recovered)

---
Edit: Based on information from EU Press Room
[EU COVID-19 certificate must facilitate free movement without discrimination](https://www.europarl.europa.eu/news/en/press-room/20210422IPR02606/eu-covid-19-certificate-must-facilitate-free-movement-without-discrimination) April 29, 2021 I have changed the name from "Digital Green Certificate" to "COVID-19 certificate".

Edit: See also https://github.com/eu-digital-green-certificates/dgc-overview "Digital Green Certificate: Overview" Open Source Project.

Edit: https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/safe-covid-19-vaccines-europeans/eu-digital-covid-certificate_en now named "EU Digital COVID Certificate".

Edit: Add link to https://digitaler-impfnachweis-app.de/

---
Internal Tracking ID: [EXPOSUREAPP-6080](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6080)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for proposal. Internal Tracking ID: EXPOSUREAPP-6080

**Comment by Ein-Tim** [comment]
[n-tv](https://www.n-tv.de/panorama/Digitaler-Impfpass-noch-vor-den-Sommerferien-article22489636.html) talks about a planned implementation! 

(h/t @vaubeahn 🙂)

**Comment by alanrick** [comment]
Read this [optimistic news](https://twitter.com/anked/status/1382433412871507970). 
Very encouraging for the propagation and hence effectivity of the CWA.

**Comment by Ein-Tim** [comment]
This issue was mentioned in https://www.focus.de/corona-virus/impfung/corona-impf-nachweis-grosses-update-corona-warn-app-kuenftig-mit-digitalen-impfpass_id_13239972.html

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Thanks for closing the loop! The [Focus article - Großes Update: Corona-Warn-App künftig mit digitalen Impfpass](https://www.focus.de/corona-virus/impfung/corona-impf-nachweis-grosses-update-corona-warn-app-kuenftig-mit-digitalen-impfpass_id_13239972.html) refers back to this wishlist item #424.

[focus.de](https://www.focus.de/corona-virus/impfung/corona-impf-nachweis-grosses-update-corona-warn-app-kuenftig-mit-digitalen-impfpass_id_13239972.html) actually refers to [chip.de](https://www.chip.de) and the original article is posted under [chip.de - Digitaler Impfpass kommt in die Corona-Warn-App](https://www.chip.de/news/Digitaler-Impfpass-kommt-in-die-Corona-Warn-App_183404309.html).

**Comment by alanrick** [comment]
My understanding of this feature suggestion is that the test result and green-pass status can be fed back into the CWA app where it can be used in determining infection risks. E.g. If I have a green-pass I will not receive a high-risk notification after checking into an event where someone else later tests positive. But the certificate with my personal details is kept in a separate app. 

However, from the screenshots and description of the [article](https://www.focus.de/corona-virus/impfung/corona-impf-nachweis-grosses-update-corona-warn-app-kuenftig-mit-digitalen-impfpass_id_13239972.html) it implies that the CWA will in future contain personal information:

> Ein negatives Ergebnis eines Schnelltestes bleibt 48 Stunden in Corona-Warn-App gespeichert und dient als digitaler Nachweis. Dabei ist der Test personalisiert und es werden **Name und Geburtsdatum** der getesteten Person angezeigt.

Either the article is wrong, or there is some aspect of the mechanism that I have not understood. This is important to me because currently I show skeptics that there is no personal stored in the CWA, other than what I choose to write in the journal, and even there I don't type in full names.

**Comment by Ein-Tim** [comment]
> Either the article is wrong, or there is some aspect of the mechanism that I have not understood. This is important to me because currently I show skeptics that there is no personal stored in the CWA, other than what I choose to write in the journal, and even there I don't type in full names.

Please refer to this talk @MikeMcC399 and I had yesterday: https://github.com/corona-warn-app/cwa-wishlist/issues/489#issuecomment-827574263

**Comment by Ein-Tim** [comment]
The work on this just begun: https://github.com/corona-warn-app/cwa-app-ios/pull/2584

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> Seems like we'll see an integration in version 2.3.

I hope we'll see a blog entry on https://www.coronawarn.app/en/blog/ if that is what has been decided. @dsarkar did warn though in https://github.com/corona-warn-app/cwa-wishlist/issues/489#issuecomment-827736774 that the situation is "dynamic".

**Comment by MikeMcC399** [comment]
According to https://www.europarl.europa.eu/news/en/press-room/20210422IPR02606/eu-covid-19-certificate-must-facilitate-free-movement-without-discrimination from today, based on the EU parliament's debate yesterday (April 28, 2021) they are now calling it “EU COVID-19 certificate” - instead of "Digital Green Certificate", so I will modify the title and of the main issue.

Trying to interpret the information in the above link, I also come to the same conclusion as @dsarkar that the situation continues to be dynamic!

**Comment by dsarkar** [comment]
FYI https://github.com/eu-digital-green-certificates

**Comment by MikeMcC399** [comment]
@dsarkar 
Many thanks for the link!

https://github.com/eu-digital-green-certificates/dgc-overview so congratulations to Deutsche Telekom and SAP!

## About this Project

The digital green certificate implements the EU trustframework according the specification of the eHealth Network Interoperability Subgroup (https://github.com/ehn-digital-green-development/hcert-spec). 

To this end the European Commission has tasked Deutsche Telekom and SAP to develop the [Digital Green Certificates Gateway](https://github.com/eu-digital-green-certificates/dgc-gateway) as well as applications that may be used by all countries connected to the gateway. These include a national backend with an issuer component ( [Issuance Service](https://github.com/eu-digital-green-certificates/dgca-issuance-service), [Issuance Web](https://github.com/eu-digital-green-certificates/dgca-issuance-web) ) and an app to validate Digital Green Certificates ( [Verifier Service](https://github.com/eu-digital-green-certificates/dgca-verifier-service), [Verifier App - Android](https://github.com/eu-digital-green-certificates/dgca-verifier-app-android), [Verifier App - iOS](https://github.com/eu-digital-green-certificates/dgca-verifier-app-ios) ) as well as a wallet app to be used by the citizens of connected countries ( [Wallet App - Android](https://github.com/eu-digital-green-certificates/dgca-wallet-app-android), [Wallet App - iOS](https://github.com/eu-digital-green-certificates/dgca-wallet-app-ios) )."

**Comment by MikeMcC399** [comment]
This is also related to 
https://www.bundesgesundheitsministerium.de/coronavirus/faq-covid-19-impfung/faq-digitaler-impfnachweis.html
and
https://digitaler-impfnachweis-app.de/ which refers to the **CovPass-App** from RKI.

**Comment by MikeMcC399** [comment]
https://www.n-tv.de/panorama/Bund-startet-Test-fuer-digitalen-Impfnachweis-article22578846.html reports "Bund startet Test für digitalen Impfnachweis" with [CovPass-App](https://digitaler-impfnachweis-app.de/).

**Comment by Ein-Tim** [comment]
I wonder why this is not yet labeled as `Fix 2.3` @dsarkar 

Don't we integrate with the Digital Green Certificate in the next version? Even if it's not yet official, everybody can follow the (nearly finished) work in the prod. repos.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> I wonder why this is not yet labeled as `Fix 2.3` @dsarkar
> 
> Don't we integrate with the Digital Green Certificate in the next version? Even if it's not yet official, everybody can follow the (nearly finished) work in the prod. repos.

On Android, the [release_info_strings.xml for release/2.3.x](https://github.com/corona-warn-app/cwa-app-android/blob/release/2.3.x/Corona-Warn-App/src/main/res/values/release_info_strings.xml) says "You can now add your vaccination certificates in the app and present them via QR code. The app displays full vaccination protection 14 days after the final vaccination."

The [Digital Green Certificate](https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/safe-covid-19-vaccines-europeans/covid-19-digital-green-certificates_en) is more than just vaccination. It corresponds to the triad of vaccination, negative test or recovery. So I would not expect to see the integration in the 2.3 release, because the release text does not mention a certificate for negative test, nor for recovery.

@heinezen has added the [approved label](https://github.com/corona-warn-app/cwa-wishlist/labels/approved) to this issue. The  [Android v2.4.0-RC3 release candidate](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.4.0-RC3) mentions "Green certificate UI skeleton (EXPOSUREAPP-7516)" with PR https://github.com/corona-warn-app/cwa-app-android/pull/3283 so I suggest that 2.4 would be the next release to look at, as pieces are added to work with the [Digital Green Certificate](https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/safe-covid-19-vaccines-europeans/covid-19-digital-green-certificates_en).

**Comment by heinezen** [comment]
> I wonder why this is not yet labeled as Fix 2.3 @dsarkar
> Don't we integrate with the Digital Green Certificate in the next version? Even if it's not yet official, everybody can follow the (nearly finished) work in the prod. repos.

@Ein-Tim As @MikeMcC399 said, more features for the EU COVID certificate are coming in subsequent releases. It's better to think of it as a **certificate infrastructure** than just one single certificate, although 2.3 will implement the most important parts as far as I know.

It should also be noted that CWA 2.3 (and maybe 2.4) will likely release before the "official" start date of the certificate, so there might be last-minute adjustments based on feedback from the testing and staged rollout phases. Furthermore, backend infrastructure for the health departments is built in parallel in the background. As of now, it is difficult to determine when everything is ready, but the feature releases implementing the certificate will probably come in short succession in June/Juli.

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
The original link https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/safe-covid-19-vaccines-europeans/covid-19-digital-green-certificates_en now redirects to
https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/safe-covid-19-vaccines-europeans/eu-digital-covid-certificate_en where it shows the label:

**EU Digital COVID Certificate**

The contents there, including the timeline, have also been updated.

**Comment by heinezen** [comment]
@MikeMcC399 Thanks for updating us on that. I put the timeline in your top post, so that everyone knows what's going on.

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
According to https://www.n-tv.de/panorama/Den-Digi-Impfpass-gibt-s-beim-Apotheker-article22605257.html "Übertrag aus Impfbuch ab Montag" [CovPass-App](https://digitaler-impfnachweis-app.de/impfschutz-pruefen/) will be available on Monday.

**Comment by MikeMcC399** [comment]
https://www.n-tv.de/panorama/Digitaler-Corona-Impfpass-ab-Donnerstag-verfuegbar-article22607422.html "Digitaler Corona-Impfpass ab Donnerstag verfügbar" tells us that CWA 2.3.2 was released last night and that Bundesgesundheitsminister Jens Spahn is going to make an announcement tomorrow, Thursday, Jun 10, 2021 regarding the [CovPass-App](https://digitaler-impfnachweis-app.de/impfschutz-pruefen/).

**Comment by MikeMcC399** [comment]
CWA Version 2.3 has been released and this version includes the functionality to scan in SARS-CoV-2 vaccination certificates. See https://www.coronawarn.app/en/blog/.

[CovPass-App](https://digitaler-impfnachweis-app.de/impfschutz-pruefen/) is available now and the FAQs
https://digitaler-impfnachweis-app.apps.public.bfarm.de/faq/ say:

> **Gilt der digitale Impfnachweis nur in Deutschland oder auch in anderen Mitgliedstaaten der Europäischen Union?**
>
> Der digitale Impfnachweis kann nicht nur in Deutschland genutzt werden. Der in Deutschland ausgestellte digitale Impfnachweis kann auch im EU-Ausland als Nachweis für erfolgte Impfungen gelten, wenn der jeweilige EU-Mitgliedstaat digitale Nachweise zulässt. Dasselbe gilt perspektivisch auch für digitale Genesenenzertifikate und Testzertifikate.

So, the first part of this wishlist item, to integrate with the EU Digital COVID Certificate for vaccination, has been fulfilled with the release of CWA 2.3.2.

Outstanding is the functionality for compatibility with the EU Digital COVID Certificate for recovery and test.

**Comment by MikeMcC399** [comment]
"Today, the Presidents of the three EU institutions, the European Parliament, the Council of the EU and the European Commission attended the official signing ceremony for the Regulation on the EU Digital COVID Certificate, marking the end of the legislative process."

Full announcement on: [EU clears way for the EU Digital COVID Certificate](https://ec.europa.eu/commission/presscorner/detail/en/statement_21_2965), June 14, 2021

**Comment by MikeMcC399** [comment]
https://www.n-tv.de/ratgeber/Diese-Erleichterungen-stehen-an-article22651577.html reports on official introduction of cross-border EU Digital COVID Certificates starting tomorrow, July 1, 2021.

**Comment by MikeMcC399** [comment]
This wishlist item is implemented. 

See blog announcements https://www.coronawarn.app/en/blog/

https://www.coronawarn.app/en/blog/2021-07-12-cwa-version-2-5/ says:

"Deutsche Telekom and SAP’s project team have released version 2.5 of the Corona-Warn-App, in which users who have recovered from COVID-19 can integrate a digital certificate that serves as official proof for their recovery. Whether vaccinated, recovered, or tested, users can now manage all types of certificates in one place in their Corona-Warn-App. Users can manage certificates both for themselves and for others, such as children."

**Comment by dsarkar** [comment]
Thanks @MikeMcC399.
