### ISSUE TITLE
[Overview] Local rules and more useful information 

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-wishlist#429]
|Issue|Title|Status|JIRA|
|---|---|---|---|
|https://github.com/corona-warn-app/cwa-wishlist/issues/151 |Auflistung von Regelungen für spezifische Bundesländer - Add local regulations and restrictions|| EXPOSUREAPP-2161|
|https://github.com/corona-warn-app/cwa-wishlist/issues/168|Nützliche Informationen in der App|**CLOSED**||
|https://github.com/corona-warn-app/cwa-wishlist/issues/203|Provide local regulations information|**CLOSED**||
|https://github.com/corona-warn-app/cwa-wishlist/issues/222|Display information on local regulations/restrictions|**CLOSED**||
|https://github.com/corona-warn-app/cwa-wishlist/issues/223|Rules and stuff|**CLOSED**||
|https://github.com/corona-warn-app/cwa-wishlist/issues/235|Bringing additional Information into the Corona App // Local Corona Restrictions & Regulations |**CLOSED**||
|https://github.com/corona-warn-app/cwa-wishlist/issues/252|local regulations information on the basis of mobile phone location data |**CLOSED**||
|https://github.com/corona-warn-app/cwa-wishlist/issues/253 |Get local regulation information on the basis of smartphone local data|**CLOSED**||
|https://github.com/corona-warn-app/cwa-wishlist/issues/323|Include local political corona regulations in a retrievable way|**CLOSED**||
|https://github.com/corona-warn-app/cwa-wishlist/issues/428|Regional regulation change notification|**OPEN**||

---
Internal Tracking ID: [EXPOSUREAPP-6133](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6133)

**Comment by Ein-Tim** [comment]
Here to take over, if you want (-:

In future you can also lemme know when you want a new Overview and I can create one 🙂👍
