### ISSUE TITLE
How to deal with antigentests (NOT PCR-Tests)?

### ISSUE THREAD

**Issue by dideldei** [corona-warn-app/cwa-wishlist#434]
## Current Implementation

Currently only lab confirmed PCR tests results are accepted.

## Suggested Enhancement

Point-of-Care-Tests that use antigen (viral) material are becoming widly available und used. They are much faster and/but slightly less sensitive and specific than PCR. They are done by health care professionals. You should find a way to deal with these tests. There are several possible scenarios:
1. Ignore them and only accept PCR-swaps from labs. In the future you will miss more and more confirmed cases when Ag-tests take over diagnosis in time oder cost critical scanerios.
2. Accept them as you accept PCR swap results, which leads to a much bigger number of places and persons that should be able to create a QR code and/or push results on the server.

## Expected Benefits

Warnings could be 24h faster, but less accurate (to an unknown extent). It is cost saving, when ag confirmed tests do not "force" a pcr swap afterwards to satisfiy the needs of the CWA. And it is safer for medical personell not to do 2 swaps. On the other hand the (degree of) loss of accuracy should be discussed.
Probalby this is RKI stuff, but maybe you have communication channals, that might reach them.

---
Internal Tracking ID: [EXPOSUREAPP-6171](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6171)

**Comment by Ein-Tim** [comment]
Can this issue be closed? 

See https://www.coronawarn.app/en/blog/2021-05-02-corona-warn-app-version-2-1/

**Comment by MikeMcC399** [comment]
Also, there is a link for new Rapid Antigen Test Partners https://www.coronawarn.app/en/rat-partner/ with additional information regarding the comment https://github.com/corona-warn-app/cwa-wishlist/issues/434#issuecomment-812026282 from @dideldei and the e-mail address registrierung.labore.pandemietest@t-systems.com (which is also mentioned in https://www.coronawarn.app/en/blog/2021-05-02-corona-warn-app-version-2-1/ that @Ein-Tim posted).

See also https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki.

**Comment by dideldei** [comment]
Well, the original question included, if positive POCT tests could trigger a "minor" warning, when sent through CWA on contact persons' smartphones. I am not sure, if this was discussed. But anyways...
