### ISSUE TITLE
Easter wishes from the community

### ISSUE THREAD

**Issue by fynngodau** [corona-warn-app/cwa-wishlist#436]
Dear Corona-Warn-App project team,

the wishlist is a place where the community may publicly express its wishes for the future of the project.

Today, we would like to bring forward a very special wish: it is a wish that requires no approval from any party involved in the project, a wish that takes zero pull requests and no config changes to be implemented.

We, the Corona-Warn-App community, would like to wish you, as well as everyone who is important to you, all the best; that you won't ever need to Warn Others, and that you are and remain healthy.

Enjoy your Easter holidays!

The Corona-Warn-App community

![20210402_173658](https://user-images.githubusercontent.com/16943720/113487697-d6e31900-94b9-11eb-88b5-8c4b70bd5609.png)

---
Internal Tracking ID: [EXPOSUREAPP-6168](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6168) ;-)

**Comment by heinezen** [comment]
Dear community,

Thank you for your wishes! As in our usual procedure, we have forwarded your feedback to the dev team and the RKI by creating a Jira ticket (ticket ID: EXPOSUREAPP-6168). I am sure this request will be very popular with them 😄 

Enjoy your Easter Holidays and stay healthy! 🐰 

Corona-Warn-App Open Source Team

**Comment by harambasicluka** [comment]
@fynngodau thanks for delivering this nice words! :)
I hope you also enjoyed the long weekend! 🐰 

& many thanks for everything you do!

**Comment by fynngodau** [comment]
Easter party is over – birthday party is now live in #555!
