### ISSUE TITLE
Clear recommendation needed whether or not to switch Active Region/App while traveling in Europe.

### ISSUE THREAD

**Issue by alanrick** [corona-warn-app/cwa-wishlist#437]
## Where to find the issue
The issue occurs in directly linked or indirectly linked FAQs.

## Describe the issue
A traveler arriving in a different EU location is faced with the choice as to whether to continue to use the CWA, or download a local app, and also whether to switch the Local Region to the country they are traveling in or about to travel in.  Some countries require Covid-19 tests to be made before arriving in the country, and some after arriving in the country to leave quarantine. So the handling of test-results also has to be taken into consideration.

Now that interoperability between several European Apps has been enabled, the in-app documentation and UI should reflect this, and the traveler should be given clear answer as to whether to stick with the CWA in the new country, or switch to the local compatible app.

Currently, this information can only be gleaned through linked faqs and is often contradictory depending on how many links you traverse. So linking is not sufficient. 

Examples:
Caveat: I have included the UK NHS app in these examples, even though it is no longer EU and not compatible (but uses the Google/Apple AP), simply to give examples of issues that will almost certainly occur in other apps in future, if not already. I have not installed all national compatible apps to give a comprehensive as-is comparison because what follows are simply examples.

**Example 1: FAQs**
The EU claims that a switch is necessary when a test is performed: 
"You can only insert a positive coronavirus test result in the app of the country where the test was taken."
https://ec.europa.eu/commission/presscorner/detail/en/qanda_20_1905#gateway
But elsewhere in the same FAQ
"Thanks to the EU interoperability gateway service, citizens can use one single app even when they travel cross-borders, while continuing to benefit from contact tracing and being able to report a positive test or to receive an alert."

The RKI linked from the CWA recommends sticking to the original Active Area when traveling:
"If you are in another EU country or in one of these countries and have made a molecular biological test (PCR test) which is positive, you can upload it to the Corona-Warn-App. To do so, it is necessary to verify your identity by calling the hotline +49 800 7540002."

(As an aside, often 800 numbers cannot be reached from other countries. My test with the French covid number failed, but the German number did work from Ireland).

**Example 2: Local Capabilities**
The CWA does not support extended functions in other countries. So by not transferring away from the CWA you would be at a disadvantage. 

Other EU apps sometimes show local information. 
E.g. Irish apps show local infection rates. It also enables a call-back number. UK app supports  QR-Code venue registration. Local regulations may also already be supported in some apps.
However, some apps do not let you use the app unless you switch to their active region (E.g. UK). So often the app's secondary value over and above the Google/API RPI tracking cannot be used unless the Local Region is set to the local country (deactivating the CWA).

In future, we can expect local diversification to play an even more important role.

## Suggested change
Because linking to FAQs will inevitably lead to different sources (RKI, Telekom, SAP technical, BDI...) with often outdated information contradictions are inevitable. So linking to FAQs is not sufficient. One bullet point in the "_Learn More and Help"_ wizard is what's needed. Alternatively, a sentence of recommendation in the _Transnational Exposure Logging_ section.
![photo_2020-11-30_11-19-41](https://user-images.githubusercontent.com/7034358/100597663-0280a780-32fe-11eb-8b89-acd36eaff622.jpg)

---
Internal Tracking ID: [EXPOSUREAPP-6170](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6170)

**Comment by dsarkar** [comment]
Internal Tracking ID: EXPOSUREAPP-6170

**Comment by Ein-Tim** [comment]
FYI: The Twitter account [@coronawarnapp](https://twitter.com/coronawarnapp) included this question in [this](https://twitter.com/coronawarnapp/status/1434845008335622151?s=21) thread: 

> Frage: Soll ich im Ausland die #CWA nutzen oder ländereigene Apps?

> Durch die länderübergreifenden Risiko-Ermittlung (Interoperabilität) müsst Ihr nicht die App der anderen Länder installieren.

> Die Apps dieser Länder sind mit der #CWA interoperabel:
➡️ http://coronawarn.app/de/faq/#interoperability_countries

> Falls es zu einer Testung im Ausland kommt, ist es eventuell notwendig, andere Apps zu installieren. 

> Bleibt Ihr im Ausland, nutzt die #CWA und wollt nach einem positiven Test warnen, verhält es sich wie bei einer Testung in Deutschland ohne #CWA-Anbindung.

> So geht's: Ihr müsst die Tele-TAN-Hotline anrufen (+49 30 498 75402). Die Nummer ist auch aus dem Ausland erreichbar. 

> Dort stellt Ihr die Situation dar und bekommt eine Tele-TAN zum Warnen.

> Mehr Infos:
➡️ http://coronawarn.app/de/faq/?search=Corona+Warn+App+Ausland

**Comment by alanrick** [comment]
Closing this issue because interoperability is now widespread and well-known, and the pros and cons of switching will significantly depend on individual preferences.
