### ISSUE TITLE
[Contact-Journal] QR-Codes for easier entries and check-in at locations

### ISSUE THREAD

**Issue by LukasLeonardKoening** [corona-warn-app/cwa-wishlist#438]
I am hoping, I did not missed a duplicate issue despite searching the repositories.

## Feature description

- QR codes for locations (stores, restaurants, ...)
    - Locations can create a QR code on the CWA website and provide it to their customer (e.g. at the entrance). 
    - This QR-Code contains the name and contact information of the location (e-mail and/or phone number)
    - The customer/visitor scans the QR code with the CWA and adds the estimated time of stay
    - An entry in the contact journal of the customer/visitor is created
- QR codes for persons
    - Every user of the app has his own QR code within the app which contains his name 
        - (and it would be better if there would be any contact information but there would be some privacy issues I assume)
    - Other users can scan this code with their CWA and an entry in the contact journal is created
    - The users who scanned the code can change the settings (> or < 15min, mask, indoor) and save the entry
- the data is stored locally and the user can extract the data for the health authorities if he had been infected with the Covid-19 virus

## Problem and motivation

I am using the contact journal for some time now and it could be improved. Besides that the solution from the luca app needs a connection the the health authorities which is problematic as we can see...
So why not implement check in options in the existing, very well working contact tracing app?
I am very open for suggestions!

## Is this something you're interested in working on

Yes. I have some experience in developing iOS and Android Apps (front- and backend).

**Comment by Ein-Tim** [comment]
Something similar (but anonymous) is currently planned for the next release, version 2.0:

https://github.com/corona-warn-app/cwa-documentation/blob/master/event_registration.md

**Comment by LukasLeonardKoening** [comment]
> Something very similar is currently planned for the next release, version 2.0:
> 
> https://github.com/corona-warn-app/cwa-documentation/blob/master/event_registration.md

If I understand that right, it is not really the same. It has nothing to do with the contact journal. It is for planned "get-togethers" and meetings but not for the every day purpose (just hop in to the store to grab a cup of coffee). It seems to be deeply integrated into the exposure notification framework.
Besides that it looks like there are a lot of security issues...

**Comment by LukasLeonardKoening** [comment]
I think the biggest difference is between exposure notification (event_regestration.md) and contact tracing information for the health authorities (my idea).

**Comment by Ein-Tim** [comment]
> It has nothing to do with the contact journal.

Yes it has, the user can choose to save his visit into the contact journal. 

> It is for planned "get-togethers" and meetings but not for the every day purpose (just hop in to the store to grab a cup of coffee)

But the coffee shop could also have a QR-Code. 

> It seems to be deeply integrated into the exposure notification framework.

Yes, to make it possible to warn and get warned via the feature. 

> and contact tracing information for the health authorities (my idea).

Yes, see the discussion in #138

**Comment by LukasLeonardKoening** [comment]
> Yes it has, the user can choose to save his visit into the contact journal.

Oh okay, thank you for the clarification. I did not find a file, where this is described. Maybe the documentation of this feature should be expanded by these information?

Is there a way to contribute to this feature?

**Comment by Ein-Tim** [comment]
@LukasLeonardKoening 

You can find the development in the iOS and Android repo: 

- iOS: https://github.com/corona-warn-app/cwa-app-ios
Android: https://github.com/corona-warn-app/cwa-app-android

The work is on the `release/2.0.x` branch. 

Feel free to rephrase this issue and reopen, or if you think that the upcoming event registration feature will cover this then monitor #138.

Thanks for contributing!

**Comment by Ein-Tim** [comment]
Some screenshots are in the asset of this release: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.0.0-RC1

**Comment by Ein-Tim** [comment]
Hey @LukasLeonardKoening 👋 

I wanted to say sorry if my comments were a bit rude 😅

To explain a bit more:

The [event-registration](https://github.com/corona-warn-app/cwa-documentation/blob/master/event_registration.md) feature, planned for version 2.0 (the next release), will make following possible:

1. A CWA user (which can be the owner of a restaurant, somebody who celebrates a birthday, etc.) creates a QR-Code for an event
2. Users who are going to the event can check-in **and** decide how long they'll stay and wether they want the event to get "copied" into the contact journal
3. In addition to the positive keys of other people, CWA will also download keys of "positive events" (somebody attending the event registered a positive test result), if your CWA then detects that you were on a "positive event", you'll receive a red warning. 

*Video of user flow will follow here*
