### ISSUE TITLE
Switzerland

### ISSUE THREAD

**Issue by treysis** [corona-warn-app/cwa-wishlist#44]
App needs to be available in Swiss app stores.

**Comment by NicolaiKilian** [comment]
100% agreed! This is the only neighbouring state of Germany where there are still no release plans for the App Store!

**Comment by nitramwin** [comment]
RKI still doesn’t have this country on the list. Ayayay

**Comment by relefant** [comment]
There is a lot of traffic across this border. I live in Germany but work in Zurich. Our supermarket is jam packed with people from Switzerland every weekend. As mentioned by @NicolaiKilian this is the only border where there are no plans to release in the Swiss App/Play Store. I have to have the Swiss store on my phone for my work commitments. 

My wife has Corona Warn App, but I can't install it.  Someone pay a lawyer 20 million and end this nonsense.

**Comment by silvano** [comment]
Please give this some priority. Commuting between D-CH is such a common thing. Is there any information available on the status of D-CH compatibility? For everybody with the same problem, at least the Swiss Corona Warning App is available within the German App Store.

**Comment by tkowark** [comment]
As noted in https://github.com/corona-warn-app/cwa-backlog/issues/9#issuecomment-652980998 , the Corona-Warn-App is now also available in App stores for Switzerland!

**Comment by treysis** [comment]
On Android, will this be bundled with the release of 1.0.5? Because there is no change yet on PlayStore.

**Comment by tkowark** [comment]
Mhhh, the change was made ~2 hours ago. As written in https://github.com/corona-warn-app/cwa-backlog/issues/9#issuecomment-652980998 it might take some time to become effective. Can you recheck later tonight or tomorrow morning?

**Comment by treysis** [comment]
Usually this goes much faster. That is unless you also publish a new APK which will have to pass Google's review process first.

**Comment by tkowark** [comment]
I'll reopen the issue until the app is really available and re-check with the folks responsible for the stores.

**Comment by treysis** [comment]
It's been working in Apple's AppStore since yesterday shortly after the announcement. But still no change in Google's PlayStore.

**Comment by tkowark** [comment]
That's really strange since the respective options are set:

<img width="400" alt="Screenshot 2020-07-03 at 11 49 55" src="https://user-images.githubusercontent.com/164467/86457131-7739c080-bd23-11ea-8cfd-ee4952fcd629.png">

Can anybody else see the app in Suisse app stores? @NicolaiKilian @silvano @relefant @nitramwin ?

**Comment by NicolaiKilian** [comment]
I can confirm it’s available in Swiss Apple AppStore.
Don’t know about the PlayStore.

**Comment by nitramwin** [comment]
Also available in the Swiss PlayStore. Cheers.

**Comment by nitramwin** [comment]
Sorry for the spam. I used the wrong account. In the Swiss PlayStore, the CWA is not yet visible.

**Comment by treysis** [comment]
For quick checking of availability, right-click the following link and select "open incognito/private":
https://play.google.com/store/apps/details?id=de.rki.coronawarnapp&gl=ch
If a green "Install" button appears, it means the app is available. Compare how it looks for e.g. France (again, right-click -> icognito/private):
https://play.google.com/store/apps/details?id=de.rki.coronawarnapp&gl=fr

**Comment by tkowark** [comment]
Ok, the problem seems to be there for all new countries ... thanks for the link!

**Comment by tkowark** [comment]
Just got confirmation, the update is still in state "Processing Update". Per official docs, the review process might take up to 48 hours, so let's wait until the weekend...

**Comment by treysis** [comment]
Thanks. I would have expected Google to fast track Corona apps.

**Comment by treysis** [comment]
Still nothing. I wonder if anyone has made an inquiry to Google to investigate? I sometimes feel the responsible people just can't be bothered. At least not anymore.

Anyway, it's almost 3 weeks since initial release. The PR window is closed and the ship has long sailed.

**Comment by treysis** [comment]
Even working week started again, there is still no change in availability. Please confirm.

**Comment by akuckartz** [comment]
Can this issue be reopened until availability is confirmed?

**Comment by treysis** [comment]
Now available. Can be closed.
