### ISSUE TITLE
Possibility to deactivate automatic check out

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#440]
## Current Implementation
In version 2.0 you are forced to enter an automatic check-out time for places.

## Suggested Enhancement
Make it possible to deactivate the automatic check out.

## Expected Benefits
Avoid to early check outs in situations where users don't yet know how long they'll stay when they check-in (and thus can't tell when they check out).

----
Internal Tracking-ID: [EXPOSUREAPP-6756](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6756)

**Comment by heinezen** [comment]
@Ein-Tim 

Thank you. There is now a Jira tick for this request (ticket ID: EXPOSUREAPP-6756). The development and the RKI will now discuss how feasible this would be for the app and how it could be implemented.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Closing as declined.

**Comment by heinezen** [comment]
This feature was **declined** by the development team and will not be pursued further. If someone doesn't know how long they will stay, they should choose a longer time than their estimated staying time. Automatic checkout is considered a must-have feature.

----
Corona-Warn-App Open Source Team
