### ISSUE TITLE
Clear communication about „fake check-ins“ with event registration feature

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#442]
## Current Implementation
n/a

## Suggested Enhancement & Expected Benefits 

The public [noticed](https://twitter.com/janboehm/status/1379573411400286209?s=21) a few days ago that it's possible with the luca app to check-in from anywhere to an event. 

To not have the same _bad_ discovery made by public I think it's very important that, with the release of version 2.0, it get's clearly communicated that the Corona-Warn-App has the same vulnerability. 
It should be explained that this is not a big problem with the CWA feature, because: 

1. According to the [documented threads - targeting specific venues](https://github.com/corona-warn-app/cwa-documentation/blob/master/event_registration.md#targeting-specific-venues), "CWA only allows a certain number of check-ins per day."
1.1 So if somebody want's to target venues in a noticeable scale, he needs more than one device running CWA (and he needs a positive result on more than one device, see point 2)

2. To warn other people via the Corona-Warn-App, you need to register a positive test result. This is only possible thorough either a QR-Code linked to a positive test result, this can only be obtained if somebody really is tested positive, or via a TAN requested from the Verification hotline 
2.1 The TeleTAN IHMO is the way an attacker would go, it's too hard to somehow get "positive QR-Codes". 
2.2 If somebody obtains a TeleTAN without having a positive test result, he/she already now is able to send out false positive warnings. 

3. The CWA system can't be "DDOS"sed by faking many check-ins. 
The CWA is a fully automatic system. 
Unlike the luca app it doesn't need the health authorities in any of the warning steps. 
Even if there were 10.000 users checked-in with you at the same time (because somebody faked check-ins), all these 10.000 users can be notified, since the system is fully automatic. 
Thus, also your real contacts would be notified from CWA in such a "fake check-in" scenario. 
With the luca app, it would get very hard for the health authority to distinguish between real and fake contacts, so a individual risk assessment from the health authority get's impossible. 

Please let me know what you think about this (and also if I'm missing something 🙂)

**Comment by raceface2nd** [comment]
Maybe the CWA project group should consider in getting in touch with pass4all or https://www.wirfuerdigitalisierung.de/ which have apps in production since months and all of these guys integrated brilliant features into there systems.

Especially pass4all already developed last year a wide toolkit on several possibilities to check into an event. They already have solutions on keeping track of the checked in people on wide area event properties like fair grounds, wide area festival areas hosting tens of thousands of people and so on. 

Driven by the wish to support options which help us that we can hopefully work in our businesses in event industry after more than one year business lock down are widely connected with many initiatives which developed these brilliant solutions and concepts. I am sure many partners in our network will share there experiences and success stories.

One thing is clear, this situation can only be brought under control with team players.

Addressing the mentioned limit of checked in users one should know that (only with an eye on events, shows and concerts) the majority of these events which can be called as event industry is produced for tens of thousands of guests.

Limiting the amount of checked in users would not disturb hotels, restaurants, theaters and so on, but would block a perspective for event industry.

**Comment by Ein-Tim** [comment]
@raceface2nd 

Thanks for the suggestion, I opened this issue because I want to avoid the same bad reception of the CWA as it happened to the luca app. The release of version 2.0 is (according to the press) planned for the 16.04.2021. 
Documentation on the event registration can be found here: https://github.com/corona-warn-app/cwa-documentation/blob/master/event_registration.md

For proposal, which aren't directly related to my suggestion to clearly communicate the possibility of fake check-ins, I would ask you to open a new issue.

Thank you!

**Comment by jucktnich** [comment]
What's about dynamcaly generated qr codes on e.g. TV-Screens, wich are only valid for f.e. 5min. (Not sure if this was brought up in another issue.)

**Comment by Ein-Tim** [comment]
@jucktnich It was brought up here: https://github.com/corona-warn-app/cwa-wishlist/issues/413

The problem is that you'd need a central authority which keeps track which QR-Codes belong to an event, as described in https://github.com/corona-warn-app/cwa-wishlist/issues/413#issuecomment-814792110

**Comment by jucktnich** [comment]
My solution would be time-sensitive, not scan-sensitive, so I think, no you wouldn't need it.

**Comment by Ein-Tim** [comment]
@jucktnich 

Yeah but you still need a central authority since if user A checks in on QR-Code A, then the QR-Code changes (QR-Code B) and user B checks in, still both should be warned since they aren't on different events but on the same. Or am I missing something?

**Comment by jucktnich** [comment]
I think you could use the same payload in combination with a timestamp. You can't prevent changing the timestamp, but it's harder (Maybe there's the possibility of hashing, but I don't think so)

**Comment by Ein-Tim** [comment]
@jucktnich Yeah, the solution with the timestamp would work without a central entity for this.

Would you like to add this to #413

**Comment by jucktnich** [comment]
Another, but far more complicated idea would be, to generate a random number on the users devices, generate a qr code with this number and let it be scanned by the host. The host generates his code encrypted with the number and the user scannes it from the host.

**Comment by Ein-Tim** [comment]
@jucktnich 

This would mitigate the risk of "fake check-ins", since the host would have to actively scan QR-Codes. This is a very good idea IHMO! 
But, according to the press, version 2.0 will be released next Friday, so I see no way that this makes it into the 2.0 release.

Still I suggest that you create a separate issue for this here in the wishlist.

Have a nice evening.

**Comment by jucktnich** [comment]
I thought about the solution with the timestamp and I think, that using X.509 everything would fit in a qr-code, Right?

**Comment by Ein-Tim** [comment]
I think my suggestion was taken into account when writing
https://www.coronawarn.app/en/faq/#check_in_misuse & https://www.coronawarn.app/en/faq/#prevent_false_warnings.

Closing as implemented in the FAQ.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks!
