### ISSUE TITLE
App clip for CWA event-registration

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#445]
## Current Implementation
Starting with version 2.0 it'll be possible to check-in to events with the Corona-Warn-App. For this the user has to install the app.

## Suggested Enhancement
Provide an app clip (iOS 14 feature - see https://developer.apple.com/app-clips/) which opens when a user, who doesn't have the CWA installed, scans the QR-Code.

## Expected Benefits
More users of the feature since you don't have to install the app, step through the onboarding, etc.

---
Internal Tracking ID: [EXPOSUREAPP-6372](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6372)

**Comment by jucktnich** [comment]
With an app clip you can't warn people right.

**Comment by Ein-Tim** [comment]
@jucktnich 

I thought about this, I don't think an app clip could have this scope. 
The app clip would have one function:
Use it when you don't have CWA installed, want to scan a CWA QR-Code and check into an event, but don't want to step through the onboarding.
The app clip would make clear that you can only be warned & warn others if you install the app. 
Then the user could still check in at an event and step through the onboarding at home.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks. Internal Tracking ID: [EXPOSUREAPP-6372](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6372)

**Comment by larswmh** [comment]
Closing this issue as the related internal ticket is set to `obsolete`.

Developer comment:
> This would only be iOS specific. We need functionalities which work for iOS and for Android.
