### ISSUE TITLE
Rapid test integration - documentation

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-wishlist#449]
From comment of @raceface2nd: https://github.com/corona-warn-app/cwa-quick-test-frontend/issues/51#issue-854736431

## What is missing

Are there any documents (sketches, descriptions, charts or whatever) you can provide that we might be able to prepare the ability on our technical side?

## Why should it be included

To be able to provide this additional benefit feature to our company customers I am very interested on getting information on how the technical process is planned to deliver the test results to the CWA.

Can you also estimate when this feature will be available? We have some festivals and concerts which will be held somehow in the next months hopefully as demonstrator events in conjunction with quick testing. The event organizers would love to use the CWA as trusted instance instead of using different apps for ticketing, test results and pooled contact tracing. The first event which will take place is the "Bundesgartenschau" which is held every 2 years and which open doors in about 2 weeks. We would like to support the organizers of the Bundesgartenschau in making the event as save as possible by using CWA together with quick tests.

## Where should it be included

---
Internal Tracking ID: [EXPOSUREAPP-6382](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6382)

**Comment by MikeMcC399** [comment]
See also https://github.com/corona-warn-app/cwa-documentation/issues/595.

**Comment by larswmh** [comment]
Closing this issue as the related internal ticket is set to `obsolete`.

Developer comment:
> The technical information how to integrate with the CWA is provided by TSI. TSI provides information to partners who want to integrate their RAT solutions
