### ISSUE TITLE
(Auto-)Purge Contacts/Locations in Contact Diary

### ISSUE THREAD

**Issue by nohn** [corona-warn-app/cwa-wishlist#450]
## Current Implementation

You can add contacts and locations and manually delete each of them.

## Suggested Enhancement

It should be possible to purge or auto-purge contacts/locations that haven't been contacted in the last 14 days.

## Expected Benefits

Much less clutter.

**Comment by Ein-Tim** [comment]
Related Issues:

- #322
- #405

**Comment by MikeMcC399** [comment]
@nohn 
Your request seems to be a duplicate of my request https://github.com/corona-warn-app/cwa-wishlist/issues/405. Please check it out. If you think your needs are covered by #405 you can add any additional comments there and close this one.

**Comment by nohn** [comment]
Correct. Duplicate of #405
