### ISSUE TITLE
Better advertisement and feature coverage in media

### ISSUE THREAD

**Issue by mfs12** [corona-warn-app/cwa-wishlist#455]
As the features mature and get more this app might be able to replace commercial and not privacy-friendly solution like Luca App.

How are you promoting new or matured features to the public especially because this app requires wide acceptance of the public. And the major advantage of being more privacy friendly.

----
Internal Tracking-ID: [EXPOSUREAPP-6757](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6757)

**Comment by Ein-Tim** [comment]
This is closely related to #352 "Discussion about public perception of the app".

**Comment by larswmh** [comment]
Closing this issue as the related internal ticket is set to `obsolete`.

Developer comment:
> Cannot be don by SAP. Must be done by the government or by RKI.
>
> We like and support the idea, but sorry, not possible for SAP.
