### ISSUE TITLE
Add logo to cwa-bot

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#456]
## Current Implementation
The [cwa-bot](https://github.com/apps/cwa-bot), which picks up new issues and adds them to ToDo in the CM project of the repository as well as moves issues between different groups in the CM project when e.g. labels are applied, uses the picture of the person who developed it, @svengabr. 

## Suggested Enhancement
The CWA logo should be used as the picture of the bot.

## Expected Benefits
Cleaner look, no huge benefit but also a more professional look.

## Additional Information 
The picture in the bot can't be seen on the mobile app.

**Comment by dsarkar** [comment]
@heinezen Any idea how to configure this?

**Comment by Ein-Tim** [comment]
Here's the instruction how to do it: https://docs.github.com/en/developers/apps/creating-a-custom-badge-for-your-github-app
I think @svengabr would have to do it since he's the developer.

**Comment by heinezen** [comment]
@dsarkar I'll see what I can do.

**Comment by svengabr** [comment]
@Ein-Tim I did implement the logo change to my bot.

If it won't show up right away, try to clear your cache and then try again.

I let this open for you to confirm and close the issue.

**Comment by Ein-Tim** [comment]
@svengabr 

I can see the change! 
Thank you! Looks much cleaner IHMO (but it was also quite nice to see you 😉).
Thank you! 

Closing as implemented.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks!

**Comment by fynngodau** [comment]
Great change :+1: thanks for suggesting and implementing it!

**Comment by ndegendogo** [comment]
Very nice, indeed @Ein-Tim
