### ISSUE TITLE
Advice for app use by people who have been vaccinated

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-wishlist#457]
## What is missing

What should users do who have already been vaccinated for the 1st or 2nd time? Does it change anything for app users or are the recommendations for everybody to use the app unchanged?

If a vaccinated user receives a red warning, what should they do? Should they get tested?

## Why should it be included

---
RKI writes in https://www.rki.de/SharedDocs/FAQ/COVID-Impfen/gesamt.html

"Die Wahrscheinlichkeit, dass eine Person trotz vollständiger Impfung PCR-positiv wird, ist bereits niedrig, aber nicht Null. In welchem Maß die Impfung darüber hinaus die Übertragung des Virus weiter reduziert, kann derzeit nicht genau quantifiziert werden. Auf Basis der bisher vorliegenden Daten ist davon auszugehen, dass die Viruslast bei Personen, die trotz Impfung mit SARS-CoV-2 infiziert werden, stark reduziert und die Virusausscheidung verkürzt ist.

In der Summe ist daher das Risiko einer Virusübertragung stark vermindert. Es muss jedoch davon ausgegangen werden, dass einige Menschen nach Kontakt mit SARS-CoV-2 trotz Impfung (asymptomatisch) PCR-positiv werden und dabei auch infektiöse Viren ausscheiden."

RKI also writes:

"Vollständig gegen COVID-19 geimpfte Personen sind nach Exposition zu einem bestätigten SARS-CoV-2-Fall von Quarantäne-Maßnahmen ausgenommen, ebenso wie Personen, die in der Vergangenheit eine PCR-bestätigte und symptomatische COVID-19-Erkrankung durchgemacht haben („Genesene“) und mit einer Impfstoffdosis geimpft sind."

---

As more and more people are getting vaccinated there should be more people who have built up significant resistance to becoming infected, however as can be understood from the opinions of RKI the situation is not black and white. It is still possible for vaccinated persons to become sick and pass on the virus.

According to https://www.zusammengegencorona.de/impfen/ status  May 20, 2021  39.3% have received the first dose, whilst 13.1% are completely vaccinated.

## Where should it be included

Any explicit recommendations for people who have been vaccinated should be included in the app itself and in the app FAQs.

---
Internal Tracking ID: [EXPOSUREAPP-6545](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6545)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. Internal Tracking ID: [EXPOSUREAPP-6545](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6545)


---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
I hope that RKI will be able to share their expert opinions on using the app after being vaccinated (or having recovered). The general topic is being discussed by politicians in terms of lifting legal restrictions. The app use however is voluntary, so it should not need a conclusion to the legal discussions before giving advice with regard to the app.

If there are no expert opinions forthcoming, I expect that individuals will use their own opinions and make their own decisions about app usage after having been vaccinated or having recovered from COVID-19.

**Comment by MikeMcC399** [comment]
The question 

"If a vaccinated user receives a red warning, what should they do? Should they get tested?"

is answered in https://www.coronawarn.app/en/faq/#vac_cert_red_warning.

Due to the addition of vaccination certificates in version 2.3.2 there continues to be a reason for users to keep the app running after being vaccinated.
