### ISSUE TITLE
Usability: QR check-in confusing to find

### ISSUE THREAD

**Issue by pizuz** [corona-warn-app/cwa-wishlist#466]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: iPhone SE (2020)
- iOS version: 14.4.2
- App version: 2.0.3

## Describe the bug

Trying to scan a check-in QR code is really confusing. To get to the function, you need to first select the create QR code field, click through the QR code creation instructions, then select the scan QR code field at the bottom of the screen. You lose many users during the process.

Providing the user with an easily accessible check-in scan option right from the home screen would be preferable.

## Steps to reproduce the issue

As described above, navigate through the create QR code menu and find the scan option somewhere at the bottom of the screen.

## Possible Fix

Place the scan option directly on the home screen.

----
Internal Tracking-ID: [EXPOSUREAPP-6758](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6758)

**Comment by Ein-Tim** [comment]
@pizuz 

No yo don‘t. The first time you may have to click on „Accept“.
Here‘s a screen-recording:

**Comment by dsarkar** [comment]
@pizuz Thanks for your suggestion. We are very interested in any proposal to improve UX and to make the app use/flow more consistent. More suggestions are very welcome. Thanks. Best wishes, DS


---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@Ein-Tim Would be so kind and add this one also to the UX overview! Thanks!

**Comment by dsarkar** [comment]
@pizuz @Ein-Tim What I understand from this, is that the flow is maybe not intuitive enough.

**Comment by pizuz** [comment]
> @pizuz
> 
> No yo don‘t. The first time you may have to click on „Accept“ (I simulated this by clicking on „Information“ in the 3 dots overflow menu) Here‘s a screen-recording:
> 
>  IMG_1108.MP4 
> 
> Regards
> Tim

Sorry, my bad. I didn‘t notice that the check-in function at the bottom can be reached from anywhere.

Placing a notice directly on the home screen might help avoid confusion.

**Comment by Ein-Tim** [comment]
@pizuz 

I don't think thats necessary. It can be reached like the contact diary. 
But please leave this issue open, @dsarkar I'll add it later on, hope thats ok. 🙂

**Comment by pizuz** [comment]
> @pizuz
> 
> No problem 🙂
> 
> > Placing a notice directly on the home screen might help avoid confusion.
> 
> I don't think thats necessary. It can be reached like the contact diary.
> But please leave this issue open, @dsarkar I'll add it later on, hope thats ok. 🙂

Alright. As a suggestion, maybe add an arrow pointing towards the button on first launch, because people tend to dismiss splash screens prematurely. The Facebook app tends to nag users that way, and it seems to be quite effective.

**Comment by Ein-Tim** [comment]
One more thing here: You can also scan the QR-Code with the native camera of your phone.

**Comment by Ein-Tim** [comment]
@dsarkar Added to the UX Overview. 
Please see https://github.com/corona-warn-app/cwa-app-ios/issues/2497#issuecomment-824325738
Have a nice evening.

**Comment by heinezen** [comment]
We have added this issue to our Jira ticketing system: [EXPOSUREAPP-6758](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6758)

----
Corona-Warn-App Open Source Team

**Comment by larswmh** [comment]
Closing this issue as the related internal ticket is set to `completed`.

With the addition of the universal QR code scanner to the bottom bar in version 2.12, this issue is resolved.
