### ISSUE TITLE
[Check-in] App shortcut should directly lead to qr code scanner

### ISSUE THREAD

**Issue by jucktnich** [corona-warn-app/cwa-wishlist#468]
## Current Implementation

If you click on the check-in shortcut it leads you to the check-in tab, not to the scanner.

## Suggested Enhancement

Direct lead to the qr code scanner.

## Expected Benefits

Faster & more consistent with the contact diary.

---
Internal Tracking ID: [EXPOSUREAPP-6628](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6628)

**Comment by Ein-Tim** [comment]
Should maybe be moved to wishlist since this should be considered for Android too.

**Comment by jucktnich** [comment]
It is at the wish list.

**Comment by Ein-Tim** [comment]
@jucktnich 

Sorry, thought it was in the iOS repo, the item before was in it. 
Sorry 🙂

**Comment by dsarkar** [comment]
Hi @jucktnich thanks for the suggestion. Internal Tracking ID: EXPOSUREAPP-6628


---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
This has been implemented, don't know in which version though.

**Comment by dsarkar** [comment]
@Ein-Tim @jucktnich Thanks for contributing and monitoring.
