### ISSUE TITLE
[Overview] Website related improvements/requests 

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-wishlist#470]
- [EXPOSUREAPP-5880](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5880) https://github.com/corona-warn-app/cwa-wishlist/issues/399  Make it possible to generate QR-Codes on a website

**Comment by Ein-Tim** [comment]
Although that's quite a short overview, I can take it over and also search for more issues (like https://github.com/corona-warn-app/cwa-wishlist/issues/302#issuecomment-752749343)

**Comment by dsarkar** [comment]
It still short, but maybe it triggers some more nice ideas ... ;-)

**Comment by Ein-Tim** [comment]
I hope so (; 
@dsarkar Do you want me to maintain this overview too? 🙂

**Comment by Ein-Tim** [comment]
I opened #479 because I think we will see some enhancement/feature requests when the QR-Code Generator goes live. They will then be added there.
@dsarkar I would suggest that you close this issue 🙂

Thanks!

**Comment by dsarkar** [comment]
@Ein-Tim ok ! Thanks.

**Comment by dsarkar** [comment]
@Ein-Tim We have internal ticket yet for the website overview. Once this grows bigger we will create one.
