### ISSUE TITLE
Create QR code externally

### ISSUE THREAD

**Issue by Slevin7** [corona-warn-app/cwa-wishlist#475]
Hello,
I have a calendar for my workplace where all people can see when and where which appointment is taking place.
At the moment there are still TV sets that I use with MagicMirror2 and a calendar on Nextcloud.
Now my question is, is it possible to have the QR code generated automatically?
So as an example, I'll create an event from 2pm to 4pm. Through pure magic, there is then a QR code for the warning app in the description of the event.
Yes, I know I can only wish things for the Warn app, but I would be interested first, or I would like to be able to create the QR codes outside of the app.

Many Thanks

**Comment by heinezen** [comment]
Related: https://github.com/corona-warn-app/cwa-wishlist/issues/399

**Comment by JWandscheer** [comment]
See #474, especially [https://github.com/MaZderMind/cwa-qr](https://github.com/MaZderMind/cwa-qr) to generate QR codes locally.

**Comment by dsarkar** [comment]
@Slevin7 Yes, as already mentioned above: It is possible to create CWA Event QR codes locally, even without internet connection.

**Comment by heinezen** [comment]
We have good news on this topic.

In the following days, tools and libraries for generating QR codes and QR code payloads will be published by us. These can be used by other projects, websites or vendors to create CWA-compatible codes outside of the app. Of course, the community can also use them to write or extend their own tools regarding event registration in the CWA.

----
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
FYI https://www.coronawarn.app/en/blog/2021-04-23-qr-code-generator/

**Comment by heinezen** [comment]
> In the following days

Well, the release was actually a lot sooner :smile:  The repo just went live at https://github.com/corona-warn-app/cwa-event-qr-code

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
@Slevin7 

Since the https://github.com/corona-warn-app/cwa-event-qr-code can be used as a reference implementation and fulfills your initial  request, I would say we close this issue and promote individual issues for tools, programming language support and ideas for QR code integration. That will keep the discussions clean and the CWA team can better monitor the requests.

----
Corona-Warn-App Open Source Team
