### ISSUE TITLE
Use NFC to Check-in - Just Works ;)

### ISSUE THREAD

**Issue by jwildeboer** [corona-warn-app/cwa-wishlist#476]
Not a feature request or enhancement request. more like a FYI.

What I did:

- Create QR code in CWA
- print it and extract URL
- Write URL to standard NFC 216 Tag
- Write-protect the NFC tag

And now you can check in with NFC. No camera needed, jut hold the phone close to the tag and the notification shows :) I thought it was cool.
![EzmTZa6XEAYAZCc](https://user-images.githubusercontent.com/873028/115781102-3eee9600-a3ba-11eb-8b18-7b8d922b742e.jpeg)
![EzmTZdYWYAAd6RA](https://user-images.githubusercontent.com/873028/115781109-401fc300-a3ba-11eb-8a2c-966eb399e05b.jpeg)

**Comment by Ein-Tim** [comment]
Great @jwildeboer!

Maybe add #406.

**Comment by dsarkar** [comment]
@jwildeboer Thanks again for the demo. We suggest to close this issue and as you already did, continue in #406. We track your demonstration in Internal Tracking ID: EXPOSUREAPP-5922. Thanks. Best, DS

---
Corona-Warn-App Open Source Team

**Comment by jwildeboer** [comment]
Infos added to #406, so closing this one.
