### ISSUE TITLE
For event/location type allow multiple duration presets to chose from

### ISSUE THREAD

**Issue by tik-boomer** [corona-warn-app/cwa-wishlist#477]
## Current Implementation
Event generation provides different types of events / locations. In the current version of the app per event type exactly one preset duration can be set for automatic checkout. Currently one duration preset only is possible per event. For a school with one static "event" per classroom, i.e. one QR-code poster per classroom, this could be improved, to better account for typical school schedules.

## Suggested Enhancement

allow a short list of duration presets, e.g. for a classroom

- 50 minutes (single lesson+ break / buffer)
- 105 minutes (double lesson + break / buffer)
- 305 minutes (morning lessons)
- full day

to be used with the automatic checkout procedure. The durations to be configured at the time of event generation -- different schools have different durations for lessons.

Then, in the app with the checkin dialogue, display the list of choices to select from.

This way the students following their course / lesson schedule and roaming between rooms will usually checkin for a room for the next lesson or course, select the correct duration accordingly from the presets, and at the end of the course / lesson do not have to checkout manually. This saves from queueing at the end of the lesson, at the QR-code poster, and from additional time consumed and typos (when manually entering the duration)..

## Expected Benefits
Less queueing, therefore lower risk of not keeping the recommended distance and less time wasted, they are already losing lots of school time for rapid-tests, additional hygienic measures, venting, etc. As vaccines for the youth are still many months away, they will benefit from this quite a lot over time.

----
Internal Tracking-ID: [EXPOSUREAPP-6759](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6759)

**Comment by heinezen** [comment]
Hey @tik-boomer ,

Thank you for the request. I've reformulated your post a bit, so that it applies to other scenarios, not only classrooms. However, I kept your examples as you described them. We have created an internal Jira ticket for your request. The dev team and the RKI will now have a look at this and decide how to best proceed.

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
Hey everyone,

This feature request has been **decined** for the following reasons:

* The automatic checkout time should reflect the most used duration
* It is already possible to ask users to adjust the duration when they check in or later
* A list of durations is too complicated for most use cases

We will therefore close this issue.

----
Corona-Warn-App Open Source Team

**Comment by tik-boomer** [comment]
@maugst @heinezen: Please reconsider this and re-open. The reasons mentioned by heinezen do not at all match the use case "School" in Germany.

regarding your points:
-     The automatic checkout time should reflect the most used duration
-     It is already possible to ask users to adjust the duration when they check in or later
-     A list of durations is too complicated for most use cases

In reality:
- A class room has (at minimum) two different 'most used' durations: **single** lesson AND **double** lesson. If these are not supported, there would be two QR-codes needed per room. And then those app users who scan the wrong code would seem registered (by the CWA) to a different room... :-( 
- for a class room all students / pupils arrive almost at the same time and have to check-in as quickly as possible, with minmal interaction. It is not an option that they spend lots of time time queueing like a the entry of a restaurant or a shop.

- duration adjustments for pupils / students should be minimal, as they are already losing a lot of productive time for other corona measures. If the default would be 45 minutes only, a lot of students would just accept this at the begin of the lesson and then need to re-adjust in the middle of a double lesson, leading to chaos for the teacher and the other classmates. :-(

- as the CWA distinguishes between use cases it should fully support the use cases, not just 'somehow, a little bit'. Of course this valuable feature for class rooms does not mean it should complicate **other** CWA 'locations' or check-ins. 

 --
As foreseeable today, most pupils / students will have to wait longest, until licensed vaccines will be available for them. Therefore it should be considered 'reasonable' to make their use case (which actually is a 'life case' or at least a 'health case') as good and easy as possible. The extra effort is worth it, and especially for the young(est) citizens, IMHO.

 --
From the data structure it is somewhat obvious that the designers / developers did not pay attention to the lesson structure of typical schools in Germany in the firts place. They merely added a new location name / type 'education' without understanding the implications. Now it is time to complete the design, even if it needs a modfied data structure.

**Comment by heinezen** [comment]
@tik-boomer

I've forwarded your answer back to the development team and asked for a reconsideration. We will have to see what they have to say. I'll reopen for now, so that others who want this feature have a chance to deliver arguments.


----
Corona-Warn-App Open Source Team

**Comment by tik-boomer** [comment]
Regarding others' arguments: I am in contact with the headmaster and the teacher in charge of digital classes at a secondary school. They agree, that it could be good and helpful to have school use case support by the CWA, but they definitely do not have time to engage in a discussion on github. They are are already overwhelmed by organiszing the school under weekly changes depending on politics and "incidence".

Of course I am looking forward to more arguments on this topic - but I am confident that the arguments in my post are already substantial.

**Comment by tik-boomer** [comment]
@heinezen: Shouldn't the "declined" label be removed? Not sure whose task this would be?

**Comment by heinezen** [comment]
@tik-boomer Still no news, sorry. The label `declined` is still there because that's the last official answer we got.

----
Corona-Warn-App Open Source Team

**Comment by larswmh** [comment]
Closing this issue as the related internal ticket is set to `obsolete`.

There were no more updates.
