### ISSUE TITLE
[Overview] Issues reg. the website

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#479]
**This is an overview over open issues regarding the [website](https://www.coronawarn.app).**
*Please note that we aren't mirroring every issue opened in the https://github.com/corona-warn-app/cwa-website repository here, only the ones that could be interesting for a wider audience.*

| Issue | Title | Status | JIRA |
| --- | --- | --- | --- |
| https://github.com/corona-warn-app/cwa-website/issues/1149 | More format options for downloads: PDF, PNG, SVG .... | **OPEN** | not mirrored |
| https://github.com/corona-warn-app/cwa-website/issues/1152 | Refresh QR code automatically | **OPEN** | not mirrored |
| https://github.com/corona-warn-app/cwa-website/issues/1702 | Add CWA logo in the middle of generated event QR-Codes | **OPEN** | not mirrored |

This overview was last updated on 21.02.2023 (dd.mm.yyy).

**Comment by molarya1** [comment]
Hi @dsarkar @heinezen @Ein-Tim have any/all of these issues been attended to? If not, please do let me know, I'd love to take initiative here and take a crack at these :)

**Comment by Ein-Tim** [comment]
@molarya1 

You can certainly tackle these issues if you have the knowledge to. Just write a comment in the corresponding issue, so that we know you are working on this.

**Comment by Ein-Tim** [comment]
As [CWA development is ending](https://www.coronawarn.app/en/faq/results/#ramp_down), I'm discontinuing this overview.
