### ISSUE TITLE
Allow checked in users to share QR-Code

### ISSUE THREAD

**Issue by pkreissel** [corona-warn-app/cwa-wishlist#487]
## Current Implementation

If you check into an event, and then meet someone who is not yet checked in, you would have to tell them to find the QR-Code with the host of the event, reducing the chance they would check in at all. Alternatively the host could print out the QR-Code multiple times, which might not always be possible.  
If you would like to share the QR-Code with others you would have to photograph it at the time you scan it. 

## Suggested Enhancement

It would be more convenient if people who are checked in could share the QR-Code with others, even if they are not hosts of the event. 

## Expected Benefits

Many events have not just one host and multiple participants. In the current implementation hosts have to print out sheets if they wanted to reach all guests. 
However there are situation when no printer is available (e.g. ad hoc meeting at a firm). Also people shouldn't be forced to pass their mobile phone around, as it contains sensitive information. 
Printing stuff on paper is also not environmentally friendly. 
It's just much easier if anyone who already checked in could share the meeting QR-Code with others. 
 
----
Internal Tracking-ID: [EXPOSUREAPP-6748](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6748)

**Comment by heinezen** [comment]
Hey @pkreissel ,

Thank you for your proposal. We have notified the devs by adding your request to our internal Jira ticketing system (tracking ID: EXPOSUREAPP-6748). The development team and the RKI will now review the proposal. We will report back here on Github if we have any news on the issue.

----
Corona-Warn-App Open Source Team

**Comment by MarcoSteinke** [comment]
I think I found something in your argumentation, which should be rethought:

> It would be more convenient if people who are checked in could share the QR-Code with others, even if they are not hosts of the event.

The hosts should be able to decide wether a code can be shared or not. There could be a point where a host sends his code via e-mail and only wants a certain group of visitors to be able to scan the code by direct adressing. The hosts could alienate the code as `entry ticket` or use as any other form of verification.

**Comment by heinezen** [comment]
Hello everyone,

This feature request has been declined and will not be pursued further. The reason for this decision is that the event organizer should have control over who they distribute the QR code to.

----
Corona-Warn-App Open Source Team
