### ISSUE TITLE
Modify risk assessment according to vaccination status

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-wishlist#488]
## Current Implementation

The current calculation of risk assessment takes no account of the vaccination status of the app user.

## Suggested Enhancement

The app should register the vaccination status of the user and modify the risk assessment accordingly.

This is related to the wishlist issue "Advice for app use by people who have been vaccinated" https://github.com/corona-warn-app/cwa-wishlist/issues/457 which has been resolved through the publication of https://www.coronawarn.app/en/faq/#vac_cert_red_warning.

## Expected Benefits

Vaccination reduces the risk of becoming infected. By modifying the risk assessment, warnings issued by the app should be more accurate and targeted, so that the right people isolate and get tested.

---
Internal Tracking ID: [EXPOSUREAPP-6716](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6716)

**Comment by dsarkar** [comment]
Good morning @MikeMcC399,

Thanks for the proposal. Internal Tracking ID: [EXPOSUREAPP-6716](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6716)
Best, DS

---
Corona-Warn-App Open Source Team

**Comment by di-sc** [comment]
Some thoughts to this point: When thinking about the CoronaWarnApp to be a tool to track infections even if the main risk of the virus to the people is over. The Coronavirus won't go away in the near future so the CoronaWarnApp may still be valuable.
Also people who have been infected could be treated in the same way as vaccinated people. The CoronaWarnApp knows that a person was positive tested, so after 14 days it could treat him/her in the same way as a vaccinated person (Perhaps this is already the case but I don't know).
Clear is also that the effect of an infection a person has gone through and a vaccination will decrease after some time. The scientists assume that it persists for min. half a year. Even if the person does not get a hard illness he/she may be able to again spread the virus (similar to the flu, this has to be confirmed by experts).
_My suggestion_: Add also the date after an infection and the vaccination date into account for the risk calucation.
This may also be important for #24 (people may not be infected but be able to spread the virus) and a general risk calculation as mentioned in #280 (if the necessary ENF extension would be available).

**Comment by MikeMcC399** [comment]
- Related to wishlist item #648 which suggests modifying the guidelines to cover the case of a vaccinated person receiving a red warning.

**Comment by MikeMcC399** [comment]
See also FAQ [Does my vaccination status affect the calculation of the risk? Does the calculation of the risk change if a vaccinated person has become infected, and then warns other users?](https://www.coronawarn.app/en/faq/#vac_cert_risk_assesment) which says:

"Risk calculation and vaccination certificates are independent features of the app. The risk calculation does not take into account whether you are vaccinated against COVID-19. The calculation of the risk also does not change if a vaccinated person has become infected, and then warns other users."
