### ISSUE TITLE
Contact journal synchronization for multiple phones

### ISSUE THREAD

**Issue by FlightMS** [corona-warn-app/cwa-wishlist#490]
Due to my job, I use two cell phones with the Corona-Warn-App (company cell phone and private cell phone).
Since I don't always have both phones with me at the same time, I have to maintain the contact journal separately on both devices, so that both are on the same status. The person behind both phones is the same.

Is there a possibility to provide an optional synchronization or something similar like an export/import feature, which can be used to keep the journal on the same level on both devices without further interaction by me?

----
Internal Tracking-ID: [EXPOSUREAPP-7219](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7219)

**Comment by fynngodau** [comment]
This sounds technically very challenging, as you wouldn't want the data to pass through a central server.

**Comment by jucktnich** [comment]
I do have another way. You could do the sync by qr code. (Put the data in the code.)

**Comment by fynngodau** [comment]
It's a good idea for exporting and importing, but this won't work conveniently enough for using it as described in OP.

**Comment by jucktnich** [comment]
Is it to inconvenient to scan two qr-codes for one sync? Idk, but I think it would be ok for me.

**Comment by FlightMS** [comment]
Sync by QR Code is already a good idea.

My idea is the following: All data from the contact journal will be stored in an encrypted file. The user can choose where to store it - in the local filesystem on the phone or even in attached cloud storage (OneDrive, Dropbox or personal OwnCloud etc) or send it via Mail, Airdrop, etc.
You can open the file on another phone by scanning the encryption QR Code from the other phone (or enter password etc). To enable automatic sync the file will be opened every time when starting the app, merge all possible changes like new entries with the contact journal and save the contact journal back to the file. On the other phone, the process starts again.
Another system that also works with this system (and inspired me) was the KeePassium App. https://github.com/keepassium/KeePassium#automatic-sync

Or is this too complicated to implement or problems with data security?

**Comment by larswmh** [comment]
Closing this issue as its related internal ticket was set to obsolete.

> This feature would need too much effort for too few benefits.
