### ISSUE TITLE
Capitalize German locations

### ISSUE THREAD

**Issue by DerVogel2020** [corona-warn-app/cwa-wishlist#491]
## Current Implementation
There are locations which begin with a small letter, but alone standing locations should begin with a capital letter.
I found "öffentliches Gebäude", "anderer Ort", "private Feier", "anderes Event".

## Suggested Enhancement
Instead of 
"öffentliches Gebäude" --> "Öffentliches Gebäude"
"anderer Ort" --> "Anderer Ort"
"private Feier" --> "Private Feier"
"anderes Event" --> "Andere Veranstaltung"

## Expected Benefits
Correct German wording in both apps and the website.

## References
https://github.com/corona-warn-app/cwa-app-android/pull/2981

https://github.com/corona-warn-app/cwa-website/pull/1169#issuecomment-829114810

https://github.com/corona-warn-app/cwa-website/pull/1169#issuecomment-829117407

## Other
After some research, I think it's a bug. See 
http://www.rechtschreibrat.com/DOX/rfdr_Regeln_2016_redigiert_2018.pdf  § 54 (5) and § 63 (2)

**Comment by DerVogel2020** [comment]
@dsarkar I could create issues in all the three repositories and corresponding pull requests if this is to be implemented.

**Comment by heinezen** [comment]
Hey @DerVogel2020 ,

Thanks, we will take a look. One small thing: Can you link the code lines where the missing capitalization occurs? You can link a line by clicking on the line number in the XML, then select "Copy permalink" in the three-dot-menu.

Also, if these are spelling mistakes, we will maybe handle them as a bug.

----
Corona-Warn-App Open Source Team

**Comment by DerVogel2020** [comment]
Yes.

**Comment by DerVogel2020** [comment]
**Android App:**
https://github.com/corona-warn-app/cwa-app-android/blob/e1ec946e09600826d16ea389aa8dd96f7c959129/Corona-Warn-App/src/main/res/values-de/event_registration_strings.xml#L81
https://github.com/corona-warn-app/cwa-app-android/blob/e1ec946e09600826d16ea389aa8dd96f7c959129/Corona-Warn-App/src/main/res/values-de/event_registration_strings.xml#L86
https://github.com/corona-warn-app/cwa-app-android/blob/e1ec946e09600826d16ea389aa8dd96f7c959129/Corona-Warn-App/src/main/res/values-de/event_registration_strings.xml#L102
https://github.com/corona-warn-app/cwa-app-android/blob/e1ec946e09600826d16ea389aa8dd96f7c959129/Corona-Warn-App/src/main/res/values-de/event_registration_strings.xml#L110
**Website:**
https://github.com/corona-warn-app/cwa-website/blob/fef0e3f81f580165d37f6de37564acc4a41a9b0d/src/data/eventregistration_de.json#L46
https://github.com/corona-warn-app/cwa-website/blob/fef0e3f81f580165d37f6de37564acc4a41a9b0d/src/data/eventregistration_de.json#L47
https://github.com/corona-warn-app/cwa-website/blob/fef0e3f81f580165d37f6de37564acc4a41a9b0d/src/data/eventregistration_de.json#L50
https://github.com/corona-warn-app/cwa-website/blob/fef0e3f81f580165d37f6de37564acc4a41a9b0d/src/data/eventregistration_de.json#L52
**iOS App:**
https://github.com/corona-warn-app/cwa-app-ios/blob/6626c3733244f2333a577f5963c567383db87c5c/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L2090
https://github.com/corona-warn-app/cwa-app-ios/blob/6626c3733244f2333a577f5963c567383db87c5c/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L2102
https://github.com/corona-warn-app/cwa-app-ios/blob/6626c3733244f2333a577f5963c567383db87c5c/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L2116
https://github.com/corona-warn-app/cwa-app-ios/blob/6626c3733244f2333a577f5963c567383db87c5c/src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings#L2122

**Comment by DerVogel2020** [comment]
@heinezen if the texts are not redundant in other files, you find the lines above

**Comment by Ein-Tim** [comment]
1. I'd suggest to rename the title of this issue to something like "Capitalize German locations" to make it clearer what's the problem
2. I agree that we should capitalize these things
3. I'm not sure if we should change "Event" to "Veranstaltung", this should definitely clarified with the stakeholders. 

In general a good catch @DerVogel2020!

**Comment by DerVogel2020** [comment]
> 1. I'd suggest to rename the title of this issue to something like "Capitalize German locations" to make it clearer what's the problem

Done.

> 3. I'm not sure if we should change "Event" to "Veranstaltung", this should definitely clarified with the stakeholders. Also, it's not enough to only change "Event" in the "Create QR code" section, this term is used all over the app.

Should be a separate issue. I found some occurrences of Veranstaltung in the repo. Have to look into it, if "Event" in the event registration is the meaning. E.g. in legal notes.

**Comment by DerVogel2020** [comment]
Edited "Other" in the issue, because it's a bug.

**Comment by Ein-Tim** [comment]
I think it's right with small letter because it's "ein öffentliches Gebäude" (for example). You could argue that this is the beginning of the sentence, but I think it's more like a list.

**Comment by DerVogel2020** [comment]
Closed, because there are some conventions. See https://github.com/corona-warn-app/cwa-app-android/pull/3038#issuecomment-831049896

**Comment by dsarkar** [comment]
@DerVogel2020 Thanks anyway for the suggestions! Best, DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Seems like they will change this in version 2.3: https://github.com/corona-warn-app/cwa-app-android/pull/3177 & https://github.com/corona-warn-app/cwa-app-ios/pull/2682.

@DerVogel2020 Would you like to open a PR in the website repository for this change?

**Comment by DerVogel2020** [comment]
Sure.

**Comment by dsarkar** [comment]
@DerVogel2020 Thanks.
