### ISSUE TITLE
Rename Event to Veranstaltung in German translated apps and website

### ISSUE THREAD

**Issue by DerVogel2020** [corona-warn-app/cwa-wishlist#492]
## Current Implementation
Event is not translated to German.

## Suggested Enhancement
Use Veranstaltung instead

## Expected Benefits
100% translated apps and website

## References
#491 
https://github.com/corona-warn-app/cwa-website/pull/1169#issuecomment-829114810
https://github.com/corona-warn-app/cwa-wishlist/issues/491#issuecomment-829268607

e.g. https://github.com/corona-warn-app/cwa-app-android/blob/e1ec946e09600826d16ea389aa8dd96f7c959129/Corona-Warn-App/src/main/res/values-de/legal_strings.xml#L22

## Other
I think this change should be discussed with the product owner.

---
Internal Tracking ID: [EXPOSUREAPP-7154](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7154)

**Comment by MikeMcC399** [comment]
The legal German legal document [Datenschutzerklärung](https://www.coronawarn.app/assets/documents/cwa-privacy-notice-de.pdf) uses the term "Event" too. The German [Nutzungsbedingungen](https://www.coronawarn.app/assets/documents/cwa-eula-de.pdf) does not reference events at all.

In the legal text the heading "Event-Daten" is also used to cover both Events and Places.

**Comment by DanAmt** [comment]
I would rename it  to something more general, like "Öffentlicher Raum"

**Comment by DerVogel2020** [comment]
I think, öffentlicher Raum is something different. Private Feier doesn't fit in this category, but öffentliches Gebäude does fit.

**Comment by dsarkar** [comment]
@DerVogel2020 @DanAmt @MikeMcC399 Thanks. Internal Tracking ID: [EXPOSUREAPP-7154](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7154)

---
Corona-Warn-App Open Source Team

**Comment by DerVogel2020** [comment]
Not relevant anymore.
