### ISSUE TITLE
[Event QR] add button for create QR in QR submenu

### ISSUE THREAD

**Issue by nilsriesenberg** [corona-warn-app/cwa-wishlist#495]
Add a button to create a QR-Check-In code in the "Check-In" submenu.

## Current Implementation

Currently the button to create a QR code only exists on the main page and the users are unable to create a QR code from the "Check-In" submenu. This is against the expected behaviour of the application.

## Suggested Enhancement

Add a button or an entry to create a code in the submenu of the "Check-In" page.

## Expected Benefits

better UX, closer to an expected behaviour of the app

**Comment by Ein-Tim** [comment]
Hey @nilsriesenberg 👋

Thank you for your contribution here!

This is closely related to the issue #469 "Remove event tile on main screen" which asks to bundle all features of the event-registration in one place.

If you also think that your suggestion is already covered in #469, I'd ask you to close this issue, monitor #469 and if necessary to comment there.

Thank you & stay safe!

**Comment by nilsriesenberg** [comment]
@Ein-Tim Thanks i was not aware of this issue being already existent. The searchfunction did not lead me to it.

Closed Issue #495 and moved suggesstions to #469.
https://github.com/corona-warn-app/cwa-wishlist/issues/469#issuecomment-831435870

**Comment by dsarkar** [comment]
@nilsriesenberg @Ein-Tim Thanks.

---
Corona-Warn-App Open Source Team
