### ISSUE TITLE
 Add an overview for rapid test partners

### ISSUE THREAD

**Issue by DerVogel2020** [corona-warn-app/cwa-wishlist#498]
## Feature description

As of version 2.1 Antigen-Rapid-Test results can be obtained by the CWA. Even though there are only few partners at the moment an overview in the apps of all current partners.
Links to the partners websites would also be nice, like implemented for the website in https://github.com/corona-warn-app/cwa-website/pull/1205.

See also the feature request https://github.com/corona-warn-app/cwa-website/issues/1202 for the website

## Problem and motivation

The problem is that people don't know wether their local test center is included in the CWA.

People don't want to check the press releases on a regular basis and prefer to have a comprehensive overview.

## Is this something you're interested in working on

No.

---
Internal Tracking ID: [EXPOSUREAPP-7204](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7204)

**Comment by DerVogel2020** [comment]
If #398 won't be implemented, at least an overview would be nice.

**Comment by dsarkar** [comment]
The blog https://www.coronawarn.app/en/blog/2021-05-02-corona-warn-app-version-2-1/ lists now 4 partners with links included.

**Comment by dsarkar** [comment]
We will prepare FAQ. Internal Tracking ID: [EXPOSUREAPP-7204](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7204)

---
Corona-Warn-App Open Source Team

**Comment by nschloe** [comment]
A map is now available [here](https://map.schnelltestportal.de/).

**Comment by DerVogel2020** [comment]
OK. Very nice. Is there already an in-app-link to the website? I couldn't check with Version 2.4 yet (staged rollout...).

**Comment by nschloe** [comment]
It's in 2.4 (accordining to the changelog).

**Comment by DerVogel2020** [comment]
I will check, then close this issue.

**Comment by MikeMcC399** [comment]
@nschloe 
> It's in 2.4 (accordining to the changelog).

Could you give an explicit reference to where you are reading this?

**Comment by nschloe** [comment]
https://www.coronawarn.app/de/blog/2021-06-24-cwa-version-2-4/

> Außerdem können Nutzer*innen ab sofort über eine Online-Schnelltestpartnersuche Testanbieter finden, die die Übermittlung von Schnelltest-Ergebnissen an die Corona-Warn-App unterstützen.

**Comment by MikeMcC399** [comment]
@nschloe 
Thanks! The text you quoted:

"Außerdem können Nutzer*innen ab sofort über eine [Online-Schnelltestpartnersuche](https://map.schnelltestportal.de/) Testanbieter finden, die die Übermittlung von Schnelltest-Ergebnissen an die Corona-Warn-App unterstützen."

is followed by

"Zusätzlich hat das Projektteam eine Schnelltestpartnersuche veröffentlicht. Unter https://map.schnelltestportal.de/ können Nutzer*innen ab sofort Schnelltestanbieter in ihrer Nähe finden, die die Übermittlung des Testergebnisses in die Corona-Warn-App anbieten. Durch das Setzen von Filtern, wie beispielsweise Testart oder Öffnungszeiten, können sie den gewünschten Anbieter schnell finden und teilweise über den angegebenen Link direkt einen Termin buchen."


I haven't seen anything to say that the link https://map.schnelltestportal.de/ is built into the app, and I also couldn't find anything in the 2.4.2-RC0 build I ran. (I don't have the 2.4.1 release yet.) If anybody finds this in the app it would be good to know.

**Comment by Ein-Tim** [comment]
The map is not mentioned or integrated in the app.

**Comment by Ein-Tim** [comment]
FYI: Version 2.6 will contain a new box which is titled "Testmöglichkeit finden" and looks like this: 

<img src="https://user-images.githubusercontent.com/3601228/123962296-98260780-d9b1-11eb-8262-0b886a675b32.PNG" width="300">

When clicked, the FAQ entry https://www.coronawarn.app/en/faq/#where_can_i_get_tested will open.

Source: https://github.com/corona-warn-app/cwa-app-ios/pull/3048/

**Comment by DerVogel2020** [comment]
Implemented in 2.6.1

**Comment by dsarkar** [comment]
Dear @DerVogel2020 and community. Thanks for proposal and participating here. Best, DS


---
Corona-Warn-App Open Source Team
