### ISSUE TITLE
Tab for vaccination certificate

### ISSUE THREAD

**Issue by fynngodau** [corona-warn-app/cwa-wishlist#499]
### Current design

According to https://github.com/corona-warn-app/cwa-app-android/pull/3061#issuecomment-831986993, current mockups contain plans to add a new home screen card for vaccination certificates.

![screenshot](https://user-images.githubusercontent.com/2919625/116973424-cf7f7d00-acbc-11eb-938f-0b1c29fccc29.png)

### Suggested Enhancement

A new tab could be added for the certificate. It could only be shown in case the certificate has actually been added.

So you would use the home screen card to register your certificate, but once it is registered, it gets its own tab.

It would be possible to make users aware of this functionality like follows: "A new tab has been added to your Corona-Warn-App. Use it to access your proof of vaccination."

### Expected Benefits

Users can access their proof of vaccination quicker, but do not have a useless tab in case they don't have the certificate in the app.

---
Internal Tracking ID: [EXPOSUREAPP-7152](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7152)

**Comment by dsarkar** [comment]
@fynngodau Thanks. Internal Tracking ID: [EXPOSUREAPP-7152](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7152)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Will be done in version 2.4: https://github.com/corona-warn-app/cwa-app-ios/pull/2796

**Comment by heinezen** [comment]
Hello everyone,

This has been integrated into the current CWA release 2.4.

----
Corona-Warn-App Open Source Team
