### ISSUE TITLE
Unify QR code scanner to work with all QR code types

### ISSUE THREAD

**Issue by dideldei** [corona-warn-app/cwa-wishlist#501]
## Current Implementation
The Check in feature is on the fixed bottom of the screen when the app is open, in contrast to that, many displays to not show the "Have you been tested" tab on the first glance without changing the viewport. This leads to a lot frustrating and often aborted attempts to read your test QR code with the check in feature camera. 
A real life example is to be found here: https://twitter.com/WorstAtRoutine/status/1388155757791690753?s=20

## Suggested Enhancement
Either enable the qr code scan to decide wether the user scaned a test or a check in qr or place a "test" option next to the "check in" option on the button to let users immediatly recognize there is sth. to discriminate here.

## Expected Benefits
More users would be able to enter their test qr successfully into the app. Less frustration would lead to better acceptance in the population. As the "test" feature is the most prominant feature it should be found at least as easily as the "check in" feature in UX.

----
Internal Tracking ID: [EXPOSUREAPP-7281](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7281)
Internal Tracking ID: [EXPOSUREAPP-7594](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7594) duplicate
Internal Tracking ID: [EXPOSUREAPP-8395](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8395) iOS 2.11
Internal Tracking ID: [EXPOSUREAPP-8903](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8903) Android 2.11

duplicate or strongly related to: https://github.com/corona-warn-app/cwa-wishlist/issues/501
duplicate or strongly related to: https://github.com/corona-warn-app/cwa-wishlist/issues/575

**Comment by Ein-Tim** [comment]
Related issues: 

- https://github.com/corona-warn-app/cwa-app-android/issues/2949
- https://github.com/corona-warn-app/cwa-app-android/issues/2909#issuecomment-824789923

**Comment by pkreissel** [comment]
The app should just scan any QR-Code with both features and then tell the user afterwards that they are now being redirected to the right feature.

**Comment by heinezen** [comment]
https://github.com/corona-warn-app/cwa-website/pull/1219 will add more details to the FAQ. Some improvements are also coming to the app via https://github.com/corona-warn-app/cwa-app-android/pull/3046. We will try improve the UI further if necessary.

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
New ticket ID: [EXPOSUREAPP-7594](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7594)

----
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-7281](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7281)
Internal Tracking ID: [EXPOSUREAPP-7594](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7594) duplicate
Internal Tracking ID: [EXPOSUREAPP-8395](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8395)


duplicate or strongly related to: https://github.com/corona-warn-app/cwa-wishlist/issues/501
duplicate or strongly related to: https://github.com/corona-warn-app/cwa-wishlist/issues/575

**Comment by Ein-Tim** [comment]
On Twitter I see many reports from users who are trying to scan their EU digital COVID test certificate with the QR code scanner inside of the "Register your Test" box. 
I can really understand them, normal users don't make a big difference between a "test QR code" and a "QR code for a test certificate". 
Especially here it would be nice if the QR code scanner in the "Register your Test" box would recognize if a test certificate is scanned and sends the user to the correct QR code scanner.

**Comment by MikeMcC399** [comment]
Also related : https://github.com/corona-warn-app/cwa-wishlist/issues/343 "Improve response to scanning non-CWA lab QR code".

**Comment by Ein-Tim** [comment]
Hey @dideldei, good news!

This has been implemented in version 2.11, which was released today: [Corona-Warn-App version 2.11 simplifies QR code scanning](https://www.coronawarn.app/en/blog/2021-10-06-cwa-version-2-11)

If you have an iOS device, you can download the update instantly (visit the Corona-Warn-App in the App Store & download the latest update), under Android the version will be available for everyone in the next 48h. 

If you consider your suggestion as implemented, I suggest to close this issue! 

P.S.: Version 2.12 adds a own Tab Bar icon with this "Universal QR-Code scanner".

**Comment by dsarkar** [comment]
Dear @dideldei and community, thanks for contributing here. Best, DS


---
Corona-Warn-App Open Source Team
