### ISSUE TITLE
Add quick action for Vaccination Certificate

### ISSUE THREAD

**Issue by MarcoSteinke** [corona-warn-app/cwa-wishlist#504]
## Feature description

I am referring to ` issue` https://github.com/corona-warn-app/cwa-wishlist/issues/499 and building my idea on this feature. If there will be a `Vaccination Certificate` tab in the future, add a shortcut when pressing the icon of the `CWA` on the Home Screen which can directly send the user into the app and display the according tab, if existing.

If a user does not have a registered certificate yet, there could possibly be a shortcut to directly enter the according tab to register a vaccination certificate.

#### 1. Motivation:
The current development in the politics seems to welcome privileges for citizens which are categorized as `fully vaccinated`. Thus shops/businesses in Germany could possibly use the vaccination certificate as requirement to enter their building. So there is a situation in which you want to directly access your vaccination certificate.

#### 2. Problem:

In regions with slow internet connections, users could get caught in longer loading times when opening the CWA. By directly accessing the required vaccination certificate tab, users can skip the loading of the cards in the landing tab of the CWA and only load the required data to show their certificate (if the certificate is stored locally there will not be any loading time using this method) . 

This can on the one hand improve the UX and on the other hand possibly reduce the required time for starting the app and accessing the according tab.

## Is this something you're interested in working on

Yes

---
Internal Tracking ID: [EXPOSUREAPP-7151](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7151)

**Comment by Ein-Tim** [comment]
I support this feature request to 💯%. 

May I suggest to change the title to something like "Add quick action for vaccination certificate", because one could confuse "home screen" with the apps home screen and not the one of the phone. 

Thank you!

**Comment by dsarkar** [comment]
@MarcoSteinke @Ein-Tim Thanks for the suggestions. Internal Tracking ID: [EXPOSUREAPP-7151](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7151). Best wishes, DS 

---
Corona-Warn-App Open Source Team

**Comment by jucktnich** [comment]
What's the status here? Got this somewhat lost?

**Comment by tomber42** [comment]
No quick access to certificate.. But we all need this.

**Comment by MikeMcC399** [comment]
I'm using the [CovPass-App](https://digitaler-impfnachweis-app.de/en) to get quick access to my vaccination certificate display. I have both CovPass and CWA installed.

Tapping on 
![CovPassApp_ic_launcher](https://user-images.githubusercontent.com/66998419/139391814-a3faa32a-c7b8-4aee-9b9e-cd2449da85a0.png)
shows
![CovPass display](https://user-images.githubusercontent.com/66998419/139391895-2c59f7d0-92a7-42da-aab4-e6ef0de76d6a.jpg)
with the text "Complete since ...".

For those situations where the person doing the checking is happy just to see one screen without using the [CovPassCheck app](https://digitaler-impfnachweis-app.de/en/covpasscheck-app) to digitally verify the certificate, [CovPass-App](https://digitaler-impfnachweis-app.de/en) is the simplest app to use.

CWA needs more taps to achieve the same result and even then, the information in CWA is not so consolidated that there is one easily viewable screen with name, vaccination status and QR code all viewable at once without scrolling.

---
CWA on the other hand, needs an extra tap

![CWA_ic_launcher](https://user-images.githubusercontent.com/66998419/139392049-48eaba6c-c55a-4610-b259-2aab34e7f1ea.png)

![Corona-Warn_Cert_select](https://user-images.githubusercontent.com/66998419/139392080-b5aae1b4-9211-4657-9a94-27a98e17ccfd.jpg)

![Corona-Warn display](https://user-images.githubusercontent.com/66998419/139392098-a00f1b15-bb99-4f2d-a6f5-8b2452d4fadc.jpg)

and then on this screen it does not show the vaccination status in human readable form. This requires another tap and some scrolling.

---
So for me the conclusion is that adding a quick action for CWA would not completely solve the ease of use issue. CWA would need to be more like [CovPass-App](https://digitaler-impfnachweis-app.de/en) if the goal is to be able to display vaccination certificate information in one tap in a form that a trusting checker would accept without needing any scrolling.

**Comment by MarcoSteinke** [comment]
> So for me the conclusion is that adding a quick action for CWA would not completely solve the ease of use issue. CWA would need to be more like [CovPass-App](https://digitaler-impfnachweis-app.de/en) if the goal is to be able to display vaccination certificate information in one tap in a form that a trusting checker would accept without needing any scrolling.

In my eyes there is no problem in letting the quick action directly open the correct view in the CWA and perform a scroll to the right location. 

But yes I have to agree, there are definitely more actions required to access the certificate than in the CovPass app.

On the other side the CovPass app was created to be only able to display the certificate, where the CWA has a lot of other features which are the main functionality of the application, so the certificate is only a side-feature which is not in the focus, but also shall not be in the focus.

With adding a quick action which directly leads to the certificate in a human-readable way, you could open a direct door to a side-feature, without giving it more attention inside of the app, so the main task of the CWA can remain as it is right now.

**Comment by thomasaugsten** [comment]
A check without scanning is not possible. 
It is intended from the CWA to protect your data to not show private information on the first screen. 

CWA is also not supporting only manual check because this put other people on risk if a not 3G person can visit a location with a faked screenshot

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for the detailed comparison, forwarded to the internal ticket.

**Comment by jeffbs** [comment]
I can't understand why this feature isn't implemented.

**Comment by svengabr** [comment]
There was an update posted in the Jira ticket however I was not happy with the result as I think it was misunderstood.

Using my excellent photoshop skills I was able to generate this draft as I think this is the expected result of this feature request:
![shortcut](https://user-images.githubusercontent.com/4686874/146391874-c0db840c-2492-4ef5-aebc-20ee725bcf08.png)

Regarding 
> and then on this screen it does not show the vaccination status in human-readable form. This requires another tap and some scrolling.

we got this answer:
> It was requested because of Data Privacy to not show any details on the certificate card. Neither what type of certificate it is nor the vaccination status. That's also why the info text on top got added, to inform the checkers that they need to use the CovCheck App to verify the certificate and can't do so by just looking at it.  So from Design Side we can't add the additional information, as it was an explicit request to not show them by Data Privacy.

I will report back once we got additional feedback regarding the shortcut.

**Comment by MarcoSteinke** [comment]
> 

This is what was originally supposed to be added to the app.

> There was an update posted in the Jira ticket however I was not happy with the result as I think it was misunderstood.
> 
> Using my excellent photoshop skills I was able to generate this draft as I think this is the expected result of this feature request: ![shortcut](https://user-images.githubusercontent.com/4686874/146391874-c0db840c-2492-4ef5-aebc-20ee725bcf08.png)
> 
> Regarding
> 
> > and then on this screen it does not show the vaccination status in human-readable form. This requires another tap and some scrolling.
> 
> we got this answer:
> 
> > It was requested because of Data Privacy to not show any details on the certificate card. Neither what type of certificate it is nor the vaccination status. That's also why the info text on top got added, to inform the checkers that they need to use the CovCheck App to verify the certificate and can't do so by just looking at it.  So from Design Side we can't add the additional information, as it was an explicit request to not show them by Data Privacy.
> 
> I will report back once we got additional feedback regarding the shortcut.

**Comment by mrleine** [comment]
Can you already see when this function will be rolled out?

**Comment by Ein-Tim** [comment]
This has been implemented (at least under iOS). 

<img src="https://user-images.githubusercontent.com/67682506/160155693-b4556138-fd0a-48c8-b7b4-62fcd4450593.png" width="300">

**Comment by Ein-Tim** [comment]
@MarcoSteinke Would you like to close this issue?

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Do you think this is implemented in CWA Android? I cannot see it there. I only see "Add Entry" on Android (CWA 2.19.2).

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Oh sorry, I didn't check Android. The corresponding Android PR https://github.com/corona-warn-app/cwa-app-android/pull/4685 is still in draft mode.

**Comment by MikeMcC399** [comment]
- PR https://github.com/corona-warn-app/cwa-app-android/pull/4685 was included in[ CWA Android 2.23.1](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.23.1) so it seems that this wishlist item has been fulfilled for both iOS and Android now.

**Comment by MarcoSteinke** [comment]
> * PR [Add app shortcuts to primary targets (EXPOSUREAPP-5414) cwa-app-android#4685](https://github.com/corona-warn-app/cwa-app-android/pull/4685) was included in[ CWA Android 2.23.1](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.23.1) so it seems that this wishlist item has been fulfilled for both iOS and Android now.

Amazing, this was a typical case of german bureaucracy for a simple feature,  but still very thankful for this feature being a part of the CWA now! 😄
