### ISSUE TITLE
[Check-in/Presence Tracing] Concept: Allow Health Authorities to warn CWA-users from infected non CWA-Users

### ISSUE THREAD

**Issue by vaubaehn** [corona-warn-app/cwa-wishlist#505]
## Prologue

@Ein-Tim shared a [link of the public part of the meeting "Ausschuss Digitale Agenda" at May 5th](https://dbtg.tv/cvid/7519454) in our [community Slack channel](https://covidapps.slack.com/archives/C019A2K0NAZ/p1620406302001000). Martin Fassunge (SAP project lead) was invited as an expert. In minute 58:12, Tabea Rössner (Büdnis90/Die Grünen) asked Martin Fassunge, whether there is already a solution or a concept for the situation, when a non-CWA user who attended an event and gets tested positive later, that CWA users can get warned subsequently. Martin Fassung responded "certainly not".
Actually, I think this could be possible, quickly implemented and with rather low effort and costs.
 
The following concept is basically an idea that was developed during a discussion by @floscher , @di-sc and @jucktnich in #486. I created this as a duplicate accidentally.

## Feature description/Concept

Use case: A host is creating a QR code for his event (CWA Event Registration/Presence Tracing). If legislation will still need this in future: People who are not using CWA will leave their contact details in analog paper lists. After this event, a non-CWA user gets tested positive, and the responsible health authority traces their contacts. Health authority learns about the attendence of the infected person in that event, and requests paper lists of other guests from the host.
New:
The health authorities additionally request the host's QR code for the event of that day. With the QR code, they receive the GUID of the event. Contact tracers in health authorities release a warning to all CWA users who were checked in at the same time (+30 minutes) like the infected non-CWA user via a web- or app-based interface provided by T-Systems/SAP . 

## Requirements

* The host would need to keep QR codes for the last 14 days to be able to provide the effective QR code upon request to the health authority. This would probably need new "Verordnungen" from the federal states. As long as contact lists still need to be maintained by (professional) hosts, this should be no additional effort for them.
* The health authority would need to be able to transfer the GUID from the QR code into the interface provided by T-Systems/SAP. Practically, this could be as easy as to read the QR code with the contact tracer's mobile phone's camera app, and copy/paste the URI into the interface. For comfort and to prevent flaws, a specialised app could be created - and for that already existing modules of the CWA app could be used.
* A backend for the interface would be needed, which would probably be quite close to the RAT solution provided by T-Systems, but would only need to consume GUID of the event, as well as start time and end time of the presence of the non-CWA user. If GUIDs are entered via app only, a frontend is obsolete. If app coding takes too much time, a web-frontend could do the job.
* The health authority would need authentication to provide the GUID of the event. For a fast start, IP-based authentication might be fair enough (as I assume all health authorities have their own static IPs). For better security, certificate based (issued for department or for single users) authentication likely meet best standards, but could probably be implemented at a later point in time to not lose too much time for implementation. OR: try to integrate the health authorities into the cwa-verification-server/cwa-verification-iam/cwa-verification-portal process flow.
* The backend would need to be able to deliver/incorporate the GUID of the event to the CWA-server list for Presence Tracing Warnings.

## Problem and motivation

I assume, to release a warning to CWA users takes less than five minutes for a concact tracer when the QR code is available.
To ask the host to (additionally) provide a QR code takes seconds. So, with marginal extra work in health authorities many more people could get warned _faster_.
This feature is not only in the mind of users already, but also in the mind of politicians. More people would be enabled to receive warnings and take their precautions. This might even be an incentive for more users to use CWA. In best case, paper lists (resp. recorded personal data) could become obsolete more easy, like [Saxony is going first steps](https://www.gruene-fraktion-sachsen.de/presse/pressemitteilungen/2021/corona-warn-app-checkin-sachsen/) now.

## Is this something you're interested in working on

In general yes, but I have limited time, unfortunately.

## Related
This feature is related/basically similar to #486 , and taking up one conclusion from their discussion, that the responsibility for warning others stays with the health authorities and is not delegated to the hosts.

---

@tklingbeil -> maybe you want to forward this to Martin Fassunge as a direct reply to the question in the Ausschuss Digitale Agenda.

---
Internal Tracking ID: [EXPOSUREAPP-6749](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6749)

**Comment by ndegendogo** [comment]
A very nice concept, and imo a logical extension path of today's cwa feature set.
What I like especially, is the extension of cwa impact to (*or rather from?*) non-cwa users.

**Comment by Ein-Tim** [comment]
Something like this will be implemented in version 2.9, work on that has just begun: https://github.com/corona-warn-app/cwa-app-android/pull/3917

However, I'm not sure if this solution covers Health Authorities, I don't think so.

**Comment by Ein-Tim** [comment]
@vaubahen Version 2.9 has been released today. Can this be closed? Or are there any points left?

**Comment by Ein-Tim** [comment]
@vaubaehn Could you maybe give us an update here? Do you consider this as implemented?

**Comment by vaubaehn** [comment]
Although I also think that the implementation doesn't cover health authorities in the way how it was proposed in this issue (authorities can directly warn users when they have access to the event QR code without the need to ask the host to initiate the warning), I think this issue will not be pursued further, so I'm closing here.

Thanks to everyone involved! 🍻
