### ISSUE TITLE
UX: Make it possible to edit the Rapid Test Profil

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#506]
## Current Implementation
With version 2.2, I don't have the possibility to edit the content (e.g. my name, my phone number) of the Rapid Test Profil once I've created it.

## Suggested Enhancement
Make it possible to edit the content of the Rapid Test Profil at any time.

## Expected Benefits
Better UX. Typos happen, and it should be possible to fix them as easy as possible and not have to delete the whole Profile. 

---
Internal Tracking ID: [EXPOSUREAPP-7146](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7146)
Internal Tracking ID: [EXPOSUREAPP-7119](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7119) Android
Internal Tracking ID: [EXPOSUREAPP-7651](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7651) iOS

**Comment by MikeMcC399** [comment]
Same for Android 2.2 release candidate. The only function available after creation of a Rapid Test Profile is "Remove".

**Comment by dsarkar** [comment]
@Ein-Tim @MikeMcC399 Thanks for the suggestion. Internal Tracking ID: [EXPOSUREAPP-7146](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7146). Best, DS 


---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-7119](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7119)

**Comment by dsarkar** [comment]
high priority internally

**Comment by MikeMcC399** [comment]
@dsarkar 

Perhaps [EXPOSUREAPP-7270](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7270) from "Harmonize remove Rapid Test Profile on iOS and Android" https://github.com/corona-warn-app/cwa-wishlist/issues/517 could be considered also in combination, if an additional option to edit the profile is being added?

**Comment by dsarkar** [comment]
@MikeMcC399 Ok, I will put these stories in context.

**Comment by Ein-Tim** [comment]
PR iOS: https://github.com/corona-warn-app/cwa-app-ios/pull/3046

**Comment by vaubaehn** [comment]
PR Android: https://github.com/corona-warn-app/cwa-app-android/pull/3648

**Comment by Ein-Tim** [comment]
This has been **implemented** in version 2.6.

Closing as implemented.
