### ISSUE TITLE
File upload in scanner

### ISSUE THREAD

**Issue by M123-dev** [corona-warn-app/cwa-wishlist#508]
## Feature description
In the scanner, in addition to the flashlight toggle, there should be the possibility to upload photos/files from which the qr code is extracted.

## Problem and motivation
When you get your test documents online, you have to send them to another device or print them, to scan your code,

## Is this something you're interested in working on

No, feel free to work on this.

**Comment by Ein-Tim** [comment]
Hey @M123-dev 

Thank you for contributing here!

Please take a look at #389 which is quite a similar request to yours. If you think so too, please close this issue, monitor #389 and follow up there if necessary.

Have a nice Saturday and stay safe!

**Comment by M123-dev** [comment]
Thanks @Ein-Tim, the issue really deals with the same problem.

**Comment by dsarkar** [comment]
@M123-dev @Ein-Tim  Thanks.

---
Corona-Warn-App Open Source Team
