### ISSUE TITLE
"New Features" screen should contain link to blog post

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#513]
## Current Implementation
The "New Features" screen shown after updating to a new major or minor (not patch!) version only contains some bullet points with a short explanation text of the new features.

## Suggested Enhancement
All releases are covered on https://www.coronawarn.app/en/blog/ (e.g. [the one from version 2.2](https://www.coronawarn.app/de/blog/2021-05-12-corona-warn-app-version-2-2/)). 
The "New Features" screen could contain a link to the blog post where the user can find more information reg. the new release. The blog posts are way more detailed than the in-app texts and often also contain How-Tos, etc.

## Expected Benefits
1. User can find out more about new features
2. User will find a How-To explaining how to use the new features 
3. The blog gets more attention

This is a win-win situation for the user but also for the authors of the blog since their texts will reach more people.

----
Internal Tracking-ID: [EXPOSUREAPP-7273](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7273)

**Comment by heinezen** [comment]
@Ein-Tim 

Thanks. We have created [EXPOSUREAPP-7273](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7273) in Jira to address this request.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@dsarkar Is there any information available on whether this will be implemented?

It would be a very easy change but both the user as well as the team behind the blog posts would benefit from it.

IHMO this is a no-brainer.

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
