### ISSUE TITLE
Add a warning before deleting the Rapid Test Profile

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#514]
## Current Implementation
Once a user has added a Rapid Test Profile via the "Register your Test" box, he/she can delete it by simply clicking on "Remove Rapid Test Profile" ([under iOS](https://user-images.githubusercontent.com/67682506/118035204-35c66880-b36b-11eb-9d59-28a766aec093.PN)) or via clicking on the 3 dots in the right corner and then clicking on "Remove" ([under Android](https://user-images.githubusercontent.com/66998419/117859763-b57f0500-b28f-11eb-85d5-e25849c8a7f8.jpg)).

## Suggested Enhancement
Add a warning after clicking on "Remove Rapid Test Profile"/"Remove" before finally deleting the profile.

## Expected Benefits
Less users accidentally deleting the Rapid Test Profile.

## Acknowledgements
The Android screenshot was taken from https://github.com/corona-warn-app/cwa-website/pull/1240#discussion_r630390396 by @MikeMcC399.

**Comment by jucktnich** [comment]
There is a warning on iOS

**Comment by Ein-Tim** [comment]
@jucktnich Thank you. I see it now, when I tested it on my Emulator it was not there yet but now it is. @MikeMcC399 Could you please check the behavior under Android? Thank you!

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Android warns before removing a Rapid Test Profile, so you should probably close this enhancement request, as the functionality you requested is already present.

![image](https://user-images.githubusercontent.com/66998419/118117411-e1af9880-b3eb-11eb-9155-b073edbf1b6b.png)

**Comment by Ein-Tim** [comment]
Thank you, @MikeMcC399, @jucktnich I was on an outdated RC build which didn't have this warning yet.

Closing as already implemented in version 2.2.
