### ISSUE TITLE
Add a warning before replacing test results

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#515]
## Current Implementation
Since version 2.1 it is possible to register one RAT and one PCR test into the app.
Version 2.2 introduced the Rapid Test Profile and thus the "Register your Test" box is also shown, if you already registered one RAT and one PCR Test.
Here is a screenshot from version 2.2.1 under iOS:

<img src="https://user-images.githubusercontent.com/67682506/118036322-ba65b680-b36c-11eb-995a-6f6c620987d5.PNG" width="300">
Explanation: The first box shows the PCR Test, the second box the RAT and the third box offers to register another new test.

If you do the following steps when already have registered one PCR test and one RAT:
1. Click on "Next Steps" on the "Register your Test" box
2. Click on "Scan QR Code"
3. Click on "Accept"
4. Scan a test QR Code
5. The app shows "Note" and informs that you have already registered a PCR test
6. Click "Next"

you can delete the old test without any further warning.

The screen "Note" looks like all the other screens which the user has go through before the QR code scanner, thus there's a high chance that a user will just click on "Next" without reading the text.
Also, the screen "Note" does **not** mention that a test QR code can only be scanned once.

## Suggested Enhancement
Add a warning after clicking on "Note". For example, take [the warning](https://user-images.githubusercontent.com/67682506/118037472-2f85bb80-b36e-11eb-93dc-00b6d6b1cd79.jpeg) the user gets when he/she clicks on "Delete test" in the "Your Test Result box. 

## Expected Benefits
Less users losing one test QR code because they though they could scan the other QR code again.

## Screen recoding 

For easier understanding, here's a screen recording:

https://user-images.githubusercontent.com/67682506/118037980-d4a09400-b36e-11eb-831b-42d11a1090ad.mp4

----
Internal Tracking-ID: [EXPOSUREAPP-7271](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7271)

**Comment by BastianZim** [comment]
Or maybe allow multiple tests to be added?

**Comment by Ein-Tim** [comment]
@BastianZim 

The wish to manage multiple QR codes has been raised before in #109 & #200.

It has been [declined](https://github.com/corona-warn-app/cwa-wishlist/issues/109#issuecomment-823308830), so sorry, but seems like we won't see something like this.

**Comment by BastianZim** [comment]
@Ein-Tim Thanks for the links and I agree, adding a test for a family member makes no sense. 


My use case would be adding multiple tests I have registered for but not taken yet. 
Basically, I book all of my tests for the next week (One for Monday, one for Wednesday, one for Friday etc.) at once on the Sunday before and would like to add them all to the app afterwards. Once I then take a test the results will be added over time. 

But that's probably a different issue so I'll stop polluting yours with this. 😄

**Comment by Ein-Tim** [comment]
@BastianZim 

Now I understand what you mean. 
May I ask you to [open a new Feature Request](https://github.com/corona-warn-app/cwa-wishlist/issues/new?assignees=&labels=feature+request&template=01_feature_request.md) for this? 

This would make it easier to keep track and it will be handled as a separate internal ticket. 

Thank you!

**Comment by BastianZim** [comment]
Of course, will do that just now. And thanks for your help!

**Comment by heinezen** [comment]
@Ein-Tim 

Thank you. The issue is forwarded to the devs. [EXPOSUREAPP-7271](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7271)

----
Corona-Warn-App Open Source Team

**Comment by ndegendogo** [comment]
[This ticket](https://github.com/corona-warn-app/cwa-wishlist/issues/526) explains a use case why it is important to let the user decide the time when the result of a previous test is no longer needed and can be deleted:
A negative test result is needed to cross the border between Austria and Germany for work, and it is valid for 7 days for this purpose.

**Comment by Ein-Tim** [comment]
This bad UX is still in the app over one year after I opened this issue. It is still a valid issue, but the situation has improved as the user can restore tests from the recycle bin. I still think this would be an easy to implement thing and should be done. Thus leaving this issue open.

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
