### ISSUE TITLE
Harmonize remove Rapid Test Profile on iOS and Android

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-wishlist#517]
## Current Implementation

The user interface to remove a Rapid Test Profile (RTP) differs significantly between the iOS and Android implementations. In iOS the user interface presents the text "Remove Rapid Test Profile" and in Android, a user must first tap on the three-dot symbol before the one-word text "Remove" is displayed.

![Remove Rapid Test Profile](https://user-images.githubusercontent.com/66998419/118110864-3a2e6800-b3e3-11eb-9c9c-e8a7381b836d.jpg)

The Rapid Test Profile (RTP) was introduced in Version 2.2 of CWA. 

## Suggested Enhancement

Make the steps for removing a Rapid Test Profile the same on iOS and Android.

## Expected Benefits

Having different user interface structures on iOS and Android makes describing how to use the app more difficult and complicated. See for instance the FAQ article "How can I create, edit and remove a rapid test profile?" on https://www.coronawarn.app/en/faq/#rat_profile_create_edit_delete, where it was necessary to write two different sections, one for iOS, another for Android.

Conversely, keeping the user interfaces on iOS and Android as close to one another as possible, eases documentation and reduces confusion.

----
Internal Tracking-ID: [EXPOSUREAPP-7270](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7270)

**Comment by heinezen** [comment]
@MikeMcC399 

Thank you for the report. We have created an internal ticket  [EXPOSUREAPP-7270](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7270)

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
In version 2.15.1 of the Android app the text to remove a Rapid Test Profile is:

Android App Version | Text (EN) | Text (DE)
--- | --- | ---
2.15.1 | Delete Rapid Test Profile | Schnelltest-Profil löschen

If this is the same text used in the latest version of the CWA iOS app, then this issue can be closed.

The difference of having the three-dot symbol in Android at the top-right and the menu at the bottom in iOS is a general difference, which is not specific to the Rapid Test Profile. That could be explained somewhere generically in the FAQs, for instance in the https://www.coronawarn.app/en/faq/#application section of the FAQs.

- See also https://github.com/corona-warn-app/cwa-website/issues/2280

**Comment by Ein-Tim** [comment]
Under iOS, I perform these steps to remove a rapid test profile:

1. Open CWA
2. Click on "Manage Your Tests"
3. Click on "Rapid Test Profile"
4. Click on "Edit" on the bottom
5. Click on "Delete Rapid Test Profile"
6. Click on "Delete" in the confirmation pop up.

Video:

https://user-images.githubusercontent.com/67682506/148094529-f96336e6-f87b-435d-bf92-1b10e75aea79.MOV

**Comment by MikeMcC399** [comment]
The texts for deleting a Rapid Test Profile are now the same on iOS and Android. 

- PR #2280 "Incorrect instructions to delete a Rapid Test Profile for Android" is submitted to update the FAQs:
    - https://www.coronawarn.app/en/faq/#rat_profile_create_edit_delete
    - https://www.coronawarn.app/de/faq/#rat_profile_create_edit_delete
- This wishlist item can now be closed.
