### ISSUE TITLE
Sweden

### ISSUE THREAD

**Issue by ozimand1as** [corona-warn-app/cwa-wishlist#52]
Not least, because it has the highest incidence in Europe at the moment according to [RKI](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Quarantaene_Einreisen_Deutschland.html).

Generally I think that neighboring countries, major tourist destinations, countries from which many people migrate(d) to Germany, and countries with a high burden of new infections should be prioritized.

**Comment by toebbel** [comment]
Good point to whitelist the Swedish market because it is on the "red list".

As an expat living in Sweden, I would very much like this app to be available via the Swedish Google Play store.

**Comment by tkowark** [comment]
The app is now also available on the swedish app stores: https://github.com/corona-warn-app/cwa-backlog/issues/9#issuecomment-653050126
