### ISSUE TITLE
Move Error Reports from App Information to Settings

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-wishlist#521]
## Current Implementation

CWA 2.2 includes a new menu item "Error Reports" in "App Information" which allows collecting logs and sending them to technical support.

## Suggested Enhancement

Move the menu item "Error Reports" from "App Information" to "Settings".

Alternatively, "Error Reports" could be added as a menu item which is directly accessed by the three-dot symbol, which would put it in the list under "Settings" making 5 menu items at this level.

## Expected Benefits

All other menu items in "App Information" are read-only. The "Settings" list contains items which allow the user to change the behavior of the app. The "Settings" list includes Exposure Logging (Active/Stopped), Notifications (On/Off), Prioritized Background Activity (On/Off), Share Data (On/Off) and Reset App.

"Error Reports" fits the category "Settings" better, because the user actively changes how the app works and what happens with the data.

Moving the menu item would create a more logical and intuitive user experience by grouping "Error Reports" in "Settings" together with other items where the user controls how the app works.

---
Menu displayed after tapping three-dot symbol (older screenshot)
![image](https://user-images.githubusercontent.com/66998419/118247783-e041a700-b4a3-11eb-9d2b-554d5903554e.png)

---
App Information menu
![image](https://user-images.githubusercontent.com/66998419/118249962-40d1e380-b4a6-11eb-9d1d-5265ec231368.png)

---
Settings menu
![image](https://user-images.githubusercontent.com/66998419/118250173-770f6300-b4a6-11eb-83f4-60d5719714dd.png)

---
Internal Tracking ID: [EXPOSUREAPP-7286](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7286)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for the suggestion. Internal Tracking ID: [EXPOSUREAPP-7286](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7286)


---
Corona-Warn-App Open Source Team
