### ISSUE TITLE
Allow tranferring vaccination certificate when changing devices

### ISSUE THREAD

**Issue by jucktnich** [corona-warn-app/cwa-wishlist#522]
## Current Implementation

Current you can't take the vaccination certificate and transfer it from device to device.

## Suggested Enhancement

Allow the transfer from device to device. To accomplish that, I thought about this concept:
1. The new device generates a private and a public key.
2. The public key is transferred to the old device via a qr-code.
3. The old device encrypts all vaccination certificate data with the public key.
4. The old device blocks its vaccination certificate to prevent abuse.
5. The old device takes the encrypted data and creates a qr code.
6. The new device scans the qr code, decrypts it and than stores it.

The encryption is needed to prevent multiple copies of the certificate.

## Expected Benefits

Vaccinated people don't have to request a new code.

----
Internal Tracking-ID: [EXPOSUREAPP-7300](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7300)

**Comment by thomasaugsten** [comment]
In which information based the assumption that you cannot scan the vaccination certificate on multiple devices?

**Comment by jucktnich** [comment]
https://www.bundesgesundheitsministerium.de/coronavirus/faq-covid-19-impfung/faq-digitaler-impfnachweis.html

Under "Wie soll Missbrauch verhindert werden?"

**Comment by heinezen** [comment]
Relevent parts in https://www.bundesgesundheitsministerium.de/coronavirus/faq-covid-19-impfung/faq-digitaler-impfnachweis.html:

> Die App speichert die Impfbescheinigung lokal auf dem Smartphone. Dieser 2D-Barcode ist nur einmalig einlesbar und die Impfbescheinigung ist anschließend an das einlesende Smartphone gebunden.

> Der digitale Impfnachweis ist kryptographisch vor Veränderungen geschützt und gleichzeitig an ein Smartphone gebunden, sodass auch ein möglichst umfassender Schutz vor Vervielfältigung besteht.

**Comment by heinezen** [comment]
@jucktnich 

Thanks for the proposal. I have created a ticket for this request [EXPOSUREAPP-7300](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7300). The development team will take a look.

----
Corona-Warn-App Open Source Team

**Comment by thomasaugsten** [comment]
We will recheck this information and correct the FAQ based on the latest information

**Comment by thomasaugsten** [comment]
The FAQ is now updated

**Comment by jucktnich** [comment]
I'll close it therefore
