### ISSUE TITLE
Stop error analysis after sending report

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#523]
## Current Implementation
The error analysis continues after it was send and thus you can send a report from one "session" multiple times, see this video:

https://user-images.githubusercontent.com/67682506/118354072-899ea080-b569-11eb-96e5-878dc99f6daa.mp4

This is quite confusing since for a user it seems like that the sending did not work because there is no information at all that the report was sent. 

## Suggested Enhancement
Stop the error report after sending it and point out to the ID-history where he/she can find the relevant ID.

## Expected Benefits
Less users sending error reports multiple times, less users confused, in general a better usability.

----
Internal Tracking-ID: [EXPOSUREAPP-7299](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7299)
Internal Tracking-ID: [EXPOSUREAPP-7374](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7374) bug

**Comment by dsarkar** [comment]
@Ein-Tim ok, and more importantly where is the error report ID

**Comment by achisto** [comment]
> @Ein-Tim ok, and more importantly where is the error report ID? Did find the ID?

The is is shown after a report has been sent. ![image](https://user-images.githubusercontent.com/20704439/118356561-2c5d1c00-b576-11eb-8122-ac79f362b6f0.png) ![image](https://user-images.githubusercontent.com/20704439/118356567-2f580c80-b576-11eb-8582-a1234c4ef808.jpeg)

**Comment by Ein-Tim** [comment]
@achisto 

I know, but this is really hard to find. Users with small screen phone have to scroll down to find the ID. In combination with the problem I mentioned above (that the analysis doesn't stop after sending it) a user could think that the error report was not send.

**Comment by heinezen** [comment]
@Ein-Tim 

Thanks, we have added this to the feature request list. Tracking ID is [EXPOSUREAPP-7299](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7299). We'll notiffy you if there are any news.

----
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Internal Tracking-ID: EXPOSUREAPP-7374 bug

**Comment by Ein-Tim** [comment]
@dsarkar If this is considered as a bug internally please relabel here (: 

Thank you!

**Comment by Ein-Tim** [comment]
Please disregard my deleted comment 😄

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
