### ISSUE TITLE
[OVERVIEW] Error report

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-wishlist#524]
https://github.com/corona-warn-app/cwa-wishlist/issues/523 | Stop Error Analysis after sending it
https://github.com/corona-warn-app/cwa-wishlist/issues/523 | ID of error report hard to find
https://github.com/corona-warn-app/cwa-wishlist/issues/523 | No confirmation and no ID shown after successful error report submission

https://github.com/corona-warn-app/cwa-documentation/issues/612 | Cannot stop logging and view error report before sending

**Comment by Ein-Tim** [comment]
Here to take this over and extend to the normal overview scope if you want me to. (:

**Comment by Ein-Tim** [comment]
@dsarkar Please see #525

**Comment by Ein-Tim** [comment]
I think we could close this in favor of #525, or?
