### ISSUE TITLE
Rapid test result with longer validity (8 days) 

### ISSUE THREAD

**Issue by Th-St** [corona-warn-app/cwa-wishlist#526]
I understood that the display of rapid test results should help showing the test results at border crossing.

For commuters to Austria the rapid test results are valid for 7 days according to §6a of the Austrian "COVID-19-Einreiseverordnung".
If CWA shows them only for 48 h it doesn't help the people who are crossing borders on daily basis.

Would you please extent it to be valid for 8 days?

----
Internal Tracking-ID: [EXPOSUREAPP-7982](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7982)

**Comment by MikeMcC399** [comment]
https://www.coronawarn.app/en/faq/#rat_how_long_valid does say:

"After 48 hours, your rapid test result will automatically be removed. You can then take another rapid test and register it in the app."

Perhaps the enhancement request could be to make removal of the record of a Rapid Antigen Test optional instead of forced automatic? That would be more flexible for special cases like commuters crossing the border between Germany and Austria.

**Comment by jucktnich** [comment]
There should be a warning, that this rapid test isn't valid (in Germany), the border control of Austria knows, that they can ignore the warning. Else there will be confusion, people thinking it's valid in Germany, ... A info text sadly won't work, since people won't read it.

**Comment by ndegendogo** [comment]
I like [this suggestion](https://github.com/corona-warn-app/cwa-wishlist/issues/526#issuecomment-841835304) to add a configurable option.
It allows users to adapt cwa better to their specific needs and use cases.

**Comment by Ein-Tim** [comment]
The situation here has changed since you can request a digital COVID test certificate for your tests now (if the testing site supports this) and this certificate will stay in your app even after more than 48 hours. You have to delete it manually.

**Comment by dsarkar** [comment]
@Th-St see comment above from @Ein-Tim. Does this solve your issue and we can consider this as being solved? Thanks. Best, DS 

---
Corona-Warn-App Open Source Team

**Comment by Th-St** [comment]
Thank you, CWA team, for the App and the open development allowing the users to get involved!

**Comment by dsarkar** [comment]
@Th-St Thanks for the feedback!

**Comment by Ein-Tim** [comment]
A Twitter user told me that there are still many testing sites out there which don't support the creation of DCCs and thus he says he still has this problem. 
Maybe this should be reevaluated @dsarkar?

Looking at https://map.schnelltestportal.de I can confirm what the user says, there are many testing sites which don't support DCCs.

**Comment by dsarkar** [comment]
@Th-St @Ein-Tim The use case is Austria? Are there more use cases?

**Comment by Ein-Tim** [comment]
@dsarkar 

Quote: "An der Arbeit darf ein Test länger als 48h alt sein, beim Grenzpendeln auch. Das würde mir spontan einfallen"

**Comment by dsarkar** [comment]
@Ein-Tim OK. We will forward this to TSI: This is something the test providers have to implement. Thanks.

**Comment by Ein-Tim** [comment]
@dsarkar 

I don't understand, why do the test centers have to implement that rapid antigen test results are shown for more than 48h in the Corona-Warn-App? Wouldn't it be possible to just show the test result from a rapid antigen without limit? Similar to what's already implemented for PCR test.

**Comment by dsarkar** [comment]
@Ein-Tim Actually, we have to distinguish:
1. The CWA count-down. This is something visual. 
2. The technical validity of the EU DCC certificate. If Austria e.g. check a user's DCC with a validation app, it would be convenient that the technical validity of a test EU DCC is considerably longer than two days. The rules should be applied on basis when the test was done, and every country can establish their own ones. If Austria accepts test EU DCC older than two days, they also have to be technical valid at that point.

**Comment by dsarkar** [comment]
Re-opened. Ticket assigned internally to TSI.
