### ISSUE TITLE
Allow to scan LucaApp QR-Codes for event check-ins

### ISSUE THREAD

**Issue by Diapolo** [corona-warn-app/cwa-wishlist#530]
## Current Implementation
Currently the app allows an event check-in via CWA-QR-Codes.

## Suggested Enhancement
I dislike and don't ever want to use (or be "forced" to use) that privacy nightmare LucaApp for beeing able to visit a bar, restaurant and so on. If CWA was able to process LucaApp QR-Codes and treat them like a CWA-check-in that would solve all my worries ;).

## Expected Benefits
One central (and official) app, which I like, which is privacy-friendly and allows for save check-ins, and that is CWA!

---
Internal Tracking ID: [EXPOSUREBACK-1209](https://jira-ibs.wbs.net.sap/browse/EXPOSUREBACK-1209)

**Comment by Ein-Tim** [comment]
Related issue: https://github.com/corona-warn-app/cwa-documentation/issues/590

**Comment by dsarkar** [comment]
@Diapolo Thanks. Internal Tracking ID: [EXPOSUREBACK-1209](https://jira-ibs.wbs.net.sap/browse/EXPOSUREBACK-1209)



---
Corona-Warn-App Open Source Team

**Comment by kroerig** [comment]
But checking in with CWA by scanning a luca QR code won't submit any required contact information. So you have to register manually (in the worst case with the luca contact form).

**Comment by Ein-Tim** [comment]
Update: 

https://github.com/corona-warn-app/cwa-server/pull/1362#issuecomment-882052293 says:

> The feature has a good progress. We hope we can finish the feature soon.

**Comment by maybeec** [comment]
Any news meanwhile? I strongly believe that this is one of the most critical features to get cwa a little more accepted by people. Currently, restaurants and bars mainly focusing on Luca as it was there earlier with more society critical features like for example the QR codes. 
For people there is no reason to use cwa at the moment as there are no cwa compatible QR codes outside.

 (don't get me wrong, I am just phrasing what is the common view outside without the in depth knowledge of all the technical advantages of cwa over Luca! BTW remember VHS ;))

Just a side mark as the best solution will not make acceptance automatically:
Will there be any ability to register old Luca codes as well for being compatible with cwa with a kind of legacy bridge? Why I am asking is again focusing on practicality and ease of use. Most bars printed their QR code meanwhile on the menu and they don't want to replace it or even have another one. Also one feedback was, that setting up the QR code seem to be too complicated for most of the people without having any technical understanding.
So you have to compete with easily asking the customer 'if you don't have Luca, please fill this paper form', and letting the waiter fill in your data eventually into his mobile.

**Comment by kroerig** [comment]
With the latest CoronaSchVO in NRW there is no need anymore to register at locations. Except local authorities require it.
https://www.ldi.nrw.de/mainmenu_Datenschutz/submenu_Datenschutzrecht/Inhalt/Corona---Kundenkontaktdaten/Inhalt/Kundenkontaktdaten/Kundenkontaktdaten.html

**Comment by maybeec** [comment]
Wait a few weeks. Autumn will bring contact tracing back to stage.

**Comment by MikeMcC399** [comment]
@maybeec 
CWA 2.9, just released, includes the new Warn-on-behalf of functionality. See https://www.coronawarn.app/en/blog/2021-09-08-cwa-version-2-9/

**Comment by maybeec** [comment]
Thanks @MikeMcC399 ,but this functionality would require event organizers to have a cwa qr code which actually is not the case. So this addresses not the problem explained .

**Comment by MikeMcC399** [comment]
@maybeec 
You are right of course. The "Warn-on-behalf" functionality does not resolve the LucaApp issue. It only provides functionality linked to the needs of the Gesundheitsamt.

**Comment by dsarkar** [comment]
@Diapolo @maybeec @MikeMcC399 @kroerig FYI https://www.coronawarn.app/de/faq/#check_in_luca

**Comment by Ein-Tim** [comment]
@Diapolo Would you like to close this issue?

**Comment by Diapolo** [comment]
@Ein-Tim Sure :-), thanks for helping implementing this!

**Comment by dsarkar** [comment]
Dear Community, thanks for participating in this project.

Best wishes, DS

---
Corona-Warn-App Open Source Team
