### ISSUE TITLE
Publish installation numbers from App Store Connect & Google Play Console

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#540]
## Current Implementation
The only numbers reg. the installations (which are published) are the downloads (and maybe the results from the data donation - but they were only mentioned in [this lecture](https://youtu.be/AE9ljDGNAus?t=1931)). 
However, Downloads can only go up and don't tell us on how many times the CWA is currently installed.

## Suggested Enhancement
Publish the installations shown in the Google Play Console and in Apple App Store Connect. 

## Expected Benefits
We have exact numbers that tell us on how many devices the CWA is installed.

## Additional information

1. If there are concerns about the numbers shown there please make these concerns public. 
This would be helpful for us to understand why you don't want to publish these numbers. 
2. If you publish these number this would bring us closer to the KPI - the active users. 
For sure not every installation has activated the risk detection, some are maybe only using the feature to get their test results fast and digital, but it would be closer to the active users than the downloads.

---
Internal Tracking ID: [EXPOSUREAPP-7613](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7613)

**Comment by dsarkar** [comment]
@Ein-Tim Thanks. Internal Tracking ID: [EXPOSUREAPP-7613](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7613)


---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
FYI: There is a Freedom of Information Request on this now: https://fragdenstaat.de/a/196169 (not from me). However, it asks for the data from the backend server, not from App Store Connect or/and the Google Play Console.

**Comment by Ein-Tim** [comment]
There meanwhile is the [Science Blog 5](https://www.coronawarn.app/de/science/2022-03-03-science-blog-5/) which analyzes the installation numbers of the CWA. I therefore consider this issue as resolved.
