### ISSUE TITLE
Align rapid test proof feature under Android to iOS

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#543]
## Current Implementation
The implementation fo the rapid test proof feature differs between iOS and Android.

iOS only shows the date and time of the issue, Android also shows a countdown since when the test result is available. 

| iOS | Android |
|---|---|
|<img src="https://www.coronawarn.app/assets/screenshots/2-4/en/ios/rat_7.png" width="300"> | <img src="https://www.coronawarn.app/assets/screenshots/2-4/en/android/rat_7.png" width="300"> |

## Suggested Enhancement
Align Android to iOS.
I would suggest to align iOS to Android because of the following two design flaws of the Android implementation:
- https://github.com/corona-warn-app/cwa-app-android/issues/3682
- https://github.com/corona-warn-app/cwa-app-android/issues/3559

## Expected Benefits
People who check for a valid rapid test result are not confused why "the one" CWA looks like this and "the other" CWA looks like this.

----
Internal Tracking-ID: [EXPOSUREAPP-7986](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7986)

**Comment by heinezen** [comment]
@Ein-Tim 

Thank you, but am I the only one that doesn't see the images in your post?

**Comment by Ein-Tim** [comment]
@heinezen Fixed this, the screenshots on coronawarn.app have been renamed.

**Comment by Ein-Tim** [comment]
I would suggest to align the RAT proof feature under Android to iOS, see https://github.com/corona-warn-app/cwa-app-android/issues/3557

Edit: One more reason: https://github.com/corona-warn-app/cwa-app-android/issues/3559

**Comment by Ein-Tim** [comment]
This was implemented with version 2.21 / 2.22.
