### ISSUE TITLE
Detect lower saxony QR codes and warn user

### ISSUE THREAD

**Issue by Manawyrm** [corona-warn-app/cwa-wishlist#545]
## Current Implementation
When erroneously scanning a QR code listed on the paperwork of the vaccination centers in lower saxony (for use as a vaccination certificate) the user will get a confusing "VC_PREFIX_INVALID" message.

## Suggested Enhancement
In lower saxony, regular QR codes with 8 character A-Z, 0-9 are present on the letters from the vaccination centers.
The regex `^[0-9A-Z]{8}$` matches against these NDS QR codes and could maybe used to detect them and warn the user?  

I've seen some confusion in family members, because they tried to register with that code.  

My proposal for such an error message would be something like:  
> Der gescannte QR-Code gehört zu Ihrer Anmeldung beim Impfzentrum und ist kein gültiges Impfzertifikat. Sie erhalten Ihr Impfzertifikat per Post oder von einer Apotheke.

## Expected Benefits
Users wouldn't be confused by confusing errors and the clear error message would tell them what they need to do.

**Comment by Manawyrm** [comment]
For completeness, here's a screenshot: 
<img src="https://screenshot.tbspace.de/sfhdergcutb.png" width="200" />

And here are 2 (fake) NDS QR codes:
`3DZJOU8N`:  
![](https://screenshot.tbspace.de/vixdnslaycm.png)

`ABCD1234`:
![](https://screenshot.tbspace.de/lbwdmfghujk.png)

**Comment by MikeMcC399** [comment]
- This is related to a similar request https://github.com/corona-warn-app/cwa-wishlist/issues/343 about the response to invalid codes.
- There is also a thread on https://github.com/corona-warn-app/cwa-website/issues/1343 regarding a proposal for an FAQ article as a response to the error message "VC_PREFIX_INVALID".
- In addition there is a discussion in https://github.com/corona-warn-app/cwa-app-android/issues/3394 about the error message in Android.

**Comment by Ein-Tim** [comment]
The same goes for the QR-Codes on the paper work of the Bavarian vaccination centers (not sure about the regex though). 

In General I think the error message should be improved (maybe with a link to the FAQ entry which explains this - one will hopefully be published soon https://github.com/corona-warn-app/cwa-website/issues/1343)

**Comment by Ein-Tim** [comment]
We will get a hot fix for improved error handling reg. this: https://github.com/corona-warn-app/cwa-app-android/pull/3400

The error message then will include a link to the FAQs!

**Comment by Manawyrm** [comment]
Here's a report about the same problem in Munich with a dump of the data in Munich. It seems to be a JSON-blob with an ASCII prefix? 

https://twitter.com/HillierHillier/status/1402660888843325445

**Comment by Ein-Tim** [comment]
@Manawyrm Yeah, there's nothing we can do about this better than the hot fix release 2.3.3 which will add a link to a FAQ entry.

**Comment by MikeMcC399** [comment]
Note the new FAQ entry 
- https://www.coronawarn.app/en/faq/#vac_cert_invalid (EN) or 
- https://www.coronawarn.app/de/faq/#vac_cert_invalid (DE).

**Comment by heinezen** [comment]
We have improved the error message in CWA version 2.3.3, so scanning the wrong QR code is less confusing. With the automatic distribution of vaccine certificates with every vaccination this will hopefully be even lesser of a problem.

----
Corona-Warn-App Open Source Team
