### ISSUE TITLE
App language independence from system language setting

### ISSUE THREAD

**Issue by MimiComm** [corona-warn-app/cwa-wishlist#546]
Hi.

I know there is a very similar request in #22, but the title originally referred to an entirely different issue and is (by now) misleading.
"Change language prior to giving consent to legal information"

I have my phone's system language set to English for various reasons. So far, every time I needed the app to e. g. send my employer a screenshot of a red status, I had to first set my phone to German before being able to do that. It wasn't a huge issue, but a bit of a hassle.

Now that the digital vaccination passport is about to launch, this issue becomes very pressing. I will need to be able to use the app on the go, possibly many times a day. Therefore the ability to choose an app language independently from the system setting is crucial.

Many locations might accept the digital passport presented in English, but surely some will (rightly so) insist on German. Not to mention other, less widely spoken languages many people have set their phones to.

I am asking you to consider making this a high priority, seeing as the digital passport will be an important part of daily life. 

Thank you for reading!

**Comment by jucktnich** [comment]
Please move this to the android repo since on iOS you can do this via the system settings (every app independently) and it's probably against apples rules to integrate it.

**Comment by MimiComm** [comment]
If there is a way to entirely delete this from here, please do let me know. Thank you.
