### ISSUE TITLE
Auto cleanup for users and locations

### ISSUE THREAD

**Issue by FlightMS** [corona-warn-app/cwa-wishlist#548]
## Feature description

Users and locations should be removed automatically when they are unsed for more than 14 days. The user should be able to activate or deactivate this feature.

## Problem and motivation

With time is going on, more and more entrys are in the users and contacts list. So it will be more and more confusing in the list and to get a better overview (and need less more scrolling) I delete old entries which I don't need anymore. At the moment I do that the manual way, but I like to have a feature which do this task automatically.

## Is this something you're interested in working on

Internal Tracking ID: [EXPOSUREAPP-3034](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3034)
Internal Tracking ID: [EXPOSUREAPP-6158](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6158)

**Comment by MikeMcC399** [comment]
@FlightMS 
This has already been requested in https://github.com/corona-warn-app/cwa-wishlist/issues/405.

**Comment by FlightMS** [comment]
Close - as this will be already discussed in #405
