### ISSUE TITLE
Schnelltestergebnisse länger in CWA sichtbar lassen / Keep results of fast tests longer than 48 hours

### ISSUE THREAD

**Issue by ThomsonK70** [corona-warn-app/cwa-wishlist#549]
Hi,

in vielen Bereichen reicht es, wenn man einen Schnelltest hat, der nicht älter als 72 Stunden ist. So geschehen im letzten Urlaub an der Ostsee. Die CWA hält dieses Ergebnis aber ur für 48 Stunden. Kann man nicht einrichten, dass zukünftig die Ergebnisse für 72 Stunden oder, da mit Datum versehen, unendlich angezeigt werden, bis ein neuer Test erfasst wurde? Die Doctobox App fügt einfach einen neuen Eintrag zur Liste hinzu, ohne abgelaufene Ergebnisse zu löschen. Wäre auch eine Variante. Danke!

**Comment by Ein-Tim** [comment]
Hey @ThomsonK70 

We have a very similar issue already, #526.

Please take a look at it and decide wether it would be possible to close your issue in favor of #526. 

Thank you! Stay safe and enjoy Friday!

**Comment by jucktnich** [comment]
Maybe change the Color after 24h to grey or yellow

**Comment by ThomsonK70** [comment]
> Hey @ThomsonK70
> 
> We have a very similar issue already, #526.
> 
> Please take a look at it and decide wether it would be possible to close your issue in favor of #526.
> 
> Thank you! Stay safe and enjoy Friday!

You are right. This is very similar. So, it is absolutely okay to close mine. I did not see the other one before writing mine.
