### ISSUE TITLE
[Vaccination tile] Add the name of the person to the vaccination tile on the homescreen

### ISSUE THREAD

**Issue by jucktnich** [corona-warn-app/cwa-wishlist#550]
## Current Implementation

Currently there's only the info "digital vaccination proof" "sars cov 2 vaccination".
## Suggested Enhancement

Add the name of the person to the vaccination tile on the homescreen

## Expected Benefits

People get lazy so they'll probably start not caring about the whole page only wanna see the tile. Some also might think, you can only add a vaccination certificate if you're the exact person. So when you put the name on the tile, some cheaters will be catched.

**Comment by Ein-Tim** [comment]
The vaccination tile will be removed from the home screen and moved to the new "Certificates" tab in version 2.4.
There the name of the owner will be shown:

<img src="https://user-images.githubusercontent.com/1157991/121684428-f6e91700-cabe-11eb-86eb-15c856b75210.png" width="300">

(Source: https://github.com/corona-warn-app/cwa-app-ios/pull/2903)

**Comment by jucktnich** [comment]
Ah yeah ok, thought the tile will still be there, even though the rest moves. Thx for clarification.
