### ISSUE TITLE
Vaccination certificate (DGC): show transliterated version of foreign names

### ISSUE THREAD

**Issue by stgeo** [corona-warn-app/cwa-wishlist#551]
## Current Implementation
The vaccination certificate shown in the app (Android version 2.3.4, I have not checked iOS but I assume it's the same) shows the vaccinated person's names provided in fields "gn" and "fn" in the JSON. For foreign names/certificates that name may be in a different alphabet, e.g., Cyrillic or Greek. The transliterated names from fields "gnt" and "fnt" are not shown at all.

## Suggested Enhancement
Show the transliterated names, probably in addition to the original names.

## Expected Benefits
If somebody wishes to verify the identity of the vaccinated person using the data displayed in the CWA and comparing to their personal ID, it would be easier to do so using the transliterated names. The verifying person may not be familiar enough with foreign alphabets to do a quick comparison by eye.

This might not be an issue if the QR code is actually scanned with a verifier app but I guess that also depends on the implementation of the latter.

----
Internal Tracking-ID: [EXPOSUREAPP-7977](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7977)
Internal Tracking ID: [EXPOSUREAPP-8686](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8686) Android
Internal Tracking ID: [EXPOSUREAPP-8186](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8186) iOS

**Comment by thomasaugsten** [comment]
The verification happens in the CovPass Check app. The verifier will see the name in this app and have to check this with the ID please open a ticket for this app or contact the hotline.
https://github.com/Digitaler-Impfnachweis/documentation/issues
Hotline numbers:
https://digitaler-impfnachweis-app.de/faq/
Email:
 impfnachweis@rki.de

**Comment by stgeo** [comment]
Thanks, @thomasaugsten . Unfortunately, the current version of the CovPass Check app doesn't even recognize the Bulgarian certificate (even the one generated by CWA), probably because they haven't adopted the looser checking required. This probably should also be posted as an issue there or might get fixed in an upcoming update.

Regardless, from my side the request for the enhancement stays - if the transliterated names are available in the JSON, it would be good to have them in a human-readable form in the CWA.

**Comment by thomasaugsten** [comment]
We aware of this and planning in future version to show also the ICAO name

**Comment by vaubaehn** [comment]
Although I'm in general supporting the opinion that a verifier app should take care of this, recent reports (e. g. from my wife) point out, that practically in the wild verifier apps are not used often. Instead, staff (of shops etc) often only wants to see a certificate from the app, and only check for "face validity".
ICAO names to be displayed could be helpful in these situations.
However, I'm also voting for a clearly visible text, indicating
"Zertifikat muss mit Verifier-App geprüft und mit einem Personaldokument abgeglichen werden!" as a pointer towards gate keepers...

**Comment by MikeMcC399** [comment]
@vaubaehn 
I haven't flown anywhere since before the pandemic, but I would assume that ICAO name display could come into play for international travel.

**Comment by vaubaehn** [comment]
@MikeMcC399 
> I haven't flown anywhere since before the pandemic, but I would assume that ICAO name display could come into play for international travel.

Yes, and I was even able to take a screenshot of a report/review in Google Play Store, where someone reported that border control staff obviously controlled DCCs from app display without verifier-app?! So, in these cases it would even be more of importance.
I wanted to add this to the related "please provide a language selector for the DCC details screen" issues, but I'm lost and can't find them neither in "wishlist" nor in "documentation" repo... Do you probably know where to find them? Or are they seperate in Android and iOS repos?

**Comment by MikeMcC399** [comment]
@vaubaehn 
I don't recall seeing what you are referring to and I couldn't find anything similar.

You can search across repositories with a search string like:
`org:corona-warn-app is:issue is:open DCC in:title`

You might want to open your own wishlist item if you can't find it.

**Comment by vaubaehn** [comment]
@MikeMcC399 
Thank you, your suggestion helped me.
I was now able to find some issues which are all closed already, and which did not directly refer to DCC (some did in comments).
Probably it would be better to open a new wishlist issue for this, but before I'm going to interview my wife more about her experiences (handling/interaction DCC/gate kepper) to have a better precision for a requested enhancement.

**Comment by Ein-Tim** [comment]
FYI: https://github.com/corona-warn-app/cwa-app-ios/pull/3279

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-app-android/pull/3868

**Comment by Ein-Tim** [comment]
Hey @stgeo 

Version 2.8 of the Corona-Warn-App displays names in certificates in standardized characters. 
More Information can be found in this blog post: [Corona-Warn-App version 2.8 displays names in certificates in standardized characters](https://www.coronawarn.app/en/blog/2021-08-25-cwa-version-2-8/).

Do you consider this as implemented? If yes, please close this issue. Thank you!

**Comment by Ein-Tim** [comment]
Could you close this issue @dsarkar?

**Comment by stgeo** [comment]
> Hey @stgeo
> 
> Version 2.8 of the Corona-Warn-App displays names in certificates in standardized characters.
> More Information can be found in this blog post: [Corona-Warn-App version 2.8 displays names in certificates in standardized characters](https://www.coronawarn.app/en/blog/2021-08-25-cwa-version-2-8/).
> 
> Do you consider this as implemented? If yes, please close this issue. Thank you!

Yes, sorry I've been busy. Looks good now, thanks. Closing the issue.
