### ISSUE TITLE
Birthday party 🎂

### ISSUE THREAD

**Issue by fynngodau** [corona-warn-app/cwa-wishlist#555]
Dear Corona-Warn-App developers, maintainers, community managers and community members,

today, the official Corona-Warn-App release date lies exactly one year in the past. We would like to take this opportunity to congratulate on the successful project.

[Recent reports](https://www.heise.de/news/RKI-Schaetzung-Warn-App-hat-mehr-als-100-000-Infektionsketten-unterbrochen-6070747.html) indicate that the application indeed fulfills its purpose of warning unknown users, and the time for [scientific evaluation](https://www.coronawarn.app/de/science/) has arrived. Therefore, this one-year anniversary is certainly a reason to celebrate.

During the year, the application that used to operate primarily in the background has started a transformation into an anti-pandemic supertool: with a contact journal, check-in feature, the integration of rapid tests, and finally, the digital Proof of Vaccination, there are many reasons to install this application.

I enjoy seeing the continued efforts to incorporate community feedback into the project; and I truly believe that the world were to be a better place if _every_ software project made at least as much transparency efforts as this one.

It is truly relieving to be able to squash simple bugs oneself by providing fixes directly to the developers. In this sense, I am extraordinarily happy to have be a part of this project.

Cheers, best wishes and enjoy your stay in this birthday party issue

Fynn

**Comment by vaubaehn** [comment]
## Dear Corona-Warn-App,

you have been my loyal companion for a year now. On the first day we had butterflies in our stomach, but soon the bugs were a little dominant. But never mind, even if we had our issues, you have developed well in the meantime! And I'm looking forward to another year with you, even if it would be nicer if the circumstances were such that we didn't have to depend on each other ...
Please also send my greetings to your developers and all other people around you, and convey my gratitude to them! All the best for your future!

All the best and ...


## HAPPY BIRTHDAY!!!

<img src="https://user-images.githubusercontent.com/68376758/122256835-b418ac00-cecf-11eb-9e33-fe6922ab4ea3.png" width="200">

**Comment by Ein-Tim** [comment]
Dear CWA project team! I want to say thank you for all your great and unbelievable work you’ve done in the last 365 days for all German citizens! With the help of the Corona-Warn-App many infection chains have been broken and surely many citizens didn’t catch COVID-19 because of the Corona-Warn-App!
The CWA was developed in such an unbelievable fast time, and everything was and is Open-Source! We’re not only helping to fight Corona, together, but we are also setting new standards for IT projects which are tax founded!

Thank you for the new features you deliver with every update! Thank you for the contact journal, thank you for the statistics, thank you for the event-registration and for sure also for the vaccination certificate in the app!

And an even huger thank you for letting outside contributors helping to make the app even better and contributing to it! 

Happy birthday @Corona-Warn-App and I’m really joyful that I can be a part of this unbelievable nice community, consisting out of the developers, the community managers and other people like me! ❤️🎉

Cheers
Tim

**Comment by Bubu** [comment]
Happy birthday Corona-Warn-App (team)! :tada: 

![image](https://user-images.githubusercontent.com/105185/122269658-c26dc480-cedd-11eb-90ac-9ca61e04df14.png)

**Comment by DanAmt** [comment]
🎂🍀❤️Happy Birthday CWA and team !! ☕️💫🎁

**Comment by Ein-Tim** [comment]
We're approved, yeahhhy 🎉😉

**Comment by thomasaugsten** [comment]
Thanks also back to you guys. 
You helped a lot of people to use the app in giving support or creating a great fork.
And of course you helped us to improve the app and make it such a great success.

**Comment by jucktnich** [comment]
Thanks a lot CWA team, you were there everytime someone needed help, even though you hadn't Office time. You did a great job in community management, so we everytime knew what was goin on. You've did a great job breaking infection chains, probably so many like all public health departments 👏. The development pace was just 🚀. This project just showed many Germans how 🤖 can help 😀, and this all Open Source just amazing! Happy Birthday 🥳 @corona-warn-app and thanks a lot for the amazing work between the developers, community managers and the community!

**Comment by jucktnich** [comment]
Hopefully there won't be a second birthday. I'm already looking with a laughing and a crying eye at the moment when the CWA(-development) will be discontinued. But maybe the Bundesregierung just decides, to use this amazing team on other important "Digitalisierungs"tasks.

**Comment by ndegendogo** [comment]
Happy birthday! cwa is now in the wild for one year, and you made it happen! Thanks a lot for all your hard work, for your commitment to the project, for the great features you have developed, for the nice community you have created.
🎉🎉🎉🎉🎉

**Comment by juliankpf** [comment]
Happy Birthday, Corona-Warn-App!! 🎉🎉🎉🎉🎉

**Comment by mia0x1** [comment]
Happy Birthday CWA, I hope we won't need you in the near future anymore. 
But I am really looking forward for upcoming open-source projects with such a great community. Cheers 🎉🎉🎉🎉🎉

**Comment by fynngodau** [comment]
@jucktnich Definetly gotta have an after-party then, right?😅

**Comment by vaubaehn** [comment]
> Definetly gotta have an after-party then, right?😅

On the other hand: if you compare the costs of FFP2-masks for one year and citizen tests for six months for the tax payer with the costs of one year CWA development and maintaing costs, I really don't see any reason for discontinuation 😉

**Comment by jucktnich** [comment]
@fynngodau but then in person 😉

**Comment by hschepp1965** [comment]
I'm just the PR man, but still: To the entire community, my heartfelt thanks for supporting the CWA so fantastically and continuing to do so. Without your permanent input, your passion, your support, your help, the CWA would not be where it is today!

**Comment by heinezen** [comment]
On behalf of the Open Source Team on Github and in the stores: Thank you for being so cooperative and supporting as a community!

----
Corona-Warn-App Open Source Team

**Comment by svengabr** [comment]
🎉🎉🎉🎉🎉

Happy birthday to the CWA community!
It was a great year working together with all of you.

❤️

**Comment by fynngodau** [comment]
Birthday party is now over and Silvester party is live over at #740!

**Comment by Ein-Tim** [comment]
Birthday 2.0, now: https://github.com/corona-warn-app/cwa-wishlist/issues/833
