### ISSUE TITLE
which test centers cooperate with the app?

### ISSUE THREAD

**Issue by nschloe** [corona-warn-app/cwa-wishlist#559]
[Since early May 2021, one can register rapid tests via CWA.](https://www.bundesregierung.de/breg-de/suche/corona-warn-app-schnelltests-1902350) This doesn't work in all test centers though. I'd love to see a list of test centers which support this feature.

**Comment by MikeMcC399** [comment]
@nschloe 

Your request looks very similar to https://github.com/corona-warn-app/cwa-wishlist/issues/498 "Add an overview for rapid test partners".

Note that there is also an FAQ article on this topic https://www.coronawarn.app/en/faq/#rat_partner (or https://www.coronawarn.app/de/faq/#rat_partner for the German language version), which links to https://www.coronawarn.app/en/faq/#where_can_i_get_tested.

The FAQs do not exactly answer your request, however that is the best information available at this time.

**Comment by nschloe** [comment]
Definitely a dup of #498. Thanks for the quick response!
