### ISSUE TITLE
Scanning french vaccination certificate QR Codes (tous anti-covid app)

### ISSUE THREAD

**Issue by devsnd** [corona-warn-app/cwa-wishlist#560]
## Current Implementation

I have been vaccinated in france and have a french certificate for the vaccination. When I try to scan the corresponding QR Code, I receive an error message `VC_PREFIX_INVALID`. The second Barcode Code that is provided on the certificate cannot be scanned at all (it's not a QR code and it's labeled as 2D-DOC)

## Suggested Enhancement

It would be great if I could scan and store my french vaccination certificate in the Corona warn app, so I can use the app to certify my vaccination in germany using the app.

## Expected Benefits

It does not matter where someone was vaccinated, the virus does not stop at any country border. IMHO the app should enable as many vaccinated people as possible (within the EU) to be used to certify their vaccination digitally.

**Comment by MikeMcC399** [comment]
@devsnd 
Did your French vaccination certificate look anything like the example shown in https://www.coronawarn.app/en/faq/#vac_cert_invalid

![EU Digital Covid Vaccination Certificate Demo](https://user-images.githubusercontent.com/66998419/121585483-f014c280-ca32-11eb-83b1-38ef4a74719b.jpg)

There is also a Belgian example shown in https://ec.europa.eu/health/sites/default/files/ehealth/docs/covid-certificate_paper_guidelines_en.pdf (Certificat numérique européen COVID).

When was your French certificate issued? In Germany the EU compatible certificates started being issued on June 14, 2021 (apart from a few earlier certificates produced as part of the pilot project). So in Germany any QR code which was issued before June 14, 2021 is very likely to be incompatible with the scanning built into Corona-Warn-App and CovPass-App. I don't know the dates for France though.

**Comment by MikeMcC399** [comment]
Note also from https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/safe-covid-19-vaccines-europeans/eu-digital-covid-certificate_en

"The certificate will be introduced in EU Member States. Countries can start issuing and using it already and it will become available in all EU Member States as of 1 July 2021"

and further down that page it shows France "Technically ready to connect to the EUDCC gateway" however it says "NO" against "Effectively connected, issuing and/or verifying at least one EUDCC (vaccination, recovery, negative test)".

There is a [map of Europe on the EU site](https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/safe-covid-19-vaccines-europeans/eu-digital-covid-certificate_en#what-data-does-the-certificate-include-is-the-data-safe) which shows the status of each country.

**Comment by thomasaugsten** [comment]
The Bar-code you scanned is not a valid EU certificate. France is planning to start with the EU certificates at 22.06.21

**Comment by devsnd** [comment]
Hey Mike,

Thanks for your detailed response!

My certificate does not look like the one you have posted: I did receive my second shot at the end of may, so therefore I probably still have the french national vaccine Certificate, instead of the EU cert, which is unfortunate.

Does that mean that I have to get a EU certificate from the french government instead? And if so, it would be great if the app could point the user in the right direction.

What would be the impediments to support the french style QR codes in the current app? I'd be willing to work on a PR to get this implemented if in any way possible. But I surely would need some pointers how exactly to get there.

**Comment by MikeMcC399** [comment]
Hi Tom @devsnd 

According to https://www.schengenvisainfo.com/news/frances-covid-19-vaccine-passport-to-be-updated-on-june-22/ your certificate in TousAntiCovid should get updated tomorrow. I would wait and see what happens first.

**Comment by MissinstaPam** [comment]
Hi I have the same issue got my 2nd vaccination 21/6 & received QR code.  Each time I scan the code it tells me that its not authentic.  I have tried everything to resolve....any suggestions that would help me get this onto my tousanticovid app

**Comment by MikeMcC399** [comment]
@MissinstaPam 
>I have the same issue got my 2nd vaccination 21/6 & received QR code. Each time I scan the code it tells me that its not authentic. I have tried everything to resolve....any suggestions that would help me get this onto my tousanticovid app

Which country issued your QR code? France or Germany?

If you are asking about putting a German (EU compatible) vaccination certificate into the TousAntiCovid App you probably need to check with the support for TousAntiCovid App to find out if they have gone live and are ready to accept EU certificates already.

**Comment by MissinstaPam** [comment]
no its a french one wanting to put into the french app

**Comment by Ein-Tim** [comment]
@MissinstaPam 

Please contact the Support of the TousAntiCovid app in this case. 
Thanks!

**Comment by MissinstaPam** [comment]
yes I did yesterday but haven't received any response other than the tech people are looking into it.  I am trying to avoid going back to the vaccination centre to find out its an issue with my phone :(  but I have even changed my region to France (despite me being Irish with an Irish phone contract)

thanks for the response, I guess its a waiting game

**Comment by MikeMcC399** [comment]
@MissinstaPam 
> no its a french one wanting to put into the french app

Since this issue list is about the German Corona-Warn-App, we can't really help you with the French TousAntiCovid app.

[TousAntiCovid](https://play.google.com/store/apps/details?id=fr.gouv.android.stopcovid&hl=en) on the Google Play Store lists the web site as https://bonjour.tousanticovid.gouv.fr/ and the support address as contact@tousanticovid.gouv.fr. There is also a link to https://attestation-vaccin.ameli.fr/.

I found on https://www.ameli.fr/assure/covid-19/vaccination-contre-la-covid-19/lattestation-de-vaccination-certifiee-en-pratique

"When will the vaccination certificate be available for travel?

From June 23, it will be possible to download its certificate of vaccination certified in accordance with European standards, with English subtitles, from the Health Insurance teleservice. This certificate will be part of the evidence authorized for travel within the European Union as of July 1."

so it looks as though one more day of patience is needed for people vaccinated in France to be able to get a certificate which is compatible with the German Corona-Warn-App.

**Comment by relffok** [comment]
@devsnd Did the automatic update in TousAntiCovid work for you?

**Comment by heinezen** [comment]
Hello @devsnd ,

According to the [European overview for EU Covid Certificates](https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/safe-covid-19-vaccines-europeans/eu-digital-covid-certificate_en#what-data-does-the-certificate-include-is-the-data-safe), France should be connected to the system by now. You should be able to get a certificate compatible to the EU system.

Unfortunately, I don't know how France handles the issueing of new certificates, so I can't give instructions on how to proceed. Maybe a Frenc government website has more infos?

----
Corona-Warn-App Open Source Team

**Comment by devsnd** [comment]
So the tousanticovid app now supports reading the new format, but my certificate inside of the app is still in the old format. I'll monitor if the certificate will be updated within the next few days and also try the support from the tousanticovid app to find out if there is something I still need to do to get it updated.

Once I have the EU Cert, I will report back if i can transfer it from the french app to the German one. So if you don't mind I'd like to keep the issue open in the meanwhile (I hope that doesn't negatively impact any support KPIs or something 😬)

And thanks again for your prompt and very helpful responses!

**Comment by thomasaugsten** [comment]
This ha no negative impact. The support of the French codes is a very valuable information

**Comment by MissinstaPam** [comment]
Hi all there was an issue in France with certificates issues on Monday 21/6 as France changed over the new system on Tuesday 22/6! In order for me to rectify this I could print it again on Amelie.fr but as I am Irish I am not in the French health care system I returned to the vaccination centre today Sunday 27/6 where I got a new certificate in the new format & this is now visible in the App wallet of Tousanticovid! Issue resolved

**Comment by davidsan** [comment]
In France, the QR in EUDCC format can be obtained from [Ameli](https://attestation-vaccin.ameli.fr). It shows up correctly when added to the CWA app.

**Comment by MissinstaPam** [comment]
Hi David, as stated above this solution will only work if you are in the French Healthcare system.  I got vaccinated as an EU Health Insured person.  Hopefully this issued only applied to certs issued the day before the changeover to the new format and hopefully everyone with the same issue as me has had the matter resolved

**Comment by dsarkar** [comment]
@devsnd  See https://github.com/corona-warn-app/cwa-wishlist/issues/560#issuecomment-869163083

**Comment by relffok** [comment]
With the latest TousAntiCovid update a conversion from 2D-DOC to the EU certificate is possible directly in the app. Adding it to CWA was no problem either!

**Comment by MikeMcC399** [comment]
@devsnd 
Did you have any success in the meantime?

**Comment by devsnd** [comment]
With the latest version of the TousAntiCovid app, I was now able to convert my certificate. Just tap on the three dots in the upper right corner of your DOC-2D certificate (a small option menu appears) and tap convert. After the conversion, you can export the certificate as an image. You can then print that image or send it to other device, so that you can scan it again in the german app. Scanning the exported EUDCC in the german corona warn app works perfectly. 

Thanks to everybody for your responses and insights. I will close this issue now as my specific problem has been solved. Similar but distinctly different problems should be tracked in a new issue.

Thanks once more and have a nice day. 🎉

**Comment by heinezen** [comment]
Thanks for reporting! Great that it works for you now.

----
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@devsnd Thanks for reporting and contributing here. Best wishes, 

---
Corona-Warn-App Open Source Team
