### ISSUE TITLE
Add CWA Apple Watch app for EU COVID-19 vaccination/immunity certificate

### ISSUE THREAD

**Issue by janekwunderlich** [corona-warn-app/cwa-wishlist#563]
## Feature description

As previously described in issues such as https://github.com/corona-warn-app/cwa-app-ios/issues/2965 the option to add vaccination (or in the future EU COVID-19 tested/immunity certificates) records was wanted several times in order to make it easier and quicker for users to access their records when required to provide them. The reason the request was denied was privacy - Apple Wallet can be accessed too easily without an extra layer of protection.

An easy and privacy protecting solution would be an Apple Watch app which lets you access your vaccination (tested/immunity) records and provides the QR code to be scanned when required. 

The app on Apple Watch would just allow you to access your records, no additional functionality.

## Problem and motivation

Quicker access to provide immunity proof when legally required. It's just a lot easier for people who own an Apple Watch.

## Is this something you're interested in working on

Sadly, I haven't done much with WatchKit yet. So no.

----
Internal Tracking-ID: [EXPOSUREAPP-8106](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8106)

**Comment by Ein-Tim** [comment]
Related issue: #12 ("Corona-Warn-App for Apple-Watch").

But not a duplicate, since the author of #12 explicitly mentions that the certificate scenario should be tracked in a separate issue (see https://github.com/corona-warn-app/cwa-wishlist/issues/12#issuecomment-864000856).

**Comment by Nils-witt** [comment]
Maybe also a watch face compilation for easy access?

**Comment by idoodler** [comment]
Why not just use the Wallet integration, its quickly available on both iOS ans watchOS (double press on the side button). Why make a whole new App for that?

**Comment by Nils-witt** [comment]
There was a request for the wallet integration in this Issue https://github.com/corona-warn-app/cwa-app-ios/issues/2965 and why they rejected it (for now) and with the own app there are no third-party services involved

**Comment by larswmh** [comment]
Closing this issue as the related internal ticket is set to `obsolete`.

Developer comment:
Too much effort and no equivalent functionality for Android.
