### ISSUE TITLE
Impfnachweis für mehrere Personen / vaccination verification for multiple persons

### ISSUE THREAD

**Issue by bassqualle** [corona-warn-app/cwa-wishlist#564]
## Current Implementation
Corona warn app can handle the vaccination vertificate of one person only.

## Suggested Enhancement
Corona warn app can manage vaccination certificates of multiple persons, which is useful for families. 

## Expected Benefits
- Case: Husband and wife can use one mobile phone to verify vaccination certificates on requests. This comes in handy when a family as a group checks into a event/location.
- Case: Parents can also have the vaccination certificates of their kids on their mobiles.
- Info: CovPass app is already able to do this! And I dislike to have two apps for the same purpose while I am a supporter of the Corona warn app.

---
Internal Tracking ID: [EXPOSUREAPP-7648](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7648) iOS
Internal Tracking ID: [EXPOSUREAPP-7574](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7574) Android

**Comment by jucktnich** [comment]
Will be integrated

**Comment by jucktnich** [comment]
https://github.com/corona-warn-app/cwa-app-ios/pull/2934

**Comment by Ein-Tim** [comment]
Planned for Version 2.5.

Internal Tracking ID: [EXPOSUREAPP-7648](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7648)

**Comment by bassqualle** [comment]
Thanks! Will watch out for version 2.5 then :-)

**Comment by MikeMcC399** [comment]
Android [v2.5.0-RC0](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.5.0-RC0) includes:

Family Support for certificates (EXPOSUREAPP-7574)
- Person overview screen (EXPOSUREAPP-7666) [#3441](https://github.com/corona-warn-app/cwa-app-android/pull/3441)
- Support registering certificates for multiple persons (EXPOSUREAPP-7682) [#3445](https://github.com/corona-warn-app/cwa-app-android/pull/3445)
- Certificates info screen update (EXPOSUREAPP-7661) [#3450](https://github.com/corona-warn-app/cwa-app-android/pull/3450)
- Sort persons by name (EXPOSUREAPP-7952) [#3476](https://github.com/corona-warn-app/cwa-app-android/pull/3476)
- Register CoronaTest-Certificate directly (EXPOSUREAPP-7974) [#3484](https://github.com/corona-warn-app/cwa-app-android/pull/3484)
- PersonOverviewFragment Selfies (EXPOSUREAPP-7681) [#3488](https://github.com/corona-warn-app/cwa-app-android/pull/3488)
- Person details screen (EXPOSUREAPP-7574, 7657, 7861) [#3487](https://github.com/corona-warn-app/cwa-app-android/pull/3487)
- Navigate to person details (EXPOSUREAPP-7984) [#3536](https://github.com/corona-warn-app/cwa-app-android/pull/3536)

@dsarkar 
I couldn't find any Android PR corresponding to 

> Internal Tracking ID: [EXPOSUREAPP-7647](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7647) Android 

https://github.com/corona-warn-app/cwa-app-ios/pull/2978 "Feature/7647 recovery certificate/storybranch" is however used in iOS. Could you perhaps check and modify the main entry for Android accordingly?

**Comment by heinezen** [comment]
@MikeMcC399 The Android PR is https://github.com/corona-warn-app/cwa-app-android/pull/3487

Edit: Correct Jira tickets are linked now

**Comment by MikeMcC399** [comment]
@heinezen 
> The Android PR is corona-warn-app/cwa-app-android#3463
>
> Edit: Correct Jira tickets are linked now

I don't understand because corona-warn-app/cwa-app-android#3463 refers to a recovery certificate, whereas this wishlist item is about vaccination certificates for multiple persons.

Originally the article said:
Internal Tracking ID: EXPOSUREAPP-7648 iOS
Internal Tracking ID: EXPOSUREAPP-7647 Android

and you have now changed this to
Internal Tracking ID: EXPOSUREAPP-7647 iOS
Internal Tracking ID: EXPOSUREAPP-7617 Android

EXPOSUREAPP-7648 refers to Feature/7648 family in iOS and seems to have been the right reference for iOS

Perhaps "Family Support for certificates (EXPOSUREAPP-7574)" is the right corresponding reference for Android?

**Comment by heinezen** [comment]
@MikeMcC399 You're correct, I got the two mixed up. The linking inside Jira was also not correct.

Everything should be fixed now!

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
RKI announced this for mid-July 2021. https://twitter.com/coronawarnapp/status/1410175946792083463?s=20.

**Comment by Ein-Tim** [comment]
This has been implemented with version 2.5! 🎉

See the blog post: https://www.coronawarn.app/en/blog/2021-07-12-cwa-version-2-5/

**Comment by dsarkar** [comment]
Dear @bassqualle and community. Thanks for contributing here. As mentioned by @MikeMcC399 and @Ein-Tim this feature has been implemented with release 2.5. Therefore we suggest to close this issue. Thanks to everybody! Best, DS

---
Corona-Warn-App Open Source Team

**Comment by bassqualle** [comment]
Dear @dsarkar @Ein-Tim @MikeMcC399 and CWA-development team,

I am very much looking forward for this feature in the upcoming update of CWA!
Thanks for the quick implimentation and for the transparent handling of issues and feature requests.

**Comment by dsarkar** [comment]
@bassqualle Thanks for the feedback!
