### ISSUE TITLE
Zertifikatkennungseingabe als Alternative zum QR-Code

### ISSUE THREAD

**Issue by UsagiMitsu** [corona-warn-app/cwa-wishlist#565]

**Comment by UsagiMitsu** [comment]
Hi! :) 

Mein Handy hat leider eine leicht defekte Kamera. Daher kann ich den QR-Code meines Impfzertifikats nicht scannen. Wäre es vielleicht möglich, die Eindeutige Zertifikatkennung alternativ auch händisch einzugeben?
Z. B. So wie ein iPhone die Code-Eingabe anbietet, wenn der Fingerabdruck aus Grund XYZ nicht gelesen werden konnte. :) 

Wäre cool, wenn das klappt. :) 

LG
Usagi <3

**Comment by jucktnich** [comment]
Somewhat related to https://github.com/corona-warn-app/cwa-wishlist/issues/389

**Comment by thomasaugsten** [comment]
Es reicht leider nicht die eindeutige Zertifikatskennung einzugeben. Es muss der komplette 573 Zeichen lange Inhalt eingegeben werden

**Comment by Ein-Tim** [comment]
... der nur mit Hilfe eines anderes QR-Code scanners herausgefunden werden kann, oder @thomasaugsten?

**Comment by thomasaugsten** [comment]
Das ist korrekt, ein Mensch kann keine QR-Codes erfassen

**Comment by UsagiMitsu** [comment]
Danke euch drei (?) :) 
Schade, aber selbst wenn ich die über 500 Zeichen herausbekommen würde, sicherzustellen, dass ich alles korrekt eingegeben habe und dann den Fehler finden ist 5x komplexer als das W-LAN-Passwort richtig einzugeben. -.- 
Aber vielen lieben Dank für die Erleuchtung!! <3

**Comment by Ein-Tim** [comment]
@UsagiMitsu Wenn du magst kannst du diesen Issue schließen. Du solltest dazu einen großen Button sehen, links unter dem Kommentieren-Feld, wenn du auf GitHub.com bist.
