### ISSUE TITLE
Add option to start on certificates tab

### ISSUE THREAD

**Issue by Pe-te** [corona-warn-app/cwa-wishlist#566]
## Current Implementation
Always starts on the first tab

## Suggested Enhancement
App should make it configurable (with an option last active tab)

## Expected Benefits
i just want to show people my fancy Impfnachweis, so I want to start on the second tab to save clicks! 😄

----
Internal Tracking-ID: [EXPOSUREAPP-8178](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8178)

**Comment by heinezen** [comment]
@Pe-te 

Thank you for your suggestion. I've created an internal ticket for the proposal. It will now be discussed by the dev team.

----
Corona-Warn-App Open Source Team

**Comment by ndegendogo** [comment]
An option to start cwa on the last used tab is a good idea. Everybody uses cwa differently; and for a good user experience the app should make it as easy as possible to use for everybody.

**Comment by larswmh** [comment]
Closing this issue as the related internal ticket is set to `obsolete`.

Developer comment:

> Main purpose of the app is "warn others" -> Homescreen.

**Comment by ndegendogo** [comment]
@larswmh and maybe adding a remark: the comment on that Jira ticket is outdated meanwhile (probably it was correct when the Jira ticket was closed).

Meanwhile we have the behaviour, at least on iOS (for Androod I don't know): the app starts on the same tab as was active when I closed it before.
😅😅😅

**Comment by MikeMcC399** [comment]
@ndegendogo 
On Android my experience is that the app always starts on the "Status" tab, however if you long-press on the CWA icon to open the app, there is now an option "Display Certificates", which opens the app on the "Certificates" tab.

This was introduced in [v2.23.1](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.23.1) with "Add app shortcuts to primary targets (EXPOSUREAPP-5414)" https://github.com/corona-warn-app/cwa-app-android/pull/4685.

**Comment by Ein-Tim** [comment]
iOS automatically continues where you left off in an app if you don't hard close it or the device decides to kill the background process for performance reasons.

**Comment by ndegendogo** [comment]
> iOS automatically continues where you left off in an app

@Ein-Tim the behaviour of cwa was not like this in the early days when they introduced the tabs. **Has this maybe changed with newer versions of iOS?**

Yes, Apple recommends that apps behave this way; and they provide an API to make it easy for app developers. But I think  still the app developers have to implement this behaviour / use the API.

**Comment by Ein-Tim** [comment]
@ndegendogo 

I have no app on my phone which behaves in a different way, so I guess it's standard now. 
Could also be that it depends on iOS version & iPhone model.
