### ISSUE TITLE
Apple App Store: Lower age rating to 12

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#568]
## Current Implementation
The App Store rates that the Corona-Warn-App as 17+ for "Frequent/Intense Medical/Treatment Information". 
Why this is a problem has been described here: #29

## Suggested Enhancement
Lower the age limit to 12 again.

## Expected Benefits
See #29.

---
Internal Tracking ID: [EXPOSUREAPP-8176](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8176)

**Comment by dsarkar** [comment]
@Ein-Tim Thanks. Internal Tracking ID: [EXPOSUREAPP-8176](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8176)


---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
I can confirm that this has been changed with version 2.5.

Closing as fixed/implemented.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for checking.
