### ISSUE TITLE
Simplify QR code scan behaviour

### ISSUE THREAD

**Issue by DRE-TSI** [corona-warn-app/cwa-wishlist#575]
This is an idea, to simplify the QR code scan variety.

 In CWA there are 5 kinds of QR-code (V2.4 and following):

- RAT
- PCR test
- Event check-in
- RAT profile
- Vaccination certificates

and with following versions of the CWA it's likely that there will be even more (Luca, ...).
 
Problem: 
I saw it for myself, that a user opened the check-in-screen and tried to scan a PCR test code. This went wrong, with an error message (which was correct). 

But I assume, that a lot more people are confused, which qr-code to scan with which "module".

 
Idea:
Only one "multi purpose" scan screen on the CWA home screen and depending on the QR content string, the CWA decides, how to go on:

- QR for PCR-Test
   Beginning with "https://localhost" - jump to PCR-Test-result screen
- QR for RAT-Registration
   Beginning with: "https://s.coronawarn.app" - jump to RAT-result screen
- QR for Event-Registration:
   Beginning with: "https://e.coronawarn.app" - jump to the Check in screen 
- QR for vaccination : 
   Complex and encrypted/signed data, which (from my point of view) is possible to decrypt 
   and detect as a valid vaccination certificate code - jump to Vaccination certificate screen

- QR for RAT-Profile 
   nothing to scan with the CWA only possibility to show app created code at the test station 

So many issues to the user could be minimized or suppressed, when the CWA scan modul would decide for the user, which qr code was scanned and to route this data to the correct modul/section within the app.

See also EXPOSUREAPP-7281.

---
Internal Tracking ID: [EXPOSUREAPP-7281](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7281)
Internal Tracking ID: [EXPOSUREAPP-7594](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7594) duplicate
Internal Tracking ID: [EXPOSUREAPP-8395](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8395)

duplicate or strongly related to: https://github.com/corona-warn-app/cwa-wishlist/issues/501
duplicate or strongly related to: https://github.com/corona-warn-app/cwa-wishlist/issues/575

**Comment by jucktnich** [comment]
I'd rather suggest (like posted in another issue) to generate a qrcode scan module, which gets called from all the places you can scan an qrcode and if you scan a qrcode, which is not for this part of the app, shows a message, if the qrcode should be opened in the part of the app, which the qrcode is for.

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-7281](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7281)
Internal Tracking ID: [EXPOSUREAPP-7594](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7594) duplicate
Internal Tracking ID: [EXPOSUREAPP-8395](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8395)


duplicate or strongly related to: https://github.com/corona-warn-app/cwa-wishlist/issues/501
duplicate or strongly related to: https://github.com/corona-warn-app/cwa-wishlist/issues/575

**Comment by Ein-Tim** [comment]
@dsarkar Would it make sense to close this issue in favor of #501?

**Comment by DRE-TSI** [comment]
Closed, duplicate of #501 .
