### ISSUE TITLE
Increase brightness while QR code is shown

### ISSUE THREAD

**Issue by Mucithe** [corona-warn-app/cwa-wishlist#576]
## Avoid duplicates
* [X] This enhancement request has not already been raised before
* [X] Enhancement request is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [X] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

Currently the QR codes can be hard to scan if the display is too dark.

## Suggested Enhancement

The app could increase the brightness of the screen every time a QR code is shown. This is done for example by the wallet app.

## Expected Benefits

This way there should be less problems with scanning the QR codes.

---
Internal Tracking ID: [EXPOSUREAPP-8224](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8224)

**Comment by dsarkar** [comment]
@Mucithe Thanks for the suggestion. Internal Tracking ID: [EXPOSUREAPP-8224](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8224)
Best wishes, DS 

---
Corona-Warn-App Open Source Team

**Comment by jucktnich** [comment]
Duplicate of #571

**Comment by Mucithe** [comment]
Oh sorry, I didn't look at this repo as I didn't know the possibilities and the current implementation on Android.  But I will leave it to the maintainer whether this issue is closed or not, as it has already been mirrored in Jira and an assignee has been added to it.

**Comment by dsarkar** [comment]
@Mucithe no worries, we can keep your issue open, since your title is more general.
@jucktnich Thanks for pointing out the duplicate.


FYI: This suggestion is considered as a  high priority issue to be implemented.

**Comment by heinezen** [comment]
Duplicate of #571
