### ISSUE TITLE
Hide Vaccination "Valid to" from main screen of vaccination certificate and explain what it means in the details

### ISSUE THREAD

**Issue by jkrwdf** [corona-warn-app/cwa-wishlist#577]
## Current Implementation

In contrast to CovPass, the CWA prominently shows the validity of the digital signature of the vaccination certificate

![image](https://user-images.githubusercontent.com/5329491/124265581-2aefaf00-db36-11eb-8b3f-aebeb0494b47.png)

As most users of the CWA are not technicians, there is a potential of confusion between "Until when is my vaccination protecting me" and "technical validity of the signature".

## Suggested Enhancement

At the location shown in the screenshot above, no "Valid to" shall be shown. 
In the detail data of the vaccination (when you tap the "Vaccination x of y" field), the signature validity may be shown, but with an explanation text what it means (that this date has no medical meaning). 

## Expected Benefits
Avoid people deducing wrong conclusions ("Ah, I need a new vaccination after that date").

In the screenshot above, the fact that both dates are fully unrelated is already hinted by the fact that my vaccination was in a different month from the date when the certificate was technically created.

**Comment by Ein-Tim** [comment]
Hey @jkrwdf 

Could you take a look at https://github.com/corona-warn-app/cwa-documentation/issues/645, please? I think this issue basically asks for the same, to clarify what the "valid to" means. 

Thanks.

**Comment by jkrwdf** [comment]
Hi @Ein-Tim , 

absolutely. Thanks for the hint. 

Closing.
