### ISSUE TITLE
Blurred QR code for certificates

### ISSUE THREAD

**Issue by erikzimmermann** [corona-warn-app/cwa-wishlist#580]
## Current Implementation
Currently, the QR code is directly visible on the certificate page and can be scanned without security confirmation. 

If someone wants to see my vaccine certificate, he/she could get my QR code directly, which could then be copied to other devices.

## Suggested Enhancement
The QR code should be blurred by default (or as an option in the settings). To display the code, the user could simply tap on the blurred code to make it readable.

## Expected Benefits
Security enhancements to prevent scammers from stealing vaccine certificate QR codes.

---
Internal Tracking ID: [EXPOSUREAPP-8268](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8268)

**Comment by dsarkar** [comment]
@CodingAir thanks for the proposal. Internal Tracking ID: [EXPOSUREAPP-8268](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8268) 

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@CodingAir 

Could you elaborate in which situations this would increase the security?

**Comment by Ein-Tim** [comment]
@CodingAir Was it your intention to close this issue?

**Comment by erikzimmermann** [comment]
> @CodingAir Was it your intention to close this issue?

Yes, I don't think it's necessary anymore.
