### ISSUE TITLE
Generate printout for EU vaccination certificates

### ISSUE THREAD

**Issue by marcellogalhardo** [corona-warn-app/cwa-wishlist#583]
## Feature description

Generate a printout for the stored EU COVID certificate.

Now that Corona Warn App supports Vaccination Certificates, it would be great if we could export the certificates for backup purposes. 

There are similar data exporting requests but none of them mention COVID Vaccination Certificates.

## Problem and motivation

A backup will let us change phones and keep our certificates, without requiring to scan again the original physical papers (that might be lost).

## Is this something you're interested in working on

Yes, for Android platform.

----
Internal Tracking-ID: [EXPOSUREAPP-8352](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8352) obsolete (vaccination DCC)
Internal Tracking ID: [EXPOSUREAPP-8328](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8328) obsolete (test DCC)
Internal Tracking ID: [EXPOSUREAPP-8384](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8384) export function for all DCCs -iOS

**Comment by Ein-Tim** [comment]
@marcellogalhardo 

Are you aware that you can just scan the QR-Code shown in the app? 
See https://github.com/corona-warn-app/cwa-wishlist/issues/582.
Or what exactly do you mean with "export"? 
Or do you want that the app generates a printout (which looks like the paper you got from the pharmacy/vaccination center/etc.)?

**Comment by heinezen** [comment]
Hey @marcellogalhardo 

If you want to transfer your certificate to another device, you can just scan the QR code displayed in the app. Generating a printout is not possible at the moment, so I'd modify your feature request to explicitly mention generated printouts.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@heinezen 

This is now very closely related to #581, maybe we should think of merging the two requests?

**Comment by heinezen** [comment]
@Ein-Tim https://github.com/corona-warn-app/cwa-wishlist/issues/581 is being discussed separately internally, so this one gets its own ticket and issue for now.

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@heinezen 
Maybe it would make sense to have a wishlist item to be able to print out all three different types of digital COVID certificates:
- Test (#581)
- Vaccination (#583)
- Recovery (not yet requested, supported by future CWA 2.5 version)

**Comment by dsarkar** [comment]
Internal Tracking-ID: [EXPOSUREAPP-8352](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8352) obsolete (vaccination DCC)
Internal Tracking ID: [EXPOSUREAPP-8328](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8328) obsolete (test DCC)
Internal Tracking ID: [EXPOSUREAPP-8384](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8384) export function for all DCCs

Currently the following is being considered:
- PDF can be generated for all types of certificates
- Original EU template used for printing
- PDF can be shared using the standard OS sharing functionality

**Comment by Ein-Tim** [comment]
@heinezen Was it intended to close this?

**Comment by heinezen** [comment]
Good news everyone,

The dev team has considered export for all digital certificates. We will now use https://github.com/corona-warn-app/cwa-wishlist/issues/581 as the main discussion thread. The issue here will be closed.

----
Corona-Warn-App Open Source Team
