### ISSUE TITLE
Scan vaccination QR codes from file

### ISSUE THREAD

**Issue by mfleisch** [corona-warn-app/cwa-wishlist#584]
## Feature description
Possibility to directly import vaccination certificate files (qr-code) into the CWA without the need of a second device or to print it on paper. If the detection of the qr-code in differently structured documents makes things complicated the user could select the qr-code in a preview window.

## Problem and motivation

Certificates are usually provided as a pdf that contains the qr-code. To import this qr-code in to the CWA it has either to be printed or a second devices is needed to display the qr-code which seems to be a unnecessarily complicated workflow. There are people that just have a smartphone and do not have a printer at home. 

## Is this something you're interested in working on

No

----
Internal Tracking-ID: [EXPOSUREAPP-8353](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8353)

**Comment by Ein-Tim** [comment]
Related issue: #389

**Comment by heinezen** [comment]
@mfleisch 

Thanks for your proposal. I've added it to our internal list of feature request. The devs and the RKI will take a look and decide whether this will be implemented.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
I suggest to merge this issue with #389 since it seems like that a import of QR codes is considered for all QR codes, including vaccination QR codes.

**Comment by dsarkar** [comment]
@mfleisch Thank you for your contribution. We suggest closing this issue as duplicate. As @Ein-Tim mentioned, this proposal is covered by #389. 

Best wishes, DS 


---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
I think the `Fix 2.7` label is wrong here... sadly (;

**Comment by dsarkar** [comment]
@mfleisch @Ein-Tim yep the 2.7 label was a mistake. This feature is in the pipeline, but at this stage it is not clear right now in wich release it will be implemented.
