### ISSUE TITLE
Text: Make it clearer that you don't have to renew event QR-Codes every day

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#588]
## Current Implementation

| English | German |
|---|---|
| <img src="https://user-images.githubusercontent.com/67682506/126013039-73e61cf1-16a4-4e86-90d0-8b1b710eade9.png" width="300"> | <img src="https://user-images.githubusercontent.com/67682506/126013043-5b4b9d14-30e2-40ef-ac96-e5f0bf71a0b9.png" width="300"> |

## Suggested Enhancement
Many users think that they **have to** renew CWA event-registration QR codes every day and therefore decide against the CWA (see: https://twitter.com/jaeger1972/status/1405169435288211464?s=20 & https://twitter.com/RobertKoeHH/status/1414534318907662342). 
It should be made clearer that this is only strongly recommended, but they don't have to.

## Suggested Change

Change
"If you want to use a QR code for the long term, you should generate it again each day, outside of your operating hours."
to
"If you want to use a QR code for the long term, we recommend to generate it again each day, outside of your operating hours."

Same in the respective German text.

## Expected Benefits
Users won't decide against CWA because they think that they have to renew the code every day. Thus more places where user can check-in with the CWA. 

## Additional Information

I can create a PR for this under iOS.

----
Internal Tracking-ID: [EXPOSUREAPP-8476](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8476)

**Comment by heinezen** [comment]
@Ein-Tim 

You need to extend the section with Expected Benefits more because renewing the code is an important security measure and should not be considered as optional. Of course, you're not forced to renew the QR code, but that's only possible because there's no central entity that can invalidate it.

The reason the QR code is renewed is outlined in the [event registration documentation](https://github.com/corona-warn-app/cwa-documentation/blob/master/event_registration.md#profiling-of-venues)

> An adversary can collect these warnings and aggregate them to compile a list of venues with the most warnings (colloquially referred to as most infectious venues) or a list of venues with their most recent warning.

Not renewing the QR code significantly reduces the effort for the adversary here as they only need to acquire the QR code once.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@heinezen 

The expected benefit of being clearer here is that venue owners or organizer of Events don't decide against the Corona-Warn-App because they think they have to renew the codes every day.

E.g: The owner of a restaurant in Lower Saxony wants to digitalize their process of storing contact data. They inform themselves what options they have. The "luca" app, the "darichrein" service, "free2pass" and also the official and in Lower Saxony allowed "Corona-Warn-App".
In general they would prefer to use the "Corona-Warn-App", because they have already installed it on their smartphone and they know that it's very simple for their guests because they don't have to enter any contact data & in case of an infection they have to do nothing, not uploading any keys or similar. 

Now they think where to put the QR-Codes, they want to split their restaurant into zones, since it's quite big and also has an outdoor area, so it wouldn't make so much sense to have one QR-code for all guests. 
They decide to split the indoor area into 3 zones and the outdoor one into 2. They have the idea to print out the QR-codes and laminate them to glue them on the tables, so that it's ensured that all guests check in to the right QR-code. 

But then they read through the information text in the CWA again and also comes across the text I shared screenshots of in the OP. They are not sure what this means and can't find more information in the FAQ. At this point they are very unsure if they would have to print out new QR-codes every day or if it's sufficient to use one QR-code all the time. They know from other restaurant owners who use the "luca" app that they don't have to renew the QR-code and at this point they decide against the Corona-Warn-App and for the "luca" app. 

---

I also don't ask for a big change here, but the text could be aligned with the last bullet point of the "Data protection and data security" paragraph which says:

<img src="https://user-images.githubusercontent.com/67682506/126032265-237d2f17-2742-4667-8fa1-151874d76b45.jpeg" width="300">

The bullet point sounds much nicer and it's clear that this is only a recommendation "We **recommend** creating new QR codes […]".

**Comment by heinezen** [comment]
@Ein-Tim 

I can see where you're coming from, but the example does not address the security problems that result in not renewing the QR code. If we consider the security implications, using one QR code is not sufficient.

Maybe I should provide an example for an attack: In short, if QR code were never renewed, an adversary can very easily create a "hotspot map" where they show the venues that have been visited by COVID positive persons and how many positive people have visited the venue overall. This can lead to a stigmatization of the venue for something that is pretty much out of their control. It can also lead to a stigmatization of known guests because they could have contracted COVID.

So, if the proposed change leads to venue owners thinking that they can skip renewing the QR code, this is not a good trade-off.


----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@heinezen 

Thank you for understanding my point!

I understand your point here and I think we both know that not renewing QR codes can lead to security risks. Thanks also for the example, this makes it clearer again. 

It has to be decided internally if we could change the text "**If you want to use a QR code for the long term, you should generate it again each day, outside of your operating hours.**" to something where it gets clear that this is a recommendation, like "**If you want to use a QR code for the long term, we recommend to generate it again each day, outside of your operating hours.**"

I don't see this change to lead to a higher security risk because venue owners don't renew the QR code, since the text in the last bullet point (see [here](https://user-images.githubusercontent.com/67682506/126032265-237d2f17-2742-4667-8fa1-151874d76b45.jpeg)) also already talks about a recommendation.

My point is not to encourage venue owners to not renew QR codes, but to make sure that nobody decides against the Corona-Warn-App check-in feature because they think that they have to renew the QR code. They don't have to, but it's strongly recommended. 

As said in the OP, I could provide a PR for this under iOS, but before I do this I'd like the team to look at my proposed change, which would be to change the text from:

"If you want to use a QR code for the long term, you should generate it again each day, outside of your operating hours."
to
"If you want to use a QR code for the long term, we recommend to generate it again each day, outside of your operating hours."

(Thanks for the note with they - and in general thanks for taking your time to write comments that long ❤️)

**Comment by heinezen** [comment]
@Ein-Tim 

I thought about it and I think we should try to solve the problem like this: I'll ask the dev team to

1. Align the text in the Data Protection Notice and the QR code creation information screen
2. Decide whether there should be *strong* or *soft* recommendation (i.e, whether to use "should" vs. "recommend" in the text)
3. Check if we have to warn users about the potential consequences (like the data protection notice already does)

The text change would need approval in any case. We'll see what the developers have to say about the topic.

> (Thanks for the note with they - and in general thanks for taking your time to write comments that long ❤️)

Well, thank you too for watching the Twitter users :)

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@dsarkar I would like to give it a try and provide a PR for this item. Could you please cross-check what the internal status of this item is and come back to me?

Thank you!

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
