### ISSUE TITLE
Add a timestamp to error messages (especially when error occurs from background process)

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-wishlist#589]
## Current Implementation

Currently, error messages are displayed without any timestamp.
When an error occurs during background processing, the message is displayed only much later. This makes it hard to analyse the root cause of such an error.

## Suggested Enhancement

The error message should be composed with a timestamp. This is especially usefull if the error happens during background processing, e.g. risc check.

## Expected Benefits

In some cases, especially for errors occurring during background processing, the timestamp of the **root cause of the failure** would give us more context and help with error analysis.

---
Internal Tracking ID: [EXPOSUREAPP-10190](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10190)

**Comment by ndegendogo** [comment]
See also [this comment](https://github.com/corona-warn-app/cwa-wishlist/issues/112#issuecomment-667407139)

**Comment by ndegendogo** [comment]
@dsarkar @heinezen 

Please ask the devs what they think of this idea. I would volunteer for a PR, but only for iOS, not for Android. I would limit the timestamp to error codes from ENF.

I hope that this could help to give insights, especially on error 13

**Comment by ndegendogo** [comment]
@dsarkar @heinezen I didn't get any feedback on this proposal for a long time.

Recently I got again [ENF error 13](https://github.com/corona-warn-app/cwa-app-ios/issues/3329#issuecomment-950280426). I saw the error message when I opened cwa in the morning; at this time my ENF log shows a successful risk check. However, in the night before I have an empty ENF log entry.
So I have the suspicion: maybe the error message is related to the empty log entry in the night?
In my opinion it would be extremely helpful to confirm (or reject) this suspicion.

So I implemented the extended error message according to this proposal and submitted PR #3749 (only for iOS).
We can as well discuss the pros and cons of such a timestamp directly in the PR.
Please add the label so the developers are not confused. Thanks!

**Comment by dsarkar** [comment]
@ndegendogo Good morning! We forwarded you comment together with the proposal and PR! Thanks!

**Comment by ndegendogo** [comment]
cwa version 2.14.1 (0) was rolled out.
Closing this as fixed.

**Comment by dsarkar** [comment]
@ndegendogo Thanks again for the PR. Apparently this feature made already happy at least one tester. ;-)

**Comment by ndegendogo** [comment]
> Apparently this feature made already happy at least one tester. ;-)

@dsarkar really?! 😅🎉
