### ISSUE TITLE
Room based  exposure notification

### ISSUE THREAD

**Issue by stefanlin** [corona-warn-app/cwa-wishlist#59]
## Feature description
Add support for none Phone devices. Here you can imagine that in a certain room of a building a device is placed that sends IDs just like a telephone. Maybe with higher transmission power. If it is discovered in this room that there have been many infections (e.g. by aerosols) the IDs of the device in the room could be published.

## Problem and motivation

Epidemiologically, it may be become important that when super spreading events are discovered, **all** people who have participated in these events shoud be informed.

## Is this something you're interested in working on

Yes

----------
Internal Tracking ID: EXPOSUREAPP-2139

**Comment by daimpi** [comment]
Related: https://github.com/corona-warn-app/cwa-wishlist/issues/70

**Comment by sbernhard** [comment]
Something like this would also help in Kindergarten, Schools and other areas in which no mobile phones are allowed.
I think about a tiny device which just handles the bluetooth part and does later on send / receive the data when connect to a phone (= parents).

**Comment by Blackjacx** [comment]
> Something like this would also help in Kindergarten, Schools and other areas in which no mobile phones are allowed.
> I think about a tiny device which just handles the bluetooth part and does later on send / receive the data when connect to a phone (= parents).

Maybe the Apple AirTags, probably announced this Tuesday, could help accomplishing this task... Or any kind of Bluetooth beacons, since Android should be considered.

**Comment by heinezen** [comment]
Hello everyone,

This feature has been implemented in CWA 2.0 as part of the event registration feature. Instead of having a beacon sending the random IDs, the users have to scan a QR code (which would be the same as your static device).

This issue will be closed. If you have new ideas for the current implementation of the feature, please consider opening a new issue.

----
Corona-Warn-App Open Source Team
