### ISSUE TITLE
Hotline wish: Daily reminder for contact journal 

### ISSUE THREAD

**Issue by DRE-TSI** [corona-warn-app/cwa-wishlist#590]
This wish was addressed at the Technical Hotline:

Anrufer wünscht dass sich das Tagebuch täglich meldet quasi als Erinnerung, dass man Informationen reinschreibt!! Denn bei coronika wäre dies möglich?!

**Comment by Ein-Tim** [comment]
Hi @DRE-TSI 

Thanks for forwarding this suggestion, however, we have this issue already: #294.

I suggest to close this issue here.

Thank you!

**Comment by DRE-TSI** [comment]
Hi TIM,

sure, I did not see the other issue.

Kind regards,

DRE-TSI

**Comment by DRE-TSI** [comment]
duplicate

**Comment by heinezen** [comment]
Duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/294
