### ISSUE TITLE
Contact Journal: Add 4th category „Vaccinated“

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#594]
## Current Implementation
In the contact journal, you can enter people & locations. 
For people, you can choose the circumstances in which the encounter took place:

![image](https://user-images.githubusercontent.com/67682506/126290298-4fea9f88-adea-4229-b9ba-4c3b34e8e4da.jpeg)

## Suggested Enhancement
Add a 4rd category "Vaccinated" / "Not vaccinated". 

## Expected Benefits
In case the user catches COVID and sends their contact journal to the health authority, they can better asses the risk for the encounters of the person.

----
Internal Tracking-ID: [EXPOSUREAPP-8992](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8992)

**Comment by LukaHarambasic** [comment]
Not sure if that's the expected benefit the author on Twitter mentioned: 

> Die App erkennt dadurch das Risiko besser, ob ein geimpfter oder ungeimpfter infiziert ist.
Bezüglich der Ansteckungrate ist das schon entscheidend...
https://twitter.com/Nobody_see_me/status/1417406339341508635 

Engl. (auto translated)
> The app thus recognizes the risk better, whether a vaccinated or unvaccinated person is infected.
In terms of the infection rate, this is already decisive...

It sounds like that the user assumes that the data from the contact diary is used in the risk calculation. Which isn't and can't be.

**Comment by Ein-Tim** [comment]
@LukaHarambasic 

Yes, I also wondered and thus I wrote my own expected benefit. I'll come back to the Twitter user. 

Edit: I've clarified this: https://twitter.com/eintim2/status/1417420666500964354?s=21

**Comment by WiseWomanVP** [comment]
I don't think this is a good idea, as you would be storing private health information about the vaccination status of a person in your device.

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
