### ISSUE TITLE
"Warn others" function should be deactivated if registered RAT is positive, but registered PCR test is negative

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#596]
## Current Implementation
If a user takes a RAT, registers it in the CWA & it returns positive, it's quite likely that they first go and take a PCR-test before warning others. If the PCR-test is also registered in the app and it then returns negative, the user still has the option to warn others by using the button of the RAT. This does not make sense, since RAT test results are often debunked by PCR-tests. This is also mentioned in the Corona-Warn-App "Machen Sie einen PCR-Test um dieses Ergebnis zu verifizieren".

## Suggested Enhancement
Deactivate the "Warn others" button if there is one negative PCR test in the app and one positive RAT in the app. 

## Expected Benefits
Less false warnings. 

## Screenshot

Here's a screenshot of a friend, which was in this situation just a few days ago:
![Screenshot](https://user-images.githubusercontent.com/67682506/126361429-ec1421cd-f8fd-4f9e-ad28-1d28ca75e1d1.jpg)

----
Internal Tracking-ID: [EXPOSUREAPP-8993](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8993)

**Comment by jucktnich** [comment]
+There should be a check,
- if the PCR-Test was made >24h **before** the RAT you should be able to warn other normally
- if the PCR-Test and the RAT were made in 24h timeframe, everything should be disabled
- if the PCR-Test was made >24h **after** the RAT you should be able to warn only for the time frame between the RAT and the PCR.
The times should be when the test was taken, what probably means the registration time for PCRs

**Comment by fynngodau** [comment]
We should not assume that both tests that can be registered in the app always belong to the same person. For instance, one might scan in a test of another person to retrieve their EU DCC. Therefore, it might be better to display a warning message that advises users against warning others if they have retrieved a negative PCR test (or if the test does not belong to the person who carries the device with them).

**Comment by heinezen** [comment]
Hello everyone,

This feature request has been **declined** because the app does not know the time the PCR test was done. It only knows the registration time. The feature was already discussed when RAT functionality was introduced to the app. However, it was declined by RKI for the reason I mentioned.

----
Corona-Warn-App Open Source Team
