### ISSUE TITLE
Function to sort scanned certificates

### ISSUE THREAD

**Issue by Jo-Achim** [corona-warn-app/cwa-wishlist#598]
## Current implementation

currently there is only the option to sort (display) the scanned certificates: "**Activate this switch if ... and you mainly use the app. Your certificates appear in the first position in the list.**" So also for two certificates, only.

That's nice. But a meaningful sorting fails already from the third, scanned, certificate.
Your own certificate should come first - you can do this with the above switch. But the order of the other certificates is apparently based on the first name... that is not desirable.
**A freely definable order would be desirable.** So... youself comes first, wife and children afterwards ... and - because you need the certifictes less often - the parents / in-laws etc. further down.

Is actually logical and, as I said, would be desirable.

## Possible Fix

While keeping one switch: the first certificate only slides down one position at a time if another certificate is to be the first. In this way, a desired sequence could be achieved, possibly in several steps, if other sorting is dispensed with at the same time.
Example: Currently sorted and displayed order: A, B and C. Desired: A, C and B. => C in first position (= C, A, B) and then A in first position = A, C and B.

Alternatively: directly assign a numerical position in the display sequence to the certificates.

----
Internal Tracking-ID: [EXPOSUREAPP-8995](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8995)

**Comment by heinezen** [comment]
Hello everyone.

This feature request has been **declined** because the implementation would be too complex and require too much effort for the expected benefits. We will not pursue this further.

----
Corona-Warn-App Open Source Team
