### ISSUE TITLE
Spin-off: Weather Alerts via Cell Broadcasting

### ISSUE THREAD

**Issue by gitbrueck** [corona-warn-app/cwa-wishlist#599]
The CWA is a perfect open source project for corona warning purpose. It could be a model for a project to solve the problem of automatic interpretation of weather alerts basing on map informations.
Nowadays we see the weather forecast on the tv screen. But nobody tells us when to leave our home. We need an automatic weather forecast interpretation based on map information.

**Comment by MikeMcC399** [comment]
@gitbrueck 
This doesn't seem like a topic for the Corona-Warn-App wishlist.

Apart from the link https://www.bbk.bund.de/DE/Warnung-Vorsorge/Warn-App-NINA/warn-app-nina_node.html which @dsarkar gave, the Deutscher Wetterdienst [WarnWetter App](https://www.dwd.de/DE/service/dwd-apps/dwdapps_node.html) also provides comprehensive weather warnings according to selected or current location. It includes configurable push notifications to warn users according to selected criteria.

**Comment by gitbrueck** [comment]
@MikeMcC399 
I think of a traditional siren that tells me when to wake up, when to go to the basement, when to close the windows, when to escape. I don't want to make the decision about what to do because of what weather.

@dsarkar 
Yes, I think of an IT firm. CWA is a success story. I think, the CWA-Project could not be extended, because the RKI has nothing to do with weather. Yes, I think you are right, the weather interpretation processor could reside on my phone. Another Approach would be to have a central processor, which sends cell broadcasts.

**Comment by MikeMcC399** [comment]
This is really off-topic and out-of-scope for CWA, but https://www.n-tv.de/politik/Seehofer-Cell-Broadcasting-kommt-wohl-article22695894.html says it is coming.

**Comment by gitbrueck** [comment]
The cell broadcast messages should be interpretable by machines.

The weather interpretation processor should be connectable by google maps. If a message advices to escape, google maps could show possible ways.

**Comment by jucktnich** [comment]
I think, that if the CWA-Project Team would take other Tasks from the German government, they'll also turn into a success story. I guess, this is also what @gitbrueck tries to say

**Comment by gitbrueck** [comment]
Apple and Google invited the German government into the right direction, to the CWA.

Google integrates secure storage of vaccination certificates into Android and starts in the USA.
CWA leads Google in the right direction.

https://www.bloombergquint.com/technology/google-said-to-be-fined-593-million-by-french-antitrust-agency
This drives Google crazy and it drives Germany crazy as well.

**Comment by heinezen** [comment]
Hello everyone,

As others in this thread have said: Talks about potential other projects is out-of-scope for the CWA. We can only discuss CWA development because that is in our scope of influence. I also hope that local and federal governments learn their lessons from CWA development, but we have limited influence on their decisions. Therefore, we will close this issue.

----
Corona-Warn-App Open Source Team
