### ISSUE TITLE
Secondary devices

### ISSUE THREAD

**Issue by RobinKrumm** [corona-warn-app/cwa-wishlist#60]
## Feature description

It would be great to use the cwa also on secondary devices like kind of keychains or wristbands, etc...

## Problem and motivation

Children do not carry their phone the whole day and so they could not use the app correctly.

**Comment by Cube707** [comment]
I find this idea very good. I am carrying my smartwatch much more frequently than my phone, especially since I am able to pay with it.

**Comment by nitramwin** [comment]
Yes, I agree with this feature request.

**Comment by tkowark** [comment]
That’s a good point. In #37 , there is also some more discussion about the implications of that. Since rhis is a duplicate, I‘ll close it but invite you to upvote the existing issue!
