### ISSUE TITLE
Allow users to rename Check-Ins

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#600]
## Current Implementation
The name of the Check-Ins are displayed to all users the way the name was entered by the person who generated the QR code. 

## Suggested Enhancement
Allow users to rename their Check-Ins. 

## Expected Benefits
There are plenty of locations where the name of the location is just "Bäckerei", "Arztpraxis", "Restaurant", etc. 
This can easily get confusing, e.g. if you go to one "Bäckerei" (in CWA called "Bäckerei") and then on the next day to another one which is also just called "Bäckerei".
If the user had the option to rename the Check-Ins (e.g. one "Bäckerei" into "Bäckerei am Bahnhof") it would be clearer for them which location is meant.

----
Internal Tracking-ID: [EXPOSUREAPP-8996](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8996)

**Comment by heinezen** [comment]
Hello,

This feature request was **declined** because it is already possible to add notes to the contact journal entry of an event after it finishes. This is seen as sufficient by the dev team.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@dsarkar @thomasaugsten 

Any chance we could reopen this issue to get this reevaluated now with the situation that users are scanning luca QR codes which have the name "undefined" in it?
It would be nice for users to be able to rename these "undefined" check-ins to something more meaningful.
