### ISSUE TITLE
Support for Google Pay Covid vaccination cards

### ISSUE THREAD

**Issue by DRSchlaubi** [corona-warn-app/cwa-wishlist#603]
## Feature description
As previously requested in Digitaler-Impfnachweis/certification-apis#37, corona-warn-app/cwa-app-ios#2965 and corona-warn-app/cwa-app-android#3486. The original issue on this has been closed due to privacy concerns, that were unfortunately discussed internally, so I can't know if all of them still exists. However since the original issue on this has been closed, Google has released [a new pass type](https://developers.googleblog.com/2021/06/google-updates-passes-api-to-save-covid-testing-and-vaccination-information-on-Android-devices.html) in the passes API specifically, which might solves some concerns? In other open discussions about this, people have been concerned about being able to see the phones Covid certificates even if it's locked, which won't be an issue, since this certificates require a display lock to be set and the phone to be unlocked.

### Documentation links
- https://developers.googleblog.com/2021/06/google-updates-passes-api-to-save-covid-testing-and-vaccination-information-on-Android-devices.html
- https://developers.google.com/pay/passes/guides/pass-verticals/use-cases?vertical=covid-cards
- https://payments.developers.google.com/terms/aup#covid-cards
- https://developers.google.com/android/reference/com/google/android/gms/pay/package-summary

## Problem and motivation
It can come in quite handy to have all of your cards and passes in one place, also having an official way to do this can make use of the new Pass type which is only available to authorities which can actually create vaccination certificates

## Is this something you're interested in working on

Maybe. I am not sure how much I could do as the documentation on Covid certificate is locked behind a registration form only authorities have access to, I would be able to work on the Integration in the App itself since this Documentation is public

**Comment by Ein-Tim** [comment]
@ Community Managers, please move to the Android repository, as this does not affect iOS.

**Comment by DRSchlaubi** [comment]
> @ Community Managers, please move to the Android repository, as this does not affect iOS.

~~This repo is iOS specific?~~

Oh I see this repo is only for issues affecting both Apps. Sorry, my bad

**Comment by Ein-Tim** [comment]
@DRSchlaubi

This repo contains issues that affect both OS, iOS & Android. 

E.g., the [request to be able to add vaccination certificates into the Apple Wallet](https://github.com/corona-warn-app/cwa-app-ios/issues/2965), has been [transferred](https://github.com/corona-warn-app/cwa-app-ios/issues/2965#event-4904573022) to the iOS repository from the wishlist repository, as it does not affect Android.

Same applies here, this request does not affect iOS, so it should be transferred to the Android repository. 

> Oh I see this repo is only for issues affecting both Apps. Sorry, my bad'

Not a problem at all (:

**Comment by heinezen** [comment]
@DRSchlaubi Please repost your comment in https://github.com/corona-warn-app/cwa-app-android/issues/3486 and we'll see if we can reopen the related issue.

----
Corona-Warn-App Open Source Team

**Comment by DRSchlaubi** [comment]
Closed as discussion has been moved back to corona-warn-app/cwa-app-android#3486

**Comment by heinezen** [comment]
Duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/3486
