### ISSUE TITLE
Improve usability for deleting a certificate

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-wishlist#608]
## Current Implementation

This is a follow-on from https://github.com/corona-warn-app/cwa-app-android/issues/3895 "Cannot remove vaccination certificates"

The app does not describe how to remove a certificate and it is not easy to find the remove menu option for a certificate.

### Steps to reproduce

1. In Android CWA tap on "Certificates" tab
2. Tap on three-dot symbol and select "Information"
3. Scroll down to bottom, where it says:<br>"You have the possibility to delete COVID-19 certificates in the app at any time. Until then, the certificates will be stored on your smartphone."<br>There are no instructions here about how to delete a certificate.
4. Tap "CONTINUE" 
5. Tap Scan button and scan in a certificate
6. Note that a three-dot symbol appears which contains a menu option "Delete Certificate"
7. Click back arrow
8. Now there is no menu available to delete a certificate and no help
9. With CWA 2.10.1 and later there is however a right arrow to suggest that there is a detailed level which can be called up

## Suggested Enhancement

- Add some help text about how to delete a certificate
- On the view where multiple certificates are listed provide some more obvious way about how to delete a certificate

## Expected Benefits

- Better user experience. Users should not have to struggle with the simple task of deleting a certificate.

---
Internal Tracking ID: [EXPOSUREAPP-8918](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8918)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for the proposal. Internal Tracking ID: [EXPOSUREAPP-8918](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8918)

**Comment by Ein-Tim** [comment]
@MikeMcC399 

> On the view where multiple certificates are listed provide some more obvious way about how to remove a certificate

Did you know that it's possible to delete certificates from this view? 

Here's a screen recording:

https://user-images.githubusercontent.com/67682506/128846627-0f0da3b2-2fd8-46ae-85ea-3fa07ef15adc.MOV

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Thanks for the iOS recording. That is interesting to see.

On Android there is no swipe function implemented on individual certificates or right arrow displayed. On Android all you can do is to tap on a certificate which brings the details level of the certificate onto the display where there is no plain text button to remove the certificate. You have to know or guess that the remove function is hidden in the three-dot symbol.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Ah okay, interesting to see that this is only implemented under iOS. Although iOS might be a bit better than Android here, the function to remove certificates is still very hidden. 

I hope that the developers find a solution where it's easy for users to remove certificates! Hopefully iOS and Android can also be aligned to each other, this would be nice too!

**Comment by MikeMcC399** [comment]
The in-app documentation and app user interface should be sufficient for users to find how to carry out tasks like removing a certificate.

In the meantime the website FAQs are bridging the information gap:

- https://www.coronawarn.app/en/faq/#eu_dcc_remove "How do I remove a certificate from the Corona-Warn-App?"
- https://www.coronawarn.app/de/faq/#eu_dcc_remove "Wie kann ich ein Zertifikat aus der Corona-Warn-App entfernen?"

That in itself is a problem because the UI has been changed multiple times over versions staring from 2.3 to the current 2.13 and it becomes overly complicated to try to cover all these versions in one article.

See also:
- [x] https://github.com/corona-warn-app/cwa-website/issues/2030
- [x] https://github.com/corona-warn-app/cwa-website/issues/2032

**Comment by MikeMcC399** [comment]
Changed terms from "remove" to "delete" to correspond to CWA Android 2.15.1 UI.
