### ISSUE TITLE
Check whether the version of the EU vaccination certificate used is compatible with country

### ISSUE THREAD

**Issue by Jo-Achim** [corona-warn-app/cwa-wishlist#609]
## Current Implementation
CWA 2.6.1: No check to ensure that the EU vaccination certificate used is up-to-date.

## Suggested Enhancement
The validity check of an EU vaccination certificate stored in the CWA for a destination country can be negative.

_Example:_
![Screenshot_20210809-102558_Corona-Warn_2](https://user-images.githubusercontent.com/21124877/128832876-21aeafe3-72ff-432f-8d57-77e04551e915.jpg)

If this is the case, it would be desirable if it were then also checked whether the EU vaccination certificate used for the test itself corresponds to the current version.
If not, this should be communicated to the user in a suitable form, including the instruction to renew the EU vaccination certificate and then repeat the validity check.

Cross reference: https://github.com/corona-warn-app/cwa-documentation/issues/679#issuecomment-895154648... 
## **Possible Fixes:**

If relevant, the CWA could even check itself whether the stored certificates are stored in the current version of certificate.

## Expected Benefits
Avoidance of false negative EU certificate checks due to outdated certificate versions. 
And thus an increase in the quality of the test result. 

----
Internal Tracking-ID: [EXPOSUREAPP-9051](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9051)

**Comment by heinezen** [comment]
Hello everyone,

This feature was implemented in CWA release 2.7. We consider it solved.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@heinezen 

Not sure about that, where does the app check which schema version a certificate uses? And where does the app show this information to the user?

**Comment by MikeMcC399** [comment]
@heinezen 
> This feature was implemented in CWA release 2.7. We consider it solved.

CWA 2.7 implements the display of the technical expiration date (see https://www.coronawarn.app/en/blog/2021-08-16-cwa-version-2-7/).

I can't see anything in the above blog post which talks about a special check of a certificate schema version against a country's Business Rules. I believe it is the responsibility of the country providing the business rules to ensure that they handle all currently valid certificate schema versions correctly.

Note that this wishlist item is linked to the open issue https://github.com/corona-warn-app/cwa-documentation/issues/679 "[Business Rules Validation]Business Rules "passed" not displayed in "open status screen" when some schema versions do not match" from @vaubaehn.

You might like to check whether the reason you have given for closing this wishlist item is correct or not.

**Comment by Jo-Achim** [comment]
> 
> 
> @heinezen
> 
> You might like to check whether the reason you have given for closing this wishlist item is correct or not.

Thank you, @MikeMcC399.
