### ISSUE TITLE
[Solved?] Optimized Synchronization of Central Notifications Database Update with Timing of Automatic Download to Devices

### ISSUE THREAD

**Issue by seppf** [corona-warn-app/cwa-wishlist#61]
Now that the first datasets of notifications of positiv testing are available, it seems that synchronization of database update and automatic download possibly could be optimized. It seems that daily update is available some time after midnight, but automatic downloads sometimes already start before midnight. In this case new datasets would arrive at cwa and be evaluated to calculate the risk of infection only the next automatic download one day later.
However, the information about a possible infection should be available as soon as possible.
If observation is correct, changing the schedule of upload / download could improve the effectivness of the cwa.
Either the update of the database should be earlier (e.g. 10 pm) or the automatic download should start later (e.g. 2 am).
If resources are no issue, a more often update / download schedule should be considered (e.g. twice or three times a day).
If there are not sufficient new real infection contact notifications, faked (i.e. dummy) could be used for stuffing to keep data privacy.
(Observation is based on an cwa running on an Android v9)
Thanks for considering my suggestion. 
Kind Regards, seppf

------
Internal Tracking ID: EXPOSUREAPP-2138

**Comment by ST4YHealthy** [comment]
Can somebody please explain, why faked (i.e. dummy) data would keep data privacy ?
I would like to understand why the RandomIDCount could NOT fit the exact and correct value! Whos privacy could be affected in a negative way???

**Comment by dsarkar** [comment]
Hi @seppf, 

Thanks for your suggestion. However, now with CWA version 1.7.1 we think that this issue has been resolved. See here https://www.coronawarn.app/en/faq/#risk_update_24 and here https://www.coronawarn.app/en/blog/2020-11-25-corona-warn-app-version-1-7/.

We suggest closing this issue. 

Best wishes,
DS

---
Corona-Warn-App Open Source Team
