### ISSUE TITLE
Schnelltestportal:Feedback und Verbesserungsvorschläge aus der Praxis

### ISSUE THREAD

**Issue by konradherz** [corona-warn-app/cwa-wishlist#614]
Hallo,
Ich bin neu hier und möchte aus der Praxis der schnelltestdurchführung Verbesserungsvorschläge unterbreiten:
Bei der Erfassung der Daten der Probanden wird immer nach dem standardisierten Namen gefragt, es ist notwendig, Vor- und Nachnamen 2 Mal einzutragen, auch wenn der erfasste Name eine Umlaute bzw. Sonderzeichen enthält. Kann das nicht so programmiert werden, dass diese Eingabe nur notwendig ist, wenn Zeichen abweichend von ICAO Standard vorkommen?
Ein zweiter Vorschlag ist, nach der Erfassung der per. Daten vor Verlassen der Eingabemaske noch einmal darauf hinzuweisen, dass die Proben-ID notiert werden muss. Auch wäre es sinnvoll, die Anzeige dieser ID farblich hervorzuheben.
Keine Ahnung, ob ich hier richtig bin, um das zu platzieren, aber einen Versuch war es wert.
Liebe Grüße
K. Herz

**Comment by dsarkar** [comment]
@konradherz Danke für Frage. Sollte es um das CWA Schnelltestportal gehen (https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki/CWA-Schnelltest-Portal), dann ist dieses Issue hier besser platziert: https://github.com/corona-warn-app/cwa-quick-test-frontend/issues

---
Corona-Warn-App Open Source Team

**Comment by konradherz** [comment]
Hallo, 
können Sie das dorthin verschieben?

**Comment by konradherz** [comment]
Verschoben und schnelltestportal
