### ISSUE TITLE
Change icon of CWA when fully vaccinated (add a ✅ or similar)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#617]
## Current Implementation
The icon of the Corona-Warn-App stays unchanged even if the fully vaccinated status is reached.

## Suggested Enhancement
Change the icon of the Corona-Warn-App as soon as the fully vaccinated status is reached. Add a ✅ or similar.

## Expected Benefits
Improved user experience. 
From Twitter (German only):
"Einfach nur ein netter Anreiz / Belohnung. Sozusagen ein kostenloser In-App Kauf Zeigefinger nach oben Die Impfung IST auch ein wenig Verkauf, wie man sieht." 
&
"Verkaufspsychologisch ist es einfach Fakt, dass ein Anreizsystem, welches auf positiver Verstärkung beruht, besser funktioniert als das dröge hineindozieren von Fakten."

## Additional information
This issue is based on the feedback I got from a Twitter user: https://twitter.com/Balou_DA/status/1426110388312186886?s=20

----
Internal Tracking-ID: [EXPOSUREAPP-9056](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9056)

**Comment by fynngodau** [comment]
I think this is a funny idea.

On Android this is possible by creating an [`<activity-alias>`](https://developer.android.com/guide/topics/manifest/activity-alias-element) and [enabling and disabling it](https://stackoverflow.com/questions/6408086/android-can-i-enable-disable-an-activitys-intent-filter-programmatically). See https://stackoverflow.com/questions/1103027/how-to-change-an-application-icon-programmatically-in-android#15249542. However this might unfortunately not work reliably on all devices.

@Ein-Tim I think this should be added to the gamification overview as well.

**Comment by heinezen** [comment]
Hello everyone,

This feature request was **declined** to prrevent misuse of the app as a validator app. Nobody should be encouraged to look for a green checkmark and decide, that this certificate is valid. The check shuld only be done in CovPassCheck.

----
Corona-Warn-App Open Source Team
