### ISSUE TITLE
Local 7-day incidence maps: Provision of additional information (warning levels, etc.)

### ISSUE THREAD

**Issue by Jo-Achim** [corona-warn-app/cwa-wishlist#618]
## Current Implementation
"Local 7-day incidence" maps available; CWA 2.6.1. 
Extensions regarding the display of local 'warning levels' and 'corresponding information on corona restrictions'...

## Suggested Enhancement
Extension of the “Local 7-day incidence” cards information from the CWA with the information: '“Warning level:" x'.
('"Warning level:" x' would be comparable to the '"Warning level:" x' - Info under NINA.)

_Examples:_
New informations on "Local 7-day incidence" cards:
![Screenshot_20210813-102128_3](https://user-images.githubusercontent.com/21124877/129344970-a79416f5-109b-4a71-9ccd-bdc9dae3404f.jpg)

... and the additional information about this (via link) ...
![Screenshot_20210813-102128_3i](https://user-images.githubusercontent.com/21124877/129345237-626407db-e43d-4b4c-bc13-b17e4500f5b9.jpg)

The user should be shown the current, location-specific (daily) 'warning level' on the “Local 7-day incidence” maps.
Via [3-dot-menu] of "Local 7-day incidence" maps, he should be able to access the 'corona restrictions' applicable in this regard via a "Link" displayed there.
The "Link" could open a page of the RKI or other official sources with the 'corona restrictions' applicable according to the 'warning level'. (NINA allegedly obtains the information and texts displayed from the dpa.)

## Expected Benefits
As a result, the user of the CWA should be able to find out about 'warning levels' and 'corona restrictions' in their home district, neighboring communities / districts, ... (German) federal states. (See "Additional context" too.)

## Additional context
Politicians are currently discussing the sole value of 'incidences' and would also like to include hospitalizations etc. in future "Corona assessments" and derive corresponding corona restrictions from them. And these restrictions should apply locally.
This also means, however, that current information about location-specific valid 'warning levels' and 'corresponding restrictions' will become increasingly difficult to find.

Here the CWA could provide additional, very helpful and valuable services, especially in the existing context of “travel”.
(Possible cross-reference: https://github.com/corona-warn-app/cwa-wishlist/issues/615#issue-969541517.)

Best regards, Joachim.

----
Internal Tracking-ID: [EXPOSUREAPP-9057](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9057)

**Comment by jucktnich** [comment]
Related: #430 especially #151

**Comment by Ein-Tim** [comment]
@Jo-Achim 

FYI: In it's latest update (version 3.4.0) NINA removed the warning levels, and instead, just shows the 7-day-incidence. 

How would you like to proceed with this issue now?

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> FYI: In it's latest update (version 3.4.0) NINA removed the warning levels, and instead, just shows the 7-day-incidence.

On Android I don't see NINA 3.4.0 yet. ~~I assume this is a staged rollout, since~~ on iOS 3.4.0 appeared only today.

**Comment by heinezen** [comment]
Hello everyone,

This feature request was **declined** by stakeholders because the feature is a responsibility of NINA rather than the CWA.

----
Corona-Warn-App Open Source Team

**Comment by Jo-Achim** [comment]
> 
> @Jo-Achim
> 
> How would you like to proceed with this issue now?

The answer is currently difficult.
On the one hand, it may be that the "warning levels" no longer have any meaning. On the other hand - even as things stand now - the incidence values will only be of limited informative value because they are to be combined with local occupancy figures in the hospitals / intensive care units.

Against this background, it seems to me that many new approaches are necessary. Because my goal was originally to give the CWA user an indication of the applicable rules of conduct.
Perhaps it makes sense in Germany to implement a link to NINA within the CWA; if necessary, directly to the installed NINA app (and if NINA provides the necessary information). 

Best regards, Joachim.

**Comment by Jo-Achim** [comment]
> 
> 
> > @Jo-Achim
> > How would you like to proceed with this issue now?
> 
> The answer is currently difficult.
> On the one hand, it may be that the "warning levels" no longer have any meaning. On the other hand - even as things stand now - the incidence values will only be of limited informative value because they are to be combined with local occupancy figures in the hospitals / intensive care units.
> 
> Against this background, it seems to me that many new approaches are necessary. Because my goal was originally to give the CWA user an indication of the applicable rules of conduct.
 
So I will add a link to a Bavarian [Krankenhaus-Ampel](https://www.stmgp.bayern.de/coronavirus#kh-ampel) ('Hospital traffic light') as example.

Best regards, Joachim.

**Comment by Jo-Achim** [comment]
> 
> 
> @Ein-Tim
> 
> > FYI: In it's latest update (version 3.4.0) NINA removed the warning levels, and instead, just shows the 7-day-incidence.
> 
> On Android I don't see NINA 3.4.0 yet. I assume this is a staged rollout, since on iOS 3.4.0 appeared only today.

On Android, NINA version 3.3.3 (Build 3382) is still up-to-date today.

**Comment by MikeMcC399** [comment]
NINA just informed me that the 112 emergency service number is out-of-service throughout Germany. 🙁 

It also told me that an update is available, so now NINA Android is on 3.4.0 https://play.google.com/store/apps/details?id=de.materna.bbk.mobile.app&hl=en&gl=US
