### ISSUE TITLE
Add Home Screen widget for EU digital COVID certificates

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#619]
## Current Implementation
There are no Home Screen widget for CWA at all.

## Suggested Enhancement
Add a Home Screen widget for EU digital COVID certificates.

## Expected Benefits
The user does not have to open the Corona-Warn-App and click on the certificates tab to show their certificate, but instead can just perform the one time action to add the CWA EU DCC widget to their Home Screen and can always quickly access their selected COVID certificate. 

## Additional information
This report is based on feedback from a Twitter user: https://twitter.com/alvinthecalvin/status/1426408490969489413?s=20

---

## Related issues
- #13
- #26

----
Internal Tracking-ID: [EXPOSUREAPP-9058](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9058)

**Comment by jucktnich** [comment]
A quick action to access your certificate should be implemented first, but I guess that's something for another issue.

**Comment by Ein-Tim** [comment]
@jucktnich This is covered by #504.

**Comment by fynngodau** [comment]
(To be honest, widgets are terrible to implement on Android. But I think it's a good idea!)

**Comment by jucktnich** [comment]
Implementing iOS 14 widgets is relatively easy IMO. So this would compensate it 😉.

**Comment by TillJohanndeiter** [comment]
Is this feature still relevant? I would like to work on the android implementation

**Comment by fynngodau** [comment]
@TillJohanndeiter It still seems like a good addition to me!

Management around the official Corona-Warn-App can be very slow with deciding whether or not they want a certain feature even if the pull requests are available, so it's better not to start working unless official confirmation is available.

But if you are interested and do want to start working on this right away, I would definetly merge this into CCTG, so we could already ship the feature there while CWA decides upon your PR.

**Comment by larswmh** [comment]
Closing this issue as the related internal ticket was set to `obsolete`.

Developer comment:

> This was rejected because of budget restrictions from stakeholders many times already.
