### ISSUE TITLE
UI improvement: Make the Certificates tab easier to understand

### ISSUE THREAD

**Issue by Chanator** [corona-warn-app/cwa-wishlist#622]
## Current Implementation

Under "Zertifikate" one only sees the QR code of the currently chosen certificate, and the option to add a new certificate.

## Suggested Enhancement

Two options:
1) Add a button with the same functionality as clicking on the QR code. (It leads to the detailed page of all your certificates)
2) Add a text label, or some other visual indicator, that tells the user that clicking on the QR code leads to more detailed information.

## Expected Benefits

Implementing at least one of the two options would save a lot of frustration and time for some demographics.

My father spent more than hour searching the app and the FAQ-section on what he has to do if he needs to show his certificate, and where his certificate details are. He was practically fuming and cursing in the end since he couldn't find anything describing it.

It is intuitive to us developers and people who grew up with smartphones, that the QR code displayed is touchable and also contains all the information you need to show. But for people who may have just gotten a smartphone and don't know much about tech, this is not so.

----
Internal Tracking-ID: [EXPOSUREAPP-9130](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9130) iOS
Internal Tracking-ID: [EXPOSUREAPP-9200](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9200) Android

**Comment by alanrick** [comment]
In Austria, they religiously check you’ve received a 2nd jab (I know - they should check the validity of the certificate using Cov Check or equivalent instead but that’s the way it is). My CWA was “verified” at least 15 times in restaurants and hotels.  To check the 2 jabs the waiter/waitress has to 
a) navigate into the certificate details,
b) Scroll down,
c) go back to repeat this for my partner’s certificate.

I’d prefer the main view of the eu certificate to include an extra summary line below the name to include:
count of jabs, name of last vaccine type and (maybe)  date of last jab. This would remove the need for extra navigation. 
Scrolling up and down would be all that’s needed for all family members.

**Comment by heinezen** [comment]
Hello everyone,

UI improvements for this particular issue are planned for CWA release 2.10. The certificates tab will receive visual indicators to signify that there is more information.

----
Corona-Warn-App Open Source Team

**Comment by alanrick** [comment]
So will it show the essential summary as illustrated in this screenshot from iOS wallet or will it simply indicate that to see the summary you have to navigate deeper?
![9F2C4634-6583-45AD-BABE-1C83452AAEC3](https://user-images.githubusercontent.com/7034358/132234559-c3a4b1f3-4563-42e6-bcc7-36d4b861c07d.jpeg)

**Comment by alanrick** [comment]
Hilarious experience using a paper hard copy of a screenshot of the 2.8.1 CWA rendering of the EU certificate. 

1. I showed it to the person controlling entry at the 2G Ludwigshafen Film  Festival (where film tickets are controlled by scanning a qr code on the ticket)
2. Controller explained it wasn’t valid because it only showed my name and not the date of the last injection. 
3. I explained that’s embedded in the qr code and she needed to use covcheck to validate my print-out. Neither controller had heard of the app or had a mobile with them (allegedly).
4. I whipped out mine, scanned the code with covcheck and showed the green status.
5. She explained that’s still not sufficient because the date of the last jab is still not displayed (covcheck design decision )
6. I was about to answer when the controller lost interest and let me in. 

I’ll try again tonight with a print-out of my Apple Wallet rendering.

**Comment by ndegendogo** [comment]
***Nowadays everybody designs their solutions using apps** ... assuming "everybody" owns a (modern!) smartphone, and the minority who don't can be neglected  ... I am not so sure if that was a wise design decision of CovPass (or rather of the "European Health Certificate standardisation group") ...*

Lets assume I was working at a border control, as doorkeeper of an event, or similar role. What does my employer expect - that I load the Verifier app to my **private** device and use that to fulfil my work? Or will my employers buy work smartphones for everybody?

**Comment by jucktnich** [comment]
I mean you could use those qr scanning devices, you can buy them for 2€/piece

**Comment by ndegendogo** [comment]
@jucktnich .. and the CovPass verifier is supposed to run on those 2€ scanners??

**Comment by Ein-Tim** [comment]
FYI: This is how they will improve the situation @Chanator:
![image](https://user-images.githubusercontent.com/67682506/132311500-bf037c19-82e5-4f4e-8518-da94675abf78.jpeg)

Screenshot from https://github.com/corona-warn-app/cwa-app-ios/pull/3479

**Comment by jucktnich** [comment]
@ndegendogo if you can code, yes

**Comment by ndegendogo** [comment]
@jucktnich this is what I mean. The covPass developers can code for sure, but they are rolling out the verifier app for *smartphones*. And iirc only for *modern* smartphones, excluding Android 5 and the like.
The *average doorkeeper* is not supposed to be able to code.
And the "official" verifier app needs to be deployed "ready-made" (and signed by the owner = BMG); not a self-compiled version that could theoretically have all sorts of modifications, including malicious.

**Comment by jucktnich** [comment]
@ndegendogo A qr code scanner distributed by the bmg would be helpful, maybe that's possible?

**Comment by ndegendogo** [comment]
@jucktnich very good idea!!

**Comment by jucktnich** [comment]
@ndegendogo an idea would be to build a covcheck website, so you
1. don't need to install something and
2. virtually every smartphone would be supported.

**Comment by ndegendogo** [comment]
@jucktnich I am not sure if I understand this idea ... how would this work?

**Comment by jucktnich** [comment]
@ndegendogo this is a separate idea from the scanner

**Comment by alanrick** [comment]
> I’ll try again tonight with a print-out of my Apple Wallet rendering. 

The controllers at the FFLU accepted the Apple Wallet screenshot Print-out immediately without question.  

I'm not convinced about the value of the ">" sign over an additional line of data. Particularly as there no shortage of vertical screen estate on mobile devices. In Practice, the data would eliminate the need for navigation.

**Comment by Chanator** [comment]
> 
> 
> FYI: This is how they will improve the situation @Chanator:
> ![image](https://user-images.githubusercontent.com/67682506/132311500-bf037c19-82e5-4f4e-8518-da94675abf78.jpeg)
> 
> Screenshot from [corona-warn-app/cwa-app-ios#3479](https://github.com/corona-warn-app/cwa-app-ios/pull/3479)

Thanks for letting me know.

It is an improvement and I appreciate that they take feedback and suggestions.

Personally I would add "Tap for more details" below the QR-code, but I understand that this would need to be translated and wouldn't be as elegant.

**Comment by Ein-Tim** [comment]
@Chanator 

This has now been implemented in version 2.10, which has been released today. Do you consider this as implemented? Or do you think that it's still not obvious enough? 

If you consider this as implemented I'd like to ask you to close this issue. 

Thanks!

**Comment by Chanator** [comment]
> 
> 
> @Chanator
> 
> This has now been implemented in version 2.10, which has been released today. Do you consider this as implemented? Or do you think that it's still not obvious enough?
> 
> If you consider this as implemented I'd like to ask you to close this issue.
> 
> Thanks!

I think that it is still not obvious enough. I would suggest adding "Tap for more details" below the QR-code, translated for each supported language.

If this gets rejected, the issue can be closed.

**Comment by Ein-Tim** [comment]
@Chanator 

Okay, thanks for the feedback!

@dsarkar Please decide how to continue with this issue (espacially @Chanator's [last comment](https://github.com/corona-warn-app/cwa-wishlist/issues/622#issuecomment-925167711)).
Will you create a new Internal Tracking ID for this proposal, or do you want @Chantor to open a new issue?

**Comment by MikeMcC399** [comment]
Just for reference, the screenshots for CWA 2.10 Android on https://www.coronawarn.app/en/screenshots/#android_certificates show the new right-arrow and the news line too (if applicable):

![image](https://user-images.githubusercontent.com/66998419/134806811-1a3a3406-33c5-4d72-8a04-f62fbb83fa2f.png)

Right-arrows are used generally in the app to indicate that there is more information available e.g.
- on the risk tile
- on Manage Your Tests, for instance to Scan QR Code
- in the Contact Journal for the details of each day

Arrows (back and forward) and X (to cancel) symbols are common language-independent navigational elements. I guess we assume that users should be familiar with using them.

**Comment by alanrick** [comment]
Looks great. Will the arrow replace the greater-than sign in the iOS version, too?

**Comment by Ein-Tim** [comment]
@alanrick 

The ">" is the arrow under iOS, you can also see that on the start side. 
Native iOS apps (like Health) also use the ">" and not an arrow.

**Comment by alanrick** [comment]
Thanks.  I’d seen that in one line text menus (like “See All>” ) but hadn’t noticed that elsewhere.

**Comment by Ein-Tim** [comment]
I recommend to close this issue @Chanator.

As @MikeMcC399 laid out in [his comment](https://github.com/corona-warn-app/cwa-wishlist/issues/622#issuecomment-927294634), arrows are an typical UI element which most users will understand means that by tapping on the respective field will reveal further details.

We did no hear any feedback on the suggestion you made in https://github.com/corona-warn-app/cwa-wishlist/issues/622#issuecomment-925167711 from the Open-Soruce-Team yet, thus I recommend to follow up in a new issue if necessary. 

Thank you!

**Comment by dsarkar** [comment]
@Chanator Thanks for contributing here!
@Ein-Tim Thanks for the "ping".
