### ISSUE TITLE
Add a box "This is my test" when registering a test in the app

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#623]
## Feature description

Based on the discussion we had in https://github.com/corona-warn-app/cwa-website/issues/1626 & https://github.com/corona-warn-app/cwa-documentation/issues/685 @dsarkar [came up](https://github.com/corona-warn-app/cwa-website/issues/1626#issuecomment-900045590) with the idea to extend the process of registering a test in the app with a check box "This is my test". 
Basically, the idea is to make it more safe to receive test results from other persons (e.g. family members, children without a mobile, elderly people, etc.) in case the test result returns positive. 
The process would be like this:

Before the "Your Consent" screen a screen "Is this your test?" is shown which has a tick box to confirm that this test is for me or, when unticked, that this test is not from me. In the case that you untick the "This is my test" box the "Your Consent" screen is skipped and CWA does not request access to RPIs. If the test result returns positive, CWA does not offer to warn other people, since it wasn't the device owner who tested positive.

## Problem and motivation
There are quite many people using the CWA as a EU DCC generator, for their own tests but also for tests from friends & family. At the moment, if the user does not explicitly disallow CWA to access RPIs, CWA would warn the contacts of the user automatically, even though it might not be the device owner (who carried around the device with them most of the time) who tested positive. 
With a "This is my test" box this problem would be tackled and false warnings would be avoided, while still making it as easy as possible for users to generate EU DCCs for other people. 

---
Internal Tracking ID: [EXPOSUREAPP-9042](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9042)

**Comment by jucktnich** [comment]
+if the CWA sometime will support multiple tests, you should only be able to tick the box once. This would mitigate the problem stated in another issue about multiple tests, that you may be able to pile up tests and warn to often.

**Comment by dsarkar** [comment]
@jucktnich Actually, very interesting idea! Thanks.

**Comment by ndegendogo** [comment]
> +if the CWA sometime will support multiple tests, you should only be able to tick the box once.

@jucktnich what will be the flow if I forget to tick the box when I scan my own test? Do you suggest that I somehow can edit and tick the box later? Or do I then need to delete the test and scan it again? 
*... wait - this it not possible, right?*

**Comment by jucktnich** [comment]
This should not be some box you can tick more a popup, where you can say it's my test and no it's not my test. +There should be a text explaining, that you can't change it later.

**Comment by Ein-Tim** [comment]
And, additionally, I'd say, by default, the box ("This is my test") is ticked.

**Comment by ndegendogo** [comment]
@Ein-Tim not sure that this is a good default.
Given that this is an **uncorrectable** decision - how many people will then accidentally register other tests as their own, and notice too late?

**Comment by Ein-Tim** [comment]
@ndegendogo 

I consider it as worse if the device owner is not able to warn their contacts because they forgot to tick the box than registering tests from other people and accidentally warn your contacts. 
Do you have a different opinion on this?

**Comment by ndegendogo** [comment]
@Ein-Tim well, actually I am unhappy with both variants of default.
And I am also unhappy with no default, and **force** the user to decide -> too complicated.

And in truth I am unhappy with the fact that it is **final** and a wrong click cannot be corrected.

What is the issue if we allow editing here? (besides of the higher effort to implement it)

**Comment by Ein-Tim** [comment]
IHMO we could allow editing here. At the end the devs/stakeholders would decide this.

**Comment by ndegendogo** [comment]
> IHMO we could allow editing here. At the end the devs/stakeholders would decide this.

In that case I am **very happy** with default "my test". After all, in most cases this will be true. 😀

**Comment by ndegendogo** [comment]
And just an anecdotical story how creative some people are using cwa.
I know the mother of a very young child. Both parents were proud cwa users (of course the girl not 😀). Then the girl picked it up in the KiTa.
And the mother scanned the positive PCR test into **her** device and warned others.

**Comment by jucktnich** [comment]
@ndegendogo if you can change it later, the whole point with you can't pile tests up vanishes.

**Comment by vaubaehn** [comment]
Some additional thoughts:
Instead if a tick/check box, there could be 2 options/radio buttons. No default is selected. You will need to choose one option, before the continue button gets activated.

There are some caveats:
Editing the chosen option will be difficult, when the 'release TEKs in case of positive test'-in-advance right will be granted to the ENS, I think. Don't know if API can change it, when later a different option/test holder is selected.

About piling up tests: iirc, ENS limits the number of times, TEKs can be released. I can't remember the numbers, but I think it was something like once per day or once per six days... I'm too tired to look it up now, can try tomorrow.

**Comment by jucktnich** [comment]
@vaubaehn
> This should not be some box you can tick more a popup, where you can say it's my test and no it's not my test. +There should be a text explaining, that you can't change it later.

I guess this was "rejected" by @ndegendogo ?

**Comment by ndegendogo** [comment]
> I guess this was "rejected" by @ndegendogo ?

I still remember well how much we strived to make the core flow of cwa - share my keys and warning others - as simple and straightforward as possible. And I am afraid that each additional click could be contraproductive to this goal.

But of course I am just discussing here like everybody else; and not in a position to "reject" proposals 😅 - this is up to the product owner (RKI).

**Comment by jucktnich** [comment]
@ndegendogo I hadn't had a better word. any ideas what I could use instead?

**Comment by ndegendogo** [comment]
@jucktnich 😅😅😅
no, your wording is just fine
maybe "opposed" could be an alternate wording

**Comment by vaubaehn** [comment]
I'm currently thinking about proposing a concrete solution for a multiple user environment for storing tests also for family members. I know that #200 and #109 already have been declined. But the solution I'm thinking about would circumvent problems explained in #200 and #109 and also would make this issue here (#623) obsolete.
Hope I can manage next week.

**Comment by Ein-Tim** [comment]
This has been implemented in version 2.21: [Corona-Warn-App Version 2.21 now allows test management for family members](https://www.coronawarn.app/en/blog/2022-04-19-cwa-2-21/).

I'm closing this issue as implemented now.
