### ISSUE TITLE
Twitter Suggestion: Make it possible to see 7-day-incidences of other EU countries

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#624]
## Current Implementation
At the moment the user can only see the 7-day-incidences of districts & federal states in Germany and the incidence of the whole country.

## Suggested Enhancement
Give the user the option to add the 7-day-incidences of other EU countries.

## Expected Benefits
The user can find relevant information directly in their Corona-Warn-App. Also, the possibility to view the incidence of other countries could help the user to make a better decision to which country it's safe to travel at the moment.

## Additional information

1. This report is based on feedback I received from a Twitter user: https://twitter.com/bleickard/status/1427611271554285572?s=20
2. The user told me that he wishes that he could also select districts for other countries, however, as I regard this as not feasible for the Corona-Warn-App, I did not include this in the text above.

---
Internal Tracking ID: [EXPOSUREAPP-13520](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13520)

**Comment by Ein-Tim** [comment]
This issue was not even mirrored to JIRA. Please mirror it to JIRA, thanks.

**Comment by Ein-Tim** [comment]
This issue was not mirrored to JIRA in nearly one year (!). Why @dsarkar, @larswmh?

**Comment by larswmh** [comment]
Thanks for your enhancement request @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-13520](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13520)

> This issue was not mirrored to JIRA in nearly one year (!). Why @dsarkar, @larswmh?

The issues unfortunately snowed under, but we're getting back to all the issues you're mentioning us in now. Sorry for the inconvenience.

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Thank you @larswmh! Appreciate it and no problem!

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
