### ISSUE TITLE
EU DCC: Support booster vaccinations

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#626]
## Current Implementation
It is not possible to add booster vaccinations (3rd shot) into the Corona-Warn-App. 
See: https://twitter.com/coronawarnapp/status/1428599023397744643?s=21

## Suggested Enhancement
Support booster vaccinations.

## Expected Benefits
Certificates for all vaccination shots, not only the first two.

---

## Related Issue
- https://github.com/Digitaler-Impfnachweis/certification-apis/discussions/178

Related Internal Tracking IDs: 

Internal Tracking ID: [EXPOSUREAPP-9035](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9035)
Internal Tracking ID: [EXPOSUREAPP-9041](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9041)
Internal Tracking ID: [EXPOSUREAPP-8808](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8808)
Internal Tracking ID: EXPOSUREBACK-1448

**Comment by dsarkar** [comment]
@Ein-Tim Thanks. 

Work is planned on:

- **Show booster vaccinations in certificates list**
Internal Tracking ID: [EXPOSUREAPP-9035](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9035) iOS 
Internal Tracking ID: [EXPOSUREAPP-9041](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9041) Android

- **[iOS][Android] Notification settings for booster vaccination**
Internal Tracking ID: [EXPOSUREAPP-](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8808) iOS, Android

- **[iOS][Android] Notify CWA users about required booster vaccination**
Internal Tracking ID: [EXPOSUREAPP-8718](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8718)

- **distribute config, which tells the client to inform user, when next vaccination dosis should be taken**
EXPOSUREBACK-1484

**Comment by vaubaehn** [comment]
There will most likely be some problems with business rule validation:
https://github.com/corona-warn-app/cwa-app-android/pull/3988#issuecomment-907382808

**Comment by RalphRichter** [comment]
Adding a EU Covid Cert for the 3rd vaccination to CWA works, but it can not be validated in Germany. looks like the rule of the frameworks not updated yet. The German CovPassCheck-App is saying --> certificate invalid, The Swiss and Luxembourg one recognizes it as valid. 

If I do the check with CWA it is saying not Valid

Please address and Update [https://www.coronawarn.app/de/faq/#vac_cert_booster_cwa](https://www.coronawarn.app/de/faq/#vac_cert_booster_cwa)

After having a complete vaccination 2nd more than 14 days ago .... 3rd should not show this like in the picture

![IMG_0019](https://user-images.githubusercontent.com/67153468/133979758-b134cf88-6d5d-453a-9835-ec66800e8c5b.PNG)

**Comment by thomasaugsten** [comment]
The german rule will be updated as soon as possible.

**Comment by Ein-Tim** [comment]
I'll close this issue now, as this has been implemented in the latest release. 

For the issue @RalphRichter mentioned please monitor https://github.com/corona-warn-app/cwa-documentation/issues/709.

Closing as implemented (CWA version 2.9).
