### ISSUE TITLE
Integrate the digital registration on entry in the CWA & add a "Registration Profile"

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#627]
## Feature description

The digital registration on entry, which is currently only available on https://www.einreiseanmeldung.de, should be integrated in the app.
As the page https://www.einreiseanmeldung.de/#/ shows: 

"
This website is published by

Robert Koch Institute
Nordufer 20
13353 Berlin
represented by the President
"

I guess there should be no legal problems in integrating a page published by the RKI into an app published by the RKI. 

Additionally, the Corona-Warn-App should include a feature to store the for the digital registration on entry required data and the user should be able to select this data as a "auto fill out". 
If required, the Corona-Warn-App should offer an option to securely upload a digital COVID certificate.

## Problem and motivation
Currently, the process of filling in the digital registration on entry has to be done every time somebody wants to enter Germany from a high risk or a virus variants area. There is no option to create an account or similar. The Corona-Warn-App could make the process a lot easier and help users to register their entry to Germany.

## Additional information
This issue is partly based on feature requests from Twitter users ([here](https://twitter.com/bleickard/status/1427611271554285572?s=20) & [here](https://twitter.com/DanRo__/status/1427626741032423436?s=20)), but I added some more ideas to it (thus no "Twitter Suggestion:" in the title).

Internal Tracking ID: [EXPOSUREAPP-13521](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13521)

**Comment by Ein-Tim** [comment]
This issue is nearly 10 months old and was never mirrored to JIRA. Please mirror it to JIRA now.

**Comment by Ein-Tim** [comment]
Please mirror this issue to JIRA now @dsarkar / @larswmh.

**Comment by larswmh** [comment]
Thanks for your feature request @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-13521](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13521)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
The page https://www.einreiseanmeldung.de doesn't exist anymore, this issue is therefore obsolete.
