### ISSUE TITLE
Don't show the "Check Validity" button after importing a certificate

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#628]
## Current Implementation
Currently, after importing a certificate in the by scanning a QR code, this is the screen a user sees:
<img src="https://user-images.githubusercontent.com/67682506/130323938-3ceaff46-4eed-4bc7-9b31-64f64e712b5f.jpeg" width="300">

## Suggested Enhancement
Don't show the "Check Validity" button so prominently, show another screen or make it more clear that the Validity Check is only for intended to be used if one wants to travel ("Check Validity in other Countries").

## Expected Benefits
I was able to observe that many people click on the "Check Validity" button because they think this will give them a confirmation that their certificate was issued correctly or so. 
When they notice that they have to enter a country, they are often confused and wonder why they have to do this. 
Only after an explanation from me they understood what this button does. 
So the expected benefit is less user confusion & better UX.

----
Internal Tracking-ID: [EXPOSUREAPP-9300](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9300)

**Comment by heinezen** [comment]
Hey @Ein-Tim ,

Thanks for your suggestion. I've passed the information the developers. We are currrently working on investigating a lot of similar UX issues, so I hope this will be part of the larger UI overhaul in the next releases.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
As the button was renamed to "Check Validity for Travel" I don't see this problem anymore so this issue is obsolete now.
