### ISSUE TITLE
Twitter Suggestion: Add a new tab "Tests"

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#629]
## Feature description

A new tab called "Tests" should be added to the tab bar. It would basically show the "Manage Your Tests" screen which we already know from the Home Screen. The "Manage Your Tests" box would be removed from the home screen. 

## Problem and motivation
Currently, the Home Screen is very packed with very different features, the exposure logging, the risk status, the tests, the statistics, the event QR code creation box and some other stuff. 
To give the Home Screen a clearer look, the test box should be moved to it's own tab and the "Planning an event?" box should be merged with the "Check-In" tab (#469)

## Additional information
1. This time, when moving features around, to avoid confusion, leave the test management box on the Home Screen **and** on the tab bar  & if the user uses the box on the Home Screen redirect the user to the tab and show a message "The test management feature has been moved to it's own tab!" with a red arrow pointing at the new tab. Afterwards, the box is not on the home screen anymore.
2. This report is based on feedback from a Twitter user: https://twitter.com/anonyme_melone/status/1429818825927806977?s=20

---
Internal Tracking ID: [EXPOSUREAPP-13522](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13522)

**Comment by Ein-Tim** [comment]
This issue is nearly 10 months old and was never mirrored to JIRA. Please mirror it to JIRA now.

**Comment by Ein-Tim** [comment]
Please mirror this issue to JIRA now @dsarkar / @larswmh.

**Comment by larswmh** [comment]
Thanks for your feature request @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-13522](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13522)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
