### ISSUE TITLE
Twitter Suggestion: Integrate functionality of the CovPassCheck-App into the Corona-Warn-App

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#633]
## Feature description
The functionality of the [CovPassCheck-App](https://digitaler-impfnachweis-app.de/en/covpasscheck-app) should be integrated into the Corona-Warn-App. 
There should be a new section "Check validity of certificates" where the user is able to scan certificates of other people, these are checked for validity and CWA shows the status of validity. 
Additionally, there should be an option to **switch off** the automatic download of certificates list (revoked certificates, etc.) to not take away free space from a user who doesn't even use this features.

## Problem and motivation
An integration of the functionality of the CovPassCheck-App into the Corona-Warn-App would solve multiple problems. One is the problem that certificates are very rarely checked with the CovPassCheck-App but instead just looked at. If CWA would have the same functionality as the CovPassCheck-App it is safe to assume that at least a few more people will check certificate with a check app.
Another motivation to integrate this is to let CWA more and more become a "Allzwecktool" (all-purpose-tool) in the "fight" against Corona. 

## Additional information
This feature request is based on the wish a user shared with me on Twitter: https://twitter.com/bergruebe/status/1429881896071311370?s=20

---
Internal Tracking ID: [EXPOSUREAPP-13523](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13523)

**Comment by Ein-Tim** [comment]
This issue is nearly 10 months old and was never mirrored to JIRA. Please mirror it to JIRA now.

**Comment by Ein-Tim** [comment]
Please mirror this issue to JIRA now @dsarkar / @larswmh.

**Comment by larswmh** [comment]
Thanks for your feature request @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-13523](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13523)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
