### ISSUE TITLE
Hospital QR-Codes for enabling in-hospital positive tested users to warn their contacts via the Corona-Warn-App 

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#634]
<details>
<summary>Prologue - Skip if not interested</summary>

The Twitter account [@Anaesthet1](https://twitter.com/Anaesthet1) with more than 20.000 followers has tweeted about his experience with the Corona-Warn-App: 
https://twitter.com/Anaesthet1/status/1430504822101454850?s=20
The Tweet received over 800 likes and over 40 comments, some from users who are also sharing their experience.
In the Tweet he1 says that he/she: "As a physician in the emergency department and ICU who has constant contact with secured infected patients, I have had a red alert exactly ONE time because ONE time a positive tested patient entered this into the app." (Translated from German using DeepL)
The official Twitter account of the Cororna-Warn-App ([@coronawarnapp](https://twitter.com/coronawarnapp)) [reacted](https://twitter.com/coronawarnapp/status/1430936110843273216?s=20) on this Tweet and making clear that the Corona-Warn-App does not warn users who are in contact with already positive tested users but warns users who had contact with a later positive tested user in the last 14 days. 
I reached out to [@Anaesthet1](https://twitter.com/Anaesthet1) and while talking to him/her it [became clear](https://twitter.com/Anaesthet1/status/1430554639397789706?s=20) that he/she also has contact to not yet positive tested people who are then tested positively once in the hospital.
I then [asked](https://twitter.com/EinTim2/status/1430555840663199752?s=20) whether people who are tested in hospitals (who maybe came in with an ambulance) really get a QR-Code to receive their test result via CWA, [@Anaesthet1](https://twitter.com/Anaesthet1) [answered](https://twitter.com/Anaesthet1/status/1430556360446562310?s=20) that this depends on the condition the person is in. But he/she also said the issuing of CWA test result QR codes and lack of knowledge about the option to warn contacts with a TAN is also a problem. 
This got me and that's why I open this issue. 

</details>

## Feature description
Hospitals should have an easy, safe way to hand out QR-codes if a user was tested positive. In many hospitals, the current workflow is that an employee takes the swab from a person arriving in the hospital and then waiting for 15 minutes (in case of a RAT) or sending the probe to the laboratory and receiving the result. Then an employee walks to the tested person and informs them about their test result. If the result is negativ, everything is fine, go ahead. But if the result is positive it would be a really great addition if hospital staff could easily create QR-Codes for the Corona-Warn-App. These QR-Codes could be handed over with the information of the positive test result and a little flyer / information text why the person should warn their contacts via the Corona-Warn-App.

## Problem and motivation
The problem is that in the most hospitals the test procedure is not connected to the Corona-Warn-App system at all, thus CWA users who were tested positive in a hospital often have only one option to warn their contacts: Call the hotline and get a TeleTAN. 
This is really not very practical and probably nothing you (or I) would do when diagnosed with COVID in a hospital. People have other things in mind then calling some hotline to get a row of letters and numbers to enter it into an app. 

But if it would be possible for the user to just quickly scan a QR code in this app directly after the employee told them their positive test result **and** informing them about the possibility to warn others via the Corona-Warn-App, then more users would do it and more users would get warned. 

---
Internal Tracking ID: [EXPOSUREAPP-13530](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13530)

**Comment by Ein-Tim** [comment]
This issue is nearly 10 months old and was never mirrored to JIRA. Please mirror it to JIRA now.

**Comment by Ein-Tim** [comment]
Please mirror this issue to JIRA now @dsarkar / @larswmh.

**Comment by larswmh** [comment]
Thanks for your feature request @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-13530](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13530)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.

Also, the problem I described in the OP vanished with the SRS feature, which shipped with version 3.0.
