### ISSUE TITLE
Split statistics section in vaccinated and unvaccinated

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#635]
## Current Implementation
Statistics are not splitted in vaccinated and unvaccinated.

## Suggested Enhancement
Split the statistics, one group "vaccinated or recovered" and one "not vaccinated". So the new cards would be:
1. Vaccinated or recovered COVID-19 patients in hospitals 
2. Unvaccinated COVID-19 patients in hospitals
3. Vaccinated or recovered patines in intensive care units in hospitals
4. Unvaccinated COVID-19 patines in hospitals

Similar to what the French app, "TousAntiCovid" shows for entry into intensive care:

<img src="https://user-images.githubusercontent.com/67682506/131048274-27a7db7b-07c3-4130-ad5b-1207d3bc4fd8.PNG" width="300">

## Expected Benefits
Users see that vaccinated people are way less likely to get in the hospital or even into intensive care when vaccinated.

---
Internal Tracking ID: [EXPOSUREAPP-9179](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9179)

**Comment by Ein-Tim** [comment]
@dsarkar 
Any update here?
[@coronawarnapp](https://twitter.com/coronawarnapp?s=21) responded to a [tweet](https://twitter.com/monika_souris/status/1435218103294644227?s=21) which asked for the "Hospitalisierungen" with "Das wird zeitnah umgesetzt. [...]" ([Source](https://twitter.com/coronawarnapp/status/1435225725645246470?s=21)).

**Comment by dsarkar** [comment]
@Ein-Tim Yes, we have an Internal Tracking ID: [EXPOSUREAPP-9179](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9179) "new statistic tiles for hospitalization and intensive care"

**Comment by Ein-Tim** [comment]
Seems like version 2.12 will add the "Hospitalisierungsinzidenz": https://github.com/corona-warn-app/cwa-app-ios/pull/3585

**Comment by Ein-Tim** [comment]
Little update: The first part of this issue was implemented, however, the suggestion to also split the statistics in vaccinated and unvaccinated was not implemented. 
I will therefore adjust the title and OP of this issue and leave it open.

**Comment by Ein-Tim** [comment]
Closing this issue in favor of #636
