### ISSUE TITLE
Split statistics in two sections: Vaccinated/recovered and not vaccinated 

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#636]
## Current Implementation
There is no differentiation between vaccinated/recovered people and not vaccinated people in the statistics.

## Suggested Enhancement
The app should differentiate between vaccinated/recovered people and not vaccinated people in these statistics:
1. "Confirmed New Infections" -> "Confirmed New Infections from unvaccinated people" & "Confirmed New Infections from vaccinated or recovered people"
2. "7-Day Incidence" -> "7-Day Incidence unvaccinated people" & "7-Day Incidence vaccinated or recovered people"

Similar to what France does: 

<img src="https://user-images.githubusercontent.com/67682506/131212226-56b063e3-a241-4d1b-91e7-08662fb1cfd9.jpeg" width="300">

## Expected Benefits
Motivating users to get vaccinated (: 

## Additional information 
This enhancement request is partly based on this request from a user on Twitter: https://twitter.com/kaystrobach/status/1430799184341446657?s=20
However, I added the "Confirmed New Infections" part myself, thus no "Twitter Report:" in the title here (;

---
Internal Tracking ID: [EXPOSUREAPP-11567](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11567)

**Comment by larswmh** [comment]
Thanks for your enhancement request @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-11567](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11567)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
