### ISSUE TITLE
Provide localized versions for "Value Set" fixed values for e.g. test type

### ISSUE THREAD

**Issue by jkrwdf** [corona-warn-app/cwa-wishlist#639]
## Avoid duplicates
* [X] This enhancement request has not already been raised before
* [?] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [X] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
Some fields in the digital COVID-19 certificate contain code-values from the document [Value Sets](https://ec.europa.eu/health/sites/default/files/ehealth/docs/digital-green-value-sets_en.pdf).

This document also provides English "Display" texts for the codes. 

For example the type of test 

LP6464-4 Nucleic acid amplification with probe detection
LP217198-3 Rapid immunoassay

or the vaccination type:

1119305005 SARS-CoV-2 antigen vaccine
1119349007 SARS-CoV-2 mRNA vaccine
J07BX03 covid-19 vaccines

Those English values literally appear in the CWA when displaying a certificate.

![image](https://user-images.githubusercontent.com/5329491/125780329-5409ff88-05fe-4a65-8d13-4d1332105ac0.png)

Especially the text "Rapid immunoassay" was for me as native German speaker at first quite strange. 

## Suggested Enhancement
Provide localized versions for those fixed code-values (e.g. "Antigen-Schnelltest" or "SARS-CoV-2 mRNA Impfstoff".

## Expected Benefits
Better user experience. 

----
Internal Tracking-ID: [EXPOSUREAPP-8988](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8988)

**Comment by heinezen** [comment]
Hello everyone,

The responsibility for the translation was moved to the EU cerificate repositories. See:

https://github.com/ehn-dcc-development/ehn-dcc-valuesets
https://github.com/ehn-dcc-development/ehn-dcc-valuesets/blob/release/2.0.0/test-type.json

----
Corona-Warn-App Open Source Team

**Comment by larswmh** [comment]
See comment above for why this issue was closed, thanks to all participants
