### ISSUE TITLE
Twitter Suggestion: New (optional) push notification about all encounters with later PCR positive tested people

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#642]
## Feature description

Direct quote (translated to English):

"[…] it is about the introduction of a push message that optionally notifies every key exchange with a PCR positive. These push messages should not generate a new status, but rather describe how many keys once, twice (very fleeting encounter, no more than 10 minutes) when the signal strength is too high or possibly very low/very far apart. No new status should be introduced. The current green messages are also included in these push messages.
These push messages could then also replace the push messages that call on people to go to the app regularly. Many want warnings and are aware that an infection is unrealistic. But they want to be continuously sensitised to where infections are realistic. […]" 

## Problem and motivation
Due to the "absence" of low risk exposures since version 1.9 of the Corona-Warn-App, some users think the app is broken because it does not show them any low risk encounters anymore... 
With this optional push notifications the user has the change to see that the app works, but that they were never close enough to an infected user & that's why there are no low risk contacts. 

## Additional information
Twitter link: https://twitter.com/BerndScholz10/status/1435196714563121155?s=20
The text I quoted above send me via DM (direct message) on Twitter, so there is no link I could share with you for this. 

---
Internal Tracking ID: [EXPOSUREAPP-13531](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13531)

**Comment by Ein-Tim** [comment]
This issue stayed unmirrored to JIRA for a prolonged period of time. Please mirror it to JIRA now.

**Comment by Ein-Tim** [comment]
Please mirror this issue to JIRA now @dsarkar / @larswmh.

**Comment by larswmh** [comment]
Thanks for your feature request @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-13531](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13531)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
