### ISSUE TITLE
Rapid Test Profile: Make it possible to store more than one rapid test profile in the app

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#647]
## Current Implementation
Only one RAT profile can exist & be stored in the app at a time.

## Suggested Enhancement
Make it possible to store more than one RAT profile in the app at the same time. 
So, e.g. the parents of a little child which doesn't have a smartphone yet, can create & save a RAT profile for the child.

## Expected Benefits
The RAT profile feature gets more useful and enables the users to create as many RAT profiles as they want. This isn't only a enhancement for the above mentioned parents of children but also for elderly people which live together but only have one smartphone.

---
Internal Tracking ID: [EXPOSUREAPP-11248](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11248)

**Comment by StephanFl** [comment]
Would be a very usefull feature the more family members without a mobile phone you have (two childs in my case).

**Comment by larswmh** [comment]
Thanks for your suggestion @Ein-Tim. Internal Tracking ID: [EXPOSUREAPP-11248](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11248)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Implemented in version 2.22. Closing.
