### ISSUE TITLE
Link to the FAQ entry "How to behave if I am partially or completely vaccinated, but receive a red warning in the Corona-Warn-App?" on the increased risk detail screen

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#648]
## Current Implementation
The increased risk detail screen doesn't mention what to do if one is already vaccinated and receives this increased risk encounter.

## Suggested Enhancement
Add a new bullet point to the guidelines which are shown when the app has detected an increased risk.
The text of the bullet point should be:
"If you are vaccinated against COVID-19 be alert for typical COVID-19 symptoms. Even vaccinated people can show symptoms in breakthrough cases. If you notice any suspicious symptoms, get tested." and link to the FAQ entry https://www.coronawarn.app/en/faq/#vac_cert_red_warning.

## Expected Benefits
Users which are vaccinated against COVID-19 and receive a notification about an encounter with increased risk can find information on how to behave directly inside of the app and are guided to the FAQ in an easy way.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Your suggestion is related to https://github.com/corona-warn-app/cwa-wishlist/issues/488 where I suggested that the app should use the vaccination status of the smartphone user to modify the risk assessment and message.

Your suggestion is to just add the scenario of a vaccination user to the guidelines text output, as can be seen on the screenshots:
https://www.coronawarn.app/en/screenshots/#ios_cards or
https://www.coronawarn.app/en/screenshots/#android_cards

like https://www.coronawarn.app/assets/screenshots/2-10/en/android/TracingDetailsFragment_tracing_increased.png

![image](https://user-images.githubusercontent.com/66998419/134804359-0a35e2f5-8b20-4a0d-80ae-2aaa519f8d49.png)

I support your suggestion!

**Comment by MikeMcC399** [comment]
The guidelines might also want to cover the case of a recovered person receiving a red warning.

**Comment by Ein-Tim** [comment]
This issue has been mitigated in version 2.15.1 with the updated texts.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for following up!
