### ISSUE TITLE
Display certificate on locked screen for increased privacy

### ISSUE THREAD

**Issue by rafaces** [corona-warn-app/cwa-wishlist#649]
## Feature description
Showing certificate on locked screen
(So even though the screen is locked, the possibility to see the certificate... See [Transportr](https://play.google.com/store/apps/details?id=de.grobox.liberario) app as an example of how this works)

## Problem and motivation
- This feature is extremely useful for privacy reasons;
- Whenever you have to hand over your phone to authorities so your certificate needs to be checked, this drastically reduces the chances of authority abuse (you basically don't have to hand over an UNLOCKED phone to authorities)

## Is this something you're interested in working on
No

**Comment by Ein-Tim** [comment]
This should be moved to the Android repository. It is not possible under iOS for apps to show any content on the Lock Screen (besides from notifications).

Also, just for your information, the feature request to add Google Pay support was denied exactly for the reason that with this change everybody would be able to see your certificate, without having to unlock the device. For more information please see https://github.com/corona-warn-app/cwa-app-android/issues/3486

**Comment by jucktnich** [comment]
Showing the certificate on an locked phone was already denied

**Comment by rafaces** [comment]
Thanks for the quick reaction @Ein-Tim. Didn't know there was a repo for Android; will close it and post there :)
And the concern sounds reasonable; I think simple solution is 1) Feature toggle so user can decide if he/she wants it or not; 2) Displaying it on locked screen only while app is open/in use

Thank you again for the help
