### ISSUE TITLE
Add additional languages

### ISSUE THREAD

**Issue by coder66** [corona-warn-app/cwa-wishlist#65]
Now that the app is in multiple country app stores, please add additional languages so that the users understand the app better.

These would be: Turkish, English, French, Spanish, Italian and Polish

Having a German only app is not only an issue in Germany with the Turkish community, but also for the listings in the other EU country app stores.

**Comment by tkowark** [comment]
Just FYI: The app already is available in english since day one and a PR for Turkish was introduced just today.

**Comment by coder66** [comment]
Excellent news! But somehow this was not communicated yet, at least did not read in the press. Also I was not able to find language options in the app settings, to be able to change the language.

**Comment by tkowark** [comment]
The settings are not available in the app itself, but through the OS settings. The app picks up your preferred languages in order of appearance. If you, for example, have languages italian - german - english, the app will be in german. For iOS, if you have more than 1 language set in the OS, you can select the app language via Settings -> Corona Warn.

An in-app language switch is topic of #22

**Comment by coder66** [comment]
Please consider adding a language selection in the app (Android). There are surely cases where users have eg German OS setting but who would prefer to use the app in their mother language.

**Comment by akuckartz** [comment]
@coder66
> An in-app language switch is topic of #22
