### ISSUE TITLE
Twitter suggestion: EU DCC validity check: Don't show "Certificate Is Not Valid" if the 14 day waiting period since the last vaccination hasn't passed yet but show "Certificate get's valid on dd.mm.yyyy"

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#650]
## Current Implementation
Currently, the "Check Validity" feature of the Corona-Warn-App shows "Certificate Is Not Valid" if check is carried out before min. 14 days since the vaccination have passed.

## Suggested Enhancement
Don't show "Certificate Is Not Valid" in case a certificate complies with all rules but only min. 14 days haven't passed yet but show "Certificate gets valid on dd.mm.yyyy" (dd.mm.yyyy = day, month & year when the certificate gets valid.

## Expected Benefits
There were users on Twitter complaining that they thought that "Certificate Is Not Valid" means something like the signature of the certificate is not valid, etc. They did not think that the "Certificate Is Not Valid" status is shown if min. 14 days since the last shot haven't passed yet.

## Additional information
This is a enhancement report based on feedback from two Twitter users: https://twitter.com/rmetzler/status/1443665683901042695?s=20 & https://twitter.com/ahzf/status/1439833976294842368?s=20

---
Internal Tracking ID: [EXPOSUREAPP-13532](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13532)

**Comment by Ein-Tim** [comment]
This issue stayed unmirrored to JIRA for a prolonged period of time. Please mirror it to JIRA now.

**Comment by Ein-Tim** [comment]
Please mirror this issue to JIRA now @dsarkar / @larswmh.

**Comment by larswmh** [comment]
Thanks for your enhancement request @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-13532](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13532)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
