### ISSUE TITLE
Arier-Nachweis importieren?

### ISSUE THREAD

**Issue by RobinLinus** [corona-warn-app/cwa-wishlist#651]
Ist es möglich einen Arier-Nachweis in die Corona-Warn-App zu importieren?

**Comment by Ein-Tim** [comment]
@SebastianWolf-SAP, something for you? 

I consider this as "Unacceptable behavior" according to the [Code of Conduct](https://github.com/corona-warn-app/cwa-wishlist/blob/master/CODE_OF_CONDUCT.md#our-standards), see https://github.com/corona-warn-app/cwa-wishlist/blob/master/CODE_OF_CONDUCT.md#our-standards:

"Examples of unacceptable behavior include:
[…]
- Trolling, insulting or derogatory comments, and personal or political attacks"

I'd consider this as "Trolling", and very bad and disrespectful trolling (comparing digital vaccination certificates to the "Arier-Nachweis" is just unacceptable).

**Comment by SebastianWolf-SAP** [comment]
@RobinLinus This is a clear violation of our Code of Conduct as outlined by @Ein-Tim. As a consequence, you receive an official warning. Other violations in the future will lead to a temporary or permanent ban.
