### ISSUE TITLE
Link to FAQ entry „How long is my certificate valid​" from the „Technical Expiration Date“ box in the app

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#654]
## Current Implementation
Currently, there is a box in the certificate details screen, showing this:
![image](https://user-images.githubusercontent.com/67682506/136336132-550477ef-6c46-40e8-8b96-ba45d42cc948.jpeg)

## Suggested Enhancement
Add a new sentence to this box:
"What is the Technical Expiration Date?" and link to this FAQ entry: https://www.coronawarn.app/en/faq/#eu_dcc_validity

## Expected Benefits
Many users (on Twitter, in App Store reviews, etc.) ask what exactly the technical expiration date is and whether they have to get a new certificate and if yes if this will be send to them by post or if they have to go to a pharmacy. 
Most users will not look into the FAQs by themselves, so the best way would be to directly guide them to the right FAQ entry.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Good suggestion!

---
Now for an off-topic comment!

I guess you posted a screenshot from iOS. The date format is wrong for an English screen as the dot after the 17 is only used in German, not in English. 

If you want to follow this us, please log a separate iOS issue and let me know. There were some discussions in https://github.com/corona-warn-app/cwa-app-android/pull/3987 about harmonizing date format display in Android and across Android and iOS.

**Comment by Ein-Tim** [comment]
Good Morning @MikeMcC399 

Thanks for the note regarding the wrong formatting, I'll open an issue in the iOS repository for this later today.

Since we had quite many date formatting issues in the past, maybe it would be good to open an issue in the documentation repository asking to align CWA under Android and CWA under iOS to another and make sure that always the right formatting is used. What do you think?

**Comment by MikeMcC399** [comment]
@Ein-Tim 

It's probably good to start with the concrete case of the technical expiry date in iOS. I can post the Android formats used in that issue when you open it. We can also discuss any further steps in that issue.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I opened https://github.com/corona-warn-app/cwa-app-ios/issues/3662 reg. this.

**Comment by Ein-Tim** [comment]
This has been implemented. Closing.
