### ISSUE TITLE
Twittet Suggestion: Make it possible to show one Check In full screen (proof that one checked in)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#655]
## Feature description
The user should be able to click on a Check In whiled checked in.
The app then shows that the user has checked in and how long the user is already checked in. 

## Problem and motivation
Currently, if users want to proof that they checked in, they have to show the Check In tab to the controlling person. 
The controlling person, however, is not only able to see the current check in, but also the history. 
This can be seen as a privacy flaw, as some users might not want the controlling person to see where they went in the past days. 

## Additional information 
This feature request is based on the feedback I received from a Twitter user: https://twitter.com/marginauto/status/1446862229148737536?s=21

---
Internal Tracking ID: [EXPOSUREAPP-13533](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13533)

**Comment by Ein-Tim** [comment]
This issue stayed unmirrored to JIRA for a prolonged period of time. Please mirror it to JIRA now.

**Comment by Ein-Tim** [comment]
Please mirror this issue to JIRA now @dsarkar / @larswmh.

**Comment by larswmh** [comment]
Thanks for your feature request @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-13533](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13533)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
