### ISSUE TITLE
Twitter Suggestion: Hologramms and running clock

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#656]
## Feature description

The next version of CWA and CovPass should feature hologrammes behind or near the QR code in order to prevent fraud/people misusing screenshots. 
The hologram changes colour when the orientation of the phone changes.

An example is the digital certificate app in Victoria, Australia: https://twitter.com/emma_os/status/1447076386795966464?s=21

Below the QR code should be a running clock in the 24hr format of hh:mm:ss to make sure it’s not an image file.

## Problem and motivation

CovPassCheck is rarely being used so this could be an easy to implement solution to check for validity without using an additional app. 

## Additional information
1. If it's decided to implement this, it should be considered for CovPass as well.
2. This feature suggestion is based on the feedback I received on Twitter: https://twitter.com/julianforscht/status/1447136889962745859?s=21

**Comment by thomasaugsten** [comment]
A hologram or running is not a proof for a valid certificate. It is very easy to provide a fake app or website with this feature. 

The user will also show the printed out version and I don't think the printed version has holograms on it. 

Every support to not prove with a check app makes it easy to fake a certificate.

**Comment by Ein-Tim** [comment]
@thomasaugsten 

I agree with you on this. I transferred your comment to the Twitter user.

**Comment by jucktnich** [comment]
The problem is: since the CWA is open source, you can do something as complicated as you want, everyone (who knows a bit about programming) can fool the system in minutes.

**Comment by ndegendogo** [comment]
> as complicated as you want, everyone (who knows a bit about programming) can fool the system in minutes.

@jucktnich except cryptography, like a digital signature. This you cannot forge as long as you don't have the true secret / private signature key. 
The only drawback is that you cannot do this kind of verification in your head.

**Comment by ndegendogo** [comment]
> A hologram or running is not a proof for a valid certificate. 

@thomasaugsten sure, it is not a proof. But it makes "fooling" a bit harder.
Of course we all agree that the only true and unforgeable way of verification is to use the CovPassCheck app.

But compare it with our money. It has many fancy security features. Some can be checked 'manually', others only with special equipment. The sum of all makes it harder to forge money. And forging money is a criminal act, so people think twice before they try to fool with it...

**Comment by Ein-Tim** [comment]
This issue stayed unmirrored to JIRA for a prolonged period of time. Please mirror it to JIRA now.

**Comment by Ein-Tim** [comment]
For the reason given by @thomasaugsten in https://github.com/corona-warn-app/cwa-wishlist/issues/656#issuecomment-939695228 I'll close this issue now.
