### ISSUE TITLE
Mention free of charge test directly in the app (if risk status is increased)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#657]
## Current Implementation
The app does not mention that the tests stay free of charge, even after the new CoronaTestV came into force on 11.10.2021, if the Corona-Warn-App shows an increased risk notification. 

## Suggested Enhancement
Add this information directly into the app.

## Expected Benefits
Users can find relevant information directly in the app and get tested if a high risk notification is shown.

**Comment by achisto** [comment]
Good suggestion, there could also be a link to the [corresponding FAQ-entry](https://www.coronawarn.app/de/faq/#vac_cert_red_warning). I am wondering though, whether that FAQ-entry should be changed, because at least the BMG says, it is not binding that the test is a PCR-test: 

> Darüber hinaus haben folgende asymptomatische Personen nach der Coronavirus-Testverordnung grundsätzlich Anspruch auf eine kostenlose Testung. Diese Testung kann auch durch eine Diagnostik mittels Nukleinsäurenachweis des Coronavirus SARS-CoV-2, also zum Beispiel eine PCR-Testung, erfolgen. **Ein strikter Anspruch auf eine PCR-Testung besteht jedoch nicht, da auch eine Diagnostik durch Antigen-Tests möglich ist.**
> 
> Kontaktpersonen von Menschen, bei denen durch einen Arzt oder den öffentlichen Gesundheitsdienst eine Infektion mit SARS-CoV-2 festgestellt wurde. Kontaktpersonen sind zum Beispiel Mitglieder desselben Haushalts, Personen mit engem räumlichen Kontakt zu einer infizierten Person oder Personen, die über die Corona-Warn-App eine Warnung mit der Statusanzeige „erhöhtes Risiko“ erhalten haben.
> 
Source: [https://www.bundesgesundheitsministerium.de/coronavirus/nationale-teststrategie/faq-covid-19-tests.html](https://www.bundesgesundheitsministerium.de/coronavirus/nationale-teststrategie/faq-covid-19-tests.html)

**Comment by abraxa1982** [comment]
To make it perfectly understandably maybe even a hint, this information is also correct for fully vaccinated people, many people think, there is a difference.

**Comment by Ein-Tim** [comment]
@achisto 

Very good comment! 

This is also confirmed by the "Verordnung zum Anspruch auf Testung in Bezug auf einen direkten Erregernachweis des Coronavirus SARS-CoV-2 (Coronavirus Testverordnung – TestV) 
Vom 21. September 2021" (https://www.bundesanzeiger.de/pub/publication/EaknuyebqGE4JSI7pwk/content/EaknuyebqGE4JSI7pwk/BAnz%20AT%2021.09.2021%20V1.pdf?inline).

§1 says: "Zur Diagnostik können nach Maßgabe dieser Verordnung und der Teststrategie des Bundesministeriums für Gesund- heit eine Labordiagnostik mittels Nukleinsäurenachweis, eine variantenspezifische PCR-Testung oder eine Diagnostik durch Antigen-Test gehören. [...]"

I will create an issue in the website repo.

**Comment by achisto** [comment]
@Ein-Tim sound great, I was just looking for the right place to raise this issue. Maybe you could also mention §2 Abs. 2 Nr. 5 which also still addresses the CWA: 

> Kontaktpersonen im Sinne des Absatzes 1 Satz 1 sind: [...] Personen, die durch die Corona-Warn-App des Robert Koch-Institutes eine Warnung mit der Statusanzeige erhöhtes Risiko erhalten haben

**Comment by Ein-Tim** [comment]
@achisto

Do you think it's necessary to mention the legal basis in the FAQs? 

@abraxa1982

This is a good point! After the wrong information that one has the right to get a PCR test is removed from the FAQ (and replaced with the information that one has the right to get tested with one of the tests mentioned in the Coronavirus Testverordnung) I will bring your point up. 

You could also [create a new issue](https://github.com/corona-warn-app/cwa-website/issues/new/choose) for this yourself in the website repository.

**Comment by achisto** [comment]
@Ein-Tim not in the FAQ, I think, although it surely wouldn't hurt. Your text sounds great, thank you for raising the issue at the appropriate place.

**Comment by Diapolo** [comment]
Good suggestion!

**Comment by Ein-Tim** [comment]
This will be implemented in the next version: https://github.com/corona-warn-app/cwa-app-ios/pull/3932

<img src="https://user-images.githubusercontent.com/67682506/144649156-52b89a5d-fb2f-4cb8-9d8f-ae6b6938a577.png" width="300">

**Comment by Ein-Tim** [comment]
This has been implemented in version 2.15.1.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for following up!
