### ISSUE TITLE
Increase contrast of „ + ZERTIFIKATE “ - field / button or move this option into 'Certificate' - 3-Dot-Menue …

### ISSUE THREAD

**Issue by Jo-Achim** [corona-warn-app/cwa-wishlist#658]
CWA 2.11.2 (Android)

## Suggested Enhancement
Increase contrast / background color of „ + ZERTIFIKATE “ - field / button:

![Screenshot_20211013-144957_3](https://user-images.githubusercontent.com/21124877/137165858-ff972dc9-80a7-44f6-ac5d-458f018e94ed.png)

_or_

Move the „ + ZERTIFIKATE “ - option into the ‘Certificate’ - 3-Dot-Menue:

![Screenshot_20211013-154134_3](https://user-images.githubusercontent.com/21124877/137166581-4ee31d85-4192-45f6-9eea-0cecfeef6b4f.png)

## Expected Benefits
Better recognizability / legibility / more meaningful assignment.

The increase in contrast / background color may also apply to the backgrounds of the other 3-dot-menus; see second screenshot as a suggestion!

**Comment by MikeMcC399** [comment]
@Jo-Achim 
In the next version (2.12) that button is removed and there is a universal scan button introduced. At least, that is what is showing in the 2.12 release candidates.

**Comment by MikeMcC399** [comment]
I would classify this as an Android bug in 2.11.2.

The screenshots look as though they are edited (Vorname Name) and I assume that this is a display when there are certificates stored for more than one person on the device.

If there are only certificates for one person stored, then the "+ CERTIFICATE" button is either on top of the QR code, or it is on top of a white background. In both cases the contrast is good.

I suggest to transfer to [cwa-app-android](https://github.com/corona-warn-app/cwa-app-android ) to check that the issue does not also occur in 2.12.x Android.

**Comment by Ein-Tim** [comment]
This is not a problem under iOS: 
<img src="https://user-images.githubusercontent.com/67682506/137176037-3aab33d0-aa99-4c9f-9d7d-aba6132a82b0.png" width="300">

Screenshot from https://www.coronawarn.app/de/screenshots/#ios_certificates

**Comment by Jo-Achim** [comment]
@MikeMcC399 
> 
> 
> I would classify this as an Android bug in 2.11.2.
> 
As far as I remember, the 'problem' existed for a while; at least since version 2.7.1.
> The screenshots look as though they are edited (Vorname Name) and I assume that this is a display when there are certificates stored for more than one person on the device.
> 
Yes.
It may be that the contrast / background color problem 'only' occurs when there are multiple certificates. However, a change would be desirable.

And it would be fine:
> The increase in contrast / background color may also apply to the backgrounds of the other 3-dot-menus; see second screenshot as a suggestion!

@Ein-Tim,
thank you.

----

I think we are waiting for version 2.12. On the one hand this point is not so important and on the other hand:
> 
> 
> @Jo-Achim In the next version (2.12) that button is removed and there is a universal scan button introduced. At least, that is what is showing in the 2.12 release candidates.

**Comment by MikeMcC399** [comment]
The problem can be seen on the [Android certificates screenshot page](https://www.coronawarn.app/en/screenshots/#android_certificates) and as @Ein-Tim wrote, this issue only affects Android, as can be seen by viewing the [iOS certificates screenshot page](https://www.coronawarn.app/en/screenshots/#ios_certificates)

This is the Android 2.11 screen:

![PersonOverviewFragment_many_persons_2 11](https://user-images.githubusercontent.com/66998419/137264151-655aac9d-8d36-4892-9161-27bb374a9e12.png)

**Comment by MikeMcC399** [comment]
@Jo-Achim 

On an Android  2.12 release candidate build the screen changes to the following example. The exact appearance will depend on the geometry of the device and the display font and zoom size settings.

![PersonOverviewFragment_many_persons_2 12](https://user-images.githubusercontent.com/66998419/137264275-7fcc7914-1118-49e1-88ed-8b36a610dc9d.png)

**Comment by Jo-Achim** [comment]
@MikeMcC399,

thanks for information's. 

But I think to move the " + ZERTIFICATE " - option into the 3-Dot-Menue is a better solution! 
Why?
In my opinion, the main task of the certificate screen is to show one of the QR codes for the purpose of proof of vaccination.
Everything else is an unnecessary waste of space in this sense / on this screen.

Of course, it must be possible to add new vaccination certificates. But how often is this necessary, in opposition to the main task? Therefore a corresponding option in the 3-dot-menu of the certificate screen is sufficient; according to my 2nd screenshot [here](https://github.com/corona-warn-app/cwa-wishlist/issues/658#issue-1025421736).

PS: Next time I will also access the 'certificates screenshot pages'.

_PS2: This applies to both Android and iOS as a result._

**Comment by Jo-Achim** [comment]
Ok, since the new scan function on the main screen (CWA 2.12.1) is also intended for "Check-ins", the 'scan symbol' makes sense here. (If it were only about 'Tests' and 'Certificates', then the symbol in the subsection of "Certificates" would be better.)

In this respect, my wish for the " + Certificates " button to be more recognizable has been fulfilled. That's why I'm closing here.
