### ISSUE TITLE
Add new bullet point to "Certificate Verification by Third Parties" screen mentioning that the ID has to be checked

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#660]
## Current Implementation
The "Certificate Verification by Third Parties" screen does not mention that the person who scans the QR code with the CovPassCheck-App has to check the ID of the person controlled too:

<img src="https://user-images.githubusercontent.com/67682506/137495417-815c5528-e313-4a04-ad0c-baba97f4673c.jpeg" width="300">

## Suggested Enhancement
Add a new bullet point after the second one:
- Additionally to scanning the QR code with the CovPassCheck app, third parties must also see your ID to ensure that the certificate shown to them actually belongs to the person showing it. 

## Expected Benefits
@fynngodau Shared an article from the BR in our community slack, where guests of a restaurant were angry because the person controlling the DCCs wanted to see an ID. Link to this article: https://www.br.de/nachrichten/bayern/corona-kontrollen-in-der-gastro-sterne-koch-in-wuerzburg-klagt-ueber-aerger,Slog82m

So, an expected benefit would be to make the life of people properly controlling DCCs easier, as they don't have to discuss with people not wanting to show their ID. 

---
Internal Tracking ID: EXPOSUREAPP-13342

**Comment by MikeMcC399** [comment]
@Ein-Tim 
There is more information available through the link in your screenshot which links to https://www.coronawarn.app/en/faq/#eu_dcc_check

![image](https://user-images.githubusercontent.com/66998419/137499908-baebc68f-cae5-439f-8d01-0f668809c40c.png)

**Comment by Ein-Tim** [comment]
@MikeMcC399 Yes, you're right. However, it would be even better if this note is shown directly in the app.

**Comment by Ein-Tim** [comment]
This issue stayed unmirrored to JIRA for a prolonged period of time. Please mirror it to JIRA now.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

The instructions about what to do in the CovPassCheck App are in that app. CWA does not need to include these instructions.

It says "Check the following data against an ID document from the person you are checking."

**Comment by Ein-Tim** [comment]
@MikeMcC399 It speeds up the process if the CWA user knows that an ID has to be presented.

**Comment by Ein-Tim** [comment]
I have a PR ready for this item under iOS.

@svengabr & @dsarkar Could you let me know if a PR reg. this is welcome?

**Comment by svengabr** [comment]
@Ein-Tim I will create a ticket for this. However, I can not guarantee if your PR will be merged as the app developer team most of the time won't accept any community PRs for the iOS or Android app.

**Comment by Ein-Tim** [comment]
@svengabr 

> However, I can not guarantee if your PR will be merged as the app developer team most of the time won't accept any community PRs for the iOS or Android app.

Mh, did something change here during the last weeks? I always had the impression that the team welcomes community PRs very much.

**Comment by svengabr** [comment]
Internal Tracking ID: EXPOSUREAPP-13342

**Comment by svengabr** [comment]
@Ein-Tim I will ask the dev team once again for a general state in terms of App PRs. For the website, we will accept community additions most of the time.

**Comment by svengabr** [comment]
@Ein-Tim 

The response is:

* New features PRs are critical since the RKI would be asked first if said feature should be implemented. Then a whole other internal process would start (dev, security checks, testing [...]). Community PRs will not be accepted easily in terms of new features.
* Bugfix PRs are appreciated since bugs need to be fixed anyways and this would help our developers.
* Text changes are critical since all texts are approved from multiple instances. Texters, Developers, Legal, RKI, BMG [...]. So a simple text change/addition will not go through easily. Best approach would be to submit the suggested text change as a ticket and we will bring this up to the internal discussion. Once we have green light, a community PR can later be accepted. So I wont have a good feeling to say "go ahead and create a pull request" to a community member when there is _**a risk**_ it wont get accepted.

**Comment by MikeMcC399** [comment]
@svengabr 

For text changes there is a special instruction for Android which is missing in iOS.

In https://github.com/corona-warn-app/cwa-app-android/blob/main/.github/pull_request_template.md it says:

"The PR can not contain changes in localization files, e.g. values-[LANGUAGE-CODE]/strings/* and / or assets/* (see https://github.com/corona-warn-app/cwa-app-android/issues/332 for further information)."

Probably something similar should be added to the iOS repository.

**Comment by Ein-Tim** [comment]
@svengabr 

Okay thanks, so in the end, nothing really has changed PRs to iOS & Android repo are always provided with a certain risk of not being merged because the stakeholders decline the feature/text change/whatever (happened here for example: https://github.com/corona-warn-app/cwa-app-android/pull/4719).

But this shouldn't be a show stopper for the community, or? Providing PRs with good additions were in the past accepted, after some while. See e.g. this PR from @fynngodau: https://github.com/corona-warn-app/cwa-app-android/pull/2481 (PR was continued in another one, but the changes were approved in the end).

But that's off topic here, maybe I'll comment in https://github.com/corona-warn-app/cwa-documentation/issues/890 regarding this.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Regarding https://github.com/corona-warn-app/cwa-wishlist/issues/660#issuecomment-1151010762, at least under iOS, it is no problem to add new strings / change strings in German. Everything else is done by the translation team.

**Comment by Ein-Tim** [comment]
PR https://github.com/corona-warn-app/cwa-app-ios/pull/4613 opened at my own risk.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

- If your PR https://github.com/corona-warn-app/cwa-app-ios/pull/4613 for iOS is accepted, then there should be a corresponding change done for Android.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

- My PR https://github.com/corona-warn-app/cwa-app-ios/pull/4613 was merged, so this means RKI has approved the changes. I'm sure someone will mirror the changes to Android soon. If not, you could follow up through an issue, or I will do that :D

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> If not, you could follow up through an issue, or I will do that :D

I will leave that to the developers or to you.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
- See https://github.com/corona-warn-app/cwa-app-android/pull/5325

@dsarkar 

This item can now have a Fix 2.25 label added.

**Comment by Ein-Tim** [comment]
This feature has been implemented in version 2.25. Therefore I'm closing this issue now.
