### ISSUE TITLE
Make it possible to set a reminder for turning exposure logging back on when turning it off

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#661]
## Current Implementation
Currently, the app does not offer the feature to get a reminder to reactivate exposure logging when turning exposure logging off. 

## Suggested Enhancement
Add the option to select a time when the app should remind you to reactivate exposure logging.
Here is an example how the French app, "TousAntiCovid" has implemented this:

<img src="https://user-images.githubusercontent.com/67682506/137503592-906ca5bb-1316-43f2-9098-18d4a03da6c0.jpeg" width="300">

## Expected Benefits
Users who turn exposure logging off don't forget to turn it back on, because the app reminds them to do so.

---
Internal Tracking ID: [EXPOSUREAPP-11150](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11150)

**Comment by MikeMcC399** [comment]
Similar suggestions were made in https://github.com/corona-warn-app/cwa-wishlist/issues/251:

- https://github.com/corona-warn-app/cwa-wishlist/issues/251#issuecomment-726344250
- https://github.com/corona-warn-app/cwa-wishlist/issues/251#issuecomment-769646898

but it is not clear if that is the major wish in #251.

**Comment by larswmh** [comment]
Thanks for your suggestion @Ein-Tim. 
Internal Tracking ID: [EXPOSUREAPP-11150](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11150)

--- 
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
