### ISSUE TITLE
Do not show "Exposure check failed" screen if no new event IDs can be downloaded because the device is not connected to the internet

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#662]
## Current Implementation
Currently, the app shows the "Exposure check failed" card if a user was/is checked in to an event and the device is not connected to the internet. 
The reason for this is that the app tries to download new Event IDs as often as possible & performs a risk check with the IDs.
This is quite confusing, as the Bluetooth based risk check is only carried out all 4h and the app does not show "Exposure check failed" if the device is not connected to the internet at the moment the check should be performed (or until up to 24h after the last successful check).

## Suggested Enhancement
Don't show the "Exposure check failed" screen if no new event IDs can be downloaded because the device is offline. You don't do this when no new random IDs can be downloaded, so why should you do this if no new event IDs can be downloaded?

## Expected Benefits
This is very confusing for the end user, who will ask the question whether the app still works offline or if they always have to be online to use the app.

## Related Issues
- https://github.com/corona-warn-app/cwa-app-ios/issues/3188
- https://github.com/corona-warn-app/cwa-documentation/issues/722

---
Internal Tracking ID: [EXPOSUREAPP-10997](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10997)

**Comment by dsarkar** [comment]
@Ein-Tim thanks.

Internal Tracking ID: [EXPOSUREAPP-10997](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10997)

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@Ein-Tim FYI, not sure, but this story might become obsolete/fixed with https://github.com/corona-warn-app/cwa-app-ios/pull/4017.

**Comment by Ein-Tim** [comment]
PR https://github.com/corona-warn-app/cwa-app-ios/pull/4598 fixes this under iOS.

@dsarkar Feel free to apply the `Fix 2.24` label here.

**Comment by Ein-Tim** [comment]
I can confirm that this has been addressed in version 2.24 under iOS, I will check Android as soon I receive the update on the device.

**Comment by mtwalli** [comment]
@Ein-Tim  This issue has been fixed also in Android in 2.26.0, please close the issue ?

**Comment by Ein-Tim** [comment]
@mtwalli As I commented above, I'd like to test this myself and will close this issue as soon as I can confirm the fix.

**Comment by mtwalli** [comment]
Ok, 2.26 is fully rolled out, Hopefully you should have received it by now

**Comment by Ein-Tim** [comment]
Confirm fixed. Closing.
