### ISSUE TITLE
[Question:] Future processing of the data for the 'hospital traffic light' ...

### ISSUE THREAD

**Issue by Jo-Achim** [corona-warn-app/cwa-wishlist#663]
Since I assume that we will (understandably) again experience a patchwork of corona measures / restrictions this year, I would be interested to know whether, and if so, how the new framework conditions 'incidence' and 'hospital traffic lights' should be taken into CWA?

Finally, unlike in the past, local protective measures / restrictions should in future be defined or made dependent on the _'local incidence'_ and the _'local hospital occupancy'_ - represented by the hospital traffic light (green / yellow / red).

## Current Implementation
We currently have the 'local incidences' in the CWA (2.12.2) and now the "nationwide 7-day hospitalization incidence" as well as the data for "nationwide COVID-19 patients in intensive care units". Cross-reference: https://github.com/corona-warn-app/cwa-wishlist/issues/635#issue-980723375.

## Suggested Enhancement / Extension proposal
In order to draw conclusions about the local measures / restrictions with the help of the CWA against this background, the data of the "local hospital occupancy" and their processing would also be required.

## Questions
Should this 'local' data also flow into the CWA in parallel to the configured "Local 7-day incidence"? Including the status of the 'hospital traffic light'?
Or should there be a reference to NINA instead (NINA v.3.4.0 -> "Corona rules for the district ...", "Contact provisions", 1st paragraph, last sentence, eg: "The hospital traffic light is green." )?
Or are there other plans? 

## Expected Benefits
Against the background of the CWA expansion from a tool for 'detection and tracking of possible infection risks' to a more comprehensive tool for 'almost everything' to do with Corona (e.g. 'checking the entry requirements'), an above-mentioned expansion of the CWA would certainly make sense and be too fit the previous extensions.

So, the user is better informed about the current situation in the hospitals and can, due to the 'hospital traffic light', draw conclusions directly from CWA about currently applicable restrictions or use this information.

**Comment by Ein-Tim** [comment]
This will actually be implemented in the next version: https://github.com/corona-warn-app/cwa-app-ios/pull/3679

Version 1.13 will show the local 7 day hospitalization. 

**But** as this number is only available on state level, the number for all districts in one state will be the same, see https://github.com/corona-warn-app/cwa-app-ios/pull/3683 which says:

> Auf den lokalen Kacheln zur 7-Tage-Inzidenz der Neuinfektionen wird nun zusätzlich die 7-Tage-Inzidenz der Hospitalisierung angezeigt. Da diese Kennzahl nur auf Bundeslandebene verfügbar ist, wird bei Auswahl eines Kreises die Hospitalisierung zum jeweiligen Bundesland angezeigt.

**Comment by Jo-Achim** [comment]
Then, for the sake of completeness, I would like to note that NINA apparently has the relevant information about the hospital traffic light, because the reference under contact details is: "In the district ... The hospital traffic light is green".
See: NINA v.3.4.0 -> "Corona rules for the district ..." ("Corona-Regeln für ..."), "Contact provisions" ("Kontaktbestimmungen"), 1st paragraph, last sentence, eg: "The hospital traffic light is green."
Or have I misunderstood something now?

But it doesn't really matter if the corona measures / restrictions relate to the state (instead of the district).

**Comment by Ein-Tim** [comment]
@Jo-Achim 

> Or have I misunderstood something now?

No, you haven't. Where can I find the hospitalizations in NINA? For me (iOS) NINA only shows the normal 7 day incidence.

**Comment by Jo-Achim** [comment]
> 
> Where can I find the hospitalizations in NINA? For me (iOS) NINA only shows the normal 7 day incidence.

NINA v 3.4.0 (Android): 

- Start NINA.
- Tap on "Corona-Regeln für den Landkreis XY".
- On "Corona-Regeln für den Landkreis XY" - screen, scroll down to "Kontaktbestimmungen" and you can read e.g.: 
"Im Landkreis XY gelten die Regelungen der Bayerischen Infektionsschutzmaßnahmen-Verordnung für eine Sieben-Tage-Inzidenz von über 35.
**Die Krankenhausampel steht auf GRÜN.**"

**Comment by Ein-Tim** [comment]
@Jo-Achim 

Thanks! Found it! 
But as CWA not only shows "Green/Yellow/Red" but the real number, I guess that's the reason why it is on federal state level.

**Comment by Jo-Achim** [comment]
Well, in my opinion, a number is hardly relevant. 
Because the color assessment of the hospital traffic lights (i.e. green, yellow, red) depends on the respective occupancy of the local intensive care units and is therefore the basis for local corona protective measures (i.e. mask requirement, contact restrictions, etc.).

**Comment by ndegendogo** [comment]
> "Im Landkreis XY gelten die Regelungen der Bayerischen Infektionsschutzmaßnahmen-Verordnung für eine Sieben-Tage-Inzidenz von über 35. Die Krankenhausampel steht auf GRÜN."

@Jo-Achim as far as I understand, the Bavarian "Ample" is specified on state level, not on district level. So it makes pretty sense to show the state level numbers. *(I don't know how the other Bundesländer have specified their Ampel)*.

**Comment by Jo-Achim** [comment]
Yes, it currently appears that the data for the hospital traffic light (in Bavaria) apply at the state level; not at the district level, as NINA suggests. See: [Explanation on the hospital traffic light](https://www.stmgp.bayern.de/coronavirus#kh-ampel) or [Important key figures for Bavaria at a glance" (LGL)](https://www.lgl.bayern.de/gesundheit/infektionsschutz/infektionskrankheiten_a_z/coronavirus/karte_coronavirus/index.htm#kennzahlen).

If we assume that it stays that way, this does not change the problem of numbers vs. traffic light colors. Because measures, based on numbers, should be communicated with traffic light colors for the sake of simplicity; see link above "Explanation of the hospital traffic light".
That means specifically:
For example, if I have configured a "Local 7-Day-Incidence Bavaria" display for Bavaria, a "Local 7-Day-Incidence Hospitalization Bavaria" could also be displayed, which then shows the incidence value plus the classification of this value as a traffic light color.
Alternatively, this information could also be displayed on the "Local 7-Day Incidence Bavaria" map, for example after redesign.

Should the hospital traffic light later apply nationwide or at the district level, the new "Local 7-Day-Incidence (Bavaria)" display named under "Alternative" could be used analogously for the displays of the "7-Day-Incidence (Bundesweit)" or "Local 7-Day-Incidence (Landkreis XY)”.

It is actually open how other federal states handle the hospital traffic light, because information is somehow difficult to find. However, as far as I know, the hospital traffic light is a nationwide definition to simplify the presentation of the situation for citizens. In this respect, appropriate information should be available somewhere (RKI?). 

**_PS:_**
However, it can also be that everything is not right and that we are acting at the level of our digitization here. I just added a couple of cities in different states to the locations in NINA. And indeed: NINA does not seem to have a 'hospital traffic light' for other federal states!

And other searches almost only return results for Bavaria; at least Berlin knows a "Corona traffic light", which apparently has little to do with the hospital traffic light.

**I'll leave the topic open, but we can leave it alone for the moment.** Perhaps something will change soon ;-), because that has little to do with consistent, uniform and understandable acting at the moment. Thanks to a wrong federalism at this point. Sometimes you don't have to be surprised about the reactions in public.

**Comment by Jo-Achim** [comment]
Small update:
From today, stricter corona rules apply in Bavaria because the hospital traffic light is now yellow. See: [Ampelstufe in Bayern jetzt gelb: Was ab heute gilt](https://www.br.de/nachrichten/bayern/corona-regeln-in-bayern-was-mit-der-ampelstufe-gelb-ab-sonntag-gilt,Snubsde).
And a 'regionalization' of the hospital traffic light is being discussed.

**Comment by Jo-Achim** [comment]
Small update - without wanting to lean too far out of the window again ...

The local (Bavarian) hospital traffic light (red / yellow / green) seems to become a nationwide **3-6-9 rule** in order to show the current hospital occupancy rates.
The hospital occupancy shown in this way should then, if necessary with the respective incidences, be the basis for the respectively valid corona protective measures.

We'll see how this develops - and how 'uniform' the result will be at the federal level.

**Comment by Ein-Tim** [comment]
The hospital traffic light doesn't really play an role anymore, so I guess this issue is obsolete, right?

**Comment by Jo-Achim** [comment]
Yes, it is obsolete now.
