### ISSUE TITLE
Make it easier to discover how to create own-events

### ISSUE THREAD

**Issue by alanrick** [corona-warn-app/cwa-wishlist#668]
Ref: #338 

## Current Implementation
To create your own event qr-code for others to check in to (such as a meeting or social get-together), you go to the "status" screen and scroll down several pages before a section is displayed "Planning an event" and then there is a "Create QR Code" button. I'd almost forgotten that this existed, and since the Baden-Württemberg rule-change spent ages trying to locate the button in the _Check in_ tab and the _Journal_ Tab, unsuccessfully.

## Suggested Enhancement
The "Create QR Code" button should be in the Check in tab. Perhaps directly under the "Scan QR Code".

![CWASelfCheckin](https://user-images.githubusercontent.com/7034358/138878417-bd31f029-af8a-46b0-a55b-051008197b87.png)

## Expected Benefits
I find the button very useful (after discovering it), particularly as it adds an entries to my Journal. By making this capability easier to discover it would be used more often by more CWA users.

**Comment by Ein-Tim** [comment]
Related issue:
- #469

**Comment by alanrick** [comment]
You're right.  I'd overseen the "event" terminology. 
Seeing as the identical suggestion was already made in May, at last this thread shows it's still an issue.
Closing it as a duplicate.
