### ISSUE TITLE
California Vaccine registry QR code "not a valid vaccination certificate" Will CA be added?

### ISSUE THREAD

**Issue by VWFeature** [corona-warn-app/cwa-wishlist#669]
I KNOW the app is for EU pharmacies- will you be adding US state records?

![Screenshot_20210623-103002](https://user-images.githubusercontent.com/7052879/123143728-b61ec580-d40f-11eb-9264-6f28376331c1.jpg)

FWIW, 
My data was in the Office of Personnel Management breach, including an FBI background check, so if you want to buy my data it's out there. 
But thanks to those who alerted me the QR code has unencrypted name and DOB in it.

---
Internal Tracking ID: [EXPOSUREAPP-8090](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8090)

**Comment by MikeMcC399** [comment]
@dsarkar 
This is a feature request which is not tied to Android, so it should be moved to https://github.com/corona-warn-app/cwa-wishlist.

It's about California, USA vaccine certificates.

**Comment by larswmh** [comment]
Closing this issue as its related internal ticket was set to `completed`.

> It is factually correct that anyone can have a vaccination certificate issued in Germany who has been vaccinated with vaccines that are approved in Germany and presents the required vaccination documentation.
> Practically, however, it looks more difficult here, since the issuance of vaccination certificates according to § 20i Abs. 3 S. 3 SGB V i.V.m. § 1 Abs1. of the Coronavirus vaccination regulation is only rewarded, if the e.g. person lives permanently in DEU, is insured in private health insurance or public health insurance or is employed in Germany.
> Accordingly, it is unlikely that certificates will be issued to persons who are not listed in Section 1(1) CoronaImpfV, as this will not be remunerated.
> The situation is similar with the case of trainees: These would have to present a certificate (internship contract, rental contract, etc.) stating that a longer stay (at least three to six months) in DEU is planned. Then a certificate could be issued if the person was vaccinated with a vaccine approved in DEU.
