### ISSUE TITLE
Group Certificate with "Firstname Lastname" and "Lastname Firstname"

### ISSUE THREAD

**Issue by Nio-av** [corona-warn-app/cwa-wishlist#671]
## Current Implementation
Certificates are grouped together as long as they are for the same Person. The group logic checks, if trim(firstname) and trim(lastname) are identical.

Some Certificate Authorities invert firstname and lastname. Therefore, these certificates aren't grouped together.

## Suggested Enhancement
Certificates are grouped even if firstname and lastname are mixed up. 

## Expected Benefits
Clean interface and grouped certificates.

**Comment by Nio-av** [comment]
Idee: Manuelle Clusterrung; Hilft z.B. bei unterschiedlichem Handling vom Zweitnamen

https://twitter.com/9lukas5/status/1477625249470586881?s=21

**Comment by Ein-Tim** [comment]
Related issue:
- #705

**Comment by Ein-Tim** [comment]
FYI: iOS PR https://github.com/corona-warn-app/cwa-app-ios/pull/4179 starts working on an automatic solution, e.g. filtering out "Dr." ([link to code](https://github.com/corona-warn-app/cwa-app-ios/pull/4179/files#diff-301ce2b909539e9b152de45bc1275cb29e09382c1c9c7d645f9a55efbef34c09R100)).

**Comment by larswmh** [comment]
Closing this ticket as this was implemented in version 2.19 of the Corona-Warn-App. 
See [FAQ](https://www.coronawarn.app/en/faq/results/#cert_fault_tolerant_name_handling) or [Blog](https://www.coronawarn.app/en/blog/2022-03-16-cwa-2-19/)

---
Corona-Warn-App Open Source Team
