### ISSUE TITLE
Twitter Suggestion: Show whether an increased risk is shown because of multiple encounters with low risk or because of one encounter direct on the risk card

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#674]
## Current Implementation
To find out whether one has an increased risk because they had a long or/and close contact to one person or because they had multiple encounters with low risk, one has to click on the contact journal. Only there the app shows this information.

## Suggested Enhancement
Show whether an increased risk is shown because of multiple encounters with low risk or because of one encounter direct on the risk card.

## Expected Benefits
Users see all relevant information directly on the risk card and don't have to switch to the contact journal. 

## Additional Information
This report is based on feedback from a Twitter user: https://twitter.com/fliggerit/status/1456720731153342466?s=20

---
Internal Tracking ID: [EXPOSUREAPP-13524](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13524)

**Comment by Ein-Tim** [comment]
This issue stayed unmirrored to JIRA for a prolonged period of time. Please mirror it to JIRA now.

**Comment by Ein-Tim** [comment]
Please mirror this issue to JIRA now @dsarkar / @larswmh.

**Comment by larswmh** [comment]
Thanks for your enhancement request @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-13524](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13524)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
