### ISSUE TITLE
[Enhancement] hospitalization / traffic light

### ISSUE THREAD

**Issue by kevin-kraus** [corona-warn-app/cwa-wishlist#681]
## Current Implementation

Currently only the **daily** change in Hospizalization is shown in the Statistics Widget.
## Suggested Enhancement

The Bavarian corona rules are currently no longer based on incidence but on two key figures:
- Corona patients who were admitted to the hospital in the last 7 days (intensive care unit or normal ward).
- Corona patients who are treated in the intensive care unit.

These would need to be displayed in the statistics widget so that users can understand the current status of the Corona traffic light.
## Expected Benefits

Users of the app could determine which kind of warning
Users could more easily find out which warning level is currently in effect according to the Corona traffic light via the statistics widget. 

---

Internal Tracking ID: EXPOSUREAPP-10668

**Comment by Ein-Tim** [comment]
Related issue: 

- #663

**Comment by kevin-kraus** [comment]
> Related issue: 
> 
> 
> 
> - #663

I have explicitly not asked for a implementation / display of the so called "corona traffic light" as I think it would not be required to show the status. 
Especially because as far as I know only Bavaria uses this system at the time, it would be a feature that only benefits Bavarian citizens. 

What do you think of it?

**Comment by Ein-Tim** [comment]
Quote from the OP of #663:

> In order to draw conclusions about the local measures / restrictions with the help of the CWA against this background, the data of the "local hospital occupancy" and their processing would also be required.

This is, IHMO, nearly the same as what is suggested here.

---

When I mention related issues, I do not mean that this and the related issue should be merged, I just want to give the author of the issue a short feedback that there is already an issue which talks about a similar thing.

I would recommend to leave this issue open for now, except if the Open-Source-Team tells otherwise (:

**Comment by svengabr** [comment]
Internal Tracking ID: EXPOSUREAPP-10668

**Comment by kevin-kraus** [comment]
@svengabr Is there any possibility to see the progress on those internal tracking id's? (e.g. planned for implementation etc.)

Or are those only visible to the CWA-developer team?

**Comment by larswmh** [comment]
Closing this issue as the related internal ticket is set to `obsolete`.

Developer comment:

> This is exactly what the CWA shows:
> 
> - 7-Day Incidence for Hospitalization
> - Covid-19 Patients in Intensive Care Units
