### ISSUE TITLE
Add the „Received Warnings“ figure from the analysis page to the statistics section in the app

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#682]
## Current Implementation
Currently, the "Received Warnings", shown on https://www.coronawarn.app/en/analysis/ are not visible in the apps statistics section.

## Suggested Enhancement
Add the "Received Warnings" figure from https://www.coronawarn.app/en/analysis/ to the apps statistics section.

## Expected Benefits
Users can see how many other users were warned. With this we clear up some prejudices like "The app does not work, nobody ever got a warning" & "The app is broken, I see green all the time".
This would take only little effort and may make at least a little difference in the public perception of the app.

---
Internal Tracking ID: [EXPOSUREAPP-11245](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11245)

**Comment by larswmh** [comment]
Thanks for your suggestion @Ein-Tim. Internal Tracking ID: [EXPOSUREAPP-11245](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11245)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
