### ISSUE TITLE
Add new statistic tile: Booster Shots administered

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#685]
## Current Implementation
The app does only show:
- "People Who Have Received at Least One Vaccine Dose"
- "People Who Are Fully Vaccinated"
- "Vaccine Doses Administered"

## Suggested Enhancement
Add a new statistic tile:
- "People Who Have Received a Booster Vaccine Dose"

## Expected Benefits
People are informed how many booster vaccination shots were administered.

---
Internal Tracking ID: [EXPOSUREAPP-10832](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10832) duplicate of
Internal Tracking ID: [EXPOSUREAPP-10765](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10765) Android
Internal Tracking ID: [EXPOSUREAPP-10614](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10614) iOS

**Comment by larswmh** [comment]
Hi @Ein-Tim, thanks for your suggestion. We have created an internal ticket and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-10832](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10832)

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-10832](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10832) duplicate of
Internal Tracking ID: [EXPOSUREAPP-10765](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10765) Android
Internal Tracking ID: [EXPOSUREAPP-10614](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10614) iOS

**Comment by Ein-Tim** [comment]
Seems like this is planned for one of the next releases: https://github.com/corona-warn-app/cwa-server/pull/1641

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-app-ios/pull/4052

**Comment by MikeMcC399** [comment]
@Ein-Tim 

This item has been implemented. See https://www.coronawarn.app/en/blog/2022-02-02-cwa-2-17/ announcement for CWA 2.17 released on Feb 2, 2022.

**Comment by Ein-Tim** [comment]
Thanks for the reminder @MikeMcC399! 

Closing this issue.
