### ISSUE TITLE
Vaccination certificate from another country

### ISSUE THREAD

**Issue by vforchi** [corona-warn-app/cwa-wishlist#686]
## What is missing

I couldn’t find if the app supports loading certificates generated in other EU countries, and if it’s possible to mix them up. For example, if one gets the first two doses in Germany and the booster in Italy or Spain.

## Why should it be included

Considering that we will probably get one dose every 6 to 12 months, more and more people will have a mix situation and would like to make sure that the app supports it.

## Where should it be included

Not sure.

**Comment by MikeMcC399** [comment]
@vforchi

The app refers to the certificates as "EU digital COVID certificates" and the FAQ https://www.coronawarn.app/en/faq/#eu_dcc_which says:

"The [EU Digital COVID Certificate Regulation](https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/safe-covid-19-vaccines-europeans/eu-digital-covid-certificate_en) entered into application on July 1, 2021 and the certificates will be accepted in all EU Member States."

You can also get to the FAQ from the tile on the Status page.

So I think your request is already explicitly answered by the [FAQ -  Which EU certificates are supported?](https://www.coronawarn.app/en/faq/#eu_dcc_which).

**Comment by vforchi** [comment]
Sorry about this, I did look in the documentation, but couldn’t find it.
Thanks for the quick reply.
