### ISSUE TITLE
Delete contact journal location when the check-in is deleted

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#688]
## Current Implementation
The contact journal location which is created when one checked in to an event and did not deactivate that a contact journal entry should be created, is not deleted after 16 days but stays in the contact journal (as selectable) forever.

## Suggested Enhancement
Delete the contact journal location together with the check in after 16 days.

## Expected Benefits
Cleaner contact journal for the user.

---
Internal Tracking ID: [EXPOSUREAPP-11244](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11244)

**Comment by sebastianbrinkmann76** [comment]
Good idea! :)

**Comment by larswmh** [comment]
Thanks for your suggestion @Ein-Tim. Internal Tracking ID: [EXPOSUREAPP-11244](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11244)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
