### ISSUE TITLE
Improve your development process

### ISSUE THREAD

**Issue by HolgerMayer** [corona-warn-app/cwa-wishlist#69]
## Current Implementation

During the development of the first release I saw several points in the development process and the resulting issues that lead to my opinion that there is some software development process improvement not only possible but would help the overall project.

## Suggested Enhancement

1) Use your development process more transparent

In the release press conference it was mentioned, that you use Scrum. In the scoping document you describe epics and use stories. But these are not visible in the development nor the testing.  

You should:
- use  the project feature of GitHub to manage what user stories are currently implemented / improved and which ones are on backlog
- use user story id's in the git comments when commiting 
- create automatic tests for user stories with reference to these (see 3 below)

2) think about where your system borders are

It is obvious, that the QR code infrastructure is not working well. Here the system border was defined to narrow. The creation and distribution of QR codes ist part of the overall system.  This is a very common mistake during system development when parts that doesn't need software development, are excluded from the system view. The same has been true with the first version concerning the lab interface. Here it was solved later with the introduction of the test result server.

You don't need to  follow the whole V-Model. But in general it is important that in a first draft a high level specification entities that will not get a new software should be described too. 

3) test, test, test

Do more automatic testing. Even if you don't follow a test first methology, it is important to write tests early. The developer has a mental model of what he will implement. The test gives a different perspective concerning what he implements. So the test helps to see if mental model, implementation and tests fit. 
If some third person tests the code later, she got a different mental model of what the software should do. Worst case it leads to a tests that verifies the existing code does what the existing code does not what he should do. This is especially happening because of the truly bad comments in the code.

- code should be accepted into the repository only together with unit tests.
- create user story snippet tests for subsystems
- create automatic UI-Tests for user stories
- publish these tests in GitHub !

and finally - do at least peer reviews of code and commenting. 

## Expected Benefits

1) use your development process more transparent

- you will get reduced issues concerning what you are currently doing and when which feature will be available.
- you will get an at least minimal requirement tracing change process
- you will get a repeatable tested system which improves quality during your release cycles

2) think about where your system borders are
- you reduce the risk of late rework
- you can schedule features for a later release more easily
- members of the project team get a high level view on all components - developed or existing

3) test, test, test

in the long run easier refactoring, introduction of new features and overall better quality

-------------------
Internal Tracking Id: EXPOSUREAPP-2128

**Comment by SebastianWolf-SAP** [comment]
Thank you very much for your proposal. The release information is currently available on GitHub at https://github.com/corona-warn-app/cwa-app-android/releases. We will see if and how we can include all (or parts) of the information also in other places.

This idea is one of these feature ideas or enhancements. Consequently, we will move this issue to cwa-wishlist and allow the community and you to further refine it, discuss pros and cons, and evaluate alternatives.

The issue will not be closed in this repository to ensure long-term visibility. All issues in the cwa-wishlist repository will be discussed with our contracting entities. They will decide whether they will be implemented or pursued further. As soon as we have any updates, we will let you know about the details.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by larswmh** [comment]
Closing this issue as the related internal ticket is set to `completed`.
