### ISSUE TITLE
Show how many people are in ICU ("Auslastung Insgesamt")

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#691]
## Current Implementation
The app only shows how many people infected with COVID-19 are in ICU in hospitals, but not how many people are in ICU in total. 

## Suggested Enhancement
Show:
- How many people are in ICU because of COVID-19
- How many people are in ICU in general
- How many free % of ICU capacity are available

## Expected Benefits
Users are misinterpreting the number of people on ICU because of COVID-19. They think that these % are all people who are in ICU & forget that there are also non-COVID patients in ICU.

---
Internal Tracking ID: [EXPOSUREAPP-10983](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10983)

**Comment by svengabr** [comment]
Internal Tracking ID: EXPOSUREAPP-10983

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
