### ISSUE TITLE
Show trajectory („Verlaufskurve“) of statistics

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#692]
## Current Implementation
The app shows the statistics only with the latests values available and with an trend indicator (arrows).

## Suggested Enhancement
Add the trajectory to the statistics. Users are then able to see whether, e.g. in the past two weeks (the period of time should be selectable by the user), more or less people came into ICU.

## Expected Benefits
The user is better informed and sees whether the situation is getting better (lower incidence than in the past 2 weeks, less people are coming into ICU, more people are getting vaccinated, etc.) or worse (incidences on the rise, more people in ICU, less vaccination than in the last weeks, etc.).

---
Internal Tracking ID: [EXPOSUREAPP-11243](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11243)

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Although the following is not about the exact statistic you are requesting a trend in, you can find something similar on:

- [Corona-Warn-App (CWA): Kennzahlen](https://www.coronawarn.app/de/analysis/) (in the list of links at the bottom of the page: RKI: Covid-19-Trends (DE)) => 
- [RKI: Covid-19-Trends in Deutschland im Überblick](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/COVID-19-Trends/COVID-19-Trends.html?__blob=publicationFile#/home) => 
- Krankheitsschwere

This is selectable by 1, 2 or 3 months or complete timeframe.

**Comment by larswmh** [comment]
Thanks for your suggestion @Ein-Tim. Internal Tracking ID: [EXPOSUREAPP-11243](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11243)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
