### ISSUE TITLE
Export/Import data - in case I have a new device

### ISSUE THREAD

**Issue by imbalino** [corona-warn-app/cwa-wishlist#693]
## Feature description
Hi there,
the feature I would like to see is an "export data" function I can use on my old phone, and an "import data" function I can use when freshly installing the CWA on a new device.

## Problem and motivation

I recently bought a new phone. Now I have to carry both the new phone and the old phone with me for 14 days. This is quite cumbersome and I think most people don't even think about it when switching devices.

My reasoning behind this is:
* My old phone contains the tracking data and all encounters of the last 14 days.
* My new phone will start tracking and recording all my encounters from today on
* If I test positive tomorrow -> how do I notify the people I encountered in the last 14 days **and** the people I encountered since I started using CWA on my new phone? I think I can't scan the positive test result in both my new phone and my old phone's CWA.
* If somebody I encountered in the last 14 days tests positive -> how can I get notified without having to check the CWA on my old phone for the next 14 days?

The solution would be to have a data export/import feature which I can use to transfer the data from one phone to another. As the CWA does not use a centralized server to store all IDs and encounters (as far as I understand), I would need to transfer the export file manually from one device to another. Maybe there is even an elegant solution where I have to scan a QR code from my old phone with my new phone to transfer the data.  

## Is this something you're interested in working on

I'm open for clarification questions

**Comment by Ein-Tim** [comment]
Related issue:
- #8

**Comment by Ein-Tim** [comment]
> how do I notify the people I encountered in the last 14 days and the people I encountered since I started using CWA on my new phone? 

This question is answered in https://www.coronawarn.app/en/faq/#test_multiple_devices.

**Comment by imbalino** [comment]
Thanks for the hint to the FAQ. I guess this can be closed as duplicate.
