### ISSUE TITLE
Zusätzlich den Ort des Kontakts aufzeichnen

### ISSUE THREAD

**Issue by morber13** [corona-warn-app/cwa-wishlist#700]
## Current Implementation

Es werden nur die IDs der Kontakte gespeichert, nicht der Ort

## Suggested Enhancement

Zusätzlich zu den IDs der Kontakte sollte auch der jeweilige Ort aufgezeichnet werden. Auch diese Daten bleoiben lokal auf dem Smartphone des Users. Datenschutz ist also gewährleistet.

## Expected Benefits

Wird ein Risikokontakt ermittelt, kann auch der zugehörige Ort des Kontakts angezeigt werden. Das erlaubt dem Benutzer, das jeweilige Risiko genauer einzuschätzen.

Beispiel: An einem Tag war ich 
1) im Impfzentrum und habe längere Zeit mit vielen Menschen in der Warteschlange gestanden. Allerdings wurde durchgehend Maske getragen.
2) An demselben Tag war ich abends in einem Restaurant, in dem konsequent 2G kontrolliert wurde. 

Falls der Kontakt bei 1) stattfand, kann ich die Warnung ignorieren, weil alle beteiligten durchgehend Maske trugen. Bei 2) könnte es kritischer aussehen, weil am Tisch die Masken abgenommen wurden.

Dieses Feature sollte vom Benutzer abgeschaltet werden können. So werden auch sehr vorsichtige Benutzer zufriedengestellt.

**Comment by Ein-Tim** [comment]
Related issues:

- #288
- #206 
- #266

---

@morber13 

Danke für den Vorschlag! Die Corona-Warn-App greift auf das Exposure Notification Framework / System von Apple & Google zurück. Dieses zeichnet die Bluetooth Low Energy Beacons auf und speichert dieses ab. Die Corona-Warn-App hat auf diese keinen Zugriff, kann also auch nicht den Ort hinzufügen.
Dieses Feature müssten also von Apple & Google implementiert werden.

In #288 findest du viele Interessante Kommentare zu diesem Thema. 

Schönen Sonntag noch!

**Comment by morber13** [comment]
Aber das Abspeichern selbst macht doch die App? Dann könnte sie doch die Low Energy Beacons nehmen und in eine Struktur packen, die noch den Standort aufnimmt. Oder wo ist da das Problem?

**Comment by Ein-Tim** [comment]
@morber13 

Nein, die Schnittstelle von Apple & Google speichert die Bacons ab. Die App hat keinen Zugriff darauf.

**Comment by morber13** [comment]
Ok, und wer holt sie zum Abgleich wieder raus? (Nur für mich zum Verständnis; das würde das Problem auch nicht lösen)

**Comment by Ein-Tim** [comment]
@morber13 Die CWA lädt die positiv Schlüssel vom Server, übergibt sie der Schnittstelle, diese gleicht ab ob Schlüssel die dein Gerät empfangen hat als positiv markiert wurden. Sollte das der Fall sein bekommt die App alle Informationen zur Begegnungen (Dauer, Entfernung (in db), Tag). Die App selber hat aber niemals Kontakt mit dem empfangenen Schlüsseln. 

Das ist jetzt natürlich vereinfacht dargestellt, die ganze Dokumentation findest du hier: https://github.com/corona-warn-app/cwa-documentation

**Comment by morber13** [comment]
Ist das so für die CWA mit Google und Apple ausgehandelt worden, um die Skeptiker zu beruhigen?

**Comment by Ein-Tim** [comment]
@morber13 

Nein, Apple & Google haben zu Beginn der Pandemie ein Framework für Apps wie die CWA zur Verfügung gestellt. Weitere Infos: https://developer.apple.com/exposure-notification/

**Comment by morber13** [comment]
Nochmal nachgefragt: Es würde schon sehr helfen, wenn man den genauen Zeitpunkt (nicht nur den Tag) der Begegnung mitgeteilt bekommt. Nach Überfliegen der genannten Issues habe ich den Eindruck, dass auch die Aufzeichnung des Tags erst später implementiert wurde.
Was spricht gegen die Aufzeichnung des genauen Zeitstempels? Hierfür dürfte es eigentlich keine Akzeptanzprobleme geben - im Gegensatz zur Aufzeichnung des Standorts?
Falls bereits eine Erweiterung des ENF / ENS beantragt wurde: Wie ist jetzt der Stand?

**Comment by Ein-Tim** [comment]
@morber13 

> Nach Überfliegen der genannten Issues habe ich den Eindruck, dass auch die Aufzeichnung des Tags erst später implementiert wurde.

Der Tag von Risiko-Begegnungen wurde schon seit Version 1 der oben erwähnten Schnittstelle an die CWA weitergegeben, er wurde nur bis version 1.9 der CWA als relative Angabe ("Letzte Begegnung vor x Tagen") und nicht als absolute Angabe ("Letzte Begegnung am dd.mm.yyyy") angegeben. 
Das Datum von Begegnungen mit niedrigem Risiko wird auch schon immer der CWA weitergeben, wird aber erst seit Version 1.13 auch dem Nutzenden angezeigt (siehe https://github.com/corona-warn-app/cwa-wishlist/issues/178).

> Was spricht gegen die Aufzeichnung des genauen Zeitstempels? Hierfür dürfte es eigentlich keine Akzeptanzprobleme geben

Unter Umsänden schon, da so die Warnende Person deutlich einfacher deanonymisiert werden kann als wenn nur das Datum der Begegnung angezeigt wird.

**Comment by morber13** [comment]
Dieses Feature wird also in absehbarer Zukunft nicht kommen? Dann ist die CWA nutzlos. Ich kenne einige Leute, die sie abgeschaltet haben, weil sie letztens nur nervt und keine wirklich weiterführenden Informationen liefert.

**Comment by Ein-Tim** [comment]
Ich habe keinen Einblick in die Entwicklung, da ich auch nur aus der Community bin. Ganz generell kann ich aber sagen: Wenn Apple & Google die Schnittstelle nicht so erweitern, das auch der Zeitpunkt der Begegnung erfasst bzw. an die Apps weitergegeben wird, kann dieses Feature nicht in die CWA implementiert werden.

Ich halte die App nicht für nutzlos deswegen, im Endeffekt kann ich mich eh nicht daran erinnern wo ich am vorletzten Samstag um 17:31 Uhr war, also lasse ich mich einfach so oder so bei rot Testen, egal ob da jetzt die Uhrzeit auch noch steht oder nicht.

**Comment by morber13** [comment]
Na ja - "einfach so testen" ist ja nicht. Ich bin am Sa. gegen Mittag zum Testzentrum, das (zum Glück negative) Testergebnis bekam ich eben (Mo. 16:15). Hätte ich alles sehr ernst genommen, hätte ich mich das ganze Wochenende in Quarantäne begeben, alle Verabredungen abgesagt und gezittert... Leider scheinen die Labors am Wochenende nicht zu arbeiten.
Wenn ich Zeit (und daher auch Ort) der Begegnung gewusst hätte, hätte ich mir das alles sparen können - inklusive des ekligen Würgereizes beim Testen.

**Comment by Ein-Tim** [comment]
@morber13 Aber glaubst du du hättest dich genau erinnern können was genau du um z.B. 16:37 Uhr gemacht hast? Ich könnte das nicht (und ich benutzte das Kontakt-Tagebuch in der CWA, das beinhaltete aber ja nicht die genauen Uhrzeiten sondern nur Zeiträume). 

Im Endeffekt ist das auch egal, da es technisch einfach nicht möglich ist, also lass uns nicht diskutieren (:

**Comment by jucktnich** [comment]
Related: https://github.com/corona-warn-app/cwa-wishlist/issues/701

**Comment by Ein-Tim** [comment]
Also related: #266
