### ISSUE TITLE
Twitter Suggestion: Pressing on "Nicht mehr Anzeigen" on expired RAT should show a hint that the test result is transferred into the recycle bin 

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#703]
## Current Implementation
Currently, if a user has a RAT registered in the app and it's older than 48h, the "Status" page of the app shows this: 

<img src="https://user-images.githubusercontent.com/67682506/143917132-55fff352-7f4b-4666-a485-93ff7a2e3e1c.jpeg" width="300">

Clicking on "Nicht mehr Anzeigen" directly transfers the test result into the recycle bin without any notice displayed to the user. 

## Suggested Enhancement
A hint should be shown that the result is transferred to the recycle bin.

## Expected Benefits
This helps the user to understand what happens. Some users might search for the test result afterwards but don't find it anymore. 

---
Internal Tracking ID: [EXPOSUREAPP-10775](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10775)

**Comment by larswmh** [comment]
Hi @Ein-Tim, thanks for forwarding this Twitter suggestion. We have created an internal ticket and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-10775](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10775)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
If I understand [this](https://github.com/corona-warn-app/cwa-app-android/pull/4495) PR correct, it is not the intention to move RATs to the recycle bin if they are outdated? 

Can you confirm @larswmh?

**Comment by larswmh** [comment]
Good morning @Ein-Tim, I can confirm that this is intended.

Best wishes,
LW

**Comment by Ein-Tim** [comment]
@larswmh 

Okay, thanks. Closing.
