### ISSUE TITLE
Add a new pop up screen which asks for confirmation before importing a certificate

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#706]
## Current Implementation
Scanning an EU digital COVID certificate directly imports it, without asking the user whether the intention is really to import it or to verify if. 

## Suggested Enhancement
The following is a concrete suggestion for solving #666 & also partly what has been described in #698.

When a user scans a certificate with the app, a new pop up screen should be shown, where the user has to confirm that the intuition really is to import a certificate and not to verify it.
As an example, I suggest to take a look at how it's implemented "AntiCovid":

<img src="https://user-images.githubusercontent.com/67682506/143941316-a2bf7025-baa2-4e59-a737-791eccf52f25.PNG" width="300">

## Expected Benefits
This change would lower / nearly mitigate that the CWA is used to "verify" DCCs from other people. 

---
Internal Tracking ID: [EXPOSUREAPP-10826](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10826)

**Comment by larswmh** [comment]
Hi @Ein-Tim, thanks for your suggestion. We have created an internal ticket and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-10826](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10826)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@larswmh 

What's the Prio of this internal ticket? Low, I assume? You might want to transfer these articles into the internal ticket and decide again on the Prio. 

Article one: https://www.ksta.de/koeln/datenspeicherung-koelner-gastwirt-warnt-vor-corona-warn-app-bei-2g-kontrollen-39197126

Article two: https://www1.wdr.de/nachrichten/rheinland/barbesitzer-deckt-sicherheitsluecke-corona-warn-app-auf-100.html

@thomasaugsten Can we expect any UI improvement here in the next releases?

**Comment by dsarkar** [comment]
@Ein-Tim We will look at this. Thanks.

**Comment by Ein-Tim** [comment]
I meanwhile consider this as implemented with version 2.15.

**Comment by Ein-Tim** [comment]
I changed my mind, a pop-up screen like CovPass has it would be better than the current solution. Reopening.

**Comment by Ein-Tim** [comment]
Changed my mind again, CWAs solution is fine.
