### ISSUE TITLE
Replace quick action to Check In with one which opens the universal QR code scanner

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#707]
## Current Implementation
The quick action "Check In" opens the UQS where all supported QR codes can be scanned.

## Suggested Enhancement
Rename the quick action to "Scan QR code" and let it open the universal QR code scanner. 

## Expected Benefits
It becomes clearer to the user that the scanner which is opened by pressing on "Check In"  on the quick action is actually opening a QR code scanner where all kinds of QR codes can be scanned. Also, the icon in the quick action menu was not replaced with the new check in icon which is used since version 2.12.

---
Internal Tracking ID: [EXPOSUREAPP-10957](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10957)

**Comment by svengabr** [comment]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/4686874/145194842-4c70df89-fd2d-494f-997d-d957db2db503.png)

**Comment by svengabr** [comment]
Internal Tracking ID: EXPOSUREAPP-10957

**Comment by svengabr** [comment]
Thanks for your suggested enhancement @Ein-Tim

I did forward this to the team.

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-10957](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10957)

**Comment by dsarkar** [comment]
@Ein-Tim I suggest you change the title to: 

Rename the quick action to "Scan QR code"

**Comment by Ein-Tim** [comment]
@dsarkar 

I can do this, but then this would be just a text change, but it's more. If just the text is changed the user still is directed to the Check-in tab (and there the UQS is opened), although the intention was to only open the UQS. 

You know what I mean?

**Comment by dsarkar** [comment]
@Ein-Tim OK, I see. App should stay in current tab and not switch.

**Comment by Ein-Tim** [comment]
This has been implemented. Therefore closing this issue.
