### ISSUE TITLE
Store and track PCR test results for children who do not have own phone

### ISSUE THREAD

**Issue by joernpeller** [corona-warn-app/cwa-wishlist#709]
## Feature description
It would be neccessary to add a feature adding test results for other persons that do not go into the personal warning tracking.

## Problem and motivation

As a parent of a child who needed to be tested by the pediatrician with a PCR test I want to be able to track her/his test progress. 

## Is this something you're interested in working on

---
Internal Tracking ID: [EXPOSUREAPP-10986](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10986)

**Comment by Ein-Tim** [comment]
Good Morning @joernpeller 👋

Just to get you right, your problem isn't that you can't add your PCR test and the one from your child to the app at the same time?

If this is your problem, when registering the test result of your child, you're able to not allow automatic warning in case the test returns positive.

---

Below you find some related issues:

Related to the closed issue: #200

However, #200 was [declined](https://github.com/corona-warn-app/cwa-wishlist/issues/200#issuecomment-824802492) with the following reason:
> The reason for this is that the main reason for receiving a test is sharing the result and warning others. Entering a test result of another family member and sharing the result should not be the focus of the app, because then the random IDs collected by the device do not correspond to the persons the familiy member met.

But as you especially mention that these test should not go "into the personal warning track", I don't think this is a duplicate. 

Another related issue, which is still open, is 

- #623

**Comment by svengabr** [comment]
Internal Tracking ID: EXPOSUREAPP-10986

**Comment by Ein-Tim** [comment]
FYI: It seems like there is something planned for 2.21: https://github.com/corona-warn-app/cwa-app-android/pull/4947

**Comment by Ein-Tim** [comment]
FYI: This has been implemented in version 2.21: [Corona-Warn-App Version 2.21 now allows test management for family members](https://www.coronawarn.app/en/blog/2022-04-19-cwa-2-21/).

**Comment by joernpeller** [comment]
Great! Thanks for implementing this functionality!

**Comment by Ein-Tim** [comment]
@joernpeller Could you close this issue now, please?

**Comment by joernpeller** [comment]
Done
