### ISSUE TITLE
Map of Risk Contacts

### ISSUE THREAD

**Issue by JulianAnders** [corona-warn-app/cwa-wishlist#714]
## Feature description

As high risk contact person i want to know where the contact happened, in order to prevent future contacts or to avoid risky places. I therefore like to have a map view that shows where the contact that led to the status change has been tracked. In order to keep the data security standards, this can be done locally on the devices by saving a GPS location with every contact locally. 

## Is this something you're interested in working on

 Yes

**Comment by Ein-Tim** [comment]
This is not possible, see #700.

**Comment by JulianAnders** [comment]
@Ein-Tim danke dir. den issue hatte ich gar nicht gefunden. schade, dass das technisch derzeit nicht möglich scheint.

**Comment by dsarkar** [comment]
@JulianAnders Danke erst mal, hier teilzunehmen. Es ist tatsächlich nicht nur eine Frage der technischen Umsetzbarkeit, sondern auch den hohen Datenschutz-Ansprüchen gerecht zu werden. 

---
Corona-Warn-App Open Source Team

**Comment by jucktnich** [comment]
Für den Datenschutz: https://github.com/corona-warn-app/cwa-wishlist/issues/701
