### ISSUE TITLE
Verifying passport and saving it in app 

### ISSUE THREAD

**Issue by claravoss** [corona-warn-app/cwa-wishlist#716]
## Feature description

In other environments, passport verification is already widely used (e.g. online insurance/ online banking/ etc via AI verification or PostIdent).

It would be amazing if the user could do that and save the verification and the used passport pictures in the app.

Then when a QR code is checked, the checker sees the passport pictures and the verification. If the picture matches, the person doesn't have to also show the passport.

## Problem and motivation
This would save a lot of time when checking QR codes.

Specific steps:

1. User requests passport validation
2. User takes pictures/ videos of passport and himself/herself
3. Pictures/Videos are saved in app
4. Pictures or videos are used for Validation via Internet or PostIdent
5. App get notification of verification
6. App saves pictures/videos with QR code

When scanning:
1. User shows QR code
2. Scanner scans QR code and scrolling down can see a validated passport and the pictures/videos used for validation
3. Scanner will look at the person and verify if same person

## Is this something you're interested in working on

No

**Comment by Ein-Tim** [comment]
Good Morning @claravoss 

Thanks for the suggestion! I suggest to take a look at https://github.com/corona-warn-app/cwa-wishlist/issues/459, as this is quite similar. 

It would be nice to not multithread the discussion but try to stay in one issue, e.g. #459.

If you think this issue can be closed in favor of #459, it would be great if you would so!

**Comment by svengabr** [comment]
Thanks for your suggestion @claravoss 

Since #459 was declined already, it would not make sense to re-open the topic at the current time.

To keep the board clean I would like to close the issue.
