### ISSUE TITLE
Corona Scanner Missbrauch Schutz

### ISSUE THREAD

**Issue by Crajs20** [corona-warn-app/cwa-wishlist#717]
In Bars und Geschäften wird oft die Corona Warn App zur Besucher Kontrolle genutzt und die Zertifikate direkt gespeichert.
https://www.ksta.de/koeln/datenspeicherung-koelner-gastwirt-warnt-vor-corona-warn-app-bei-2g-kontrollen-39197126

Um dies zu verhindern könnte die App ein Zeit Counter für den Scanner haben.

Wenn kein Zertifikat gespeichert ist, können zwei Weitere  in einer Minute gescannt werden, 2. Impfungen und Booster Inpfungen, wenn Erstimpfubg vorhanden sofort hinzugefügt werden. Werden zu viele Zertifikate in einer Minute oder weniger gescannt sollte ein Hinweis mit dem Hinweis auf die CocPass Check App angezeigt werden.

Idea for a timer on the certificate scanner to limit the number of scan, which can be done in a specific time frame. ~ in 1 minutes only two 1. certificate can be scanned, additional 2nd or booster certificate, if 1st certificate is saved is still possible.
If the max scan numbers is reached, a warning should be displayed and a link to toe CovPass Check should be visible.

---
Internal Tracking ID: [EXPOSUREAPP-10969](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10969)

**Comment by Ein-Tim** [comment]
Verwandte Issues: 

- #706
- #666

**Comment by DanAmt** [comment]
Sollte dringend behoben werden ! Weitere Idee ist die Anzahle der Certs zu limitieren. zB 10 pro App sollte für die meisten Familien reichen. Die obige Timelimit Lösung ist auch sehr gut. Vllt beides,.

**Comment by DanAmt** [comment]
Do we need to translate this into English ?  @Ein-Tim ?

**Comment by Ein-Tim** [comment]
@DanAmt With the issues #706 & #666 I don't think a translation in English is necessary. The issue should be clear.

**Comment by DanAmt** [comment]
Weiter zum Feature: Falls der/die Usende durch Ratelimit oder Timelimit geblockt wird, sollte er/sie einen Hinweis auf CovPass Check App mit Link zum AppStore erhalten, nicht nur Fehlermeldung.

**Comment by DanAmt** [comment]
This issue is likely relatively easy to fix and has some potential of bad PR.

**Comment by Crajs20** [comment]
thanks a lot for the comments - I add an English comment to the 1st post and will follow in english.
I don't have an overview about potential bad PR - but to protect the owners of the scanned certificates and help the scanning people for a misusage of the app, a technical optimization should be implemented.

**Comment by DanAmt** [comment]
Bad PR started today with above newspaper article. Might get worse. I also
agree about the protection against this gotcha.

Am Mi., 8. Dez. 2021 um 21:30 Uhr schrieb Crajs20 ***@***.***

**Comment by parttimehorse** [comment]
This story has also shown up at WDR ([Link](https://www1.wdr.de/nachrichten/rheinland/barbesitzer-deckt-sicherheitsluecke-corona-warn-app-auf-100.html)) today. 

Of course, this is a user error and not a flaw with the app, but judging rom the KStA article... 

_"Die Zertifikate auf seinem Smartphone stammen von seinen Gästen, die er im Rahmen der 2G-Kontrollen per App überprüft hat. "_

_"Er habe von Sicherheitsleuten schon oft gehört: „Das ist total lästig – ich muss ständig diese ganzen QR-Codes von den Gästen von meinem Smartphone löschen!“"_

If this is really a more common user error / misconception than one would assume, I'd suggest giving the scan function description text a clarification do-over asap (e.g. declaring that this will import the certificate, and that CovPassCheck should be used for verification purposes) or do a confirmation pop-up on each import (which then also can refer to CovPassCheck in case the user was trying to verify codes).

**Comment by Crajs20** [comment]
Here also a video from WDR TV
[https://www1.wdr.de/mediathek/video/sendungen/lokalzeit-koeln/video-missbrauch-mit-impfzertifikaten-per-warn-app-100.html](url)

**Comment by DanAmt** [comment]
I would really recommend a technical barrier to prevent this from happening. (Bright yellow warning screen as suggested in #706, time limit, limit number of certs that can be imported or similar effective method)

**Comment by dsarkar** [comment]
Dear @DanAmt @Crajs20, dear community,
thanks for the discussion here, we will look at this.

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-10969](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10969)

**Comment by vaubaehn** [comment]
Hi all,
the issue will obviously be solved soon: According to first PRs found in the CWA repos, it looks like after 10 persons' DCCs are stored in the CWA, scanning another one will display a warning. After storing 20 persons, no new person's DCC will be stored.
This will a) limit the number of persons that can be affected by the misuse of the CWA, and b) notify the host of a venue or an event to use CovPassCheck instead. The number of persons can be adapted via remote-app-config.
Related PRs:
https://github.com/corona-warn-app/cwa-app-android/pull/4502
https://github.com/corona-warn-app/cwa-server/pull/1630/files

Thanks @Ein-Tim for pinging with the server PR ❤️

**Comment by nohn** [comment]
To me it would make much more sense to ask if the certificate should be saved or only verified after scanning. That way CWA users wouldn't have to install covpasscheck.

**Comment by vaubaehn** [comment]
@nohn I don't understand your point, unfortunately. CWA users won't have to install CovPassCheck at all, would they? The problem only occurs when hosts of venues/events check DCCs with/misuse CWA to validate - they must use CovPassCheck. And obviously many of them still don't know.
With the current version of CWA users know that their DCC is valid in Germany, when the scan is accepted. No further need for CWA users for additional checks (other then validating "Einreiseregeln"/business rules for other countries via "Gültigkeit prüfen").

**Comment by DanAmt** [comment]
@nohn CoronaWarnApp is not for verification of other certs. To do this we use CovPassCheck App.

**Comment by nohn** [comment]
> @nohn CoronaWarnApp is not for verification of other certs. To do this we use CovPassCheck App.

You do, but obviously not everyone. I see no point in installing a second app, if CWA could do that. But, whatever. It was just a suggestion. Your app, your users, your confusion, your bad press.

**Comment by vaubaehn** [comment]
@DanAmt 
FYI: There is another neat idea for a technical barrier that tech leads of CWA are thinking about to realize:
https://github.com/ehn-dcc-development/hcert-spec/issues/107#issuecomment-972889382
It's only a solution bound to Germany and only for CWA/CovPass/CovPassCheck, but worth evaluating.

**Comment by dl1chb** [comment]
Why not just put a "I want to save this cert" at the bottom after a cert is scanned or use this quick-button for the scanner only for check-ins as #706? Or (I think better) for saving a cert the user has to go to his own certs and actively choose "import cert". This prevents those users. 

Of course you should use CovPassCheck for checking and not CWA as you should use a boat for driving on water instead your car, but you see it happened by accident. [irony]For non accidential use the use of cameras, printers and scanners schould be blocked, too.[/irony]

**Comment by Jo-Achim** [comment]
Eine Alternative zum "Corona Scanner Missbrauch Schutz" wäre diese: https://github.com/corona-warn-app/cwa-wishlist/issues/666#issuecomment-996038372.
An alternative to the "Corona scanner abuse protection" would be this: https://github.com/corona-warn-app/cwa-wishlist/issues/666#issuecomment-996038372.

**Comment by Ein-Tim** [comment]
This issue is obsolete IMO, the app now shows a warning that it can't be used to verify certificates & refers to the CovPassCheck-App. 

Here is a screenshot of the warning:
<img src="https://user-images.githubusercontent.com/67682506/172055669-ffbdd078-e6e7-48b3-9900-37e2ca350157.PNG" width="300">

Please close this issue.

**Comment by Ein-Tim** [comment]
Please close this issue @larswmh / @dsarkar.

**Comment by larswmh** [comment]
Closing as suggested
