### ISSUE TITLE
Let the user decide which certificate is the one which is currently used

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#718]
## Current Implementation
The app decides which is the currently used certificate. It does so depending on some values, like how old a test is, whiter it's a RAT or a PCR test, etc. 

## Suggested Enhancement
Let the user decide which certificate is the one which is currently used.

## Expected Benefits
The user can decide which certificate is the most important to them and select the currently used certificate accordingly.

---
Internal Tracking ID: [EXPOSUREAPP-11160](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11160)

**Comment by larswmh** [comment]
Thanks for your suggesiton @Ein-Tim.
Internal Tracking ID: [EXPOSUREAPP-11160](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11160)

---
Corona-Warn-App Open Source Team

**Comment by erikzimmermann** [comment]
I had a few situations where I accidentally showed the wrong certificate by opening the "main" certificate (the first that will be shown in the app).

IMO, it would be best to just stick to the last vaccine certificate. The test result can still be opened with "certificates".

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
