### ISSUE TITLE
Remove contact warning after receiving a negative test result

### ISSUE THREAD

**Issue by NicolaiSchmid** [corona-warn-app/cwa-wishlist#720]
## Current Implementation

/
## Suggested Enhancement

I've looked through the issues and couldn't find anything on that topic, so I'll propose this feature here. Feel free to close it, if it's a known duplicate. 
A friend of mine had an exposure logged and was thus shown a warning.  He took a quick-test and was cleared. The warning, however, remains. I think the warning became invalid after he tested himself and should thus be voided. 
 
## Expected Benefits

Clearer UX

I'm not sure if this is out of scope, please let me know your feedback, advice and comments!

**Comment by Ein-Tim** [comment]
Hi @NicolaiSchmid 👋

This seems like an duplicate of #239 to me, or? 

FYI, a today published blog post mentions exactly this. 
The blog post is: [Was tun bei einer roten Kachel?](https://www.coronawarn.app/de/blog/2021-12-15-cwa-red-tile-guidance) and is currently only available in German.

It says:

### Wieso bleibt die rote Kachel bestehen, obwohl ich bereits negativ getestet bin?

Die rote Warnmeldung bleibt so lange bestehen, bis die zugrundeliegende Risikobegegnung **mehr als 14 Tage in der Vergangenheit** liegt. Dieser Status ändert sich auch dann nicht, wenn Sie einen negativen Antigen-Schnelltest oder PCR-Test in der App registrieren. **Das hat folgenden Grund:** Die rote Warnung sagt aus, dass Sie Kontakt zu einer positiv auf SARS-CoV-2 getesteten Person hatten und sich dabei angesteckt haben können. Das negative Testergebnis sagt lediglich aus, dass bei Ihnen zum Zeitpunkt der Probenahme kein SARS-CoV-2 nachgewiesen wurde. Ob das "Nicht-Infektiös-Sein" zu diesem Zeitpunkt eine Ansteckung zum Zeitpunkt der Begegnung mit der positiv getesteten Person ausschließt, lässt sich nicht immer automatisch entscheiden.

**Ein Beispiel:** Wenn Sie eine Warnung über eine Risikobegegnung bekommen, die beispielsweise vor zwei Tagen stattgefunden hat, und Sie daraufhin sofort einen Schnelltest durchführen, kann dieser Test negativ ausfallen. Es kann aber sein, dass Sie sich dennoch angesteckt haben, die Viruslast aber erst einige Tage später so hoch ist, dass ein erneuter Test dann positiv ausfällt. Aus diesem Grund sollten Sie 3 bis 5 Tage nach dem ersten Test einen **zweiten Test durchführen.**

**Comment by NicolaiSchmid** [comment]
Jep, same idea. And I follow your reasoning: since the "official" rule reasons that if you had been infected, it can only be known for certain after 14 days (at any shorter duration, it still might be "lingering" inside you), it doesn't matter whether you tested negatively since then or not. 
So the app functions as expected and follows "reality"
I just didn't think long enough about it, thank you for pointing it out!
