### ISSUE TITLE
Expand context menu iOS (called 3D or Haptic Touch) with current certificate 

### ISSUE THREAD

**Issue by mrleine** [corona-warn-app/cwa-wishlist#721]
I have a suggestion to expand the context menu of the app for a longer period of time (called haptic touch or 3D touch).

Since the certificate has to be presented more and more frequently nowadays in the age of 2G, I would like a function to be able to call up the currently used certificate via this context menu.
Just as it is already possible with a diary entry for today or check-in (QR code scanner).
Unfortunately, it is not possible for me to do the programming myself due to the lack of the corresponding hardware requirements. So I now hope for the community here.

**Comment by Ein-Tim** [comment]
Hey @mrleine 👋

Thank you for opening this enhancement request! However, I think #504 is already proposing what you want to get implemented, or?
If yes, I suggest that you close this issue & monitor #504 instead.

Thanks and enjoy the evening!
