### ISSUE TITLE
Vaccination certificate (QR code) should show date/extra info immediately, prevent scrolling

### ISSUE THREAD

**Issue by bufemc** [corona-warn-app/cwa-wishlist#722]
## Current Implementation
You can import and show vaccination certificates in the app, but you either have to scroll it, or tap it just to show further information. 

## Suggested Enhancement
I keep it short but simple: currently the shown vaccination certificate in the CWA app needs another tap just to show the date of the vaccination. As in "the La(e)nd of Baden-Wuerttemberg" there are 2G+ restrictions now applied, so one always has to tap the QR code just to show the date. There are two major improvements possible IMHO:
- show the vaccination date (or other information, like it was the 2nd time or so) immediately, e.g. on top/above the QR code
- show the certificate screen (with extra information) on full screen, without the need to scroll it

I would it implement myself and provide a PR, but ATM I have no Android IDE nor IOS IDE installed..
This Improvement idea might be valid also for the Android version.

## Expected Benefits
Both parties, the customer and the person behind the desk, save some time and nerves - even not in the La(e)nd(le) ;-)

**Comment by moabits** [comment]
If I understood correctly, then it is actually a feature that the CWA only shows the QR code without the extra info to facilitate verification with the CovPass Check app.
Therefore, regarding the 2G+, displaying this info should be implemented in the CovPass Check app (see https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/73 and https://github.com/Digitaler-Impfnachweis/covpass-android/issues/139)
So this is either intended behaviour or a duplicate, isn't it?

**Comment by svengabr** [comment]
@moabits Thanks, I just got the info from my colleagues as well.
This enhancement request won't get implemented due to data-saving reasons.

The app should display only the QR code and this is in fact intended behavior. The CheckApp will then later give the "go" or "no-go".

**Comment by Ein-Tim** [comment]
@svengabr 

I suggest you apply the `declined` label to this issue.

**Comment by svengabr** [comment]
Feedback from Jira:

> It was requested because of Data Privacy to not show any details on the certificate card. Neither what type of certificate it is nor the vaccination status. That's also why the info text on top got added, to inform the checkers that they need to use the CovCheck App to verify the certificate and can't do so by just looking at it.  So from Design Side we can't add the additional information, as it was an explicit request to not show them by Data Privacy.

**Comment by Ein-Tim** [comment]
@svengabr 

Just out of curiosity: Who requested this?
