### ISSUE TITLE
Display „Valid from dd.mm.yyyy“ for recovery certificates which aren‘t valid yet

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#723]
## Current Implementation
Currently, CWA only shows when a recovery certificate becomes invalid, even if it's not valid yet.

![image](https://user-images.githubusercontent.com/67682506/146376065-87f57840-bdd6-4b86-bb1e-0a467449ebc1.jpeg)

## Suggested Enhancement
If a recovery certificate is not yet valid, CWA should show when it becomes valid.

Here's a screenshot from CovPass, where this is already implemented:

![image](https://user-images.githubusercontent.com/67682506/146376187-dbb59941-e0db-4dab-a294-9630336393d4.jpeg)

## Expected Benefits
The user
a) does not think that the certificate is already valid and
b) can find out when the certificate gets valid more easily.

---
Internal Tracking ID: [EXPOSUREAPP-11142](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11142)

**Comment by larswmh** [comment]
Thanks for your suggestion @Ein-Tim.
Internal Tracking ID: [EXPOSUREAPP-11142](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11142)

---
Corona-Warn-App Open Source Team

**Comment by GisoSchroederSAP** [comment]
Guys, is there a chance to get the QR code of the recovery certificate. I'm asking to validate, the "valid from" date is filled (and if so, if it is filled correctly). If so, yes, I agree, for consistency we should show this date field. If the field does not contain a (valid) date, we need to consider to communicate this to the user - either in the app or in the FAQ.

**Comment by Ein-Tim** [comment]
@GisoSchroederSAP 

Do you have an E-Mail address where the user could send the QR-Code to?

**Comment by GisoSchroederSAP** [comment]
We use our Community mailbox for this purpose: corona-warn-app.opensource@sap.com
Maybe a view words to refer to this github issue would be helpful to recognize the link.
Thank you!

**Comment by jheubuch** [comment]
Hi,
I sent you an e-mail with the certificate attached.

Thank you!

**Comment by GisoSchroederSAP** [comment]
Thanks for this. File was received, QR-Code was analyzed. From data content perspective, everything is complete and properly encoded, so the data are fine.
I'm going to address this for consistency reasons with the Product Owner. Maybe we find a way to put this into the DEV activities in a short time frame.

**Comment by Ein-Tim** [comment]
@GisoSchroederSAP What did the PO say? Will this be implemented soon?

**Comment by GisoSchroederSAP** [comment]
Didn't hear anything yet, I just asked again.

**Comment by Ein-Tim** [comment]
@GisoSchroederSAP Just a little reminder that this issue exists and is open for nearly half a year now. I wonder what delays this decision so much, I always thought that there should be feature parity between CovPass app and CWA.

**Comment by Ein-Tim** [comment]
@GisoSchroederSAP Did you get feedback from the PO in the last 30 days?

**Comment by GisoSchroederSAP** [comment]
I'm sorry, I missed the first answer in June 14th:
The valid_from date for a recorvery certificate is used to calculate the effective validity (fachliche Gültigkeit) for the G status in Germany.
As the G status and the effective validity are country-specific properties (and not equally defined across Europe), this valid_from date cannot be shown initially. In contrast, the valid_to date (180 days starting with the first positive PCR test) is defined in the JSON schema definition version 1.3.0 of the EU Health Network specifications for digital certificates, so it can be displayed safely.

Subsequently, there are no plans for the proposed changes mentioned in this issue, I recommend either closing this issue or creating a feature request to present the valid_from date based on the issuing country code.

**Comment by Ein-Tim** [comment]
@GisoSchroederSAP 

Ok, thanks for the feedback. Was this a decision by someone from SAP or from RKI? Anyways, I suggest that the CovPass & CWA team aligns in this mater.

**Comment by Ein-Tim** [comment]
Another thing I find quite surprising:

CWA currently does not show the "Valid until" date, although you say it is safe to show it. If it's safe to show it, why isn't it shown by CWA?

**Comment by Ein-Tim** [comment]
I now opened https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/202 and will wait for feedback. Let's see what happens next. I'm closing this issue until further notice.

**Comment by Ein-Tim** [comment]
@GisoSchroederSAP I expect this issue to be reopened and the feature to be implemented under the circumstances that stakeholders (RKI/BMG) re-approved the feature for CovPass, see https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/202#issuecomment-1346701830:

> We discussed this internally and received feedback from our stakeholders, that we should stick to displaying the valid from information.
The app is mainly focused on german users, who should be aware of when they can use the recovery certificate within germany.

Could you please re-assess the situation?

**Comment by Ein-Tim** [comment]
@brianebeling / @dsarkar 

Please re-open the issue, see my [comment above](https://github.com/corona-warn-app/cwa-wishlist/issues/723#issuecomment-1346737548).

cc @GisoSchroederSAP

**Comment by brianebeling** [comment]
@Ein-Tim Reopening the issue, no problem. Thanks for the obversation, we will take a look after the holidays.

In case we don't hear from each other again till then, I wish you a "Guten Rutsch!" already. Enjoy the remaining holidays. 🥳

**Comment by Ein-Tim** [comment]
@brianebeling 

Thank you for reopening! I also wish you, as well as the whole team, a "Guten Rutsch" and hope that you have relaxed remaining holidays! 🎉

**Comment by Ein-Tim** [comment]
@brianebeling @GisoSchroederSAP 

Please, could you now re-assess this issue? Thank you!

**Comment by Ein-Tim** [comment]
So - finally with version 1.40 of the CovPass app they changed to the CWA approach. Closing this issue.
