### ISSUE TITLE
Anzeige aktueller Impfangebote

### ISSUE THREAD

**Issue by Pozzdamm** [corona-warn-app/cwa-wishlist#724]
Impfstellen (Impfzentren, Ärzte, Mobile Teams etc.) erhalten die Möglichkeit via CWA aktuelle Impftermine einzustellen. Dazu wäre es notwendig, dass sich die Impfestellen in der CWA akkreditieren können. In einem ersten Schritt wäre ersteinmal ein Link des jeweiligen Bundeslandes sinnvoll, in dem auf Impf.Orte und -Möglichkeiten aktuell hingeweisen wird.

**Comment by Ein-Tim** [comment]
Hi @Pozzdamm 

Könntest du dir bitte Issue #300 anschauen & überlegen ob es dieses neue Issue noch braucht? Beide Issues erfragen im Endeffekt das selbe.

Danke & einen schönen Samstag!

**Comment by Pozzdamm** [comment]
> Hallo @Pozzdamm
> 
> Könntest du dir bitte Ausgabe #300 anschauen & überlegen, ob es dieses neue Heft noch braucht? Beide Fragen erfragen im Endeffekt das selbe.
> 
> Danke & einen schönen Samstag!

Jawohl, das stimmt [https://github.com/corona-warn-app/cwa-wishlist/issues/300] beschreibt das Problem noch präziser. Ich schließe daher diesen Issue hier.
