### ISSUE TITLE
Automatic correct obviously wrong vaccination certificates

### ISSUE THREAD

**Issue by Th-St** [corona-warn-app/cwa-wishlist#731]
## Feature description

If there are 3 vaccination certificates registered in the app for the same person, please validate them to be "1/2, 2/2 and 3/3".
And if possible allow to print a PDF stating Vaccination 3/3.

## Problem and motivation
A person I know got 2 vaccinations in Germany. The booster was done in Austria.
The doctor stated that it is the third vaccination but Austria only issues this vaccination as 1/2.
Now he has the vaccinations "1/2, 2/2, 1/2" regitered in the app.
To solve this he needs to see an Austrian doctor who adds the two German vaccinations into the Austrian eImpfpass to enable the issuing of a correct certificate. This he needs to pay.
Maybe a German pharmacist can issue the certificate, too.
In both cases unnecessary work and costs are generated. The app validated all 3 certificates and just shows the third one obviously wrong.

## Is this something you're interested in working on
No

**Comment by Ein-Tim** [comment]
Tte app can't change any data in the certificates as this would break the cryptographic signature.
