### ISSUE TITLE
iOS: Add certificate to Apple Wallet

### ISSUE THREAD

**Issue by luisoos** [corona-warn-app/cwa-wishlist#732]
## Feature description
ENG: I know that you can already do this with the competition ([covidpass.marvinsextro.de](covidpass.marvinsextro.de)), but I would like to have faster access to the certificates and the idea occurred to me that this could be linked via Apple Wallet, at least for iOS, so that can store a card there for the COVID-19 certificate and thus access it quickly (by double-clicking the side button). I am sure that this could help a lot of people in everyday life.

GER: Ich weiß, dass man dies schon mit der Konkurrenz machen kann ([covidpass.marvinsextro.de](covidpass.marvinsextro.de)), aber ich würde mir einen schnelleren Zugriff auf die Zertifikate wünschen und mir kam die Idee, dass man dies über Apple Wallet zumindest für iOS verknüpfen könnte, sodass dort für das COVID-19-Zertifikat eine Karte hinterlegen kann und somit schnell darauf (durch doppelte Betätigung des Seitenknopfs) zugreifen könnte. Ich bin mir sicher, dass dies vielen Leuten im Alltag helfen könnte.

## Problem and motivation
ENG: I experience it myself that it takes me far too long to have my vaccination certificate ready and thus it would at least simplify my everyday life - and I believe that of many others too.
GER: Ich erlebe es selbst, dass ich viel zu lange brauche, um mein Impf-Zertifikat bereitzuhalten und somit würde es zumindest mein alltägliches Leben - und ich glaube auch das vieler anderer - vereinfachen.

## Is this something you're interested in working on
No

---
Internal Tracking ID: [EXPOSUREAPP-7811](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7811)

**Comment by jucktnich** [comment]
See https://github.com/corona-warn-app/cwa-app-ios/issues/2965 and https://github.com/corona-warn-app/cwa-wishlist/issues/646

**Comment by dsarkar** [comment]
@luisoos Thanks for the suggestion. This is a duplicate of:
https://github.com/corona-warn-app/cwa-app-ios/issues/2965
https://github.com/corona-warn-app/cwa-wishlist/issues/646
https://github.com/corona-warn-app/cwa-wishlist/issues/732
https://github.com/corona-warn-app/cwa-wishlist/issues/755


---
Internal Tracking ID: [EXPOSUREAPP-7811](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7811)
