### ISSUE TITLE
Twitter Request: Make it possible to test whether CWA can send notifications

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#733]
## Feature description

The user should be able to test whether CWA can correctly send notifications. This could be achieved by giving the user the option to press on a button "Test notification" in the settings of CWA. CWA should then schedule a notification in the background & send it after x minutes (e.g. 15 minutes).
If the user does receive the notification, they know that the app works properly, if not they know that something is not working and the user can investigate where the problem lays. 

## Problem and motivation

With a test notification, the user can see whether CWA runs properly in the background and notifications are send as intended. 

## Related issue

- #243

## Additional information

This feature request is based on the feedback I received from a Twitter user: https://twitter.com/Wikinaut/status/1473375519500611591?s=20

---
Internal Tracking ID: [EXPOSUREAPP-11149](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11149)

**Comment by larswmh** [comment]
Thanks for forwarding this suggestion @Ein-Tim.
Internal Tracking ID: [EXPOSUREAPP-11149](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11149)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
