### ISSUE TITLE
Contact Journal: When finished to create a new person/place, the view should scroll to it

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#734]
## Current Implementation

Currently, when adding a new person or place to the contact journal, the view stays on the top. See this little video:

https://user-images.githubusercontent.com/67682506/147360133-66985289-2349-4c3d-af2d-e8f478de727a.MP4

## Suggested Enhancement
The view should scroll to the newly created person/place.

## Expected Benefits
Users are seeing that the creation of the new entry was successful and can enter details.

---
Internal Tracking ID: [EXPOSUREAPP-11139](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11139)

**Comment by vaubaehn** [comment]
Vote +1.

And I'm on video! 😀

**Comment by larswmh** [comment]
Thanks for your suggestion @Ein-Tim. 
Internal Tracking ID: [EXPOSUREAPP-11139](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11139)

--- 
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
> And I'm on video! 😀

Me too! 😀

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
