### ISSUE TITLE
Twitter Suggestion: After scanning a check-in QR code, the user should be checked in, without having to press a button

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#735]
## Current Implementation
Currently, after the user has scanned a check in QR code, the user has to click on a button ("Check in"). Here's a video: 

https://user-images.githubusercontent.com/67682506/147360418-948acaec-64af-4366-950a-29d96fb9681a.MP4

## Suggested Enhancement
The user should be checked in automatically, without having to click on a button. 

## Expected Benefits
Better UX leading to a faster check in process.

## Additional information
This suggestion is based on the feedback I received from a user on Twitter: https://twitter.com/BerndBurkert/status/1472175218420596740?s=20

**Comment by Jo-Achim** [comment]
The problem without an additional tab could be that you might have caught the wrong QR code!?
In addition, the option "Record in my contact journal after check-out?" be unreachable (see video, ~pos. 0:03).

**Comment by Ein-Tim** [comment]
@Jo-Achim 

I understand your concerns and have transferred them back to the user on Twitter. 

Have a "Guten Rutsch" in 2022!

**Comment by Jo-Achim** [comment]
Thank you @Ein-Tim.

Also for you and in general: "Guten Rutsch" and health in 2022.

**Comment by Ein-Tim** [comment]
This issue stayed unmirrored to JIRA for a prolonged period of time. Please mirror it to JIRA now.

**Comment by Ein-Tim** [comment]
I withdraw this proposal for the reason @Jo-Achim mentioned above. Closing this issue.
