### ISSUE TITLE
Twitter Suggestion: Add a new statistic tile: People died from COVID-19

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#736]
## Current Implementation
The app does not show how many people died from COVID-19.

## Suggested Enhancement
Add the number of deaths to the app.
1. Overall deaths
2. New deaths (+ from yesterday) 

## Expected Benefits
CWA users are better informed about the current situation reg. the COVID-19 pandemic in Germany. 

## Additional information
This enhancement request is based on the feedback I received on Twitter: https://twitter.com/AtariFrosch/status/1474298253172789281?s=20

---
Internal Tracking ID: [EXPOSUREAPP-11140](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11140)

**Comment by larswmh** [comment]
Thanks for forwarding this suggestion @Ein-Tim. Could you explain what is meant with "Nes deaths"?

**Comment by Ein-Tim** [comment]
@larswmh Sorry, this was a typo, I wanted to write "New deaths". This should be clear, or?

**Comment by larswmh** [comment]
Thanks for the clarification @Ein-Tim. 
Internal Tracking ID: [EXPOSUREAPP-11140](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11140)

--- 
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
