### ISSUE TITLE
umgehend dafür sorgen das Genesene mit Booster auch dies in der App ausweisen können

### ISSUE THREAD

**Issue by micha47259** [corona-warn-app/cwa-wishlist#739]
dringend ein update das genesene auch ihren booster vorweisen können . die app kann das nicht obwohl in bundesländern der booster schon angewendet wird. ein unding. jemand der kontrolliert muss auch erkennen das bei genesenen die 2/2 impfung ein booster ist . ein monat ist das problem bekannt und es passiert nichts…

---
Internal Tracking ID: [EXPOSUREAPP-11143](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11143)

**Comment by dsarkar** [comment]
Hi @micha47259,

Danke für den Beitrag. Das Problem ist bekannt, und es ist kein "Fehler", der in der App behoben werden kann, sondern es liegt an der Definition des Schemas der QR-Codes. Dieses Schema wurde auf EU-Ebene definiert. Mehr zu diesem Problem hier: https://www.coronawarn.app/de/faq/#vac_booster_jj

Nebenbei bemerkt: Selbst wenn man in die Corona-Warn-App eine Logik einbauen würde, aufgrund eines Genesenenzertifikats ein 2/2-Zertifikat als Booster zu erkennen, würde das Problem an sich nicht behoben sein, da mit der CovPassCheck-App nur ein Zertifikat beim Prüfvorgang gescanned wird, und die CovPassCheck-App also beim Prüfen die 2/2 Zertifikate nicht in Booster und Grundimmunisierung differenzieren kann.

Es gibt aber Neuigkeiten:
Erst vor kurzem wurde das Schema wegen dieses Problems auf EU-Ebene umdefiniert. Eine 2/2 Booster, würde dann als 2/1  ausgestellt werden. Es ist also abzusehen, dass in einer zukünftigen Version der Corona-Warn-App sowie der CovPassCheck-App dieses Problem nicht mehr auftritt, sofern die Zertifikate mit dem neuen Schema ausgestellt wurden.

---
Corona-Warn-App Open Source Team

**Comment by micha47259** [comment]
Hallo
Danke für die Antwort. Gibt es denn schon neue Erkenntnisse wann dies auch in der App zur Verfügung stehen soll? Die Auffrischung bekommt ja immer mehr Bedeutung bei Zugangs Regeln. Daher muss diese Lösung ja zeitnah kommen.
Gruß

**Comment by dsarkar** [comment]
@micha47259 Derzeit kann keine Aussage getroffen werden, wann die App(s) angepasst werden. Allein das Anpassen der App(s) reicht nicht aus, um die oben genannten Zertifikate als Booster zu erkennen,  da die schon ausgestellten Zertifikate noch die alte Notation benutzen. Es müssen also auch auf Ausstellerseite Anpassungen vorgenommen werden, die Zertifikate mit der neuen Notation auszustellen.



---
Internal Tracking ID: [EXPOSUREAPP-11143](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11143)

**Comment by dsarkar** [comment]
@micha47259 This feature was implemented with release 2.18. We suggest closing this issue. Thanks for contributing here!

Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by larswmh** [comment]
Closing this issue as suggested.
