### ISSUE TITLE
Silvester Party! 🎆

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#740]
This is not a typical wishlist issue, but it‘s also a wish. I want to wish everyone a happy new year, „Einen guten Rutsch“ and say: Thank you! ❤️

Thank you for another great year in the Community of the Corona-Warn-App, thank you for the big updates we saw over the last 365 days, which brought some great new features to all the users of the CWA. 🚀
We are close to 40.000.000 downloads, more than 1.00.000 users who were tested positive with a PCR test have warned their contacts via the app and at least 9 million users were warned via the CWA! 🎉

To all of the team, the community & their loved ones: Stay healthy, stay safe & see you in 2022! 🎇

<img src="https://user-images.githubusercontent.com/67682506/147829389-6c10fa37-3f27-45c3-8197-8f867b3026b5.gif" width="1000">

Feel free to comment below & say thank you!

**Comment by DanAmt** [comment]
Wishing one and all a happy and prosperous new new year !! 
Thanks for the good work everyone !!

**Comment by Ein-Tim** [comment]
@vaubaehn does sadly not have time to comment here, so I'm commenting on behalf of him:

"Greetings and a good and healthy start into 2022 for all of you!" 🎉🎆

**Comment by Josef54517519** [comment]
Thanks for everything! Happy new year!!!

**Comment by erAck** [comment]
Sweet 💖
Thanks and all the best and may this 202[01] shithole end!

**Comment by Nils-witt** [comment]
Thanks for all the work you all done this year and helping all of us with it. I did not think that this app would be such an simple but important app in our lifes.

@Ein-Tim is always in my Twitter timeline helping everyone, thank you, too. 

Happy new year to all of you.

**Comment by NicoErnst** [comment]
What Tim says ;)

Don´t you wonder, I made a new account probably not only just for this.

Thanks-a-mile to all contributors, evangelists and basically everyone supporting this project.  Seeing how CWA has evolved this year I am certain we can make this an even better and more popular tool to fight the pandemic. Let us not lose focus and only implement the features people really want, use and understand.

As we say in Bavaria: Kemmt´s guad ummi!

P.S.: Where can I file a pull-request for 2021? And 2020 for that matter? ;)

**Comment by rugk** [comment]
Thanks a lot for such an effective app and good early warning system. I also had a red CWA warning and PCR testing was flawlessly and easily done after that.

Thanks a lot and happy new year fighting your/our new evil Omicron… We can make that! :blush: :tada:

**Comment by Marvin-Keller** [comment]
Thank you guys for the good work and for giving me a good topic for my bachelor thesis. Wish you all the best! 🎉

**Comment by WolfgangScheida** [comment]
Nice issue. 👍

Happy New Year!

**Comment by larsschwarz** [comment]
Keep up the great work! #LucaSucks

**Comment by jucktnich** [comment]
Happy new year to the team & community. Let's hope we don't need such an issue again...

**Comment by dstapp** [comment]
Keep your good work up. Und rutscht gut :)

**Comment by Bergruebe** [comment]
Happy new year to everybody! I'm looking forward to the next year 2️⃣0️⃣2️⃣2️⃣!

**Comment by Free-Beast** [comment]
Thanks for yor operational readiness. Bleibt standhaft, kommentiert eure Quellcodes immer ordentlich. Guten Rutsch und gesundes neues Jahr.

**Comment by ManuelB** [comment]
Good job guys! Happy new year!

**Comment by ndegendogo** [comment]
Also from my side a big thank-you to the developers: for your commitment to this amazing  project; for all the bug-fixes, features, and improvements; and for your patience to review all the contributions from us community.
**I wish you all a happy new year 2022.**
🎉🎉🎉🚀🚀🚀🍀🍀🍀

**Comment by mokrates** [comment]
whoo \o/

**Comment by moormaster** [comment]
Happy new year! :)

**Comment by laryllian** [comment]
Vielmals Danke für die unfassbar tolle Doku inklusive der mittlerweile akzeptablen DSFA. ;)

**Comment by Jo-Achim** [comment]
I also wish everyone a good and healthy 2022.
And thanks for the good work here.

**Comment by topialla** [comment]
Ein gesundes(!) neues Jahr!

**Comment by dsarkar** [comment]
Dear community,

Thanks for all the wishes! Also from our side, all the best to all of you, a very happy and healthy 2022 to everybody! And many thanks for all the contributions from you, the community, to this project!

Best wishes,

---
Corona-Warn-App Open Source Team

**Comment by fynngodau** [comment]
Dear maintainers, dear community, I'm a bit late to the party, so let me keep it short this time:

I wish you all a happy and successful new year! :sparkle: :sparkles: :four_leaf_clover:

**Comment by Ein-Tim** [comment]
Silvesters over, but now it's CWAs birthday: https://github.com/corona-warn-app/cwa-wishlist/issues/833
