### ISSUE TITLE
Allow to manually edit identity information in CoronaWarnApp

### ISSUE THREAD

**Issue by MaxG87** [corona-warn-app/cwa-wishlist#745]
## Feature description
I would like to have an identity management inside the CoronaWarnApp to manage which certificates belong together. Sometimes two  certificates
* of two persons with the same name, or
* of the same person but with slightly different names
 
are added to the CoronaWarnApp. In both cases the grouping of certificates fails to do the correct thing. I would like to be able to resolve that manually.

## Problem and motivation
I swear I am not making this up.

For convenience, I manage my family's Corona related certificates in the CoronaWarnApp. This includes vaccination certificates as well as certificates of recovery. For my spouse, Erika Maria Mustermann the certificates of vaccination list both here forenames. Her certificate of recovery only lists the first. Thus, I have two entries for her in my list of certificates.

I now could want to include a certificate of my sister, Erika Mustermann, to the CoronaWarnApp. In this case I suspect that her certificates would be grouped to the certificate of recovery of my spouse.

## Is this something you're interested in working on
No, I have too much other stuff to do. Sorry.

---
Internal Tracking ID: [EXPOSUREAPP-10871](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10871)

**Comment by Ein-Tim** [comment]
Hi @MaxG87 

Thanks for raising this feature request! Did you take a look at #705? It seems like this issue is a duplicate of #705, or?

Thanks for checking.

**Comment by MaxG87** [comment]
Yes, indeed this duplicates #705.
