### ISSUE TITLE
Booster vaccination certificate is not combined with the other certificates if the second name is missing

### ISSUE THREAD

**Issue by MagnusOstertag** [corona-warn-app/cwa-wishlist#748]
Hi,

I came across some unexpected behavior in the Android app and also saw it in the IOS app: The first two vaccination certificates are combined into one tab, the third certificate is not included in this tab. The only difference between the two 'persons' is the missing second name.

The issue probably originates from the fact that I had to use my passport ('amtlich', with the 2nd name) for the first two vaccinations and only had to show my electronic health card (without the 2nd name, you do not have to state it there) or even only a registration form for the 3rd dose.

I would propose that only the first and last name and the date of birth are checked for determining whether the certificate is from the same person.

---
Internal Tracking ID: [EXPOSUREAPP-10871](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10871)

**Comment by dsarkar** [comment]
Hi @MagnusOstertag,

Thanks for the suggestion. Transferred to wishlist repository. Internal Tracking ID: [EXPOSUREAPP-10871](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10871)

Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by kroerig** [comment]
Same here. Maybe it's possible to implement a manuel merge function for certificates.

**Comment by Ein-Tim** [comment]
@kroerig 

I suggest you read thorough #705.

**Comment by Ein-Tim** [comment]
FYI: iOS PR https://github.com/corona-warn-app/cwa-app-ios/pull/4179 starts working on an automatic solution, e.g. filtering out "Dr." ([link to code](https://github.com/corona-warn-app/cwa-app-ios/pull/4179/files#diff-301ce2b909539e9b152de45bc1275cb29e09382c1c9c7d645f9a55efbef34c09R100)).

**Comment by MagnusOstertag** [comment]
It's solved, nice!

**Comment by dsarkar** [comment]
Hi @MagnusOstertag,

thanks for reporting here and your feedback. Best wishes, DS

---
Corona-Warn-App Open Source Team
