### ISSUE TITLE
Twitter request: Add CWA quick setting (Android) / icon for control center (iOS) for turning exposure logging on/off

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#749]
## Feature description

The user should have the option to add a quick setting for turning exposure logging on or off to these menus: 

| Android | iOS | 
|---|---|
| <img src="https://user-images.githubusercontent.com/67682506/148662482-8ea9b336-f84a-487c-846a-f1e1f7f9fe42.jpg" width="300"> | <img src="https://user-images.githubusercontent.com/67682506/148662478-a316f899-1496-43a2-a409-30972e007aa9.jpeg" width="300"> |

## Problem and motivation
Users can quickly turn off exposure logging, when it is not needed, e.g. when they are sleeping, etc. 

## Additional information
This issue is based on the request of a Twitter user: https://twitter.com/anonyme_melone/status/1471932916921995267?s=20

---
Internal Tracking ID: [EXPOSUREAPP-11346](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11346)

**Comment by mrjammock** [comment]
Thx 👍

**Comment by larswmh** [comment]
Thanks for your suggestion @anonymous-melon and thanks for forwarding it from Twitter @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-11346](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11346)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
