### ISSUE TITLE
Fuzzy logic on name fields matching

### ISSUE THREAD

**Issue by kroerig** [corona-warn-app/cwa-wishlist#754]
## Current Implementation
On https://www.coronawarn.app/de/blog/2021-12-20-cwa-2-15/ it says: _Nutzer*innen sollten unbedingt darauf achten, dass der Name, der im Zertifikat, das sie zur Überprüfung benutzen wollen, hinterlegt ist, EXAKT dem Namen entspricht, den sie im Buchungssystem angegeben haben. Ist das nicht der Fall, können sie das entsprechende Zertifikat in der Corona-Warn-App nicht auswählen._ 

## Suggested Enhancement
Implement a fuzzy logic /regexp that matches even if the name is not exactly the same.

## Expected Benefits
Some people have multiple givennames but they only use one (Rufname). And you won't type four givennames when you buy a concert ticket. Most times this will even exceed the field limits. So matching parts of the name would be very helpfull for those people.

---
Internal Tracking ID: [EXPOSUREAPP-11299](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11299)

**Comment by Jo-Achim** [comment]
If possible, a good idea.

**Comment by larswmh** [comment]
Thanks for your suggestion @kroerig. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-11299](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11299)

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@kroerig  Thanks for creating this wishlist item. With the implementation of a fault tolerant name handling in version 2.19 we would suggest closing this issue. Best wishes, DS

---
Corona-Warn-App Open Source Team
 [EXPOSUREAPP-11617](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11617) 
 [EXPOSUREAPP-11618](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11618)

**Comment by larswmh** [comment]
Closing this issue as suggested since there was no further activity.

---
Corona-Warn-App Open Source Team
