### ISSUE TITLE
Send Notification for new exposures while already showing "Increased Risk"

### ISSUE THREAD

**Issue by tmechen** [corona-warn-app/cwa-wishlist#759]
## Current Implementation
* Having "Increased Risk" status because of some exposures
* Recieve new exposure keys some days later
* No Notification is send to the user

## Suggested Enhancement
* Trigger notifications for new exposures - while already knowing about the "Increased Risk" from other exposures
  
## Expected Benefits
* Especially with Omikron in mind, one could have increased risk because of someone, maybe even somebody you know you didnt actually meet (eg neighbors) and "ignore" the increased risk after some testing or days. 
* Without a new notification one has to check manually if there are new entries to the journal, because of another exposure.

## User Story
We currently see the red warning. But I'm pretty sure this is "just" a neighbor whom we never met, but who walked the staircase or something like this (literally didnt leave the house on some of the days the journal links to the exposure). But with the current implementation, I would not receive a notification when meeting somebody else in the next days until the "Increased Risk" goes down to green again. 
![image](https://user-images.githubusercontent.com/9123876/149788976-3ffd286d-2612-4253-9d72-e83652a55357.png)

---
Internal Tracking ID: [EXPOSUREAPP-11421](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11421) iOS
Internal Tracking ID: [EXPOSUREAPP-12064](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12064) Android

**Comment by larswmh** [comment]
Thanks for your enhancement request @tmechen. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-11421](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11421)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
PR for iOS: https://github.com/corona-warn-app/cwa-app-ios/pull/4320

**Comment by Ein-Tim** [comment]
@tmechen 

Would you like to close this issue as this was implemented in version 2.20?
