### ISSUE TITLE
Animated feedback when the user switches the app to the foreground

### ISSUE THREAD

**Issue by carsten801** [corona-warn-app/cwa-wishlist#76]
Hi, 
first of all -> to the complete CWA-Team -> Very good job! 🙌 ❤️
As far as i can see, there is no Issue regarding this

## Current Implementation
When the user starts or switches the app to the foreground there is only a static screen showing up. 
![cwa-start](https://user-images.githubusercontent.com/67377294/85924432-8d163400-b892-11ea-8a14-67006ab88f36.jpeg)
Many Non-Techies asked me "Is the app still working" .... 

## Suggested Enhancement
There should be an animated feedback for the user. My suggestion:
Let the icon in front of "Risiko-Ermittlung aktiv" pulsate (2-3 seconds) and then switch the inner color to green or place a checkmark inside. 

## Expected Benefits
The user will get better feedback that the app is working properly.

---------------
Internal Tracking Id: EXPOSUREAPP-2120

**Comment by tens0rfl0w** [comment]
Please see [this](https://github.com/corona-warn-app/cwa-app-ios/pull/821) PR in the iOS repository.

**Comment by carsten801** [comment]
> Please see [this](https://github.com/corona-warn-app/cwa-app-ios/pull/821) PR in the iOS repository.


Oh, cool 😊!
I‘m not a OpenSpurce-GitHub-Pro... does that mean, there is a chance this is coming in the next release? 

My thoughts for the moment: 
When the tracing status icon is animated forever, there i a chance the user is waiting for a „result“ ... 
Someone a better idea that just showing a ✔️ after a few seconds?

**Comment by tens0rfl0w** [comment]
Hey @carsten801,
this probably will be introduced in the next big version bump, so when version 1.1 is released it may be included.

> When the tracing status icon is animated forever, there i a chance the user is waiting for a „result“ ...

This is a legit idea! Maybe that would be a valuable addition in the future.🙂

**Comment by heinezen** [comment]
This was implemented a wile ago, so we will close this issue.

----
Corona-Warn-App Open Source Team
