### ISSUE TITLE
Change the color of the "Test entfernen" button from blue to red

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#760]
## Current Implementation
The button "Test entfernen" is shown with a blue background. 

## Suggested Enhancement
The button "Test entfernen" should be shown with a red background. 

## Expected Benefits
Users are less likely to press on the button by accident (e.g. because they think this is part of a screen flow, or similar). 

---
Internal Tracking ID: [EXPOSUREAPP-11420](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11420)

**Comment by larswmh** [comment]
Thanks for your enhancement request @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-11420](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11420)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
