### ISSUE TITLE
Status 2G+ auch für Geimpfte und Genesene anzeigen

### ISSUE THREAD

**Issue by mromling** [corona-warn-app/cwa-wishlist#763]
## Current Implementation
Aktuell wird der Status 2G+ nicht für alle angezeigt, die keinen zusätzlichen Test benötigen.
## Suggested Enhancement
Personen, die doppelt geimpft und dann genesen sind (nach einer Erkrankung), gehören zu dem Personenkreis, der keinen zusätzlichen Test benötigt. Die Anzeige müsste  also 2G+ sein. Es wird aber 2G angezeigt.

## Expected Benefits
Wegfall von unnötigen Diskussionen in Restaurants etc.

---
Internal Tracking ID: [EXPOSUREAPP-11401](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11401)

**Comment by Ein-Tim** [comment]
Der Blog-Post: [Corona-Warn-App Version 2.16 zeigt Nutzer*innen aktuellen Status-Nachweis an](https://www.coronawarn.app/de/blog/2022-01-17-cwa-2-16/) sagt:

> 2G+ mit Auffrischimpfung: Geimpfte oder Genesene, die eine Auffrischimpfung (Boosterimpfung) erhalten haben, müssen laut Beschluss der Gesundheitsminister*innen von Bund und Ländern bei einer 2G-Plus-Regelung momentan keinen aktuellen Test vorlegen. Die CWA berücksichtigt diese Regelung in der Statusanzeige derzeit noch nicht. Das heißt, bei vorhandenem Impf- oder Genesenenzertifikat und Zertifikat der Auffrischimpfung zeigt sie noch nicht den 2G+-Status an. **Das Projektteam arbeitet bereits daran, dass die CWA in Zukunft Zertifikate von Auffrischimpfungen entsprechend einbezieht.**

Dieses Feature ist also geplant. Das Problem ist jedoch, dass Booster nicht immer als Booster erkannt werden können. 
Momentan wird nämlich z.B. die 2. Impfung nach einer Genesung als 2/2 ausgestellt, also genauso wie eine normale 2/2 Impfung.

Verlässlich erkennt die App nur 3/3 Zertifikate, die können als Booster erkannt werden.

Aber hier soll bald nachgebessert werden, dann werden 2/2 Booster als 2/1 ausgestellt, siehe https://www.coronawarn.app/de/faq/#vac_booster_jj.

---

Trotzdem gibt es weiterhin einige Probleme mit dem 2G+ Badge, da viele Bundesländer andere Regeln eingeführt haben (z.B. Zutritt zu 2G+ mit 2. Impfung nach J&J, wenn diese Impfung nicht mehr als 90 Tage her ist). Siehe auch https://github.com/corona-warn-app/cwa-documentation/issues/797.

Es wird also noch spannend, wie genau das Projekt-Team hier vorgehen wird.

**Comment by mromling** [comment]
Ich meinte nicht mit Boosterimpfung. 

Ich meinte: doppelt geimpft (2/2) und dann genesen!

Auch diese Personen gelten als 2G+. Benötigen also keinen Test und wohl aktuell auch keine Booster-Impfung, da die Erkrankung wie ein Booster wirkt.

**Comment by Ein-Tim** [comment]
@mromling 

Das wird kompliziert. Man müsste das 1. Zertifikat (1/2) in der App haben, das 2. Zertifikat (2/2) und dann ein Genesenenzertifikat das eine Infektion zertifiziert, die nach der 2. (oder vor der ersten) Impfung stattfand. 

Wenn ein Zertifikat fehlt, würde das nicht mehr funktionieren und zur Überprüfung müssten dann alle Zertifikate in CovPassCheck gescannt werden. 

Oder übersehe ich was?

**Comment by mromling** [comment]
Ne, Du hast nix übersehen. Genauso ist es - und so ist auch meine Situation in der App - und vieler Bekannter, die den gleichen Status haben.

Ich habe schon komplexere Algorithmen gesehen. Bei doppelt geimpft und geboostert muss man ja auch 3 Zertifikate in der App haben.
Hier kommt halt nur eine zeitliche Komponente dazu.

**Comment by mromling** [comment]
Ergänzung. In dem von mir beschriebenen Fall muss die Genesung nach der 2. Impfung stattgefunden haben.

**Comment by Ein-Tim** [comment]
@mromling 

> In dem von mir beschriebenen Fall muss die Genesung nach der 2. Impfung stattgefunden haben.

Gilt nicht auch 
1x Genesen
2x Geimpft
als geboostert?

**Comment by mromling** [comment]
Das kann sein. So ganz blickt man nicht mehr durch. Wäre aber logisch und ist glaube ich auch so.

**Comment by laundmo** [comment]
also ich habe 3/3 Impfungen und Zertifikate und kriege auch kein 2G+ gezeigt

**Comment by Ein-Tim** [comment]
@laundmo Das ist momentan so korrekt: https://www.coronawarn.app/de/faq/#admission_policy

**Comment by laundmo** [comment]
naja, korrekt ist das nicht, laut Regelung gellten doch 3/3 Impfungen als 2G+, also ist das ganz klar ein momentan fehlendes feature.

> Das Projektteam arbeitet bereits daran, dass die Corona-Warn-App in Zukunft Zertifikate von Auffrischimpfungen entsprechend einbezieht.

das sagt der link sogar selber

persönlich fände ich es angemessen diese anzeige abschalten zu können, da sie ganz klar momentan falsche aussagen macht und dies zu Konflikten und Verwirrung führt, wenn man das Zertifikat jemand anderem zeigt.

**Comment by Ein-Tim** [comment]
@laundmo 

Korrekt war hier der falsche Begriff, sorry.

**Comment by laundmo** [comment]
Also ich habe jetzt nochmal darüber nachgedacht, und 3/3 Impfungen sind ja sehr klar 2G+ zu bestimmen. Ich sehe also keinen Grund das für mindestens diese fälle sehr bald ein Update kommt was dies richtig anzeigt.

**Comment by Jo-Achim** [comment]
I'll quote myself from today (https://github.com/corona-warn-app/cwa-documentation/issues/797#issuecomment-1030812492):
> Is it correct that, for example, a digital vaccination certificate (DCC) with the content "3/3" or "2/1" must always be a booster vaccination? (See: [Vorschriften für die Kodierung](https://ec.europa.eu/commission/presscorner/detail/de/ip_21_6837).)
> 
> If yes... I have to express a little disappointment here regarding CWA v2.17.2. Although I had already recognized the difficulties and general conditions regarding programming [here](https://github.com/Digitaler-Impfnachweis/covpass-android/issues/139#issuecomment-1030600726), for example.
> 
> I think no matter which 'all-encompassing' solutions regarding "2G+" or similar are in the pipeline, the current version of the CWA would have deserved an evaluation and display of "2G+" by now. And if only as a temporary workaround for the particularly simple cases; e.g. with vaccination certificates "3/3" or "2/1". After determining "2G" in the algorithm, this would only have required an additional check as to whether a "3/3" or "2/1" can be found in the currently used DCC. I'll leave it open in terms of effort, whether a one-liner or three-liner would have been sufficient.
> 
> With the help of the new info card "People with booster vaccination" (until February 4th, 2022) 54.2% or 45,062,243 people, it is possible to estimate how many people could have possibly benefited from this workaround.

**Comment by Regenhardt** [comment]
Habe die Zertifikate 2/2 und 3/3 gespeichert und bei mir wird 2G+ angezeigt wie erwartet.

**Comment by Jo-Achim** [comment]
@Regenhardt, 
Reference: CWA version 2.18.1, right?

**Comment by Regenhardt** [comment]
Just checked, yes it's version 2.18.1

**Comment by riQQ** [comment]
I have the certificates 1/2, 2/2 and 3/3 saved and CWA 2.18.1 displays 2G+.

Ich habe die Zertifikate 1/2, 2/2 und 3/3 gespeichert und bekomme auch 2G+ angezeigt in der CWA 2.18.1.

**Comment by dsarkar** [comment]
@riQQ @Regenhardt Thanks for your feedback. 
@mromling We suggest closing this issue as implemented/fixed.

Thanks everybody for contributing and giving feedback here.

Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by mromling** [comment]
Fixed
