### ISSUE TITLE
Integrate schnelltesttest.de into the Corona-Warn-App

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#768]
## Feature description

https://schnelltesttest.de offers the option to scan the barcode printed on the packaging of rapid antigen tests for self usage. After scanning the barcode, the site shows the BfArM rating for this test (how well the test can detect an infection, etc.) 

## Problem and motivation

To help users make an informed decision which test to buy, the Corona-Warn-App should help by showing how precise the test is. 
In the past there were discussions on whether rapid antigen tests (for self usage) are really working and that only some are able to detect an infection reliably. This unsettled many people and CWA could help, with this feature, to restore trust in the tests. 

## Additional information

https://schnelltesttest.de is provided by https://zerforschung.org (https://github.com/zerforschung). 
The project is Open-Source, the code is available here: https://github.com/zerforschung/schnelltesttest.de

---
Internal Tracking ID: [EXPOSUREAPP-11505](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11505)

**Comment by larswmh** [comment]
Thanks for your suggestion @Ein-Tim. We have created an internal ticekt for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-11505](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11505)

---
Corona-Warn-App Open Source Team

**Comment by bunchofsage** [comment]
If a lot of users register RAT and see the results within the app: does the QR-Code for the RAT also contain information about the product used? A negative or positive test paired with sensitivity data could help inform behavior decisions (but also nudge more test centers to use high-sensitivity RAT because the quality is more visible). I know of one test center in Cologne that advertises with high-sensivity tests on their website - most don't (or do not seem to bother).

**Comment by Ein-Tim** [comment]
@bunchofsage Only in an EU digital test certificate the test used is shown.

**Comment by achisto** [comment]
@bunchofsage as @Ein-Tim already pointed out, the EU certificate contains the test name. I've attached two examples of two tests I took last year that show the test name. From there one you can simply use a website like[ schnelltesttest.de]( https://schnelltesttest.de) or the [PEI sensitivity document](https://www.pei.de/SharedDocs/Downloads/DE/newsroom/dossiers/evaluierung-sensitivitaet-sars-cov-2-antigentests.pdf?__blob=publicationFile&v=69) to check the test's sensitivity by searching for its name. 

[picture 1](https://user-images.githubusercontent.com/20704439/150887664-74867432-ec2d-4012-92c3-4ab436057604.jpg)
[picture 2](https://user-images.githubusercontent.com/20704439/150887672-2157d6c5-5f13-48c8-920c-8d7db3bb36dc.jpg)

**Comment by Ein-Tim** [comment]
schnelltesttest.de is now referred to in https://coronawarn.app/en/faq/#schnelltesttest.

**Comment by Ein-Tim** [comment]
The website https://schnelltesttest.de has a disclaimer on top saying that it is not updated anymore, due to changes in the way how data is published. Also, as the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
