### ISSUE TITLE
Restaurant/Event-Mode

### ISSUE THREAD

**Issue by durator** [corona-warn-app/cwa-wishlist#77]
Situation to solve:
Users have to leave adress and phone data when visiting restaurants or Eventsin Germany.
CoronaWarnApp could solve this when there is a device running it and registrer even short contacts.

## Feature description
Switching the app into a "Restaurant/Event-Mode" has following Effects:
the contact isvalid immediatly: no time threshold, only distance
When id's are interchanged in this mode both devices give audio feedback. This has two avantages. Users are shure about successful participiant marking and abuse leads to unexpected noise.
Other requests want transparency to lokal stored ids. If that is realised, event mode should recommend a event name which appears in guest id-list

## Is this something you're interested in working on

No
Im afraid I don't have the programmer skills

-------------
Internal Tracking Id: EXPOSUREAPP-2119

**Comment by daimpi** [comment]
Related:
- #59 
- #70

**Comment by SonaliDK** [comment]
Hi @durator,

Thank you for your proposal. All issues in the cwa-wishlist repository will be discussed with our contracting entities. They will decide whether they will be implemented or pursued further. As soon as we have any updates, we will let you know about the details.

Best regards,

SD

Corona-Warn-App Open Source Team

**Comment by alanrick** [comment]
> All issues in the cwa-wishlist repository will be discussed with our contracting entities. They will decide whether they will be implemented or pursued further. As soon as we have any updates, we will let you know about the details.
> 

> Corona-Warn-App Open Source Team

Hi @SonaliDK  Did a meeting with your contracting entities take place in July or August? If so, did they manage to reach a decision ?

🤞Alan

**Comment by Ein-Tim** [comment]
I think the event-registration label has been accidentally added here, when reading through the OP from @durator, it has nothing to do with the event-registration feature contained in version 2.0 of the Corona-Warn-App.

@durator Do you think that another solution, besides of the event-registration feature in version 2.0, is needed?

**Comment by heinezen** [comment]
Hello @durator ,

A similar feature has been implemented in CWA 2.0 as part of the event registration feature. The difference to your approach is that there is no mutual registration. Only the user has to register the QR coder in the current implementation.

You can open a new issue for this topic that takes the event registration feature into account. We will leave the issue open for now.

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
@Ein-Tim It's not *the* event registration from the CWA, but it's still a form of event registration. The label fits (for the wishlist at least).

----
Corona-Warn-App Open Source Team

**Comment by durator** [comment]
Hi, 
The event registration how it's implemented, could solve the problem mentioned here.
whether it will work now depends on politicians, no more on the software.
They have to decide that, if you do CWA QR-code-scan, you don't need to leave your address any more.
At the moment no one can check the feature because there may not be any events or open restaurants.
Hope there are soon possibilities.
Thank You for implementing Event registration.

**Comment by dsarkar** [comment]
Hi @durator,

Many thanks for contributing here and your feedback. Best wishes, DS


---
Corona-Warn-App Open Source Team
