### ISSUE TITLE
Add warning before finally deleting certificate or test from the recycle bin

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#774]
## Current Implementation
When the user deletes a test or a certificate from the recycle bin, there is no warning shown that this is irreversible.

Here is a video: 

https://user-images.githubusercontent.com/67682506/151373666-86313998-1e3b-47d0-bc24-7e5725b4c3b3.mov

## Suggested Enhancement
Add a warning pop up informing the user about what the consequences of finally deleting a test / a certificate are. 

## Expected Benefits
Less users accidentally doing something that they didn't want to do. Especially for test results this is important as a test QR code can only be scanned once.

---
Internal Tracking ID: [EXPOSUREAPP-11599](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11599)

**Comment by larswmh** [comment]
Thanks for your enhancement request @Ein-Tim.
Internal Tracking ID: [EXPOSUREAPP-11599](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11599)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@larswmh / @thomasaugsten / @mlenkeit 

Please prioritize this item & bring it up to the PO ASAP. 

Currently, the userflow is the following:
1. Delete test, see this warning:

<img src="https://user-images.githubusercontent.com/67682506/173045488-52ddd1f1-2834-4cc3-9b69-8b7b6a539e32.png" width="300">

As you can see, this warning doesn't talk about not being able to scan the test again, if completely deleted. 

2. Go to the recycle bin, delete the test there. No warning at all is shown.

**So currently, there is no warning AT ALL in the app that you are only able to scan tests once!**

**Comment by Ein-Tim** [comment]
@mlenkeit / @thomasaugsten 

This is a high priority item and seems more like a bug to me. As there is no hint in the app that a test can't be scanned more than one time, users are happily deleting tests and try to re-scan them, because they think this way they can refresh them. See e.g. this [Tweet](https://twitter.com/alltoowell91/status/1541818307988389888?s=20&t=byM0N4p_gIuXMckx1zfRjg).

Please, bring this to the attention of the PO/RKI in the next meeting.

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
