### ISSUE TITLE
Notification badge for journal tab to point user to the exposure history

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#778]
## Feature description

If the user has more than 1 exposure with increased risk, a red notification badge should appear on the journal tab to point the user to the exposure history. Best would be, after the tab is opened for the first time and a notification badge is present, a splash screen is shown which explains what can be found here. 

## Problem and motivation
Many users don't know that they can find the exposure history in the journal. There is a point to it on the increased risk detail screen, however, it seems like many users do not read the texts or don't understand it. 

---
Internal Tracking ID: [EXPOSUREAPP-12074](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12074)

**Comment by larswmh** [comment]
Thanks for your feature request @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-12074](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12074)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Please add the https://github.com/corona-warn-app/cwa-wishlist/labels/contact-journal label to this issue.

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
