### ISSUE TITLE
Zeit des Risiko Kontakt anzeigen

### ISSUE THREAD

**Issue by Eisdaemon** [corona-warn-app/cwa-wishlist#780]
Es wäre sehr praktisch wenn bei einem Risiko Kontakt den Zeitpunkt des Kontakt an.

Dadurch könnten Leute einschätzen, ob sie beim Kontakt z.B. eine Maske anhatten oder könnten andere Leute die keine Risikobegegnung bekommen haben darüber informieren.

Oh versehentlich Falsche Kategorie, tut mir Leid

**Comment by Ein-Tim** [comment]
Hey @Eisdaemon 👋

Es gibt dazu einen Blog-Post: [Warum zeigt die Corona-Warn-App bei einer roten Kachel die genaue Uhrzeit und den Ort der Begegnung nicht an?](https://www.coronawarn.app/de/blog/2022-01-21-cwa-uhrzeit-rote-kachel)

**Comment by Ein-Tim** [comment]
@dsarkar 

Could you close this issue please?

**Comment by dsarkar** [comment]
@Eisdaemon Danke für den Vorschlag. Wir haben diesen Vorschlag schon mehrmals erhalten, z.b. https://github.com/corona-warn-app/cwa-wishlist/issues/762 oder https://github.com/corona-warn-app/cwa-wishlist/issues/746. Bitte weitere Diskussionen dort weiterführen.

Internal Tracking ID: [EXPOSUREAPP-11435](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11435) 

Best wishes, DS

---
Corona-Warn-App Open Source Team
