### ISSUE TITLE
View Number of People Checked in to a specific (nearby?) location

### ISSUE THREAD

**Issue by JonasStettin** [corona-warn-app/cwa-wishlist#784]
## Feature description
Theres a variety of solutions out there, to check how crowded an area or event you wish to join is.
The CWA should have all the information required, to be able to tell people how crowded a certain location is, already.

E.g. I want to go to the gym. But I only wanna go there, if theres no more than 40 people. People that go to this example-gym have to check-in with the CWA already anyways. So there could be a Section in the CWA, where I can view how many people are currently checked in to that gym, so I can decide if I go there, or if its to crowded and therefore too risky.

This should obviously be an opt-in option for the person hosting the location. The Host should also be able to set a maximum amount of people that can go there. So I can see how many people are still allowed in (by the standards of the host).

## Problem and motivation
To empower people to make educated descisions to go or not to go somewhere, based on data the CWA already gathers anyways.

## Is this something you're interested in working on
No

**Comment by Ein-Tim** [comment]
CWA's check-in feature works decentralized, this means, there is **no** central entity which knows how many users are currently checked in to an event. 

#610 suggested to implement this, however, this was rejected.

**Comment by JonasStettin** [comment]
Sorry, didnt see that one - please close

**Comment by Ein-Tim** [comment]
@JonasStettin You, as the author of this issue, can close it.
