### ISSUE TITLE
Allow multiple Schnelltest-Profile and concurrent tests

### ISSUE THREAD

**Issue by janhoffmann** [corona-warn-app/cwa-wishlist#785]
## Feature description
App can store multiple qt-profiles (e.g. parent and child) and more than 1 test can be registered at once.

## Problem and motivation
In reality we are often faced with this:
Parents use the modern registration and tests result notification via App, but need to take the Papier-Route for their kids. They therefore need to wait 20min at the station until the test results are ready.
This is conter-productice because they are longer "in the public" as needed. Not all places might have enough room to wait safely.
If the app could register multiple tests concurrently, this problem would be already fixed on backend and station side. The only remaining issue is in the app.

---
Internal Tracking ID: [EXPOSUREAPP-2068](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-2068)
Internal Tracking ID: [EXPOSUREAPP-12456](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12456) Android
Internal Tracking ID: [EXPOSUREAPP-12372](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12372) iOS

**Comment by Ein-Tim** [comment]
Regarding multiple tests: https://github.com/corona-warn-app/cwa-wishlist/issues/109

**Comment by larswmh** [comment]
Thanks for your feature request @janhoffmann. As mentioned in the issue @Ein-Tim already linked, this has been declined in the past. Nonetheless, we still receive lots of requests about this. Therefore, I have linked your issue to our already existing internal ticket.
Internal Tracking ID: [EXPOSUREAPP-2068](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-2068)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
FYI: Seems like it will be possible to register the tests of others with version 2.21: https://github.com/corona-warn-app/cwa-app-android/pull/4947

**Comment by Ein-Tim** [comment]
FYI: Seems like with version 2.21 you will be able to create more than one RAT profile: https://github.com/corona-warn-app/cwa-app-android/pull/5048

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-12456](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12456) Android
Internal Tracking ID: [EXPOSUREAPP-12372](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12372) iOS

**Comment by janhoffmann** [comment]
@Ein-Tim I don't think so. The only update is that you can register more tests. 

To allow a fast registration without manual input, it would be as important to have multiple profiles, I can't see that on my Android device with 2.21.1

**Comment by janhoffmann** [comment]
@dsarkar you tagged it with fix 2.22, when do you expect that version?

**Comment by Ein-Tim** [comment]
@janhoffmann 

Multiple RAT profiles will be possible in 2.22. Release will probably be ca. 2-3 weeks from now. 

_Disclaimer: This is only a guess._

**Comment by dsarkar** [comment]
@janhoffmann @Ein-Tim As usual, following the usual pattern, this is what you can expect, however, things might change.

**Comment by MikeMcC399** [comment]
@janhoffmann 

CWA 2.22 was released on May 4, 2022 with your requested functionality. See https://www.coronawarn.app/en/blog/2022-05-04-cwa-2-22/.

Please check if this is what you expected and close this request if the implementation fits your needs.
