### ISSUE TITLE
Zeit und Ort des Risikos anzeigen

### ISSUE THREAD

**Issue by MWandtke** [corona-warn-app/cwa-wishlist#787]
#Feature description
Wenn ich einem Risiko ausgesetzt wurde und die App rot ist, dann sollte man über einen Klick auf das Risiko sehen, wann und wo es war. Vllt sogar mit Klick auf eine Maps App. So kann man es als Nutzer besser eingrenzen.

## Problem and motivation
Man sieht nie wann und wo es war. Wenn man mal einen Tag hatte, wo man mehrfach unterwegs war, so hat man keinen Ahnung. Ist auch sinnvoll um ggf. Kontaktverfolgung zu machen.

## Is this something you're interested in working on

No

---
Corona-Warn-App Open Source Team
Internal Tracking ID: [EXPOSUREAPP-3670](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3670)
Internal Tracking ID: [EXPOSUREAPP-3669](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3669)

**Comment by Ein-Tim** [comment]
Hallo @MWandtke 👋

Ich verstehe deinen Wunsch, mehr Informationen zu Risiko-Begegnungen zu erhalten, sehr gut.
Dieses Feature kann allerdings nicht implementiert werden, warum wird in diesem Blog-Post beschrieben:
[Warum zeigt die Corona-Warn-App bei einer roten Kachel die genaue Uhrzeit und den Ort der Begegnung nicht an?](https://www.coronawarn.app/de/blog/2022-01-21-cwa-uhrzeit-rote-kachel/)

**Comment by MWandtke** [comment]
Danke dann schreibe ich ein Feature Request an Apple

**Comment by Ein-Tim** [comment]
@MWandtke 

Möchtest du diesen Issue schließen? 

cc @dsarkar
