### ISSUE TITLE
Button to open contact journal directly from increased risk details screen (follow up to #392)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#790]
## Current Implementation
The contact journal includes the encounter history. In the contact journal you can find on which date your encounters were. The contact journal is referenced from the increased risk details screen with the the text:

<img src="https://user-images.githubusercontent.com/67682506/153754831-114032bc-ac55-47c7-9b0d-03657ae98450.jpeg" width="300">

## Suggested Enhancement
As already suggested in the OP of #392, there should be a button "Open the Journal", which directly opens the contact journal. The view in the contact journal should directly scroll to the most recent day with an exposure.  

## Expected Benefits
In the situation that you have an increased risk, most users will probably worry that they caught COVID and won't read trough all the info texts, etc. A button is therefore a very good option, because users normally **love** to press on things and will also press on the button.

---
Internal Tracking ID: [EXPOSUREAPP-12026](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12026)

**Comment by larswmh** [comment]
Thanks for your enhancement request @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-12026](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12026)

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
It's annoying to have to exit the Increased Risk details screen, where the contact journal is mentioned, in order to access the Journal tab in the bottom navigation bar.

As this wishlist item says, it would be useful to be able to click on "contact journal" directly from the text.

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
