### ISSUE TITLE
Missing recommendation in "Guidelines" section of the app: Reduce contacts

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#791]
## Current Implementation
Screenshots of the current "Guidelines" section of the app are available here: https://www.coronawarn.app/en/screenshots/#ios_cards

## Suggested Enhancement
The "Guidelines" section does not recommend to reduce contacts, although the RKI clearly does so: [Risikobewertung zu COVID-19](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Risikobewertung.html) says:
"Grundsätzlich sollten alle nicht notwendigen Kontakte reduziert und Reisen vermieden werden."'
There should be a new point in the "Guidelines" section: "Reduce all contacts, which are not necessary"

## Expected Benefits
The "Guidelines" section in the official app, published by the RKI, includes all recommendations by the RKI. 

---
Internal Tracking ID: [EXPOSUREAPP-12001](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12001)

**Comment by larswmh** [comment]
Thanks for your suggestion @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-12001](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12001)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
