### ISSUE TITLE
App should offer deletion of positive test when test is older than 10 days

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#792]
## Current Implementation
Users have to delete a positive test manually, there is no hint shown in the app that they have to do this, in order to get the app "back to normal". 

## Suggested Enhancement
The app should offer, either through a pop-up or a splash screen, to delete the test. If the action is confirmed by the user, the test should be deleted automatically. 

## Expected Benefits
There are many users who think they have to uninstall the app/reset it in order to continue to use it, after they registered a positive test in the app. If the app would pro-active ask them whether the test result can be deleted, this would be very helpful.

---
Internal Tracking ID: [EXPOSUREAPP-11912](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11912)

**Comment by dsarkar** [comment]
@Ein-Tim Thanks, nice idea!

**Comment by Ein-Tim** [comment]
I consider this as resolved now, because after 7 days the risk tile is shown again and thus the user can see the risk status again. They can then decide if they want to delete the test or not.
