### ISSUE TITLE
Countdown

### ISSUE THREAD

**Issue by FreeCovid** [corona-warn-app/cwa-wishlist#793]
## Current Implementation
The app offers several widgets with informsdions, like the local incidence.

## Suggested Enhancement
As politicians now start to promise a kind of „freedom day“ a counter would be nice.

Maybe the app could be deinstalled automatically or stop working at this day.

## Expected Benefits
As Corona/Covid is over after 21st march, everybody would be happy. Maybe people would install CWA before this day, just to uninstall it.

**Comment by Ein-Tim** [comment]
I do **not** support this enhancement request for the following reasons:

1. Most users of the CWA are careful and may oppose or be against such a "freedom" day. - This is not a strong argument, as they could just not look at the countdown.
2. Nobody can guarantee you that on 21st march all rules will be out of effect. Politics change, so does the situation in regard of Corona infections/hospitalization, etc. 
3. Instead of implementing such a feature, and binding development resources to it, it should rather be though of how the CWA could be used after this day or whether using it after this date makes no sense anymore. The app should be prepared (info screen for the user, etc.).

**Comment by leif5672** [comment]
There is still so much to implement in the CWA (just look at the wishlist), making thinking about a shutdown protocol at this point obsolete.

**Comment by Ein-Tim** [comment]
So, here is the best argument to not implement anything like this: https://www.tagesschau.de/inland/corona-bundeslaender-109.html 

@FreeCovid Would you like to close this issue? Without an exact date which is kept no matter what happens, this could be implemented. But as there is no such a date and different federal states act different, this is impossible to implement. 

cc @dsarkar

**Comment by Ein-Tim** [comment]
Tomorrow is the 21st march, this feature was not yet implemented and nothing meaningful will happen tomorrow. 

I can only again suggest to close this issue.

**Comment by MikeMcC399** [comment]
- In the current [RKI weekly report](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/Wochenbericht/Wochenbericht_2022-03-17.pdf?__blob=publicationFile) (German only) it says: "Grundsätzlich sollten auch weiterhin Kontakte nach Möglichkeit reduziert werden. Sofern Kontakte
nicht gemieden werden können, sollten sie auf einen engen Kreis von Personen beschränkt werden,
Masken getragen und Mindestabstände eingehalten werden. In Innenräumen sollten kontinuierlich
medizinische Masken getragen werden. Innenräume sind vor, während und nach dem Aufenthalt
mehrerer Personen regelmäßig und gründlich zu Lüften (AHA+L-Regel). Das RKI rät dazu enge Kontaktsituationen, z. B. Tanzveranstaltungen und andere Feiern im öffentlichen und privaten Bereich zu
meiden. **Es wird empfohlen, die Corona-Warn-App zu nutzen.**"

- Certificates are still needed in German states and for international travel to some countries.

- According to https://www.n-tv.de/politik/Lauterbach-Freedom-Day-wird-es-nicht-geben-article23196500.html "Gesundheitsminister Karl Lauterbach pocht bei den künftigen Schutzmaßnahmen weiter auf die Zuständigkeit der Bundesländer. Sie sollen die Möglichkeit nutzen, geltende Maßnahmen bis zum 2. April zu verlängern. Einen "Freedom Day" werde es somit nicht geben."

The Corona-Warn-App is therefore still relevant and useful. It is too early to stop using it.

**Comment by Ein-Tim** [comment]
Please close this issue. It is obsolete. @brianebeling
