### ISSUE TITLE
2G+ instead of 2G badge 

### ISSUE THREAD

**Issue by UnrelatedWorks** [corona-warn-app/cwa-wishlist#799]
## Curent implimentation 
When vaccinated 2 or 3 times a 2G badge is displayed above the QR code.

## Suggested Enhancement
If a third vaccination is present, change the badge to 2G+ from 2G. 

## Expected Benefits
When verifying a 2G+ status, a buisness needs to scroll down the the different vaccinations. With a improved badge it would simplify the process to verify the 2G+ status greatly.

**Comment by Ein-Tim** [comment]
This will be implemented in the next version: https://github.com/corona-warn-app/cwa-app-ccl/pull/25

**Comment by UnrelatedWorks** [comment]
perfect, thank you
