### ISSUE TITLE
Backup exposure history to transfer to new/reseted phone

### ISSUE THREAD

**Issue by ma6** [corona-warn-app/cwa-wishlist#8]
## Feature description

Create a backup in order to be able to continue using the app without exposure data loss when moving to a new phone. Coming with that restoring the exposure data on a new phone. Preferably, this would be possible moving between iOS and Android.

## Problem and motivation

When a user changes their phone all exposure data for the last two weeks is lost. If they can make a backup of the data and restore it on their new phone this data could still be accessible and they could be warned and warn others about the infection. 

## Is this something you're interested in working on

Yes, from UX POV.

---------------
Internal Tracking ID: EXPOSUREAPP-2182

**Comment by tens0rfl0w** [comment]
As @corneliusroemer already stated this is not possible in any way and needs to be discussed by the vendors (Google/Apple) of the EN framework.

**Comment by ma6** [comment]
Thanks for the clarification. I assumed that this is not possible at the current state of the API. I reckon the workaround by @corneliusroemer is an idea though not perfect ;). With this workaround: is it possible to mark oneself as infected on two phones with just one test? Perhaps that would be something to address in the FAQs.

**Comment by tens0rfl0w** [comment]
@ma6 The TAN/QR code is only valid for a one time key submission, so no, you cannot push the keys from two phones with one key.😐

**Comment by RoxanaVuc** [comment]
https://github.com/corona-warn-app/cwa-app-android/issues/962#issue-671932114

**Comment by Xelfmade** [comment]
I've exactly this described case. I switched my phone and now all my old contacts are lost. But I noticed that the Google API indeed syncs the contacts, even from old phone. Isn't it possible to pull their information? To my mind, this is a big issue, especially in this time of year and Smartphone season.. (Apple, Google, Samsung, OnePlus all released new phones)

**Comment by daimpi** [comment]
@Xelfmade unless you [have root](https://github.com/corona-warn-app/cwa-app-android/issues/1238) this is unfortunately not possible as long as Google/Apple don't allow it (they store all the keys in their Exposure Notification Framework (ENF)). My recommendation would be [this](https://github.com/corona-warn-app/cwa-website/issues/411#issue-713118035):
>  Alternatively, one could advise that the old phone could be left at home and only be turned on once a day for two weeks to check for risk encounters. This would be sufficient to receive warnings about risk encounters from days where only the old phone was carried; however, in the unlikely event of receiving a positive test result oneself, one would require an extra TeleTAN to be able to submit diagnosis keys from both phones (I'm not sure whether this is supposed to be possible in such a case).

**Comment by Xelfmade** [comment]
Yes. All keys are stored in the ENF and will analysed to the same time. There should be a way to accomplish this..

But do you think, everyone will do this, even if they know about it? That's really bad and more over the case of a positive test.

**Comment by daimpi** [comment]
@Xelfmade 

I agree that it would be convenient to have an option to export this data to a new phone but unfortunately there is nothing CWA can do about this except forwarding the request to Google/Apple. Whether they will ever allow this? 🤷 As this opens new attack surfaces I wouldn't count on it tbh. 

> All keys are stored in the ENF and will analysed to the same time. There should be a way to accomplish this..

The stored keys cannot be read (unless you have root) by you or CWA. ENF is fully responsible for handling those and CWA is only getting the final results of the calculation handed over via [the API](https://developers.google.com/android/exposure-notifications/exposure-notifications-api).

> But do you think, everyone will do this, even if they know about it? That's really bad and more over the case of a positive test.

You're right: unfortunately not everyone will do this but I hope we'll at least get a [FAQ entry](https://github.com/corona-warn-app/cwa-website/issues/411) which describes the procedure.

**Comment by USR123456** [comment]
Has this been filed as a feature request/bug with Apple/Google?

**Comment by MikeMcC399** [comment]
If there is ever a backup / restore mechanism implemented, it would not only need to include exposure keys, but also any pending test registered through a QR code.

**Comment by DanAmt** [comment]
I second this. New phone owners have to carry two phones or lose two weeks of protection.

**Comment by MikeMcC399** [comment]
@DanAmt 
> New phone owners have to carry two phones or lose two weeks of protection.

https://www.coronawarn.app/en/faq/#new_device advises:

- Your old device must be able to perform regular checks for possible encounters. Therefore, leave the device permanently turned on and permanently connected to the Internet.
- Keep the old device in a stationary location, e.g., in a specific place in your apartment. If possible, place the device where you can hear or see it so that you are alerted early by a notification of the app.
- Actively access the Corona-Warn-App on the old device at least once a day and check your risk status there.

If you carry the old phone with you and exposure logging is activated, then you will pick up new encounters. If possible it is best to just leave the old phone at home where it most likely will not have new encounters, then after two weeks you can disable exposure notifications on the old phone.

**Comment by larswmh** [comment]
Closing this issue as its related internal ticket was set to obsolete.

> This is not possible because of ENF restrictions on iOS and Android.
