### ISSUE TITLE
[contact-journal] Contacts journal entries clean-up

### ISSUE THREAD

**Issue by truscobox** [corona-warn-app/cwa-wishlist#803]
## Current Implementation
None.

## Suggested Enhancement
Automatically clean up the saved contacts and locations lists after a contact or location is no longer featured in the contacts journal.

## Expected Benefits
Declutters the saved contacts and locations lists.

**Comment by MikeMcC399** [comment]
- See also https://github.com/corona-warn-app/cwa-wishlist/issues/405.

**Comment by truscobox** [comment]
Oh. I didn't see that one!
