### ISSUE TITLE
Option to deactivate "New Features" screen

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#807]
## Current Implementation
Currently after a (non patch) update, users are always welcomed with a "New Features" screen.

## Suggested Enhancement
Make it possible to deactivate the showing of this screen in the settings of the app.

## Expected Benefits
There are many users complaining about this screen on Twitter (e.g. [here](https://twitter.com/ZSleyer/status/1495346255345725444?s=20&t=g0C9VkQV2UGjWQ8c1BUHnw)). These users are stating that they are not interested in the new features of the app and it just slows down their usage of the app, to e.g. present their EU DCC.
These users will probably not read through the text on the screen but just click on the button to dismiss the screen. Thus, giving an option to deactivate this screen, won't make the users less informed about the new features in the app.

## Alternate solution
For an alternate solution, please see #808.

---
Internal Tracking ID: [EXPOSUREAPP-12135](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12135)

**Comment by larswmh** [comment]
Thanks for your enhancement suggestion @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-12135](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12135)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
