### ISSUE TITLE
Replace the "New Features" screen with a "New Features" tile on the "Status" tab

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#808]
## Current Implementation
Currently after a (non patch) update, users are always welcomed with a "New Features" screen.

## Suggested Enhancement
Instead of showing a splash screen, which seems to annoy users, a tile on the "Status" tab should be shown, on which the user can click and where the features of the new version are listed & explained.

## Expected Benefits
There are many users complaining about this screen on Twitter (e.g. [here](https://twitter.com/ZSleyer/status/1495346255345725444?s=20&t=g0C9VkQV2UGjWQ8c1BUHnw)). These users are stating that they are not interested in the new features of the app and it just slows down their usage of the app, to e.g. present their EU DCC.
Showing a splash screen, which hinders users from using the app as normal until dismissed, is quite an an _aggressive_ way to inform about new features. A tile, on which the user has to click pro-actively, is a better and more comfortable solution

## Alternate solution
For an alternate solution, please see #807.

---
Internal Tracking ID: [EXPOSUREAPP-12136](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12136)

**Comment by larswmh** [comment]
Thanks for your enhancement request @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-12136](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12136)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
