### ISSUE TITLE
Twitter suggestion: Make it possible to request the EU DCC of others but not the test result (warning others is not possible)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#809]
## Feature description
It should be possible to scan a test QR code in the CWA, choose to only request the EU test DCC of the it, which is then automatically added to the certificates tab when the test result is available.
**It should not be possible to warn others in the case that the test result is positive should be deactivated.**

## Problem and motivation
Many users are using the CWA to retrieve the test results from e.g. their children. Most will probably not be careful enough to deactivate the "Warn others automatically" feature & thus there are false positive warnings issued.
Giving these users the option to only receive the test DCC of a test in the app, but deactivating the warn others feature, would solve this problem. 

## Additional information
This feature request is based on the suggestion from a user on Twitter: https://twitter.com/abseitslaeufer/status/1488969705402552320?s=20&t=g0C9VkQV2UGjWQ8c1BUHnw

---
Internal Tracking ID: [EXPOSUREAPP-12126](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12126)

**Comment by larswmh** [comment]
Thanks for forwarding this feature request from Twitter @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-12126](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12126)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
I consider this as implemented with version 2.21.
