### ISSUE TITLE
Twitter suggestion: Send push notification even if the risk status is already increased

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#810]
## Current Implementation
The user receives one push notification when the risk status changes from low to increased. If there are more exposures while the risk status is already increased, there is no push notification send anymore.

## Suggested Enhancement
Also send a push notification for new increased risk encounters, even if the risk status is already increased. 

## Expected Benefits
The user does not miss any exposures.

## Additional Information
This issue is based on the feedback from a user on Twitter: https://twitter.com/itengelhardt/status/1486575878989570048?s=20&t=g0C9VkQV2UGjWQ8c1BUHnw

**Comment by thomasaugsten** [comment]
This enhancement is planned for v2.20

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-11421](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11421) iOS
Internal Tracking ID: [EXPOSUREAPP-12064](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12064) Android

@Ein-Tim is this a duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/759 ?

**Comment by Ein-Tim** [comment]
@dsarkar Indeed it is, closing.
