### ISSUE TITLE
Information pop-up to not use CWA for checking DCCs is missing a "Cancel" action

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#811]
## Current Implementation
Currently, the information pop up which is shown to the user when certificates from 3 persons are already stored in the app and the user scans the certificate from another person only offers the actions 
1. "OK" (continues and adds the certificate to the app), 
2. "Download CovPassCheck-App" which brings the user to the CovPassCheck-App in the store and 
3. "FAQ zur Zertifikatsprüfung" which opens a FAQ entry 

## Suggested Enhancement
There should be another action "Cancel"/"Abbruch" which closes the QR code scanner and does **not** import the certificate. 

## Expected Benefits
Currently, even if the pop up actually helps the user and informs them that they are using the wrong app, the certificate scanned will be imported in the app and they have to delete it manually.
A "Cancel" action would solve this problem.

---
Internal Tracking ID: [EXPOSUREAPP-12125](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12125)

**Comment by larswmh** [comment]
Thanks for your enhancement request @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-12125](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12125)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
