### ISSUE TITLE
Approx contact time

### ISSUE THREAD

**Issue by dariusptrs** [corona-warn-app/cwa-wishlist#813]
## Feature description

 It would be cool to at least be able to see when the contact with an infected person has been approximately. For example: morning, noon or evening.
I dont know if it is possible to implement that so easily or wheather the whole system has to be changed, but I think it might be better than just showing people the whole day.

## Problem and motivation
 It would help people to have a better guess where they have had contact with an infected person.

## Is this something you're interested in working on

No, I can not code Swift

**Comment by dsarkar** [comment]
Hi @DariCari 

Thanks for participating here. See blog article about this topic:
- DE https://www.coronawarn.app/de/blog/2022-01-21-cwa-uhrzeit-rote-kachel/
- EN https://www.coronawarn.app/en/blog/2022-01-21-cwa-uhrzeit-rote-kachel/
