### ISSUE TITLE
Pop up shown when already showing increased risk and another increased risk encounter is detected should have a "Bring me to the Journal" button

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#816]
## Current Implementation
As you can see in https://github.com/corona-warn-app/cwa-app-ios/pull/4320, the only button will be "OK".

## Suggested Enhancement
Add another button "Open the Journal". 

## Expected Benefits
Users tend to just click on "OK" on pop ups where no other action is available, as they are sure this has no important information. Adding another button thus leads to more users reading the pop up **and** is convenient for the user as they are directly transferred to the contact journal. 

---
Internal Tracking ID: [EXPOSUREAPP-12220](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12220)

**Comment by larswmh** [comment]
Thanks for your enhancement request @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-12220](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12220)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
