### ISSUE TITLE
Family Account

### ISSUE THREAD

**Issue by mucneko** [corona-warn-app/cwa-wishlist#817]
## Feature description

Anlegen/managen eines Gruppenaccounts mit mehreren, zusammengehörigen Personen. (Impfzertifikate, Tests, positive Tests angeben/warnen)

Idee: alles, wie gehabt, nur eine Gruppe 'drüberlegen'.

## Problem and motivation

Familien sind oft gemeinsam unterwegs. Die Kinder haben aber idR keine eigenen Handys (und damit auch keine eigene CWA), sind aber im Familienverband mit unterwegs. Wenn jetzt eine Person im Verband positiv getestet wird, kann man das nicht so richtig schön weitergeben. Auch das Verwalten der Kinder-Impf-Zertifikate ist eher so ... es geht... (dazugefrickelt?)

Hier ist es dann auch möglich Tests, Warnungen, Impfzertifikate, Eventanmeldungen usw. über diese Gruppe für die Gesamtgruppe (Warnungen) und die einzelnen Mitglieder (Impfzertifikate/Testergebnisse) vorzunehmen. 
Mögliche Zusatzerweiterung: Mitglieder bei Gemeinschaftsaktionen (gemeinsame Eventanmeldung) aus der Gruppe ausnehmen, weil z.B. nicht mit dabei.

## Is this something you're interested in working on
No

Not sure, ich habe mich mit App-programmierung noch nicht beschäftigt. (sollte da vielleicht nicht gleich mit sowas anfangen)

---
Internal Tracking ID: [EXPOSUREAPP-13010](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13010)

**Comment by Ein-Tim** [comment]
This issue is over one month old and there was no feedback from the Open-Soruce-Team. It was not even mirrored to JIRA.

**Comment by larswmh** [comment]
Thanks for your feature request @mucneko. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-13010](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13010)

---
Corona-Warn-App Open Source Team

**Comment by mucneko** [comment]
Thank you, 2.21 / 2.22 has mostly what I wanted to have.

I'll close this Case and thank you for support.

**Comment by dsarkar** [comment]
Hi @mucneko, thanks for your feedback. Best wishes, DS

---
Corona-Warn-App Open Source Team
