### ISSUE TITLE
Loss of vaccination status (IfSG) - remind before Oct 2022 

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-wishlist#820]
## Current Implementation

People who have had only two vaccinations are recommended by CWA to get a booster vaccination, however there is no warning in the app that they will lose their full vaccination status after Sep 30, 2022.

## Suggested Enhancement

Consider all cases listed in the [Infektionsschutzgesetz - IfSG](https://www.gesetze-im-internet.de/ifsg/BJNR104510000.html) § 22a "Impf-, Genesenen- und Testnachweis bei COVID-19; COVID-19-Zertifikate; Verordnungsermächtigung" and warn users in plenty of time if they need to take action before Oct 1, 2022 in order to maintain a status of fully vaccinated against COVID-19.

## Expected Benefits

Avoid users being surprised by loss of vaccination status.

## References

1. [Infektionsschutzgesetz - IfSG](https://www.gesetze-im-internet.de/ifsg/BJNR104510000.html) ("Infektionsschutzgesetz vom 20. Juli 2000 (BGBl. I S. 1045), das zuletzt durch Artikel 3a des Gesetzes vom 28. Juni 2022 (BGBl. I S. 938) geändert worden ist"), § 22a Impf-, Genesenen- und Testnachweis bei COVID-19; COVID-19-Zertifikate; Verordnungsermächtigung

"Ein vollständiger Impfschutz gegen das Coronavirus SARS-CoV-2 liegt vor, wenn"... "insgesamt drei Einzelimpfungen erfolgt sind" ... "(es) liegt ein vollständiger Impfschutz bis zum 30. September 2022 auch bei zwei Einzelimpfungen vor" ...

Please read the full legal text which covers various different situations.

2. ~Booster rule BNE-DE-0300~ (withdrawn)

~"The Federal Ministry of Health recommends that all persons who have not had a proven case of the coronavirus (SARS-CoV-2) and who obtained their base vaccination more than six months ago arrange a vaccination appointment or discuss the benefits of getting a booster shot with their doctor. Scientific studies confirm that booster shots provide a higher level of protection against becoming infected with COVID-19. As your saved certificates indicate that you belong to this group of persons and have not yet received a booster shot, we would like to inform you of this recommendation. (Rule BNR-DE-0300)"~

3. [Booster rule BNE-DE-0110](https://timokoenig.github.io/eu-dcc-rules/?ruleset=de-bn-rules&country=DE&rule=BNR-DE-0110) valid from May 4, 2022 to June 1, 2030

"EN: The German Standing Committee on Vaccinations (STIKO) recommends a booster vaccination for everyone age 12 and older who has not been diagnosed with a SARS-CoV-2 coronavirus infection and who completed their basic immunization more than three months ago. The certificates you have saved indicate that these criteria apply to you and that you have not had a booster vaccination. We therefore wish to point out this recommendation. (Rule DE-BNR-0110)" ...

---
Internal Tracking ID: [EXPOSUREAPP-13008](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13008)

**Comment by MikeMcC399** [comment]
This wishlist item affects the repositories:

- [Corona Warn App - Common Covid Logic (CCL)](https://github.com/corona-warn-app/cwa-app-ccl)
- [Digital COVID Certificates: Booster Notification Rules - Translation](https://github.com/corona-warn-app/dcc-rule-translation)

**Comment by Ein-Tim** [comment]
Please mirror this issue to JIRA @dsarkar / @larswmh.

**Comment by larswmh** [comment]
Thanks for your enhancement request @MikeMcC399. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-13008](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13008)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@mlenkeit 

Hey Maximilian, I hope it is OK to ping you on this issue! I think this issue should be assigned internally with a higher than normal (whilst issue) priority. It seems like a very sense full request and CWA should be made ready for such an reminder, e.g. by using Booster Notification Rules, as soon as possible, both to make sure that this feature actually makes it into the app & to ensure users have enough time to act. 

Hope you have a relaxed weekend, I would appreciate a little feedback (👍) from you so that I know you saw this comment.

Stay safe and healthy everyone!

**Comment by Ein-Tim** [comment]
@dsarkar I want to push this issue one more time. Could you let us know what the internal status is?

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for "cherry-picking" this one. Re-assigned and underlined importances/relevance of this issue.

**Comment by Ein-Tim** [comment]
Thanks @dsarkar! Enjoy your Friday afternoon!

**Comment by Ein-Tim** [comment]
@GisoSchroederSAP is there any update on this topic available? Was it brought to the attention of the PO?

**Comment by GisoSchroederSAP** [comment]
All,
the new IfSG  law is not yet in power, it has not even gone through the reading in the parliament. We expect the BMG to provide specific details in the near future on how to adapt the app to the new resolutions. As mentioned above, the existing ticket with internal Tracking ID: [EXPOSUREAPP-13008](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13008) 
So, yes, the PO is aware of this topic (and I just added one more comment there, to keep the ball roling). But we may need to wait until the new IfSG is in place.

**Comment by MikeMcC399** [comment]
@GisoSchroederSAP 

This issue refers to the [Infektionsschutzgesetz - IfSG](https://www.gesetze-im-internet.de/ifsg/BJNR104510000.html) ("Infektionsschutzgesetz vom 20. Juli 2000 (BGBl. I S. 1045), das zuletzt durch Artikel 3a des Gesetzes vom 28. Juni 2022 (BGBl. I S. 938) geändert worden ist") in its current active form, not to any future planned change to the law.

See the following link for the full current text of the respective paragraph: [§ 22a Impf-, Genesenen- und Testnachweis bei COVID-19; COVID-19-Zertifikate; Verordnungsermächtigung](https://www.gesetze-im-internet.de/ifsg/__22a.html)

According to the current law the change in definition of "vollständiger Impfschutz" takes effect on Oct 1, 2022 which is 24 days from today.

**Comment by Ein-Tim** [comment]
To be very concrete: This change is in law and if there is no "Verordnung" which removes the text from the law, it will go into effect soon (01.10.2022). So to inform the user about this change, this topic needs to be included in the **current 2.27 sprint** @GisoSchroederSAP.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Did you or will you open an issue in one of the CovPass-App repos to make sure CovPass updates their apps?

**Comment by MikeMcC399** [comment]
@Ein-Tim

> Did you or will you open an issue in one of the CovPass-App repos to make sure CovPass updates their apps?

No. If you have concerns about CovPass, please raise them yourself in the appropriate repositories (issue or discussion).

**Comment by MikeMcC399** [comment]
I re-checked this and it seems that it is more or less effectively already covered by the current CCL rules:

With a 2/2 vaccination the Vaccination Status is shown as:

"You have received all vaccinations for basic immunization. Your vaccination protection is effective. Please also find out about the recommended booster vaccinations."

With a 3/3 vaccination certificate the text changes to:

"You have received all currently recommended vaccinations. Your vaccination protection is complete."

The question is if "Your vaccination protection is effective." is still a correct statement on Oct 1, 2022.

Since this is a concrete question for CCL, I will add it to the CCL repo.

There is currently no specific reminder in the app about the change taking place on Oct 1, 2022, however the app already recommends the necessary booster vaccination without pointing out the legal implication.

**Comment by MikeMcC399** [comment]
- CCL question: https://github.com/corona-warn-app/cwa-app-ccl/issues/101 added

**Comment by MikeMcC399** [comment]
Since it is effectively too late to add any special warning to the app in time for Oct 1, 2022, I will close this wishlist item.

I suggest checking again on or after Oct 1, 2022 to make sure that the information displayed in the app is aligned with the [Infektionsschutzgesetz - IfSG](https://www.gesetze-im-internet.de/ifsg/BJNR104510000.html) in its current form.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

> Since it is effectively too late to add any special warning to the app in time for Oct 1, 2022, I will close this wishlist item.

Why do you think it is too late? You mean that the information wouldn't help the user anymore now?

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> Why do you think it is too late? You mean that the information wouldn't help the user anymore now?

I was no longer able to identify any benefit. If you see some disadvantage please explain in case I missed some point.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

From my point of view the benefit would be to transparently communicate to the user that their vaccination status changed. But maybe this can be done solely by CCL?

**Comment by GisoSchroederSAP** [comment]
To be very clear: Yes, we support your idea and would love to get an additional reminder implemented. Especially, as losing the "fully-vaccinated status" may have social and/or financial impact in the near future, this transparancy is much appreciated.
However, this reminder still needs to be aligned with and confirmed by the customer. And here we have the issue: Currently, the customer rather has focus on the IfSG changes than on the details of the CWA enhancements.

**Comment by Ein-Tim** [comment]
@GisoSchroederSAP 

Thanks for the clear communication!

**Comment by MikeMcC399** [comment]
@GisoSchroederSAP 

> Especially, as losing the "fully-vaccinated status" may have social and/or financial impact in the near future,

You are right, since according to [§ 20a Immunitätsnachweis gegen COVID-19](https://www.gesetze-im-internet.de/ifsg/__20a.html) this affects people working in medical facilities etc. who are required to have an "Impfnachweis", defined as "Ein Impfnachweis ist ein Nachweis hinsichtlich des Vorliegens eines **vollständigen** Impfschutzes gegen das Coronavirus SARS-CoV-2 in deutscher, englischer, französischer, italienischer oder spanischer Sprache in verkörperter oder digitaler Form."

so I will re-open this item, even if is unlikely that a warning can be issued in time.

[Einrichtungsbezogene Impfpflicht](https://www.zusammengegencorona.de/faqs/spezifische-personengruppen/einrichtungsbezogene-impfpflicht/#id-d7cecfe2-644e-5097-a769-8065f836a0fc) explains this requirement in detail, including the change coming up on Oct 1, 2022.

"Die Nachweise von Personen, die nur zwei Impfungen in Anspruch genommen haben (oder nur eine in den Fällen des § 22a Absatz 1 Satz 2 IfSG) laufen damit mit Ablauf des 30. September 2022 ab. Diese Personen sind verpflichtet gem. § 20a Absatz 4 IfSG der Leitung der Einrichtung oder des Unternehmens innerhalb eines Monats nach Ablauf der Gültigkeit des bisherigen Nachweises einen neuen Nachweis vorzulegen. "

Edit: [§ 20a Immunitätsnachweis gegen COVID-19](https://www.gesetze-im-internet.de/ifsg/__20a.html) was repealed (weggefallen) and is no longer in force staring Jan 1, 2023.

**Comment by MikeMcC399** [comment]
A new page has been published by BMG on https://www.bundesgesundheitsministerium.de/service/gesetze-und-verordnungen/ifsg.html

The FAQs on https://www.bundesgesundheitsministerium.de/service/gesetze-und-verordnungen/ifsg/faq-ifsg.html confirm about the changes to vaccination status which come into force on Oct 1, 2022:

![image](https://user-images.githubusercontent.com/66998419/189435156-9f00481f-d024-4a8c-b998-b483ab858001.png)

**Comment by Ein-Tim** [comment]
Also, the question is what status do I have in e.g. the following case:
- 2x vaccinated
- 1x recovered

Am I "Vollständig geimpft/immunisiert", even after 01.10.2022?

CCL should definitely be made ready so that the general public can trust that the data CWA is displaying is accurate and correct.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

You should read [IfSG § 22a](https://www.gesetze-im-internet.de/ifsg/__22a.html) regarding recovery. It is quite complicated. Again, if you want to pursue this topic, I suggest to create a new issue to avoid confusing the issues.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I think I already found the answer in §22a so there is no need for a new issue.

I one has been vaccinated 2x & then recovered form Sars-CoV-2 they will still be "fully vaccinated" even after 01.10.2022.

**Comment by MikeMcC399** [comment]
I'm going to close this issue once again, as the aim was to remind **before** Oct 1, 2022.

Given the planned changes for CCL 3.3, a special warning doesn't seem to be necessary. People affected by the [Einrichtungsbezogene Impfpflicht](https://www.zusammengegencorona.de/faqs/spezifische-personengruppen/einrichtungsbezogene-impfpflicht/#id-d7cecfe2-644e-5097-a769-8065f836a0fc) are probably well informed through other channels. In any case the time has run out for any interim message before the 2.27 release.

- PR https://github.com/corona-warn-app/cwa-app-ccl/pull/105 shows that 2G/3G status will no longer be presented, since it is no longer relevant 
- https://github.com/corona-warn-app/cwa-app-ccl/issues/101#issuecomment-1243988754 says that the necessary changes are planned to be made in CCL 3.3 for release with CWA 2.27.

**Comment by MikeMcC399** [comment]
- There is a proposed new BNR rule (see https://github.com/corona-warn-app/dcc-rule-translation/issues/10#issuecomment-1252418923). Although I don't expect the rule to warn before Oct 2022, it should at least give a warning after Oct 2022 if a user's vaccination has become incomplete due to changes in the IfSG definitions.
