### ISSUE TITLE
Request EU digital COVID certificate of recovery directly via the app if a positive PCR test is registered

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#821]
## Feature description

It should be possible to request an EU digital COVID certificate of recovery directly via the Corona-Warn-App if a positive PCR test is registered in the app.
The process would be similar to the one which is already implemented for providing an EU digital COVID test certificate for a negative PCR or rapid antigen test to the user.

### User story

1. User gets tested at a testing station & receives a test result QR code for the Corona-Warn-App
2. The user scans the QR code with the app and enters their date of birth to request a EU digital COVID test certificate in the case of a negative result
3. The user is tested positive, the app either automatically warns others or informs the user to do so
4. After others were warned or the user declined to warn others, the app should offer the creation of an EU digital COVID certificate of recovery
5. The user decides that they want a recovery certificate issued via the app
6. The app preforms the same steps as when issuing a test certificate, but requests a recovery certificate and not a test certificate

## Problem and motivation
Currently, users have to go to their pharmacy or doctor to receive an EU digital COVID certificate of recovery. However, with just some adjustment on server side (allow to transmit personal information with positive tests) and some adjustments on the app, it would be possible to offer a digital-first solution to the user. 

## Possible disadvantages
At the moment, before issuing a certificate of recovery, the pharmacy or the doctor checks the ID card of the person requesting the certificate. This can't be done in the app.
However, I don't think that this is a problem for the following reasons:
1. Before getting PCR tested, the person getting tested has to show their ID to the personal at the testing station
2. Test certificates can also be issued via the app, without ID check performed directly via the app. The only requirement is that the in-app entered DOB has to match the DOB transmitted from the testing station together with the test result

---
Internal Tracking ID: [EXPOSUREAPP-12609](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12609)

**Comment by larswmh** [comment]
Thanks for your feature request @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-12609](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12609)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
