### ISSUE TITLE
Implement check for domestic rules into CWA (Align to CovPass)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#824]
## Current Implementation
CWA does not offer to check the domestic rules for Germany, while CovPass offers to do this.

## Suggested Enhancement
Make it possible to check the domestic rules for Germany with CWA, so that users don't have to download CovPass just for this.

## Expected Benefits
CWA users have the same features as CovPass users.

**Comment by thomasaugsten** [comment]
Domestic rules a included in the G status no explicit domestic rule check is necessary

**Comment by Ein-Tim** [comment]
@thomasaugsten So CovPass only included this because it doesn't have the G status / CCL feature?

**Comment by thomasaugsten** [comment]
CovPass use this to show the different rule compared to the German EU-rules

**Comment by Ein-Tim** [comment]
@thomasaugsten Okay, makes sense. Closing.
