### ISSUE TITLE
Don't send expiring soon notification for certificates that are not currently used

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#828]
## Current Implementation
The app sends a notification to inform the user that a certificate is about to expire, regardless whether the certificate is the currently used one or not. 

## Suggested Enhancement
Do **not** send this notification if the certificate about to expire is not the currently used one. There is no benefit for normal users from this notification and it causes confusion (e.g. do I need to get my certificate reissued, do I have to get a booster, etc.).

## Expected Benefits
Less confused users, some examples of confused users: 
- https://twitter.com/micwim/status/1527319310452260865?s=20&t=xg0saCvHXQi_NDg50Bmfpg
- https://twitter.com/StefGalla/status/1527312341875904512?s=20&t=xg0saCvHXQi_NDg50Bmfpg

## Additional information
This is a time sensitive issue. I therefore request prioritized mirroring to JIRA & assessment by the team. 

## Pings
Open-Source-Team: @dsarkar & @larswmh
FYI: @mlenkeit & @Thomasaugsten

**Comment by thomasaugsten** [comment]
A deployment to disable the notification and banner is already prepared and will be deployed tomorrow

**Comment by Ein-Tim** [comment]
@thomasaugsten Thanks for the information! Does this change disable the notifications forever or only until version 2.23 is released?

BTW: Do you have a link to the corresponding server PR? I only found https://github.com/corona-warn-app/cwa-server/pull/1824, which delays the notification for one day.

**Comment by thomasaugsten** [comment]
This kind of notification. will be disabled forever only relevant certificate will send a push notification with 2.23
Its a configuration adjustment no server pr is needed here but we will sync the application yml after it is on production

**Comment by Ein-Tim** [comment]
@thomasaugsten Okay, thanks for the information, so IIUC, my proposal will be implemented with version 2.23?

> Its a configuration adjustment no server pr is needed here but we will sync the application yml after it is on production

👍

**Comment by thomasaugsten** [comment]
Correct

**Comment by Ein-Tim** [comment]
Thanks for your fast responses @thomasaugsten. 

@dsarkar I suggest to add the `Fix 2.23` label here.

**Comment by Ein-Tim** [comment]
Version 2.23 has been released. Closing this issue as implemented.
