### ISSUE TITLE
Sidebar with Links and Searchable Regulations of each Federal State

### ISSUE THREAD

**Issue by michscho** [corona-warn-app/cwa-wishlist#83]
## Problem and motivation
**It is challenging to gain an overview of the regulations of the federal states.** These change frequently and vary from federal state to federal state. (Pain)
A searchable application with the current restrictions would be extremely helpful. A straightforward design and searchable regulations would be ideal. What is better suited for this than the Corona App? (Gain)

## Feature description

<img width="758" alt="image" src="https://user-images.githubusercontent.com/39197673/86155244-6f500580-bb04-11ea-8a16-8fe5e8f3fbbc.png">

https://www.figma.com/proto/5WnvyPYw3ls1W5PgY14Ir7/Android-UI-Kit-Copy?node-id=44698%3A3153&scaling=scale-down

_Use Case:_
The user opens the sidebar, selects his federal state and searches for a specific case. For example, he wants to meet with friends. He searches for friends and finds an easy-to-understand card with all information about what is allowed in his federal state. If he wants to know more, he can click on the card.

-------
Internal Tracking id: EXPOSUREAPP-2110

**Comment by SonaliDK** [comment]
Hi @Nolimimer,

Thank you for your proposal. All issues in the cwa-wishlist repository will be discussed with our contracting entities. They will decide whether they will be implemented or pursued further. As soon as we have any updates, we will let you know about the details.

Best regards,

SD

Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Maybe this issue could be merged with #151? I think the only difference is how the UI would look.

**Comment by larswmh** [comment]
Closing this issue as its related internal ticket was set to obsolete.
