### ISSUE TITLE
abgelaufene Zertifikate nicht verlängerbar

### ISSUE THREAD

**Issue by DirtyHarry09** [corona-warn-app/cwa-wishlist#831]
Hallo,
ich habe die iOS App 2.23.1 installiert.
Ich habe drei Zertifikate, die ersten beiden laufen am 17.06. ab. Ich hatte eine Benachrichtigung der App erhalten, dass sie ablaufen, allerdings vor dem Erscheinen der neuen Version.
Trotzdem kann ich die beiden Zertifikate nicht verlängern.
Das ist doch aus meiner Sicht fehlerhaft. Oder kann man nur das aktuell verwendete Zertifikat (der 3. Impfung) verlängern?
Viele Grüße,
Hartmut.

---
Internal Tracking ID: [EXPOSUREAPP-13308](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13308)

**Comment by Ein-Tim** [comment]
Hi Hartmut,

wie du schon richtig vermutest kann immer nur das aktuell verwendete Zertifikat verlängert werden. 
Mehr Infos dazu gibt's im Blog: [CWA 2.23: Verlängerung von technisch abgelaufenen Zertifikaten in der CWA](https://www.coronawarn.app/de/blog/2022-06-01-cwa-2-23/)

"**Genesenenzertifikate** können immer technisch erneuert werden, wenn sie drohen abzulaufen. Bei **Impfzertifikaten** müssen Nutzer\*innen lediglich das aktuell verwendete Zertifikat verlängern, da es hinreichend Informationen über den Impfschutz enthält. Für Nutzer\*innen, die drei Impfzertifikate in der CWA hinterlegt haben, bedeutet das beispielsweise: das Impfzertifikat der Erst- und Zweitimpfung wird nicht ausgetauscht, sondern lediglich das Impfzertifikat der Auffrischimpfung, sobald es droht abzulaufen."

**Comment by dsarkar** [comment]
Hi @DirtyHarry09,

Wie @Ein-Tim richtig zitiert, genügt es in diesem Fall, dass nur das aktuell verwendetet Impfzertifikat (3. in diesem Fall) verlängert wird, um ausreichenden Impfschutz in der App zu dokumentieren. Für anderen abgelaufenen Zertifikate (das erste und zweite) empfiehlt es sich, diese nicht zu löschen sondern zu Dokumentationszwecken aufzubewahren.


Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@thomasaugsten Could you please close this issue?
