### ISSUE TITLE
Reissue certificates that are not currently used

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#832]
## Current Implementation
Currently, the app only offers to reissue the certificate of the currently used certificate.

## Suggested Enhancement
Make it possible to also reissue certificates which are not currently used. However, **don't** send a push notification if a certificate, which is not the currently used one, expires. 

## Expected Benefits
There might be some use cases where users need all certificates (e.g. there were airlines requiring passengers to upload all certificates of a series to prove vaccination, and not only the latest one. There might also be other use cases which we can't imagine here, but exist in reality. 
It's not good that the app is so restrictive here.

**Comment by dsarkar** [comment]
Hi @Ein-Tim, thanks for your suggestion. Currently, my understanding is that this is not necessary.
1. The upload of DCCs via the App (Verification services) is currently not being used.
2. A user can export expired certificates into pdf files and upload these. Uploading pdf files is be the common way to present theses docs beforehand.

**Comment by Ein-Tim** [comment]
Hey @dsarkar, thanks for your answer!

> A user can export expired certificates into pdf files and upload these. Uploading pdf files is be the common way to present theses docs beforehand.

That's good! The only question is, for example Lufthansa, do they verify the uploaded certificates or is it enough for them that there are certificates present, even if they might be technically expired.

This topic was originally brought up in out Community Slack channel: https://covidapps.slack.com/archives/C0194ML0MLN/p1654243873402289?thread_ts=1654100872.991559&channel=C0194ML0MLN&message_ts=1654243873.402289, but also on Twitter: https://twitter.com/imanaris97/status/1532652984932478988?s=21&t=jtqdRLfpMYnqDbRO1b4e8w

I just want to avoid a situation where it's autumn, 3G/2G/whatever requirements come back and at some point some company / institution wants to see all certificates and not only the latest one & users then have to go to a pharmacy to get new certificates.
Maybe the team could cross check e.g. the behavior of the Lufthansa validator: https://www.lufthansa.com/xx/en/digital-document-check#documents

**Comment by MikeMcC399** [comment]
@Ein-Tim 
In your title "possibilityto" should be two words => "possibility to". Or you could shorten the title to
"Reissue certificates that are not currently used" since this is the wishlist repository and that would be your wish.

**Comment by Ein-Tim** [comment]
Done @MikeMcC399! Thank you!

**Comment by MikeMcC399** [comment]
A workaround for this wishlist request item is to temporarily delete newer certificates leaving the expired certificate as the currently used certificate. Then renew the desired expired certificate. Finally restore the deleted certificates from the recycle bin.

**Comment by Ein-Tim** [comment]
@MikeMcC399 Yes, that is a workaround. If this is the officially suggested workaround for this, it should be added to the FAQs. Then I would also consider this as implemented & close it.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
>  If this is the officially suggested workaround for this, it should be added to the FAQs.

I don't know if this will ever be an "officially suggested workaround" as the official information in the [Version 2.23 blog](https://www.coronawarn.app/en/blog/2022-06-01-cwa-2-23/) says:

"For **vaccination certificates**, users only need to renew the certificate currently in use, as it contains sufficient information about vaccination protection. For users who have stored three vaccination certificates in the CWA, this means that the vaccination certificate of the first and second vaccination will not be exchanged, but only the vaccination certificate of the booster vaccination as soon as it is about to expire."

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Yeah, but in the OP I Outline why the passive possibility should still be implemented.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> Yeah, but in the OP I outlined in the OP why the passive possibility should still be implemented.

You only listed why it might be required, but I didn't see any concrete example listed.

If the official statement is that only the certificate in use needs to be updated, then any apps or sites requesting certificates should follow that rule.

Since we are still in the early days of the first vaccination certificates expiring I would not be surprised if there are going to be problems. Please keep us up to date if you find any specific example where an earlier vaccination certificate is also required to be renewed.

**Comment by Ein-Tim** [comment]
> If the official statement is that only the certificate in use needs to be updated, then any apps or sites requesting certificates should follow that rule.

I agree with you here, but we saw e.g. with the acceptance of CovPassCheck that this might take some while until everyone accepts that and changes their process. In the meantime the enduser has to explain why some of the certificates are expired.

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
