### ISSUE TITLE
Birthday party 🎂

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#833]
Dear Corona-Warn-App developers, Open-Source-Team, community and everyone else who is involved in this project somehow, today we celebrate the second birthday of the Corona-Warn-App! 
Much has happened since [last years Birthday party](https://github.com/corona-warn-app/cwa-wishlist/issues/555), the Corona-Warn-App continued its transformation from contact tracing only to the "Schweizer Taschenmesser" for the COVID-19 pandemic.
Users are able to request EU DCCs for their test certificates, many features were implemented around the EU DCCs, local statistics, better contact journal, family member tests, and so on...

The team as well as the community did incredible work in the past 12 months and the Corona-Warn-App got even better!

The [scientific evaluation](https://www.coronawarn.app/de/science/2022-03-03-science-blog-5/) shows us that ca. 30,000,000 people are using the Corona-Warn-App, to get informed about risky exposures fast, inform themselves about local incidences, get their results of COVID tests, and so on. 

Now, at the moment, Corona seems to take a little break, at least politically. And to all of the team as well as the community and their loved ones, during this summer: Stay careful, stay healthy but allow yourself to take a break & enjoy the summer.

Now, all that's left to say: I'm very grateful to be part of this nice community, enjoy your stay in this issue!

Happy Birthday!🎂🎈🎉

**Comment by fynngodau** [comment]
Dear project members, dear community,

last year, [some of us](https://github.com/corona-warn-app/cwa-wishlist/issues/555#issuecomment-862661306) were hoping that we would be in a position to celebrate a well-justified "goodbye" before the project's second birthday.

Yet here we are, the project is still alive, so it deserves another party! :tada:

I today also want to express my appreciation for the timely launch of the certificate renewal feature, allowing new certificates to be issued before old ones would expire. Good job! I am looking forward to future forward-thinking updates throughout the coming year. :slightly_smiling_face: 

And thanks for hosting another amazing party, Tim! :partying_face: :wink:

**Comment by DanAmt** [comment]
Happy Birthday 🎊🎁🎈

**Comment by fynngodau** [comment]
Birthday party is over – New Year's Eve party is starting now at #873!
