### ISSUE TITLE
Add possibility to register a positive selftest 

### ISSUE THREAD

**Issue by janknieling** [corona-warn-app/cwa-wishlist#835]
## Feature description

It will be very nice to have the possibility to register a positive COVID-19 rapid selftest in the app to warn your contacts without a rapid test or PCR test from a test center.

## Problem and motivation

I think the benefits of this function is that people can warn there contacts if they are positive because the free „Bürgertests“ will expire soon

## Is this something you're interested in working on

No

**Comment by Ein-Tim** [comment]
Hey @janknieling,

thank you for raising this issue! I think this is a duplicate of #374, what do you think? 

If you agree with me, please close this issue. Thanks!

**Comment by Ein-Tim** [comment]
@thomasaugsten Can you please close this issue as a duplicate of #374? Thanks!
