### ISSUE TITLE
Don't block users from exporting single certificates if they are able to export all certificates

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#836]
## Current Implementation
Currently, in some cases (f.i. if the user wants to export an EU DCC which was not issued by Germany) the user gets an error message that the app can't export this certificate. However, if the user then uses the export all feature, which was shipped with version 2.24, the user is able to export all certificates, including these where the app stated that an export is not possible.

## Suggested Enhancement
Don't block certificate exports from single certificates if the user is able to export this certificate using the export all feature. 

## Expected Benefits
The user is not confused and it is easier to export the certificate. Also, this would add some logic to this part of the app :D

---
Internal Tracking ID: [EXPOSUREAPP-13474](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13474)

**Comment by larswmh** [comment]
Thanks for your enhancement request @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-13474](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13474)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
- PR https://github.com/corona-warn-app/cwa-app-android/pull/5491 resolves this issue under Android

**Comment by Ein-Tim** [comment]
- PR https://github.com/corona-warn-app/cwa-app-ios/pull/4763 resolves this issue under iOS

**Comment by Ein-Tim** [comment]
@mlenkeit Are you able to apply the `Fix 2.27` label to this issue?

**Comment by Ein-Tim** [comment]
Implemented!
