### ISSUE TITLE
Do not prompt user to take a PCR test after a positive RAT is registered if a positive PCR test was registered in the last days 

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#837]
## Current Implementation
If a user registers a positive PCR test in the app and after some days a positive RAT, the app recommends to take a PCR test to verify the result of the RAT. However, with near 100% certainty the positive RAT is a test the user took to end isolation ("Freitestung"). The user thus already knows he is infected from the positive PCR test and it is not necessary to take another PCR test. 

## Suggested Enhancement
Adapt the text:
"Take a PCR test to verify this test result."
if the user registered a positive PCR test in the app in the last days.

## Expected Benefits
Make clear statements which don't confuse users. This issue is actually based on the feedback from a user on Twitter which was confused by this and user if he needs to take another PCR test: https://twitter.com/KathrinBreer/status/1542869916600221696?s=20&t=xpsNZd4A91Q2_t9pPrB5Tw

---
Internal Tracking ID: [EXPOSUREAPP-13574](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13574)

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for suggestion. Will be forwarded.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

I assume you mean "Adapt the text:" not "Adopt the text:"

Adopt doesn't make sense, because the text is already part of the app.

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
