### ISSUE TITLE
Clear statement after exposure submission that others were warned

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#838]
## Current Implementation
Currently, the app only makes vague statements that others were warned after the "Warn others" process was finished successfully. Actually, the only thing I found was this message: "Thanks to your support, other people can now be warned and respond appropriately.".

## Suggested Enhancement
Make a clear statement whether others were already warned or not, like.
"The process to warn others was finished successfully and other people are now warned.".

## Expected Benefits
I wrote with quite a few users on Twitter via DM who were unsure if the app did warn others already, or if they still have to do anything. This is especially a problem if the app warned automatically in the background. 

---
Internal Tracking ID: [EXPOSUREAPP-13576](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13576)

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for the suggestion.

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
