### ISSUE TITLE
Make clear statement whether certificate needs to be renewed or not

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#839]
## Current Implementation
Currently, the app always shows the following text if a certificate is about to expire technically or is already expired.

> If this is one of the certificates you currently use, please be sure to renew it on time. You can renew such certificates directly in the app if they will expire within the next 28 days or expired within the last 90 days, provided they were issued in Germany. In this case, the “Renew Certificates” option appears in your certificate overview, below the “Proof of Status” tile. If this is not one of the certificates you currently use, it does not have to be extended and no action is required on your part.

## Suggested Enhancement
The app knows if a certificate is the currently used one or not, so it can make a clear statement whether to renew the certificate or not. Examples for texts:

**CASE 1: Multiple currently used certificates about to expire, need to be renewed:**

> This certificate is one of the certificates you currently use, please be sure to renew it on time. You can renew the certificates you currently use directly in the app if they will expire within the next 28 days or expired within the last 90 days, provided they were issued in Germany. In this case, the “Renew Certificates” option appears in your certificate overview, below the “Proof of Status” tile.

**CASE 2: One currently used certificate about to expire, needs to be renewed:**

> This certificate is the one you currently use, please be sure to renew it on time. You can renew the certificate directly in the app if it will expire within the next 28 days or expired within the last 90 days, provided it was issued in Germany. In this case, the “Renew Certificates” option appears in your certificate overview, below the “Proof of Status” tile.

**CASE 3: Certificate is not currently used, doesn't need to be renewed, multiple other certificates which are currently used:**

> This certificate is about to expire. As this is not one of the certificates you currently use, it does not have to be renewed and no action is required on your part.

**CASE 4: Certificate is not currently used, doesn't need to be renewed, one other certificate is currently used:**

> This certificate is about to expire. As this is not the certificate you currently use, it does not have to be renewed and no action is required on your part.

**It would certainly be easier to not consider whether there are multiple certificates currently in use or only one. That's for sure also possible.**

## Expected Benefits
Clearer communication, less confusion for the user. Better UX overall. 

---
Internal Tracking ID: [EXPOSUREAPP-13575](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13575)

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for suggestion. Will be forwarded.

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
