### ISSUE TITLE
Dashboard / statistics on recorded contacts

### ISSUE THREAD

**Issue by hanswurst13** [corona-warn-app/cwa-wishlist#84]
## Feature description

Provide some numbers / statistics around the activity of the app. It would be interesting to know the number of contacts that were recorded per day. 

## Problem and motivation

I think the feature could address two topics:
#### Information / Entertainment
I think we can all agree that currently the app is a bit boring 😏. It is not doing anything but sitting in the background and recording things that I cannot see. I would be really interested in getting more insight into the contacts that have been recorded by the app. The visualization could look similar to the Health app on iOS that shows you the number of steps per day. Only in this case the number of recorded contacts would be shown.

#### Drive behaviour of distancing
Providing the information on recorded contacts could lead to a changed distancing behaviour of the user. It could be seen as an incentive to reduce the number of contacts and keep the distance to others respectively.

## Is this something you're interested in working on

No

**Comment by hanswurst13** [comment]
I realized that this has already been discussed and is a duplicate.

**Comment by Novaal** [comment]
Relevant discussions are for example:

- https://github.com/corona-warn-app/cwa-app-android/issues/492
- https://github.com/corona-warn-app/cwa-app-ios/issues/678
- https://github.com/corona-warn-app/cwa-app-android/issues/570
- https://github.com/corona-warn-app/cwa-app-android/issues/518
