### ISSUE TITLE
Add link to CWA FAQ entry "TAN Procedure" to "Request TAN for PCR Test" screen

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#846]
## Current Implementation
Currently, the app does not link to the newly created FAQ entry "TAN Procedure" in the "Request TAN for PCR Test" screen.

## Suggested Enhancement
Add a link to the FAQ entry https://www.coronawarn.app/en/faq/results/#tan_procedure / https://www.coronawarn.app/de/faq/results/#tan_procedure to the screen.

## Expected Benefits
If the user has open questions or wants to find more details reg. the TAN process, they can easily find the relevant FAQ entry.

---
Internal Tracking ID: EXPOSUREAPP-13885

**Comment by MikeMcC399** [comment]
@Ein-Tim 

This is obsolete with CWA 3.0, since there is no longer a "Request TAN for PCR Test" option in the app.
