### ISSUE TITLE
Edit/delete names of places/people in the contact journal

### ISSUE THREAD

**Issue by WiseWomanVP** [corona-warn-app/cwa-wishlist#856]
## Avoid duplicates
* [x] This enhancement request has not already been raised before
* [ ] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

In the contact journal you can enter in names for people or places. However, if you happen to have the wrong keyboard currently active, after typing in a correct name ("Bio Company") it gets "corrected" to "Bin Company" by the keyboard between hitting "Done" and the name being stored. There is no way to correct or delete an entry, even one that is no longer needed for the past 14 days. 

## Suggested Enhancement

As in many other apps, I want to be able to press long on a name in the list and be able to correct the spelling. I also want to be able to delete names (as I now have 3 incorrect "Bin Company" entries as I was testing what happened).

## Expected Benefits

Helps me keep my list of people and places clean (I can delete or fix mistakes) and tidy. 

Internal Tracking ID: [EXPOSUREAPP-3034](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3034)
Internal Tracking ID: [EXPOSUREAPP-5495](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5495)

**Comment by Ein-Tim** [comment]
@mtwalli I think this issue can be closed, see the comments above.
