### ISSUE TITLE
Provide better app experience on Android foldable devices

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-wishlist#859]
## Avoid duplicates

* [X] This enhancement request has not already been raised before
* [X] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

[Will the app also be available on tablets, smart watches, and other wearables?](https://www.coronawarn.app/en/faq/#smartwatch) states:

"We don’t plan to implement the app for tablets, smart watches, and other wearables. Our focus is on smart phones, for example because of the availability of the required APIs."

https://github.com/corona-warn-app/cwa-app-android/blob/main/Corona-Warn-App/src/main/AndroidManifest.xml restricts the app to not rotate.

## Issue

The CWA app does not necessarily display optimally on foldable Android devices. 
- The app only displays in portrait mode. 
- Some screens do not work correctly on larger devices, see for instance https://github.com/corona-warn-app/cwa-app-android/issues/4203.

Some new foldables enable smartphones to have a larger display than previously available. For example https://www.gsmarena.com/samsung_galaxy_z_fold3_5g-10906.php 7.6 inches and 1768 x 2208 pixels. The larger foldable devices are similar to tablets which the FAQs says the app has not been specifically developed for.

Reference: [Learn about foldables](https://developer.android.com/guide/topics/large-screens/learn-about-foldables).

## Suggested Enhancement

1. Make sure that the app behaves well on larger screens. 
2. Allow the app to display rotated.

## Expected Benefits

Provide a better experience for users of larger foldable Android devices.

**Comment by MikeMcC399** [comment]
For example on an unfolded 8" fold-out device the Data Privacy model's head is cut off:

![image](https://user-images.githubusercontent.com/66998419/158818952-d8520439-5b0a-467d-944f-f536bbe989b3.png)

Compare this with the display in flipped (folded) state:

![image](https://user-images.githubusercontent.com/66998419/158819209-0e038fc7-22ff-4373-bb14-dee6bb9de6a6.png)

**Comment by MikeMcC399** [comment]
@dsarkar 
This doesn't seem to have been mirrored to Jira. Would you like to do this please?

**Comment by mtwalli** [comment]
This topic is also related to tablets and allowing different orientations in the App which should be also supported in iOS world

**Comment by Ein-Tim** [comment]
@mtwalli The app is not available on iPads. This is an Android exclusive request. Please move it back to the Android repo.

Allowing the app to be used in landscape is not the point of this issue, right @MikeMcC399?

**Comment by mtwalli** [comment]
@Ein-Tim it is true that iOS does not have foldable devices, but Foldable devices have both Large and Small screen on the same device. Improving experience for Large screens falls in the same category and different orientations have to be allowed too.

**Comment by Ein-Tim** [comment]
I think @MikeMcC399 should state if it is OK for him to move this here.

**Comment by mtwalli** [comment]
@Ein-Tim  For me to understand , is not every new feature request should be in the `wishlist` also ? this point is also mentioned in the template https://github.com/corona-warn-app/cwa-app-android/blob/main/.github/ISSUE_TEMPLATE/02_enhancement.md 
> If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

**Comment by Ein-Tim** [comment]
@mtwalli Only feature requests that concern both, iOS & Android should be in the wishlist according to my knowledge.

Opening a new Enhancement request issue in the [iOS repo](https://github.com/corona-warn-app/cwa-app-ios/issues/new/choose) shows this as the first point under the "Avoid duplicates" section:

* [ ] Enhancement request is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

Maybe the README should be adopted? I could provide a PR for this.

**Comment by Ein-Tim** [comment]
I think there is the differentiation between
- feature requests
- enhancement requests.

While feature requests request new features (e.g. a button to increase brightness on the "Certificates" tab), an enhancement reutest requests enhancement for e.g. the usability of the app on specific devices.

As, in general, there is feature parity between iOS & Android, new feature requests should always be opened in the wishlist, as implementation should be considered for both OSs.
Enhancement requests however may be limited to one of the both OSs (due to different design, devices, etc.).

**Comment by MikeMcC399** [comment]
@mtwalli / @Ein-Tim 

Regarding the previous comments:

This enhancement request is purely for Android foldables. It could be extended to cover Android tablets and iOS tablets, but this is not in the description. I have added the checklist from the template to the OP to be clear that this is Android only.

I considered this to be an enhancement request, but since it would be a significant change to implement the request on Android, the developers may want to define it as a feature request. See [Android developers: Learn about foldables](https://developer.android.com/guide/topics/large-screens/learn-about-foldables).

**Comment by mtwalli** [comment]
@MikeMcC399 , @Ein-Tim  Thanks for referencing the docs here, that is exactly what I'm talking about. Supporting foldable devices is not a small change ,but we will require to visit and adapt each and every screen to look good on small and large screens. it we design anyway for large screens it means that we can support tablets anyway out of the box and also enabled different orientations. iOS is not excluded  in this case and it should adapted as well. it is not an enhancement that can be done by the Android team only but rather whole team should be involved mainly UX team to make sure both platforms are aligned. I hope it is clear now.

Quote from  Android docs:
> For example, a large-screen foldable device unfolded in landscape orientation is like a tablet; a two-pane layout with a navigation rail makes excellent use of the wide screen. Folded, the device is similar to a standard phone; a single column layout with a bottom navigation bar is simple but effective. Because the layouts are separate, you can optimize each for its specific use case.

**Comment by Ein-Tim** [comment]
Yep, it is, thanks @mtwalli!

**Comment by MikeMcC399** [comment]
- Note also overlap with the wishlist item https://github.com/corona-warn-app/cwa-wishlist/issues/848
