### ISSUE TITLE
Wrong Vaccination Status for children

### ISSUE THREAD

**Issue by Th-St** [corona-warn-app/cwa-wishlist#862]
## Current Implementation

If a person has 2 vaccinations the app shows that the vaccination would not be complete regardless of the person's age.

## Suggested Enhancement

If the birthday of the person is less than 12 years ago, the app should show that the person is fully vaccinated with 2 vaccinations. The third vaccination is only mandatory for persons which are 12 years or older. 

## Expected Benefits

Correct display of the current legal situation also for children who are less than 12 years old.

---
Internal Tracking ID: [EXPOSUREAPP-14023](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14023)

**Comment by MikeMcC399** [comment]
- See https://github.com/corona-warn-app/cwa-app-ccl/issues/83#issuecomment-1155070469 which says that there is no age distinction in the legal text [IfSG § 22a](http://www.gesetze-im-internet.de/ifsg/__22a.html). This is the legal situation, which is different to the medical recommendations from the [STIKO](https://www.rki.de/DE/Content/Infekt/Impfen/ImpfungenAZ/COVID-19/Impfempfehlung-Zusfassung.html), e.g. [21. Aktualisierung der COVID-19-Impfempfehlung](https://www.rki.de/DE/Content/Infekt/EpidBull/Archiv/2022/Ausgaben/33_22.pdf?__blob=publicationFile).

**Comment by Th-St** [comment]
Sorry!
You are right. There is no recommendation that children should get a third vaccination if they are healthy, but they need it to be legally fully vaccinated.
