### ISSUE TITLE
Add link to "Corona-Impfcheck" from Infektionsschutz.de to certificates

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#864]
## Feature description

The Bundeszentrale für gesundheitliche Aufklärung (BZGA) published a tool which quickly surveys the user on their immune protection against Sars-CoV-2 & gives (booster) vaccination recommendations based on the answers the user gave.
Here's a link to the tool: https://www.infektionsschutz.de/coronavirus/schutzimpfung/der-corona-impfcheck (it seems to be only available in German).

I request to add a link to this page to the person overview screen, so that users can always check if there is a recommendation for a (booster) vaccination. 

## Problem and motivation
Currently, the app sends booster notifications, however, the app can't take into account e.g. recoveries which can't be documented anymore or the overall health status of a person. Adding a link to this tool would help the user and deliver a more accurate result. 

---
Internal Tracking ID: [EXPOSUREAPP-14107](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14107)

**Comment by larswmh** [comment]
Thanks for your feature request @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-14107](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14107)

---
Corona-Warn-App Open Source Team

**Comment by larswmh** [comment]
@Ein-Tim would you think adding this to the FAQ, which is linked to in the Certificates tab of the app, would make sense? I wouldn't rule out that it will be implemented directly into the app, but think it's much more likely to be implemented in the FAQ and would forward it if you agree with me

**Comment by Ein-Tim** [comment]
@larswmh 

Adding this to the FAQ seems like a good idea, but as we all know most users never make their way to the FAQ, a direct link in the app would be best (-:

But for sure, go ahead and add it to the FAQ. 

The FAQ entry https://www.coronawarn.app/en/faq/#vac_status seems like a good place for this.

**Comment by dsarkar** [comment]
@Ein-Tim the FAQ you mention is directly linked from the app in the "vaccination status" info box. So, indirectly via the FAQ article a user could reach that webpage.

![image](https://user-images.githubusercontent.com/1409741/194893002-cffcbeec-6408-4dc1-9e18-4e2ac89cc642.png)

**Comment by Ein-Tim** [comment]
@dsarkar

Yes, that's why I suggest to add the link to this FAQ entry (-:

If you want to, I can provide a PR for this in the website repo.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks, PR will be appreciated, however, we need to get first feedback that such a change is accepted.

**Comment by Ein-Tim** [comment]
@dsarkar Ok, just shoot me a comment here and I will provide a PR.

**Comment by dsarkar** [comment]
@Ein-Tim PR would be merged. Do you still want to provide it? Thanks.

**Comment by Ein-Tim** [comment]
@dsarkar PR will follow in the due course of this week.

**Comment by Ein-Tim** [comment]
I'll start working on this today, expect a PR on the weekend.

**Comment by Ein-Tim** [comment]
- PR https://github.com/corona-warn-app/cwa-website/pull/3141 provided.

**Comment by Ein-Tim** [comment]
A link was added to the FAQ. That's a good start. 👍

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect to see any bigger features implemented. I'm therefore closing this issue.
