### ISSUE TITLE
Add explanation of vaccination statistic terms to the app

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#866]
## Current Implementation
The CWA includes the following statistics, among others, on vaccination:

- "People Who Have Received at Least One Vaccine Dose" ("Mindestens eimal geimpfte Personen")
- "People Who Have Basic Immunization" ("Grundimmunisiert")
- "People Who Have Received a Booster Vaccination" ("Personen mit Auffrischimpfung")

The used terms are nowhere defined in the app. For example, the user can't tell if "People Who Have Basic Immunization" includes all people who have received two shots or three. 

## Suggested Enhancement
Add the definitions of these terms to the apps statistics information screen. The terms are defined by STIKO, the definition is for example available in this document: https://www.rki.de/DE/Content/Infekt/EpidBull/Archiv/2022/Ausgaben/40_22.pdf?__blob=publicationFile.

## Expected Benefits
The user finds explanation on relevant statistics directly in the app.

## Additional information
1. I'm opening this issue based on feedback I received via Twitter, however, I also support this request. Here's the link to Twitter: https://twitter.com/longvaccvoyager/status/1583480974985158658?s=20
2. This is a follow-up to https://github.com/corona-warn-app/cwa-documentation/issues/922

---
Internal Tracking ID: [EXPOSUREAPP-14221](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14221)

**Comment by dsarkar** [comment]
Good morning @Ein-Tim, thanks for the suggestion. Internal Tracking ID: [EXPOSUREAPP-14221](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14221)

**Comment by MikeMcC399** [comment]
Assuming that the immunization data displayed in the CWA statistics tiles has the same source as https://github.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland then the exact definitions are on https://github.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland#erkl%C3%A4rung-zum-merkmal-impfstatus.

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect to see any bigger features implemented. I'm therefore closing this issue.
