### ISSUE TITLE
Add information to positive test result that this is not a certificate of recovery

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#867]
## Current Implementation
Registered positive tests currently stay in the app for an unlimited period of time. Also, the information on the positive test result doesn't mention the fact that the positive test result in the CWA is **not** a certificate of recovery.

## Suggested Enhancement
The information presented to the user should include a paragraph reg. the certificate of recovery. Something like this would be good:
"Bitte beachten Sie, dass das hier angezeigte positive Testergebnis nicht als Nachweis über eine Genesung von Corona verwendet werden kann. Um eine durchgemachte Infektion nachzuweisen, benötigen Sie ein Genesenenzertifikat. Sollten Sie bereits ein Genesenenzertifikat haben, scannen Sie es bitte mit dem QR-Code-Scanner. Es wird Ihren dann unter dem Reiter 'Zertifikate' angezeigt."

## Expected Benefits
There are quite a few users on Twitter who leave their positive test result in the CWA because they think this is a way to prove that they recovered from Corona. 
Some examples:
- https://twitter.com/DanaScullyyy/status/1586410717401317376?s=20
- https://twitter.com/NessySheep/status/1544384150345584640?s=20

---
Internal Tracking ID: [EXPOSUREAPP-14287](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14287)

**Comment by dsarkar** [comment]
Hi @Ein-Tim, thanks you very much for this interesting suggestion and providing examples from twitter. Internal Tracking ID: [EXPOSUREAPP-14287](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14287)

Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect to see any bigger features implemented. I'm therefore closing this issue.
