### ISSUE TITLE
Make difference between positive test result & certificate of recovery more clear

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#868]
## Current Implementation
Currently, some users find it quite hard to understand the difference between a
- certificate of recovery and a
- positive test result
in the app.

Questions I saw on Twitter include:
"Do I really need to go to a pharmacy to get a QR code [certificate of recovery] to warn others via the app?",
"Why is there no certificate of recovery for the positive test result in the app?"

## Suggested Enhancement
Find a way to make the difference between a certificate of recovery & a positive test result more clear.

## Expected Benefits
Less confused users.

Some examples from Twitter: 
- https://twitter.com/J__Ludwig/status/1580844037283930112?s=20
- https://twitter.com/LutzStaacke/status/1578426290704875520?s=20
- https://twitter.com/Kandisbunzler/status/1581176759189639170?s=20

---
Internal Tracking ID: [EXPOSUREAPP-14287](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14287)

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for opening this issue. I understand that your suggestion https://github.com/corona-warn-app/cwa-wishlist/issues/867 is a possible implementation of this issue here, correct?

**Comment by Ein-Tim** [comment]
@dsarkar Yes, that would be one way.

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect to see any bigger features implemented. I'm therefore closing this issue.
