### ISSUE TITLE
Display a downloadable/printable pdf version of the PCR-Test

### ISSUE THREAD

**Issue by robinduerhager** [corona-warn-app/cwa-wishlist#869]
## Feature description
Currently, when having a positive PCR-Test, the tests status only gets stored in the app for 21 days. When you click on the PCR Test, you just get some more details about how to best behave in such a situation. Though, when having a positive or negative test, some might want to print the original test report out for backup purposes and in case someone needs to show that the person had an immunulogical event with COVID. Therefore a `print` button after clicking on the PCR-Test would be helpful.

## Problem and motivation
The problem is, that not everybody gets a link to some pdf for the test result but might need some print version of it for some use case. There are also so many different portals on which you might get your test result but also might not. The CWA being the single source of truth for printable test results could help out a lot with this issue.

## Is this something you're interested in working on
No, i sadly don't have the time to dig into this project :( though i hope you are willing to implement this feature request :).

---
Internal Tracking ID: [EXPOSUREAPP-12624](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12624)

**Comment by Ein-Tim** [comment]
Hey @robinduerhager!

Thank you for this feature request! Could you please have a look at the following to issues and check if your proposal is sufficiently covered by them? If yes, I'd suggest you monitor these issues for update and close this one. Thanks!

- https://github.com/corona-warn-app/cwa-wishlist/issues/821
- https://github.com/corona-warn-app/cwa-wishlist/issues/822

Especially #822 seems to be quite an exact duplicate of this issue.

**Comment by dsarkar** [comment]
Hi @robinduerhager, 

thanks for your suggestion; see comment https://github.com/corona-warn-app/cwa-wishlist/issues/869#issuecomment-1301490319 from @Ein-Tim.

Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by robinduerhager** [comment]
Hi @dsarkar and @Ein-Tim thanks for the quick reply.

Actually, both issues cover mine well, #822 even very precisely, though i would want to extend this one with being able to download the test result / labor report regardless of the test status.

I will close this issue and create a Comment at #822 :). Thank you for pointing me in the right direction, it seems like i typed in the wrong keywords during my search.
