### ISSUE TITLE
GitHub: Commands for the cwa-bot

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#870]
## Feature description
It would be great to add commands for the cwa-bot, so that the community can help keeping the CM board up to date. 

I imagine a command like:
```
@cwa-bot move to "$CATEGORY"
```

"$CATEGORY" must be replaced with one of the following:
- "ToDo"
- "In Progress"
- "Waiting for Input"
- "Mirrored to Jira"
- "Done"

## Problem and motivation
Currently, the cwa-bot has moved many issues into the "ToDo" category, although there is actually nothing left to do, but e.g. I just edited the comment I wrote before closing the issue. This is only one case where such a "false sorting" can happen, looking at the "ToDo" column here in the cwa-wishlist repository ([Link](https://github.com/corona-warn-app/cwa-wishlist/projects/1#column-11716982)), I think there are many many issues which should be in other categories.

## Is this something you're interested in working on

For sure, just let me know how I could help!

**Comment by brianebeling** [comment]
I'm not quite if anyone is actively using the board. With JIRA and our internal task management its quite obsolete now and feels more like "another board to maintain". Even though I doubt such a feature would be abused, it could still absolutely be abused and is unlikely to be implemented.

Thank you for the offer though, we greatly appreciate your help!

**Comment by Ein-Tim** [comment]
@brianebeling If the board is not used anymore, I suggest deleting the project and shut-down the cwa-bot. Should I open a new issue regarding this?

**Comment by brianebeling** [comment]
Hey Tim. Don't worry about it for now, first I have to find out if anyone is using the board actively. Thank you for the offer though, if you want I can come back to you. It'd probably be quicker to discuss it internally and then taking action directly.

**Comment by Ein-Tim** [comment]
@brianebeling Makes sense! If you have any questions/follow-up information, you can also contact me via Slack DM! Thank you and have a nice Sunday!
