### ISSUE TITLE
Version 3.0: Do not show how long the app needs to be installed before a SRS warning can be issued

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#871]
## Upcoming Implementation

If the user just installed the app and tries to warn others with a SRS test, the app will show that a warning can not yet be issued and that the app needs to be installed for at least x days/hours. 

## Suggested change to the upcoming implementation
I **strongly** suggest to not show how long the app needs to be installed until a SRS warning can be issued, as this might encourage trolls to leave the app installed, because they have a clear goal in front of their eyes when they can troll other users. If the app doesn't give them a goal, but only informs the user that a SRS warning can't be issued at that point of time, I'm quite sure that many trolls will give up and uninstall the app again. 

## Expected Benefits
In my opinion, this change could drastically reduce the number of trolls who install the app just to warn others, although they are not positive.

## Related issue
- https://github.com/corona-warn-app/cwa-wishlist/issues/872

---
Internal Tracking ID: [EXPOSUREAPP-14519](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14519)

**Comment by dsarkar** [comment]
Good Morning @Ein-Tim, 

Thanks for the suggestion, Internal Tracking ID: EXPOSUREAPP-14519.

**Comment by Ein-Tim** [comment]
Good morning @dsarkar!
Thanks for the fast mirror! Appreciate it! ❤️

**Comment by Ein-Tim** [comment]
@larswmh 

I have the feeling this issue was taken into account when the texts for https://github.com/corona-warn-app/cwa-website/pull/3322 were written. Is there any update reg. the texts in the app available?

**Comment by larswmh** [comment]
@Ein-Tim 

From what it looks like right now, the app won't show how long you need to have it installed before you can warn. It will only show you how long you have to wait to warn again. To be safe, this has been forwarded and I hope to be able to come back to you soon.

We certainly knew about this issue by the time we were working on the texts, but it's hard to tell how much it has surfaced internally to the point where it would potentially change it up in the app itself. I can imagine that the app development team might have seperately thought about this aspect as well.

**Comment by Ein-Tim** [comment]
@larswmh 

> To be safe, this has been forwarded and I hope to be able to come back to you soon.

Thank you very much!

**Comment by dsarkar** [comment]
@Ein-Tim Actually, it will show the minimum time the app has to be installed before a SRS warning can be issued. Currently it is not considered to be a problem.

**Comment by Ein-Tim** [comment]
Okay, I'll still leave this issue open. After version 3.0 has been released I'm considering CWA to be in ramp down mode and will re-assess all my open issues again and close those that are no longer relevant.

**Comment by Ein-Tim** [comment]
Perfect example of why, giving the trolls an exact amount of time: https://twitter.com/twoedel/status/1616545905553072128?s=20&t=c3YIum6pUxcdc94hZS-p1w
Without a clear goal, I'm sure the user would just give up and uninstall the app.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for forwarding the tweets.

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
