### ISSUE TITLE
Version 3.0: Increase time until a SRS warning can be issued after the app installation

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#872]
## Upcoming Implementation
With version 3.0, it will be possible to warn other users without having to scan a QR code or call the hotline to get a TAN to warn others, but a warning can be issued simply by clicking some buttons in the CWA. There is a period of time implemented in the mobile apps which hinders users from issuing such a SRS warning if the app hasn't been installed for a given amount of time (Please note that I think this amount of time is security relevant, and I'm thus not exposing the value).

## Suggested change to the upcoming implementation
 I think the value which has been chosen for the upcoming implementation is too short, the amount of time should be increased by at least two days.

## Expected Benefits
In my opinion, this change could drastically reduce the number of times when trolls are able to issue a SRS warning, although they are not tested positive. Especially in combination with https://github.com/corona-warn-app/cwa-wishlist/issues/871 this would be a good change and would make the implementation even more bullet-proof against trolls.

## Related issue
- https://github.com/corona-warn-app/cwa-wishlist/issues/871

---
Internal Tracking ID: [EXPOSUREAPP-14520](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14520)

**Comment by dsarkar** [comment]
Good Morning @Ein-Tim, 

Thanks for the suggestion, Internal Tracking ID: EXPOSUREAPP-14520.

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
