### ISSUE TITLE
Silvester Party! 🎉

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#873]
Dear Corona-Warn-App developers, dear Open-Source-Team, dear community and everyone else who is involved in this project somehow, I want to wish you a happy new year. Also, we take a look back on what we achieved with the Corona-Warn-App in the year 2022!

In 2022 
- we [found out](https://www.coronawarn.app/en/science/2022-03-03-science-blog-5/) how many active users the Corona-Warn-App has
- the milestone of more than 8,000,000 issued warnings over the CWA was reached
- the “Status-Nachweis” was [integrated into the app](https://www.coronawarn.app/de/blog/2022-01-17-cwa-2-16/), which helped users guide through complicated entry rules
- the translations & dev team [rushed to integrate](https://www.coronawarn.app/de/blog/2022-03-30-cwa-2-20/) Ukrainian translation into the app after the war began
- it finally [became possible](https://www.coronawarn.app/de/blog/2022-04-19-cwa-2-21/) to register more than one test in the app
- the team [came up](https://www.coronawarn.app/de/blog/2022-06-01-cwa-2-23/) with a great implementation for easy certificate renewal
- the COVID-19 situation in Germany changed, [so did the app](https://www.coronawarn.app/de/blog/2022-07-27-cwa-2-25)

But 2022 was so much more than that. We waved goodbye to great developers and team members, who left the project and said hello to new faces. We celebrated the second birthday of the Corona-Warn-App (https://github.com/corona-warn-app/cwa-wishlist/issues/833) and we watched as COVID-19 restrictions were lifted and a somewhat normal life returned.
Thank you to the great community that remained here on GitHub and thanks to the great Open-Source-Team, which is always available if we need help! And for sure also a big big thank you to the whole development team and everyone else working on this app behind closed curtains!

To everyone reading this & their loved ones: Stay healthy, enjoy today & see you in 2023! 🎇

<img src="https://user-images.githubusercontent.com/67682506/147829389-6c10fa37-3f27-45c3-8197-8f867b3026b5.gif" width="1000">

Feel free to comment below & say thank you!

**Comment by fynngodau** [comment]
I wish everyone a happy new year in advance – even if it may be CWA's last 🥲

**Comment by dsarkar** [comment]
Dear @Ein-Tim, dear @fynngodau, dear community!

Thank you for the wishes and very nice words you found to summarise the year 2022. 

And of course, not to forget, you, the community was and still is a substantial part of this project with all your activity and inputs you had and have to offer, say suggestions/ideas/proposals, feedback and reviews, bug reporting and analysing, also asking questions, helping other users with their issues, and a lot more ..., which you do not only here but also by spreading the word, using your knowledge, assisting, forwarding feedback, etc, on other platforms! 

We think that the participation of you, the community, plays an important role in the success and acceptance of this project.

So, to join your wishes, all the best to you and your loved ones!


---
Corona-Warn-App Open Source Team

**Comment by ndegendogo** [comment]
Dear development team,
thanks a lot for another year of your hard and dedicated work on cwa. The app has us accompanied through 2 1/2 year of the pandemy now. It was one of the earliest countermeasures availabe; long before the vaccination; and long before you could buy self-tests everywhere.
Hopefully the experts are right who tell us that next year the pandemy will be ... well, not over, and not harmless, but it will loose its exceptional horror and be a "normal" disease like many others ... and hopefully we can then send cwa into retirement ...

I wish you all a happy new year, with new and exciting projects! 🎉🎉🎉🚀🚀🚀

Stay healthy - stay safe! 🍀🍀🍀

**Comment by Qli1** [comment]
I would like to say thank you and wish everyone a happy new year 2023

**Comment by WolfgangScheida** [comment]
Thanks dear Tim for your engagement and your support! 🚀

**Comment by DanAmt** [comment]
Thanks all for your great work. Have a good time in the new year! 🎊🤩

**Comment by brianebeling** [comment]
Thank you all for the nice words and great work, and also thanks Tim for the post! I think @dsarkar already said everything. This project has so much variety and felt really fullfiling working on. It played an important part in the fight against Corona. I'm exited to see where this will go in 2023 and what more we will archive as a community. Thank you all for being a part of it.

I wish you all the best in the new year. 🥳

**Comment by fynngodau** [comment]
Silvester party is wrapping up. But do not worry, there is no need to stop partying: the farewell party is just getting started over at #878!

**Comment by Ein-Tim** [comment]
Silvester's over, farewell party's now live over at #878.
