### ISSUE TITLE
No new features planned?

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-wishlist#876]
My understanding is that the CWA project is in ramp-down mode and that there will be no new features in the next app version 3.1.

If that is definitely the case, then the README etc. should be updated to avoid disappointment, since it still suggests that this repository is open for suggestions and, by implication, that there is some likelihood that a community suggestion could be implemented in a future app version.

**Comment by GisoSchroederSAP** [comment]
@MikeMcC399 , even with the likelihood of another disappointment: At this current point of time we _will_ proceed with usual community work. This also includes the open repository for suggestions - everything here still remains a valuable resource, at least for retrospective project activities.

**Comment by MikeMcC399** [comment]
I withdraw this request, since there was never any general promise in this repository that wishlist items would be implemented. It is entirely up to the product owners what they decide.

I note however that in practice all the enhancement requests from the [corona-warn-app/cwa-app-android](https://github.com/corona-warn-app/cwa-app-android) repository have now been closed. See [enhancement list search](https://github.com/corona-warn-app/cwa-app-android/labels/enhancement) showing 0 Open and 446 Closed.

**Comment by MikeMcC399** [comment]
- See issue https://github.com/corona-warn-app/cwa-wishlist/issues/877
