### ISSUE TITLE
Provide more helpful update messages

### ISSUE THREAD

**Issue by zhedar** [corona-warn-app/cwa-wishlist#90]
This concerns mostly the mobile applications.

I couldn't look up the changelog on the Play Store, but the change messages on iOS are not really helpful. 
"kleinere Verbesserungen" doesn't say anything at all. Better specify, what bugs you squashed or what enhancements you've implemented.

One way to do this, is just to list the fixed issues and / or merged PRs on GitHub. If they are tagged with the release they went into, this should be pretty straightforward.

I would view such an action as a transparency plus, which fortifies trust in the app.

![IMG_5423](https://user-images.githubusercontent.com/6633403/86294120-3e4efe00-bbf4-11ea-86bf-7ed7426b9074.jpg)

----------
Internal tracking Id: EXPOSUREAPP-2105

**Comment by jkrwdf** [comment]
On iOS, the most recent update contained information:

> 1.0.4   03.07.2020
> Dieses Update behebt das Problem, dass auch bei kurzer Deaktivierung der App innerhalb der letzten 14 Tage nur 13 von 14 Tagen angezeigt werden.


Todays Android update still does not:

> 1.0.5  07.07.2020
> NEUE FUNKTIONEN
> Kleinere Verbesserungen
> 

Especially as the Android version is right now under scrutiny (number of days and rate limit issue) it would have been helpful to see what was fixed in 1.0.5.

**Comment by SonaliDK** [comment]
Hi @zhedar,

Thank you for your proposal. All issues in the cwa-wishlist repository will be discussed with our contracting entities. They will decide whether they will be implemented or pursued further. As soon as we have any updates, we will let you know about the details.

Best regards,

SD

Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
There are now better update messages so I think this can be closed

**Comment by zhedar** [comment]
Yep, since 1.0.4 I'm fairly happy with those. Thanks!
