### ISSUE TITLE
[UI] Launchscreen

### ISSUE THREAD

**Issue by tens0rfl0w** [corona-warn-app/cwa-wishlist#92]
## Avoid duplicates

* [x] This issue has not already been raised before
* [x] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Suggested Enhancement

The launch time of the app is quite low, but in certain circumstances, it can happen that the launch takes some seconds. To improve the user journey from the beginning on, I would add the CWA logo to the launch screen. Maybe just copying the layout and style of the privacy protection window. A top up would be to add the navbar in the launchscreen, this is a little bit „old“ practice, but maybe it fits. Currently it is just blank and not really „pretty“.

----------
Internal Tracking Id: EXPOSUREAPP-2103

**Comment by Blackjacx** [comment]
Uff really, the iOS launch screen is white! If this issue is free I would like to work on that with pleasure 🙃

**Comment by dsarkar** [comment]
Hi @tens0rfl0w, @Blackjacx. Thanks for your contributions.  This seems to be resolved, and in that case I would suggest closing this issue. Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Hi @tens0rfl0w, @Blackjacx. Thanks again for your contributions. This seems to be resolved, We will close this issue now. 

Best wishes,
DS

Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
There are still some circumstances where the launch screen is empty... But I think these are edge cases, in general there is now the Logo shown 👍
