### ISSUE TITLE
„Datenschutzinformation“ (privacy info)

### ISSUE THREAD

**Issue by PhluMolto** [corona-warn-app/cwa-wishlist#95]
For greater acceptance:
That comprehensive „Datenschutzinformation“ (to be read before activating the app) in the German iOS app should urgently be made available for D/L eg as a pdf, for the user to be able to read it offline, eg on a bigger screen! Otherwise people who care about their privacy will stop at that point, either removing the app or keeping it inactive!

**Comment by tkowark** [comment]
Just stumbled across the older Android issue, which is now part of the wishlist as #96 . Hence, we'll close this issue.
