### ISSUE TITLE
Link zum PDF der Datenschutzerklärung in App einbinden (+Historie)

### ISSUE THREAD

**Issue by gizmo21** [corona-warn-app/cwa-wishlist#96]
## Current Implementation
Aktuell ist in der App nur die eingebettete Datenschutzerklärung / Nutzungsbedingung vor.
Diese kann auch nicht mit Screenshots gesichert werden.

Es gibt zwar eine PDF-Ausgabe aber weder ist der Link in der App noch habe ich ihn als Verlinkung auf der Webseite gefunden. 
https://www.coronawarn.app/assets/documents/cwa-privacy-notice-de.pdf

## Suggested Enhancement
Bei jedem App-Dialog, bei dem man der aktuellen Datenschutzerklärung/Nutzungsbedingungen zustimmen muss (was ggf. auch bei Versionsupdate erfolgen sollte - HINT), sollte man die aktuell gültigen Versionen als PDF herunterladen können um zu sichern was man zu einem Zeitpunkt X zugestimmt hat.
Zudem sollte eine Historie der PDFs auf der Webseite mit Link in der App angelegt werden.
Bestenfalls mit Änderungsangaben (nice-to-have).
Versions-Datum ist ja zumindest bei der DSE schon vorhanden.  

## Expected Benefits
Da es einerseits um Gesundheitsdaten geht sollte jeder der will zumindest dokumentieren können was er da genau zustimmt und welche Änderungen es gab.
Leider kam es in der Vergangenheit auch bei PPP-Projekten (LKW-Mautdaten) schon zu Forderungen nach Ausweitung der ehemaligen Zweckbindung, Datennutzung weshalb zumindest die Möglichkeit der Dokumentation schön wäre.

---------------
Internal Tracking Id: EXPOSUREAPP-2102

**Comment by tkowark** [comment]
Thank you for the suggestion. We received a similar one for iOS and will discuss them both with the product management team. As linked above, the documents are also part of the website:

* https://www.coronawarn.app/assets/documents/cwa-privacy-notice-de.pdf
* https://www.coronawarn.app/assets/documents/cwa-eula-de.pdf

**Comment by PhluMolto** [comment]
Good for a broader acceptance of that app. Generates trust. And trust is needed urgently!

**Comment by Ein-Tim** [comment]
Kleines Update hier: 

Die Datenschutzerklärung auf der Website wird in den Nutzungsbedingungen erwähnt: 
<img src="https://user-images.githubusercontent.com/67682506/125984741-6fa572d3-96bd-477f-8e80-9dd64f96fee6.jpeg" width="300">

Auf der Webseite wurde ein Archiv der alten Datenschutzerklärungen angelegt: https://www.coronawarn.app/de/privacy/

**Comment by MikeMcC399** [comment]
@dsarkar 

This issue has the label "ready-to-close" attached to it and the comment https://github.com/corona-warn-app/cwa-wishlist/issues/96#issuecomment-881597049 from @Ein-Tim answers the issues as they were originally described.

Is there some reason this issue is still open or can it be closed?

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for pinging me. I usually leave it to the author to close the issue. In this case, it has been a long time, so we can close that one.
