### ISSUE TITLE
US App Store availability

### ISSUE THREAD

**Issue by rknLA** [corona-warn-app/cwa-wishlist#99]
I appreciate that there are legal concerns about releasing this app outside of Germany, but COVID-19 knows no borders and does not care which App Store a person uses.

My request is for the US, as that’s what I personally need, but how many hoops are you going to make immigrants from other countries jump though before they can participate in keeping all of Germany safe?

**Comment by szhorvat** [comment]
This has already been asked https://github.com/corona-warn-app/cwa-wishlist/issues/41
